const translates = {
	sixiang: "Tứ Tượng Phong Ấn",
	std_sunhao: "Chuẩn Tôn Hạo",
	std_sunhao_prefix: "Chuẩn",
	std_mateng: "Chuẩn Mã Đằng",
	std_mateng_prefix: "Chuẩn",
	std_mayunlu: "Chuẩn Mã Vân Lộc",
	std_mayunlu_prefix: "Chuẩn",
	std_jianggan: "Chuẩn Tương Cán",
	std_jianggan_prefix: "Chuẩn",
	std_zhouchu: "Chuẩn Chu Xử",
	std_zhouchu_prefix: "Chuẩn",
	std_lvlingqi: "Chuẩn Lã Linh Kỵ",
	std_lvlingqi_prefix: "Chuẩn",
	std_dc_yanghu: "Chuẩn Dương Hỗ",
	std_dc_yanghu_prefix: "Chuẩn",
	std_dc_luotong: "Chuẩn Lạc Thống",
	std_dc_luotong_prefix: "Chuẩn",
	std_lijue: "Chuẩn Lý Quắc",
	std_lijue_prefix: "Chuẩn",
	std_chengpu: "Chuẩn Trình Phổ",
	std_chengpu_prefix: "Chuẩn",
	std_db_wenyang: "Chuẩn Văn Ương",
	std_db_wenyang_prefix: "Chuẩn",
	std_re_dengzhi: "Chuẩn Đặng Chi",
	std_re_dengzhi_prefix: "Chuẩn",
	std_zhangyì: "Chuẩn Trương Dực",
	std_zhangyì_prefix: "Chuẩn",
	std_chengyu: "Chuẩn Trình Dục",
	std_chengyu_prefix: "Chuẩn",
	std_fanyufeng: "Chuẩn Phàn Ngọc Phượng",
	std_fanyufeng_prefix: "Chuẩn",
	std_feiyi: "Chuẩn Phí Y",
	std_feiyi_prefix: "Chuẩn",
	stdcanshi: "Tàn Thực",
	stdcanshi_info: "Kỹ năng khóa, giai đoạn Bốc Bài, bạn đổi thành bốc X lá bài (X là số nhân vật đã bị thương trên bàn và X ít nhất là 1). Sau đó trong lượt này, sau khi bạn dùng 【Giết】 hoặc bài chú thông thường chỉ định mục tiêu, nếu người đó đã bị thương, bạn bỏ một lá bài.",
	stdxiongyi: "Hùng Dị",
	stdxiongyi_info: "Kỹ năng giới hạn, giai đoạn Xuất Bài, bạn có thể chọn một số nhân vật bất kỳ, những nhân vật này lần lượt chọn có sử dụng một 【Giết】 không thể bị đáp trả hay không, sau đó những nhân vật này lặp lại quy trình này cho đến khi có nhân vật không sử dụng 【Giết】.",
	stdyouji: "Du Kỵ",
	stdyouji_info: "Kỹ năng Chủ Công, giai đoạn Chuẩn Bị, bạn có thể di chuyển một lá bài Tọa Kỵ của một nhân vật thế lực Quần.",
	stdfengpo: "Phượng Phách",
	stdfengpo_info: "Khi bạn dùng 【Giết】 gây sát thương, bạn có thể bỏ một lá bài của bạn hoặc của người đó, nếu bỏ bài Rô bằng cách này, thì sát thương này +1.",
	stddaoshu: "Đạo Thư",
	stddaoshu_info: "Mỗi vòng giới hạn một lần, giai đoạn Chuẩn Bị của một nhân vật, bạn có thể tiết lộ một lá bài của một nhân vật khác ngoài người đó, sau đó khiến người đó nhận được lá bài này, và bạn và người đó trong lượt này không thể dùng bài cùng hoa với lá bài này.",
	stddaizui: "Đái Tội",
	stddaizui_info: "Kỹ năng khóa, sau khi bạn chịu sát thương, bạn được xem như trong vòng này chưa phát động 【Đạo Thư】.",
	stdxiongxia: "Hung Hiệp",
	stdxiongxia_info: "Bạn có thể dùng hai lá bài xem như 【Quyết Đấu】 sử dụng cho hai nhân vật khác. Sau khi 【Quyết Đấu】 bạn dùng bằng cách này kết toán xong, nếu tất cả nhân vật mục tiêu đều chịu sát thương do bài này gây ra, thì 【Hung Hiệp】 mất hiệu lực trong lượt này.",
	stdhuiji: "Huy Kích",
	stdhuiji_info: "Bạn dùng 【Giết】 có thể chỉ định thêm tối đa hai mục tiêu. Nếu làm vậy, khi nhân vật mục tiêu đáp trả 【Giết】 này, các nhân vật mục tiêu khác có thể thay thế người đó dùng 【Tránh】.",
	stdmingfa: "Minh Phạt",
	stdmingfa_info: "Giai đoạn Xuất Bài, bạn có thể gây cho một nhân vật có thể lực lớn hơn 1 1 điểm sát thương, sau đó kỹ năng này mất hiệu lực cho đến khi người đó chết hoặc hồi phục thể lực.",
	stdjinjian: "Tiến Gián",
	stdjinjian_info: "Mỗi lượt mỗi hạng mục giới hạn một lần, khi bạn gây ra / chịu sát thương, bạn có thể ngăn ngừa sát thương này, sau đó sát thương bạn gây ra / chịu lần tiếp theo trong lượt này +1.",
	stdrenzheng: "Nhân Chính",
	stdrenzheng_info: "Kỹ năng khóa, khi có sát thương bị ngăn ngừa, bạn khiến nhân vật trong lượt hiện tại bốc một lá bài.",
	stdxiongsuan: "Hung Toán",
	stdxiongsuan_info: "Kỹ năng khóa, giai đoạn Chuẩn Bị, nếu thể lực của bạn là nhiều nhất bàn, thì bạn phải gây cho ít nhất một nhân vật có thể lực bằng bạn mỗi người 1 điểm sát thương.",
	stdchunlao: "Thuần Lao",
	stdchunlao_info: "Khi kết thúc giai đoạn Bỏ Bài, nếu bạn đã bỏ ít nhất hai lá bài trong giai đoạn này, thì bạn có thể dùng những lá bài này để đổi bài trên tay với một nhân vật khác, sau đó người đó có thể khiến bạn hồi phục 1 điểm thể lực.",
	stdquedi: "Khước Địch",
	stdquedi_info: "Bạn có thể dùng 【Giết】 xem như 【Quyết Đấu】.",
	stdzhiyinmeng: "Cấp Minh",
	stdzhiyinmeng_info: "Giai đoạn Chuẩn Bị, bạn có thể đưa cho một nhân vật khác một số lá bài bất kỳ, sau đó người đó có thể đưa cho bạn một số lá bài bất kỳ.",
	stdhehe: "Hòa Hợp",
	stdhehe_info: "Khi kết thúc giai đoạn Bốc Bài, bạn có thể khiến tối đa hai nhân vật khác có số bài trên tay bằng bạn mỗi người bốc một lá bài.",
	stdzhiyi: "Chấp Nghĩa",
	stdzhiyi_info: "Kỹ năng khóa, khi kết thúc lượt của một nhân vật, nếu bạn đã dùng 【Giết】 trong lượt này, thì bạn được xem như đã dùng 【Giết】 hoặc bốc một lá bài.",
	stdshefu: "Thiết Phục",
	stdshefu_info: "① Giai đoạn Kết Thúc, bạn có thể gọi một lá bài trên tay là “Phục Binh” đặt úp lên bài tướng. ② Khi một nhân vật dùng bài, bạn có thể bỏ một “Phục Binh” trên bài tướng có cùng tên với bài này và khiến bài này vô hiệu.",
	stdyibing: "Ích Binh",
	stdyibing_info: "Khi một nhân vật vào trạng thái hấp hối, bạn có thể nhận được một lá bài của người đó.",
	stdbazhan: "Bả Chiến",
	stdbazhan_info: "Giai đoạn Xuất Bài giới hạn hai lần, bạn có thể tiết lộ một lá bài trên tay và đưa cho một nhân vật nam, sau đó người đó có thể tiết lộ và đưa cho bạn một lá bài trên tay khác loại với lá bài này.",
	stdzhanying: "Tiêu Ảnh",
	stdzhanying_info: "Kỹ năng khóa, trong lượt của bạn, nhân vật có số bài trên tay nhiều hơn khi bắt đầu lượt không thể dùng bài đỏ và chịu sát thương +1.",
	stdtiaohe: "Điều Hòa",
	stdtiaohe_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể bỏ một lá bài Trang Bị và một lá bài Giáp trên bàn (không thể là bài của cùng một nhân vật).",
	stdqiansu: "Khiêm Tố",
	stdqiansu_info: "Khi bạn trở thành mục tiêu của bài chú, nếu khu vực Trang Bị của bạn không có bài, thì bạn có thể bốc một lá bài.",
	old_shen_zhaoyun: "Lao Thần Triệu Vân",
	old_shen_zhaoyun_prefix: "Lao Thần",
	std_xushu: "Chuẩn Từ Thứ",
	std_xushu_prefix: "Chuẩn",
	std_xuezong: "Chuẩn Tiết Tông",
	std_xuezong_prefix: "Chuẩn",
	std_liuzhang: "Chuẩn Lưu Chương",
	std_liuzhang_prefix: "Chuẩn",
	std_wangyuanji: "Chuẩn Vương Nguyên Cơ",
	std_wangyuanji_prefix: "Chuẩn",
	std_wanglang: "Chuẩn Vương Lãng",
	std_wanglang_prefix: "Chuẩn",
	std_zhonghui: "Chuẩn Chung Hội",
	std_zhonghui_prefix: "Chuẩn",
	std_fuhuanghou: "Chuẩn Phục Thọ",
	std_fuhuanghou_prefix: "Chuẩn",
	std_liubiao: "Chuẩn Lưu Biểu",
	std_liubiao_prefix: "Chuẩn",
	std_gongsunyuan: "Chuẩn Công Tôn Uyên",
	std_gongsunyuan_prefix: "Chuẩn",
	std_cenhun: "Chuẩn Sầm Hôn",
	std_cenhun_prefix: "Chuẩn",
	std_sunshao_prefix: "Chuẩn",
	std_jiangwan: "Chuẩn Tưởng Uyển",
	std_jiangwan_prefix: "Chuẩn",
	std_maliang: "Chuẩn Mã Lương",
	std_maliang_prefix: "Chuẩn",
	std_simashi: "Chuẩn Tư Mã Sư",
	std_simashi_prefix: "Chuẩn",
	std_guanxing: "Chuẩn Quan Hưng",
	std_guanxing_prefix: "Chuẩn",
	std_huaxin: "Chuẩn Hoa Hân",
	std_huaxin_prefix: "Chuẩn",
	stdwuyou: "Vũ Hựu",
	stdwuyou_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể thi điểm với một nhân vật, nếu bạn không thắng, trong lượt này bạn xem như có 【Vũ Thánh】. Sau đó nhân vật thắng thi điểm xem như sử dụng một 【Quyết Đấu】 nhắn vào nhân vật thua.",
	stdqiuyuan: "Cầu Viện",
	stdqiuyuan_info: "Khi bạn trở thành mục tiêu của 【Giết】 do một nhân vật sử dụng, bạn có thể khiến một nhân vật khác chọn một: 1. Đưa cho bạn một lá bài; 2. Trở thành mục tiêu bổ sung của 【Giết】 này.",
	stdzhuikong: "Chuỵ Khủng",
	stdzhuikong_info: "Giai đoạn Chuẩn Bị của nhân vật khác, bạn có thể dùng 【Giết】 để thi điểm với người đó, nhân vật thắng có thể sử dụng lá bài thi điểm của đối phương.",
	stdzishou: "Tự Thủ",
	stdzishou_info: "Trước khi bắt đầu giai đoạn Xuất Bài, bạn có thể bốc số lá bài bằng số thế lực trên bàn, sau đó bỏ qua giai đoạn này.",
	stdjujin: "Cứ Kinh",
	stdjujin_info: "Kỹ năng Chủ Công, sau khi bạn chịu sát thương do nhân vật thế lực Quần khác gây ra, bạn có thể bỏ hai lá bài, sau đó hồi phục 1 điểm thể lực.",
	stdhuaiyi: "Hoài Dị",
	stdhuaiyi_info: "Kỹ năng khóa, giai đoạn Chuẩn Bị, bạn tiết lộ tất cả bài trên tay, nếu màu sắc khác nhau, bạn bỏ tất cả bài có một màu, sau đó nhận được mỗi người một lá bài của tối đa số lượng nhân vật khác tương ứng, nếu số nhân vật được chọn lớn hơn 1, bạn mất 1 điểm thể lực.",
	stdfengbai: "Phong Bái",
	stdfengbai_info: "Kỹ năng Chủ Công, khi bạn nhận được bài trong khu vực Trang Bị của một nhân vật thế lực Quần, bạn có thể khiến người đó bốc một lá bài.",
	stdjishe: "Cực Xa",
	stdjishe_info: "Giai đoạn Xuất Bài, nếu giới hạn bài trên tay của bạn lớn hơn 0, bạn có thể khiến giới hạn bài trên tay trong lượt này -1, sau đó bốc một lá bài.",
	stdwudu: "Vô Độ",
	stdwudu_info: "Khi một nhân vật không có bài trên tay chịu sát thương, bạn có thể giảm 1 điểm giới hạn thể lực, ngăn ngừa sát thương này.",
	stdjinglve: "Cảnh Lược",
	stdjinglve_info: "Khi bắt đầu giai đoạn Bỏ Bài của nhân vật khác, bạn có thể tiết lộ và đưa cho người đó hai lá bài, khiến người đó trong giai đoạn này không thể bỏ những lá bài này, sau đó bạn có thể nhận một lá bài bị bỏ trong giai đoạn này khi kết thúc giai đoạn.",
	std_sunshao: "Chuẩn Tôn Thiệu",
	stddingyi: "Định Nghi",
	stddingyi_info: "Giai đoạn Kết Thúc của một nhân vật, nếu trong khu vực Trang Bị của người đó không có bài, người đó có thể bốc một lá bài.",
	stdzuici: "Tội Từ",
	stdzuici_info: "Sau khi bạn chịu sát thương, bạn có thể di chuyển một lá bài trên bàn vào khu vực của nguồn gây sát thương.",
	stdruwu: "Nho Vũ",
	stdruwu_info: "Bạn có thể dùng một lá bài Trang Bị không phải là bài được đặt vào trong lượt này xem như 【Vô Trung Sinh Hữu】 hoặc 【Quyết Đấu】.",
	stdchengshi: "Thừa Sự",
	stdchengshi_info: "Kỹ năng giới hạn, khi một nhân vật khác chết, bạn có thể đổi chỗ ngồi và bài trong khu vực Trang Bị với người đó.",
	stdxiemu: "Hiệp Mục",
	stdxiemu_info: "Giai đoạn Xuất Bài của nhân vật khác giới hạn một lần, người đó có thể tiết lộ và đưa cho bạn một bài cơ bản, sau đó phạm vi tấn công của người đó trong lượt này +1.",
	stdnaman: "Nạp Man",
	stdnaman_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể dùng một số bài cơ bản bất kỳ xem như 【Nam Man Nhập Xâm】 chỉ định số lượng mục tiêu tương ứng.",
	oldjuejing: "Tuyệt Cảnh",
	oldjuejing_info: "Kỹ năng khóa. ① Giai đoạn Bốc Bài, bạn khiến số bài bốc định mức +X (X là thể lực đã mất của bạn). ② Giới hạn bài trên tay của bạn +2.",
	oldlonghun: "Long Hồn",
	oldlonghun_info: "Bạn có thể dùng Y lá bài cùng hoa theo quy tắc sau để dùng hoặc đánh ra: ♥ xem như 【Đào】, ♦ xem như 【Giết】 Hỏa, ♣ xem như 【Tránh】, ♠ xem như 【Vô Tiết Khả Kích】 (Y là thể lực của bạn và ít nhất là 1).",
	stdxiaofan: "Hiêu Phiên",
	stdxiaofan_info: "Kỹ năng khóa, sau khi bạn dùng bài kết toán xong, bạn bỏ bài trong X khu vực đầu tiên của bạn: 1. Khu vực Phán Định 2. Khu vực Trang Bị 3. Khu vực bài trên tay (X là số loại bài bạn đã dùng trong lượt này).",
	stdtuishi: "Thoái Thất",
	stdtuishi_info: "Kỹ năng khóa, bạn không thể dùng 【Vô Tiết Khả Kích】, bài chữ cái bạn dùng vô hiệu.",
	stdfunan: "Phục Nan",
	stdfunan_info: "Mỗi lượt giới hạn một lần, khi bài do nhân vật khác dùng bị bạn đáp trả, bạn có thể nhận được nó.",
	stdjiexun: "Giới Huấn",
	stdjiexun_info: "Giai đoạn Kết Thúc, bạn có thể khiến một nhân vật bỏ một lá bài trên tay, nếu lá bài này có hoa ♦️, người đó bốc hai lá bài.",
	stdwuyan: "Vô Ngôn",
	stdwuyan_info: "Kỹ năng khóa, bài chú của bạn đều được xem là 【Vô Tiết Khả Kích】.",
	stdjujian: "Cử Tiến",
	stdjujian_info: "Mỗi lượt giới hạn một lần, sau khi 【Vô Tiết Khả Kích】 của bạn kết toán xong, có thể đưa cho một nhân vật khác.",
	stdyinge: "Dẫn Qua",
	stdyinge_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể khiến một nhân vật khác đưa cho bạn một lá bài, sau đó người đó xem như sử dụng một 【Giết】 nhắn vào bạn hoặc một nhân vật khác trong phạm vi tấn công của bạn.",
	stdshiren: "Thi Nhân",
	stdshiren_info: "Mỗi lượt giới hạn một lần, khi bạn trở thành mục tiêu của 【Giết】 do nhân vật khác sử dụng, bạn có thể bốc hai lá bài, sau đó đưa cho nhân vật đó một lá bài.",
	stdjuyi: "Cứ Ích",
	stdjuyi_info: "Kỹ năng Chủ Công, lần đầu tiên mỗi lượt nhân vật thế lực Quần khác gây sát thương cho bạn, người đó có thể ngăn ngừa sát thương này, đổi thành nhận một lá bài của bạn.",
	stdqianchong: "Khiêm Xung",
	stdqianchong_info: "Kỹ năng khóa, nếu số bài trong khu vực Trang Bị của bạn là lẻ / chẵn, bạn dùng bài không giới hạn số lần / khoảng cách.",
	stdshangjian: "Thượng Kiệm",
	stdshangjian_info: "Giai đoạn Kết Thúc, nếu số bài bạn đã mất trong lượt này không lớn hơn thể lực của bạn, bạn có thể nhận từ bộ bài bỏ một lá bài bạn đã mất trong lượt này.",
	stdgushe: "Cổ Thiệt",
	stdgushe_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể thi điểm với một nhân vật, nhân vật thắng thi điểm bốc một lá bài, sau đó nhân vật thua thi điểm có thể lặp lại quy trình này với đối phương.",
	stdjici: "Kích Từ",
	stdjici_info: "Khi bạn lật ngửa lá bài thi điểm, bạn có thể mất 1 điểm thể lực, khiến điểm số của lá bài này được xem là k.",
	stdxingfa: "Hưng Phạt",
	stdxingfa_info: "Giai đoạn Chuẩn Bị, nếu số bài trên tay bạn không nhỏ hơn thể lực, bạn có thể gây cho một nhân vật khác 1 điểm sát thương.",
	stdyuanqing: "Uyên Thanh",
	stdyuanqing_info: "Khi kết thúc lượt, bạn có thể khiến tất cả nhân vật lần lượt chọn và nhận từ bộ bài bỏ một lá bài mà họ đã mất trong lượt này.",
	stdshuchen: "Sơ Trần",
	stdshuchen_info: "Ngoài lượt của bạn, bạn có thể dùng bài trên tay vượt quá giới hạn bài trên tay xem như 【Đào】.",
	std_zhangbao: "Chuẩn Trương Bào",
	std_zhangbao_prefix: "Chuẩn",
	std_liuchen: "Chuẩn Lưu Sâm",
	std_liuchen_prefix: "Chuẩn",
	std_guansuo: "Chuẩn Quan Sách",
	std_guansuo_prefix: "Chuẩn",
	std_xiahouba: "Chuẩn Hạ Hầu Bá",
	std_xiahouba_prefix: "Chuẩn",
	std_caorui: "Chuẩn Tào Duệ",
	std_caorui_prefix: "Chuẩn",
	std_liuye: "Chuẩn Lưu Diệp",
	std_liuye_prefix: "Chuẩn",
	std_guohuanghou: "Chuẩn Quách Hoàng Hậu",
	std_guohuanghou_prefix: "Chuẩn",
	std_lvfan: "Chuẩn Lã Phạm",
	std_lvfan_prefix: "Chuẩn",
	std_dingfeng: "Chuẩn Đinh Phụng",
	std_dingfeng_prefix: "Chuẩn",
	std_sunluban: "Chuẩn Tôn Lỗ Ban",
	std_sunluban_prefix: "Chuẩn",
	std_liuzan: "Chuẩn Lưu Tán",
	std_liuzan_prefix: "Chuẩn",
	std_sunyi: "Chuẩn Tôn Dực",
	std_sunyi_prefix: "Chuẩn",
	std_taoqian: "Chuẩn Đào Khiêm",
	std_taoqian_prefix: "Chuẩn",
	std_jiling: "Chuẩn Kỷ Linh",
	std_jiling_prefix: "Chuẩn",
	std_liru: "Chuẩn Lý Nho",
	std_liru_prefix: "Chuẩn",
	std_wangyun: "Chuẩn Vương Doãn",
	std_wangyun_prefix: "Chuẩn",
	stdjuezhu: "Giác Trục",
	stdjuezhu_info: "Kỹ năng khóa, sau khi bạn gây ra / chịu sát thương, bạn trong lượt này dùng bài không giới hạn số lần / xem như sử dụng một 【Quyết Đấu】 nhắn vào nguồn gây sát thương.",
	stdchengji: "Thừa Kế",
	stdchengji_info: "Bạn có thể dùng hai lá bài khác màu xem như 【Giết】 để dùng hoặc đánh ra.",
	stdzhanjue: "Chiến Tuyệt",
	stdzhanjue_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể dùng tất cả bài trên tay xem như 【Quyết Đấu】, sau đó bốc một lá bài.",
	stdqinwang: "Cần Vương",
	stdqinwang_info: "Kỹ năng Chủ Công, khi bạn cần đánh ra 【Giết】, các nhân vật thế lực Thục khác có thể bỏ một bài cơ bản, xem như bạn đã đánh ra nó.",
	stdzhengnan: "Chinh Nam",
	stdzhengnan_info: "Giai đoạn Chuẩn Bị, bạn có thể dùng một lá bài đỏ trên tay xem như 【Giết】; nếu bạn giết được nhân vật bằng cách này, bốc hai lá bài.",
	stdbaobian: "Báo Biến",
	stdbaobian_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể mất 1 điểm thể lực và khiến một nhân vật bỏ một lá bài trên tay; nếu lá bài này là bài cơ bản, bạn xem như sử dụng một 【Giết】 nhắn vào người đó.",
	stdhuituo: "Hối Thác",
	stdhuituo_info: "Sau khi bạn chịu sát thương, bạn có thể tiết lộ hai lá bài trên cùng bộ bài, sau đó thay thế một số lá bài bất kỳ.",
	stdmingjian: "Minh Giám",
	stdmingjian_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể tiết lộ một lá bài và đưa cho một nhân vật khác, sau đó người đó có thể sử dụng lá bài này.",
	stdpolu: "Phá Lỗ",
	stdpolu_info: "Sau khi bạn gây ra hoặc chịu sát thương, có thể bỏ một lá bài trong khu vực Trang Bị của nhân vật bị thương; nếu nhân vật đó là bạn, bạn bốc một lá bài.",
	stdchoulve: "Trù Lược",
	stdchoulve_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể đưa cho nhân vật khác một lá bài trên tay, sau đó người đó có thể tiết lộ và đưa cho bạn một lá bài Trang Bị.",
	stdjiaozhao: "Kiểu Chiếu",
	stdjiaozhao_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể khiến một nhân vật khác có số bài trên tay không nhỏ hơn hai tiết lộ hai lá bài trên tay, sau đó bạn có thể dùng một lá bài để đổi một lá bài trong số đó.",
	stddanxin: "Đàn Tâm",
	stddanxin_info: "Sau khi bạn chịu sát thương, bạn có thể phát động một lần 【Kiểu Chiếu】 và đổi thành bạn nhận được một trong những lá bài đã tiết lộ của người đó.",
	stddianfeng: "Điển Phong",
	stddianfeng_info: "Khi một nhân vật mất tất cả bài trong khu vực Trang Bị, bạn có thể bốc một lá bài.",
	stdduanbing: "Đoản Binh",
	stdduanbing_info: "Kỹ năng khóa, phạm vi tấn công của bạn luôn là 1. Sát thương do 【Giết】 bạn dùng gây ra lần đầu tiên mỗi lượt +1.",
	stdfenxun: "Phấn Tốn",
	stdfenxun_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể bỏ một lá bài Giáp và chọn một nhân vật khác, trong lượt này người đó được xem là nằm trong phạm vi tấn công của bạn.",
	stdzenhui: "Tấn Hủy",
	stdzenhui_info: "Khi bạn dùng 【Giết】 hoặc bài chú, bạn có thể khiến một nhân vật không phải mục tiêu trở thành người sử dụng bài này.",
	stdchuyi: "Trừ Dị",
	stdchuyi_info: "Mỗi vòng giới hạn một lần, khi một nhân vật khác gây sát thương cho một nhân vật trong phạm vi tấn công của bạn, bạn có thể khiến sát thương này +1.",
	stdfenyin: "Phấn Âm",
	stdfenyin_info: "Giai đoạn Bốc Bài, bạn có thể bốc thêm hai lá bài; nếu làm vậy, trong lượt này khi bạn dùng bài, nếu màu bài này giống với màu bài bạn đã dùng trước đó, bạn phải bỏ một lá bài.",
	stdzaoli: "Táo Lệ",
	stdzaoli_info: "Kỹ năng khóa, giai đoạn Chuẩn Bị, bạn bỏ tất cả bài trên tay hoặc trong khu vực Trang Bị, sau đó bốc X bài và mất 1 điểm thể lực (X là tổng số bài bạn bỏ bằng cách này và thể lực đã mất của bạn).",
	stdyirang: "Ịp Nhượng",
	stdyirang_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể tiết lộ tất cả bài trên tay và đưa những bài này cho một nhân vật khác có số bài trên tay ít nhất, sau đó bạn bốc số lá bài bằng số loại đã đưa ra.",
	stdshuangdao: "Song Nhận",
	stdshuangdao_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể thi điểm với một nhân vật khác. Nếu bạn thắng, bạn có thể xem như sử dụng một 【Giết】 không giới hạn khoảng cách nhắn vào tối đa hai nhân vật có khoảng cách tính với người đó là 1; nếu bạn không thắng, thì bạn không thể dùng 【Giết】 trong lượt này.",
	stdjuece: "Tuyệt Sách",
	stdjuece_info: "Giai đoạn Kết Thúc, bạn có thể gây cho một nhân vật đã mất ít nhất hai lá bài trong lượt này 1 điểm sát thương.",
	stdmieji: "Diệt Kế",
	stdmieji_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể đưa cho một nhân vật khác một bài chú đen, sau đó có thể bỏ tối đa hai lá bài của người đó.",
	stdyunji: "Vận Cơ",
	stdyunji_info: "Bạn có thể dùng một lá bài Trang Bị xem như 【Mượn Đao Giết Người】.",
	stdzongji: "Túng Kế",
	stdzongji_info: "Khi một nhân vật chịu sát thương do 【Giết】 hoặc 【Quyết Đấu】 gây ra, bạn có thể bỏ mỗi người một lá bài của nhân vật đó và nguồn gây sát thương.",
	std_tianfeng: "Chuẩn Điền Phong",
	std_tianfeng_prefix: "Chuẩn",
	stdgangjian: "Cương Gián",
	stdgangjian_info: "Giai đoạn Chuẩn Bị của nhân vật khác, bạn có thể khiến người đó xem như sử dụng một 【Giết】 nhắn vào bạn, nếu 【Giết】 này không gây sát thương, người đó không thể dùng bài chú trong lượt này.",
	stdguijie: "Quỳ Khiết",
	stdguijie_info: "Khi bạn cần sử dụng hoặc đánh ra một 【Tránh】, bạn có thể bỏ hai lá bài đỏ và bốc một lá bài, xem như đã dùng hoặc đánh ra nó.",
	std_liuxie: "Chuẩn Lưu Hiệp",
	std_liuxie_prefix: "Chuẩn",
	stdtianming: "Thiên Mệnh",
	stdtianming_info: "Khi bạn trở thành mục tiêu của 【Giết】, bạn có thể bỏ tất cả bài và bốc hai lá bài, sau đó nhân vật khác có thể lực lớn nhất duy nhất cũng có thể làm như vậy.",
	stdmizhao: "Mật Chiếu",
	stdmizhao_info: "Giai đoạn Kết Thúc, bạn có thể đưa tất cả bài cho một nhân vật khác và chọn một nhân vật khác nữa, sau đó người thứ nhất có thể cùng với người thứ hai mỗi người mất 1 điểm thể lực.",
	stdzhongyan: "Chung Yên",
	stdzhongyan_info: "Kỹ năng Chủ Công. Khi nhân vật thế lực Quần khác chết, bạn có thể hồi phục 1 điểm thể lực.",
	std_simazhao: "Chuẩn Tư Mã Chiêu",
	std_simazhao_prefix: "Chuẩn",
	stdzhaoxin: "Chiêu Tâm",
	stdzhaoxin_info: "Kỹ năng khóa. Giai đoạn Chuẩn Bị, bạn tiết lộ tất cả bài trên tay, nếu màu của những bài này đều giống nhau, bạn gây cho một nhân vật 1 điểm sát thương.",
	std_guozhao: "Chuẩn Quách Chiếu",
	std_guozhao_prefix: "Chuẩn",
	stdwufei: "Vu Phỉ",
	stdwufei_info: "Giai đoạn Chuẩn Bị, bạn có thể khiến một nhân vật nữ tiết lộ tất cả bài trên tay, sau đó người đó bỏ tất cả bài có một màu và bốc một lá bài.",
	stdjiaochong: "Tiêu Sủng",
	stdjiaochong_info: "Giai đoạn Kết Thúc của nhân vật nam, bạn có thể phát động một lần 【Vu Phỉ】 nhắn vào một nhân vật nữ.",
	std_jiakui: "Chuẩn Giả Quỳ",
	std_jiakui_prefix: "Chuẩn",
	stdzhongzuo: "Trung Tá",
	stdzhongzuo_info: "Kỹ năng khóa. Khi kết thúc lượt của một nhân vật, nếu bạn đã gây ra hoặc chịu sát thương trong lượt này, bạn và người đó mỗi người bốc một lá bài.",
	stdwanlan: "Vãn Lan",
	stdwanlan_info: "Kỹ năng giới hạn. Khi nhân vật khác vào trạng thái hấp hối, bạn có thể đưa cho người đó tất cả bài trên tay, sau đó người đó hồi phục thể lực về 1 điểm.",
	std_yufan: "Chuẩn Ngu Phiên",
	std_yufan_prefix: "Chuẩn",
	stdzongxuan: "Tung Huyền",
	stdzongxuan_info: "Khi bài trên tay của bạn vì bị bỏ vào bộ bài bỏ, bạn có thể bỏ một lá bài trên bàn.",
	stdzhiyan: "Trực Ngôn",
	stdzhiyan_info: "Giai đoạn Kết Thúc, bạn có thể nhận một lá bài Trang Bị đã vào bộ bài bỏ trong lượt này.",
	std_zhugeke: "Chuẩn Gia Cát Khác",
	std_zhugeke_prefix: "Chuẩn",
	stdaocai: "Ngạo Tài",
	stdaocai_info: "Khi kết thúc mỗi lượt, nếu bạn không có bài trên tay, bạn có thể xem hai lá bài trên cùng bộ bài và nhận một lá bài trong số đó.",
	stdduwu: "Độc Vũ",
	stdduwu_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể bỏ tất cả bài trên tay và gây cho một nhân vật trong phạm vi tấn công 1 điểm sát thương.",
	std_mengda: "Chuẩn Mông Đạt",
	std_mengda_prefix: "Chuẩn",
	stdzhuan: "Trục An",
	stdzhuan_info: "Kỹ năng khóa. Khi bạn chịu sát thương lần đầu tiên mỗi lượt, bạn bốc ba lá bài, sau đó nguồn gây sát thương nhận được một lá bài của bạn.",
	std_caozhen: "Chuẩn Tào Chân",
	std_caozhen_prefix: "Chuẩn",
	stdsidi: "Ty Địch",
	stdsidi_info: "Khi có nhân vật đánh ra 【Giết】, bạn có thể bốc một lá bài.",
	std_dongyun: "Chuẩn Đổng Doãn",
	std_dongyun_prefix: "Chuẩn",
	stdbingzheng: "Bỉnh Chính",
	stdbingzheng_info: "Giai đoạn Kết Thúc, bạn có thể khiến một nhân vật bỏ một lá bài, nếu số bài trên tay của người đó không bằng thể lực, bạn mất 1 điểm thể lực.",
	stdduliang: "Đốc Lương",
	stdduliang_info: "Sau khi bạn chịu sát thương, bạn có thể bốc một lá bài, nếu số bài trên tay bạn bằng thể lực, bạn hồi phục 1 điểm thể lực.",
	std_baosanniang: "Chuẩn Bão Tam Nương",
	std_baosanniang_prefix: "Chuẩn",
	stdzhennan: "Trấn Nam",
	stdzhennan_info: "Giai đoạn Chuẩn Bị của nhân vật khác, bạn có thể bỏ một lá bài trên tay, nếu làm vậy, sau khi người đó dùng lá bài tiếp theo trong lượt này, nếu lá bài này màu đỏ, bạn khiến người đó nhận được nó.",
	stdshuyong: "Xù Dũng",
	stdshuyong_info: "Khi nhân vật khác liên tục dùng hai lá bài cùng tên trong lượt, bạn có thể bốc một lá bài.",
	std_liuba: "Chuẩn Lưu Ba",
	std_liuba_prefix: "Chuẩn",
	stdduanbi: "Đoạn Tệ",
	stdduanbi_info: "Giai đoạn Kết Thúc, bạn có thể bỏ tất cả bài trên tay, sau đó khiến hai nhân vật mỗi người bốc hai lá bài.",
	std_kongrong: "Chuẩn Khổng Dung",
	std_kongrong_prefix: "Chuẩn",
	stdlirang: "Lễ Nhượng",
	stdlirang_info: "Khi kết thúc giai đoạn Bỏ Bài của nhân vật khác, bạn có thể đưa cho người đó một lá bài, sau đó nhận được tất cả bài đỏ đã vào bộ bài bỏ trong giai đoạn này.",
	std_zoushi: "Chuẩn Trâu Thị",
	std_zoushi_prefix: "Chuẩn",
	stdhuoshui: "Họa Thủy",
	stdhuoshui_info: "Kỹ năng khóa, nhân vật khác có bài trong khu vực Phán Định chịu sát thương +1.",
	stdqingcheng: "Khuynh Thành",
	stdqingcheng_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể dùng hai lá bài đỏ không phải chú xem như hai 【Lạc Bất Tư Thục】 sử dụng cho bạn và một nhân vật khác.",
	std_sunluyu: "Chuẩn Tôn Lục Dục",
	std_sunluyu_prefix: "Chuẩn",
	stdmumu: "Mục Mục",
	stdmumu_info: "Giai đoạn Chuẩn Bị, bạn có thể bỏ một lá bài trên tay, sau đó di chuyển một lá bài Trang Bị trên bàn.",
	stdmeibu: "Mị Bộ",
	stdmeibu_info: "Khi nhân vật đang trang bị bài Vũ Khí dùng 【Giết】, bạn có thể khiến người đó bỏ một lá bài trên tay.",
	std_zhoufang: "Chuẩn Chu Phường",
	std_zhoufang_prefix: "Chuẩn",
	stdqijian: "Thất Tiên",
	stdqijian_info: "Giai đoạn Chuẩn Bị, bạn có thể khiến hai nhân vật có tổng số bài trên tay là 7 mỗi người chọn một: 1. Bỏ một lá bài của đối phương; 2. Khiến đối phương bốc một lá bài.",
	stdyoudi: "Dụ Địch",
	stdyoudi_info: "Giai đoạn Kết Thúc, bạn có thể dùng một lá bài đỏ xem như 【Thuận Thủ Khiên Dương】.",
	std_baoxin: "Chuẩn Bão Tín",
	std_baoxin_prefix: "Chuẩn",
	stdyimou: "Nghị Mưu",
	stdyimou_info: "Sau khi bạn chịu sát thương, bạn có thể đưa một lá bài cho một nhân vật khác.",
	stdmutao: "Mộ Thảo",
	stdmutao_info: "Giai đoạn Chuẩn Bị, bạn có thể khiến một nhân vật tiết lộ tất cả bài trên tay, nếu trong đó có 【Giết】, bạn gây cho người đó 1 điểm sát thương.",
	std_peixiu: "Chuẩn Bùi Tú",
	std_peixiu_prefix: "Chuẩn",
	stdzhitu: "Chế Đồ",
	stdzhitu_info: "Bạn có thể dùng ít nhất hai lá bài có tổng điểm số bằng 13 xem như bài chú thông thường bất kỳ.",
	std_yangbiao: "Chuẩn Dương Bưu",
	std_yangbiao_prefix: "Chuẩn",
	stdyizheng: "Nghĩa Tranh",
	stdyizheng_info: "Giai đoạn Chuẩn Bị, bạn có thể thi điểm với một nhân vật có thể lực không nhỏ hơn bạn, nhân vật thắng gây cho nhân vật thua 1 điểm sát thương.",
	stdrangjie: "Nhượng Tiết",
	stdrangjie_info: "Sau khi bạn chịu sát thương, bạn có thể di chuyển một lá bài trên bàn.",
	std_huangfusong: "Chuẩn Hoàng Phủ Tùng",
	std_huangfusong_prefix: "Chuẩn",
	stdtaoluan: "Thảo Loạn",
	stdtaoluan_info: "Giai đoạn Kết Thúc của nhân vật khác, bạn có thể đưa cho người đó một lá bài, người đó tiết lộ tất cả bài trên tay, sau đó bỏ tất cả 【Tránh】.",
	std_zerong: "Chuẩn Trách Dung",
	std_zerong_prefix: "Chuẩn",
	stdcansi: "Tàn Tứ",
	stdcansi_info: "Kỹ năng khóa, giai đoạn Chuẩn Bị, bạn khiến một nhân vật trong phạm vi tấn công nhận được một lá bài của bạn, sau đó xem như lần lượt sử dụng 【Giết】, 【Quyết Đấu】 nhắn vào người đó.",
	std_pangdegong: "Chuẩn Bàng Đức Công",
	std_pangdegong_prefix: "Chuẩn",
	stdlingjian: "Lệnh Tiến",
	stdlingjian_info: "Kỹ năng khóa, khi 【Giết】 bạn dùng lần đầu tiên mỗi lượt kết toán xong, nếu bài này không gây sát thương, bạn thiết lập lại 【Minh Thức】.",
	stdmingshi: "Minh Thức",
	stdmingshi_info: "Kỹ năng giới hạn, giai đoạn Xuất Bài, bạn có thể chọn một: ① Bốc hai lá bài; ② Hồi phục 1 điểm thể lực; ③ Gây cho một nhân vật 1 điểm sát thương; ④ Di chuyển một lá bài trên bàn.",
	get std_nanhualaoxian() {
		return Math.random() > 0.25 ? "Chuẩn Nam Hoa Lão Tiên" : "Chuẩn Nam Hoa Tiểu Tiên";
	},
	std_nanhualaoxian_prefix: "Chuẩn",
	stdxianlu: "Tiên Lục",
	stdxianlu_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể bỏ một lá bài Trang Bị trên bàn của một nhân vật, nếu lá bài này màu đỏ, bạn đặt lá bài này xem như 【Lạc Bất Tư Thục】 vào khu vực Phán Định của bạn và gây cho người đó 1 điểm sát thương.",
	stdtianshu: "Thiên Thư",
	stdtianshu_info: "Kỹ năng khóa, giới hạn bài trên tay của bạn +X (X là số thế lực hiện tại -1).",
	std_zhangyao: "Chuẩn Trương Mỹ Nhân",
	std_wangfuren: "Chuẩn Vương Phu Nhân",
	std_panglin: "Chuẩn Bàng Lâm",
	std_huangchong: "Chuẩn Hoàng Sủng",
	std_caoxiong: "Chuẩn Tào Hùng",
	std_maohuanghou: "Chuẩn Mao Hoàng Hậu",
	std_zhengcong: "Chuẩn Trịnh Thông",
	std_jiangjie: "Chuẩn Khương Tiệp",
	std_zhangyao_prefix: "Chuẩn",
	std_wangfuren_prefix: "Chuẩn",
	std_panglin_prefix: "Chuẩn",
	std_huangchong_prefix: "Chuẩn",
	std_caoxiong_prefix: "Chuẩn",
	std_maohuanghou_prefix: "Chuẩn",
	std_zhengcong_prefix: "Chuẩn",
	std_jiangjie_prefix: "Chuẩn",
	stdlianrong: "Liên Dung",
	stdyuanzhuo: "Oán Chước",
	stdbizun: "Tịch Tôn",
	stdhuangong: "Hoàn Cung",
	stdzhuying: "Trú Doanh",
	stdzhongshi: "Trung Sự",
	stdjuxian: "Cứ Hiểm",
	stdlijun: "Lệ Quân",
	stdwuwei: "Vô Vi",
	stdleiruo: "Luy Nhược",
	stddechong: "Đắc Sủng",
	stdyinzu: "Ấm Tộc",
	stdqiyue: "Khởi Việt",
	stdjieji: "Kiếp Kích",
	stdfengzhan: "Phong Triển",
	stdruixi: "Nhuệ Tập",
	stdlianrong_info: "Khi bài ♥️ của nhân vật khác vì bị bỏ vào bộ bài bỏ, bạn có thể nhận được nó.",
	stdyuanzhuo_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể bỏ một lá bài của một nhân vật khác, sau đó người đó xem như sử dụng một 【Hỏa Công】 nhắn vào bạn.",
	stdbizun_info: "Mỗi lượt giới hạn một lần, bạn có thể dùng một lá bài Trang Bị xem như 【Giết】 hoặc 【Tránh】, sau đó nhân vật có số bài trên tay nhiều nhất duy nhất có thể di chuyển một lá bài trên bàn.",
	stdhuangong_info: "Kỹ năng khóa, khi bạn mất lá bài cuối cùng trên bàn, bạn bốc một lá bài.",
	stdzhuying_info: "Khi nhân vật khác chịu sát thương không phải thuộc tính, nếu người đó chưa bị liên hoàn, bạn có thể khiến người đó bị liên hoàn.",
	stdzhongshi_info: "Kỹ năng khóa, khi bạn đang bị liên hoàn / chưa bị liên hoàn gây sát thương cho nhân vật chưa bị liên hoàn / đang bị liên hoàn, sát thương này +1.",
	stdjuxian_info: "Kỹ năng khóa, khi nhân vật khác nhận được bài của bạn, bạn ngăn ngừa việc đó.",
	stdlijun_info: "Giai đoạn Chuẩn Bị, bạn tiết lộ mỗi người một lá bài trên tay của tối đa X nhân vật, sau đó các nhân vật có bài bị tiết lộ bằng cách này lần lượt chọn một: 1. Sử dụng bài đã tiết lộ bằng cách này; 2. Bỏ bài đã tiết lộ bằng cách này (X là thể lực của bạn).",
	stdwuwei_info: "Sau khi bạn chịu sát thương, bạn có thể đặt một lá bài Trang Bị vào khu vực Trang Bị của một nhân vật, sau đó bạn bỏ X lá bài của người đó (X là số lượng phạm vi tấn công của người đó tăng lên vì điều này).",
	stdleiruo_info: "Giai đoạn Kết Thúc, bạn có thể nhận một lá bài trong khu vực Trang Bị của một nhân vật khác, sau đó người đó có thể xem như sử dụng một 【Giết】 không giới hạn khoảng cách nhắn vào bạn.",
	stddechong_info: "Giai đoạn Chuẩn Bị của nhân vật khác, bạn có thể đưa cho người đó ít nhất một lá bài, nếu làm vậy, khi bắt đầu giai đoạn Bỏ Bài tiếp theo của người đó, nếu số bài trên tay của người đó không nhỏ hơn thể lực, bạn có thể gây cho người đó 1 điểm sát thương.",
	stdyinzu_info: "Kỹ năng khóa, phạm vi tấn công của nhân vật có số bài trên tay lớn hơn thể lực +1; phạm vi tấn công của nhân vật có số bài trên tay không lớn hơn thể lực -1.",
	stdqiyue_info: "Kỹ năng khóa, khi bắt đầu ván chơi, bạn nhận 【Tuyên Hoa Phủ】 từ ngoài trò chơi.",
	stdjieji_info: "Kỹ năng khóa, sau khi 【Giết】 đầu tiên bạn dùng mỗi lượt gây sát thương cho một nhân vật khác, bạn nhận một lá bài trên tay của người đó, sau đó người đó xem như sử dụng một 【Giết】 không giới hạn khoảng cách nhắn vào bạn.",
	stdfengzhan_info: "Kỹ năng khóa, khi bắt đầu ván chơi, bạn nhận 【Bách Tịch Song Chủy】 từ ngoài trò chơi.",
	stdruixi_info: "Giai đoạn Kết Thúc của mỗi lượt, nếu bạn đã mất bài trong lượt này, bạn có thể dùng một lá bài xem như 【Giết】 không giới hạn khoảng cách.",
	xuanhuafu: "Tuyên Hoa Phủ",
	xuanhuafu_skill: "Tuyên Hoa Phủ",
	xuanhuafu_info: "Kỹ năng khóa, khi bạn dùng 【Giết】 chỉ định mục tiêu, khiến một nhân vật khác có khoảng cách với người đó là 1 trở thành mục tiêu bổ sung của 【Giết】 này.",
	baipishuangbi: "Bách Tịch Song Chủy",
	baipishuangbi_skill: "Bách Tịch Song Chủy",
	baipishuangbi_info: "Kỹ năng khóa, khi bạn dùng 【Giết】 chỉ định một mục tiêu có giới tính khác bạn, nếu bạn không có bài trên tay, sát thương do 【Giết】 này gây ra +1.",
	std_simahui: "Chuẩn Tư Mã Huy",
	std_simahui_prefix: "Chuẩn",
	stdjianjie: "Tiến Kiệt",
	stdjianjie_info: "Giai đoạn Chuẩn Bị, bạn có thể tiết lộ mỗi người một lá bài của tối đa ba nhân vật, những nhân vật này lần lượt có thể dùng bài đỏ / đen đã tiết lộ xem như Hỏa Công / Thiết Tác Liên Hoàn.",
	stdchenghao: "Xưng Hảo",
	stdchenghao_info: "Mỗi lượt giới hạn một lần, khi có nhân vật chịu sát thương thuộc tính, bạn có thể xem một lá bài trên cùng bộ bài, sau đó đưa nó cho bất kỳ nhân vật nào.",
	std_zhengxuan: "Chuẩn Trịnh Huyền",
	std_zhengxuan_prefix: "Chuẩn",
	stdzhengjing: "Chỉnh Kinh",
	stdzhengjing_info: "Khi bắt đầu giai đoạn Bốc Bài, bạn có thể tiết lộ tất cả bài trên tay của bạn và số lượng bài tương ứng trên cùng bộ bài (tối đa ba lá), bạn đưa bài có một hoa trong số đó cho một nhân vật khác, sau đó bạn nhận những bài còn lại.",
	std_miheng: "Chuẩn Di Hành",
	std_miheng_prefix: "Chuẩn",
	stdkuangcai: "Cuồng Tài",
	stdkuangcai_info: "Kỹ năng khóa, giai đoạn Xuất Bài bạn dùng hai lá bài đầu tiên không giới hạn khoảng cách và số lần, sau khi kết toán nếu gây sát thương bạn bốc một lá bài, nếu không thì bỏ một lá bài.",
	stdshejian: "Thiệt Kiếm",
	stdshejian_info: "Khi bạn trở thành mục tiêu duy nhất sử dụng bài của nhân vật khác, bạn có thể chọn bỏ hai lá bài trên tay, sau đó người đó chịu 1 điểm sát thương do bạn gây ra ở giai đoạn Kết Thúc của lượt này.",
	std_majun: "Chuẩn Mã Quân",
	std_majun_prefix: "Chuẩn",
	stdgongqiao: "Công Xảo",
	stdgongqiao_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể chọn một nhân vật và liên tục lật ngửa các lá bài trên cùng bộ bài cho đến khi có bài Trang Bị. Sau đó khiến người đó sử dụng bài Trang Bị này và dùng tất cả bài trên tay để đổi lấy những lá bài còn lại đã lật.",
	std_zhangfen: "Chuẩn Trương Phấn",
	std_zhangfen_prefix: "Chuẩn",
	stdwanglu: "Vọng Lỗ",
	stdwanglu_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể bỏ một lá bài Trang Bị trên bàn, nhân vật mất bài Vũ Khí bằng cách này bốc X lá bài (X là phạm vi tấn công của bài Vũ Khí này).",
	std_zhaoyan: "Chuẩn Triệu Yên",
	std_zhaoyan_prefix: "Chuẩn",
	stdjinhui: "Cẩm Hội",
	stdjinhui_info: "Giai đoạn Chuẩn Bị, bạn có thể lật ngửa ba lá bài trên cùng bộ bài, sau đó cùng với một nhân vật khác lần lượt sử dụng một lá bài trong số đó (không thể liên tục sử dụng bài cùng màu).",
	stdqingman: "Khinh Mạn",
	stdqingman_info: "Kỹ năng khóa, khi kết thúc mỗi lượt, bạn bốc bài lên X lá (X là số ô Trang Bị trống của bạn, tối đa là 3).",
	std_liuli: "Chuẩn Lưu Lý",
	std_liuli_prefix: "Chuẩn",
	stdfuli: "Phủ Lê",
	stdfuli_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể tiết lộ tất cả bài trên tay và bỏ tất cả bài loại sát thương trong đó (không có thì không bỏ), sau đó khiến một nhân vật khác lặp lại quy trình này và hồi phục 1 thể lực.",
	stddehua: "Đức Hóa",
	stddehua_info: "Khi kết thúc lượt bạn chỉ mất hai lá bài, bạn có thể xem như sử dụng một bài cơ bản.",
	std_huangwudie: "Chuẩn Hoàng Vũ Điệp",
	std_huangwudie_prefix: "Chuẩn",
	stdshuangrui: "Song Nhuệ",
	stdshuangrui_info: "Giai đoạn Chuẩn Bị, bạn có thể dùng một số lá bài trên tay bất kỳ xem như một 【Giết】, nếu số bài trên tay của nhân vật mục tiêu bằng bạn, 【Giết】 này không thể bị đáp trả.",
	std_qinghegongzhu: "Chuẩn Thanh Hà Công Chúa",
	std_qinghegongzhu_prefix: "Chuẩn",
	stdzengou: "Tấn Cấu",
	stdfeili: "Phỉ Ly",
	stdzengou_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể xem bài trên tay của một nhân vật và tiết lộ hai lá bài trong đó, sau đó bạn xem như sử dụng một bài cơ bản có tên khác với tên bài đã tiết lộ, nếu không thì người đó bốc một lá bài.",
	stdfeili_info: "Khi bạn chịu sát thương, bạn có thể bỏ hai lá bài hoặc khiến 【Tấn Cấu】 mất hiệu lực trong vòng này, sau đó ngăn ngừa sát thương này.",
	std_quyi: "Chuẩn Cúc Nghĩa",
	std_quyi_prefix: "Chuẩn",
	stdfuqi: "Phục Kỵ",
	stdjiaozi: "Kiêu Tư",
	stdfuqi_info: "Kỹ năng khóa, 【Giết】 do bạn và nhân vật có khoảng cách với bạn là 1 sử dụng nhắn vào nhau không thể bị đáp trả.",
	stdjiaozi_info: "Kỹ năng khóa, khi bạn gây sát thương lần đầu tiên mỗi lượt, nếu bài trên tay bạn là nhiều nhất bàn, bạn khiến sát thương này +1.",
	std_wenyuan: "Chuẩn Văn Uyên",
	std_wenyuan_prefix: "Chuẩn",
	stdkengqiang: "Khanh Cường",
	stdshangjue: "Thương Quyết",
	stdkengqiang_info: "Mỗi lượt giới hạn một lần, khi bạn dùng bài sát thương, bạn có thể chọn một: 1. Bốc hai lá bài; 2. Mất 1 điểm thể lực, khiến sát thương của bài này +1.",
	stdshangjue_info: "Kỹ năng giới hạn, khi bạn vào trạng thái hấp hối, bạn có thể hồi phục thể lực lên giới hạn thể lực, sau đó bạn có thể mất 【Khanh Cường】 để khiến kỹ năng này xem như chưa được phát động.",
	std_xushao: "Chuẩn Hứa Thiệu",
	std_xushao_prefix: "Chuẩn",
	stdyingmen: "Doanh Môn",
	stdpingjian: "Bình Giám",
	stdyingmen_info: "Giai đoạn Xuất Bài giới hạn một lần, nếu bạn không có “Phóng Khách”, bạn có thể bốc hai lá bài và đặt số lượng bài cơ bản hoặc bài chú thông thường tương ứng lên bài tướng, gọi là “Phóng Khách”.",
	stdpingjian_info: "Bạn có thể dùng một lá bài trên tay xem như “Phóng Khách”, nếu làm vậy, bạn cần bỏ một “Phóng Khách” bất kỳ.",
	std_zhangxuan: "Chuẩn Trương Huyền",
	std_zhangxuan_prefix: "Chuẩn",
	stdtongli: "Đồng Lễ",
	stdshezang: "Xa Táng",
	stdtongli_info: "Giai đoạn Xuất Bài giới hạn một lần, khi bạn dùng bài, nếu số bài bạn đã dùng trong giai đoạn này bằng X, bạn có thể khiến bài này kết toán thêm một lần (X là số hoa của bài trên bàn).",
	stdshezang_info: "Khi bạn vào trạng thái hấp hối, bạn có thể di chuyển tối đa bốn lá bài trên bàn đến khu vực Trang Bị của bạn.",
	std_jushou: "Chuẩn Thư Thọ",
	std_jushou_prefix: "Chuẩn",
	stdjianying: "Tiệm Doanh",
	stdshibei: "Thỉ Bắc",
	stdjianying_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể di chuyển một lá bài trên bàn, sau đó lần đầu tiên bạn dùng bài cùng hoa hoặc cùng điểm số với lá bài này trong giai đoạn này, bạn bốc một lá bài",
	stdshibei_info: "Kỹ năng giới hạn, sau khi bạn chịu sát thương, bạn hồi phục 1 điểm thể lực.",
	std_kebineng_prefix: "Chuẩn",
	std_kebineng: "Chuẩn Kha Tỷ Năng",
	stdkoujing: "Khấu Tinh",
	stdkoujing_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể dùng một số lá bài trên tay bất kỳ xem như một 【Giết】 không giới hạn khoảng cách và số lần; sau khi nhân vật khác chịu sát thương do 【Giết】 này gây ra, người đó có thể đổi bài trên tay với bạn.",
	std_niujin_prefix: "Chuẩn",
	std_niujin: "Chuẩn Ngưu Kim",
	stdcuorui: "Thoái Nhuệ",
	stdcuorui_info: "Khi bắt đầu ván chơi và khi bạn giết nhân vật khác, bạn có thể bốc bài trên tay lên X lá (X là số nhân vật trên bàn và tối đa là 7)",
	std_ganfuren_prefix: "Chuẩn",
	std_ganfuren: "Chuẩn Cam Phu Nhân",
	stdzhijie: "Trí Giới",
	stdzhijie_info: "Mỗi vòng giới hạn một lần, khi bắt đầu giai đoạn Xuất Bài của một nhân vật, bạn có thể tiết lộ một lá bài trên tay của người đó. Ba lần đầu tiên trong giai đoạn này người đó dùng bài cùng loại với lá bài này, bạn bốc một lá bài. ",
	stdshushenx: "Thục Thận",
	stdshushenx_info: "Khi kết thúc mỗi lượt, nếu bạn đã nhận được ba lá bài trở lên trong lượt này, bạn có thể khiến một nhân vật khác hồi phục 1 điểm thể lực.",
	std_wangshen_prefix: "Chuẩn",
	std_wangshen: "Chuẩn Vương Thẩm",
	stdanran: "Ngạn Nhiên",
	stdanran_info: "Sau khi bạn chịu sát thương, bạn có thể bốc một lá bài, sau đó số bài bốc bằng cách này lần tiếp theo +1 (tối đa bốn lá). ",
	stdgaobian: "Cáo Biến",
	stdgaobian_info: "Kỹ năng khóa, khi kết thúc lượt của nhân vật khác, nếu trong lượt này chỉ có một nhân vật chịu sát thương, nhân vật bị thương này chọn sử dụng một 【Giết】 đã vào bộ bài bỏ trong lượt này hoặc thiết lập lại “Ngạn Nhiên”.",
	std_caojinyu_prefix: "Chuẩn",
	std_caojinyu: "Chuẩn Tào Kim Ngọc",
	stdyuqi: "Ngung Khấp",
	stdyuqi_info: "Nhân vật có khoảng cách đến bạn nhỏ hơn hoặc bằng thể lực hiện tại của bạn sau khi chịu sát thương, bạn có thể khiến người đó bốc một lá bài.",
	stdshanshen: "Thiện Thân",
	stdshanshen_info: "Khi một nhân vật chết, nếu nguồn gây sát thương không phải là bạn, bạn có thể hồi phục 1 điểm thể lực.",
	std_lvboshe_prefix: "Chuẩn",
	std_lvboshe: "Chuẩn Lã Bá Xa",
	stdfushi: "Phược Thỉ",
	stdfushi_info: "Sau khi 【Giết】 do nhân vật có khoảng cách với bạn là 1 sử dụng lần đầu tiên mỗi lượt kết toán xong, bạn nhận được nó. Bạn có thể dùng một số 【Giết】 bất kỳ xem như một 【Giết】 có thể chỉ định tối đa số lượng mục tiêu tương đương.",
	std_wuke_prefix: "Chuẩn",
	std_wuke: "Chuẩn Ngô Kha",
	stdanda: "Ám Đạt",
	stdanda_info: "Mỗi vòng giới hạn một lần, khi một nhân vật vào trạng thái hấp hối, bạn có thể khiến nguồn gây sát thương đưa cho người đó một lá bài, nếu không thì người đó hồi phục 1 điểm thể lực.",
	stdzhuguo: "Trợ Quốc",
	stdzhuguo_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể khiến một nhân vật bốc bài trên tay lên hai lá.",
};

export default translates;
