import { lib, game, ui, get, ai, _status } from "noname";

const translates = {
	jilin: "Tập Lân",
	jilin_info: "①Khi trò chơi bắt đầu, bạn đem hai lá bài trên cùng của chồng bài đặt úp lên thẻ võ tướng, gọi là “Chí”. ②Khi bạn trở thành mục tiêu của lá bài do nhân vật khác sử dụng, bạn có thể lật ngửa một lá “Chí” đang úp để khiến lá bài đó vô hiệu với bạn. ③Khi bắt đầu lượt, bạn có thể dùng bất kỳ số lượng bài trên tay nào để thay thế số lượng tương đương các lá “Chí” đang úp.",
	//Hài tử, nhượng lao thần tư mã hạ khứ bồi lao đại ba
	yingyou: "Anh Du",
	yingyou_info: "①Khi bắt đầu giai đoạn ra bài, bạn có thể lật ngửa một lá “Chí” rồi rút X lá bài (X là số lượng “Chí” đang ngửa). ②Khi bạn mất một lá bài có cùng hoa với một trong các lá “Chí” đang ngửa, bạn rút một lá bài.",
	yingtian: "Ứng Thiên",
	yingtian_info: `Kỹ năng thức tỉnh. Sau khi một nhân vật tử vong, nếu số lượng thế lực trên sân không lớn hơn 2, bạn nhận được ${get.poptip("reguicai")}, ${get.poptip("rewansha")}, ${get.poptip("lianpo")} và mất đi 〖Anh Du〗, đồng thời trong ván game này bạn sử dụng bài không bị giới hạn khoảng cách.`,

	shen_luxun: "Thần Lục Tốn",
	shen_luxun_prefix: "Thần",
	nzry_junlve: "Quân Lược",
	nzry_junlve_info: "Kỹ năng khóa định, khi bạn chịu hoặc gây ra sát thương, bạn nhận được X dấu ấn “Quân Lược” (X là điểm sát thương).",
	nzry_cuike: "Thôi Khắc",
	nzry_cuike_info: "Khi bắt đầu giai đoạn ra bài, nếu số lượng dấu ấn “Quân Lược” là số lẻ, bạn có thể gây cho một nhân vật 1 điểm sát thương; nếu số lượng dấu ấn “Quân Lược” là số chẵn, bạn có thể hoành trí một nhân vật và bỏ một lá bài trong khu vực của người đó. Sau đó, nếu số lượng dấu ấn “Quân Lược” vượt quá 7 cái, bạn có thể xóa bỏ toàn bộ dấu ấn “Quân Lược” và gây cho tất cả nhân vật khác 1 điểm sát thương.",
	nzry_dinghuo: "Trị Phóng",
	nzry_dinghuo_info: "Kỹ năng hạn định, giai đoạn ra bài, bạn có thể xóa bỏ toàn bộ dấu ấn “Quân Lược”, khiến tối đa số lượng tương đương các nhân vật đang bị hoành trí bỏ tất cả bài trong khu trang bị. Sau đó, bạn gây cho một nhân vật trong số đó 1 điểm hỏa sát thương.",
	shen_liubei: "Thần Lưu Bị",
	shen_liubei_prefix: "Thần",
	nzry_longnu: "Long Nộ",
	nzry_longnu_info: "Kỹ năng chuyển hoán, Kỹ năng khóa định, Dương: Khi bắt đầu giai đoạn ra bài, bạn mất 1 điểm sinh lực và rút một lá bài, sau đó trong giai đoạn này các lá bài màu đỏ trên tay bạn đều xem như Hỏa 【Sát】 và không bị giới hạn khoảng cách. Âm: Khi bắt đầu giai đoạn ra bài, bạn giảm 1 điểm giới hạn sinh lực và rút một lá bài, sau đó trong giai đoạn này các lá bài Cẩm nang trên tay bạn đều xem như Lôi 【Sát】 và không bị giới hạn số lần sử dụng.",
	nzry_jieying: "Kết Doanh",
	nzry_jieying_info: "Kỹ năng khóa định, khi trò chơi bắt đầu hoặc khi thẻ võ tướng của bạn trọng trí, bạn bị hoành trí; tất cả các nhân vật đang bị hoành trí có giới hạn bài trên tay +2; giai đoạn kết thúc, bạn hoành trí một nhân vật khác.",

	shen_ganning: "Thần Cam Ninh",
	shen_ganning_prefix: "Thần",
	shen_zhangliao: "Thần Trương Liêu",
	shen_zhangliao_prefix: "Thần",

	drlt_poxi: "Phách Kích",
	drlt_poxi_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể xem bài trên tay của một nhân vật khác, sau đó bạn có thể bỏ bốn lá bài có hoa khác nhau trong số bài trên tay của bạn và người đó. Nếu làm vậy, dựa theo số lượng bài của bạn bị bỏ lần này để thực hiện các hiệu ứng sau: 0 lá, khấu trừ 1 điểm giới hạn sinh lực; 1 lá, bạn kết thúc giai đoạn ra bài và lượt này giới hạn bài trên tay -1; 3 lá, bạn hồi 1 điểm sinh lực; 4 lá, bạn rút bốn lá bài.",
	drlt_jieying: "Kiếp Doanh",
	drlt_jieying_info: "Khi bắt đầu lượt, nếu trên sân không có nhân vật nào sở hữu dấu ấn “Doanh”, bạn nhận được 1 dấu ấn “Doanh”; giai đoạn kết thúc, bạn có thể đưa một dấu ấn “Doanh” của mình cho một nhân vật; nhân vật có dấu ấn “Doanh” trong giai đoạn rút bài được rút thêm một lá, giai đoạn ra bài giới hạn số lần sử dụng 【Sát】 +1, giới hạn bài trên tay +1. Khi kết thúc lượt của nhân vật khác có “Doanh”, người đó xóa bỏ dấu ấn “Doanh”, sau đó bạn nhận tất cả bài trên tay của người đó.",
	drlt_duorui1: "Kỹ năng thất hiệu",
	drlt_duorui1_bg: "Duệ",
	drlt_duorui: "Đoạt Duệ",
	drlt_duorui_info: "Khi bạn gây sát thương cho một nhân vật khác trong giai đoạn ra bài, bạn có thể phế bỏ một ô trang bị trong khu trang bị của mình (nếu đã phế bỏ toàn bộ thì có thể bỏ qua bước này), sau đó nhận được một kỹ năng của nhân vật đó cho đến khi kết thúc lượt sau của người đó hoặc người đó tử vong (ngoại trừ kỹ năng Thức tỉnh, Hạn định, Chủ công, Ẩn nặc, Sứ mệnh và các kỹ năng đặc thù khác). Nếu làm vậy, kỹ năng đó của nhân vật này mất hiệu lực và bạn không thể phát động tiếp 〖Đoạt Duệ〗 cho đến khi bạn mất đi kỹ năng nhận được theo cách này.",
	drlt_zhiti: "Chỉ Đề",
	drlt_zhiti_info: "Kỹ năng khóa định. ①Nhân vật khác đã bị thương trong phạm vi tấn công của bạn có giới hạn bài trên tay -1; ②Khi bạn và nhân vật đã bị thương so điểm hoặc thắng 【Quyết Đấu】 / chịu sát thương do nhân vật đã bị thương gây ra, nếu đối phương / nguồn sát thương nằm trong phạm vi tấn công của bạn, bạn khôi phục một ô trang bị.",
	shen_zhaoyun: "Thần Triệu Vân",
	shen_zhaoyun_prefix: "Thần",
	shen_guanyu: "Thần Quan Vũ",
	shen_guanyu_prefix: "Thần",
	shen_lvmeng: "Thần Lã Mông",
	shen_lvmeng_prefix: "Thần",
	shen_simayi: "Thần Tư Mã Ý",
	shen_simayi_prefix: "Thần",
	shen_caocao: "Thần Tào Tháo",
	shen_caocao_prefix: "Thần",
	shen_zhugeliang: "Thần Gia Cát Lượng",
	shen_zhugeliang_prefix: "Thần",
	shen_zhouyu: "Thần Chu Du",
	shen_zhouyu_prefix: "Thần",
	shen_lvbu: "Thần Lã Bố",
	shen_lvbu_prefix: "Thần",
	xinjuejing: "Tuyệt Cảnh",
	xinjuejing_info: "Kỹ năng khóa định. ①Giới hạn bài trên tay của bạn +2. ②Khi bạn rơi vào hoặc thoát khỏi trạng thái hấp hối, bạn rút một lá bài.",
	relonghun: "Long Hồn",
	relonghun_info: "Bạn có thể đem một đến hai lá bài cùng hoa sử dụng hoặc đánh ra theo quy tắc sau: Cơ (♥) dùng như 【Đào】, Rô (♦) dùng như Hỏa 【Sát】, Chuồn (♣) dùng như 【Thiểm】, Bích (♠) dùng như 【Vô Giải Khả Kích】 thông thường. Nếu bạn chuyển hóa theo cách này bằng hai lá: bài màu đỏ, thì giá trị hồi phục hoặc sát thương của lá bài này +1; bài màu đen, thì bạn bỏ một lá bài của nhân vật lượt hiện tại.",
	xinlonghun: "Long Hồn",
	xinlonghun_info: "Bạn có thể đem bài trên tay sử dụng hoặc đánh ra theo quy tắc sau: Cơ (♥) dùng như 【Đào】, Rô (♦) dùng như Hỏa 【Sát】, Chuồn (♣) dùng như 【Thiểm】, Bích (♠) dùng như 【Vô Giải Khả Kích】.",
	longhun: "Long Hồn",
	longhun1: "Long Hồn♥︎",
	longhun2: "Long Hồn♦︎",
	longhun3: "Long Hồn♠︎",
	longhun4: "Long Hồn♣︎",
	juejing: "Tuyệt Cảnh",
	longhun_info: "Bạn có thể đem X lá bài cùng hoa sử dụng hoặc đánh ra theo quy tắc sau: Cơ (♥) dùng như 【Đào】, Rô (♦) dùng như 【Sát】 có hỏa sát thương, Chuồn (♣) dùng như 【Thiểm】, Bích (♠) dùng như 【Vô Giải Khả Kích】 (X là giá trị sinh lực hiện tại của bạn và ít nhất là 1).",
	juejing_info: "Kỹ năng khóa định. ①Giai đoạn rút bài, bạn khiến số bài rút định mức +X (X là số sinh lực bạn đã mất). ②Giới hạn bài trên tay của bạn +2.",
	wushen: "Võ Thần",
	wushen_info: "Kỹ năng khóa định. ①Các lá bài Cơ (♥) trên tay bạn đều xem như 【Sát】. ②Bạn sử dụng Cơ (♥) 【Sát】 không bị giới hạn khoảng cách và số lần, đồng thời không thể bị hưởng ứng.",
	wuhun: "Võ Hồn",
	wuhun_info: "Kỹ năng khóa định, nhân vật giết bạn lập tức rơi vào trạng thái hấp hối.",
	shelie: "Thiệp Liệp",
	gongxin: "Công Tâm",
	gongxin_discard: "Bỏ",
	gongxin_top: "Đỉnh chồng bài",
	renjie: "Nhẫn Giới",
	renjie2: "Nhẫn Giới",
	renjie_info: "Kỹ năng khóa định, khi bạn chịu 1 điểm sát thương, bạn nhận được một dấu ấn “Nhẫn”; Kỹ năng khóa định, khi bạn bỏ bài trong giai đoạn bỏ bài, bạn nhận được số lượng dấu ấn “Nhẫn” bằng với số lượng bài bị mất.",
	sbaiyin: "Bái Ấn",
	sbaiyin_info: `Kỹ năng thức tỉnh, khi bắt đầu giai đoạn chuẩn bị, nếu số lượng dấu ấn “Nhẫn” của bạn không nhỏ hơn 4, bạn giảm 1 điểm giới hạn sinh lực, sau đó nhận được ${get.poptip("jilue")}.`,
	jilue: "Cực Lược",
	jilue_info: `Khi lá bài phán xét của một nhân vật có hiệu lực, bạn có thể bỏ 1 dấu ấn “Nhẫn” và phát động ${get.poptip("jilue_guicai")}; mỗi khi bạn chịu sát thương, bạn có thể bỏ 1 dấu ấn “Nhẫn” và phát động ${get.poptip("jilue_fangzhu")}; khi bạn sử dụng bài Cẩm nang, bạn có thể bỏ 1 dấu ấn “Nhẫn” và phát động ${get.poptip("jilue_jizhi")}; giai đoạn ra bài giới hạn một lần, bạn có thể bỏ 1 dấu ấn “Nhẫn” và phát động ${get.poptip("jilue_zhiheng")}; giai đoạn ra bài, bạn có thể bỏ 1 dấu ấn “Nhẫn” và nhận được ${get.poptip("jilue_wansha")} cho đến khi kết thúc lượt.`,
	jilue_guicai: "Quỷ Tài",
	jilue_fangzhu: "Phóng Trục",
	jilue_wansha: "Hoàn Sát",
	jilue_zhiheng: "Chế Hành",
	jilue_jizhi: "Tập Trí",
	jilue_guicai_info: "Trước khi lá bài phán xét của bất kỳ nhân vật nào có hiệu lực, bạn có thể đánh ra một lá bài để thay thế nó.",
	jilue_fangzhu_info: "Sau khi chịu sát thương, bạn có thể khiến một nhân vật khác rút X lá bài (X là số sinh lực bạn đã mất), sau đó nhân vật đó lật mặt thẻ võ tướng.",
	jilue_wansha_info: "Kỹ năng khóa định. ①Trong lượt của bạn, nhân vật khác không ở trạng thái hấp hối không thể sử dụng 【Đào】. ②Khi có nhân vật rơi vào trạng thái hấp hối trong lượt của bạn, bạn khiến tất cả các kỹ năng phi khóa định của những nhân vật khác ngoại trừ người đó mất hiệu lực cho đến khi kết thúc kết toán trạng thái hấp hối này.",
	jilue_zhiheng_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ bất kỳ số lượng bài nào và rút số lượng bài tương đương, nếu bạn bỏ toàn bộ bài trên tay khi phát động 〖Chế Hành〗, bạn rút thêm một lá bài.",
	jilue_jizhi_info: "Khi bạn sử dụng bài Cẩm nang, bạn có thể rút một lá bài. Nếu lá bài này là bài Cơ bản, bạn có thể bỏ nó, sau đó khiến giới hạn bài trên tay của lượt này +1.",
	lianpo: "Liên Phá",
	lianpo_info: "Khi kết thúc lượt của một nhân vật, nếu bạn đã giết nhân vật trong lượt này, bạn có thể thực hiện một lượt bổ sung.",
	guixin: "Quy Tâm",
	qinyin: "Cầm Âm",
	yeyan: "Nghiệp Viêm",
	shelie_info: "Giai đoạn rút bài, bạn có thể đổi thành lật năm lá bài trên cùng của chồng bài, sau đó chọn lấy mỗi loại hoa bài khác nhau một lá.",
	gongxin_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể xem bài trên tay của một nhân vật khác, và có thể trưng ra một lá Cơ (♥) trong số đó, sau đó đem nó bỏ đi hoặc đặt lên đỉnh chồng bài.",
	guixin_info: "Sau khi bạn chịu 1 điểm sát thương, bạn có thể lấy một lá bài trong khu vực của mỗi nhân vật khác, sau đó bạn lật mặt.",
	qinyin_info: "Khi kết thúc giai đoạn bỏ bài, nếu bạn đã bỏ từ hai lá bài trở lên trong giai đoạn này, bạn có thể chọn một hạng mục: 1. Khiến tất cả nhân vật mỗi người hồi 1 điểm sinh lực; 2. Khiến tất cả nhân vật mỗi người mất 1 điểm sinh lực.",
	yeyan_info: "Kỹ năng hạn định, giai đoạn ra bài, bạn có thể gây cho một đến ba nhân vật tối đa tổng cộng 3 điểm hỏa sát thương (bạn có thể tùy ý phân phối điểm sát thương cho mỗi mục tiêu), nếu bạn phân phối từ 2 điểm hỏa sát thương trở lên cho một nhân vật, bạn phải bỏ bốn lá bài trên tay có hoa khác nhau trước rồi mới mất 3 điểm sinh lực.",
	qixing: "Thất Tinh",
	qixing_bg: "Tinh",
	qixing2: "Thất Tinh",
	qixing3: "Thất Tinh",
	qixing_info: "Khi trò chơi bắt đầu, bạn đem bảy lá bài trên cùng của chồng bài đặt lên thẻ võ tướng, gọi là “Tinh”. Sau đó / Khi kết thúc giai đoạn rút bài, bạn có thể dùng bất kỳ số lượng bài trên tay nào để trao đổi số lượng tương đương với các “Tinh” này.",
	dawu: "Đại Vụ",
	dawu2_bg: "Vụ",
	dawu2: "Đại Vụ",
	dawu3: "Đại Vụ",
	dawu_info: "Giai đoạn kết thúc, bạn có thể bỏ X lá “Tinh” và chỉ định số lượng nhân vật tương đương: Cho đến khi bắt đầu lượt sau của bạn, khi những nhân vật này chịu sát thương phi lôi điện, ngăn chặn sát thương này.",
	kuangfeng: "Cuồng Phong",
	kuangfeng2: "Cuồng Phong",
	kuangfeng2_bg: "Phong",
	kuangfeng3: "Cuồng Phong",
	kuangfeng_info: "Giai đoạn kết thúc, bạn có thể bỏ một lá “Tinh” và chỉ định một nhân vật: Cho đến khi bắt đầu lượt sau của bạn, khi nhân vật đó chịu hỏa sát thương, sát thương này +1.",
	baonu: "Cuồng Bạo",
	baonu_bg: "Bạo",
	baonu_info: "Kỹ năng khóa định, khi trò chơi bắt đầu, bạn nhận được hai dấu ấn “Bạo Nộ”; Kỹ năng khóa định, khi bạn gây ra / chịu 1 điểm sát thương, bạn nhận được 1 dấu ấn “Bạo Nộ”.",
	shenfen: "Thần Phẫn",
	shenfen_info: "Kỹ năng hạn định, giai đoạn ra bài, bạn có thể bỏ 6 dấu ấn Bạo Nộ, gây cho tất cả các nhân vật khác trên sân 1 điểm sát thương, sau đó khiến họ bỏ bốn lá bài.",
	wuqian: "Vô Tiền",
	wuqian_info: `Giai đoạn ra bài, bạn có thể bỏ hai dấu ấn Bạo Nộ và nhận được kỹ năng ${get.poptip("wushuang")} cho đến khi kết thúc lượt.`,
	wumou: "Vô Mưu",
	wumou_info: "Kỹ năng khóa định, khi bạn sử dụng bài Cẩm nang thông thường, bạn chọn một hạng mục: 1. Bỏ 1 dấu ấn “Bạo Nộ”; 2. Mất 1 điểm sinh lực.",
	ol_wuqian: "Vô Tiền",
	ol_wuqian_info: `Giai đoạn ra bài, bạn có thể bỏ 2 dấu ấn “Bạo Nộ” và chọn một nhân vật khác chưa từng chọn trong lượt này, bạn nhận kỹ năng ${get.poptip("wushuang")} và khiến phòng cụ của người đó vô hiệu cho đến khi kết thúc lượt.`,
	ol_shenfen: "Thần Phẫn",
	ol_shenfen_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ 6 dấu ấn “Bạo Nộ” và chọn tất cả nhân vật khác, gây cho mỗi nhân vật này 1 điểm sát thương. Sau đó những nhân vật này trước tiên bỏ hết bài trong khu trang bị, rồi mỗi người bỏ bốn lá bài trên tay. Cuối cùng bạn lật mặt thẻ võ tướng của mình.",
	new_wuhun: "Võ Hồn",
	new_wuhun_info: "Kỹ năng khóa định, khi bạn chịu sát thương, nguồn sát thương nhận được X dấu ấn “Ác Mộng” (X là điểm sát thương). Kỹ năng khóa định, khi bạn tử vong, bạn chọn một nhân vật khác có số lượng dấu ấn “Ác Mộng” nhiều nhất. Nhân vật đó tiến hành phán xét: nếu kết quả phán xét không phải là 【Đào】 hoặc 【Đào Viên Kết Nghĩa】, nhân vật đó tử vong.",
	new_guixin: "Quy Tâm",
	new_guixin_info: "Sau khi bạn chịu 1 điểm sát thương, bạn có thể dựa theo thứ tự ưu tiên khu vực bạn đã chọn để ngẫu nhiên nhận một lá bài trong khu vực của mỗi nhân vật khác, sau đó bạn lật mặt.",
	dili: "Đế Lực",
	dili_info: 'Kỹ năng khóa định. Khi trò chơi bắt đầu, bạn ngẫu nhiên nhận được một đường <span style="font-family: yuanli">Đông Ô Vận Mệnh Tuyến</span>.',
	yuheng: "Ngự Hành",
	yuheng_info: '①Giai đoạn ra bài giới hạn một lần. Bạn có thể mất toàn bộ kỹ năng phi khóa định không phải 〖Ngự Hành〗, sau đó ngẫu nhiên nhận được một kỹ năng liên quan đến toàn bộ <span style="font-family: yuanli">Đông Ô Vận Mệnh Tuyến</span>. Nếu trong giai đoạn này bạn chưa từng phát động kỹ năng phi khóa định khác, bạn ngẫu nhiên nhận được một nội dung liên quan đến <span style="font-family: yuanli">Đông Ô Vận Mệnh Tuyến</span> hiện tại. ②Khi kết thúc giai đoạn ra bài, nếu bạn chưa từng phát động 〖Ngự Hành ①〗 trong giai đoạn này, bạn mất 1 điểm sinh lực.',
	yuheng_append: '<span style="font-family: yuanli">Thiên hạ anh hùng thùy địch thủ? Tào Lưu. Sinh tử đương như Tôn Trọng Mưu!</span>',
	dili_shengzhi: "Thánh Chất",
	dili_shengzhi_info: "Kỹ năng khóa định. Nếu bạn thông qua 〖Ngự Hành〗 đã từng nhận được 〖Anh Hồn〗〖Hoằng Đức〗〖Bỉnh Nhất〗, thì khi bạn sử dụng bài có điểm số là số nguyên tố, lá bài này không thể bị hưởng ứng.",
	dili_chigang: "Trì Cương",
	dili_chigang_info: "Kỹ năng khóa định. Nếu bạn thông qua 〖Ngự Hành〗 đã từng nhận được 〖Quan Vi〗〖Bật Chính〗〖An Quốc〗, thì trước khi giai đoạn phán xét của bạn bắt đầu, bạn bỏ qua giai đoạn này và nhận thêm một giai đoạn rút bài.",
	dili_qionglan: "Khung Lãm",
	dili_qionglan_info: 'Kỹ năng khóa định, Kỹ năng hạn định. Nếu bạn thông qua 〖Ngự Hành〗 đã từng nhận được 〖Thiệp Liệp〗〖Vấn Quái〗〖Bác Đồ〗, thì sau khi kết toán 〖Ngự Hành〗 bạn phát động kết thúc, bạn ngẫu nhiên nhận được thêm hai đường <span style="font-family: yuanli">Đông Ô Vận Mệnh Tuyến</span> khác.',
	dili_quandao: "Quyền Đạo",
	dili_quandao_info: "Kỹ năng khóa định. Nếu bạn thông qua 〖Ngự Hành〗 đã từng nhận được 〖Chế Hành〗〖Giới Huấn〗〖An Tuất〗, thì các lá bài có điểm số là chữ cái trong vùng bài trên tay bạn được xem như 【Điều Tế Diêm Mai】.",
	dili_jiaohui: "Giao Huy",
	dili_jiaohui_info: "Kỹ năng khóa định. Nếu bạn thông qua 〖Ngự Hành〗 đã từng nhận được 〖Hạ Thư〗〖Kết Nhân〗〖Đế Minh〗, và số bài trên tay của bạn là 1, thì tên của lá bài này được xem như 【Viễn Giao Cận Công】.",
	dili_yuanlv: "Uyên Lự",
	dili_yuanlv_info: "Kỹ năng khóa định. Nếu bạn thông qua 〖Ngự Hành〗 đã từng nhận được 〖Quan Triều〗〖Quyết Yển〗〖Lạn Cương〗, thì khi bạn trở thành mục tiêu của bài trang bị không phải 【Trường An Đại Hạm】 do chính mình sử dụng, bạn đem lá bài này đặt vào đống bài hủy, sau đó sử dụng một lá 【Trường An Đại Hạm】 có cùng loại phụ với lá bài trang bị này.",
	changandajian_equip1: "Trường An Đại Hạm",
	changandajian_equip2: "Trường An Đại Hạm",
	changandajian_equip3: "Trường An Đại Hạm",
	changandajian_equip4: "Trường An Đại Hạm",
	changandajian_equip5: "Trường An Đại Hạm",
	changandajian_equip6: "Trường An Đại Hạm",
	changandajian_destroy: "Trường An Đại Hạm",
	changandajian_equip1_info: "Kỹ năng khóa định. Sau khi bạn mất đi 【Trường An Đại Hạm】 trong khu trang bị, bạn tiêu hủy nó. Sau đó bạn chọn một lá bài trên sân. Nếu điểm số lá bài này là chữ cái, bạn nhận lấy nó, nếu không thì bỏ nó.",
	changandajian_equip2_info: "Kỹ năng khóa định. Sau khi bạn mất đi 【Trường An Đại Hạm】 trong khu trang bị, bạn tiêu hủy nó và hồi 1 điểm sinh lực. Sau đó bạn chọn một lá bài trên sân. Nếu điểm số lá bài này là chữ cái, bạn nhận lấy nó, nếu không thì bỏ nó.",
	changandajian_equip3_info: "Kỹ năng khóa định. Khoảng cách từ nhân vật khác đến bạn +2. Sau khi bạn mất đi 【Trường An Đại Hạm】 trong khu trang bị, bạn tiêu hủy nó. Sau đó bạn chọn một lá bài trên sân. Nếu điểm số lá bài này là chữ cái, bạn nhận lấy nó, nếu không thì bỏ nó.",
	changandajian_equip4_info: "Kỹ năng khóa định. Khoảng cách từ bạn đến nhân vật khác -2. Sau khi bạn mất đi 【Trường An Đại Hạm】 trong khu trang bị, bạn tiêu hủy nó. Sau đó bạn chọn một lá bài trên sân. Nếu điểm số lá bài này là chữ cái, bạn nhận lấy nó, nếu không thì bỏ nó.",
	changandajian_equip5_info: "Kỹ năng khóa định. Giới hạn bài trên tay của bạn +2. Sau khi bạn mất đi 【Trường An Đại Hạm】 trong khu trang bị, bạn tiêu hủy nó. Sau đó bạn chọn một lá bài trên sân. Nếu điểm số lá bài này là chữ cái, bạn nhận lấy nó, nếu không thì bỏ nó.",
	changandajian_equip6_info: "Kỹ năng khóa định. Khoảng cách từ bạn đến nhân vật khác -2, khoảng cách từ nhân vật khác đến bạn +2. Sau khi bạn mất đi 【Trường An Đại Hạm】 trong khu trang bị, bạn tiêu hủy nó. Sau đó bạn chọn một lá bài trên sân. Nếu điểm số lá bài này là chữ cái, bạn nhận lấy nó, nếu không thì bỏ nó.",
	};

export default translates;
