import { lib, game, ui, get, ai, _status } from "noname";

const translates = {
//江山如故·起
	jsrg_liuhong: "Khởi Lưu Hoành",
	jsrg_liuhong_prefix: "Khởi",
	jsrgchaozheng: "Triù Tranh",
	jsrgchaozheng_info: "Giai đoạn Chuẩn Bị, bạn có thể khiến tất cả nhân vật khác nghị sự. Nếu kết quả là: đỏ, nhân vật có ý kiến màu đỏ mỗi người hồi phục 1 điểm thể lực; đen, nhân vật có ý kiến màu đỏ mỗi người mất 1 điểm thể lực. Sau đó nếu tất cả ý kiến đều giống nhau, bạn bốc X lá bài (X là số nhân vật tham gia nghị sự lần này).",
	jsrgshenchong: "Thậm Sủng",
	jsrgshenchong_info: `Kỹ năng giới hạn. Giai đoạn Xuất Bài, bạn có thể khiến một nhân vật khác nhận được ${get.poptip("jsrgfeiyang")} và ${get.poptip("jsrgbahu")}. Nếu làm vậy, khi bạn chết, người đó mất tất cả kỹ năng và bỏ tất cả bài trên tay.`,
	jsrgjulian: "Tụ Liễm",
	jsrgjulian_info: "Kỹ năng Chủ Công. ① Các nhân vật thế lực Quần khác mỗi lượt giới hạn hai lần. Khi người đó bốc bài không phải ở giai đoạn Bốc Bài và không phải vì 【Tụ Liễm】, người đó có thể bốc một lá bài. ② Giai đoạn Kết Thúc, bạn có thể nhận mỗi người một lá bài của tất cả nhân vật thế lực Quần khác.",
	jsrgfeiyang: "Phi Dương",
	jsrgfeiyang_info: "Khi bắt đầu giai đoạn Phán Định, nếu trong khu vực Phán Định của bạn có bài, bạn có thể bỏ hai lá bài trên tay và bỏ một lá bài trong khu vực Phán Định của bạn.",
	jsrgbahu: "Bạt Hỗ",
	jsrgbahu_info: "Kỹ năng khóa. ① Giai đoạn Chuẩn Bị, bạn bốc một lá bài. ② Giới hạn số lần bạn dùng 【Giết】 +1.",
	jsrg_hejin: "Khởi Hà Tiến",
	jsrg_hejin_prefix: "Khởi",
	jsrgzhaobing: "Chiếu Binh",
	jsrgzhaobing_info: "Giai đoạn Kết Thúc, bạn có thể bỏ tất cả bài trên tay, sau đó khiến tối đa X nhân vật khác lần lượt chọn một: 1. Ngửa lên đưa cho bạn một 【Giết】; 2. Mất 1 điểm thể lực (X là số bài bạn bỏ lần này).",
	jsrgzhuhuan: "Tru Hoạn",
	jsrgzhuhuan_info: "Giai đoạn Chuẩn Bị, bạn có thể tiết lộ tất cả bài trên tay và bỏ tất cả 【Giết】, sau đó khiến một nhân vật khác chọn một: 1. Bỏ số lượng bài tương ứng, sau đó chịu 1 điểm sát thương; 2. Khiến bạn bốc số lượng bài tương ứng, sau đó bạn hồi phục 1 điểm thể lực.",
	jsrgyanhuo: "Diên Họa",
	jsrgyanhuo_info: "Kỹ năng khóa. Khi bạn chết, bạn thêm kỹ năng toàn cục sau: khi có nhân vật dùng 【Giết】, lượng sát thương cơ bản của 【Giết】 này +1.",
	jsrg_sunjian: "Khởi Tôn Kiên",
	jsrg_sunjian_prefix: "Khởi",
	jsrgpingtao: "Bình Thảo",
	jsrgpingtao_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể khiến một nhân vật khác chọn một: 1. Đưa cho bạn một lá bài, sau đó giới hạn số lần bạn dùng 【Giết】 trong lượt này +1; 2. Khiến bạn xem như sử dụng một 【Giết】 nhắn vào người đó.",
	jsrgjuelie: "Tuyệt Liệt",
	jsrgjuelie_info: "① Khi bạn dùng 【Giết】 chỉ định một nhân vật làm mục tiêu, bạn có thể bỏ một số lá bài bất kỳ và bỏ số lượng bài tương ứng của người đó. ② Nếu số bài trên tay hoặc thể lực của bạn là nhỏ nhất bàn, thì 【Giết】 bạn dùng gây sát thương +1.",
	jsrg_huangfusong: "Khởi Hoàng Phủ Tùng",
	jsrg_huangfusong_prefix: "Khởi",
	jsrgguanhuo: "Quan Hỏa",
	jsrgguanhuo_info: "Giai đoạn Xuất Bài, bạn có thể xem như sử dụng một 【Hỏa Công】. Sau khi 【Hỏa Công】 chưa từng gây sát thương mà bạn dùng bằng cách này kết toán xong, nếu số lần bạn phát động 【Quan Hỏa】 trong giai đoạn này: là 1, thì sát thương do 【Hỏa Công】 bạn dùng trong giai đoạn này gây ra +1; không là 1, bạn mất 【Quan Hỏa】.",
	jsrgjuxia: "Cư Hạ",
	jsrgjuxia_info: "Mỗi lượt giới hạn một lần. Khi nhân vật khác dùng bài chỉ định bạn làm mục tiêu, nếu số kỹ năng của người đó nhiều hơn bạn, người đó có thể khiến bài này vô hiệu với bạn, sau đó khiến bạn bốc hai lá bài.",
	jsrg_new_juxia: "Cư Hạ",
	jsrg_new_juxia_info: "Mỗi lượt giới hạn một lần. Khi nhân vật khác dùng bài chỉ định bạn làm mục tiêu, nếu số kỹ năng của người đó nhiều hơn bạn, bạn có thể bốc hai lá bài.",
	jsrg_xushao: "Khởi Hứa Thiệu",
	jsrg_xushao_prefix: "Khởi",
	jsrgyingmen: "Doanh Môn",
	jsrgyingmen_info: "Kỹ năng khóa. ① Khi bắt đầu ván chơi, bạn đặt bốn lá bài tướng ngẫu nhiên từ bộ bài tướng lên bài tướng của bạn, gọi là “Phóng Khách”. ② Khi bắt đầu lượt, nếu số “Phóng Khách” của bạn nhỏ hơn 4, bạn ngẫu nhiên bổ sung “Phóng Khách” từ bộ bài tướng lên bốn lá.",
	jsrgpingjian: "Bình Giám",
	jsrgpingjian_info: "Bạn có thể phát động kỹ năng này vào thời điểm thỏa mãn điều kiện kỹ năng trên “Phóng Khách” của bạn có nhãn không có kỹ năng hoặc chỉ có kỹ năng khóa, sau đó bạn chọn bỏ một “Phóng Khách”. Nếu bỏ đúng “Phóng Khách” của kỹ năng vừa phát động lần này, bạn bốc một lá bài.",
	jsrg_dongbai: "Khởi Đổng Bạch",
	jsrg_dongbai_prefix: "Khởi",
	jsrgshichong: "Thị Sủng",
	jsrgshichong_info: "Kỹ năng chuyển hóa. Khi bạn dùng bài chỉ định nhân vật khác làm mục tiêu duy nhất, Dương: bạn có thể nhận một lá bài trên tay của nhân vật mục tiêu; Âm: nhân vật mục tiêu có thể đưa cho bạn một lá bài trên tay.",
	jsrglianzhu: "Liên Tru",
	jsrglianzhu_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể tiết lộ một lá bài đen trên tay và đưa cho một nhân vật khác, sau đó xem như bạn lần lượt dùng một 【Quá Hà Sách Kiều】 nhắn vào tất cả nhân vật khác cùng thế lực với người đó.",
	jsrg_new_lianzhu: "Liên Tru",
	jsrg_new_lianzhu_info: "Giai đoạn Kết Thúc, bạn có thể xem như dùng một 【Quá Hà Sách Kiều】, sau khi kết toán, mục tiêu duy nhất của bài này phải chọn một: 1. Mất 1 điểm thể lực; 2. Khiến bạn phát động 【Liên Tru】 nhắn vào nhà dưới của người đó.",
	jsrg_qiaoxuan: "Khởi Kiều Huyền",
	jsrg_qiaoxuan_prefix: "Khởi",
	jsrgjuezhi: "Tuyệt Chất",
	jsrgjuezhi_info: "① Khi bạn mất một lá bài Trang Bị trong khu vực Trang Bị, bạn có thể phế bỏ ô Trang Bị tương ứng. ② Mỗi giai đoạn trong lượt của bạn giới hạn một lần. Khi bạn dùng bài gây sát thương cho nhân vật mục tiêu, bạn khiến sát thương này +X (X là số lượng bài trong khu vực Trang Bị của người đó có cùng phân loại phụ với các ô Trang Bị bạn đã phế bỏ).",
	jsrg_new_juezhi: "Tuyệt Chất",
	jsrg_new_juezhi_info: "① Khi bạn mất một lá bài Trang Bị trong khu vực Trang Bị, bạn có thể phế bỏ ô Trang Bị tương ứng và bốc hai lá bài. ② Khi một nhân vật chịu sát thương trong lượt của bạn, nếu trong khu vực Trang Bị của người đó có bài cùng phân loại phụ với ô Trang Bị bạn đã phế bỏ, bạn có thể khiến sát thương này +1.",
	jsrgjizhao: "Cấp Triệu",
	jsrgjizhao_info: "Giai đoạn Chuẩn Bị hoặc giai đoạn Kết Thúc, bạn có thể khiến một nhân vật chọn một: 1. Sử dụng một lá bài trên tay; 2. Khiến bạn có thể di chuyển một lá bài trong khu vực của người đó.",
	jsrg_yangbiao: "Khởi Dương Bưu",
	jsrg_yangbiao_prefix: "Khởi",
	jsrgzhaohan: "Chiêu Hán",
	jsrgzhaohan_info: "Kỹ năng khóa. Giai đoạn Chuẩn Bị, nếu trong ván chơi này: chưa xào bài, bạn hồi phục 1 điểm thể lực; đã xào bài, bạn mất 1 điểm thể lực.",
	jsrgrangjie: "Nhượng Tiết",
	jsrgrangjie_info: "Sau khi bạn chịu 1 điểm sát thương, bạn có thể di chuyển một lá bài trên bàn, sau đó bạn có thể chọn nhận từ bộ bài bỏ một lá bài vào bộ bài bỏ trong lượt này và cùng hoa với bài này.",
	jsrgyizheng: "Nghĩa Tranh",
	jsrgyizheng_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể thi điểm với một nhân vật có số bài trên tay lớn hơn bạn. Nếu bạn: thắng, người đó bỏ qua giai đoạn Bốc Bài tiếp theo; không thắng, người đó có thể gây cho bạn tối đa 2 điểm sát thương.",
	jsrg_kongrong: "Khởi Khổng Dung",
	jsrg_kongrong_prefix: "Khởi",
	jsrglirang: "Lễ Nhượng",
	jsrglirang_info: "Mỗi vòng giới hạn một lần. Khi bắt đầu giai đoạn Bốc Bài của nhân vật khác, bạn có thể đưa cho người đó hai lá bài. Sau đó khi kết thúc giai đoạn Bỏ Bài của lượt này, bạn có thể nhận được tất cả bài mà người đó đã bỏ vào bộ bài bỏ trong giai đoạn này.",
	jsrgzhengyi: "Tranh Nghĩa",
	jsrgzhengyi_info: "Khi bạn chịu sát thương lần đầu tiên mỗi lượt, nhân vật khác đã nhận được bài vì 【Lễ Nhượng】 trong vòng này có thể chuyển sát thương này cho người đó.",
	jsrg_new_lirang: "Lễ Nhượng",
	jsrg_new_lirang_info: "Khi bắt đầu mỗi vòng, bạn có thể chọn tối đa hai nhân vật khác và lật ngửa bốn lá bài trên cùng bộ bài, những nhân vật này có thể lần lượt nhận một số lá bài bất kỳ trong số đó, sau đó bạn nhận số bài còn lại.",
	jsrg_new_zhengyi: "Tranh Nghĩa",
	jsrg_new_zhengyi_info: "Khi nhân vật có số bài nhận được vì 【Lễ Nhượng】 ít nhất duy nhất trong vòng này chịu sát thương lần đầu tiên mỗi lượt, nhân vật có số bài nhận được vì 【Lễ Nhượng】 nhiều nhất duy nhất trong vòng này có thể chuyển sát thương này cho người đó.",
	jsrg_zhujun: "Khởi Chu Tuấn",
	jsrg_zhujun_prefix: "Khởi",
	jsrgfendi: "Phân Địch",
	jsrgfendi_info: "Mỗi lượt giới hạn một lần. Khi bạn dùng 【Giết】 chỉ định mục tiêu duy nhất, bạn có thể tiết lộ một số lá bài bất kỳ trên tay của người đó, khiến người đó không thể dùng hoặc đánh ra bài có bài thực thể tương ứng không hoàn toàn là những lá bài này cho đến khi 【Giết】 này kết toán xong. Sau đó khi 【Giết】 này gây sát thương cho người đó, bạn nhận được những lá bài này từ khu vực bài trên tay hoặc bộ bài bỏ của người đó.",
	jsrgjuxiang: "Cự Tương",
	jsrgjuxiang_info: "Khi bạn nhận được bài không phải ở giai đoạn Bốc Bài, bạn có thể bỏ số bài đó, khiến nhân vật trong lượt hiện tại trong giai đoạn Xuất Bài định mức của lượt này, giới hạn số lần dùng 【Giết】 +X (X là số hoa của bài bạn bỏ bằng cách này).",
	jsrg_liubei: "Khởi Lưu Bị",
	jsrg_liubei_prefix: "Khởi",
	jsrgjishan: "Tích Thiện",
	jsrgjishan_info: "Mỗi lượt mỗi hạng mục giới hạn một lần. ① Khi một nhân vật chịu sát thương, bạn có thể mất 1 điểm thể lực và ngăn ngừa sát thương này, sau đó bạn và người đó mỗi người bốc một lá bài. ② Sau khi bạn gây sát thương, bạn có thể khiến một nhân vật có thể lực nhỏ nhất mà bạn đã phát động 【Tích Thiện①】 nhắn vào người đó hồi phục 1 điểm thể lực.",
	jsrgzhenqiao: "Chấn Sao",
	jsrgzhenqiao_info: "Kỹ năng khóa. ① Phạm vi tấn công của bạn +1. ② Khi bạn dùng 【Giết】 chỉ định mục tiêu, nếu khe Vũ Khí của bạn trống và chưa bị phế bỏ, bạn khiến hiệu ứng của 【Giết】 này kết toán thêm một lần.",
	jsrg_wangyun: "Khởi Vương Doãn",
	jsrg_wangyun_prefix: "Khởi",
	jsrgshelun: "Xá Luận",
	jsrgshelun_info: "Giai đoạn Xuất Bài giới hạn một lần, nếu bạn có bài trên tay, bạn có thể chọn một nhân vật khác, sau đó khiến tất cả nhân vật khác ngoại trừ người đó có số bài trên tay không lớn hơn bạn nghị sự. Nếu kết quả là: đỏ, bạn bỏ hai lá bài của người đó; đen, bạn gây cho người đó 2 điểm sát thương.",
	jsrgfayi: "Phạt Dị",
	jsrgfayi_info: "Khi nghị sự của bạn kết toán xong, bạn có thể gây 1 điểm sát thương cho một số lượng nhân vật bất kỳ có ý kiến khác với bạn.",
	jsrg_liuyan: "Khởi Lưu Yên",
	jsrg_liuyan_prefix: "Khởi",
	jsrgtushe: "Đồ Xạ",
	jsrgtushe_info: "Khi bạn dùng bài không phải Trang Bị chỉ định mục tiêu, bạn có thể tiết lộ tất cả bài trên tay (không có bài thì không tiết lộ). Nếu bạn không có bài cơ bản, bạn có thể bốc X lá bài (X là số mục tiêu mà bài này chỉ định).",
	jsrgtongjue: "Thông Tuyệt",
	jsrgtongjue_info: "Kỹ năng Chủ Công. Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể đưa một số lá bài bất kỳ cho số lượng nhân vật thế lực Quần khác tương ứng. Sau đó bạn không thể dùng bài chỉ định những nhân vật này làm mục tiêu cho đến khi kết thúc lượt.",
	jsrg_caocao: "Mộng Tào Tháo",
	jsrg_caocao_prefix: "Mộng",
	jsrgzhenglve: "Chính Lược",
	jsrgzhenglve_info: "① Khi kết thúc lượt của vị trí số một, bạn có thể bốc một lá bài, sau đó khiến một nhân vật chưa có dấu hiệu “Liệp” nhận được “Liệp” (nếu vị trí số một trong lượt này chưa gây sát thương thì đổi thành tối đa hai người). ② Bạn dùng bài nhắn vào nhân vật có “Liệp” không giới hạn khoảng cách và số lần. ③ Mỗi lượt giới hạn một lần. Khi bạn gây sát thương cho nhân vật có “Liệp”, bạn có thể bốc một lá bài và nhận được bài đã gây ra sát thương này.",
	jsrgzhenglve_info_identity: "① Khi kết thúc lượt của Chủ Công, bạn có thể bốc một lá bài, sau đó khiến một nhân vật chưa có dấu hiệu “Liệp” nhận được “Liệp” (nếu Chủ Công trong lượt này chưa gây sát thương thì đổi thành tối đa hai người). ② Bạn dùng bài nhắn vào nhân vật có “Liệp” không giới hạn khoảng cách và số lần. ③ Mỗi lượt giới hạn một lần. Khi bạn gây sát thương cho nhân vật có “Liệp”, bạn có thể bốc một lá bài và nhận được bài đã gây ra sát thương này.",
	jsrghuilie: "Hội Liệp",
	jsrghuilie_info: "Kỹ năng giác tỉnh. Giai đoạn Chuẩn Bị, nếu số nhân vật có “Liệp” lớn hơn 2, bạn giảm 1 điểm giới hạn thể lực, sau đó nhận được 【Bình Nhung】 và 【Phi Ảnh】.",
	jsrgpingrong: "Bình Nhung",
	jsrgpingrong_info: "Mỗi vòng giới hạn một lần. Khi kết thúc lượt của một nhân vật, bạn có thể bỏ “Liệp” của một nhân vật, sau đó bạn thực hiện một lượt bổ sung sau lượt này. Sau khi lượt đó kết thúc, nếu bạn chưa gây sát thương trong lượt đó, bạn mất 1 điểm thể lực.",
	jsrg_nanhualaoxian: "Khởi Nam Hoa Lão Tiên",
	jsrg_nanhualaoxian_prefix: "Khởi",
	jsrgshoushu: "Thụ Thuật",
	jsrgshoushu_info: "Kỹ năng khóa. ① Khi bắt đầu mỗi vòng, nếu trên bàn không có 【Thái Bình Yếu Thuật】, bạn có thể lấy 【Thái Bình Yếu Thuật】 từ ngoài trò chơi đặt vào khu vực Trang Bị của một nhân vật. ② Khi 【Thái Bình Yếu Thuật】 rời khỏi khu vực Trang Bị của một nhân vật, bạn khiến bài này bị hủy.",
	jsrgxundao: "Tầm Đạo",
	jsrgxundao_info: "Trước khi lá bài phán định của bạn có hiệu lực, bạn có thể khiến tối đa hai nhân vật lần lượt bỏ một lá bài, sau đó bạn chọn một lá bài đã bỏ bằng cách này và đang nằm trong bộ bài bỏ để thay thế lá bài phán định này.",
	jsrglinghua: "Linh Hóa",
	jsrglinghua_info: "① Giai đoạn Chuẩn Bị, bạn có thể thực hiện hiệu ứng 【Sấm Sét】 với nhân vật mục tiêu là bạn. Nếu bạn không vì vậy chịu sát thương, bạn có thể khiến một nhân vật hồi phục 1 điểm thể lực. ② Giai đoạn Kết Thúc, bạn có thể thực hiện hiệu ứng 【Sấm Sét】 với nhân vật mục tiêu là bạn và hiệu ứng phán định bị đảo ngược. Nếu bạn không vì vậy chịu sát thương, bạn có thể gây cho một nhân vật 1 điểm sát thương Lôi.",
	sbyingmen: "Doanh Môn",
	sbyingmen_info: "Kỹ năng khóa. ① Khi bắt đầu ván chơi, bạn đặt bốn lá bài tướng ngẫu nhiên từ bộ bài tướng lên bài tướng của bạn, gọi là “Phóng Khách”. ② Khi bắt đầu lượt, bạn có thể chọn có bỏ một số lượng “Phóng Khách” bất kỳ hay không, sau đó nếu số “Phóng Khách” của bạn nhỏ hơn 4, bạn ngẫu nhiên bổ sung “Phóng Khách” từ bộ bài tướng lên bốn lá.",
	sbpingjian: "Bình Giám",
	sbpingjian_info: "Bạn có thể phát động kỹ năng này vào thời điểm thỏa mãn điều kiện kỹ năng trên “Phóng Khách” của bạn có nhãn không có kỹ năng hoặc chỉ có kỹ năng khóa, sau đó bạn chọn bỏ một “Phóng Khách”. Nếu bỏ đúng “Phóng Khách” của kỹ năng vừa phát động lần này, thì bạn bốc một lá bài khi kỹ năng này kết toán xong.",
	//江山如故·承
	jsrg_sunce: "Mộng Tôn Sách",
	jsrg_sunce_prefix: "Mộng",
	jsrgduxing: "Độc Hành",
	jsrgduxing_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể xem như sử dụng một 【Quyết Đấu】 có thể chỉ định một số lượng nhân vật mục tiêu bất kỳ, và bài đỏ trên tay của bạn cũng như tất cả nhân vật mục tiêu đều được xem là 【Giết】 cho đến khi bài này kết toán xong.",
	jsrgzhiheng: "Chế Hoành",
	jsrgzhiheng_info: "Kỹ năng khóa. Khi bạn vì thực hiện hiệu ứng của bài mà gây sát thương cho nhân vật mục tiêu, nếu trong lượt này người đó đã đáp trả bài bạn đã dùng, sát thương này +1.",
	jsrgzhasi: "Trá Tử",
	jsrgzhasi_info: "Kỹ năng giới hạn. Khi bạn chịu sát thương có giá trị không nhỏ hơn thể lực của bạn, bạn có thể ngăn ngừa sát thương này, sau đó mất 【Chế Hoành】 và nhận được 【Chế Hành】. Sau đó bạn không được tính vào khoảng cách và thứ tự chỗ ngồi cho đến khi bạn dùng bài nhắn vào nhân vật khác hoặc khi bạn chịu sát thương.",
	jsrgbashi: "Bá Thế",
	jsrgbashi_info: "Kỹ năng Chủ Công, mỗi lượt giới hạn bốn lần, khi bạn cần đánh ra 【Giết】 hoặc 【Tránh】, bạn có thể khiến nhân vật thế lực Ngô khác chọn có đánh ra một 【Giết】 hoặc 【Tránh】 hay không. Nếu có nhân vật đáp ứng, thì xem như bạn đã đánh ra một 【Giết】 hoặc 【Tránh】.",
	jsrg_xuyou: "Thừa Hứa Du",
	jsrg_xuyou_prefix: "Thừa",
	jsrglipan: "Ly Phản",
	jsrglipan_info: "Khi kết thúc lượt, bạn có thể đổi thế lực, sau đó bốc X lá bài và thực hiện một giai đoạn Xuất Bài bổ sung. Khi giai đoạn này kết thúc, tất cả nhân vật cùng thế lực với bạn lần lượt có thể dùng một lá bài xem như 【Quyết Đấu】 sử dụng nhắn vào bạn (X là số nhân vật khác cùng thế lực với bạn).",
	jsrgqingxi: "Khinh Tập",
	jsrgqingxi_info: "Kỹ năng thế lực Quần. Giai đoạn Xuất Bài mỗi nhân vật giới hạn một lần. Bạn có thể chọn một nhân vật có số bài trên tay nhỏ hơn bạn, bạn bỏ bài trên tay xuống bằng với người đó, sau đó xem như sử dụng một 【Giết】 găm nhắn vào người đó.",
	jsrgjinmie: "Tận Diệt",
	jsrgjinmie_info: "Kỹ năng thế lực Ngụy. Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể chọn một nhân vật có số bài trên tay lớn hơn bạn, bạn xem như sử dụng một 【Giết】 Hỏa nhắn vào người đó. Khi bài này gây sát thương, bạn bỏ bài trên tay của người đó xuống bằng với bạn.",
	jsrg_lvbu: "Thừa Lữ Bố",
	jsrg_lvbu_prefix: "Thừa",
	jsrgwuchang: "Vô Thường",
	jsrgwuchang_info: "Kỹ năng khóa. ① Khi bạn nhận được bài của nhân vật khác, bạn đổi thế lực thành giống với người đó. ② Khi bạn dùng 【Giết】 hoặc 【Quyết Đấu】 gây sát thương cho nhân vật mục tiêu cùng thế lực với bạn, sát thương này +1, sau đó đổi thế lực thành Quần.",
	jsrgqingjiao: "Khinh Giảo",
	jsrgqingjiao_info: "Kỹ năng thế lực Quần. Giai đoạn Xuất Bài mỗi hạng mục giới hạn một lần. Bạn có thể dùng một lá bài xem như 【Thôi Tâm Trí Phúc】 / 【Sấn Hỏa Đả Kiếp】 nhắn vào một nhân vật có số bài trên tay lớn hơn / nhỏ hơn bạn.",
	jsrgchengxu: "Thừa Hư",
	jsrgchengxu_info: "Kỹ năng thế lực Thục. Nhân vật khác cùng thế lực với bạn không thể đáp trả bài bạn dùng.",
	jsrg_zhanghe: "Thừa Trương Hợp",
	jsrg_zhanghe_prefix: "Thừa",
	jsrgqiongtu: "Cùng Đồ",
	jsrgqiongtu_info: "Kỹ năng thế lực Quần. Mỗi lượt giới hạn một lần. Bạn có thể đặt một lá bài không phải cơ bản lên bài tướng xem như sử dụng một 【Vô Tiết Khả Kích】. Nếu bài này có hiệu lực, bạn bốc một lá bài, nếu không thì bạn đổi thế lực thành Ngụy và nhận được tất cả bài “Cùng Đồ”.",
	jsrgxianzhu: "Tiên Trứ",
	jsrgxianzhu_info: "Kỹ năng thế lực Ngụy. Bạn có thể dùng một bài chú thông thường xem như 【Giết】 không giới hạn số lần. Khi bài này gây sát thương cho mục tiêu duy nhất, bạn xem như sử dụng một bài chú thông thường này nhắn vào nhân vật đó.",
	jsrg_zoushi: "Thừa Trâu Thị",
	jsrg_zoushi_prefix: "Thừa",
	jsrgguyin: "Cô Ngâm",
	jsrgguyin_info: "Giai đoạn Chuẩn Bị, bạn có thể lật úp, và khiến tất cả nhân vật nam khác lần lượt chọn có lật úp hay không. Sau đó bạn và tất cả nhân vật úp mặt lần lượt mỗi người bốc một lá bài, cho đến khi các bạn tích lũy nhận được X lá bài bằng cách này (X là số nhân vật nam trong số nhân vật còn sống và đã chết).",
	jsrgzhangdeng: "Chướng Đăng",
	jsrgzhangdeng_info: "① Khi một nhân vật úp mặt cần sử dụng 【Rượu】, nếu bài tướng của bạn úp, người đó có thể xem như sử dụng nó. ② Khi một nhân vật phát động 【Chướng Đăng①】 lần thứ hai trong một lượt, bạn lật ngửa bài tướng lên.",
	jsrg_guanyu: "Thừa Quan Vũ",
	jsrg_guanyu_prefix: "Thừa",
	jsrgguanjue: "Quán Tuyệt",
	jsrgguanjue_info: "Kỹ năng khóa. Khi bạn dùng hoặc đánh ra bài có hoa, bạn khiến tất cả nhân vật khác trong lượt này không thể dùng hoặc đánh ra bài có hoa đó.",
	jsrgnianen: "Niệm Ân",
	jsrgnianen_info: "Bạn có thể dùng một lá bài xem như bài cơ bản bất kỳ để dùng hoặc đánh ra, sau đó nếu bài này không phải màu đỏ hoặc bài bạn dùng hoặc đánh ra bằng cách này không phải 【Giết】 thường, thì cho đến khi kết thúc lượt này, kỹ năng này mất hiệu lực và bạn xem như có 【Mã Thuật】.",
	jsrg_chendeng: "Thừa Trần Đăng",
	jsrg_chendeng_prefix: "Thừa",
	jsrglunshi: "Luận Thế",
	jsrglunshi_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể khiến một nhân vật bốc số lá bài bằng số nhân vật trong phạm vi tấn công của người đó (tối đa bốc đến năm lá), sau đó người đó bỏ số lá bài bằng số nhân vật có phạm vi tấn công bao gồm người đó.",
	jsrgguitu: "Quỷ Đồ",
	jsrgguitu_info: "Giai đoạn Chuẩn Bị, bạn có thể đổi chỗ hai lá bài Vũ Khí trên bàn, sau đó nhân vật có phạm vi tấn công giảm vì cách này sẽ hồi phục 1 điểm thể lực.",
	jsrg_zhenji: "Thừa Chân Mật",
	jsrg_zhenji_prefix: "Thừa",
	jsrgjixiang: "Tế Hương",
	jsrgjixiang_info: "Trong lượt, mỗi tên bài giới hạn một lần. Khi một nhân vật khác cần dùng hoặc đánh ra một lá bài cơ bản, bạn có thể bỏ một lá bài khiến người đó xem như dùng hoặc đánh ra nó, sau đó bạn bốc một lá bài và khiến giới hạn số lần phát động 【Xưng Hiền】 trong giai đoạn này +1.",
	jsrgchengxian: "Xưng Hiền",
	jsrgchengxian_info: "Giai đoạn Xuất Bài giới hạn hai lần. Bạn có thể dùng một lá bài trên tay xem như một bài chú thông thường chưa dùng bằng cách này trong lượt này (bài chuyển hóa này cần có cùng số mục tiêu hợp lệ với bài trên tay được chuyển hóa).",
	jsrg_zhangliao: "Thừa Trương Liêu",
	jsrg_zhangliao_prefix: "Thừa",
	jsrgzhengbing: "Chỉnh Binh",
	jsrgzhengbing_info: "Kỹ năng thế lực Quần. Giai đoạn Xuất Bài giới hạn ba lần. Bạn có thể tái luyện một lá bài, nếu lá bài này là: 【Giết】, trong lượt này giới hạn bài trên tay bạn +2; 【Tránh】, bạn bốc một lá bài; 【Đào】, bạn đổi thế lực thành Ngụy.",
	jsrgtuwei: "Đột Vi",
	jsrgtuwei_info: "Kỹ năng thế lực Ngụy. Khi bắt đầu giai đoạn Xuất Bài, bạn có thể nhận mỗi người một lá bài của một số lượng nhân vật bất kỳ trong phạm vi tấn công. Sau đó khi kết thúc lượt này, những nhân vật này chưa chịu sát thương trong lượt này sẽ lần lượt nhận một lá bài của bạn.",
	jsrg_xugong: "Thừa Hứa Cống",
	jsrg_xugong_prefix: "Thừa",
	jsrgbiaozhao: "Biểu Triệu",
	jsrgbiaozhao_info: "Giai đoạn Chuẩn Bị, bạn có thể chọn một nhân vật khác. Cho đến khi bắt đầu lượt tiếp theo của bạn hoặc khi bạn vào trạng thái hấp hối, các nhân vật khác ngoài người đó dùng bài nhắn vào người đó không giới hạn số lần, và sát thương do người đó dùng bài nhắn vào bạn gây ra +1.",
	jsrgyechou: "Nghiệp Thù",
	jsrgyechou_info: "Khi bạn chết, bạn có thể khiến một nhân vật khác nhận được hiệu ứng sau: khi người đó chịu sát thương có giá trị không nhỏ hơn thể lực của người đó, người đó khiến sát thương này tăng gấp đôi.",
	jsrg_chunyuqiong: "Thừa Thuần Vu Quỳnh",
	jsrg_chunyuqiong_prefix: "Thừa",
	jsrgcangchu: "Thương Trữ",
	jsrgcangchu_info: "Giai đoạn Kết Thúc của một nhân vật, bạn có thể khiến tối đa X nhân vật mỗi người bốc một lá bài, nếu X lớn hơn số nhân vật còn sống, thì đổi thành mỗi người bốc hai lá bài (X là số bài bạn nhận được trong lượt này).",
	jsrgshishou: "Thất Thủ",
	jsrgshishou_info: "Kỹ năng khóa. ① Khi bạn dùng 【Rượu】, bạn bốc ba lá bài, sau đó bạn không thể dùng bài trong lượt này nữa. ② Khi bạn chịu sát thương Hỏa, bạn khiến 【Thương Trữ】 mất hiệu lực cho đến sau khi kết thúc lượt tiếp theo của bạn.",
	//江山如故·转
	ying: "Ảnh",
	ying_info: "Khi bài này vào bộ bài bỏ, hệ thống đưa bài này ra khỏi trò chơi.",
	jsrg_guojia: "Mộng Quách Gia",
	jsrg_guojia_prefix: "Mộng",
	jsrgqingzi: "Khinh Tư",
	jsrgqingzi_info: "Giai đoạn Chuẩn Bị, bạn có thể bỏ mỗi người một lá bài trong khu vực Trang Bị của một số lượng nhân vật khác bất kỳ, sau đó khiến những nhân vật này nhận được 【Thần Tốc】 cho đến khi bắt đầu lượt tiếp theo của bạn.",
	jsrgdingce: "Định Sách",
	jsrgdingce_info: "Sau khi bạn chịu sát thương, bạn có thể lần lượt bỏ mỗi người một lá bài trên tay của bạn và nguồn gây sát thương. Nếu hai lá bài này cùng màu, bạn xem như sử dụng một 【Động Trúc Tiên Cơ】.",
	jsrgzhenfeng: "Châm Phong",
	jsrgzhenfeng_info: "Giai đoạn Xuất Bài mỗi loại giới hạn một lần. Bạn có thể xem như sử dụng một bài cơ bản hoặc bài chú thông thường có trong mô tả kỹ năng của nhân vật còn sống (không giới hạn khoảng cách và số lần). Khi bài này có hiệu lực đối với nhân vật có mô tả kỹ năng chứa bài này, bạn gây cho người đó 1 điểm sát thương.",
	jsrg_zhangfei: "Chuyển Trương Phi",
	jsrg_zhangfei_prefix: "Chuyển",
	jsrgbaohe: "Bạo Hát",
	jsrgbaohe_info: "Khi kết thúc giai đoạn Xuất Bài của một nhân vật, bạn có thể bỏ hai lá bài, sau đó xem như bạn dùng một 【Giết】 nhắn vào tất cả nhân vật có phạm vi tấn công bao gồm người đó. Khi một nhân vật dùng bài đáp trả 【Giết】 này, 【Giết】 này gây sát thương cho các nhân vật mục tiêu tiếp theo +1.",
	jsrgxushi: "Hư Thế",
	jsrgxushi_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể đưa cho một số lượng nhân vật bất kỳ mỗi người một lá bài, sau đó bạn nhận được gấp đôi số lượng đó 【Ảnh】.",
	jsrg_machao: "Chuyển Mã Siêu",
	jsrg_machao_prefix: "Chuyển",
	jsrgzhuiming: "Truy Mệnh",
	jsrgzhuiming_info: "Khi bạn dùng 【Giết】 chỉ định mục tiêu duy nhất, bạn có thể tuyên bố một màu và khiến nhân vật mục tiêu bỏ một số lá bài bất kỳ, sau đó bạn tiết lộ một lá bài của nhân vật mục tiêu. Nếu màu của lá bài này giống với màu bạn tuyên bố, thì 【Giết】 này không tính vào giới hạn số lần, không thể bị đáp trả và gây sát thương +1.",
	jsrg_lougui: "Chuyển Lâu Khuê",
	jsrg_lougui_prefix: "Chuyển",
	jsrgshacheng: "Sa Thành",
	jsrgshacheng_info: "① Khi bắt đầu ván chơi, bạn đặt hai lá bài trên cùng bộ bài lên bài tướng, gọi là “Thành”. ② Khi một nhân vật dùng 【Giết】 kết toán xong, bạn có thể bỏ một “Thành”, khiến một trong các nhân vật mục tiêu của bài này bốc X lá bài (X là số bài người đó đã mất trong lượt này và tối đa là 5).",
	jsrgninghan: "Ngưng Hàn",
	jsrgninghan_info: "Kỹ năng khóa. ① 【Giết】 ♣ trong bài trên tay của tất cả nhân vật đều được xem là 【Giết】 Băng. ② Khi một nhân vật chịu sát thương đóng băng, bạn đặt bài thực thể tương ứng gây ra sát thương này vào “Thành”.",
	jsrg_zhangren: "Chuyển Trương Nhậm",
	jsrg_zhangren_prefix: "Chuyển",
	jsrgfuni: "Phục Nặc",
	jsrgfuni_info: "Kỹ năng khóa. ① Giá trị cuối của phạm vi tấn công của bạn là 0. ② Khi bắt đầu mỗi vòng, bạn khiến một số lượng nhân vật bất kỳ nhận được tổng cộng X 【Ảnh】 (X là một nửa số nhân vật còn sống, làm tròn lên). ③ Khi có bài vào bộ bài bỏ, nếu trong đó có 【Ảnh】, bạn dùng bài trong lượt này không giới hạn khoảng cách và không thể bị đáp trả.",
	jsrgchuanxin: "Xuyên Tâm",
	jsrgchuanxin_info: "Giai đoạn Kết Thúc của một nhân vật, bạn có thể dùng một lá bài xem như 【Giết】. Khi một nhân vật chịu sát thương với kênh là 【Giết】 này, sát thương này +Y (Y là thể lực người đó đã hồi phục trong lượt này).",
	jsrg_huangzhong: "Chuyển Hoàng Trung",
	jsrg_huangzhong_prefix: "Chuyển",
	jsrgcuifeng: "Thôi Phong",
	jsrgcuifeng_info: "Kỹ năng giới hạn. Giai đoạn Xuất Bài, bạn có thể xem như sử dụng một lá bài loại sát thương đơn mục tiêu (không giới hạn khoảng cách). Khi kết thúc lượt này, nếu tổng giá trị sát thương mà mục tiêu của bài này chịu trong lượt này không phải là 1, bạn thiết lập lại tất cả kỹ năng trên bài tướng.",
	jsrgdengnan: "Đăng Nan",
	jsrgdengnan_info: "Kỹ năng giới hạn. Giai đoạn Xuất Bài, bạn có thể xem như sử dụng một bài chú thông thường không phải sát thương. Khi kết thúc lượt này, nếu tất cả mục tiêu của bài này đều chịu sát thương trong lượt này, bạn thiết lập lại tất cả kỹ năng trên bài tướng.",
	jsrg_xiahourong: "Chuyển Hạ Hầu Vinh",
	jsrg_xiahourong_prefix: "Chuyển",
	jsrgfenjian: "Phấn Kiếm",
	jsrgfenjian_info: "Mỗi lượt mỗi hạng mục giới hạn một lần. Khi bạn cần dùng 【Quyết Đấu】 hoặc 【Đào】 nhắn vào nhân vật khác, bạn có thể khiến sát thương bạn chịu trong lượt này +1, xem như sử dụng nó.",
	jsrg_sunshangxiang: "Chuyển Tôn Thượng Hương",
	jsrg_sunshangxiang_prefix: "Chuyển",
	jsrgguiji: "Khuê Kỵ",
	jsrgguiji_info: "Mỗi lượt giới hạn một lần. Giai đoạn Xuất Bài, bạn có thể đổi bài trên tay với một nhân vật nam có số bài trên tay nhỏ hơn bạn. Sau đó khi kết thúc giai đoạn Xuất Bài tiếp theo của người đó, bạn có thể đổi bài trên tay với người đó.",
	jsrgjiaohao: "Kiêu Hào",
	jsrgjiaohao_info: "① Giai đoạn Xuất Bài của nhân vật khác giới hạn một lần. Người đó có thể đặt một lá bài Trang Bị trong tay vào khu vực Trang Bị của bạn. ② Giai đoạn Chuẩn Bị, bạn nhận được X 【Ảnh】 (X là một nửa số ô Trang Bị trống của bạn, làm tròn lên).",
	jsrg_pangtong: "Chuyển Bàng Thống",
	jsrg_pangtong_prefix: "Chuyển",
	jsrgmanjuan: "Mạn Quyển",
	jsrgmanjuan_info: "Nếu bạn không có bài trên tay, bạn có thể dùng hoặc đánh ra bài đã vào bộ bài bỏ trong lượt này như bài trên tay (mỗi điểm số mỗi lượt giới hạn một lần).",
	jsrgyangming: "Dưỡng Danh",
	jsrgyangming_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể thi điểm với một nhân vật, nếu người đó: không thắng, bạn có thể lặp lại quy trình này với người đó; thắng, người đó bốc X lá bài, sau đó bạn hồi phục 1 điểm thể lực (X là số lần người đó không thắng trong giai đoạn này).",
	jsrg_hansui: "Chuyển Hàn Toại",
	jsrg_hansui_prefix: "Chuyển",
	jsrgniluan: "Nghịch Loạn",
	jsrgniluan_info: "Giai đoạn Chuẩn Bị, bạn có thể chọn bất kỳ hạng mục nào: 1. Bỏ một lá bài, gây 1 điểm sát thương cho một nhân vật chưa gây sát thương cho bạn; 2. Khiến một nhân vật đã gây sát thương cho bạn bốc hai lá bài.",
	jsrghuchou: "Hỗ Thù",
	jsrghuchou_info: "Kỹ năng khóa. Khi bạn gây sát thương cho nhân vật cuối cùng đã dùng bài loại sát thương nhắn vào bạn, sát thương này +1.",
	jsrgjiemeng: "Giai Minh",
	jsrgjiemeng_info: "Kỹ năng Chủ Công, kỹ năng khóa. Khoảng cách từ tất cả nhân vật thế lực Quần đến nhân vật khác -X (X là số nhân vật thế lực Quần).",
	jsrg_zhangchu: "Chuyển Trương Sở",
	jsrg_zhangchu_prefix: "Chuyển",
	jsrghuozhong: "Hoặc Chúng",
	jsrghuozhong_info: "Tất cả nhân vật giai đoạn Xuất Bài giới hạn một lần. Người đó có thể đặt một lá bài đen không phải chú vào khu vực Phán Định của mình xem như 【Binh Lương Đoạn】, sau đó khiến bạn bốc hai lá bài.",
	jsrgrihui: "Nhật Huệ",
	jsrgrihui_info: "① Khi bạn dùng 【Giết】 gây sát thương cho nhân vật mục tiêu, bạn có thể khiến các nhân vật khác có bài trong khu vực Phán Định mỗi người bốc một lá bài. ② 【Giết】 đầu tiên bạn dùng trong một lượt nhắn vào nhân vật không có bài trong khu vực Phán Định không có bất kỳ giới hạn số lần nào.",
	jsrg_xiahouen: "Chuyển Hạ Hầu Ân",
	jsrg_xiahouen_prefix: "Chuyển",
	jsrghujian: "Hộ Kiếm",
	jsrghujian_info: "① Khi bắt đầu ván chơi, bạn lấy một 【Xích Huyết Thanh Phong】 từ ngoài trò chơi. ② Khi kết thúc lượt của một nhân vật, nhân vật cuối cùng dùng hoặc đánh ra bài trong lượt này có thể nhận được 【Xích Huyết Thanh Phong】 trong bộ bài bỏ.",
	jsrgshili: "Thị Lực",
	jsrgshili_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể dùng một lá bài Trang Bị trên tay xem như 【Quyết Đấu】.",
	jsrg_fanjiangzhangda: "Chuyển Phạm Cường Trương Đạt",
	jsrg_fanjiangzhangda_ab: "Chuyển Phạm Cương Trương Đạt",
	jsrg_fanjiangzhangda_prefix: "Chuyển",
	jsrgfushan: "Phụ Sơn",
	jsrgfushan_info: "Khi bắt đầu giai đoạn Xuất Bài, tất cả nhân vật khác có thể lần lượt đưa cho bạn một lá bài và khiến giới hạn số lần bạn dùng 【Giết】 trong giai đoạn này +1. Khi kết thúc giai đoạn này, nếu số lần bạn dùng 【Giết】 chưa đạt giới hạn và tất cả nhân vật đã đưa bài cho bạn bằng cách này trong giai đoạn này đều còn sống, bạn mất 2 điểm thể lực, nếu không thì bạn bốc bài trên tay lên giới hạn thể lực.",
	//江山如故·合
	jsrg_zhugeliang: "Mộng Gia Cát Lượng",
	jsrg_zhugeliang_prefix: "Mộng",
	jsrgwentian: "Vấn Thiên",
	jsrgwentian_info: "① Bạn có thể dùng bài trên cùng bộ bài xem như 【Vô Tiết Khả Kích】/【Hỏa Công】, nếu bài này không phải đen/đỏ, 【Vấn Thiên】 mất hiệu lực trong vòng này. ② Mỗi lượt giới hạn một lần. Khi bắt đầu một giai đoạn của bạn, bạn có thể xem năm lá bài trên cùng bộ bài, sau đó đưa một lá bài trong số đó cho một nhân vật khác, đặt những lá bài còn lại lên đỉnh hoặc đáy bộ bài theo bất kỳ thứ tự nào.",
	jsrgchushi: "Xuất Sư",
	jsrgchushi_info: "Giai đoạn Xuất Bài giới hạn một lần. Nếu bạn không phải là Chủ Công, bạn có thể nghị sự với Chủ Công. Nếu kết quả là: đỏ, bạn và người đó mỗi người bốc một lá bài, nếu tổng số bài trên tay bạn và người đó nhỏ hơn 7, lặp lại quy trình này; đen, khi bạn gây sát thương thuộc tính trong vòng này, sát thương này +1.",
	jsrgyinlve: "Ẩn Lược",
	jsrgyinlve_info: "Mỗi vòng mỗi hạng mục giới hạn một lần. Khi một nhân vật chịu sát thương Hỏa / Lôi, bạn có thể ngăn ngừa sát thương này, sau đó sau khi kết thúc lượt hiện tại, thực hiện một lượt chỉ có giai đoạn Bốc Bài / Bỏ Bài.",
	jsrg_jiangwei: "Hợp Khương Duy",
	jsrg_jiangwei_prefix: "Hợp",
	jsrgjinfa: "Căng Phạt",
	jsrgjinfa_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể tiết lộ một lá bài trên tay, sau đó khiến tất cả nhân vật có giới hạn thể lực không lớn hơn bạn nghị sự. Nếu kết quả cùng màu với bài này: giống, bạn khiến tối đa hai người trong số đó bốc bài trên tay lên giới hạn thể lực; khác, bạn nhận được hai 【Ảnh】. Sau đó nếu không có nhân vật khác cùng ý kiến với bạn, bạn có thể đổi thế lực.",
	jsrgfumou: "Phục Mưu",
	jsrgfumou_info: "Kỹ năng thế lực Ngụy. Khi nghị sự của bạn kết toán xong, nhân vật có ý kiến khác với bạn trong lượt này không thể dùng hoặc đánh ra bài có màu giống với ý kiến của họ, bạn có thể dùng một 【Ảnh】 xem như 【Xuất Kỳ Bất Ý】 nhắn vào một nhân vật có ý kiến khác với bạn.",
	jsrgxuanfeng: "Tuyển Phong",
	jsrgxuanfeng_info: "Kỹ năng thế lực Thục. Bạn có thể dùng một 【Ảnh】 xem như 【Giết】 găm không giới hạn khoảng cách và số lần.",
	jsrg_luxun: "Hợp Lục Tốn",
	jsrg_luxun_prefix: "Hợp",
	jsrgyoujin: "Dụ Tiến",
	jsrgyoujin_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể thi điểm với một nhân vật, bạn và người đó trong lượt này không thể dùng hoặc đánh ra bài trên tay có điểm số nhỏ hơn điểm số bài thi điểm của mình, và nhân vật thắng xem như dùng một 【Giết】 nhắn vào nhân vật thua.",
	jsrgdailao: "Đãi Lao",
	jsrgdailao_info: "Giai đoạn Xuất Bài, nếu bạn không có bài trên tay có thể dùng, bạn có thể tiết lộ tất cả bài trên tay và bốc hai lá bài, sau đó kết thúc lượt này.",
	jsrgzhubei: "Trục Bắc",
	jsrgzhubei_info: "Kỹ năng khóa. ① Khi bạn gây sát thương cho nhân vật đã chịu sát thương trong lượt này, sát thương này +1. ② Bạn dùng bài nhắn vào nhân vật đã mất lá bài cuối cùng trên tay trong lượt này không giới hạn số lần.",
	jsrg_zhaoyun: "Hợp Triệu Vân",
	jsrg_zhaoyun_prefix: "Hợp",
	jsrglonglin: "Long Lâm",
	jsrglonglin_info: "Khi nhân vật khác lần đầu tiên dùng 【Giết】 chỉ định mục tiêu đầu tiên trong giai đoạn Xuất Bài của họ, bạn có thể bỏ một lá bài khiến 【Giết】 này vô hiệu, sau đó người đó có thể xem như dùng một 【Quyết Đấu】 nhắn vào bạn, sau khi bạn gây sát thương bằng cách này, người đó không thể dùng bài trên tay trong giai đoạn này nữa.",
	jsrgzhendan: "Trấn Đảm",
	jsrgzhendan_info: "① Bạn có thể dùng một lá bài không phải cơ bản trên tay xem như bài cơ bản bất kỳ để dùng hoặc đánh ra. ② Khi bạn chịu sát thương hoặc khi kết thúc mỗi vòng, bạn bốc X lá bài và khiến kỹ năng này mất hiệu lực trong vòng này (X là số lượt đã được thực hiện bởi tất cả nhân vật trong vòng này và tối đa là 5).",
	jsrg_simayi: "Hợp Tư Mã Ý",
	jsrg_simayi_prefix: "Hợp",
	jsrgyingshi: "Ưng Thệ",
	jsrgyingshi_info: "Khi bạn lật úp, bạn có thể xem ba lá bài dưới đáy bộ bài (nếu số nhân vật đã chết lớn hơn 2 thì đổi thành năm lá), sau đó đặt một số lượng bài bất kỳ trong số đó lên đỉnh bộ bài theo bất kỳ thứ tự nào, số còn lại đặt xuống đáy bộ bài theo bất kỳ thứ tự nào.",
	jsrgtuigu: "Thoái Cốt",
	jsrgtuigu_info: "① Khi bắt đầu lượt, bạn có thể lật úp và khiến giới hạn bài trên tay của bạn trong lượt này +X, sau đó bốc X lá bài và xem như sử dụng một 【Giải Giáp Quy Điền】 (X là một nửa số nhân vật còn sống, làm tròn xuống), nhân vật mục tiêu không thể dùng bài nhận được bằng cách này cho đến khi kết thúc lượt của họ. ② Khi kết thúc mỗi vòng, nếu bạn chưa thực hiện lượt nào trong vòng này, thì bạn thực hiện một lượt bổ sung. ③ Khi bạn mất bài trong khu vực Trang Bị, bạn hồi phục 1 điểm thể lực.",
	jsrg_guoxun: "Hợp Quách Tuần",
	jsrg_guoxun_prefix: "Hợp",
	jsrgeqian: "Át Tiền",
	jsrgeqian_info: "① Giai đoạn Kết Thúc, bạn có thể tích mưu một số lần bất kỳ. ② Khi bạn dùng 【Giết】 hoặc bài tích mưu chỉ định nhân vật khác làm mục tiêu duy nhất, bạn có thể khiến bài này không tính vào giới hạn số lần và nhận được một lá bài của mục tiêu, sau đó người đó có thể khiến khoảng cách từ bạn đến người đó trong lượt này +2.",
	jsrgfusha: "Phục Sát",
	jsrgfusha_info: "Kỹ năng giới hạn. Giai đoạn Xuất Bài, nếu trong phạm vi tấn công của bạn chỉ có một nhân vật, bạn có thể gây cho người đó X điểm sát thương (X là phạm vi tấn công của bạn, tối đa bằng số người chơi).",
	jsrg_sunlubansunluyu: "Hợp Đại Tiểu Hổ",
	jsrg_sunlubansunluyu_prefix: "Hợp",
	jsrgdaimou: "Đãi Mưu",
	jsrgdaimou_info: "Mỗi lượt mỗi hạng mục giới hạn một lần. Khi một nhân vật dùng 【Giết】 chỉ định nhân vật khác / bạn làm mục tiêu, bạn có thể dùng bài trên cùng bộ bài để tích mưu / bạn phải bỏ một lá bài tích mưu trong khu vực của bạn.",
	jsrgfangjie: "Phương Khiết",
	jsrgfangjie_info: "Giai đoạn Chuẩn Bị, nếu bạn không có bài tích mưu, bạn hồi phục 1 điểm thể lực và bốc một lá bài, nếu không thì bạn có thể bỏ một số lượng bài tích mưu bất kỳ trong khu vực của bạn và mất 【Phương Khiết】.",
	jsrg_caofang: "Hợp Tào Phương",
	jsrg_caofang_prefix: "Hợp",
	jsrgzhaotu: "Chiếu Đồ",
	jsrgzhaotu_info: "Mỗi vòng giới hạn một lần. Bạn có thể dùng một lá bài đỏ không phải chú xem như 【Lạc Bất Tư Thục】, sau khi kết thúc lượt hiện tại, mục tiêu thực hiện một lượt bổ sung với giới hạn bài trên tay -2.",
	jsrgjingju: "Kinh Cụ",
	jsrgjingju_info: "Khi bạn cần sử dụng bất kỳ loại bài cơ bản nào, bạn có thể di chuyển một lá bài trong khu vực Phán Định của nhân vật khác đến khu vực Phán Định của bạn, xem như bạn đã sử dụng nó.",
	jsrgweizhui: "Nguy Trụy",
	jsrgweizhui_info: "Kỹ năng Chủ Công. Khi kết thúc lượt của nhân vật thế lực Ngụy khác, người đó có thể dùng một lá bài đen trên tay xem như 【Quá Hà Sách Kiều】 nhắn vào bạn.",
	jsrg_sunjun: "Hợp Tôn Tuấn",
	jsrg_sunjun_prefix: "Hợp",
	jsrgyaoyan: "Yêu Yến",
	jsrgyaoyan_info: "Giai đoạn Chuẩn Bị, bạn có thể khiến tất cả nhân vật lần lượt chọn có nghị sự khi kết thúc lượt hay không, nếu kết quả nghị sự là: đỏ, bạn nhận được mỗi người một lá bài trên tay của một số lượng nhân vật bất kỳ không nghị sự; đen, bạn có thể gây cho một nhân vật nghị sự 2 điểm sát thương.",
	jsrgbazheng: "Bá Chính",
	jsrgbazheng_info: "Khi ý kiến được tiết lộ trong nghị sự mà bạn tham gia, ý kiến của nhân vật đã chịu sát thương do bạn gây ra trong lượt này được xem là giống với bạn.",
	jsrg_liuyong: "Hợp Lưu Vĩnh",
	jsrg_liuyong_prefix: "Hợp",
	jsrgdanxin: "Đan Tâm",
	jsrgdanxin_info: "Bạn có thể dùng X lá bài xem như 【Thôi Tâm Trí Phúc】 (X là số lần phát động kỹ năng này trong lượt này), bạn tiết lộ bài đã đưa ra và nhận được bằng cách này, nhân vật nhận được bài ♥ bằng cách này hồi phục 1 điểm thể lực và bốc một lá bài, sau đó khoảng cách từ bạn đến nhân vật mục tiêu +1 cho đến khi kết thúc lượt.",
	jsrgfengxiang: "Phong Hương",
	jsrgfengxiang_info: "Kỹ năng khóa, sau khi bạn gây ra hoặc chịu sát thương lần đầu tiên mỗi lượt, bạn đổi tất cả bài trong khu vực Trang Bị với một nhân vật khác. Nếu số bài trong khu vực Trang Bị của bạn vì vậy giảm, bạn bốc số lá bài bằng số bài đã giảm.",
	jsrg_weiwenzhugezhi: "Hợp Vệ Ôn Gia Cát Trực",
	jsrg_weiwenzhugezhi_prefix: "Hợp",
	jsrgfuhai: "Phù Hải",
	jsrgfuhai_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể khiến tất cả nhân vật khác có bài trên tay đồng thời tiết lộ một lá bài trên tay, sau đó bạn chọn một hướng và bốc X lá bài (X là số lượng bài có điểm số liên tục tăng nghiêm ngặt hoặc giảm nghiêm ngặt của các nhân vật theo hướng đó, tối thiểu là 1).",
	jsrg_zhangxuan: "Hợp Trương Huyền",
	jsrg_zhangxuan_prefix: "Hợp",
	jsrgtongli: "Đồng Lễ",
	jsrgtongli_info: "Khi bạn dùng bài cơ bản hoặc bài chú thông thường chỉ định mục tiêu đầu tiên trong giai đoạn Xuất Bài, nếu số hoa trong bài trên tay bạn bằng với số bài bạn đã dùng trong giai đoạn này, thì bạn có thể tiết lộ tất cả bài trên tay, khiến bài này kết toán thêm một lần.",
	jsrgshezang: "Xa Táng",
	jsrgshezang_info: "Mỗi vòng giới hạn một lần. Khi bạn hoặc nhân vật khác trong lượt của bạn vào trạng thái hấp hối, bạn có thể lật ngửa bốn lá bài trên cùng bộ bài, nhận được một số lá bài bất kỳ có hoa khác nhau trong số đó.",
	jsrg_gaoxiang: "Hợp Cao Tường",
	jsrg_gaoxiang_prefix: "Hợp",
	jsrgchiying: "Trì Ứng",
	jsrgchiying_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể chọn một nhân vật, khiến các nhân vật khác trong phạm vi tấn công của người đó lần lượt bỏ một lá bài. Nếu số bài cơ bản bỏ bằng cách này không lớn hơn thể lực của người đó, người đó nhận được những bài cơ bản đó.",
	jsrg_guozhao: "Hợp Quách Chiếu",
	jsrg_guozhao_prefix: "Hợp",
	jsrgpianchong: "Thiên Sủng",
	jsrgpianchong_info: "Giai đoạn Kết Thúc của một nhân vật, nếu bạn đã mất bài trong lượt này, bạn có thể phán định. Nếu kết quả là đỏ / đen, bạn bốc số lượng bài bằng số bài đỏ / đen đã vào bộ bài bỏ trong lượt này.",
	jsrgzunwei: "Tôn Vị",
	jsrgzunwei_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể chọn một nhân vật khác và chọn thực hiện một hạng mục, sau đó loại bỏ hạng mục đó: 1. Bốc bài trên tay lên bằng với người đó (tối đa bốc năm lá); 2. Di chuyển bài Trang Bị của người đó đến khu vực Trang Bị của bạn, cho đến khi số bài trong khu vực Trang Bị của bạn không ít hơn người đó; 3. Hồi phục thể lực lên bằng với người đó.",

	xumou_jsrg: "Tích Mưu",
	xumou_jsrg_info: "Bài “Tích Mưu” có thể tồn tại nhiều lần trong khu vực Phán Định. Khi bắt đầu giai đoạn Phán Định, bạn chọn một: ⒈ Sử dụng bài thực thể tương ứng của bài này, sau đó trong giai đoạn này không thể dùng bài có tên bài này nữa; ⒉ Đặt tất cả bài “Tích Mưu” vào bộ bài bỏ.",

	jsrg_yuanshao: "Mộng Viên Thiệu",
	jsrg_yuanshao_prefix: "Mộng",
	jsrgzhimeng: "Chấp Minh",
	jsrgzhimeng_info: "Giai đoạn Chuẩn Bị, bạn có thể lật ngửa X lá bài trên cùng bộ bài (X là số nhân vật còn sống), sau đó khiến tất cả nhân vật đồng thời tiết lộ một lá bài trên tay. Nếu có nhân vật tiết lộ bài có hoa khác với tất cả nhân vật khác, thì những nhân vật này nhận được tất cả bài có hoa đó từ những lá bài đã lật.",
	jsrgtianyu: "Thiên Dữ",
	jsrgtianyu_info: "Khi một lá bài có nhãn “sát thương” hoặc bài Trang Bị bị đặt vào bộ bài bỏ, nếu lá bài này trong lượt này chưa từng nằm trong khu vực bài trên tay hoặc khu vực Trang Bị của bất kỳ nhân vật nào, thì bạn có thể nhận được nó.",
	jsrgzhuni: "Tru Nghịch",
	jsrgzhuni_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể khiến tất cả nhân vật đồng thời chọn một nhân vật khác ngoại trừ bạn. Nếu có nhân vật trong lượt này có số lần được chỉ định nhiều nhất duy nhất, thì bạn trong lượt này dùng bài nhắn vào nhân vật đó không có giới hạn về số lần và khoảng cách.",
	jsrghezhi: "Hợp Chí",
	jsrghezhi_info: "Kỹ năng Chủ Công, kỹ năng khóa. Các nhân vật thế lực Quần khác khi cần chọn nhân vật vì 【Tru Nghịch】, sẽ đổi thành chọn nhân vật mà bạn đã chọn lần này.",
	jsrg_caojiewangfu: "Suy Tào Tiết Vương Phủ",
	jsrg_caojiewangfu_prefix: "Suy",
	jsrgzonghai: "Túng Hại",
	jsrgzonghai_info: "Mỗi vòng giới hạn một lần. Khi có nhân vật khác vào trạng thái hấp hối, bạn có thể khiến người đó chọn tối đa hai nhân vật. Các nhân vật không được chọn không thể dùng bài trong quá trình kết toán hấp hối này, và sau khi kết toán trạng thái hấp hối này xong, bạn gây cho mỗi nhân vật mà người đó đã chọn 1 điểm sát thương.",
	jsrgjueyin: "Tuyệt Nhân",
	jsrgjueyin_info: "Khi bạn chịu sát thương lần đầu tiên trong một lượt, bạn có thể bốc ba lá bài, sau đó trong lượt này tất cả nhân vật chịu sát thương +1.",
	jsrg_songhuanghou: "Suy Tống Hoàng Hậu",
	jsrg_songhuanghou_prefix: "Suy",
	jsrgzhongzen: "Chúng Tấn",
	jsrgzhongzen_info: "Kỹ năng khóa. ① Khi bắt đầu giai đoạn Bỏ Bài, bạn khiến tất cả nhân vật có số bài trên tay nhỏ hơn bạn mỗi người đưa cho bạn một lá bài trên tay. ② Khi kết thúc giai đoạn Bỏ Bài, nếu số bài ♠ bạn bỏ trong giai đoạn này lớn hơn thể lực của bạn, thì bạn bỏ tất cả bài.",
	jsrgxuchong: "Hư Sủng",
	jsrgxuchong_info: "Khi bạn trở thành mục tiêu của bài, bạn có thể chọn một: ⒈ Bốc một lá bài; ⒉ Khiến nhân vật trong lượt hiện tại, giới hạn bài trên tay trong lượt này +2. Sau khi chọn xong, bạn nhận được một 【Ảnh】.",
	jsrg_zhangjiao: "Suy Trương Giác",
	jsrg_zhangjiao_prefix: "Suy",
	jsrgxiangru: "Tương Nhu",
	jsrgxiangru_info: "Khi một nhân vật khác đã bị thương / bạn chịu sát thương trí mạng, bạn / nhân vật khác đã bị thương có thể đưa cho nguồn gây sát thương hai lá bài, sau đó ngăn ngừa sát thương này.",
	jsrgwudao: "Ngộ Đạo",
	jsrgwudao_info: "Kỹ năng giác tỉnh. Khi một nhân vật vào trạng thái hấp hối, nếu bạn không có bài trên tay, thì bạn tăng 1 điểm giới hạn thể lực và hồi phục 1 điểm thể lực, sau đó nhận được 【Kinh Lôi】.",
	jsrgjinglei: "Kinh Lôi",
	jsrgjinglei_info: "Giai đoạn Chuẩn Bị, bạn có thể chọn một nhân vật khác A, sau đó chọn một số lượng nhân vật bất kỳ có tổng số bài trên tay nhỏ hơn A, khiến những nhân vật này lần lượt gây cho A 1 điểm sát thương Lôi.",
	jsrg_yangqiu: "Suy Dương Cầu",
	jsrg_yangqiu_prefix: "Suy",
	jsrgsaojian: "Tảo Gian",
	jsrgsaojian_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể xem bài trên tay của một nhân vật khác, sau đó tiết lộ một lá bài trong đó (không hiển thị cho chính nhân vật đó). Sau đó nhân vật đó lặp lại việc bỏ một lá bài trên tay, cho đến khi người đó bỏ được năm lá bài / bỏ đúng lá bài bạn đã chọn / không còn bài trên tay để bỏ. Nếu số bài trên tay của người đó sau khi bỏ xong lớn hơn bạn, thì bạn mất 1 điểm thể lực.",
	mbsaojian: "Tảo Gian",
	mbsaojian_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể xem bài trên tay của một nhân vật khác và chọn một lá bài trong đó (đồng đội có thể gợi ý bài để bỏ cho bạn), sau đó nhân vật đó lặp lại việc bỏ một lá bài trên tay, cho đến khi người đó bỏ được năm lá bài / bỏ đúng lá bài bạn đã chọn / không còn bài trên tay để bỏ. Sau đó nếu số bài trên tay của người đó lớn hơn bạn, thì bạn mất 1 điểm thể lực.",
	mbsaojian_info_identity: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể xem bài trên tay của một nhân vật khác và chọn một lá bài trong đó, sau đó nhân vật đó lặp lại việc bỏ một lá bài trên tay, cho đến khi người đó bỏ được năm lá bài / bỏ đúng lá bài bạn đã chọn / không còn bài trên tay để bỏ. Sau đó nếu số bài trên tay của người đó lớn hơn bạn, thì bạn mất 1 điểm thể lực.",
	jsrg_dongzhuo: "Suy Đổng Trác",
	jsrg_dongzhuo_prefix: "Suy",
	jsrgguanshi: "Quan Thế",
	jsrgguanshi_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể dùng 【Giết】 xem như 【Hỏa Công】 sử dụng cho một số lượng nhân vật bất kỳ. Khi 【Hỏa Công】 này kết toán xong với một nhân vật mục tiêu, nếu không gây sát thương cho người đó, thì bài này đối với các nhân vật mục tiêu còn lại sẽ đổi sang kết toán dưới hình thức 【Quyết Đấu】.",
	jsrgcangxiong: "Tàng Hung",
	jsrgcangxiong_info: "Khi bạn mất một lá bài vì bỏ bài hoặc bị nhân vật khác nhận được, bạn có thể dùng bài này để tích mưu. Sau đó nếu đang trong giai đoạn Xuất Bài của bạn, thì bạn bốc một lá bài.",
	jsrgjiebing: "Cướp Bính",
	jsrgjiebing_info_identity: "Kỹ năng giác tỉnh. Giai đoạn Chuẩn Bị, nếu số bài tích mưu của bạn lớn hơn thể lực của Chủ Công, thì bạn tăng 2 điểm giới hạn thể lực và hồi phục 2 điểm thể lực, sau đó nhận được 【Bạo Oai】.",
	jsrgjiebing_info: "Kỹ năng giác tỉnh. Giai đoạn Chuẩn Bị, nếu số bài tích mưu của bạn lớn hơn thể lực của vị trí số một, thì bạn tăng 2 điểm giới hạn thể lực và hồi phục 2 điểm thể lực, sau đó nhận được 【Bạo Oai】.",
	jsrgbaowei: "Bạo Oai",
	jsrgbaowei_info: "Kỹ năng khóa. Giai đoạn Kết Thúc, nếu số nhân vật khác đã dùng hoặc đánh ra bài trong lượt này: lớn hơn 2, thì bạn mất 2 điểm thể lực; không lớn hơn 2, thì bạn gây cho một trong số đó 2 điểm sát thương.",
	jsrg_zhanghuan: "Suy Trương Hoán",
	jsrg_zhanghuan_prefix: "Suy",
	jsrgzhushou: "Tru Thủ",
	jsrgzhushou_info: "Khi kết thúc lượt của một nhân vật, nếu bạn đã mất bài trong lượt này, thì bạn có thể chọn lá bài có điểm số lớn nhất duy nhất được đặt vào bộ bài bỏ trong lượt này, và gây 1 điểm sát thương cho một nhân vật đã mất lá bài này trong lượt này.",
	jsrgyangge: "Dương Qua",
	jsrgyangge_mizhao: "Mật Chiếu",
	jsrgyangge_info: "Mỗi vòng giới hạn một lần. Nhân vật khác có thể lực thấp nhất có thể phát động 【Mật Chiếu】 nhắn vào bạn trong giai đoạn Xuất Bài của họ.",
	jsrg_liubiao: "Suy Lưu Biểu",
	jsrg_liubiao_prefix: "Suy",
	jsrgyansha: "Yến Sát",
	jsrgyansha_info: "Giai đoạn Chuẩn Bị, bạn có thể xem như sử dụng 【Ngũ Cốc Phong Đăng】 cho một số lượng nhân vật bất kỳ. Sau khi bài này kết toán xong, tất cả nhân vật không phải mục tiêu có thể lần lượt dùng một lá bài Trang Bị xem như 【Giết】 nhắn vào một trong các nhân vật mục tiêu.",
	jsrgqingping: "Thanh Bình",
	jsrgqingping_info: "Giai đoạn Kết Thúc, nếu các nhân vật trong phạm vi tấn công của bạn đều có bài trên tay và số bài trên tay đều không lớn hơn bạn, thì bạn có thể bốc số lá bài bằng số lượng các nhân vật đó.",
	jsrg_yl_luzhi: "Suy Lục Thực",
	jsrg_yl_luzhi_prefix: "Suy",
	jsrgruzong: "Nho Tông",
	jsrgruzong_info: "Khi kết thúc lượt, nếu nhân vật mục tiêu mà bạn dùng bài chỉ định trong lượt này chỉ có một, thì bạn có thể bốc bài trên tay lên bằng với người đó. Nếu nhân vật đó là chính bạn, thì bạn có thể đổi thành khiến một số lượng nhân vật khác bất kỳ bốc bài trên tay lên bằng với bạn (đều tối đa bốc năm lá).",
	jsrgdaoren: "Đạo Nhận",
	jsrgdaoren_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể đưa một lá bài trên tay cho một nhân vật khác, sau đó gây cho tất cả nhân vật nằm trong phạm vi tấn công của cả bạn và người đó mỗi người 1 điểm sát thương.",
	jsrg_chenfan: "Suy Trần Phiên",
	jsrg_chenfan_prefix: "Suy",
	jsrggangfen: "Cương Phẫn",
	jsrggangfen_info: "Khi nhân vật có số bài trên tay lớn hơn bạn dùng 【Giết】 chỉ định nhân vật khác làm mục tiêu, bạn có thể trở thành mục tiêu bổ sung của 【Giết】 này, và khiến tất cả nhân vật khác cũng chọn có làm như vậy hay không. Sau đó người sử dụng tiết lộ bài trên tay của họ, nếu số bài đen trên tay của họ nhỏ hơn số mục tiêu, thì hủy bỏ tất cả mục tiêu của 【Giết】 này.",
	jsrgdangren: "Đương Nhân",
	jsrgdangren_info: "Kỹ năng chuyển hóa. Dương: Khi bạn cần dùng 【Đào】 cho chính mình, bạn có thể xem như sử dụng nó. Âm: Khi bạn có thể dùng 【Đào】 cho nhân vật khác, bạn phải xem như sử dụng nó.",
	jsrg_zhangju: "Suy Trương Cử",
	jsrg_zhangju_prefix: "Suy",
	jsrgqiluan: "Khởi Loạn",
	jsrgqiluan_info: "Mỗi lượt giới hạn hai lần. Khi bạn cần dùng 【Giết】 hoặc 【Tránh】, bạn có thể bỏ một số lá bài bất kỳ, và khiến tối đa số lượng nhân vật khác tương ứng chọn có thay bạn dùng nó hay không. Nếu có nhân vật đáp ứng, thì bạn bốc số lá bài bằng số bài bạn đã bỏ.",
	jsrgxiangjia: "Tương Giả",
	jsrgxiangjia_info: "Giai đoạn Xuất Bài giới hạn một lần. Nếu trong khu vực Trang Bị của bạn có bài Vũ Khí, thì bạn có thể xem như sử dụng một 【Mượn Đao Giết Người】. Sau đó nhân vật mục tiêu của bài này có thể xem như sử dụng một 【Mượn Đao Giết Người】 nhắn vào bạn.",
	//江山如故·兴
	jsrg_jiananfeng: "Hưng Giả Nam Phong",
	jsrg_jiananfeng_prefix: "Hưng",
	jsrgshanzheng: "Thiện Chính",
	jsrgshanzheng_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể nghị sự với một số lượng nhân vật bất kỳ, nếu kết quả là: đỏ, bạn có thể gây 1 điểm sát thương cho một nhân vật không tham gia nghị sự; đen, bạn nhận được tất cả bài ý kiến.",
	jsrgxiongbao: "Hung Bạo",
	jsrgxiongbao_info: "Khi bạn tham gia nghị sự, có thể tiết lộ thêm một lá bài trên tay, nếu làm vậy, các nhân vật khác đổi thành tiết lộ bài ngẫu nhiên.",
	jsrgliedu: "Liệt Đố",
	jsrgliedu_info: "Kỹ năng khóa, các nhân vật nữ khác và nhân vật có số bài trên tay lớn hơn bạn không thể đáp trả bài bạn dùng.",
	jsrg_wenyang: "Hưng Văn Ương",
	jsrg_wenyang_prefix: "Hưng",
	jsrg_zhugedan: "Hưng Gia Cát Đản",
	jsrg_zhugedan_prefix: "Hưng",
	jsrg_wangjun: "Hưng Vương Tuấn",
	jsrg_wangjun_prefix: "Hưng",
	jsrg_limi: "Hưng Lý Mật",
	jsrg_limi_prefix: "Hưng",
	jsrgfuzhen: "Phúc Trận",
	jsrgfuzhen_info: "Giai đoạn Chuẩn Bị, bạn có thể bí mật chọn một nhân vật khác, sau đó mất 1 điểm thể lực và xem như sử dụng một 【Giết】 Lôi nhắn vào tối đa ba nhân vật bao gồm người đó. Sau khi bài này kết toán xong, bạn bốc số lá bài bằng giá trị sát thương do bài này gây ra, nếu không gây sát thương cho nhân vật được bí mật chọn, bạn xem như dùng lại một 【Giết】 Lôi nhắn vào những nhân vật này.",
	jsrgbeizhi: "Bội Chí",
	jsrgbeizhi_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể thi điểm với một nhân vật, nhân vật thắng cần xem như sử dụng một 【Quyết Đấu】 nhắn vào ba nhân vật bao gồm nhân vật thua (không đủ thì chọn tất cả), sau khi bài này gây sát thương, nguồn gây sát thương nhận được một lá bài của nhân vật bị thương.",
	jsrgshenji: "Thâm Kỵ",
	jsrgshenji_info: "Kỹ năng khóa, bài có mục tiêu là bạn nếu có mục tiêu khác, thì bạn kết toán hiệu ứng của bài này cuối cùng.",
	jsrgzuozhan: "Tọa Chiêm",
	jsrgzuozhan_info: "Khi bắt đầu ván chơi, bạn chọn bạn và tối đa hai nhân vật khác, phạm vi tấn công của bạn +X (X là giá trị thể lực cao nhất trong số các nhân vật được chọn và tối đa là 5). Sau khi một nhân vật “Tọa Chiêm” chết, bạn khiến một nhân vật “Tọa Chiêm” còn sống nhận được từ bộ bài bỏ tối đa X lá bài cơ bản có tên khác nhau.",
	jsrgcuibing: "Thôi Băng",
	jsrgcuibing_info: "Kỹ năng khóa, khi kết thúc giai đoạn Xuất Bài, bạn bốc hoặc bỏ bài trên tay xuống X lá (X là số nhân vật trong phạm vi tấn công của bạn và tối đa là 5). Nếu bạn vì vậy bỏ bài, bạn bỏ trên bàn tối đa số lượng bài tương ứng, nếu không thì bỏ qua giai đoạn Bỏ Bài của lượt này.",
	jsrglangan: "Lan Can",
	jsrglangan_info: "Kỹ năng khóa, sau khi nhân vật khác chết, bạn hồi phục 1 điểm thể lực và bốc hai lá bài, sau đó phạm vi tấn công của bạn -1 (tối đa -3).",
	jsrgchengliu: "Thừa Lưu",
	jsrgchengliu_info: "Giai đoạn Chuẩn Bị, bạn có thể gây cho một nhân vật có số bài trong khu vực Trang Bị nhỏ hơn bạn X điểm sát thương (X là số lần bạn phát động 【Thừa Lưu】 trong lượt này), sau đó bạn có thể bỏ một lá bài trong khu vực Trang Bị và lặp lại quy trình này với một nhân vật chưa được chọn bằng cách này trong lượt này.",
	jsrgjianlou: "Hạm Lâu",
	jsrgjianlou_info: "Mỗi lượt giới hạn một lần, khi một lá bài Trang Bị trên bàn vào bộ bài bỏ, bạn có thể bỏ một lá bài và nhận được nó, sau đó nếu ô Trang Bị tương ứng của bài này không có bài, bạn sử dụng nó.",
	jsrgciyin: "Từ Ứng",
	jsrgciyin_info: "Mỗi lượt giới hạn một lần, bạn có thể dùng ít nhất X lá bài xem như bài cơ bản bất kỳ để dùng hoặc đánh ra (X là số hoa chưa từng vào bộ bài bỏ trong lượt này và ít nhất là 1). Sau khi bài này kết toán xong, nếu trong lượt này bài có tất cả các hoa đều đã vào bộ bài bỏ, bạn bốc bài trên tay lên giới hạn thể lực.",
	jsrgchendu: "Trần Đốc",
	jsrgchendu_info: "Kỹ năng khóa, khi bài của bạn vì sử dụng, đánh ra hoặc bỏ bài mà vào bộ bài bỏ, nếu số lượng bài này lớn hơn thể lực của bạn, bạn đưa những bài này cho tối đa số lượng nhân vật khác tương ứng (nếu không phải lượt của bạn, các nhân vật được chọn cần bao gồm nhân vật trong lượt hiện tại).",
	jsrg_simazhao: "Mộng Tư Mã Chiêu",
	jsrg_simazhao_prefix: "Mộng",
	jin_jsrg_simazhao: "Mộng Tư Mã Chiêu",
	jin_jsrg_simazhao_prefix: "Mộng",
	jsrg_dengai: "Hưng Đặng Ngải",
	jsrg_dengai_prefix: "Hưng",
	jsrgqiantun: "Khiêm Thôn",
	jsrgqiantun_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể khiến một nhân vật khác tiết lộ ít nhất một lá bài trên tay, sau đó thi điểm với người đó, lần thi điểm này người đó chỉ có thể chọn từ những lá bài đã tiết lộ. Nếu bạn thắng, bạn nhận được bài đã tiết lộ của người đó; nếu bạn không thắng, bạn nhận được bài chưa tiết lộ của người đó. Sau đó bạn tiết lộ bài trên tay.",
	jsrgqiantun_tag: "invisible",
	jsrgxiezheng: "Hiệp Chinh",
	jsrgxiezheng_info: "Giai đoạn Kết Thúc, bạn có thể khiến tối đa ba nhân vật lần lượt đặt một lá bài trên tay lên đỉnh bộ bài, sau đó xem như bạn sử dụng một 【Binh Lâm Thành Hạ】; sau khi bài này kết toán xong nếu không gây sát thương, bạn mất 1 điểm thể lực.",
	jsrgzhaoxiong: "Chiêu Hung",
	jsrgzhaoxiong_info: "Kỹ năng giới hạn, giai đoạn Chuẩn Bị, nếu bạn đã bị thương và đã phát động 【Hiệp Chinh】, bạn có thể đổi thế lực thành Tấn, mất 【Khiêm Thôn】 và nhận được 【Uy Tứ】 và 【Đãng Dị】.",
	jsrgweisi: "Uy Tứ",
	jsrgweisi_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể chọn một nhân vật khác, khiến người đó đưa một số lá bài trên tay bất kỳ ra khỏi trò chơi cho đến khi kết thúc lượt, sau đó xem như sử dụng một 【Quyết Đấu】 nhắn vào người đó; sau khi bài này gây sát thương cho người đó, bạn nhận được tất cả bài trên tay của người đó.",
	jsrgdangyi: "Đãng Dị",
	jsrgdangyi_info: "Kỹ năng Chủ Công, mỗi ván giới hạn X lần, khi bạn gây sát thương có thể khiến sát thương này +1 (X là thể lực đã mất của bạn khi nhận được kỹ năng này +1).",
	jsrgpiqi: "Tịch Kỳ",
	jsrgpiqi_info: "Giai đoạn Xuất Bài giới hạn hai lần, bạn có thể xem như sử dụng một 【Thuận Thủ Khiên Dương】 không giới hạn khoảng cách (không thể chỉ định cùng một mục tiêu), các nhân vật trong khoảng cách 1 với mục tiêu trong lượt này có thể dùng 【Tránh】 xem như 【Vô Tiết Khả Kích】.",
	jsrgzhoulin: "Sậu Lâm",
	jsrgzhoulin_info: "Khi bạn dùng 【Giết】 gây sát thương cho một nhân vật, nếu khi bắt đầu lượt này người đó không nằm trong phạm vi tấn công của bạn, sát thương này +1.",
	jsrg_simaliang: "Hưng Tư Mã Lượng",
	jsrg_simaliang_prefix: "Hưng",
	jsrgsheju: "Nhiếp Cụ",
	jsrgsheju_info: "Kỹ năng khóa, khi bạn dùng 【Giết】 chỉ định mục tiêu duy nhất / trở thành mục tiêu duy nhất của 【Giết】, bạn và nhân vật mục tiêu / người sử dụng bài này nghị sự, nếu kết quả là đen, thì mỗi bên giảm 1 điểm giới hạn thể lực; nếu không thì nhân vật có ý kiến màu đen bốc hai lá bài.",
	jsrgzuwang: "Tộc Vọng",
	jsrgzuwang_info: "Kỹ năng khóa, giai đoạn Chuẩn Bị và giai đoạn Kết Thúc, bạn bốc bài trên tay lên giới hạn thể lực.",
	jsrgzuwang_append: '<span style="font-family: yuanli">“Công hà bất thảo nhân nhi cụ vi nhân sở thảo!”——Hà Mặc</span>',
	jsrg_tufashujineng: "Hưng Đột Phát Thụ Cơ Năng",
	jsrg_tufashujineng_prefix: "Hưng",
	jsrgqinrao: "Xâm Nhiễu",
	jsrgqinrao_info: "Khi bắt đầu giai đoạn Xuất Bài của nhân vật khác, bạn có thể dùng một lá bài xem như 【Quyết Đấu】 sử dụng nhắn vào người đó. Trong quá trình kết toán bài này, nếu trong tay người đó có 【Giết】 có thể đánh ra, thì người đó phải đánh ra; nếu không thì người đó tiết lộ bài trên tay.",
	jsrgfuran: "Phục Nhiên",
	jsrgfuran_info: "Khi bạn chịu sát thương có nguồn gốc, nếu bạn không nằm trong phạm vi tấn công của nguồn gây sát thương, thì bạn có thể hồi phục 1 điểm thể lực khi kết thúc lượt này.",
	jsrg_lukang: "Hưng Lục Kháng",
	jsrg_lukang_prefix: "Hưng",
	jsrgzhuwei: "Trúc Vi",
	jsrgzhuwei_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể di chuyển một lá bài Trang Bị trên bàn, sau đó bạn có thể khiến một nhân vật không còn nhân vật nào trong phạm vi tấn công vì điều này mất 2 điểm thể lực.",
	jsrgkuangjian: "Khuông Gián",
	jsrgkuangjian_info: "Bạn có thể dùng một lá bài Trang Bị xem như bài cơ bản bất kỳ để sử dụng (không giới hạn số lần nhưng không thể chỉ định chính mình làm mục tiêu), sau đó nhân vật mục tiêu sử dụng bài Trang Bị này.",
	jsrg_malong: "Hưng Mã Long",
	jsrg_malong_prefix: "Hưng",
	jsrgfennan: "Phấn Nan",
	jsrgfennan_info: "Giai đoạn Xuất Bài giới hạn hai lần, bạn có thể khiến một nhân vật chọn một: ① Khiến bạn lật úp bài tướng, sau đó bạn di chuyển một lá bài chưa bị di chuyển trong lượt này trên bàn của người đó; ② Khiến bạn xem bài trên tay của người đó và có thể tái luyện tối đa ba lá bài trong đó.",
	jsrgxunji: "Huân Tế",
	jsrgxunji_info: "Giai đoạn Kết Thúc, nếu bạn đã gây sát thương cho tất cả nhân vật khác mà bạn đã dùng bài chỉ định trong lượt này, thì bạn có thể phân phát bài thực thể tương ứng với bài đã gây sát thương trong lượt này đang nằm trong bộ bài bỏ cho bất kỳ nhân vật nào mỗi người một lá.",
};

export default translates;
