import { lib, game, ui, get, ai, _status } from "noname";

const translates = {
	bachiqionggouyu: "Bát Xích Quỳnh Câu Ngọc",
	bachiqionggouyu_info: "Kỹ năng khóa, khi kết thúc giai đoạn Xuất Bài, hồi phục 1 điểm thể lực; khi bắt đầu giai đoạn Bốc Bài, nếu thể lực của bạn đầy, thì số bài bốc +2.",
	bachiqionggouyu_skill: "Bát Xích Quỳnh Câu Ngọc",
	bachiqionggouyu_skill_info: "Kỹ năng khóa, khi kết thúc giai đoạn Xuất Bài, hồi phục 1 điểm thể lực; khi bắt đầu giai đoạn Bốc Bài, nếu thể lực của bạn đầy, thì số bài bốc +2.",
	bazhijing: "Bát Chỉ Kính",
	bazhijing_info: "Kỹ năng khóa, sau khi bạn chịu sát thương từ một lá bài chú, ngăn ngừa sát thương do lá bài chú cùng tên gây ra cho bạn, sau khi mất trang bị này sẽ xóa bỏ ghi nhớ.",
	bazhijing_skill: "Bát Chỉ Kính",
	bazhijing_skill_info: "Kỹ năng khóa, sau khi bạn chịu sát thương từ một lá bài chú, ngăn ngừa sát thương do lá bài chú cùng tên gây ra cho bạn, sau khi mất trang bị này sẽ xóa bỏ ghi nhớ.",
	ol_le_caohong: "OL Lạc Tào Hồng",
	ol_le_caohong_prefix: "OL Lạc",
	olmojin: "Mò Kim",
	olmojin_info: `Kỹ năng khóa, khi bắt đầu ván chơi, bạn thực hiện một lần ${get.poptip({
		id: "olmojin_tip",
		name: "Mò Kim",
		type: "character",
		info: "Chọn một trong ba thao tác ngẫu nhiên (hiển thị cho nhân vật khác). Mò Kim thành công sẽ nhận được phần thưởng, sau đó tiếp tục “Mò Kim”.",
	})}. Mỗi khi ${get.poptip("olmojin_tip")} thành công, bạn nhận được phần thưởng và thực hiện lại một lần ${get.poptip("olmojin_tip")}. Khi bắt đầu lượt, đặt ${get.poptip("luoyangchan")} vào khe Vũ Khí của bạn.`,
	olmojin_directHit: "Không thể đáp trả",
	olmojin_baseDamage: "Hồi phục +1",
	oldingbao: "Định Bảo",
	oldingbao_info: `Kỹ năng giới hạn, giai đoạn Xuất Bài, bạn có thể trực tiếp hoàn thành một lần ${get.poptip("olmojin_tip")} và kết thúc giai đoạn này.`,
	luoyangchan: "Lạc Dương Sản",
	luoyangchan_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể bỏ một lá bài màu đen, thực hiện một lần hiệu quả thẻ bài may mắn (không tiêu hao thẻ bài may mắn).",
	luoyangchan_skill: "Lạc Dương Sản",
	luoyangchan_skill_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể bỏ một lá bài màu đen, thực hiện một lần hiệu quả thẻ bài may mắn (không tiêu hao thẻ bài may mắn).",
	old_lingju: "SP Linh Chư",
	old_lingju_prefix: "SP",
	fenxin_old: "Phẫn Tâm",
	fenxin_old_info: "Kỹ năng giới hạn, khi bạn giết một nhân vật không phải chủ công, bạn có thể đổi thẻ thân phận chưa lật với người đó. (Bạn không thể phát động kỹ năng này khi thân phận của bạn là chủ công)",
	sp_fuwan: "SP Phục Hoàn",
	sp_fuwan_prefix: "SP",
	spfengyin: "Phụng Ấn",
	spfengyin_info: "Khi bắt đầu lượt của nhân vật khác, nếu thể lực của người đó không ít hơn bạn, bạn có thể đưa cho người đó một 【Giết】, khiến người đó bỏ qua giai đoạn Xuất Bài và giai đoạn Bỏ Bài.",
	spchizhong: "Trì Trọng",
	spchizhong_info: "Kỹ năng khóa, giới hạn bài trên tay của bạn bằng giới hạn thể lực; khi nhân vật khác chết, bạn tăng 1 điểm giới hạn thể lực.",
	sp_fuhuanghou: "SP Phục Thọ",
	sp_fuhuanghou_prefix: "SP",
	spcangni: "Tàng Nặc",
	spcangni_info: "Khi bắt đầu giai đoạn Bỏ Bài, bạn có thể hồi phục 1 điểm thể lực hoặc bốc hai lá bài, sau đó lật úp bài tướng của bạn; trong lượt của nhân vật khác, khi bạn nhận được (mỗi lượt giới hạn một lần) / mất một lần bài, nếu bài tướng của bạn úp, bạn có thể khiến nhân vật đó bốc / bỏ một lá bài.",
	spmixin: "Mật Tín",
	spmixin_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể đưa một lá bài trên tay cho một nhân vật khác, nhân vật đó phải dùng một 【Giết】 không giới hạn khoảng cách nhắm vào một nhân vật khác do bạn chọn, nếu không thì nhân vật bạn chọn sẽ xem bài trên tay của người đó và nhận được một lá bài trong đó.",
	sp_jiben: "SP Cát Bản",
	sp_jiben_prefix: "SP",
	spduanzhi: "Đoạn Chỉ",
	spduanzhi_info: "Khi bạn trở thành mục tiêu của bài do nhân vật khác sử dụng, bạn có thể bỏ tối đa hai lá bài của người đó, sau đó mất 1 điểm thể lực.",
	spduyi: "Độc Y",
	spduyi2: "Độc Y",
	spduyi_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể lật ngửa một lá bài trên cùng bộ bài và đưa cho một nhân vật, nếu lá bài này màu đen, nhân vật đó không thể dùng hoặc đánh ra bài trên tay, cho đến khi kết thúc lượt.",
	sp_mushun: "SP Mục Thuận",
	sp_mushun_prefix: "SP",
	libai: "Lý Bạch",
	dclbjiuxian: "Tửu Tiên",
	dclbjiuxian_info: "① Bạn có thể dùng bài chú có số mục tiêu định mức lớn hơn 1 xem như 【Rượu】. ② Bạn dùng 【Rượu】 không giới hạn số lần.",
	dcshixian: "Thi Tiên",
	dcshixian_yayun: "Áp Vận",
	dcshixian_info: "Khi bạn sử dụng một lá bài, nếu tên bài này vần với tên của lá bài bạn đã sử dụng trước đó trong ván chơi này, thì bạn có thể bốc một lá bài, và khiến bài này kết toán thêm một lần.",
	taoshen: "Đào Thần",
	dcnutao: "Nộ Đào",
	dcnutao_info: "Kỹ năng khóa. ① Khi bạn dùng bài chú chỉ định mục tiêu đầu tiên, nếu (các) mục tiêu bao gồm nhân vật khác, bạn ngẫu nhiên gây 1 điểm sát thương Lôi cho một trong số các nhân vật mục tiêu khác đó. ② Khi bạn gây sát thương Lôi trong giai đoạn Xuất Bài, giới hạn số lần bạn dùng 【Giết】 trong giai đoạn này +1.",
	sunwukong: "Tôn Ngộ Không",
	dcjinjing: "Kim Tinh",
	dcjinjing_info: "Kỹ năng khóa. Bài trên tay của nhân vật khác hiển thị với bạn.",
	dccibei: "Từ Bi",
	dccibei_info: "Mỗi lượt mỗi nhân vật giới hạn một lần. Khi bạn gây sát thương cho nhân vật khác, bạn có thể ngăn ngừa sát thương này, sau đó bốc năm lá bài.",
	dcruyi: "Như Ý",
	dcruyi_info: `Kỹ năng khóa. ① Khi bắt đầu ván chơi, bạn đặt ${get.poptip("ruyijingubang")} vào khu vực Trang Bị. ② Bài Vũ Khí trong khu vực bài trên tay của bạn đều được xem là 【Giết】, và bạn không phải là mục tiêu hợp lệ của bài Vũ Khí. ③ Khi bạn sắp mất ${get.poptip("ruyijingubang")} hoặc sắp phế bỏ khe Vũ Khí, hủy bỏ việc đó. ④ Bạn không thể dùng hoặc đánh ra ${get.poptip("ruyijingubang")} trong khu vực Trang Bị xem như bài khác.`,
	ruyijingubang: "Như Ý Kim Cô Bảng",
	ruyijingubang_skill: "Kim Cô Bảng",
	ruyijingubang_effect: "Kim Cô Bảng",
	ruyijingubang_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể điều chỉnh phạm vi tấn công thực tế của bài này thành bất kỳ số nguyên nào trong khoảng 1~4. Bạn có hiệu ứng tương ứng dựa trên phạm vi tấn công thực tế của bài này:<br><li>⑴ Bạn dùng 【Giết】 không giới hạn số lần.<br><li>⑵ 【Giết】 bạn dùng gây sát thương +1.<br><li>⑶ 【Giết】 bạn dùng không thể bị đáp trả.<br><li>⑷ Sau khi bạn dùng 【Giết】 chọn mục tiêu, có thể thêm một mục tiêu bổ sung.",
	ruyijingubang_skill_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể điều chỉnh phạm vi tấn công thực tế của bài này thành bất kỳ số nguyên nào trong khoảng 1~4. Bạn có hiệu ứng tương ứng dựa trên phạm vi tấn công thực tế của bài này:<br><li>⑴ Bạn dùng 【Giết】 không giới hạn số lần.<br><li>⑵ 【Giết】 bạn dùng gây sát thương +1.<br><li>⑶ 【Giết】 bạn dùng không thể bị đáp trả.<br><li>⑷ Sau khi bạn dùng 【Giết】 chọn mục tiêu, có thể thêm một mục tiêu bổ sung.",
	longwang: "Long Vương",
	dclonggong: "Long Cung",
	dclonggong_info: "Mỗi lượt giới hạn một lần. Khi bạn chịu sát thương, bạn có thể ngăn ngừa sát thương này, sau đó khiến nguồn gây sát thương nhận được một lá bài Trang Bị từ bộ bài.",
	dcsitian: "Ty Thiên",
	dcsitian_info: `Giai đoạn Xuất Bài, bạn có thể bỏ hai lá bài trên tay khác màu. Hệ thống sẽ chọn ngẫu nhiên hai ${get.poptip({
		id: "sitian_tianqi",
		name: "Thời Tiết",
		type: "character",
		info: "<li>Liệt Nhật: Bạn lần lượt gây 1 điểm sát thương Hỏa cho các nhân vật khác.<br><li>Lôi Điện: Bạn khiến các nhân vật khác mỗi người thực hiện một lần phán định. Nếu kết quả là ♠2~9, thì người đó chịu 3 điểm sát thương Lôi không rõ nguồn gốc.<br><li>Đại Lãng: Bạn bỏ tất cả bài trong khu vực Trang Bị của các nhân vật khác (nhân vật không có bài trong khu vực Trang Bị thì đổi thành mất 1 điểm thể lực).<br><li>Bạo Vũ: Bạn bỏ tất cả bài trên tay của một nhân vật. Nếu người đó không có bài trên tay, thì đổi thành khiến người đó mất 1 điểm thể lực.<br><li>Đại Vụ: Bạn khiến tất cả nhân vật khác nhận được hiệu ứng sau: Khi người đó dùng lá bài cơ bản tiếp theo, hủy bỏ nó.",
	})} trong số tất cả, bạn xem các ${get.poptip("sitian_tianqi")} này và chọn một để thực hiện.`,
	sunyang: "Tôn Dương",
	clbshuijian: "Thủy Tiễn",
	clbshuijian_info: "Khi bắt đầu giai đoạn Bốc Bài, bạn có thể khiến số bài bốc định mức +X (X bằng một nửa số bài trong khu vực Trang Bị của bạn +1, và làm tròn xuống).",
	yeshiwen: "Diệp Thi Văn",
	clbjisu: "Cấp Tốc",
	clbjisu_info: "Trước khi bắt đầu giai đoạn Phán Định, bạn có thể bỏ qua giai đoạn Phán Định và giai đoạn Bốc Bài của lượt này, xem như sử dụng một 【Giết】 nhắm vào một nhân vật khác.",
	clbshuiyong: "Thủy Vịnh",
	clbshuiyong_info: "Kỹ năng khóa. Khi bạn chịu sát thương Hỏa, hủy bỏ nó.",
	xiaoyuehankehan: "Tiểu Ước Hãn Khả Hãn",
	dctongliao: "Thông Liêu",
	dctongliao_info: "① Khi kết thúc giai đoạn Bốc Bài, bạn có thể chọn một lá bài trên tay có điểm số nhỏ nhất, đánh dấu lá bài này là “Thông Liêu”. ② Khi bạn mất một lá bài có nhãn “Thông Liêu”, bạn bốc X lá bài (X là điểm số của lá bài này).",
	dcwudao: "Ngộ Đạo",
	dcwudao_info: "Khi bạn sử dụng bài kết toán xong, nếu lá bài bạn sử dụng trước đó cùng loại với lá bài này, thì bạn có thể trong lượt này nhận được hiệu ứng sau: Khi bạn dùng loại bài đó trong lượt, bạn khiến bài này không thể bị đáp trả và giá trị sát thương cơ bản +1.",
	zhutiexiong: "Chu Thiết Hùng",
	wu_zhutiexiong: "Chu Thiết Hùng",
	dcbianzhuang: "Biến Trang",
	dcbianzhuang_info: "① Giai đoạn Xuất Bài giới hạn một lần, bạn có thể nhận được một trong hai kỹ năng được hệ thống chọn ngẫu nhiên, và xem như sử dụng một 【Giết】 (không giới hạn khoảng cách và số lần), sau đó mất kỹ năng nhận được bằng cách này. ② Khi bạn dùng bài Trang Bị, bạn xóa bỏ ghi nhớ số lần phát động của kỹ năng này. ③ Sau khi bạn phát động 【Biến Trang①】, nếu số lần bạn phát động 【Biến Trang①】 lớn hơn 2, thì bạn đổi da thành Vũ·Chu Thiết Hùng, và đổi số kỹ năng hệ thống chọn thành ba.",
	dc_caocao: "Kinh Điển Tào Tháo",
	dc_caocao_prefix: "Kinh Điển",
	dcjianxiong: "Gian Hùng",
	dcjianxiong_info: "Sau khi bạn chịu sát thương, bạn có thể bốc một lá bài và nhận được lá bài đã gây sát thương cho bạn, sau đó bạn khiến số bài bốc của kỹ năng này +1 (tối đa là 5).",
	dc_liubei: "Kinh Điển Lưu Bị",
	dc_liubei_prefix: "Kinh Điển",
	dcrende: "Nhân Đức",
	dcrende_info: "Giai đoạn Xuất Bài mỗi nhân vật giới hạn một lần. Bạn có thể nhận hai lá bài trên tay của một nhân vật khác, sau đó xem như sử dụng một lá bài cơ bản.",
	dc_sunquan: "Kinh Điển Tôn Quyền",
	dc_sunquan_prefix: "Kinh Điển",
	dczhiheng: "Chế Hành",
	dczhiheng_info: "① Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể bỏ một số lá bài bất kỳ và bốc số lượng tương ứng, nếu bạn bỏ tất cả bài trên tay khi phát động 【Chế Hành】, thì bạn bốc thêm một lá bài. ② Mỗi lượt mỗi nhân vật giới hạn một lần. Khi bạn gây sát thương cho nhân vật khác, bạn khiến giới hạn số lần phát động 【Chế Hành①】 trong lượt này +1.",
	nezha: "Ná Tra",
	dcsantou: "Tam Đầu",
	dcsantou_info: "Kỹ năng khóa, khi bạn chịu sát thương, ngăn ngừa nó, sau đó nếu các điều kiện dưới đây đúng, bạn mất 1 điểm thể lực: 1. Trước đó trong lượt này bạn đã ngăn ngừa sát thương của nguồn gây sát thương này bằng cách này, và thể lực của bạn không nhỏ hơn 3; 2. Sát thương lần này là sát thương thuộc tính, và thể lực của bạn bằng 2; 3. Kênh của sát thương lần này là bài màu đỏ, và thể lực của bạn bằng 1.",
	dcfaqi: "Pháp Khí",
	dcfaqi_info: "Khi bạn dùng bài Trang Bị kết toán xong trong giai đoạn Xuất Bài, bạn xem như sử dụng một bài chú thông thường chưa dùng bằng cách này trong lượt này.",
	dc_sunce: "Kinh Điển Tôn Sách",
	dc_sunce_prefix: "Kinh Điển",
	dcshuangbi: "Song Bích",
	dcshuangbi_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể chọn một hạng mục: ① Bốc X lá bài, trong lượt này giới hạn bài trên tay +X; ② Bỏ tối đa X lá bài, ngẫu nhiên gây lượng sát thương Hỏa tương ứng cho nhân vật khác; ③ Xem như sử dụng X 【Giết】 Hỏa hoặc 【Hỏa Công】. (X là số nhân vật còn sống trên bàn)",
	dc_zhaoyun: "Kinh Điển Thần Triệu Vân",
	dc_zhaoyun_prefix: "Kinh Điển Thần",
	dclonghun: "Long Hồn",
	dclonghun_info: "Mỗi lượt giới hạn 20 lần, bạn có thể dùng hoặc đánh ra bài của bạn theo quy tắc sau: Cơ (♥) xem như 【Đào】, Rô (♦) xem như 【Giết】 Hỏa, Mận (♣) xem như 【Tránh】, Bích (♠) xem như 【Vô Tiết Khả Kích】.",
	dczhanjiang: "Trảm Tướng",
	dczhanjiang_info: "Giai đoạn Chuẩn Bị, nếu trên bàn có 【Thanh Cang Kiếm】, thì bạn có thể nhận được nó.",
	dc_wuyi: "Kinh Điển Ngô Ý",
	dc_wuyi_prefix: "Kinh Điển",
	dcbenxi: "Bôn Tập",
	dcbenxi_info: "Kỹ năng chuyển hóa, kỹ năng khóa. Khi bạn mất bài trên tay, Dương: hệ thống ngẫu nhiên tra cứu một câu thoại kỹ năng được chuyển đổi sang bính âm có chứa “wu,yi”, sau đó bạn đọc câu thoại này. Âm: Bạn nhận được kỹ năng tương ứng với câu thoại vừa đọc lần trước cho đến khi bắt đầu lượt tiếp theo của bạn; nếu bạn đã có kỹ năng đó, thì đổi thành gây cho mỗi nhân vật khác 1 điểm sát thương.",
	quyuan: "Khuất Nguyên",
	dcqiusuo: "Cầu Tác",
	dcqiusuo_info: "Khi bạn gây ra hoặc chịu sát thương, bạn có thể lấy một lá 【Thiết Tác Liên Hoàn】 từ bộ bài hoặc bộ bài bỏ.",
	dclisao: "Ly Tao",
	dclisao_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể chọn tối đa hai nhân vật, những nhân vật này phải đồng thời trả lời phần điền vào chỗ trống câu trong bài “Ly Tao” (dạng câu hỏi giành quyền trả lời, kết thúc trả lời khi một nhân vật trả lời đúng). Nhân vật trả lời đúng sẽ tiết lộ tất cả bài trên tay, các nhân vật còn lại trong lượt này không thể đáp trả bài bạn dùng và chịu sát thương gấp đôi.",
	xin_sunquan: "Biết Chơi Tôn Quyền",
	xin_sunquan_ab: "Tôn Quyền",
	dchuiwan: "Biết Chơi",
	dchuiwan_info: "Mỗi lượt mỗi tên bài giới hạn một lần, khi bạn bốc bài, bạn có thể chọn tối đa bằng số bài bốc các tên bài cơ bản hoặc bài chú và nhận từ bộ bài, sau đó bạn bốc ít hơn số lượng tương ứng.",
	dchuanli: "Hoán Lý",
	dchuanli_info: `Giai đoạn Kết Thúc, nếu trong lượt này bạn: dùng bài chỉ định ít nhất ba lần chính bạn làm mục tiêu, thì bạn có thể khiến tất cả kỹ năng của một nhân vật khác mất hiệu lực, sau đó người đó nhận được ${get.poptip("zhijian")} và ${get.poptip("guzheng")}, cho đến khi kết thúc lượt tiếp theo của người đó; dùng bài chỉ định ít nhất ba lần một nhân vật khác làm mục tiêu, thì bạn có thể khiến tất cả kỹ năng của người đó mất hiệu lực, sau đó người đó nhận được ${get.poptip("reyingzi")} và ${get.poptip("refanjian")}, cho đến khi kết thúc lượt tiếp theo của người đó. Sau đó nếu bạn thực hiện cả hai hạng mục, bạn nhận được ${get.poptip("rezhiheng")} cho đến khi kết thúc lượt tiếp theo của bạn.`,
	dc_noname: "Vô Danh",
	dcchushan: "Xuất Sơn",
	dcchushan_info: "Kỹ năng khóa, khi bắt đầu ván chơi, bạn nhận được mỗi kỹ năng một từ hai tướng, và đổi tên tướng của bạn thành tổ hợp tên của hai tướng này.",
	wuhujiang: "Ngũ Hổ",
	wuhujiang_ab: "Hồn Ngũ Hổ",
	wuhujiang_prefix: "Hồn",
	olhuyi: "Hổ Dực",
	olhuyi_info: "① Khi bắt đầu ván chơi, bạn chọn một từ ba kỹ năng Ngũ Hổ Tướng ngẫu nhiên để nhận. ② Sau khi bạn dùng hoặc đánh ra một lá bài cơ bản, nếu số kỹ năng nhận được vì kỹ năng này nhỏ hơn 5, bạn ngẫu nhiên nhận được một kỹ năng Ngũ Hổ Tướng có mô tả kỹ năng chứa tên bài này. ③ Khi kết thúc lượt, bạn có thể mất một kỹ năng nhận được bằng cách này, sau đó bạn xem ba lá bài trên cùng bộ bài và nhận được một lá bài trong số đó.",
	liuxiecaojie: "Lưu Hiệp Tào Tiết",
	dcjuanlv: "Quyến Lữ",
	dcjuanlv_info: "Khi bạn dùng bài chỉ định nhân vật khác giới làm mục tiêu, bạn có thể khiến người đó chọn một: ① Bỏ một lá bài; ② Khiến bạn bốc một lá bài.",
	dcqixin: "Tề Tâm",
	dcqixin_info: "Kỹ năng chuyển hóa. ① Giai đoạn Xuất Bài, bạn có thể đổi giới tính thành: Dương, Tào Tiết - nữ; Âm, Lưu Hiệp - nam. ② Khi bạn sắp chết, bạn hủy bỏ việc đó và đổi giới tính thành trạng thái chuyển hóa của 【Tề Tâm①】, điều chỉnh thể lực về thể lực của trạng thái này, sau đó bạn không thể phát động 【Tề Tâm】 trong ván chơi này.",
	dcqixin_faq: "Về Tề Tâm",
	dcqixin_faq_info: "<br>Hai trạng thái của 【Tề Tâm①】 mỗi trạng thái có giá trị thể lực bằng giới hạn thể lực ban đầu, trạng thái ban đầu là “Lưu Hiệp - nam”, và giá trị thể lực của hai trạng thái được tính riêng.",
	ol_jsrg_caocao: "Hán Tào Tháo",
	ol_jsrg_caocao_prefix: "Hán",
	oldingxi: "Định Tây",
	oldingxi_info: "Khi bạn không vì 【Định Tây】 mà dùng bài sát thương vào bộ bài bỏ, bạn có thể dùng một trong những bài sát thương đó nhắm vào nhà trên, sau đó đặt bài đã dùng lên bài tướng. Khi kết thúc lượt, bạn bốc X lá bài (X là số lượng bài “Định Tây” của bạn).",
	olnengchen: "Năng Thần",
	olnengchen_info: "Kỹ năng khóa, sau khi bạn chịu sát thương do bài gây ra, nếu bạn có bài “Định Tây” cùng tên với bài này, thì bạn ngẫu nhiên nhận được một trong số đó.",
	olhuojie: "Họa Kết",
	olhuojie_info: "Kỹ năng khóa, khi bắt đầu giai đoạn Xuất Bài, nếu X lớn hơn số người chơi, thì bạn tiến hành X lần phán định 【Sấm Sét】 cho đến khi chịu sát thương bằng cách này (X là số lượng bài “Định Tây” của bạn); sau đó nếu bạn chịu sát thương vì điều này, thì bạn nhận được tất cả bài “Định Tây”.",
	jiangziya: "Khương Tử Nha",
	xingzhou: "Hưng Chu",
	xingzhou_info: "Mỗi lượt giới hạn một lần, sau khi nhân vật có ít bài trên tay nhất chịu sát thương, bạn có thể bỏ hai lá bài trên tay, xem như sử dụng một 【Giết】 nhắm vào nguồn gây sát thương; nếu người đó chết vì điều này, bạn khiến 【Liệt Thần】 xem như chưa phát động.",
	lieshen: "Liệt Thần",
	lieshen_info: "Kỹ năng giới hạn, giai đoạn Xuất Bài, bạn có thể khiến một nhân vật điều chỉnh thể lực và số bài trên tay về thời điểm bắt đầu ván chơi.",
	shengongbao: "Thân Công Báo",
	zhuzhou: "Trợ Trụ",
	zhuzhou_info: "Mỗi lượt giới hạn một lần, sau khi nhân vật có nhiều bài trên tay nhất gây sát thương, bạn có thể khiến người đó nhận được một lá bài trên tay của nhân vật bị thương.",
	yaoxian: "Yêu Tiên",
	yaoxian_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể khiến một nhân vật bốc hai lá bài, sau đó người đó phải dùng 【Giết】 nhắm vào một nhân vật khác do bạn chỉ định, nếu không thì người đó mất 1 điểm thể lực.",
	nanjixianweng: "Nam Cực Tiên Ông",
	xwshoufa: "Thụ Pháp",
	xwshoufa_info: `Giai đoạn Xuất Bài, bạn có thể tiết lộ và đưa tất cả bài trên tay có hoa ♠/♥/♣/♦ cho một nhân vật khác, khiến người đó nhận được ${get.poptip("tiandu")}/${get.poptip("retianxiang")}/${get.poptip("reqingguo")}/${get.poptip("new_rewusheng")} cho đến khi bắt đầu lượt tiếp theo của bạn.`,
	fuzhao: "Phúc Chiếu",
	fuzhao_info: "Khi một nhân vật vào trạng thái hấp hối, bạn có thể khiến người đó thực hiện một lần phán định, nếu kết quả là ♥, người đó hồi phục 1 điểm thể lực.",
	weiqing: "Vệ Thanh",
	dcbeijin: "Bắc Tiến",
	dcbeijin_info: "Giai đoạn Xuất Bài, bạn có thể bốc một lá bài (bài này khi dùng không giới hạn số lần). Nếu làm vậy, trong lượt này lần tiếp theo bạn dùng bài hoặc phát động kỹ năng này, nếu trong tay bạn có bài nhận được bằng cách này, thì bạn mất 1 điểm thể lực.",
	ol_jsrg_lvbu: "Lữ Bố",
	ol_jsrg_lvbu_ab: "Chiến Thần Lữ Bố",
	olfengzhu: "Phùng Chủ",
	olfengzhu_info: "Kỹ năng khóa. Giai đoạn Chuẩn Bị, bạn chọn một nhân vật nam khác chưa ghi nhớ, ghi nhớ người đó là “Nghĩa Phụ”. Sau đó bốc số lá bài bằng thể lực của người đó.",
	olyuyu: "Uất Uất",
	olyuyu_info: "Kỹ năng khóa, khi kết thúc lượt, bạn khiến một nhân vật “Nghĩa Phụ” nhận 1 dấu hiệu “Hận”. Sau khi bạn chịu 1 điểm sát thương hoặc mất một lá bài trong lượt của người đó, người đó nhận 1 dấu hiệu “Hận”.",
	ollbzhiji: "Trí Kích",
	ollbzhiji_info: `Kỹ năng khóa. Khi bạn dùng bài chỉ định nhân vật “Nghĩa Phụ” làm mục tiêu, nếu bài này không phải bài sát thương, bạn thực hiện X lần phán định, nếu kết quả phán định là: bài Trang Bị, bạn nhận được ${get.poptip("shenji")}; 【Giết】 hoặc 【Quyết Đấu】, bạn nhận được ${get.poptip("wushuang")} và lá bài phán định. Nếu không, sát thương của bài này +X và loại bỏ tất cả dấu hiệu “Hận” của người đó (X là số dấu hiệu “Hận” của người đó).`,
	oljiejiu: "Giới Tửu",
	oljiejiu_info: `Kỹ năng khóa. ① Bạn không thể dùng 【Rượu】. ② Bạn có thể dùng 【Rượu】 xem như bài cơ bản bất kỳ ngoại trừ 【Rượu】. ③ Khi bắt đầu ván chơi, bạn khiến tất cả nhân vật nữ khác thay thế một kỹ năng ngẫu nhiên trên bài tướng của họ bằng ${get.poptip("lijian")}.`,
	shi_cenhun: "Sầm Hôn",
	shi_cenhun_ab: "Thực Sầm Hôn",
	dcbaoshi: "Bạo Thực",
	dcbaoshi_info: "Khi kết thúc giai đoạn Bốc Bài, bạn có thể lật ngửa hai lá bài trên cùng bộ bài. Nếu tổng số chữ trong tên của các lá bài được lật nhỏ hơn hoặc bằng 10 (【Đào】 hoặc 【Rượu】 không tính vào thống kê số chữ trong tên bài), bạn chọn một: 1. Nhận được tất cả các lá bài đã lật; 2. Lật thêm một lá bài nữa.",
	dcxinggong: "Hưng Công",
	dcxinggong_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể chọn nhận bất kỳ lá bài nào đã vào bộ bài bỏ trong lượt này. Sau đó nếu X lớn hơn 0, thì bạn chịu X điểm sát thương (X là số bài bạn nhận lần này - thể lực của bạn).",
	ol_nianshou: "Phổ Thông Niên Thú",
	ol_nianshou_ab: "Niên Thú",
	ol_zishu: "Tý Thửu",
	ol_chouniu: "Sửu Ngưu",
	ol_yinhu: "Dần Hổ",
	ol_maotu: "Mão Thố",
	ol_chenlong: "Thìn Long",
	ol_sishe: "Tỵ Xà",
	ol_wuma: "Ngọ Mã",
	ol_weiyang: "Mùi Dương",
	ol_shenhou: "Thân Hầu",
	ol_youji: "Dậu Kê",
	ol_xugou: "Tuất Cẩu",
	ol_haizhu: "Hợi Trư",
	olsuichong: "Tuế Sùng",
	get olsuichong_info() {
		let cost;
		try {
			cost = !_status?.connectMode && game?.changeCoin;
		} catch (error) {
			cost = undefined;
		}
		return "① Khi bắt đầu ván chơi, bạn có thể phát động một lần phong bao lì xì “so tay may”; ② Mỗi ván giới hạn ba lần, giai đoạn Chuẩn Bị, bạn có thể " + (cost ? "tiêu hao 10 vàng và " : "") + "phát động một lần phong bao lì xì “so tay may”. Nhân vật may mắn nhất sẽ chọn một từ ba kỹ năng Thập Nhị Sinh Thú để bạn nhận (thay thế kỹ năng Thập Nhị Sinh Thú bạn đã nhận bằng cách này trước đó).";
	},
	olshouhun: "Thú Hồn",
	olshouhun_info: "Kỹ năng khóa. ① Giai đoạn Bốc Bài bạn bốc thêm [0] lá bài, giới hạn bài trên tay của bạn +[1], giới hạn thể lực của bạn +[2]. ② Khi bạn chịu sát thương, bạn khiến một hạng mục có giá trị thấp nhất của kỹ năng này tăng +1 (mỗi hạng mục tối đa là 4).",
	olzishu: "Tý Thửu",
	olzishu_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể nhận một lá bài trên tay của nhân vật khác có số bài trên tay lớn hơn bạn, sau đó bạn có thể lặp lại quy trình này cho đến khi số bài trên tay bạn là nhiều nhất bàn.",
	olchouniu: "Sửu Ngưu",
	olchouniu_info: "Kỹ năng khóa, giai đoạn Kết Thúc, nếu thể lực của bạn là thấp nhất bàn, thì bạn hồi phục 1 điểm thể lực.",
	olyinhu: "Dần Hổ",
	olyinhu_info: "Giai đoạn Xuất Bài, bạn có thể bỏ một lá bài (loại bài bỏ bằng cách này trong giai đoạn này phải khác nhau mỗi lần), sau đó gây 1 điểm sát thương cho một nhân vật khác. Nếu có nhân vật vì điều này vào trạng thái hấp hối, thì kỹ năng này mất hiệu lực trong lượt này.",
	olmaotu: "Mão Thố",
	olmaotu_info: "Kỹ năng khóa, sau khi kết toán trạng thái hấp hối của một nhân vật xong, bạn không thể trở thành mục tiêu sử dụng bài của nhân vật khác có thể lực lớn hơn hoặc bằng bạn cho đến khi bắt đầu lượt tiếp theo.",
	olchenlong: "Thìn Long",
	olchenlong_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể mất tối đa 2 điểm thể lực, gây lượng sát thương tương ứng cho một nhân vật khác. Nếu bạn vì điều này vào trạng thái hấp hối, thì bạn giảm 1 điểm giới hạn thể lực.",
	olsishe: "Tỵ Xà",
	olsishe_info: "Sau khi bạn chịu sát thương, bạn có thể gây lượng sát thương tương ứng cho nguồn gây sát thương.",
	olwuma: "Ngọ Mã",
	olwuma_info: "Kỹ năng khóa. ① Bạn không thể bị lật úp. ② Các giai đoạn của bạn không thể bị bỏ qua. ③ Khi bạn trở thành mục tiêu sử dụng bài chú của nhân vật khác, bạn bốc một lá bài.",
	olweiyang: "Mùi Dương",
	olweiyang_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể bỏ một số lượng bài khác loại bất kỳ, sau đó khiến tối đa số lượng nhân vật tương ứng hồi phục 1 điểm thể lực.",
	olshenhou: "Thân Hầu",
	olshenhou_info: "Khi bạn trở thành mục tiêu của 【Giết】, bạn có thể thực hiện phán định, nếu kết quả là màu đỏ, thì 【Giết】 này vô hiệu với bạn.",
	olyouji: "Dậu Kê",
	olyouji_info: "Kỹ năng khóa, giai đoạn Bốc Bài, bạn bốc thêm X lá bài (X là số vòng chơi và tối đa là 5).",
	olxugou: "Tuất Cẩu",
	olxugou_info: "Kỹ năng khóa. ① 【Giết】 màu đỏ vô hiệu với bạn. ② Bạn dùng 【Giết】 màu đỏ không giới hạn khoảng cách và gây sát thương +1.",
	olhaizhu: "Hợi Trư",
	olhaizhu_info: "Kỹ năng khóa. ① Sau khi bài màu đen của nhân vật khác bị bỏ và đặt vào bộ bài bỏ, bạn nhận được những bài này. ② Giai đoạn Chuẩn Bị, nếu số bài trên tay bạn là nhiều nhất bàn, bạn mất 1 điểm thể lực.",
	hanshiwuhu: "Ngũ Hổ",
	hanshiwuhu_ab: "Hàn Thị Ngũ Hổ",
	hanshiwuhu_prefix: "Hàn Thị",
	oljuejue: "Giác Giác",
	oljuejue_info: "Kỹ năng khóa, lần đầu tiên bạn sử dụng 【Giết】/【Tránh】/【Đào】/【Rượu】 trong ván chơi này, sát thương hoặc giá trị hồi phục của bài này +1 và không tính vào giới hạn số lần, sau khi kết toán, bạn nhận được bài này.",
	olpimi: "Phi Mị",
	olpimi_info: "Sau khi bạn dùng bài chỉ định nhân vật khác làm mục tiêu duy nhất, hoặc trở thành mục tiêu duy nhất khi nhân vật khác dùng bài, bạn có thể bỏ một lá bài của người sử dụng, khiến sát thương hoặc giá trị hồi phục của bài này +1. Sau đó nếu bài trên tay của người sử dụng là nhiều nhất hoặc ít nhất, bạn bốc một lá bài và kỹ năng này mất hiệu lực trong lượt này.",
	ol_xiahouen: "OL Hạ Hầu Ân",
	ol_xiahouen_prefix: "OL",
	olyinfeng: "Dẫn Phong",
	olyinfeng_info: `Kỹ năng khóa. ① Khi bắt đầu ván chơi, bạn nhận được một ${get.poptip("chixueqingfeng")}. ② Khi ${get.poptip("chixueqingfeng")} vì bị bỏ vào bộ bài bỏ, bạn mất 1 điểm thể lực và nhận được nó. ③ Khi bài trên tay của bạn bị nhân vật khác nhận được, nếu trong tay bạn có ${get.poptip("chixueqingfeng")}, bạn gây cho người đó 1 điểm sát thương; nếu trong số bài người đó nhận lần này có ${get.poptip("chixueqingfeng")}, người đó gây cho bạn 1 điểm sát thương.`,
	olfulu: "Phụ Lỗ",
	olfulu_info: "① Sau khi 【Giết】 của bạn kết toán, bạn có thể đưa cho một trong số các nhân vật mục tiêu một lá bài trên tay, sau đó nhận tối đa hai lá bài trên tay của người đó. ② Sau khi 【Giết】 của nhân vật có thể lực nhỏ hơn bạn kết toán, nếu mục tiêu của 【Giết】 này bao gồm bạn, người đó có thể đưa cho bạn một lá bài trên tay, sau đó nhận tối đa hai lá bài trên tay của bạn.",
	tianji: "Điền Kỵ",
	dcweiji: "Vi Kế",
	dcweiji_info: "Khi bạn dùng bài chỉ định nhân vật khác làm mục tiêu, bạn có thể chọn một số từ 1-3, sau đó khiến một nhân vật mục tiêu khác chọn một số từ 1-3, nếu số bạn chọn khác với số người đó chọn, thì bạn bốc số lá bài bằng số bạn đã chọn.",
	dcsaima: "Tái Mã",
	dcsaima_info: "Khi bạn dùng bài Tọa Kỵ, bạn có thể chọn một nhân vật khác, thi điểm với người đó ba lần, nếu bạn thắng ít nhất hai lần, thì bạn gây cho người đó 1 điểm sát thương.",
	yuanshaoyuanshu: "Liệt Viên Thiệu Viên Thuật",
	yuanshaoyuanshu_prefix: "Liệt",
	yuanshaoyuanshu_shao: "Viên Thiệu",
	yuanshaoyuanshu_shu: "Viên Thuật",
	dclieti: "Liệt Đễ",
	dclieti_info: "Kỹ năng khóa, khi bắt đầu ván chơi, bạn nhận được hai bộ bài ban đầu và thêm nhãn hiệu tên tướng; khi bạn nhận được bài trên tay, sẽ thêm nhãn hiệu tên tướng vào bài dựa trên tướng hiện tại. Bạn chỉ có thể dùng hoặc đánh ra bài có nhãn hiệu tướng hiện tại. Bài không có nhãn hiệu tướng hiện tại không tính vào giới hạn bài trên tay.",
	dcshigong: "Thế Công",
	dcshigong_info: "Kỹ năng khóa, lá bài trên tay đầu tiên bạn sử dụng mỗi lượt không bị giới hạn bởi 【Liệt Đễ】, sau đó bạn chuyển đổi sang tướng có nhãn hiệu tương ứng. Nếu bạn chuyển sang Viên Thiệu vì điều này, bạn xem như sử dụng một 【Vạn Tiễn Tề Phát】; nếu bạn chuyển sang Viên Thuật vì điều này, bạn bốc hai lá bài.",
	dcluankui: "Loạn Khôi",
	dcluankui_info: "Sau khi bạn gây sát thương lần thứ hai mỗi lượt, có thể bỏ một lá bài “Viên Thiệu” để khiến sát thương lần tiếp theo của bạn trong lượt này gấp đôi; sau khi bạn nhận được bài lần thứ hai mỗi lượt, có thể bỏ một lá bài “Viên Thuật” để khiến số bài bốc lần tiếp theo của bạn trong lượt này gấp đôi.",
	taipingsangong: "Trương Giác Tam Huynh Đệ",
	oltiangong: "Thiên Công",
	oltiangong_info: `Kỹ năng khóa, khi bắt đầu lượt, bạn xem như sử dụng một ${get.poptip("leigong")}; khi kết thúc lượt, bạn xem như sử dụng một ${get.poptip("younan")}. Sau khi một nhân vật phán định, nếu kết quả là ♠, bạn gây 1 điểm sát thương Lôi cho một nhân vật khác.`,
	oldigong: "Địa Công",
	oldigong_info: "Kỹ năng khóa, khi bạn dùng bài không có “Địa Công”, nếu là bài sát thương, sát thương của bài này +1, nếu không phải bài sát thương, sau khi kết toán, nhân vật trong lượt hiện tại phán định, nếu kết quả là màu đỏ, bạn bốc một lá bài. Khi bạn nhận được bài, đánh dấu là “Địa Công”, khi kết thúc vòng này sẽ bỏ dấu hiệu này.",
	olrengong: "Nhân Công",
	olrengong_info: "Kỹ năng khóa, nếu bạn liên tục sử dụng hai lá bài khác loại, sau khi bài này kết toán, bạn bỏ một lá bài, sau đó lấy một lá bài loại còn lại từ bộ bài.",
	strong_caochong: "Tào Xung",
	strong_caochong_ab: "Xung Nhi",
	strongduanti: "Đoạn Thể",
	strongduanti_info: "Kỹ năng khóa, ① Sau khi bạn bốc bài từ bộ bài, chịu 1 điểm sát thương không rõ nguồn gốc. ② Khi bạn phát động 【Xưng Tượng】, nếu thể lực của bạn là thấp nhất bàn, nhất định lật ra một 【Đào】 hoặc 【Rượu】; nếu thể lực của bạn là cao nhất bàn, nhất định lật ra một bài sát thương hoặc bài Vũ Khí.",
	strongduanti_append: "<span class='text' style='font-family: yuanli'>Tôi muốn kiểm bài!</span>",
	stronglianwu: "Luyện Vũ",
	stronglianwu_info: "Sau khi bạn dùng 【Giết】 chỉ định mục tiêu duy nhất hoặc trở thành mục tiêu duy nhất của 【Giết】, người sử dụng có thể bỏ một lá bài của nhân vật mục tiêu cho mỗi điều kiện được thỏa mãn: 1. Đã trang bị bài Vũ Khí; 2. 【Giết】 này chịu ảnh hưởng của 【Rượu】.",
	ren_jiangwei: "Nhẫn Khương Duy",
	ren_jiangwei_prefix: "Nhẫn",
	ren_dengai: "Nhẫn Đặng Ngải",
	ren_dengai_prefix: "Nhẫn",
	renneyan: "Nột Ngôn",
	renneyan_info: "Kỹ năng chuyển hóa, kỹ năng khóa, khi bạn dùng bài không phải Trang Bị, Dương: bỏ một lá bài và khiến bài này kết toán thêm một lần, nếu không thì bài này vô hiệu; Âm: bài này không giới hạn số lần.",
	renqianyao: "Tiềm Diệu",
	renqianyao_info: "Kỹ năng giới hạn, khi bắt đầu lượt, bạn có thể bốc X lá bài, xem như sử dụng một 【Giết】 và lần lượt thực hiện X hạng mục đầu tiên: 1. 【Giết】 này chỉ định thêm một mục tiêu; 2. 【Giết】 này gây sát thương +1; 3. 【Giết】 này không thể bị đáp trả. (X là số vòng chơi)",
	renhuoluan: "Hoặc Loạn",
	renhuoluan_info: `Giai đoạn Xuất Bài giới hạn một lần, bạn có thể ${get.poptip("rule_gongtongpindian")} với tối đa hai nhân vật khác và ghi nhớ lá bài thi điểm của bạn, bạn có thể đổi lá bài thi điểm thành điểm số bất kỳ. Nhân vật có điểm số nhỏ nhất duy nhất được xem là mỗi nhân vật còn lại tham gia thi điểm dùng một 【Giết】 nhắm vào người đó, nhân vật có điểm số lớn nhất duy nhất bốc số lá bài bằng thể lực, nếu cả hai đều không phải là bạn, bạn thiết lập lại 【Hoặc Loạn】.`,
	renguxing: "Cô Tinh",
	renguxing_info: "Kỹ năng giới hạn, khi bắt đầu lượt, bạn có thể lần lượt thực hiện X hạng mục đầu tiên, từ bộ bài hoặc bộ bài bỏ: 1. Nhận được bài đã ghi nhớ bởi 【Hoặc Loạn】; 2. Nhận được tất cả bài có cùng điểm số và hoa với bài đã ghi nhớ bởi 【Hoặc Loạn】; 3. Nhận được bài có cùng tên với bài đã ghi nhớ bởi 【Hoặc Loạn】. (X là số vòng chơi, bài cùng tên nhận tối đa năm lá)",
	wild_liru: "Cuồng Lý Nho",
	wild_liru_prefix: "Cuồng",
	olhuaquan: "Hoa Quyền",
	olhuaquan_info: "Kỹ năng khóa, sau khi bạn dùng bài chỉ định nhân vật khác, bí mật chọn một hiệu ứng cho bài này: 1. Trọng Quyền, sát thương gây ra +1; 2. Khinh Quyền, sau khi dùng bạn bốc một lá bài. Sau đó (các) nhân vật mục tiêu khác lần lượt đoán hiệu ứng bạn đã chọn.",
	olhuaquan_heavy: "Trọng Quyền",
	olhuaquan_heavy_bg: "Trọng Quyền",
	olhuaquan_heavy_info: "Sát thương gây ra +1",
	olhuaquan_light: "Khinh Quyền",
	olhuaquan_light_bg: "Khinh Quyền",
	olhuaquan_light_info: "Sau khi dùng bạn bốc một lá bài",
	olsanou: "Tam Âu",
	olsanou_info: "Kỹ năng khóa, sau khi nhân vật khác chịu sát thương từ bạn hoặc đoán sai hiệu quả của 【Hoa Quyền】, bạn bốc một lá bài và khiến người đó nhận một dấu hiệu 「Kích Đảo」. Sau khi một nhân vật nhận được ít nhất 3 dấu hiệu 「Kích Đảo」, loại bỏ dấu hiệu này và bước vào trạng thái “Kích Đảo”. Nhân vật ở trạng thái “Kích Đảo” luôn bỏ qua giai đoạn Xuất Bài. Khi nhân vật ở trạng thái “Kích Đảo”, sau khi có 10 lá bài rời khỏi bộ bài hoặc vào bộ bài bỏ, người đó thoát khỏi trạng thái “Kích Đảo”.",
	bigsb_dengai: "OL Lạc Đặng Ngải",
	bigsb_dengai_prefix: "OL Lạc",
	olandu: "Ám Độ",
	olandu_info: `Kỹ năng khóa, sau khi bạn sử dụng một bài “${get.poptip({
		id: "andu_yinping",
		name: "Âm Bình",
		type: "character",
		info: "Nếu trong tên bài, chữ đầu tiên hoặc chữ cuối cùng có âm đọc là thanh ngang (âm bình, như ā, ē, ī), bài này gọi là bài “Âm Bình”",
	})}” kết toán xong, ngẫu nhiên nhận được một bài “${get.poptip("andu_yinping")}” trong bài trên tay của một nhân vật khác.`,
	olandu_mark: "Âm Bình",
	olqiqi: "Kỳ Kỳ",
	olqiqi_info: "Mỗi vòng giới hạn một lần, khi bạn dùng bài chỉ định mục tiêu, nếu số chữ trong tên bài không nhỏ hơn thể lực của bạn, bạn có thể bốc hai lá bài và khiến bài này kết toán thêm một lần, sau đó thực hiện phán định: nếu kết quả là ♥, bạn giảm 1 điểm giới hạn thể lực.",
	you_zhugeliang: "Có Gia Cát Lượng",
	you_zhugeliang_prefix: "Có",
	dcyingyou: "Ưng Hữu",
	dcyingyou_info: `① Khi bắt đầu lượt của bạn, giai đoạn Kết Thúc, sau khi chịu sát thương, bạn có thể chọn một hạng mục thực hiện và bốc một lá bài: 1. Ngẫu nhiên nhận được một kỹ năng của Ngũ Hổ Tướng; 2. Đặt ${get.poptip("real_zhuge")} vào khu vực Trang Bị; 3. Nhận được 10 tấn màn thầu. ② Khi bạn dùng bài trên tay, có thể tiêu hao số tấn màn thầu bằng điểm số của bài này, khiến bài này kết toán thêm một lần.`,
	real_zhuge: "Thật·Gia Cát Liên Nỏ",
	real_zhuge_info: "Bạn dùng 【Giết】 không giới hạn số lần, nếu 【Giết】 này có điểm số nhỏ hơn 7, không thể bị đáp trả. Bài này bị hủy sau khi rời khỏi khu vực Trang Bị.",
	real_zhuge_skill: "Thật·Gia Cát Liên Nỏ",
	real_zhuge_skill_info: "Bạn dùng 【Giết】 không giới hạn số lần, nếu 【Giết】 này có điểm số nhỏ hơn 7, không thể bị đáp trả.",
	ol_le_liushan: "OL Lạc Lưu Thiện",
	ol_le_liushan_prefix: "OL Lạc",
	oltuoquan: "Thác Quyền",
	oltuoquan_info: `Kỹ năng khóa, khi bắt đầu ván chơi, bạn khiến tất cả nhân vật khác nhận được ${get.poptip("oldianzan")}. Giai đoạn Chuẩn Bị, bạn đắm chìm hưởng lạc, mất các kỹ năng nhận được vì 【Thác Quyền】, sau đó chọn hai vị từ “${get.poptip({
		id: "tuoquan_fuchen",
		name: "Quý Hán Phụ Thần",
		type: "character",
		info: "Ban đầu là Quan Vũ, Trương Phi, Triệu Vân, Hoàng Trung, Khương Duy, Ngụy Diên, Mã Tắc, Trương Dực. Sau khi bỏ hết sẽ nhận được Tương Uyển, Phí Y.",
	})}” để ra trận, nhận được tất cả kỹ năng trên bài tướng của những tướng này (trừ kỹ năng giác tỉnh, kỹ năng giới hạn).`,
	oltuoquan_info_doudizhu: `Kỹ năng khóa, khi bắt đầu ván chơi, bạn khiến tất cả nông dân nhận được ${get.poptip("oldianzan")}. Giai đoạn Chuẩn Bị, bạn đắm chìm hưởng lạc, mất các kỹ năng nhận được vì 【Thác Quyền】, sau đó chọn hai vị từ “${get.poptip({
		id: "tuoquan_fuchen",
		name: "Quý Hán Phụ Thần",
		type: "character",
		info: "Ban đầu là Quan Vũ, Trương Phi, Triệu Vân, Hoàng Trung, Khương Duy, Ngụy Diên, Mã Tắc, Trương Dực. Sau khi bỏ hết sẽ nhận được Tương Uyển, Phí Y.",
	})}” để ra trận, nhận được tất cả kỹ năng trên bài tướng của những tướng này (trừ kỹ năng giác tỉnh, kỹ năng giới hạn).`,
	oldianzan: "Điểm Tán",
	oldianzan_info: "Nhấp vào kỹ năng này để hỗ trợ Lưu Thiện.",
	olxianglv: "Tương Lữ",
	olxianglv_info: `Kỹ năng khóa, khi bắt đầu ván chơi, bạn đặt mỗi lá bài cơ bản có tên khác nhau trong bộ bài một lá lên bài tướng. Mỗi khi bạn cho một “${get.poptip("tuoquan_fuchen")}” ra trận, ngẫu nhiên nhận được một trong những lá bài cơ bản đó.`,
	olanle: "An Lạc",
	olanle_info: `Kỹ năng khóa, sau khi bạn chịu sát thương, loại bỏ “${get.poptip("tuoquan_fuchen")}” đã ra trận, sau đó cùng với nhân vật trong lượt hiện tại mỗi người bốc một lá bài. Nếu bạn không còn “${get.poptip("tuoquan_fuchen")}” nào ra trận, bạn xem như có ${get.poptip("xiangle")}.`,
	bozai: "Ba Tử",
	quanjia: "Khuyên Giải",
	quanjia_info: "Sau khi nhân vật khác gây sát thương cho một nhân vật khác trong lượt của họ, bạn có thể ngẫu nhiên xem hai lá bài trên tay của nguồn gây sát thương. Nếu trong đó có 【Giết】, bạn dùng 【Giết】 đó nhắm vào người đó; nếu không có 【Giết】, thì lần sau phát động 【Khuyên Giải】 số bài xem +1.",
	xiangjiaoduanwu: "Hương Tiểu Đoan Ngọ",
	xuyuan: "Hứa Nguyện",
	xuyuan_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể chọn một hoa và một phân loại phụ của trang bị, sau đó ngẫu nhiên đặt một lá bài Trang Bị thỏa mãn yêu cầu từ bộ bài vào khu vực Trang Bị của bạn.",
	xiaomian: "Tiếu Diện",
	xiaomian_info: "Khi bạn dùng bài, có thể bốc X lá bài (X là số lượng bài trong khu vực Trang Bị của bạn cùng hoa với bài này). Nếu làm vậy, bạn bỏ một lá bài trong khu vực Trang Bị.",
	tw_dm_quyi: "TW Ma Cúc Nghĩa",
	tw_dm_quyi_prefix: "TW|Ma",
	dmchongqi: "Xung Kỵ",
	dmchongqi_info: `Mỗi lượt giới hạn một lần, sau khi bạn dùng 【Giết】 chỉ định mục tiêu, có thể bỏ một lá bài của nhân vật mục tiêu. ${get.poptip("rule_youji")}: 【Giết】 này gây sát thương +1.`,
	dmfanquan: "Phản Quyền",
	dmfanquan_info: `Sau khi bạn chịu sát thương, có thể chọn một nhân vật khác, khiến người đó chịu 1 điểm sát thương. ${get.poptip("rule_boji")}: người đó chịu X điểm sát thương, trong lượt này khoảng cách bạn tính với nhân vật khác +1 (X là giá trị sát thương bạn đã chịu).`,
	jm_yuanshu: "Tập Mật Viên Thuật",
	jm_yuanshu_prefix: "Tập Mật",
	mbjimi: "Tập Mật",
	mbjimi_info: "Kỹ năng khóa, khi bắt đầu ván chơi, tất cả nhân vật thay thế tất cả bài trên tay bằng số lượng tương ứng 【Đào】 hoặc 【Rượu】. Khi có 【Đào】 hoặc 【Rượu】 không vì sử dụng mà vào bộ bài bỏ, bạn nhận được một lá bài sát thương có số chữ là X (X là số lượng 【Đào】, 【Rượu】 vào bộ bài bỏ trong lượt này).",
	mbmaodie: "Mạo Điệp",
	mbmaodie_info: "Kỹ năng khóa, sau khi bạn dùng bài, nếu gây sát thương, bài sát thương bạn dùng lần tiếp theo trong lượt này cần có số chữ lớn hơn bài này; mỗi lượt giới hạn hai lần, nếu không gây sát thương, bạn nhận được một lá bài ban đầu trên tay của nhân vật mục tiêu.",
	mb_muniu: "Thủ Sát Mộc Ngưu Lưu Mã",
	mb_muniu_prefix: "Thủ Sát",
	mbshezi: "Nhiếp Tử",
	mbshezi_info: "Kỹ năng khóa, giai đoạn Chuẩn Bị, bạn chọn một nhân vật và chọn một khu vực của người đó, nếu trong khu vực đó của người đó có bài Trang Bị, bạn nhận được tất cả bài trong khu vực đó của người đó.",
	mbyixing: "Dịch Hình",
	mbyixing_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể đặt tất cả “Khí” vào bộ bài bỏ và bốc số lượng tương ứng, sau đó bạn có thể đặt một số lượng bài Trang Bị bất kỳ lên bài tướng của bạn, gọi là “Khí”. Bạn có tất cả hiệu ứng của “Khí”.",
	mb_dilu_prefix: "Thủ Sát",
	mb_dilu: "Thủ Sát Đích Lư",
	mbyuetan: "Dược Đàn",
	mbyuetan_info: "Sau khi nhân vật trong khoảng cách 1 với bạn trở thành mục tiêu của bài sát thương, bạn có thể đưa cho người đó một lá bài, sau khi bài này kết toán xong, nếu người đó không chịu sát thương, bạn bốc một lá bài. Mỗi lần bạn mất hai lá bài bằng cách này, bạn hồi phục 1 điểm thể lực.",
	mb_jueying_prefix: "Thủ Sát",
	mb_jueying: "Thủ Sát Tuyệt Ảnh",
	mbjiguan: "Ký Quán",
	mbjiguan_info: "Kỹ năng khóa, khi bắt đầu ván chơi, bạn đưa tất cả bài Tọa Kỵ ra khỏi ván chơi; giới hạn bài trên tay của bạn +2.",
	mbzhengpeng: "Chinh Bồng",
	mbzhengpeng_info: "Sau khi lượt của một nhân vật kết thúc, bạn có thể chọn một nhân vật đủ điều kiện và mất X điểm thể lực (X là số lần phát động kỹ năng này trong vòng này trước đó), mỗi điều kiện người đó thỏa mãn trong lượt này, bạn bốc một lá bài: đã chịu sát thương, đã mất bài Trang Bị, không phải nhân vật trong lượt hiện tại và đã nhận được bài. Thừa thế: thiết lập lại X của kỹ năng này, sau đó bạn nhận được mỗi loại một lá bài từ bộ bài bỏ.",
	mb_chitu_prefix: "Thủ Sát",
	mb_chitu: "Thủ Sát Xích Thố",
	mbjunkui: "Tuấn Khôi",
	mbjunkui_info: "Kỹ năng khóa, khi bắt đầu ván chơi, bạn đưa tất cả bài Tọa Kỵ ra khỏi ván chơi; giới hạn số lần bạn dùng 【Giết】 +1.",
	mbchiyuan: "Trì Nguyên",
	mbchiyuan_info: "【Giết】 đầu tiên bạn dùng mỗi lượt không giới hạn khoảng cách và cần dùng thêm một 【Tránh】 để đáp trả. Giai đoạn Xuất Bài giới hạn một lần, bạn có thể bốc X lá bài (X là số lượng bài đỏ được sử dụng liên tục hiện tại).",
	tizhongzhishen: "Thể Trọng Chi Thần",
	dcgunyuan: "Cổn Viên",
	dcgunyuan_info: "Kỹ năng khóa, ① Lần đầu tiên mỗi vòng bạn vào trạng thái hấp hối, hồi phục thể lực về 1 điểm và tăng 1 điểm giới hạn thể lực (tối đa +3); ② Giới hạn bài trên tay của bạn bằng giới hạn thể lực của bạn.",
	dczuandai: "Toàn Đại",
	dczuandai_info: "Khi bắt đầu giai đoạn Xuất Bài của bạn, bạn có thể ngẫu nhiên sử dụng một lá bài Trang Bị từ bộ bài hoặc bộ bài bỏ và bốc một lá bài, sau đó lập tức kết thúc giai đoạn Xuất Bài.",
	keaizhishen: "Khả Ái Chi Thần",
	dcmaimeng: "Mại Manh",
	dcmaimeng_info: "Sau khi giá trị thể lực của bạn thay đổi, bạn có thể chọn một hạng mục thực hiện: 1. Bốc X lá bài và ngăn ngừa sát thương bạn chịu lần tiếp theo trong lượt này; 2. Khiến một nhân vật khác đưa cho bạn X lá bài và lá bài tiếp theo người đó dùng trong lượt này vô hiệu (X là số lần phát động kỹ năng này trong lượt này).",
	weiquzhishen: "Ủy Khuất Chi Thần",
	dcweiqu: "Ủy Khuất",
	dcweiqu_info: "Mỗi lượt giới hạn hai lần, khi bạn là mục tiêu duy nhất của bài thực thể, có thể chọn một hạng mục thực hiện: 1. Bỏ tất cả bài trong khu vực Trang Bị và khiến bài này vô hiệu, 2. Bỏ tất cả bài trên tay và bốc số lượng tương ứng. (Khi bạn thực hiện xong hai hạng mục khác nhau trong một lượt, bạn bốc hai lá bài).",
	juezezhishen: "Quyết Trạch Chi Thần",
	dchuibian: "Tuệ Biện",
	dchuibian_info: "Giai đoạn Xuất Bài, bạn có thể chọn mỗi nhân vật một lá bài trên tay của hai nhân vật và đoán xem màu của hai lá bài này có giống nhau không, nếu bạn đoán đúng, bạn nhận được và tiết lộ hai lá bài này; nếu bạn đoán sai, bạn bỏ hai lá bài này và kỹ năng này mất hiệu lực đến cuối lượt này.",
	bianhuanzhishen: "Biến Hóa Chi Thần",
	dcbaibian: "Bách Biến",
	dcbaibian_info: "Khi bắt đầu lượt của bạn hoặc sau khi chịu sát thương, ngẫu nhiên nhận được một kỹ năng tướng trong Meow Mao Sát cho đến khi kết thúc lượt của bạn.",
	shuimianzhishen: "Thụy Miên Chi Thần",
	dckeshui: "Khoái Thụy",
	dckeshui_info: "Mỗi lượt của bạn giới hạn một lần, khi bắt đầu mỗi giai đoạn của bạn, bạn có thể bỏ qua giai đoạn này (trừ giai đoạn Chuẩn Bị và Kết Thúc), sau đó bạn dùng một lá bài trên cùng bộ bài, sau khi bài này kết toán sẽ kết toán thêm một lần cho một mục tiêu ngẫu nhiên, nếu bài này không thể dùng, bạn nhận được bài này và bỏ qua giai đoạn tiếp theo của bạn trong lượt này và có thể phát động lại kỹ năng này.",
	nizhuanzhishen: "Nghịch Chuyển Chi Thần",
	dcfanzhuan: "Phản Chuyển",
	dcfanzhuan_info: "Mỗi vòng giới hạn một lần, khi bắt đầu mỗi lượt, bạn có thể điều chỉnh thể lực của bạn thành giá trị thể lực đã mất và bốc số lá bài bằng giá trị thay đổi.",
	dcniyun: "Nghịch Vận",
	dcniyun_info: "Kỹ năng khóa, phạm vi tấn công, số lần dùng 【Giết】 của bạn đều +X (X là thể lực đã mất của bạn).",
	meituizhishen: "Mỹ Thoái Chi Thần",
	dcshentui: "Thân Thoái",
	dcshentui_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể khiến phạm vi tấn công của bạn +1 và xem như sử dụng một 【Giết】, 【Giết】 bạn dùng có điểm số nhỏ hơn phạm vi tấn công không giới hạn số lần và không thể đáp trả, 【Giết】 bạn dùng có điểm số lớn hơn phạm vi tấn công không giới hạn khoảng cách và gây sát thương +1.",
	dcxurui: "Súc Duệ",
	dcxurui_info: "Kỹ năng khóa, khi kết thúc lượt của bạn, nếu bạn chưa gây sát thương trong lượt này, bạn bốc số lá bài bằng phạm vi tấn công (tối đa là 5).",
	gongbaiwan: "Cung Bách Vạn",
	dchaoshi: "Hiếu Thực",
	dchaoshi_info: "Sau khi bạn gây ra hoặc chịu sát thương, bạn bốc một lá bài và đặt một lá bài lên bài tướng, khi kết thúc mỗi lượt, nếu tổng điểm số của các lá bài trên bài tướng bạn lớn hơn hoặc bằng 100, bạn nhận được một lượt bổ sung và nhận được những lá bài này.",
	ol_le_zhugeliang: "Lạc Gia Cát Lượng",
	ol_le_zhugeliang_prefix: "Lạc",
	oljiangwu: "Giảng Vũ",
	oljiangwu_info: "Kỹ năng khóa, khi bắt đầu vòng đầu tiên, bạn chọn ba “Chiến Pháp” có giá trị khác nhau để nhận. Nếu làm vậy, sau khi kết thúc mỗi vòng tiếp theo, bạn thực hiện một lần lựa chọn “Chiến Pháp” tiêu hao “Hổ Phù”. Khi kết thúc lượt của mỗi nhân vật, bạn nhận được 1 “Hổ Phù”.",
	olxinghan: "Hưng Hán",
	olxinghan_info: `Kỹ năng giới hạn, giai đoạn Xuất Bài, bạn có thể mất một số lượng chiến pháp bất kỳ, sau đó số lượng chiến pháp cấp thấp tương ứng bạn mua không tiêu hao hổ phù, và mỗi khi bạn mất một chiến pháp bằng cách này, bạn lần lượt nhận được một chiến pháp độc quyền sau: ${get.poptip("zf_dongfeng")}, ${get.poptip("zf_qiaoqi")}.`,
	ol_re_nianshou: "Niên Thú",
	olsuizhong: "Tuế Chung",
	...(() => {
		const info = "Kỹ năng khóa, sau khi bạn chịu sát thương lần đầu tiên mỗi lượt, nếu thể lực của bạn nhỏ hơn hoặc bằng 1, thì bạn hồi phục 1 điểm thể lực, sau đó bỏ một lá bài của tất cả nhân vật phe địch.";
		return {
			olsuizhong_info: info,
			olsuizhong_info_identity: info.replace("phe địch", "khác"),
		};
	})(),
	olnianyi: "Niên Dận",
	...(() => {
		const info = "Kỹ năng khóa. ① Bạn dùng bài không giới hạn khoảng cách. ② Giai đoạn Chuẩn Bị, bạn ngẫu nhiên bỏ hai lá bài trong khu vực Phán Định. ③ Sau khi kết thúc lượt của nhân vật khác, nếu bạn đã mất ít nhất ba lá bài trong lượt này, thì bạn gây cho tất cả nhân vật phe địch mỗi người 1 điểm sát thương.";
		return {
			olnianyi_info: info,
			olnianyi_info_identity: info.replace("phe địch", "khác"),
		};
	})(),
	olfuyou: "Phúc Hựu",
	olfuyou_info: "Kỹ năng khóa. ① Bạn dùng bài chú thông thường màu đỏ kết toán thêm một lần. ② Mỗi lượt giới hạn một lần, sau khi bạn dùng bài chú thông thường màu đỏ gây sát thương, bạn bốc một lá bài.",
	tw_dm_zhouyu: "TW Ma Chu Du",
	tw_dm_zhouyu_prefix: "TW|Ma",
	yiran: "Dịch Nhiên",
	yiran_info: "Kỹ năng khóa, sát thương Hỏa bạn chịu +1.",
};

export default translates;
