import { lib, game, ui, get, ai, _status } from "noname";

const translates = {
	lijue: "Lý Quyết",
	zhangji: "Trương Tế",
	fanchou: "Phàn Trù",
	guosi: "Quách Tị",
	lvkai: "Lã Khải",
	zhanggong: "Trương Cung",
	weiwenzhugezhi: "Vệ Ôn Gia Cát Trực",
	sp_liuqi: "Lưu Kỳ",
	xf_tangzi: "Đường Tư",
	gz_xf_huangquan: "Hoàng Quyền",
	xf_huangquan: "OL Hoàng Quyền",
	xf_huangquan_prefix: "OL",
	gz_xf_sufei: "Tô Phi",
	xf_sufei: "OL Tô Phi",
	xf_sufei_prefix: "OL",
	xinfu_langxi: "Lang Kích",
	xinfu_langxi_info: "Giai đoạn chuẩn bị, bạn có thể gây 0~2 điểm sát thương ngẫu nhiên cho một nhân vật khác có thể lực ít hơn hoặc bằng bạn.",
	xinfu_yisuan: "Diệc Toán",
	xinfu_yisuan_info: "Mỗi lượt giới hạn một lần. Khi thẻ Cẩm Nang bạn sử dụng trong giai đoạn ra bài kết thúc kết toán, bạn có thể giảm 1 điểm giới hạn thể lực và nhận tất cả thực thể thẻ tương ứng với thẻ này.",
	xinfu_xingluan: "Hưng Loạn",
	xinfu_xingluan_info: "Mỗi lượt giới hạn một lần. Khi thẻ chỉ định duy nhất một mục tiêu bạn sử dụng trong giai đoạn ra bài kết thúc kết toán, bạn có thể nhận ngẫu nhiên một thẻ có điểm số là 6 từ chồng bài.",
	xinfu_lveming: "Lược Mệnh",
	xinfu_lveming_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể chọn một nhân vật có số trang bị trong vùng trang bị ít hơn bạn, khiến người đó chọn một điểm số, sau đó bạn tiến hành phán xét: <br>Nếu điểm số giống nhau, bạn gây 2 điểm sát thương cho người đó; <br>Nếu điểm số khác nhau, bạn nhận ngẫu nhiên một thẻ trong vùng của người đó.",
	xinfu_tunjun: "Truân Quân",
	xinfu_tunjun_info: "Kỹ năng giới hạn, giai đoạn ra bài, bạn có thể chọn một nhân vật, khiến người đó sử dụng ngẫu nhiên X thẻ trang bị từ chồng bài (X là số lần bạn đã phát động “Lược Mệnh”).",
	xinfu_tanbei: "Tham Bối",
	xinfu_tanbei_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể khiến một nhân vật khác chọn một: 1. Khiến bạn nhận ngẫu nhiên một thẻ trong vùng của người đó, trong lượt này bạn không thể sử dụng thẻ lên người đó. 2. Khiến bạn trong lượt này sử dụng thẻ lên người đó không bị giới hạn số lần và khoảng cách.",
	xinfu_sidao: "Sưu Đạo",
	xinfu_sidaox: "Sưu Đạo",
	xinfu_sidao_info: "Giai đoạn ra bài giới hạn một lần, khi bạn sử dụng liên tiếp hai thẻ lên một nhân vật khác, bạn có thể dùng một thẻ trên tay như là [Thuận Thủ牵Dương] sử dụng lên người đó.",
	tanbei_effect1: "Tham Bối",
	tanbei_effect1_info: "",
	tanbei_effect2: "Tham Bối",
	tanbei_effect2_info: "",

	xinfu_tunan: "Đồ Nam",
	xinfu_tunan_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể khiến một nhân vật khác xem thẻ trên cùng của chồng bài, sau đó nhân vật đó chọn một: 1. Sử dụng thẻ này (không giới hạn khoảng cách); 2. Dùng thẻ này như [Sát] bình thường.",
	xinfu_bijing: "Bế Cảnh",
	xinfu_bijing_info: "Giai đoạn kết thúc, bạn có thể chọn tối đa hai thẻ trên tay và đánh dấu là “Bế Cảnh”, sau đó nhận hiệu ứng sau: 1. Khi giai đoạn bỏ bài của nhân vật khác bắt đầu, nếu bạn đã mất thẻ “Bế Cảnh” trong lượt này, người đó bỏ hai thẻ; 2. Giai đoạn chuẩn bị, bạn đúc lại tất cả thẻ “Bế Cảnh”.",
	xinfu_zhenxing: "Trấn Hành",
	xinfu_zhenxing_info: "Khi giai đoạn kết thúc bắt đầu hoặc sau khi bạn chịu sát thương, bạn có thể xem tối đa ba thẻ trên cùng của chồng bài, sau đó nhận một thẻ có hoa sắc không trùng với các thẻ còn lại.",
	xinfu_qianxin: "Khiển Tín",
	xinfu_qianxin_info: "Giai đoạn ra bài giới hạn một lần, nếu trong chồng bài không có “Tín”, bạn có thể chọn một nhân vật và đặt số thẻ bất kỳ trên tay vào vị trí bội số của X trong chồng bài (X là số người còn sống), gọi là “Tín”. Khi giai đoạn bỏ bài của nhân vật đó bắt đầu, nếu trong vùng bài trên tay có “Tín” nhận được trong lượt này, người đó chọn một: Khiến bạn rút bài cho đến khi đủ bốn lá; Lượt này giới hạn bài trên tay -2.",
	qianxin_effect: "Khiển Tín",
	qianxin_effect_info: "",
	xinfu_qianxin2: "Khiển Tín",
	xinfu_qianxin2_info: "",

	xinfu_fuhai: "Phù Hải",
	xinfu_fuhai_info: "Giai đoạn ra bài mỗi hướng giới hạn một lần, bạn có thể trưng ra một thẻ trên tay và chọn cửa trên hoặc cửa dưới. Nhân vật đó trưng ra một thẻ trên tay, nếu điểm số thẻ bạn trưng ra lớn hơn hoặc bằng điểm số thẻ người đó trưng ra, bạn bỏ thẻ mình đã trưng, sau đó tiếp tục lặp lại quy trình này với cửa trên hoặc cửa dưới của người đó; nếu điểm số thẻ bạn trưng ra nhỏ hơn điểm số thẻ người đó trưng ra, nhân vật đó bỏ thẻ đã trưng, sau đó bạn và người đó mỗi người rút X thẻ (X là số nhân vật bạn đã chọn phát động kỹ năng này trong lượt), và bạn không thể phát động [Phù Hải] thêm lần nào nữa trong giai đoạn này.",
	fuhai_clear: "Phù Hải",
	fuhai_clear_info: "",

	xz_xunxun: "Tuần Tuần",
	xz_xunxun_info: "Giai đoạn rút bài, bạn có thể xem bốn thẻ trên cùng của chồng bài, sau đó đặt hai thẻ trong số đó lên đỉnh chồng bài, và đặt các thẻ còn lại xuống đáy chồng bài theo thứ tự bất kỳ.",
	xinfu_xingzhao: "Hưng Trạo",
	xinfu_xingzhao_info: "Kỹ năng khóa. Nếu số nhân vật đã bị thương trên sân: ≥1, bạn được coi là có kỹ năng [Tuần Tuần]; ≥2, khi có thẻ trang bị đi vào hoặc rời khỏi vùng trang bị của bạn, bạn rút một thẻ; ≥3, khi giai đoạn phán xét hoặc giai đoạn bỏ bài bắt đầu, bạn bỏ qua giai đoạn đó; bằng 0 hoặc ≥4, khi bạn gây sát thương, sát thương này +1.",
	xinfu_xingzhao2: "Hưng Trạo",
	xinfu_xingzhao2_info: "",
	xinfu_xingzhao3: "Hưng Trạo",
	xinfu_dianhu: "Điểm Hổ",
	xinfu_dianhu_info: "Kỹ năng khóa, khi trò chơi bắt đầu, bạn chọn một nhân vật khác. Khi người đó chịu sát thương từ bạn hoặc hồi phục thể lực, bạn rút một thẻ.",
	xinfu_dianhu2: "Điểm Hổ",
	xinfu_dianhu2_info: "",
	xinfu_jianji: "Gián Kế",
	xinfu_jianji_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể khiến một nhân vật khác rút một thẻ. Sau đó nhân vật đó có thể sử dụng thẻ này.",
	xinfu_lianpian: "Liên Phiến",
	xinfu_lianpian_info: "Giai đoạn ra bài giới hạn ba lần. Khi bạn sử dụng thẻ liên tiếp lên một nhân vật, bạn có thể rút một thẻ, sau đó có thể đưa một thẻ cho nhân vật đó.",
	spwenji: "Vấn Kế",
	spwenji_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể khiến một nhân vật khác đưa cho bạn một thẻ. Khi bạn sử dụng thẻ cùng tên với thẻ đó trong lượt này, các nhân vật khác không thể hưởng ứng.",
	rewenji: "Vấn Kế",
	rewenji_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể khiến một nhân vật khác đưa cho bạn một thẻ. Khi bạn sử dụng thẻ cùng loại với thẻ đó trong lượt này, các nhân vật khác không thể hưởng ứng.",
	sptunjiang: "Truân Giang",
	sptunjiang_info: "Giai đoạn kết thúc, nếu bạn không sử dụng thẻ chỉ định nhân vật khác làm mục tiêu trong giai đoạn ra bài lượt này, bạn có thể rút X thẻ (X là số phe phái trên sân).",
	zongkui: "Túng Khôi",
	zongkui_mark: "Túng Khôi",
	zongkui_mark_bg: "Khôi",
	zongkui_info: "Trước khi lượt bắt đầu, bạn có thể chỉ định một nhân vật khác chưa có dấu ấn “Khôi”, khiến người đó nhận một dấu ấn “Khôi”. Mỗi khi vòng mới bắt đầu, bạn chỉ định một nhân vật khác có thể lực ít nhất và chưa có dấu ấn “Khôi”, khiến người đó nhận một dấu ấn “Khôi”.",
	guju: "Cốt Thư",
	guju_info: "Kỹ năng khóa, sau khi nhân vật có dấu ấn “Khôi” chịu sát thương, bạn rút một thẻ.",
	baijia: "Bái Giả",
	baijia_info: "Kỹ năng thức tỉnh, giai đoạn chuẩn bị, nếu số thẻ bạn nhận được từ [Cốt Thư] không dưới bảy lá, bạn tăng 1 điểm giới hạn thể lực, hồi 1 điểm thể lực, sau đó khiến tất cả nhân vật khác chưa có dấu ấn “Khôi” nhận dấu ấn “Khôi”, cuối cùng mất kỹ năng [Cốt Thư] và nhận kỹ năng [Tàm Thực].",
	bmcanshi: "Tàm Thực",
	bmcanshi_info: "Khi một nhân vật sử dụng thẻ Cơ Bản hoặc thẻ Cẩm Nang bình thường chỉ định bạn là mục tiêu duy nhất, nếu người đó có dấu ấn “Khôi”, bạn có thể hủy bỏ nó, sau đó người đó mất dấu ấn “Khôi”; khi bạn sử dụng thẻ chỉ định duy nhất một nhân vật làm mục tiêu, bạn có thể chỉ định thêm bất kỳ số lượng nhân vật nào có dấu ấn “Khôi” làm mục tiêu (không giới hạn khoảng cách), sau đó những nhân vật này mất dấu ấn “Khôi”.",

	xinpi: "Tân Tì",
	lisu: "Lý Túc",
	zhangwen: "Trương Ôn",
	xushao: "Hứa Thiệu",
	mangyachang: "Mang Nha Trường",
	xugong: "Hứa Cống",
	zhangchangpu: "Trương Xương Bồ",
	pingjian: "Bình Tiến",
	pingjian_use: "Bình Tiến",
	pingjian_info: "Khi giai đoạn kết thúc bắt đầu/Khi bạn chịu sát thương/Giai đoạn ra bài giới hạn một lần, bạn có thể khiến hệ thống truy xuất ngẫu nhiên ba thẻ Võ tướng có kỹ năng phát động vào thời điểm Giai đoạn kết thúc bắt đầu/Khi bạn chịu sát thương/Giai đoạn ra bài. Sau đó bạn có thể chọn thử phát động một trong các kỹ năng đó. Mỗi kỹ năng chỉ có thể chọn một lần trong mỗi ván game.",

	songshu: "Tụng Thục",
	songshu_info: "Giai đoạn ra bài, bạn có thể đấu điểm với nhân vật khác. Nếu bạn không thắng, bạn và người đó mỗi người rút hai thẻ, và bạn không thể phát động [Tụng Thục] thêm lần nào nữa trong giai đoạn này.",
	sibian: "Tư Biện",
	sibian_info: "Giai đoạn rút bài, bạn có thể từ bỏ rút bài, thay bằng lật bốn thẻ trên cùng của chồng bài, sau đó nhận tất cả các thẻ có điểm số lớn nhất và nhỏ nhất, đồng thời có thể đưa các thẻ còn lại cho nhân vật có số bài trên tay ít nhất.",
	lslixun: "Lợi Huân",
	lslixun_fate: "Lợi Huân",
	lslixun_info: "Kỹ năng khóa, khi bạn chịu sát thương, bạn ngăn chặn sát thương này, sau đó nhận dấu ấn “Châu” tương đương với giá trị sát thương. Khi giai đoạn ra bài bắt đầu, bạn tiến hành phán xét, nếu điểm số kết quả nhỏ hơn số lượng “Châu”, bạn bỏ số thẻ trên tay tương đương số lượng “Châu” (nếu không đủ số bài để bỏ, thì mất số lượng thể lực còn lại).",
	lskuizhu: "Quỹ Châu",
	lskuizhu_info: "Khi giai đoạn ra bài kết thúc, bạn có thể chọn một nhân vật khác có thể lực nhiều nhất trên sân, rút bài cho đến khi bằng với người đó (tối đa rút đến năm lá), sau đó nhân vật đó xem bài trên tay bạn, bỏ số lượng thẻ bất kỳ và nhận số lượng thẻ tương đương từ những thẻ đã xem. Nếu người đó nhận được nhiều hơn một thẻ, bạn chọn một: Loại bỏ một “Châu”; hoặc khiến người đó gây 1 điểm sát thương cho một nhân vật trong phạm vi tấn công của mình.",
	xpchijie: "Trì Tiết",
	xpchijie_info: "Mỗi lượt mỗi hạng mục giới hạn một lần. 1. Khi thẻ nhân vật khác sử dụng lên bạn kết thúc kết toán, bạn có thể khiến thẻ này vô hiệu với tất cả mục tiêu tiếp theo. 2. Khi thẻ nhân vật khác sử dụng kết thúc kết toán, nếu bạn là một trong những mục tiêu của thẻ này và thẻ này chưa từng gây sát thương, bạn có thể nhận tất cả thực thể thẻ tương ứng với thẻ này.",
	xpchijie2: "Trì Tiết",
	yinju: "Dẫn Cứ",
	yinju_info: "Kỹ năng giới hạn, giai đoạn ra bài, bạn có thể chọn một nhân vật khác. Nếu làm vậy, cho đến khi kết thúc lượt: 1. Khi bạn sử dụng thẻ chỉ định người đó làm mục tiêu, bạn và người đó mỗi người rút một thẻ; 2. Khi bạn sắp gây sát thương cho người đó, ngăn chặn sát thương này, sau đó người đó hồi phục thể lực tương đương.",
	yinju2: "Dẫn Cứ",

	spjiedao: "Tiết Đao",
	spjiedao_info: "Khi bạn gây sát thương lần đầu tiên mỗi lượt, bạn có thể khiến sát thương này tối đa +X (X là số thể lực bạn đã mất). Sau đó nếu nhân vật chịu sát thương này không chết, bạn bỏ số thẻ tương đương với giá trị cộng thêm của sát thương này.",
	biaozhao: "Biểu Triệu",
	biaozhao_info: "Giai đoạn kết thúc, bạn có thể đặt một thẻ lên thẻ Võ tướng, gọi là “Biểu”. Khi có một thẻ có cùng hoa sắc và điểm số với “Biểu” đi vào chồng bài bỏ, bạn đặt “Biểu” vào chồng bài bỏ và mất 1 điểm thể lực, nếu thẻ này do nhân vật khác bỏ bài mà đi vào chồng bài bỏ, thì thay bằng việc nhân vật đó nhận lấy “Biểu”. Giai đoạn chuẩn bị, nếu trên thẻ Võ tướng của bạn có “Biểu”, bạn đặt “Biểu” vào chồng bài bỏ. Sau đó bạn chọn một nhân vật, nhân vật đó hồi 1 điểm thể lực và rút bài cho đến khi bằng người có nhiều bài trên tay nhất trên sân (tối đa rút đến năm lá).",
	biaozhao2: "Biểu Triệu",
	biaozhao2_info: "",
	biaozhao3: "Biểu Triệu",
	biaozhao3_info: "",
	yechou: "Nghiệp Thù",
	yechou_info: "Khi bạn chết, bạn có thể chọn một nhân vật có số thể lực đã mất lớn hơn 1. Cho đến trước khi lượt tiếp theo của người đó bắt đầu, khi mỗi giai đoạn kết thúc của mỗi lượt kết thúc, nhân vật đó mất 1 điểm thể lực.",
	yechou2: "Nghiệp Thù",
	yechou2_info: "",
	yanjiao: "Nghiêm Giáo",
	yanjiao_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể chọn một nhân vật khác và lật bốn thẻ từ đỉnh chồng bài. Nhân vật đó chia những thẻ này thành hai nhóm có tổng điểm số bằng nhau, bạn và người đó mỗi người nhận một nhóm, sau đó đặt các thẻ còn lại chưa phân nhóm vào chồng bài bỏ. Nếu số thẻ chưa phân nhóm nhiều hơn một lá, giới hạn bài trên tay lượt này của bạn -1.",
	yanjiao2: "Nghiêm Giáo",
	yanjiao2_info: "",
	xingshen: "Tỉnh Thân",
	xingshen_info: "Sau khi bạn chịu sát thương, bạn có thể rút một thẻ và lần tiếp theo phát động [Nghiêm Giáo] số thẻ lật ra +1. Nếu số bài trên tay bạn là ít nhất trên sân, thay bằng rút hai thẻ; nếu thể lực bạn là ít nhất trên sân, số thẻ lật ra của [Nghiêm Giáo] thay bằng +2 (tổng giá trị cộng thêm không quá 4).",

	sp_zhanghe: "SP Trương Cáp",
	sp_zhanghe_prefix: "SP",
	yuanlve: "Viễn Lược",
	yuanlve_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể đưa một thẻ không phải trang bị cho một nhân vật, sau đó nhân vật đó có thể sử dụng thẻ này và khiến bạn rút một thẻ.",
	xunchen: "OL Tuân Thâm",
	xunchen_prefix: "OL",
	fenglve: "Phong Lược",
	fenglve2: "Phong Lược",
	fenglve_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể đấu điểm với một nhân vật, nếu bạn thắng, nhân vật đó đưa cho bạn mỗi loại một thẻ trong các vùng của mình; nếu bạn không thắng, bạn đưa cho người đó một thẻ. Sau khi kết toán đấu điểm đơn nhân của bạn, bạn có thể khiến đối phương nhận lấy thẻ đấu điểm của bạn.",
	mouzhi: "Mưu Thức",
	mouzhi2: "Mưu Thức",
	mouzhi_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể đưa một thẻ trên tay cho một nhân vật, nếu làm vậy, khi người đó gây sát thương cho một nhân vật trong giai đoạn ra bài của lượt tiếp theo, nếu đó là lần đầu tiên người đó gây sát thương cho nhân vật đó trong giai đoạn này, bạn rút một thẻ.",
	sp_shenpei: "SP Thẩm Phối",
	sp_shenpei_prefix: "SP",
	gangzhi: "Cương Trực",
	gangzhi_info: "Kỹ năng khóa, khi bạn sắp chịu sát thương do nhân vật khác gây ra, hoặc sắp gây sát thương cho nhân vật khác, bạn ngăn chặn sát thương này, thay bằng nhân vật chịu sát thương mất lượng thể lực tương đương.",
	beizhan: "Bị Chiến",
	beizhan2: "Bị Chiến",
	beizhan_info: "Giai đoạn kết thúc, bạn có thể khiến một nhân vật rút bài đến giới hạn thể lực (tối đa là 5). Khi lượt tiếp theo của người đó bắt đầu, nếu số bài trên tay người đó là nhiều nhất trên sân, thì những thẻ người đó sử dụng trong lượt này không thể chỉ định nhân vật khác làm mục tiêu.",
	gaolan: "OL Cao Lãm",
	gaolan_prefix: "OL",
	xiying: "Tập Doanh",
	xiying2: "Tập Doanh",
	xiying_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể bỏ một thẻ trên tay không phải thẻ Cơ Bản, sau đó khiến tất cả các nhân vật khác lần lượt chọn một: Bỏ một thẻ, hoặc không thể sử dụng hay đánh ra thẻ trong lượt này; và bạn nhận được hiệu ứng sau trong lượt này: Giai đoạn kết thúc, nếu bạn đã gây sát thương trong giai đoạn ra bài lượt này, bạn nhận được một thẻ Cơ Bản gây sát thương hoặc thẻ Cẩm Nang bình thường từ chồng bài.",
	lvkuanglvxiang: "OL Lã Khoáng Lã Tường",
	lvkuanglvxiang_prefix: "OL",
	liehou: "Liệt Hầu",
	liehou_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể khiến một nhân vật trong phạm vi tấn công đưa cho bạn một thẻ trên tay, sau đó bạn đưa một thẻ trên tay cho một nhân vật khác trong phạm vi tấn công.",
	qigong: "Tề Công",
	qigong_info: "Sau khi thẻ [Sát] bạn sử dụng bị [Thiểm] triệt tiêu, bạn có thể khiến một nhân vật khác sử dụng thêm một thẻ [Sát] lên mục tiêu đó (không thể bị hưởng ứng).",
	chunyuqiong: "Thuần Vu Quỳnh",
	sushou: "Túc Thủ",
	sushou_info: "Khi giai đoạn bỏ bài bắt đầu, bạn có thể rút X+1 thẻ (X là số “Lương”), sau đó có thể đưa cho bất kỳ nhân vật phe đồng minh nào mỗi người một thẻ.",
	cangchu: "Thương Trữ",
	cangchu_info: "Kỹ năng khóa, khi trò chơi bắt đầu, bạn nhận 3 dấu ấn “Lương”, sau khi bạn chịu 1 điểm sát thương lửa, bạn mất một dấu ấn “Lương”.",
	liangying: "Lương Doanh",
	liangying_info: "Kỹ năng khóa, nếu bạn có dấu ấn “Lương”, số thẻ rút trong giai đoạn rút bài của nhân vật phe đồng minh +1; sau khi bạn mất tất cả dấu ấn “Lương”, bạn giảm 1 điểm giới hạn thể lực, sau đó khiến các nhân vật phe địch mỗi người rút hai thẻ.",
	sp_xuyou: "SP Hứa Du",
	sp_xuyou_prefix: "SP",
	spshicai: "Thị Tài",
	spshicai2: "Thị Tài",
	spshicai_info: "Giai đoạn ra bài, thẻ trên cùng của chồng bài hiển thị với bạn. Bạn có thể bỏ một thẻ, sau đó nhận thẻ trên cùng của chồng bài, và không thể phát động tiếp [Thị Tài] cho đến khi thẻ này rời khỏi vùng bài trên tay bạn.",
	spfushi: "Phụ Thế",
	spfushi_info: "Kỹ năng khóa, nếu số nhân vật phe ta còn sống: nhiều hơn phe địch, bạn được coi là có [Trạch Chủ]; ít hơn phe địch, bạn được coi là có [Sính Công].",
	zezhu: "Trạch Chủ",
	zezhu_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể nhận mỗi chủ soái của hai bên một thẻ (nếu không có thẻ thì thay bằng việc bạn rút một thẻ), sau đó đưa cho mỗi chủ soái một thẻ.",
	chenggong: "Sính Công",
	chenggong_info: "Khi có nhân vật sử dụng thẻ chỉ định mục tiêu, nếu số mục tiêu của thẻ này lớn hơn 1, bạn có thể khiến người sử dụng rút một thẻ.",
	sp_zhangliao: "SP Trương Liêu",
	sp_zhangliao_prefix: "SP",
	mubing: "Mộ Binh",
	mubing_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể lật ba thẻ trên cùng của chồng bài. Bạn có thể bỏ bất kỳ số lượng thẻ trên tay nào, và có thể nhận bất kỳ số lượng thẻ nào có tổng điểm số không lớn hơn tổng điểm số của các thẻ bạn đã bỏ.",
	ziqu: "Tư Thủ",
	ziqu_info: "Mỗi nhân vật giới hạn một lần, sau khi bạn gây sát thương cho nhân vật khác có bài, bạn có thể ngăn chặn sát thương này. Sau đó người đó đưa cho bạn thẻ có điểm số lớn nhất của họ.",
	diaoling: "Điều Lệnh",
	diaoling_info: "Kỹ năng thức tỉnh, giai đoạn chuẩn bị, nếu bạn đã nhờ [Mộ Binh] mà nhận được sáu thẻ hoặc nhiều hơn gồm [Sát] hoặc thẻ Vũ Khí hoặc thẻ Cẩm Nang gây sát thương, bạn hồi 1 điểm thể lực hoặc rút hai thẻ, sau đó sửa đổi [Mộ Binh].",
	mubing_rewrite: "Mộ Binh·Cải",
	mubing_rewrite_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể lật bốn thẻ trên cùng của chồng bài. Bạn có thể bỏ bất kỳ số lượng thẻ trên tay nào, và có thể nhận bất kỳ số lượng thẻ nào có tổng điểm số không lớn hơn tổng điểm số của các thẻ bạn đã bỏ. Sau đó bạn có thể đem những thẻ nhận được bằng cách này đưa cho các nhân vật khác theo cách bất kỳ.",
	caobuxing: "Tào Bất Hưng",
	moying: "Mặc Ảnh",
	moying_info: "Mỗi lượt giới hạn một lần, khi bạn ở ngoài lượt không phải do sử dụng mà mất đi một thẻ Cẩm Nang hoặc thẻ Trang Bị duy nhất, bạn có thể chọn một hoa sắc và một điểm số có giá trị tuyệt đối chênh lệch với thẻ này không quá 2, sau đó nhận tất cả các thẻ trong chồng bài có cùng hoa sắc và điểm số với thẻ đó.",
	juanhui: "Quyên Hội",
	juanhui2: "Quyên Hội",
	juanhui2_backup: "Quyên Hội",
	juanhui_info: 'Giai đoạn kết thúc, bạn có thể chọn một nhân vật khác. Ghi nhớ các thẻ Cơ Bản và thẻ Cẩm Nang bình thường mà nhân vật đó sử dụng trong giai đoạn ra bài lượt tiếp theo (mỗi tên thẻ chỉ ghi nhớ một lần), trong giai đoạn ra bài lượt tiếp theo của bạn, có thể dùng một thẻ trên tay như bất kỳ thẻ nào trong số những thẻ đã ghi nhớ (mỗi thẻ giới hạn sử dụng một lần, và [Sát] không tính số lần). Khi các thẻ "Quyên Hội" đã dùng hết, bạn hồi 1 điểm thể lực và rút bài trên tay đến ba lá.',
	re_maliang: "Tân Sát Mã Lương",
	re_maliang_prefix: "Tân Sát",
	rexiemu: "Hiệp Mục",
	rexiemu_info: "Giai đoạn kết thúc, nếu trên sân không có dấu ấn “Hiệp Mục”, bạn có thể chọn một nhân vật nhận dấu ấn “Hiệp Mục” cho đến khi lượt tiếp theo của bạn bắt đầu. Khi bạn hoặc nhân vật đó sử dụng hoặc đánh ra thẻ ngoài lượt của mỗi người, bạn và người đó mỗi người rút một thẻ (mỗi lượt giới hạn một lần).",
	heli: "Hạ Lệ",
	heli_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể chọn một nhân vật khác có số bài trên tay ít hơn bạn. Nhân vật đó trưng ra tất cả thẻ trên tay, sau đó cứ thiếu một loại thẻ nào, thì nhận ngẫu nhiên một thẻ loại đó từ chồng bài.",
	zhujun: "Chu Tuấn",
	gongjian: "Công Kiên",
	gongjian_info: "Mỗi lượt giới hạn một lần, khi có nhân vật sử dụng [Sát] chỉ định mục tiêu đầu tiên, nếu giao tập A của các mục tiêu của [Sát] này và các mục tiêu của thẻ [Sát] đã được sử dụng trước đó trong ván đấu không trống, bạn có thể lần lượt bỏ tối đa hai thẻ của tất cả nhân vật trong A, sau đó nhận tất cả thẻ [Sát] đã bỏ bằng cách này.",
	kuimang: "Quỵ Mãng",
	kuimang_info: "Kỹ năng khóa, sau khi một nhân vật chết, nếu bạn từng gây sát thương cho người đó, bạn rút hai thẻ.",
	liuhong: "Lưu Hoằng",
	yujue: "Dục Tước",
	yujue_info: `Giai đoạn ra bài giới hạn một lần, bạn có thể phế bỏ một ô trang bị, sau đó khiến một nhân vật khác có bài trên tay đưa cho bạn một thẻ. Người đó nhận được ${get.poptip("zhihu")} cho đến khi lượt tiếp theo của bạn bắt đầu.`,
	zhihu: "Chấp Hốt",
	zhihu_info: "Kỹ năng khóa, mỗi lượt giới hạn hai lần, sau khi bạn gây sát thương cho nhân vật khác, bạn rút hai thẻ.",
	tuxing: "Đồ Hưng",
	tuxing2: "Đồ Hưng",
	tuxing_info: "Kỹ năng khóa, khi bạn phế bỏ một ô trang bị, bạn tăng 1 điểm giới hạn thể lực và hồi 1 điểm thể lực. Sau đó nếu tất cả ô trang bị của bạn đều đã bị phế bỏ, bạn giảm 4 điểm giới hạn thể lực, và sát thương gây ra trong ván đấu này +1.",
	re_hejin: "Tân Sát Hà Tiến",
	re_hejin_prefix: "Tân Sát",
	xin_baosanniang: "Tân Sát Bào Tam Nương",
	xin_baosanniang_prefix: "Tân Sát",
	decadexushen: "Hứa Thân",
	decadexushen2: "Hứa Thân",
	decadexushen_info: `Kỹ năng giới hạn, khi bạn rơi vào trạng thái hấp hối, bạn có thể hồi 1 điểm thể lực và nhận kỹ năng ${get.poptip("decadezhennan")}, sau đó nếu bạn thoát khỏi trạng thái hấp hối và ${get.poptip({
		id: "character_dc_guansuo",
		name: "Quan Sách",
		type: "character",
		dialog: "characterDialog",
	})} không có mặt trên sân, bạn có thể khiến một nhân vật khác chọn có dùng ${get.poptip("character_dc_guansuo")} thay thế võ tướng của họ hay không và khiến người đó rút ba thẻ.`,
	decadezhennan: "Trấn Nam",
	decadezhennan_info: "Khi có nhân vật sử dụng thẻ Cẩm Nang bình thường chỉ định mục tiêu, nếu số mục tiêu của thẻ này lớn hơn 1, bạn có thể gây 1 điểm sát thương cho một nhân vật khác.",
	ol_dingyuan: "Đinh Nguyên",
	cixiao: "Từ Hiếu",
	cixiao_info: "Giai đoạn chuẩn bị, nếu trên sân không có dấu ấn “Nghĩa Tử”, bạn có thể khiến một nhân vật khác nhận một dấu ấn “Nghĩa Tử”; nếu trên sân đã có dấu ấn “Nghĩa Tử”, bạn có thể bỏ một thẻ để di chuyển dấu ấn “Nghĩa Tử”. Nhân vật có dấu ấn “Nghĩa Tử” nhận kỹ năng “Phản Thệ”.",
	panshi: "Phản Thệ",
	panshi_info: "Kỹ năng khóa, giai đoạn chuẩn bị, bạn đưa cho nhân vật có kỹ năng “Từ Hiếu” một thẻ trên tay; khi bạn gây sát thương cho nhân vật khác trong giai đoạn ra bài do sử dụng [Sát], nếu người đó có kỹ năng “Từ Hiếu”, sát thương này +1, và bạn kết thúc giai đoạn ra bài.",
	xianshuai: "Tiên Suất",
	xianshuai_info: "Kỹ năng khóa, sau khi có nhân vật gây sát thương, nếu sát thương này là sát thương đầu tiên gây ra trong vòng này: bạn rút một thẻ; nếu nguồn sát thương là bạn, bạn gây thêm 1 điểm sát thương cho nhân vật chịu sát thương.",
	wangrong: "Vương Vinh",
	minsi: "Mẫn Tư",
	minsi2: "Mẫn Tư",
	minsi_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ bất kỳ số lượng thẻ nào có tổng điểm số là 13, sau đó rút gấp đôi số lượng thẻ đó. Trong những thẻ nhận được bằng cách này, thẻ đen không giới hạn khoảng cách trong lượt này, thẻ đỏ không tính vào giới hạn bài trên tay trong lượt này.",
	jijing: "Cát Cảnh",
	jijing_info: "Sau khi bạn chịu sát thương, bạn có thể tiến hành một lần phán xét, sau đó nếu bạn bỏ bất kỳ số lượng thẻ nào có tổng điểm số bằng với điểm số kết quả phán xét, bạn hồi 1 điểm thể lực.",
	zhuide: "Truy Đức",
	zhuide_info: "Khi bạn chết, bạn có thể khiến một nhân vật khác nhận bốn thẻ Cơ Bản có tên gọi khác nhau từ chồng bài.",
	decadewuniang: "Võ Nương",
	decadewuniang_info: "Khi bạn sử dụng hoặc đánh ra [Sát], bạn có thể nhận một thẻ của nhân vật khác. Nếu làm vậy, người đó rút một thẻ. (Nếu bạn đã phát động Hứa Thân, Quan Sách cũng rút một thẻ)",
	dongxie: "Đổng Hiệp",
	juntun: "Quân Truân",
	juntun_info: "Kỹ năng khóa, giai đoạn chuẩn bị, nếu X lớn hơn 1, bạn giảm 1 điểm giới hạn thể lực và rút X thẻ (X là giới hạn thể lực của bạn).",
	jiaojie: "Xảo Quyệt",
	jiaojie_info: "Kỹ năng khóa, thẻ đỏ của bạn không tính vào giới hạn bài trên tay. Bạn sử dụng thẻ đen không giới hạn khoảng cách và số lần.",
	dcjiaoxia: "Xảo Quyệt",
	dcjiaoxia_info: "① Khi giai đoạn ra bài bắt đầu, bạn có thể khiến tất cả thẻ trên tay của mình trong giai đoạn này đều được coi là [Sát]. Nếu làm vậy, sau khi bạn sử dụng [Sát] chuyển hóa bằng cách này gây sát thương, bạn có thể sử dụng thẻ gốc tương ứng của thẻ này. ② Giai đoạn ra bài, bạn sử dụng [Sát] lên nhân vật mà bạn chưa từng sử dụng [Sát] trong giai đoạn này không bị giới hạn khoảng cách và số lần.",
	dchumei: "Hồ Mị",
	dchumei_info: "Giai đoạn ra bài mỗi hạng mục giới hạn một lần, bạn có thể chọn một nhân vật có thể lực không lớn hơn X, khiến người đó: ① Rút một thẻ. ② Đưa cho bạn một thẻ. ③ Hồi 1 điểm thể lực. (X là số sát thương bạn gây ra trong giai đoạn này)",
	buchen: "Bất Thần",
	buchen_info: "Kỹ năng ẩn nấp, khi bạn xuất hiện trong lượt của nhân vật khác, có thể nhận một thẻ của nhân vật hiện tại.",
	smyyingshi: "Ưng Thị",
	smyyingshi_info: "Kỹ năng khóa, giai đoạn ra bài, bạn có thể xem X thẻ trên cùng của chồng bài (X là giới hạn thể lực của bạn).",
	xiongzhi: "Hùng Chí",
	xiongzhi_info: "Kỹ năng giới hạn, giai đoạn ra bài, bạn có thể xem thẻ trên cùng của chồng bài và sử dụng nó (sử dụng [Sát] có giới hạn số lần), và bạn lặp lại quy trình này cho đến khi không thể sử dụng thẻ đã xem.",
	quanbian: "Quyền Biến",
	quanbian2: "Quyền Biến",
	quanbian_info: "Khi bạn sử dụng/đánh ra thẻ trên tay trong giai đoạn ra bài, nếu thẻ này có hoa sắc và bạn chưa sử dụng/đánh ra thẻ khác có cùng hoa sắc trong lượt này, bạn có thể chọn một: ① Rút một thẻ. ② Đặt một trong X thẻ trên cùng của chồng bài xuống đáy chồng bài (X là giới hạn thể lực của bạn). Nếu bạn phát động kỹ năng này, bạn không thể sử dụng thêm thẻ trên tay có cùng hoa sắc trong lượt này.",
	re_hansui: "Tân Sát Hàn Toại",
	re_hansui_prefix: "Tân Sát",
	re_quyi: "Tân Sát Khúc Nghĩa",
	re_quyi_prefix: "Tân Sát",
	refuqi: "Phục Kỵ",
	refuqi_info: "Kỹ năng khóa, khi bạn sử dụng thẻ, bạn khiến tất cả nhân vật khác có khoảng cách bằng 1 không thể sử dụng hoặc đánh ra thẻ để hưởng ứng thẻ này.",
	hanfu: "Hàn Phức",
	hfjieying: "Tiết Ứng",
	hfjieying2: "Tiết Ứng",
	hfjieying3: "Tiết Ứng",
	hfjieying_info: "Giai đoạn kết thúc, bạn có thể chọn một nhân vật khác, nhân vật đó trong lượt tiếp theo sử dụng [Sát] có số mục tiêu là 1 hoặc thẻ Cẩm Nang bình thường sẽ không bị giới hạn khoảng cách và có thể chỉ định thêm một mục tiêu, và sau khi gây sát thương, người đó không thể sử dụng thêm thẻ cho đến khi kết thúc lượt.",
	weipo: "Nguy Bách",
	weipo_info: "Kỹ năng khóa, sau khi nhân vật khác sử dụng [Sát] hoặc thẻ Cẩm Nang bình thường chỉ định bạn làm mục tiêu, nếu số bài trên tay bạn ít hơn X, bạn rút bài cho đến khi bằng X lá, và ghi nhớ số lượng bài Y sau khi kết toán rút bài. Sau khi thẻ này kết thúc kết toán, nếu số bài trên tay bạn ít hơn Y, bạn đưa một thẻ trên tay cho người sử dụng thẻ này, và kỹ năng này mất hiệu lực cho đến khi lượt tiếp theo của bạn bắt đầu. (X là giới hạn thể lực của bạn và tối đa là 5)",
	zhaozhong: "Triệu Trung",
	yangzhong: "Ương Chúng",
	yangzhong_info: "Sau khi bạn gây ra hoặc chịu sát thương, nếu nhân vật chịu sát thương và nguồn sát thương đều còn sống, nguồn sát thương có thể bỏ hai thẻ, sau đó khiến nhân vật chịu sát thương mất 1 điểm thể lực.",
	huangkong: "Hoảng Khủng",
	huangkong_info: "Kỹ năng khóa, khi bạn trở thành mục tiêu của [Sát] hoặc thẻ Cẩm Nang bình thường ở ngoài lượt, nếu bạn không có bài trên tay, bạn rút hai thẻ.",
	re_taoqian: "Đào Khiêm",
	reyixiang: "Nghĩa Tương",
	reyixiang_info: "Kỹ năng khóa, thẻ đầu tiên nhân vật khác sử dụng trong giai đoạn ra bài gây sát thương lên bạn -1; thẻ thứ hai người đó sử dụng nếu là màu đen thì vô hiệu với bạn.",
	caosong: "Tào Tung",
	cslilu: "Lễ Lộ",
	cslilu_info: "Giai đoạn rút bài, bạn có thể từ bỏ rút bài, thay bằng rút bài trên tay đến X lá (X là giá trị nhỏ nhất giữa giới hạn thể lực của bạn và 5), sau đó đưa ít nhất một thẻ trên tay cho một nhân vật khác. Nếu số thẻ bạn đưa bằng cách này nhiều hơn số thẻ bạn đã đưa lần trước bằng cách này, bạn tăng 1 điểm giới hạn thể lực và hồi 1 điểm thể lực.",
	csyizheng: "Dực Chính",
	csyizheng2: "Dực Chính",
	csyizheng_info: "Khi giai đoạn kết thúc bắt đầu, bạn có thể chọn một nhân vật khác. Trước khi lượt tiếp theo của bạn bắt đầu, khi nhân vật đó gây sát thương hoặc hồi phục thể lực, nếu giới hạn thể lực của người đó nhỏ hơn bạn, bạn giảm 1 điểm giới hạn thể lực, và khiến giá trị sát thương/hồi phục này +1.",
	reyirang: "Ấp Nhượng",
	reyirang_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể đưa tất cả thẻ không phải Cơ Bản cho một nhân vật khác. Nếu giới hạn thể lực của người đó lớn hơn bạn, bạn điều chỉnh giới hạn thể lực của mình bằng với người đó và hồi X điểm thể lực (X là số thẻ bạn đưa cho người đó bằng cách này).",
	liangxing: "Lương Hưng",
	lulve: "Lỗ Lược",
	lulve_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể chọn một nhân vật có bài trên tay và số bài ít hơn bạn. Người đó chọn một: ① Đưa tất cả bài trên tay cho bạn, sau đó bạn lật mặt thẻ võ tướng. ② Lật mặt thẻ võ tướng, sau đó người đó được coi là sử dụng một thẻ [Sát] lên bạn.",
	lxzhuixi: "Truy Kích",
	lxzhuixi_info: "Kỹ năng khóa, khi bạn gây sát thương hoặc chịu sát thương, nếu trạng thái lật mặt của nhân vật chịu sát thương và trạng thái lật mặt của nguồn sát thương khác nhau, thì sát thương này +1.",
	zhangmiao: "Trương Mạo",
	mouni: "Mưu Nghịch",
	mouni_info: "Giai đoạn chuẩn bị, bạn có thể lần lượt sử dụng tất cả thẻ [Sát] trên tay lên một nhân vật khác (nếu người đó rơi vào trạng thái hấp hối, quy trình này chấm dứt). Sau đó nếu trong những thẻ [Sát] này có thẻ không gây được sát thương, bạn bỏ qua giai đoạn ra bài và giai đoạn bỏ bài của lượt này.",
	zongfan: "Túng Phản",
	zongfan_info: "Kỹ năng thức tỉnh. Giai đoạn kết thúc, nếu trong lượt này bạn đã sử dụng [Sát] nhờ [Mưu Nghịch] và không bỏ qua giai đoạn ra bài, bạn đưa số thẻ bất kỳ cho một nhân vật khác, sau đó tăng X điểm giới hạn thể lực và hồi X điểm thể lực (X là số thẻ bạn đưa bằng cách này và tối đa là 5). Cuối cùng mất [Mưu Nghịch] và nhận [Chiến Cô].",
	zhangu: "Chiến Cô",
	zhangu_info: "Kỹ năng khóa, giai đoạn chuẩn bị, nếu giới hạn thể lực của bạn lớn hơn 1 và không có bài trên tay/vùng trang bị không có thẻ, bạn giảm 1 điểm giới hạn thể lực, sau đó nhận ba thẻ loại khác nhau từ chồng bài.",
	re_niujin: "Tân Sát Ngưu Kim",
	re_niujin_prefix: "Tân Sát",
	recuorui: "Thôi Nhuệ",
	recuorui_info: "Kỹ năng giới hạn, giai đoạn ra bài, bạn có thể lần lượt nhận tối đa một thẻ trên tay của X nhân vật (X là thể lực của bạn).",
	reliewei: "Liệt Vi",
	reliewei_info: "Mỗi lượt giới hạn Y lần, khi có nhân vật rơi vào trạng thái hấp hối, bạn có thể rút một thẻ (Y là thể lực của bạn, nếu nhân vật lượt hiện tại là bạn, Y là vô hạn).",
	duanwei: "Đoạn煨",
	langmie: "Lang Diệt",
	langmie_damage: "Lang Diệt",
	langmie_info: "Khi giai đoạn ra bài của nhân vật khác kết thúc, nếu trong những thẻ đã sử dụng trong giai đoạn này có các thẻ cùng loại, bạn có thể rút một thẻ; khi giai đoạn kết thúc của nhân vật khác bắt đầu, nếu sát thương gây ra trong lượt này lớn hơn 1, bạn có thể bỏ một thẻ và gây 1 điểm sát thương cho người đó.",
	zhangheng: "Trương Hoành",
	dangzai: "Đương Tai",
	dangzai_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể di chuyển bất kỳ số thẻ nào trong vùng phán xét của một nhân vật khác sang vùng phán xét của bạn.",
	liangjue: "Lương Tuyệt",
	liangjue_info: "Kỹ năng khóa, sau khi một thẻ đen đi vào hoặc rời khỏi vùng phán xét hoặc vùng trang bị của bạn, bạn rút hai thẻ, sau đó nếu thể lực của bạn lớn hơn 1, bạn mất 1 điểm thể lực.",
	tangji: "Đường Cơ",
	kangge: "Kháng Ca",
	kangge_info: "Khi lượt đầu tiên của bạn bắt đầu, chọn một nhân vật khác, mỗi khi người đó nhận bài ở ngoài lượt, bạn rút số thẻ tương đương (mỗi lượt tối đa rút ba thẻ); khi người đó rơi vào trạng thái hấp hối, bạn có thể khiến người đó hồi phục thể lực đến 1 điểm (mỗi vòng giới hạn một lần). Khi nhân vật đó chết, bạn bỏ tất cả bài và mất 1 điểm thể lực.",
	jielie: "Tiết Liệt",
	jielie_info: "Khi bạn chịu sát thương từ một nhân vật không phải chính mình và không phải nhân vật “Kháng Ca”, bạn có thể ngăn chặn sát thương này và chọn một hoa sắc, sau đó bạn mất X điểm thể lực, khiến nhân vật “Kháng Ca” nhận ngẫu nhiên X thẻ có hoa sắc này từ chồng bài bỏ (X là giá trị sát thương).",
	re_dongcheng: "Đổng Thừa",
	xuezhao: "Huyết Chiếu",
	xuezhao_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ một thẻ trên tay và chọn tối đa X nhân vật khác (X là giới hạn thể lực của bạn). Những nhân vật này lần lượt chọn có đưa cho bạn một thẻ hay không, nếu chọn Có, nhân vật đó rút một thẻ và bạn trong lượt này có thể sử dụng thêm một thẻ [Sát]; nếu chọn Không, nhân vật đó trong lượt này không thể hưởng ứng thẻ bạn sử dụng. Nếu không có nhân vật nào đưa thẻ cho bạn, bạn rút bài cho đến khi bằng giới hạn thể lực.",
	re_hucheer: "Hồ Xa Nhi",
	redaoji: "Đạo Kích",
	redaoji2: "Đạo Kích",
	redaoji_info: "Lần đầu tiên nhân vật khác sử dụng thẻ Vũ Khí, bạn có thể chọn một: ① Nhận lấy thẻ này. ② Khiến người đó không thể sử dụng hay đánh ra [Sát] trong lượt này.",
	fuzhong: "Phụ Trọng",
	fuzhong_info: "Kỹ năng khóa, sau khi bạn nhận bài ở ngoài lượt, bạn nhận một dấu ấn “Trọng”. Nếu X: lớn hơn 0, khi giai đoạn rút bài bắt đầu bạn tăng định mức rút bài +1; lớn hơn 1, khoảng cách của bạn đến nhân vật khác -2; lớn hơn 2, giới hạn bài trên tay +3; lớn hơn 3, khi giai đoạn kết thúc bắt đầu, bạn gây 1 điểm sát thương cho một nhân vật khác, sau đó loại bỏ 4 dấu ấn “Trọng” (X là số lượng “Trọng”).",
	qiuliju: "Khâu Lực Cư",
	koulve: "Khấu Lược",
	koulve_info: "Sau khi bạn gây sát thương cho nhân vật khác trong giai đoạn ra bài, bạn có thể trưng ra X thẻ trên tay của người đó (X là số thể lực đã mất của người đó). Nếu trong những thẻ này: có thẻ Cơ Bản hoặc thẻ Cẩm Nang mang nhãn sát thương, bạn nhận lấy nó; có thẻ đỏ, bạn mất 1 điểm thể lực (nếu đã bị thương thì thay bằng giảm 1 điểm giới hạn thể lực), sau đó rút hai thẻ.",
	qljsuiren: "Tùy Nhận",
	qljsuiren_info: "Khi bạn chết, bạn có thể đưa tất cả thẻ Cơ Bản hoặc thẻ Cẩm Nang mang nhãn sát thương trên tay cho một nhân vật khác.",
	re_zoushi: "Trâu Thị",
	rehuoshui: "Họa Thủy",
	rehuoshui_info: "Giai đoạn chuẩn bị, bạn có thể chọn tối đa X nhân vật (X là số thể lực đã mất của bạn và ít nhất là 1). Bạn khiến kỹ năng không phải kỹ năng khóa của nhân vật đầu tiên trong số những nhân vật này mất hiệu lực cho đến khi kết thúc lượt; nhân vật thứ hai đưa cho bạn một thẻ trên tay; nhân vật thứ ba trở đi bỏ tất cả thẻ trong vùng trang bị.",
	reqingcheng: "Khuynh Thành",
	reqingcheng_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể trao đổi bài trên tay với một nhân vật nam có số bài trên tay không lớn hơn bạn.",
	caoanmin: "Tào An Dân",
	xianwei: "Hiểm Vệ",
	xianwei_info: "Kỹ năng khóa, giai đoạn chuẩn bị, bạn phế bỏ một ô trang bị và rút X thẻ (X là số ô trang bị chưa phế bỏ của bạn), sau đó khiến một nhân vật khác tự sử dụng một thẻ trang bị cùng loại phụ với ô trang bị này từ chồng bài (nếu không có thẻ khả dụng thì thay bằng rút một thẻ). Khi bạn phế bỏ tất cả ô trang bị, bạn tăng 2 điểm giới hạn thể lực, sau đó bạn và tất cả nhân vật khác được coi là nằm trong phạm vi tấn công của nhau.",
	dufuren: "Đỗ Phu Nhân",
	yise: "Dị Sắc",
	yise_info: "Sau khi nhân vật khác nhận bài của bạn, nếu trong những thẻ đó: có thẻ đỏ, bạn có thể khiến người đó hồi 1 điểm thể lực; có thẻ đen, lần tới người đó chịu sát thương do thực thi hiệu ứng của [Sát], sát thương này +1.",
	shunshi: "Thuận Thế",
	shunshi_info: "Khi giai đoạn chuẩn bị bắt đầu, hoặc sau khi bạn chịu sát thương ở ngoài lượt, bạn có thể đưa một thẻ cho một nhân vật khác không phải nguồn sát thương và nhận hiệu ứng sau cho đến khi lượt của bạn kết thúc: định mức rút bài của giai đoạn rút bài +1, giới hạn số lần sử dụng [Sát] +1, giới hạn bài trên tay +1.",
	rexingluan: "Hưng Loạn",
	rexingluan_info: "Giai đoạn ra bài giới hạn một lần, khi thẻ chỉ định duy nhất một mục tiêu bạn sử dụng kết thúc kết toán, bạn có thể nhận một thẻ trên sân có cùng điểm số với thẻ này, hoặc nhận ngẫu nhiên một thẻ trong chồng bài có cùng điểm số với thẻ này.",
	xinxingluan: "Hưng Loạn",
	xinxingluan_info: "Mỗi lượt giới hạn một lần. Khi thẻ bạn sử dụng trong giai đoạn ra bài kết thúc kết toán, bạn có thể chọn một: ① Xem hai thẻ có điểm số là 6 trong chồng bài và nhận một thẻ trong đó (nếu không có thì thay bằng rút sáu thẻ); ② Khiến một nhân vật khác bỏ một thẻ có điểm số là 6 hoặc đưa cho bạn một thẻ; ③ Nhận một thẻ trên sân có điểm số là 6.",
	re_nanhualaoxian: "Nam Hoa Lão Tiên",
	gongxiu: "Cộng Tu",
	gongxiu_info: "Giai đoạn kết thúc, nếu trong lượt này bạn đã phát động [Kinh Hợp], bạn chọn một: ① Khiến tất cả nhân vật đã trở thành mục tiêu của [Kinh Hợp] trong lượt này mỗi người rút một thẻ; ② Khiến tất cả nhân vật chưa trở thành mục tiêu của [Kinh Hợp] trong lượt này mỗi người bỏ một thẻ trên tay.",
	jinghe: "Kinh Hợp",
	jinghe_info: `Giai đoạn ra bài giới hạn một lần, bạn có thể trưng ra tối đa bốn thẻ có tên gọi khác nhau và chọn số nhân vật tương đương. Hệ thống từ "Thiên Thư viết đầy kỹ năng" (${["releiji", "rebiyue", "new_retuxi", "remingce", "xinzhiyan", "nhyinbing", "nhhuoqi", "nhguizhu", "nhxianshou", "nhlundao", "nhguanyue", "nhyanzheng"].map(skill =>get.poptip(skill)).join("、")} ) chọn ngẫu nhiên số lượng kỹ năng tương đương, sau đó những nhân vật này lần lượt chọn nhận lấy một trong số đó cho đến khi lượt tiếp theo của bạn bắt đầu.`,
	nhyinbing: "Âm Binh",
	nhyinbing_info: "Kỹ năng khóa, [Sát] bạn sử dụng gây sát thương thay bằng mất thể lực. Sau khi nhân vật khác mất thể lực, bạn rút một thẻ.",
	nhhuoqi: "Hoạt Khí",
	nhhuoqi_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ một thẻ, sau đó khiến một nhân vật có thể lực ít nhất hồi 1 điểm thể lực và rút một thẻ.",
	nhguizhu: "Quỷ Trợ",
	nhguizhu_info: "Khi một nhân vật rơi vào trạng thái hấp hối, bạn có thể rút hai thẻ (mỗi lượt giới hạn một lần).",
	nhxianshou: "Tiên Thụ",
	nhxianshou_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể chọn một nhân vật khiến người đó rút một thẻ. Nếu người đó chưa bị thương, rút thêm một lá.",
	nhlundao: "Luận Đạo",
	nhlundao_info: "Sau khi bạn chịu sát thương, nếu nguồn sát thương có nhiều bài trên tay hơn bạn, bạn có thể bỏ một thẻ của người đó; nếu nguồn sát thương có ít bài trên tay hơn bạn, bạn rút một thẻ.",
	nhguanyue: "Quan Nguyệt",
	nhguanyue_info: "Giai đoạn kết thúc, bạn có thể xem hai thẻ trên cùng của chồng bài, sau đó nhận một lá, lá còn lại đặt lại lên đỉnh chồng bài.",
	nhyanzheng: "Ngôn Chính",
	nhyanzheng_info: "Giai đoạn chuẩn bị, nếu số bài trên tay bạn nhiều hơn 1, bạn có thể giữ lại một thẻ và bỏ các thẻ còn lại, sau đó chọn tối đa số nhân vật bằng số thẻ đã bỏ, gây 1 điểm sát thương cho mỗi nhân vật này.",
	sp_mifangfushiren: "Mi Phương Phó Sĩ Nhân",
	mffengshi: "Phong Thế",
	mffengshi_info: "Khi bạn sử dụng thẻ chỉ định mục tiêu duy nhất, hoặc trở thành mục tiêu duy nhất của thẻ nhân vật khác sử dụng, nếu số bài trên tay người sử dụng thẻ nhiều hơn số bài trên tay mục tiêu của thẻ, người sử dụng thẻ có thể khiến bạn bỏ mỗi bên mình và đối phương một thẻ, và khiến giá trị sát thương của thẻ này +1.",
	dcmffengshi: "Phong Thế",
	dcmffengshi_info: "Khi bạn sử dụng thẻ chỉ định mục tiêu duy nhất, hoặc trở thành mục tiêu duy nhất của thẻ nhân vật khác sử dụng, nếu số bài trên tay người sử dụng thẻ nhiều hơn số bài trên tay mục tiêu của thẻ, bạn có thể bỏ mỗi bên mình và đối phương một thẻ, và khiến giá trị sát thương của thẻ này +1.",
	fengshi: "Phong Thế",
	fengshi_info: "Khi bạn sử dụng thẻ chỉ định mục tiêu đầu tiên, bạn có thể bỏ mỗi bên mình và một trong những mục tiêu có số bài trên tay ít hơn bạn một thẻ, và khiến thẻ này gây cho mục tiêu đó sát thương +1; khi bạn trở thành mục tiêu của thẻ nhân vật khác sử dụng, nếu số bài trên tay bạn ít hơn người đó, bạn có thể bỏ mỗi bên mình và người đó một thẻ, và khiến thẻ này gây cho bạn sát thương +1.",
	tongyuan: "Đồng Uyên",
	chaofeng: "Triều Phượng",
	chaofeng_info: "Giai đoạn ra bài giới hạn một lần. Khi bạn gây sát thương, bạn có thể bỏ một thẻ trên tay, sau đó rút một thẻ. Nếu kênh sát thương này là thẻ và thẻ bạn bỏ: có cùng màu sắc với thẻ này, thay bằng việc bạn rút hai thẻ; có cùng loại với thẻ này, sát thương này +1.",
	chuanshu: "Truyền Thuật",
	chuanshu_info: "Kỹ năng giới hạn. Giai đoạn chuẩn bị, nếu bạn đã bị thương; hoặc khi bạn chết, bạn có thể khiến một nhân vật khác nhận [Triều Phượng]. Sau đó bạn nhận [Long Đảm], [Tòng Gián] và [Xuyên Vân].",
	chuanyun: "Xuyên Vân",
	chuanyun_info: "Khi bạn sử dụng [Sát] chỉ định mục tiêu, bạn có thể khiến nhân vật mục tiêu ngẫu nhiên bỏ một thẻ trong vùng trang bị.",
	zhangning: "Trương Ninh",
	tianze: "Thiên Tắc",
	tianze_info: "① Sau khi thẻ đen trên tay đầu tiên nhân vật khác sử dụng trong giai đoạn ra bài kết thúc kết toán, bạn có thể bỏ một thẻ đen, và gây 1 điểm sát thương cho người đó. ② Sau khi phán xét của nhân vật khác có hiệu lực, nếu kết quả là màu đen, bạn rút một thẻ.",
	difa: "Địa Pháp",
	difa_info: "Mỗi lượt giới hạn một lần. Sau khi bạn nhận được thẻ đỏ trong lượt, bạn có thể bỏ một trong số đó. Sau đó bạn chọn tên một thẻ Cẩm Nang, và nhận một thẻ có tên đó từ chồng bài/chồng bài bỏ.",
	xinping: "Tân Bình",
	fuyuan: "Phụ Viên",
	fuyuan_info: "Khi bạn sử dụng hoặc đánh ra thẻ ngoài lượt, nếu số bài trên tay của nhân vật lượt hiện tại: không ít hơn bạn, bạn có thể rút một thẻ; ít hơn bạn, bạn có thể khiến người đó rút một thẻ.",
	zhongjie: "Trung Tiết",
	zhongjie_info: "Khi bạn chết, bạn có thể khiến một nhân vật khác tăng 1 điểm giới hạn thể lực và hồi 1 điểm thể lực, sau đó rút một thẻ.",
	hanmeng: "Hàn Mãnh",
	jieliang: "Tiết Lương",
	jieliang_info: "Khi giai đoạn rút bài của nhân vật khác bắt đầu, bạn có thể bỏ một thẻ, khiến số lượng rút bài trong giai đoạn này và giới hạn bài trên tay lượt này của người đó -1. Sau đó khi người đó mất bài do bỏ bài trong giai đoạn bỏ bài lượt này, bạn có thể nhận lấy một thẻ trong số đó.",
	quanjiu: "Khuyên Tửu",
	quanjiu_info: "Kỹ năng khóa. ① Thẻ [Tửu] trong vùng bài trên tay bạn có tên gọi được coi là [Sát]. ② [Sát] không chuyển hóa có thực thể thẻ tương ứng là một lá [Tửu] bạn sử dụng không tính vào giới hạn số lần.",
	re_pangdegong: "Bàng Đức Công",
	heqia: "Hòa Hiệp",
	heqia_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể chọn một: ① Đưa số thẻ bất kỳ cho một nhân vật khác. ② Khiến một nhân vật khác có bài trên tay đưa cho bạn số thẻ bất kỳ. Sau đó nhân vật nhận được bài bằng cách này có thể dùng một thẻ trên tay như bất kỳ thẻ Cơ Bản nào, và sau khi người đó tuyên bố sử dụng thẻ này, có thể tăng số mục tiêu của thẻ này lên tối đa X mục tiêu (X là số thẻ đã di chuyển bằng cách này).",
	yinyi: "Ẩn Dật",
	yinyi_info: "Kỹ năng khóa. Mỗi lượt giới hạn một lần, khi bạn chịu sát thương không phải thuộc tính, nếu số bài trên tay và thể lực của bạn đều khác với nguồn sát thương, bạn ngăn chặn sát thương này.",
	haomeng: "Hác Manh",
	xiongmang: "Hùng Mãng",
	xiongmang_info: "Bạn có thể dùng số thẻ bất kỳ có hoa sắc khác nhau trên tay như là [Sát] có giới hạn mục tiêu là X (X là số thực thể thẻ tương ứng với lá [Sát] này). Sau khi lá [Sát] này kết thúc kết toán, nếu lá bài này đã gây được/chưa gây được sát thương, thì định mức số lần sử dụng [Sát] trong giai đoạn này của bạn +1/giảm 1 điểm giới hạn thể lực.",
	yanfuren: "Nghiêm Phu Nhân",
	channi: "Sàm Nghịch",
	channi_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể đưa số thẻ bất kỳ trên tay cho một nhân vật khác, sau đó người đó có thể dùng tối đa số thẻ tương đương như là [Quyết Đấu]. Khi người đó nhờ [Quyết Đấu] này: gây được sát thương, người đó rút X thẻ (X là số thực thể thẻ tương ứng của lá [Quyết Đấu] này); chịu sát thương, bạn bỏ tất cả thẻ trên tay.",
	nifu: "Nặc Phục",
	nifu_info: "Kỹ năng khóa. Khi lượt của một nhân vật kết thúc, bạn rút hoặc bỏ bài trên tay cho đến khi đủ bốn lá.",
	licaiwei: "Lý Thái Vi",
	yijiao: "Dị Giáo",
	yijiao_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể chọn một nhân vật khác chưa có dấu ấn “Dị” và tuyên bố một số nguyên X (X∈[1,4]), nhân vật đó nhận 10X dấu ấn “Dị”. Giai đoạn kết thúc của nhân vật có dấu ấn “Dị”, người đó loại bỏ dấu ấn “Dị”, và nếu tổng điểm số của các thẻ người đó sử dụng trong lượt này: 1. nhỏ hơn số lượng dấu ấn “Dị”, người đó ngẫu nhiên bỏ tối đa ba thẻ trên tay; 2. bằng số lượng dấu ấn “Dị”, bạn rút hai thẻ và nhân vật đó thực hiện một lượt bổ sung sau khi kết thúc lượt này; 3. lớn hơn số lượng dấu ấn “Dị”, bạn rút ba thẻ.",
	qibie: "Khấp Biệt",
	qibie_info: "Sau khi một nhân vật chết, nếu bạn có bài trên tay và những thẻ này đều có thể bị bỏ, bạn có thể bỏ tất cả thẻ trên tay, sau đó hồi 1 điểm thể lực và rút X+2 thẻ (X là số thẻ bạn đã bỏ).",
	dc_zhuling: "Chu Linh",
	dczhanyi: "Chiến Ý",
	dczhanyi_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể bỏ tất cả thẻ Cơ Bản/thẻ Cẩm Nang/thẻ Trang Bị, sau đó nhận hiệu ứng tương ứng của hai loại thẻ còn lại cho đến khi lượt tiếp theo của bạn bắt đầu: thẻ Cơ Bản, bạn sử dụng thẻ Cơ Bản không giới hạn khoảng cách, và cơ số giá trị sát thương và hồi phục +1; thẻ Cẩm Nang, khi bạn sử dụng thẻ Cẩm Nang thì rút một thẻ, và thẻ Cẩm Nang không tính vào giới hạn bài trên tay; thẻ Trang Bị, khi thẻ trang bị đi vào vùng trang bị của bạn, bạn có thể bỏ một thẻ của nhân vật khác.",
	yanrou: "Diêm Nhu",
	choutao: "Thù Thảo",
	choutao_info: "Khi bạn sử dụng [Sát], hoặc trở thành mục tiêu của [Sát], bạn có thể bỏ một thẻ của người sử dụng lá [Sát] này, khiến lá [Sát] này không thể bị hưởng ứng. Nếu bạn là người sử dụng lá [Sát] này, bạn khiến lá [Sát] này không tính vào giới hạn số lần.",
	xiangshu: "Tương Thú",
	xiangshu_info: "Kỹ năng giới hạn. Khi giai đoạn kết thúc bắt đầu, nếu bạn đã gây sát thương trong lượt này, bạn có thể chọn một nhân vật đã bị thương. Nhân vật đó hồi X điểm thể lực và rút X thẻ (X là tổng giá trị sát thương bạn gây ra trong lượt này và tối đa là 5).",
	qinyilu: "Tần Nghi Lộc",
	piaoping: "Phiêu Bình",
	piaoping_info: "Kỹ năng chuyển hóa, kỹ năng khóa. Khi bạn sử dụng một thẻ, Dương: bạn rút X thẻ. Âm: bạn bỏ X thẻ. (X là số lần bạn đã phát động [Phiêu Bình] trong giai đoạn này và tối đa bằng thể lực của bạn)",
	tuoxian: "Thác Hiến",
	tuoxian_info: "Mỗi ván game giới hạn một lần. Khi bạn bỏ thẻ do thực thi hiệu ứng của [Phiêu Bình], bạn có thể khiến một nhân vật khác nhận lấy những thẻ này, sau đó khiến nhân vật đó chọn một: ⒈ Bỏ số thẻ tương đương trong các vùng. ⒉ Khiến [Phiêu Bình] của bạn mất hiệu lực cho đến khi kết thúc lượt.",
	zhuili: "Trụy Lật",
	zhuili_info: "Kỹ năng khóa. Khi bạn trở thành mục tiêu của thẻ đen nhân vật khác sử dụng, nếu [Phiêu Bình] của bạn: đang ở trạng thái Dương, bạn chuyển [Phiêu Bình] sang trạng thái Âm; đang ở trạng thái Âm, bạn tăng số lần phát động [Thác Hiến] +1, sau đó nếu số lần phát động [Thác Hiến] lớn hơn 3, thì [Trụy Lật] mất hiệu lực trong lượt này.",
	fengfang: "Phùng Phương",
	dcditing: "Đế Thính",
	dcditing_info: "Khi giai đoạn ra bài của nhân vật khác bắt đầu, nếu bạn nằm trong phạm vi tấn công của nhân vật đó, bạn có thể xem X thẻ trên tay của người đó (X là thể lực của bạn) và chọn một trong số đó, đồng thời nhận hiệu ứng sau: ① Khi người đó sử dụng thẻ có thực thể thẻ tương ứng bao gồm thẻ này chỉ định bạn làm mục tiêu, bạn khiến thẻ này vô hiệu với mình. ② Khi người đó sử dụng thẻ có thực thể thẻ tương ứng bao gồm thẻ này kết thúc kết toán, nếu bạn không phải mục tiêu của thẻ này, bạn rút hai thẻ. ③ Khi giai đoạn ra bài của người đó kết thúc, nếu thẻ này vẫn nằm trong vùng bài trên tay của người đó, bạn nhận lấy thẻ này.",
	dcbihuo: "Tị Họa",
	dcbihuo_info: "① Sau khi bạn chịu sát thương do nhân vật khác gây ra, bạn có thể khiến một nhân vật có định mức rút bài của giai đoạn rút bài lượt tiếp theo +1. ② Sau khi bạn gây sát thương cho nhân vật khác, bạn có thể khiến một nhân vật có định mức rút bài của giai đoạn rút bài lượt tiếp theo -1.",
	bianxi: "Biện Hỷ",
	dunxi: "Độn Kích",
	dunxi_info: "① Khi bạn sử dụng thẻ có nhãn sát thương, bạn có thể khiến một nhân vật không phải mục tiêu của bạn nhận một dấu ấn “Độn”. ② Nhân vật có “Độn” khi sử dụng thẻ Cơ Bản hoặc thẻ Cẩm Nang, nếu số mục tiêu của thẻ này là 1 và lúc này không có nhân vật nào ở trạng thái hấp hối, bạn khiến người đó loại bỏ một dấu ấn “Độn”. Hệ thống ngẫu nhiên chọn một nhân vật, và đổi mục tiêu của thẻ này sang nhân vật đó. Nếu nhân vật đó giống với mục tiêu ban đầu, người đó mất 1 điểm thể lực. Nếu người đó đang trong giai đoạn ra bài, thì kết thúc giai đoạn này.",
	niufu: "Ngưu Phụ",
	dcxiaoxi: "Tiêu Tập",
	dcxiaoxi_info: "Kỹ năng khóa. Khi giai đoạn ra bài bắt đầu, bạn tuyên bố X và giảm X điểm giới hạn thể lực (X∈[1,2]). Sau đó bạn chọn một nhân vật khác trong phạm vi tấn công và chọn một: ⒈ Nhận X thẻ của nhân vật đó. ⒉ Được coi là sử dụng X thẻ [Sát] lên người đó.",
	xiongrao: "Hùng Nhiễu",
	xiongrao_info: "Kỹ năng giới hạn. Khi giai đoạn chuẩn bị bắt đầu, bạn có thể chọn tất cả nhân vật khác. Tất cả các kỹ năng bình thường không phải kỹ năng khóa, kỹ năng giới hạn, kỹ năng thức tỉnh của những nhân vật này trong lượt này đều mất hiệu lực. Sau đó bạn tăng giới hạn thể lực lên 7 điểm và rút X thẻ (X là số giới hạn thể lực bạn đã tăng thêm bằng cách này).",
	dc_huban: "Hồ Ban",
	dcchongyi: "Sùng Nghĩa",
	dcchongyi_info: "① Khi một nhân vật sử dụng [Sát], nếu thẻ này là thẻ đầu tiên người đó sử dụng trong giai đoạn ra bài hiện tại, bạn có thể khiến người đó rút hai thẻ, và giới hạn số lần sử dụng [Sát] lượt này của người đó +1. ② Khi giai đoạn ra bài của một nhân vật kết thúc, nếu thẻ cuối cùng người đó sử dụng trong giai đoạn này là [Sát], bạn có thể khiến giới hạn bài trên tay lượt này của người đó +1, sau đó bạn nhận lấy lá [Sát] này.",
	wangwei: "Vương Uy",
	dcruizhan: "Nhuệ Chiến",
	dcruizhan_info: "Khi giai đoạn chuẩn bị của nhân vật khác bắt đầu, nếu số bài trên tay của người đó không ít hơn thể lực của người đó, bạn có thể đấu điểm với người đó. Nếu bạn thắng hoặc thẻ đấu điểm có [Sát], bạn được coi là sử dụng một thẻ [Sát] lên người đó. Sau đó nếu lá [Sát] này gây được sát thương và cả hai điều kiện trên đều được thỏa mãn, bạn nhận một thẻ của người đó.",
	dcshilie: "Thị Liệt",
	dcshilie_info: "① Giai đoạn ra bài giới hạn một lần. Bạn có thể chọn một: ⒈ Hồi 1 điểm thể lực, đặt hai thẻ lên thẻ Võ tướng làm “Thị Liệt”. Nếu số thẻ “Thị Liệt” nhiều hơn số người còn sống, bạn đặt thẻ dư ra sớm nhất vào chồng bài bỏ; ⒉ Mất 1 điểm thể lực, nhận hai thẻ “Thị Liệt”. (Đầy máu không hồi máu, không có bài không di chuyển) ② Khi bạn chết, bạn có thể đưa tất cả thẻ “Thị Liệt” cho một nhân vật khác không phải nguồn sát thương.",
	dc_zhaoyǎn: "Triệu Nghiễm",
	dcfuning: "Phủ Ninh",
	dcfuning_info: "Khi bạn sử dụng thẻ, bạn có thể rút hai thẻ, sau đó bỏ X thẻ (X là số lần bạn đã phát động [Phủ Ninh] trong lượt này).",
	dcbingji: "Bỉnh Kỷ",
	dcbingji_info: "Giai đoạn ra bài mỗi loại hoa sắc giới hạn một lần. Nếu bạn có bài trên tay và hoa sắc của những thẻ này đều giống nhau, bạn có thể trưng ra bài trên tay, sau đó chọn một nhân vật khác, được coi là sử dụng một thẻ [Sát] hoặc [Đào] lên người đó (có giới hạn khoảng cách).",
	mushun: "Mục Thuận",
	dcjinjian: "Kính Kiên",
	dcjinjian_info: "① Sau khi bạn chịu sát thương do nhân vật khác gây ra hoặc gây ra sát thương, bạn nhận một dấu ấn “Kính”. Sau đó bạn có thể đấu điểm với nguồn sát thương, nếu bạn thắng, bạn hồi phục 1 điểm thể lực. ② Phạm vi tấn công của bạn +X (X là số lượng “Kính”).",
	dcshizhao: "Thất Chiếu",
	dcshizhao_info: "Kỹ năng khóa. Mỗi lượt giới hạn một lần, sau khi bạn mất bài trên tay ở ngoài lượt, nếu bạn không có bài trên tay, và bạn: có “Kính”, bạn loại bỏ một dấu ấn “Kính” và rút hai thẻ; không có “Kính”, sát thương tiếp theo bạn chịu trong lượt này +1.",
	liyixiejing: "Lý Dị Tạ Tinh",
	dcdouzhen: "Đấu Trận",
	dcdouzhen_info: "Kỹ năng khóa. ① Kỹ năng chuyển hóa. Trong lượt của bạn, Dương: khi bạn sử dụng [Quyết Đấu] không chuyển hóa và có thực thể thẻ tương ứng là một lá thẻ Cơ Bản màu đen, bạn nhận mỗi mục tiêu một thẻ và nhận 1 dấu ấn “☯”; Âm: khi bạn sử dụng hoặc đánh ra [Sát] không chuyển hóa và có thực thể thẻ tương ứng là một lá thẻ Cơ Bản màu đỏ, bạn nhận 1 dấu ấn “☯”. ② Nếu số lượng “☯” của bạn là: số chẵn, tất cả thẻ Cơ Bản màu đen của bạn đều được coi là [Quyết Đấu]; số lẻ, tất cả thẻ Cơ Bản màu đỏ của bạn đều được coi là [Sát] thường không giới hạn số lần.",
	dc_hujinding: "Tân Sát Hồ Kim Định",
	dc_hujinding_prefix: "Tân Sát",
	dcdeshi: "Đức Thích",
	dcdeshi_info: "Kỹ năng khóa. Khi bạn chịu sát thương của [Sát], nếu bạn đã bị thương, bạn ngăn chặn sát thương này và khiến hệ thống truy xuất một lá [Sát] từ chồng bài bỏ/chồng bài, bạn nhận lấy lá [Sát] này, sau đó giảm 1 điểm giới hạn thể lực.",
	dcwuyuan: "Võ Duyên",
	dcwuyuan_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể đưa một thẻ [Sát] cho một nhân vật khác, sau đó bạn hồi 1 điểm thể lực, bạn và người đó mỗi người rút một thẻ. Nếu lá [Sát] này là: [Sát] đỏ, người đó hồi 1 điểm thể lực; [Sát] thuộc tính, người đó thay bằng rút hai thẻ.",
	shiyi: "Thị Nghi",
	dccuichuan: "Sia Chuyên",
	dccuichuan_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể bỏ một thẻ trên tay và chọn một nhân vật, người đó ngẫu nhiên sử dụng một thẻ trang bị từ chồng bài tương ứng với ô trang bị còn trống và người đó có thể sử dụng, bạn rút X thẻ (X là số thẻ trong vùng trang bị của người đó). Sau đó nếu số thẻ trong vùng trang bị của người đó tăng đến bốn lá, bạn mất [Sia Chuyên], nhận [Tá Gián], và khiến người đó thực hiện một lượt bổ sung.",
	dczhengxu: "Chính Tự",
	dczhengxu_info: "Mỗi lượt mỗi hạng mục giới hạn một lần. ① Khi bạn chịu sát thương, nếu bạn đã mất bài trong lượt này, bạn có thể ngăn chặn sát thương này. ② Sau khi bạn mất bài, nếu bạn đã chịu sát thương trong lượt này, bạn có thể rút số thẻ tương đương.",
	dczuojian: "Tá Gián",
	dczuojian_info: "Khi giai đoạn ra bài kết thúc, nếu số thẻ bạn sử dụng trong giai đoạn này không nhỏ hơn thể lực, bạn có thể chọn một: 1. Khiến các nhân vật có số thẻ trang bị nhiều hơn bạn mỗi người rút một thẻ; 2. Bỏ mỗi nhân vật có số thẻ trang bị ít hơn bạn một thẻ trên tay.",
	sunlang: "Tôn Lang",
	dctingxian: "Đĩnh Hiểm",
	dctingxian_info: "Mỗi lượt giới hạn một lần. Khi bạn sử dụng [Sát] chỉ định mục tiêu cuối cùng, bạn có thể rút X thẻ, sau đó có thể khiến lá [Sát] này vô hiệu với tối đa X mục tiêu trong số đó (X là số thẻ trang bị của bạn +1).",
	dcbenshi: "Bôn Thỉ",
	dcbenshi_info: "Kỹ năng khóa. ① Phạm vi tấn công của bạn +1. ② Quy tắc được tạo ra bởi “Mục tiêu sử dụng” trong thông tin mặt thẻ của lá [Sát] do bạn sử dụng đổi thành “Tất cả nhân vật trong phạm vi tấn công”.",
	sunhuan: "Tôn Hoàn",
	dcniji: "Nghịch Kích",
	dcniji_info: "① Khi bạn trở thành mục tiêu của thẻ không phải trang bị, bạn có thể rút một thẻ, gọi là “Nghịch Kích”. ② Giai đoạn kết thúc của một nhân vật, bạn có thể sử dụng một thẻ “Nghịch Kích”, sau đó bỏ tất cả thẻ “Nghịch Kích”.",
	dcmoukui: "Mưu Khuỵu",
	dcmoukui_info: "Khi bạn sử dụng [Sát] chỉ định mục tiêu đầu tiên, bạn có thể chọn hạng mục bất kỳ: 1. Rút một thẻ; 2. Bỏ một thẻ của một nhân vật mục tiêu. Nếu bạn chọn cả hai, khi lá [Sát] này bị vô hiệu hoặc bị triệt tiêu, nhân vật đó bỏ một thẻ của bạn.",
	guānning: "Quan Ninh",
	dcxiuwen: "Tu Văn",
	dcxiuwen_info: "Khi bạn sử dụng thẻ, nếu bạn chưa ghi nhớ tên thẻ này, bạn có thể ghi nhớ nó và rút một thẻ.",
	oldlongsong: "Long Tụng",
	oldlongsong_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể đưa một thẻ trên tay cho một nhân vật khác. Sau đó người đó phải chọn tất cả các kỹ năng có thời điểm phát động nằm trong thời gian rảnh của giai đoạn ra bài và bạn có thể phát động tối đa một lần trong giai đoạn này, các kỹ năng này của người đó mất hiệu lực trong giai đoạn này, bạn nhận được các kỹ năng đó.",
	dclongsong: "Long Tụng",
	dclongsong_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể đưa một thẻ đỏ cho một nhân vật khác. Sau đó người đó phải chọn tất cả các kỹ năng có thời điểm phát động bao gồm “Giai đoạn ra bài”, các kỹ năng này của người đó mất hiệu lực trong giai đoạn này, bạn nhận được các kỹ năng đó và tối đa có thể phát động một lần.",
	longsong: "Long Tụng",
	longsong_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể đưa cho hoặc nhận từ một nhân vật khác một thẻ đỏ, sau đó bạn nhận được một kỹ năng có thời điểm phát động bao gồm “Giai đoạn ra bài” của người đó trong giai đoạn này và tối đa có thể phát động một lần. Nếu người đó không có kỹ năng phù hợp điều kiện, thay bằng việc nhận ngẫu nhiên một kỹ năng thỏa mãn điều kiện.",
	dc_mengda: "Mạnh Đạt",
	dclibang: "Lợi Bàng",
	dclibang_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể bỏ một thẻ, nhận mỗi người trong hai nhân vật khác một thẻ ở trạng thái mặt ngửa. Sau đó bạn phán xét, nếu kết quả có màu sắc khác với cả hai thẻ này, bạn đưa cho một trong số những nhân vật đó hai thẻ hoặc mất 1 điểm thể lực, nếu không bạn nhận lấy thẻ phán xét và được coi là sử dụng một lá [Sát] lên một trong những nhân vật đó.",
	dcwujie: "Vô Tiết",
	dcwujie_info: "Kỹ năng khóa. ① Bạn sử dụng thẻ không màu không giới hạn khoảng cách và không tính vào số lần sử dụng. ② Nhân vật khác sau khi giết bạn không thực hiện khen thưởng hay trừng phạt thân phận.",
	dc_jsp_guanyu: "Tân Sát SP Quan Vũ",
	dc_jsp_guanyu_prefix: "Tân Sát SP",
	dcdanji: "Đơn Kỵ",
	dcdanji_info: "Kỹ năng thức tỉnh. Giai đoạn chuẩn bị, nếu số thẻ trong vùng của bạn lớn hơn thể lực, bạn giảm 1 điểm giới hạn thể lực, hồi phục thể lực đến giới hạn thể lực và rút số thẻ tương đương, sau đó nhận [Mã Thuật] và [Nộ Sân].",
	dcnuchen: "Nộ Sân",
	dcnuchen_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể trưng ra một thẻ trên tay của nhân vật khác, sau đó chọn một: 1. Bỏ bất kỳ số lượng thẻ có hoa sắc đó, gây cho người đó sát thương tương đương; 2. Nhận tất cả các thẻ có hoa sắc này trong số bài trên tay của nhân vật đó.",
	dc_jikang: "Tân Sát Kê Khang",
	dc_jikang_prefix: "Tân Sát",
	dcjuexiang: "Tuyệt Xướng",
	dcjuexiang_info: "Khi bạn chết, nhân vật giết bạn bỏ tất cả thẻ trong vùng trang bị và mất 1 điểm thể lực, sau đó bạn có thể khiến một nhân vật khác nhận [Tàn Vận].",
	dccanyun: "Tàn Vận",
	dccanyun_info: "Mỗi nhân vật giới hạn một lần. Giai đoạn ra bài, bạn có thể bỏ một thẻ và chọn một nhân vật khác, sau đó nếu số thẻ trang bị của người đó: nhỏ hơn bạn, người đó hồi 1 điểm thể lực; lớn hơn bạn, người đó mất 1 điểm thể lực; bằng bạn, người đó rút một thẻ. Nếu thể lực của bạn là 1, bạn rút một thẻ.",
	star_caoren: "Tinh Tào Nhân",
	star_caoren_prefix: "Tinh",
	starsujun: "Túc Quân",
	starsujun_info: "Khi bạn sử dụng một thẻ, nếu số lượng thẻ Cơ Bản và thẻ không phải Cơ Bản trong bài trên tay của bạn bằng nhau, bạn có thể rút hai thẻ.",
	starlifeng: "Lệ Phong",
	starlifeng_info: "Bạn có thể dùng một thẻ trên tay có màu sắc chưa từng được nhân vật nào sử dụng trong lượt này như là [Sát] không giới hạn số lần và không tính vào số lần hoặc [Vô Giải Khả Kích].",
	star_yuanshu: "Tinh Viên Thuật",
	star_yuanshu_prefix: "Tinh",
	starcanxi: "Tàn Tỉ",
	starcanxi_wangsheng: "Vọng Sinh",
	starcanxi_xiangsi: "Hướng Tử",
	starcanxi_cancel: "Hướng Tử",
	starcanxi_info: "Kỹ năng khóa. ① Khi trò chơi bắt đầu, bạn nhận dấu ấn “Tỉ Giác” tương ứng với phe phái của tất cả nhân vật trên sân (dấu ấn “Tỉ Giác” chưa nhận được trong các phe ban đầu đổi thành tăng số lượng giới hạn thể lực tương đương). ② Mỗi khi vòng mới bắt đầu, bạn chọn một phe phái tương ứng với “Tỉ Giác” và chọn một trong các hạng mục sau: 1. Vọng Sinh: Vòng này nhân vật thuộc phe đã chọn mỗi lượt lần đầu gây sát thương +1 và khoảng cách tính toán với các nhân vật khác -1; 2. Hướng Tử: Vòng này những nhân vật thuộc phe đã chọn khác mỗi lượt sau khi lần đầu hồi phục thể lực sẽ mất 1 điểm thể lực và thẻ đầu tiên sử dụng lên bạn mỗi lượt sẽ vô hiệu.",
	starpizhi: "Bĩ Trật",
	starpizhi_info: "Kỹ năng khóa. ① Sau khi một nhân vật chết, nếu bạn có dấu ấn “Tỉ Giác” tương ứng với nhân vật đó và phe phái bạn phát động [Tàn Tỉ] vòng này giống với phe đó, hoặc người đó là nhân vật cuối cùng của phe đó, bạn mất dấu ấn đó, sau đó rút X thẻ và hồi 1 điểm thể lực. ② Giai đoạn kết thúc, bạn rút X thẻ. (X là số lượng dấu ấn “Tỉ Giác” bạn đã mất trong ván đấu này)",
	starzhonggu: "Trủng Cốt",
	starzhonggu_info: "Kỹ năng chủ công, kỹ năng khóa. Giai đoạn rút bài, nếu số vòng trò chơi lớn hơn hoặc bằng số nhân vật phe Quần trên sân, bạn rút thêm hai thẻ, nếu không bạn rút ít đi một thẻ.",
	star_dongzhuo: "Tinh Đổng Trác",
	star_dongzhuo_prefix: "Tinh",
	starweilin: "Uy Lâm",
	starweilin_info: "Kỹ năng khóa. Khi bạn gây sát thương cho một nhân vật khác trong lượt, nếu người đó chưa từng chịu sát thương trong lượt này, và số thẻ bạn sử dụng trong lượt này lớn hơn hoặc bằng thể lực của người đó, thì sát thương này +1.",
	starzhangrong: "Chưởng Nhung",
	starzhangrong_info: "Giai đoạn chuẩn bị, bạn có thể chọn khiến tối đa X nhân vật có thể lực lớn hơn hoặc bằng bạn mỗi người mất 1 điểm thể lực hoặc khiến tối đa X nhân vật có số bài trên tay lớn hơn hoặc bằng bạn mỗi người bỏ một thẻ trên tay (X là thể lực của bạn). Nếu làm vậy, bạn rút số thẻ tương đương với số nhân vật đã chọn, và khi lượt này kết thúc, nếu trong những nhân vật này có nhân vật chưa từng chịu sát thương trong lượt này, bạn mất 1 điểm thể lực.",
	starhaoshou: "Hào Thủ",
	starhaoshou_info: "Kỹ năng chủ công. Sau khi nhân vật phe Quần khác sử dụng [Tửu] và kết thúc kết toán, người đó có thể khiến bạn hồi 1 điểm thể lực.",
	star_yuanshao: "Tinh Viên Thiệu",
	star_yuanshao_prefix: "Tinh",
	starxiaoyan: "Tiêu Diễm",
	starxiaoyan_info: "Kỹ năng khóa, khi trò chơi bắt đầu, bạn gây cho mỗi nhân vật khác 1 điểm sát thương thuộc tính lửa, sau đó những nhân vật này lần lượt có thể đưa cho bạn một thẻ và hồi 1 điểm thể lực.",
	starzongshi: "Túng Thế",
	starzongshi_info: "Giai đoạn ra bài, bạn có thể trưng ra một thẻ Cơ Bản hoặc thẻ Cẩm Nang bình thường có thể trưng mục tiêu, sau đó bạn dùng tất cả các thẻ khác trong bài trên tay có cùng hoa sắc với thẻ này như là thẻ này (không giới hạn khoảng cách), và thẻ này chỉ định tối đa số mục tiêu bằng số thẻ chuyển hóa.",
	starjiaowang: "Kiêu Vọng",
	starjiaowang_info: "Kỹ năng khóa, mỗi khi vòng kết thúc, nếu vòng này không có nhân vật nào chết, bạn mất 1 điểm thể lực và phát động [Tiêu Diễm].",
	staraoshi: "Ngạo Thế",
	staraoshi_info: "Kỹ năng chủ công, giai đoạn ra bài của nhân vật phe Quần khác giới hạn một lần, người đó có thể đưa cho bạn một thẻ trên tay, sau đó bạn có thể phát động [Túng Thế] một lần.",
	star_zhangchunhua: "Tinh Trương Xuân Hoa",
	star_zhangchunhua_prefix: "Tinh",
	starliangyan: "Lương Yến",
	starliangyan_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể chọn một nhân vật khác, bạn rút/bỏ tối đa hai thẻ, khiến người đó bỏ/rút số thẻ tương đương. Sau đó nếu số bài trên tay bạn và người đó bằng nhau, nhân vật rút bài bằng cách này sẽ bỏ qua giai đoạn bỏ bài tiếp theo.",
	starminghui: "Minh Tuệ",
	starminghui_info: "Khi lượt của một nhân vật kết thúc, nếu số bài trên tay bạn: ít nhất, bạn có thể được coi là sử dụng một lá [Sát] không giới hạn khoảng cách; nhiều nhất, bạn có thể bỏ bài trên tay cho đến khi số lượng không còn là nhiều nhất, sau đó khiến một nhân vật hồi 1 điểm thể lực.",
	star_sunshangxiang: "Tinh Tôn Thượng Hương",
	star_sunshangxiang_prefix: "Tinh",
	starsaying: "Táp Ảnh",
	starsaying_info: "Mỗi vòng mỗi tên thẻ giới hạn một lần, khi bạn cần sử dụng [Sát] hoặc [Thiểm], bạn có thể sử dụng một thẻ trang bị, coi như sử dụng nó; khi bạn cần sử dụng [Đào] hoặc [Tửu], bạn có thể thu hồi một thẻ trong vùng trang bị, coi như sử dụng nó.",
	starjiaohao: "Kiêu Hào",
	starjiaohao_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể đấu điểm với một nhân vật có số thẻ trang bị không lớn hơn bạn, sau đó bạn có thể khiến nhân vật thắng nhận lấy thẻ đấu điểm hoặc khiến người đó sử dụng một lá [Sát].",
	liqueguosi: "Lý Quyết Quách Tị",
	xiongsuan: "Hung Toán",
	xiongsuan_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ một thẻ trên tay và gây 1 điểm sát thương cho một nhân vật, sau đó bạn rút ba thẻ. Nếu nhân vật đó không phải bạn, bạn mất 1 điểm thể lực.",
	star_sunjian: "Tinh Tôn Kiên",
	star_sunjian_prefix: "Tinh",
	starruijun: "Nhuệ Quân",
	starruijun_info: "Sau khi bạn lần đầu sử dụng thẻ chỉ định nhân vật khác làm mục tiêu trong giai đoạn ra bài, bạn có thể chọn một nhân vật mục tiêu trong số đó và rút X thẻ (X là số thể lực bạn đã mất +1). Cho đến khi giai đoạn này kết thúc, ngoại trừ người đó, các nhân vật khác đều không nằm trong phạm vi tấn công của bạn, bạn sử dụng thẻ lên người đó không giới hạn khoảng cách, và khi bạn gây cho người đó sát thương không phải lần đầu, giá trị sát thương này đổi thành Y (Y là giá trị sát thương bạn gây cho người đó lần trước trong giai đoạn này +1, tối đa là 5).",
	stargangyi: "Cương Nghị",
	stargangyi_info: "Kỹ năng khóa. ① Trong lượt của bạn, nếu bạn chưa từng gây sát thương trong lượt này, bạn không thể sử dụng [Đào]. ② Khi bạn ở trạng thái hấp hối, giá trị hồi phục của [Đào] hoặc [Tửu] nhắm vào bạn +1.",
	star_zhangzhao: "Tinh Trương Chiêu",
	star_zhangzhao_prefix: "Tinh",
	starzhongyan: "Trung Ngôn",
	starzhongyan_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể trưng ra ba thẻ trên cùng của chồng bài, sau đó khiến một nhân vật trao đổi một thẻ trên tay với một trong số những thẻ đó. Sau đó nếu những thẻ này có cùng màu sắc, người đó hồi 1 điểm thể lực hoặc nhận một thẻ trên sân. Sau đó nếu nhân vật đó không phải bạn, bạn thực thi hạng mục mà người đó chưa thực thi.",
	starjinglun: "Kinh Luân",
	starjinglun_info: "Mỗi lượt giới hạn một lần, sau khi một nhân vật có khoảng cách trong vòng 1 với bạn gây sát thương, bạn có thể khiến người đó rút X thẻ và phát động [Trung Ngôn] lên người đó (X là số thẻ trang bị của người đó).",
	chezhou: "Xa Trụ",
	dcshefu: "Nhiếp Phục",
	dcshefu_info: "Kỹ năng khóa. Sát thương bạn gây cho nhân vật khác/nhân vật khác gây cho bạn do sử dụng thẻ đổi thành X (X là tổng số vòng đã trôi qua kể từ lần gần nhất tất cả thực thể thẻ tương ứng của lá bài này được nguồn sát thương nhận được cho đến nay).",
	dcpigua: "Phi Quái",
	dcpigua_info: "Sau khi bạn gây cho nhân vật khác sát thương vượt quá 1 điểm, bạn có thể nhận tối đa số thẻ của người đó tương đương với số vòng trò chơi, những thẻ này trong lượt này không tính vào giới hạn bài trên tay của bạn.",
	hansong: "Hàn Tung",
	dcyinbi: "Ẩn Tị",
	dcyinbi_info: "Kỹ năng khóa. ① Giới hạn bài trên tay của bạn bằng với nhân vật có giới hạn bài trên tay nhiều nhất trên sân. ② Nếu không có nhân vật nào khác có số bài trên tay bằng bạn, thì bạn sử dụng thẻ không giới hạn khoảng cách và số lần.",
	dcshuaiyan: "Suất Ngôn",
	dcshuaiyan_info: "① Khi giai đoạn rút bài hoặc giai đoạn bỏ bài của nhân vật khác kết thúc, nếu số bài trên tay bằng bạn, bạn có thể bỏ một thẻ của người đó hoặc rút một thẻ. ② Khi giai đoạn rút bài hoặc giai đoạn bỏ bài của bạn kết thúc, có thể rút X thẻ (X là số nhân vật có số bài trên tay bằng bạn).",
	matie: "Mã Thiết",
	dczhuiwang: "Truy Vong",
	dczhuiwang_info: "Kỹ năng khóa, khoảng cách bạn tính toán đến nhân vật có thể lực nhỏ hơn hoặc bằng bạn được coi là 1.",
	dcquxian: "Khu Hiểm",
	dcquxian_info: "Khi lượt bắt đầu và kết thúc, bạn có thể nhận một lá [Sát] từ chồng bài và chọn một nhân vật, những nhân vật có người đó trong phạm vi tấn công có thể lần lượt sử dụng một lá [Sát] lên người đó, mỗi khi có một nhân vật sử dụng [Sát] bạn rút một thẻ. Nếu người đó không chịu sát thương bằng cách này, những nhân vật khác trong số này không sử dụng [Sát] sẽ mất X điểm thể lực (X là số nhân vật đã sử dụng [Sát] trong số này).",
	star_xunyu: "Tinh Tuân Úc",
	star_xunyu_prefix: "Tinh",
	staranshu: "An Thứ",
	staranshu_info: "① Mỗi khi vòng kết thúc, bạn có thể chọn mỗi loại một thẻ Cơ Bản có tên khác nhau trong chồng bài bỏ đặt lên đỉnh chồng bài, sau đó được coi là sử dụng một lá [Ngũ Cốc Phong Đăng] (bắt đầu kết toán từ bạn hoặc một nhân vật đã bị thương); ② Khi lượt của một nhân vật kết thúc, nếu có nhân vật đã mất thẻ nhận được nhờ [An Thứ] ① trong vòng trước ở lượt này, bạn có thể khiến người đó rút bài đến giới hạn thể lực (tối đa rút năm lá).",
	starkuangzuo: "Khuông Tá",
	starkuangzuo_info: "Kỹ năng giới hạn, giai đoạn ra bài, bạn có thể khiến nhân vật A nhận [Thừa Phụng] (nếu người đó là chủ công và không có kỹ năng chủ công, người đó nhận thêm [Thống Âm]), sau đó khiến một nhân vật B khác đặt mỗi loại hoa sắc một thẻ lên thẻ võ tướng của A, gọi là “Khuông Tá”.",
	starchengfeng: "Thừa Phụng",
	starchengfeng_info: "Mỗi lượt giới hạn một lần, bạn có thể dùng một lá “Khuông Tá” đỏ/đen như là [Thiểm]/[Vô Giải Khả Kích] sử dụng cho thẻ sắp có hiệu lực lên bạn. Sau khi thẻ này kết thúc kết toán, nếu số màu sắc thẻ “Khuông Tá” của bạn ít hơn 2, bạn có thể lấy một thẻ trên cùng của chồng bài đặt lên thẻ võ tướng làm “Khuông Tá”.",
	startongyin: "Thống Âm",
	startongyin_info: "Kỹ năng chủ công, sau khi bạn chịu sát thương do nhân vật khác sử dụng thẻ gây ra, nếu nguồn sát thương cùng/khác phe phái với bạn, bạn có thể đặt thẻ này/một thẻ của người đó lên thẻ võ tướng làm “Khuông Tá”.",
	star_fazheng: "Tinh Pháp Chính",
	star_fazheng_prefix: "Tinh",
	starzhiji: "Tri Cơ",
	starzhiji_info: "Giai đoạn chuẩn bị, bạn có thể bỏ số lượng thẻ bất kỳ trên tay và rút bài cho đến khi đủ năm lá, sau đó nếu chênh lệch X giữa số thẻ bạn đã bỏ và số thẻ bạn đã rút: lớn hơn 0, bạn có thể gây cho tối đa X nhân vật khác mỗi người 1 điểm sát thương; bằng 0, thẻ bạn sử dụng trong lượt này không thể bị hưởng ứng; nhỏ hơn 0, giới hạn bài trên tay lượt này của bạn +2.",
	staranji: "Am Kế",
	staranji_info: "Kỹ năng khóa, khi một nhân vật sử dụng thẻ, nếu thẻ hoa sắc này được sử dụng ít nhất duy nhất trong vòng chơi này, bạn rút một thẻ.",
	star_dingfeng: "Tinh Đinh Phụng",
	star_dingfeng_prefix: "Tinh",
	stardangchen: "Đãng Trần",
	stardangchen_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể khiến một nhân vật đưa cho bạn số thẻ bất kỳ, sau đó bạn có thể bỏ X thẻ (X là số thẻ người đó đưa cho bạn). Nếu bạn bỏ bài vì lý do này, khi bạn sử dụng thẻ Cơ Bản hoặc thẻ Cẩm Nang bình thường trong giai đoạn này, có thể tiến hành một lần phán xét, nếu điểm số phán xét là bội số của X, thì thẻ này được kết toán thêm một lần.",
	starjianyu: "Tiễn Vũ",
	starjianyu_info: "Kỹ năng khóa, sau khi nhân vật khác mất thẻ trong vùng trang bị trong lượt của bạn, bạn rút một thẻ.",
	star_wenchou: "Tinh Văn Sú",
	star_wenchou_prefix: "Tinh",
	starlianzhan: "Liên Chiến",
	starlianzhan_info: "Khi bạn sử dụng thẻ sát thương chỉ định mục tiêu duy nhất, bạn có thể chọn một: ① Thêm một mục tiêu cho thẻ này; ② Khiến thẻ này được kết toán thêm một lần. Nếu làm vậy, sau khi thẻ này kết thúc kết toán, nếu số lần thẻ này gây sát thương: là 2, bạn có thể hồi 1 điểm thể lực (nếu bạn chưa bị thương thì thay bằng rút hai thẻ); là 0, nhân vật mục tiêu lần lượt được coi là sử dụng thẻ cùng tên lên bạn.",
	starweiming: "Uy Danh",
	starweiming_info: "Kỹ năng khóa, khi nhân vật khác có thể lực nhỏ hơn bạn hoặc đã chịu sát thương do bạn gây ra trong vòng này sử dụng thẻ lên bạn, người đó ngẫu nhiên bỏ một thẻ trên tay, nếu tất cả điều kiện đồng thời thỏa mãn, bạn rút một thẻ.",
	star_yanliang: "Tinh Nhan Lương",
	star_yanliang_prefix: "Tinh",
	starjizhan: "Cấp Chiến",
	starjizhan_info: "Sau khi bạn sử dụng thẻ sát thương đầu tiên trong lượt chỉ định mục tiêu đầu tiên, có thể khiến thẻ này gây cho một mục tiêu trong đó sát thương +2 (mỗi lá bài không phải sát thương bạn đã sử dụng trước đó trong lượt này, giá trị này -1); nếu thẻ này sau khi kết toán không gây được sát thương, người đó gây cho bạn 1 điểm sát thương.",
	starcuxia: "Xúc Hiệp",
	starcuxia_info: "Kỹ năng khóa, khi nhân vật khác có thể lực lớn hơn bạn hoặc đã gây sát thương cho bạn trong vòng này sử dụng thẻ lên bạn, người đó ngẫu nhiên bỏ một thẻ trên tay, nếu tất cả điều kiện đồng thời thỏa mãn, bạn rút một thẻ.",
	star_zhangrang: "Tinh Trương Nhượng",
	star_zhangrang_prefix: "Tinh",
	starduhai: "Đố Hại",
	starduhai_info: "Sau khi bạn trở thành mục tiêu của thẻ nhân vật khác sử dụng, bạn có thể chọn một loại hoa sắc, sau đó khiến người đó tăng dấu ấn 「Đố」 của hoa sắc này. Khi lượt của nhân vật đó kết thúc, nếu trong bài trên tay người đó có thẻ cùng hoa sắc với 「Đố」, thì người đó mất số điểm thể lực tương ứng với số loại hoa sắc, sau đó loại bỏ các dấu ấn 「Đố」 này.",
	starlingse: "Lệnh Sắc",
	starlingse_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể đưa cho một nhân vật khác một thẻ, sau đó ngẫu nhiên nhận hai thẻ cùng loại với thẻ này của nhân vật đó, nếu không đủ hai thẻ thì coi như người đó sử dụng một lá [Sát] lên bạn. Nếu lá [Sát] này gây sát thương, kỹ năng này được coi là chưa từng phát động.",
	star_taishici: "Tinh Thái Sử Từ",
	star_taishici_prefix: "Tinh",
	starchongwei: "Trọng Vi",
	starchongwei_info: "Kỹ năng khóa, khoảng cách bạn tính toán với các nhân vật khác +3. Sau khi bạn gây sát thương, giá trị này -1, khi giảm đến 0 bạn hồi 1 điểm thể lực và rút số thẻ bằng thể lực, sửa đổi [Xung Trở] và mất kỹ năng này.",
	starchongzu: "Xung Trở",
	starchongzu_info: "Sau khi thẻ chỉ định chính mình làm mục tiêu bạn sử dụng kết thúc kết toán, có thể chọn một: 1. Lá bài tiếp theo bạn sử dụng không giới hạn khoảng cách và số lần; 2. Rút hai thẻ và hạng mục này mất hiệu lực trong lượt này.",
	starchongzu_rewrite: "Xung Trở·Cải",
	starchongzu_rewrite_info: "Sau khi thẻ chỉ định chính mình làm mục tiêu bạn sử dụng kết thúc kết toán, có thể chọn một: 1. Lá bài tiếp theo bạn sử dụng không giới hạn khoảng cách và số lần; 2. Rút hai thẻ và hạng mục này mất hiệu lực trong lượt này; 3. Lần tới bạn sử dụng thẻ chỉ định mục tiêu, có thể gây cho một nhân vật khác trong đó 1 điểm sát thương.",
	star_jiangwan: "Tinh Tưởng Uyển",
	star_jiangwan_prefix: "Tinh",
	starzhenting: "Trấn Đình",
	starzhenting_info: "Khi lượt của một nhân vật kết thúc, nếu trong lượt này ít nhất hai nhân vật đã chịu sát thương, bạn có thể chọn một: 1. Khiến một nhân vật đã chịu sát thương trong lượt này hồi 1 điểm thể lực và rút một thẻ; 2. Khiến một nhân vật đã gây sát thương trong lượt này nhận hai thẻ đã đi vào chồng bài bỏ trong lượt này.",
	starchiguo: "Trì Quốc",
	starchiguo_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể xem ba thẻ dưới đáy chồng bài, trong giai đoạn này khi bạn sử dụng một thẻ, lật một thẻ dưới đáy chồng bài, nếu hai thẻ cùng hoa sắc, bạn tăng hoặc giảm một mục tiêu cho thẻ mình sử dụng (số mục tiêu ít nhất là 1), sau đó đặt thẻ này vào chồng bài bỏ; nếu không bạn đưa thẻ đã lật cho một nhân vật mục tiêu.",
	cuilie: "Thôi Liệt",
	dczijue: "Tỉ Tước",
	dczijue_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể khiến một nhân vật khác tuyên bố một con số từ 2-4, bạn có thể đưa cho người đó X thẻ và hồi 1 điểm thể lực, sau đó các nhân vật khác tính toán khoảng cách với bạn và điểm số thẻ đấu điểm của bạn +X cho đến khi lượt tiếp theo của bạn bắt đầu và khi bạn thắng đấu điểm thì rút một thẻ; nếu không bạn rút X thẻ (X là con số người đó đã tuyên bố).",
	dcchibi: "Xích Tị",
	dcchibi_info: "Mỗi lượt giới hạn một lần, khi nhân vật khác sử dụng thẻ chỉ định nhân vật có khoảng cách tính toán lớn hơn 1 làm mục tiêu duy nhất, bạn có thể đấu điểm với người đó: nếu bạn thắng, bạn khiến thẻ này vô hiệu và nhận lấy thẻ này; nếu bạn không thắng, bạn trở thành mục tiêu bổ sung của thẻ này.",
	dc_yanxiang: "Tân Sát Diêm Tượng",
	dc_yanxiang_prefix: "Tân Sát",
	dcyuzheng: "Dụ Tranh",
	dcyuzheng_info: "Giai đoạn ra bài mỗi hạng mục giới hạn một lần, bạn có thể khiến một nhân vật chọn một: 1. Điều chỉnh số bài trên tay bằng với nhân vật có ít bài nhất trên sân, sau X lần sử dụng hoặc đánh ra thẻ tiếp theo trong vòng này sẽ rút hai thẻ (X là số thẻ đã bỏ bằng cách này); 2. Rút số thẻ bằng giới hạn thể lực (tối đa là 5), vòng này tăng giới hạn bài trên tay tương đương, và vòng này tối đa có thể sử dụng thêm số thẻ tương đương.",
	dcyxsuishi: "Tuệ Thức",
	dcyxsuishi_info: "Giai đoạn kết thúc của một nhân vật, nếu số bài trên tay người đó không nhỏ hơn thể lực, bạn có thể tuyên bố tên một thẻ sát thương, người đó có thể dùng một thẻ như là lá bài này, nếu lá bài này gây sát thương, nhân vật chịu sát thương không thể sử dụng thẻ cùng màu sắc với thẻ đã gây sát thương cho đến khi lượt của người đó kết thúc.",
	star_zhanghe: "Tinh Trương Cáp",
	star_zhanghe_prefix: "Tinh",
	starjunxi: "Tuấn Tập",
	starjunxi_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể chọn một nhân vật khác và ghi nhớ số bài trên tay của mình; khi giai đoạn này kết thúc, nhân vật đó phải bỏ số thẻ bất kỳ và mất số thể lực bất kỳ (tổng số thẻ bỏ và thể lực là X), nếu X bằng 0, bạn bỏ hai thẻ (X là chênh lệch giữa số bài trên tay hiện tại và giá trị đã ghi nhớ của bạn).",
	starjixian: "Cơ Tiên",
	starjixian_info: "Nếu giai đoạn ra bài đầu tiên trong lượt của bạn không sử dụng thẻ Cơ Bản và thẻ Cẩm Nang, thì sau khi giai đoạn bỏ bài kết thúc bạn có thể thực hiện một giai đoạn ra bài bổ sung, trong giai đoạn này bạn không thể sử dụng thẻ trang bị.",
	old_starjixian: "Cơ Tiên",
	old_starjixian_info: "Kỹ năng khóa, khi lượt bắt đầu, bạn phải điều chỉnh thứ tự các giai đoạn định mức trong lượt này (không được giống với lượt trước).",
	star_zhangsong: "Tinh Trương Tùng",
	star_zhangsong_prefix: "Tinh",
	starxisong: "Tất Tụng",
	starxisong_info: "Mỗi vòng giới hạn một lần, khi giai đoạn ra bài của nhân vật khác bắt đầu, bạn có thể xem bài trên tay người đó, nếu làm vậy, khi giai đoạn này kết thúc, bạn tuyên bố một loại thẻ, hoa sắc và điểm số rồi trưng ra bài trên tay người đó. Nếu trong đó có thẻ hoàn toàn phù hợp với tuyên bố của bạn, kỹ năng này được coi là chưa từng phát động, sau đó người đó bỏ thẻ này, nếu bạn có thể sử dụng thì sử dụng nó.",
	starfanglang: "Phóng Lãng",
	starfanglang_info: "Giai đoạn rút bài, bạn có thể thay bằng việc chỉ rút một thẻ và trưng ra nó, sau đó cho đến khi lượt tiếp theo của bạn bắt đầu, ngoại trừ thẻ đã trưng ra, mỗi khi bạn sử dụng hoặc đánh ra lá bài đầu tiên mỗi lượt, bạn rút X thẻ (X là số hạng mục giống nhau về loại, hoa sắc, điểm số giữa lá bài này và thẻ đã trưng). Giai đoạn kết thúc, bạn có thể bỏ một thẻ, sau đó bạn nhận mỗi loại một thẻ trong chồng bài bỏ có cùng loại, điểm số, hoa sắc với thẻ này.",
	caobao: "Tào Báo",
	yanjiu: "Yếm Tửu",
	yanjiu_info: "Kỹ năng khóa, mỗi khi vòng kết thúc, bạn mất X điểm thể lực, nếu không mất thể lực vì lý do này bạn hồi 1 điểm thể lực. (X là số lượng [Tửu] bạn đã sử dụng hoặc bỏ trong giai đoạn bỏ bài vòng này)",
	poyin: "Bách Ẩm",
	poyin_info: "Kỹ năng khóa, khi lượt bắt đầu, bạn rút số thẻ bằng giới hạn thể lực, và chọn trong đó số thẻ bằng thể lực đã mất hoặc thể lực hiện tại để coi là [Tửu], khi lượt kết thúc, nhân vật có nhiều bài trên tay nhất trên sân chất vấn số lượng [Tửu] trong bài trên tay bạn có lớn hơn số bài khác hay không, nếu thành công người đó nhận một lá [Sát] từ chồng bài, nếu thất bại bạn có thể đúc lại số thẻ bất kỳ.",
};

export default translates;
