const translates = {
	jin_zhangchunhua: "Tấn Trương Xuân Hoa",
	jin_zhangchunhua_prefix: "Tấn",
	huishi: "Tuệ Thức",
	huishi_info: "Giai đoạn lấy bài, bạn có thể bỏ qua lấy bài, thay bằng quan sát X lá trên cùng chồng bài, lấy một nửa trong số đó (làm tròn xuống), sau đó để những lá còn lại vào đáy chồng bài. (X là chữ số hàng đơn vị của số lượng lá bài trong chồng bài)",
	qingleng: "Thanh Lãnh",
	qingleng_info: "Khi kết thúc lượt của một nhân vật, nếu tổng số thể lực và số bài trên tay của nhân vật đó không nhỏ hơn X, bạn có thể dùng một lá bài xem như [Sát] thuộc tính Băng không hạn chế khoảng cách lên nhân vật đó (X là chữ số hàng đơn vị của số lượng lá bài trong chồng bài). Nếu đây là lần đầu tiên bạn phát động kỹ năng này lên nhân vật đó trong ván game, bạn lấy một lá bài.",
	xuanmu: "Tuyên Mục",
	xuanmu2: "Tuyên Mục",
	xuanmu_info: "Kỹ năng khóa, kỹ năng ẩn nấp. Khi bạn xuất hiện trong lượt của nhân vật khác, ngăn chặn sát thương bạn phải chịu cho đến khi kết thúc lượt.",
	jin_simayi: "Tấn Tư Mã Ý",
	jin_simayi_prefix: "Tấn",
	zhanghuyuechen: "Trương Hổ Nhạc Lâm",
	xijue: "Tập Tước",
	xijue_gain: "Tập Tước",
	xijue_info: "Kỹ năng khóa, khi bắt đầu trò chơi, bạn nhận 4 dấu ấn “Tước”. Khi kết thúc lượt, bạn nhận X dấu ấn “Tước” (X là số sát thương bạn gây ra trong lượt này). Bạn có thể bỏ một dấu ấn “Tước” và vào thời điểm thích hợp phát động 〖Đột Kích〗 và 〖Kiêu Quả〗.",
	xijue_info_guozhan: "Kỹ năng khóa, khi bạn lần đầu lật ngửa thẻ võ tướng này, bạn nhận 4 dấu ấn “Tước”. Khi kết thúc lượt, bạn nhận X dấu ấn “Tước” (X là số sát thương bạn gây ra trong lượt này). Bạn có thể bỏ một dấu ấn “Tước” và vào thời điểm thích hợp phát động 〖Đột Kích〗 và 〖Kiêu Quả〗.",
	xijue_tuxi: "Đột Kích",
	xijue_tuxi_info: "Trong giai đoạn lấy bài, bạn có thể lấy ít đi số lá bất kỳ, sau đó lấy của các nhân vật khác mỗi người một lá bài trên tay tương ứng với số lá lấy ít đi.",
	xijue_tuxi_info_guozhan: "Trong giai đoạn lấy bài, bạn có thể lấy ít đi tối đa hai lá bài, sau đó lấy của các nhân vật khác mỗi người một lá bài trên tay tương ứng với số lá lấy ít đi.",
	xijue_xiaoguo: "Kiêu Quả",
	xijue_xiaoguo_info: "Khi bắt đầu giai đoạn kết thúc của nhân vật khác, bạn có thể bỏ một lá bài trên tay, khiến nhân vật đó chọn một: 1. Bỏ một lá trang bị, sau đó bạn lấy một lá bài; 2. Chịu 1 điểm sát thương do bạn gây ra.",
	xijue_xiaoguo_info_guozhan: "Khi bắt đầu giai đoạn kết thúc của nhân vật khác, bạn có thể bỏ một lá bài cơ bản, khiến nhân vật đó chọn một: 1. Bỏ một lá trang bị; 2. Chịu 1 điểm sát thương do bạn gây ra.",
	gz_duyu: "Đỗ Dự",
	duyu: "Tấn Đỗ Dự",
	duyu_prefix: "Tấn",
	sanchen: "Tam Trần",
	sanchen_info: "Giới hạn một lần trong giai đoạn ra bài. Bạn có thể chọn một nhân vật chưa được chọn trong lượt này. Người đó lấy ba lá bài, sau đó bỏ ba lá bài. Nếu người đó không bỏ bài bằng cách này hoặc các lá bài bỏ bằng cách này có loại hình hoàn toàn khác nhau, người đó lấy một lá bài và giới hạn số lần sử dụng 〖Tam Trần〗 trong giai đoạn này +1.",
	sanchen_info_guozhan: "Trong giai đoạn ra bài, bạn có thể chọn một nhân vật chưa được chọn trong lượt này. Người đó lấy ba lá bài, sau đó bỏ ba lá bài. Nếu người đó không bỏ bài bằng cách này hoặc các lá bài bỏ bằng cách này có loại hình hoàn toàn khác nhau, người đó lấy một lá bài và bạn nhận kỹ năng 〖Phá Trúc〗 cho đến khi kết thúc lượt. Nếu không, bạn không thể phát động tiếp 〖Tam Trần〗 trong giai đoạn này.",
	zhaotao: "Chiếu Thảo",
	zhaotao_info: "Kỹ năng thức tỉnh, giai đoạn chuẩn bị, nếu số lần bạn phát động 〖Tam Trần〗 trong ván game này lớn hơn 2, bạn giảm 1 điểm giới hạn thể lực và nhận 〖Phá Trúc〗.",
	pozhu: "Phá Trúc",
	pozhu_info: "Trong giai đoạn ra bài, bạn có thể dùng một lá bài trên tay xem như [Xuất Kỳ Bất Ý]. Nếu bạn không gây ra sát thương bởi lá bài này, bạn không thể phát động tiếp 〖Phá Trúc〗 cho đến khi kết thúc lượt.",
	pozhu_info_guozhan: "Giới hạn một lần trong giai đoạn ra bài, bạn có thể dùng một lá bài trên tay xem như [Xuất Kỳ Bất Ý].",
	jin_wangyuanji: "Tấn Vương Nguyên Cơ",
	jin_wangyuanji_prefix: "Tấn",
	shiren: "Thức Nhân",
	shiren_info: "Kỹ năng ẩn nấp. Khi bạn xuất hiện trong lượt của nhân vật khác, nếu người đó có bài trên tay, bạn có thể phát động 〖Yến Hỉ〗 lên người đó.",
	yanxi: "Yến Hỉ",
	yanxi2: "Yến Hỉ",
	yanxi_info: "Giới hạn một lần trong giai đoạn ra bài, bạn có thể chọn một nhân vật có bài trên tay. Bạn lấy một lá bài ngẫu nhiên trên tay của nhân vật đó trộn với hai lá trên cùng chồng bài rồi công khai, sau đó chọn lấy một lá. Nếu lá bạn chọn bằng cách này là bài trên tay của nhân vật đó, bạn nhận cả ba lá. Nếu không, bạn nhận lá bài đã chọn. Những lá bài bạn nhận được thông qua 〖Yến Hỉ〗 không tính vào giới hạn bài trên tay của lượt hiện tại.",
	yanxi_info_guozhan: "Giới hạn một lần trong giai đoạn ra bài, bạn có thể chọn một nhân vật có bài trên tay. Bạn lấy một lá bài ngẫu nhiên trên tay của nhân vật đó trộn với hai lá bài ngẫu nhiên trong chồng bài rồi công khai, sau đó chọn lấy một lá. Nếu lá bạn chọn bằng cách này là bài trên tay của nhân vật đó, bạn nhận cả ba lá. Nếu không, bạn nhận lá bài đã chọn. Những lá bài bạn nhận được thông qua 〖Yến Hỉ〗 không tính vào giới hạn bài trên tay của lượt hiện tại.",
	jin_simazhao: "Tấn Tư Mã Chiêu",
	jin_simazhao_prefix: "Tấn",
	tuishi: "Thôi Thí",
	tuishi_info: "Kỹ năng ẩn nấp, khi bạn xuất hiện trong lượt của nhân vật A, có thể vào lúc kết thúc lượt này chọn một nhân vật B trong phạm vi tấn công của A. A chọn một: ① Sử dụng một lá [Sát] lên B. ② Bạn gây cho A 1 điểm sát thương.",
	choufa: "Trù Phạt",
	choufa2: "Trù Phạt",
	choufa_info: "Giới hạn một lần trong giai đoạn ra bài, bạn có thể công khai một lá bài trên tay của một nhân vật khác và ghi nhớ loại hình A của nó. Bạn khiến các lá bài trên tay hiện tại có loại hình gốc không phải A của nhân vật đó đều xem như [Sát] và xem như không có thuộc tính, cho đến khi kết thúc lượt của nhân vật đó.",
	xinchoufa: "Trù Phạt",
	xinchoufa_info: "Giới hạn một lần trong giai đoạn ra bài, bạn có thể công khai một lá bài trên tay A của một nhân vật khác. Bạn khiến tất cả các lá bài trên tay có loại hình khác với A của nhân vật đó hiện tại đều xem như [Sát] và xem như không có thuộc tính, cho đến khi kết thúc lượt của nhân vật đó.",
	zhaoran: "Chiêu Nhiên",
	zhaoran2: "Chiêu Nhiên",
	zhaoran_info: "Khi bắt đầu giai đoạn ra bài, bạn có thể khiến bài trên tay của mình công khai với các nhân vật khác cho đến khi kết thúc giai đoạn ra bài. Nếu làm vậy, khi bạn mất một lá bài trên tay trong giai đoạn này, nếu trong số bài trên tay không có lá bài nào cùng hoa sắc với lá bài này và bạn chưa từng kích hoạt hiệu ứng này cho hoa sắc đó trong lượt này, bạn chọn một: ① Lấy một lá bài. ② Bỏ một lá bài của nhân vật khác.",
	visible_zhaoran: "vô hình",
	chengwu: "Thành Vụ",
	chengwu_info: "Kỹ năng chủ công, kỹ năng khóa, các nhân vật trong phạm vi tấn công của các nhân vật thuộc thế lực Tấn khác được xem là nằm trong phạm vi tấn công của bạn.",
	jin_xiahouhui: "Tấn Hạ Hầu Huy",
	jin_xiahouhui_prefix: "Tấn",
	baoqie: "Bảo Khiếp",
	baoqie_info: "Kỹ năng ẩn nấp, kỹ năng khóa. Sau khi bạn xuất hiện, nhận một lá Bảo vật không phải vật tặng từ chồng bài hoặc chồng bài bỏ. Nếu lá này là Bảo vật trong khu vực bài trên tay của bạn, bạn có thể sử dụng lá bài này.",
	jyishi: "Nghi Thất",
	jyishi_info: "Giới hạn một lần mỗi lượt, khi có nhân vật khác mất bài trên tay do vứt bỏ trong giai đoạn ra bài của họ, bạn có thể khiến người đó nhận lại một lá trong số những lá đó nằm trong chồng bài bỏ, sau đó bạn nhận những lá còn lại nằm trong chồng bài bỏ.",
	shiduo: "Thức Độ",
	shiduo_info: "Giới hạn một lần trong giai đoạn ra bài, bạn có thể đấu điểm với một nhân vật khác. Nếu bạn thắng, bạn nhận tất cả bài trên tay của người đó. Sau đó bạn đưa cho người đó X lá bài trên tay (X là một nửa số bài trên tay của bạn, làm tròn xuống).",
	jin_simashi: "Tấn Tư Mã Sư",
	jin_simashi_prefix: "Tấn",
	taoyin: "Thao Ẩn",
	taoyin2: "Thao Ẩn",
	taoyin_info: "Kỹ năng ẩn nấp, sau khi bạn xuất hiện, nếu nhân vật của lượt hiện tại tồn tại và không phải là bạn, bạn có thể khiến giới hạn bài trên tay của nhân vật đó trong lượt này -2.",
	yimie: "Di Diệt",
	yimie2: "Di Diệt",
	yimie_info: "Giới hạn một lần mỗi lượt, khi bạn gây sát thương cho nhân vật khác, nếu giá trị sát thương X nhỏ hơn Y, bạn có thể mất 1 điểm thể lực để đổi giá trị sát thương thành Y. Sau khi kết thúc kết toán sát thương này, người đó hồi phục (Y-X) điểm thể lực (Y là giá trị thể lực của người đó).",
	ruilve: "Duệ Lược",
	ruilve2: "Duệ Lược",
	ruilve_info: "Kỹ năng chủ công, giới hạn một lần trong giai đoạn ra bài của nhân vật thuộc thế lực Tấn khác, nhân vật đó có thể đưa cho bạn một lá bài cơ bản hoặc bài cẩm nang có nhãn sát thương.",
	tairan: "Thái Nhiên",
	tairan2: "Thái Nhiên",
	tairan_info: "Kỹ năng khóa, khi kết thúc lượt, bạn hồi phục thể lực về mức giới hạn, và lấy bài cho đến khi bằng giới hạn thể lực (gọi là bài “Thái Nhiên”). Sau đó khi bắt đầu giai đoạn ra bài tiếp theo của bạn, bạn mất số thể lực đúng bằng số thể lực đã hồi phục theo cách này lần trước, và bỏ tất cả bài “Thái Nhiên”.",
	gz_jin_simayi: "Tư Mã Ý",
	gz_jin_zhangchunhua: "Trương Xuân Hoa",
	gz_jin_simazhao: "Tư Mã Chiêu",
	gz_jin_wangyuanji: "Vương Nguyên Cơ",
	gz_jin_simashi: "Tư Mã Sư",
	gz_jin_xiahouhui: "Hạ Hầu Huy",
	xinquanbian: "Quyền Biến",
	xinquanbian_info: "Trong giai đoạn ra bài, mỗi khi bạn lần đầu sử dụng/đánh ra một loại hoa sắc bài trên tay, bạn có thể từ X lá trên cùng chồng bài lấy một lá có hoa sắc khác với lá bài này, và để những lá còn lại vào đỉnh chồng bài theo thứ tự tùy ý. Trong giai đoạn ra bài, bạn có thể sử dụng tối đa X lá bài trên tay không phải trang bị. (X là giới hạn thể lực của bạn)",
	shibao: "Thạch Bào",
	zhuosheng: "Trạc Thăng",
	zhuosheng_info: "Trong giai đoạn ra bài, ① Bạn sử dụng bài cơ bản nhận được trong vòng này không bị giới hạn số lần và khoảng cách. ② Sau khi bạn sử dụng bài cẩm nang thường nhận được trong vòng này và chọn mục tiêu, có thể khiến số mục tiêu của lá bài này +1 hoặc -1. ③ Khi bạn sử dụng bài trang bị nhận được trong vòng này, bạn có thể lấy một lá bài (bài nhận được bằng cách này không kích hoạt 〖Trạc Thăng〗).",
	zhuosheng_info_guozhan: "Trong giai đoạn ra bài, ① Bạn sử dụng bài cơ bản nhận được trong vòng này không bị giới hạn khoảng cách. ② Sau khi bạn sử dụng bài cẩm nang thường nhận được trong vòng này và chọn mục tiêu, có thể khiến số mục tiêu của lá bài này +1 hoặc -1. ③ Khi bạn sử dụng bài trang bị nhận được trong vòng này, bạn có thể lấy một lá bài (bài nhận được bằng cách này không kích hoạt 〖Trạc Thăng〗).",
	jin_yanghuiyu: "Tấn Dương Huy Du",
	jin_yanghuiyu_prefix: "Tấn",
	gz_jin_yanghuiyu: "Dương Huy Du",
	huirong: "Huệ Dung",
	huirong_info: "Kỹ năng ẩn nấp, kỹ năng khóa. Khi bạn xuất hiện, bạn khiến một nhân vật lấy bài đến mức/bỏ bài đến mức bằng với giá trị thể lực (tối đa lấy đến năm lá).",
	ciwei: "Từ Uy",
	ciwei_info: "Khi một nhân vật sử dụng lá bài thứ hai trong lượt của mình, nếu lá này là bài cơ bản hoặc cẩm nang thường, bạn có thể bỏ một lá bài để hủy bỏ tất cả mục tiêu của lá bài này.",
	caiyuan: "Tài Viện",
	caiyuan_info: "Kỹ năng khóa. Khi kết thúc lượt, nếu bạn chưa từng bị trừ thể lực kể từ khi kết thúc lượt trước của mình, bạn lấy hai lá bài.",
	simazhou: "Tư Mã Chu",
	caiwang: "Tài Vọng",
	caiwang_info: "Khi bạn sử dụng hoặc đánh ra bài để phản hồi lá bài của nhân vật khác sử dụng, hoặc nhân vật khác sử dụng hoặc đánh ra bài phản hồi lá bài của bạn sử dụng, nếu hai lá bài này cùng màu sắc, bạn có thể bỏ một lá bài của đối phương.",
	naxiang: "Nạp Giáng",
	naxiang2: "Nạp Giáng",
	naxiang_info: "Kỹ năng khóa, khi bạn chịu sát thương do nhân vật khác gây ra, hoặc bạn gây sát thương cho nhân vật khác, hiệu ứng “bỏ” khi bạn phát động 〖Tài Vọng①〗 lên người đó đổi thành “nhận lấy” cho đến khi bắt đầu lượt tiếp theo của bạn.",
	cheliji: "Triệt Lý Cát",
	chexuan: "Xa Huyền",
	chexuan_info: "Trong giai đoạn ra bài, nếu trong khu trang bị của bạn không có bài Bảo vật, bạn có thể bỏ một lá bài đen, chọn một lá [Dư] đặt vào khu trang bị; khi bạn mất bài Bảo vật trong khu trang bị, bạn có thể tiến hành phán xét, nếu kết quả là màu đen, đặt một lá [Dư] ngẫu nhiên vào khu trang bị.",
	qiangshou: "Khương Thủ",
	qiangshou_info: "Kỹ năng khóa, nếu trong khu trang bị của bạn có bài Bảo vật, khoảng cách giữa bạn và các nhân vật khác -1.",
	cheliji_sichengliangyu: "Tứ Thừa Lương Dư",
	cheliji_sichengliangyu_bg: "Lương",
	cheliji_sichengliangyu_info: "Khi kết thúc lượt của một nhân vật, nếu số bài trên tay của bạn nhỏ hơn giá trị thể lực, bạn có thể lấy hai lá bài, sau đó bỏ lá bài này.",
	cheliji_tiejixuanyu: "Thiết Tật Huyền Dư",
	cheliji_tiejixuanyu_bg: "Tật",
	cheliji_tiejixuanyu_info: "Khi kết thúc lượt của nhân vật khác, nếu người đó chưa gây ra sát thương trong lượt này, bạn có thể khiến người đó bỏ hai lá bài, sau đó bỏ lá bài này.",
	cheliji_feilunzhanyu: "Phi Luân Chiến Dư",
	cheliji_feilunzhanyu_bg: "Luân",
	cheliji_feilunzhanyu_info: "Khi kết thúc lượt của nhân vật khác, nếu người đó đã sử dụng bài không phải cơ bản trong lượt này, bạn có thể khiến người đó đưa cho bạn một lá bài, sau đó bỏ lá bài này.",
	weiguan: "Vệ Quán",
	zhongyun: "Trung Uẩn",
	zhongyun2: "Trung Uẩn",
	zhongyun_info: "Kỹ năng khóa. Giới hạn một lần mỗi lượt của mỗi nhân vật, sau khi bạn bị thương/hồi phục thể lực, nếu giá trị thể lực và số bài trên tay của bạn bằng nhau, bạn hồi 1 điểm thể lực hoặc gây 1 điểm sát thương cho một nhân vật trong phạm vi tấn công; Giới hạn một lần mỗi lượt của mỗi nhân vật, sau khi bạn nhận bài hoặc mất bài trên tay, nếu giá trị thể lực và số bài trên tay của bạn bằng nhau, bạn lấy một lá bài hoặc bỏ một lá bài của nhân vật khác.",
	shenpin: "Thần Phẩm",
	shenpin_info: "Trước khi lá bài phán xét của một nhân vật có hiệu lực, bạn có thể đánh ra một lá bài khác màu với lá phán xét để thay thế nó.",
	zhongyan: "Chung Diễm",
	bolan: "Bác Lãm",
	bolan_info: "① Khi bắt đầu giai đoạn ra bài, bạn có thể chọn một trong ba kỹ năng có mô tả “Giới hạn một lần trong giai đoạn ra bài”, khiến nhân vật của lượt hiện tại nhận được kỹ năng đó cho đến khi kết thúc giai đoạn này. ② Giới hạn một lần trong giai đoạn ra bài của nhân vật khác, người đó có thể mất 1 điểm thể lực để khiến bạn phát động 〖Bác Lãm①〗 một lần.",
	yifa: "Nghi Pháp",
	yifa2: "Nghi Pháp",
	yifa_info: "Kỹ năng khóa, sau khi nhân vật khác sử dụng [Sát] hoặc bài cẩm nang thường màu đen chỉ định bạn làm mục tiêu, giới hạn bài trên tay của người đó -1 cho đến khi kết thúc lượt.",
	ol_huaxin: "OL Hoa Hâm",
	ol_huaxin_prefix: "OL",
	caozhao: "Thảo Chiếu",
	caozhao_backup: "Thảo Chiếu",
	caozhao_info: "Giới hạn một lần trong giai đoạn ra bài, bạn có thể công khai một lá bài trên tay và tuyên bố một loại bài cơ bản hoặc cẩm nang thường chưa được tuyên bố theo cách này, khiến một nhân vật khác có thể lực không lớn hơn bạn chọn một: khiến lá bài này xem như lá bài bạn đã tuyên bố, hoặc người đó mất 1 điểm thể lực. Sau đó nếu lá bài này tuyên bố thành công, bạn có thể đưa nó cho một nhân vật khác.",
	olxibing: "Tức Binh",
	olxibing_info: "Sau khi bạn chịu sát thương do nhân vật khác gây ra, bạn có thể bỏ hai lá bài của mình hoặc của nhân vật đó, sau đó nhân vật có ít bài trên tay hơn trong hai người lấy hai lá bài, nhân vật lấy bài bằng cách này không thể sử dụng bài chỉ định bạn làm mục tiêu cho đến khi kết thúc lượt.",
	recaiwang: "Tài Vọng",
	recaiwang_info: "① Khi bạn sử dụng hoặc đánh ra bài để phản hồi lá bài của nhân vật khác sử dụng, hoặc nhân vật khác sử dụng hoặc đánh ra bài phản hồi lá bài của bạn sử dụng, nếu hai lá bài này cùng màu sắc, bạn có thể bỏ một lá bài của đối phương. ② Nếu số bài trên tay của bạn là 1, bạn có thể dùng lá bài đó xem như [Thiểm]. ③ Nếu số bài trong khu trang bị của bạn là 1, bạn có thể dùng trang bị đó xem như [Vô Giải Khả Kích]. ④ Nếu số bài trong khu phán xét của bạn là 1, bạn có thể dùng lá cẩm nang trì hoãn đó xem như [Sát].",
	recaiwang_hand: "Tài Vọng",
	recaiwang_equip: "Tài Vọng",
	recaiwang_judge: "Tài Vọng",
	yangyan: "Dương Diễm",
	xuanbei: "Tuyển Bị",
	xuanbei_info: "① Khi bắt đầu trò chơi, bạn nhận được hai lá bài có nhãn Ứng Biến từ chồng bài. ② Giới hạn một lần mỗi lượt. Sau khi lá bài có nhãn Ứng Biến bạn sử dụng kết thúc kết toán, bạn có thể đưa tất cả các lá bài thực thể tương ứng của lá bài này cho một nhân vật khác.",
	xianwan: "Nhàn Uyển",
	xianwan_info: "① Khi bạn cần sử dụng [Thiểm], nếu thẻ võ tướng của bạn chưa xoay ngang, bạn có thể xoay ngang thẻ võ tướng và xem như sử dụng [Thiểm]. ② Khi bạn cần sử dụng [Sát], nếu thẻ võ tướng của bạn đang xoay ngang, bạn có thể xoay dọc lại thẻ võ tướng và xem như sử dụng [Sát].",
	yangzhi: "Dương Chỉ",
	wanyi: "Uyển Di",
	wanyi_info: "Giới hạn mỗi mục một lần mỗi lượt. Trong giai đoạn ra bài, bạn có thể dùng một lá bài có hiệu ứng Ứng Biến xem như [Trục Cận Khí Viễn] / [Xuất Kỳ Bất Ý] / [Thủy Yêm Thất Quân] / [Động Chúc Tiên Cơ].",
	maihuo: "Mai Họa",
	maihuo_info: "① Sau khi bạn trở thành mục tiêu của [Sát] do nhân vật khác sử dụng, nếu lá [Sát] này không phải bài chuyển hóa và có lá thực thể tương ứng, đồng thời trên thẻ võ tướng của người đó không có “Họa” và bạn là mục tiêu duy nhất của lá bài này, bạn có thể khiến lá bài này vô hiệu với bạn, và đặt lá [Sát] này lên thẻ võ tướng của người đó, gọi là “Họa”. ② Khi bắt đầu giai đoạn ra bài của một nhân vật khác, nếu trên thẻ võ tướng của người đó có “Họa”, người đó sử dụng lá “Họa” này lên bạn (có hạn chế khoảng cách và tính vào giới hạn số lần, nếu bạn không phải là mục tiêu hợp lệ của lá bài này, thì thay bằng việc để lá “Họa” này vào chồng bài bỏ). ③ Sau khi bạn gây sát thương cho nhân vật khác có “Họa”, bạn loại bỏ “Họa” của người đó.",
	xinchang: "Tân Sướng",
	canmou: "Tham Mưu",
	canmou_info: "Khi một nhân vật sử dụng bài cẩm nang thường chỉ định mục tiêu đầu tiên, nếu số bài trên tay của người đó là nhiều nhất duy nhất trên sân, bạn có thể thêm một mục tiêu bổ sung cho lá bài này.",
	congjian: "Tòng Giám",
	congjian_info: "Khi một nhân vật khác trở thành mục tiêu duy nhất của bài cẩm nang thường, nếu giá trị thể lực của người đó là nhiều nhất duy nhất trên sân, bạn cũng có thể trở thành mục tiêu của lá bài này. Sau khi lá bài này kết thúc kết toán, nếu bạn từng chịu sát thương có nguồn gốc từ lá bài này, bạn lấy hai lá bài.",
	xuangongzhu: "Tấn Tuyên Công Chúa",
	gz_xuangongzhu: "Tuyên Công Chúa",
	xuangongzhu_prefix: "Tấn",
	gaoling: "Cao Lăng",
	gaoling_info: "Kỹ năng ẩn nấp. Khi bạn lật ngửa thẻ võ tướng này ngoài lượt, bạn có thể khiến một nhân vật hồi phục 1 điểm thể lực.",
	qimei: "Tề Mi",
	qimei_info: "Giai đoạn chuẩn bị, bạn có thể chọn một nhân vật khác. Bạn nhận được các hiệu ứng sau cho đến khi bắt đầu lượt tiếp theo: ① Giới hạn một lần mỗi lượt, khi bạn hoặc người đó nhận bài/mất bài trên tay, nếu số bài trên tay của bạn và người đó bằng nhau, nhân vật còn lại lấy một lá bài. ② Giới hạn một lần mỗi lượt, khi giá trị thể lực của bạn hoặc người đó thay đổi, nếu giá trị thể lực của bạn và người đó bằng nhau, nhân vật còn lại lấy một lá bài.",
	ybzhuiji: "Truy Cơ",
	ybzhuiji_info: "Khi bắt đầu giai đoạn ra bài, bạn có thể chọn một mục: ① Lấy hai lá bài, và khi kết thúc giai đoạn ra bài thì mất 1 điểm thể lực; ② Hồi phục 1 điểm thể lực, và khi kết thúc giai đoạn ra bài thì bỏ hai lá bài.",
	jin_yanghu: "Tấn Dương Hựu",
	jin_yanghu_prefix: "Tấn",
	huaiyuan: "Hoài Viễn",
	huaiyuanx: "Suy",
	huaiyuan_info: "① Khi bắt đầu trò chơi, bạn đánh dấu bài trên tay của mình là “Suy”. ② Khi bạn mất một lá bài “Suy”, bạn khiến một nhân vật thực hiện một mục: 1. Giới hạn bài trên tay +1. 2. Phạm vi tấn công +1. 3. Lấy một lá bài. ③ Khi bạn tử vong, bạn có thể khiến một nhân vật khác tăng giới hạn bài trên tay thêm X, và phạm vi tấn công thêm Y (X và Y là số lần bạn đã thực hiện mục một và mục hai của 〖Hoài Viễn②〗).",
	chongxin: "Sùng Tín",
	chongxin_info: "Giới hạn một lần trong giai đoạn ra bài, bạn có thể đúc lại một lá bài, và khiến một nhân vật khác có bài trên tay cũng đúc lại một lá bài.",
	dezhang: "Đức Chương",
	dezhang_info: "Kỹ năng thức tỉnh. Giai đoạn chuẩn bị, nếu bạn không có “Suy”, bạn giảm 1 điểm giới hạn thể lực và nhận 〖Vệ Thú〗.",
	weishu: "Vệ Thú",
	weishu_info: "Kỹ năng khóa. ① Khi bạn lấy bài ngoài giai đoạn lấy bài mà không phải do 〖Vệ Thú①〗, bạn khiến một nhân vật lấy một lá bài. ② Khi bạn bỏ bài ngoài giai đoạn bỏ bài mà không phải do 〖Vệ Thú②〗, bạn bỏ một lá bài của nhân vật khác.",
	jin_jiachong: "Tấn Giả Sung",
	jin_jiachong_prefix: "Tấn",
	xiongshu: "Hung Thụ",
	xiongshu_info: "Khi bắt đầu giai đoạn ra bài của nhân vật khác, bạn có thể bỏ X lá bài (X là số lần bạn đã phát động kỹ năng này trước đó trong vòng này, nếu là 0 thì không bỏ) và công khai một lá bài trên tay của người đó, sau đó bạn dự đoán “liệu người đó có sử dụng lá bài cùng tên với lá bài công khai trong giai đoạn này hay không”. Khi giai đoạn này kết thúc, nếu dự đoán của bạn chính xác, bạn gây cho người đó 1 điểm sát thương; nếu không bạn nhận lấy lá bài công khai đó.",
	jianhui: "Gian Hồi",
	jianhui_info: "Kỹ năng khóa. Bạn ghi nhớ nhân vật khác gần nhất gây sát thương cho bạn. Khi bạn gây sát thương cho người đó, bạn lấy một lá bài; khi bạn chịu sát thương do người đó gây ra, người đó phải bỏ một lá bài.",
	xinxuanbei: "Tuyển Bị",
	xinxuanbei_info: "Giới hạn một lần trong giai đoạn ra bài. Bạn có thể chọn một lá bài trong khu vực của nhân vật khác. Sau đó người đó sử dụng lá [Sát] có thực thể tương ứng là lá bài đó lên bạn. Sau đó nếu lá [Sát] này không gây sát thương cho bạn, bạn lấy một lá bài; nếu gây sát thương cho bạn, bạn lấy hai lá bài.",
	xinwanyi: "Uyển Di",
	xinwanyi_info: "① Sau khi bạn sử dụng [Sát] hoặc bài cẩm nang thường chỉ định nhân vật khác là mục tiêu duy nhất, bạn có thể đặt một lá bài của người đó lên thẻ võ tướng của bạn làm “Di”. ② Bạn không thể sử dụng/đánh ra/vứt bỏ lá bài có cùng hoa sắc với “Di”. ③ Trong giai đoạn kết thúc hoặc khi bạn chịu sát thương, bạn khiến một nhân vật nhận một lá “Di” của bạn.",
	jin_guohuai: "Quách Hoài",
	zhefu: "Triết Phụ",
	zhefu_info: "Sau khi bạn sử dụng hoặc đánh ra bài ngoài lượt, bạn có thể khiến một nhân vật khác có bài trên tay chọn một: 1. Bỏ một lá bài cùng tên. 2. Chịu 1 điểm sát thương do bạn gây ra.",
	yidu: "Di Độc",
	yidu_info: "Sau khi lá [Sát] hoặc bài cẩm nang gây sát thương bạn sử dụng kết thúc kết toán, bạn có thể công khai tối đa ba lá bài trên tay của một nhân vật mục tiêu chưa từng chịu sát thương từ lá bài này. Nếu các lá bài này đều cùng màu sắc, bạn bỏ những lá bài đó.",
	wangxiang: "Vương Tường",
	bingxin: "Băng Tâm",
	bingxin_info: "Mỗi tên bài giới hạn một lần mỗi lượt. Khi bạn cần sử dụng bài cơ bản, nếu số bài trên tay của bạn bằng giá trị thể lực và các lá bài này đều cùng màu sắc, bạn có thể lấy một lá bài, xem như sử dụng một lá bài cơ bản.",
	ol_lisu: "OL Lý Túc",
	ol_lisu_prefix: "OL",
	qiaoyan: "Xảo Ngôn",
	qiaoyan_info: "Kỹ năng khóa, khi bạn chịu sát thương do nhân vật khác gây ra ngoài lượt, nếu bạn: có “Châu”, bạn khiến nguồn sát thương nhận lấy “Châu”; không có “Châu”, bạn ngăn chặn sát thương này, sau đó lấy một lá bài, và đặt một lá bài ngửa mặt lên thẻ võ tướng, gọi là “Châu”.",
	xianzhu: "Hiến Châu",
	xianzhu_info: "Kỹ năng khóa, khi bắt đầu giai đoạn ra bài, bạn khiến một nhân vật A nhận lấy “Châu”. Nếu A không phải là bạn, bạn chọn một nhân vật B trong phạm vi tấn công của mình, xem như A sử dụng một lá [Sát] lên B.",
	chengjichengcui: "Thành Tế Thành Tụy",
	oltousui: "Thấu Tủy",
	oltousui_info: "Bạn có thể để số lượng bài bất kỳ vào đáy chồng bài, xem như sử dụng một lá [Sát] cần số lượng [Thiểm] tương ứng để triệt tiêu.",
	olchuming: "Súc Minh",
	olchuming_info: "Kỹ năng khóa. Khi bạn gây sát thương cho nhân vật khác, hoặc khi bạn chịu sát thương do nhân vật khác gây ra, nếu nguồn sát thương này không phải từ bài hoặc không có lá thực thể tương ứng, sát thương này +1, nếu không người đó vào lúc kết thúc lượt này sẽ dùng tất cả các lá bài đã gây sát thương theo cách này xem như [Tá Đao Sát Nhân] hoặc [Quá Hà Chiết Kiều] lên bạn.",
};

export default translates;
