import { lib, game, ui, get, ai, _status } from "noname";

const translates = {
	re_zhangliao: "Giới Trương Liêu",
	re_zhangliao_prefix: "Giới",
	re_simayi: "Giới Tư Mã Ý",
	re_simayi_prefix: "Giới",
	re_xuzhu: "Giới Hứa Chử",
	re_xuzhu_prefix: "Giới",
	re_xiahoudun: "Giới Hạ Hầu Đôn",
	re_xiahoudun_prefix: "Giới",
	re_lvmeng: "Giới Lã Mông",
	re_lvmeng_prefix: "Giới",
	re_zhouyu: "Giới Chu Du",
	re_zhouyu_prefix: "Giới",
	re_luxun: "Giới Lục Tốn",
	re_luxun_prefix: "Giới",
	re_zhaoyun: "Giới Triệu Vân",
	re_zhaoyun_prefix: "Giới",
	re_guanyu: "Giới Quan Vũ",
	re_guanyu_prefix: "Giới",
	re_zhangfei: "Giới Trương Phi",
	re_zhangfei_prefix: "Giới",
	re_machao: "Giới Mã Siêu",
	re_machao_prefix: "Giới",
	re_caocao: "Giới Tào Tháo",
	re_caocao_prefix: "Giới",
	re_guojia: "Giới Quách Gia",
	re_guojia_prefix: "Giới",
	re_lvbu: "Giới Lã Bố",
	re_lvbu_prefix: "Giới",
	re_huanggai: "Giới Hoàng Cái",
	re_huanggai_prefix: "Giới",
	re_daqiao: "Giới Đại Kiều",
	re_daqiao_prefix: "Giới",
	re_ganning: "Giới Cam Ninh",
	re_ganning_prefix: "Giới",
	re_huatuo: "Giới Hoa Đà",
	re_huatuo_prefix: "Giới",
	re_liubei: "Giới Lưu Bị",
	re_liubei_prefix: "Giới",

	re_diaochan: "Giới Điêu Thuyền",
	re_diaochan_prefix: "Giới",
	re_huangyueying: "Giới Hoàng Nguyệt Anh",
	re_huangyueying_prefix: "Giới",
	re_sunquan: "Giới Tôn Quyền",
	re_sunquan_prefix: "Giới",
	re_sunshangxiang: "Giới Tôn Thượng Hương",
	re_sunshangxiang_prefix: "Giới",
	re_zhugeliang: "Giới Gia Cát Lượng",
	re_zhugeliang_prefix: "Giới",
	re_zhenji: "Giới Chân Mật",
	re_zhenji_prefix: "Giới",
	re_huaxiong: "Giới Hoa Hùng",
	re_huaxiong_prefix: "Giới",

	ol_sp_zhugeliang: "Giới Ngọa Long",
	ol_sp_zhugeliang_prefix: "Giới",
	re_zhangjiao: "Giới Trương Giác",
	re_zhangjiao_prefix: "Giới",
	re_sunce: "Giới Tôn Sách",
	re_sunce_prefix: "Giới",
	ol_yuanshao: "Giới Viên Thiệu",
	ol_yuanshao_prefix: "Giới",
	ol_liushan: "Giới Lưu Thiện",
	ol_liushan_prefix: "Giới",

	olfangquan: "Phóng Quyền",
	olfangquan_info: "Trước khi giai đoạn ra bài bắt đầu, bạn có thể bỏ qua giai đoạn này. Nếu làm vậy, khi giai đoạn bỏ bài bắt đầu, bạn có thể bỏ một lá bài trên tay, khiến một nhân vật khác thực hiện một lượt bổ sung.",
	olruoyu: "Nhược Ngu",
	olruoyu_info: "Chủ công kỹ, Giác tỉnh kỹ, Giai đoạn chuẩn bị, nếu thể lực của bạn thấp nhất toàn cuộc, bạn tăng 1 điểm giới hạn thể lực, hồi phục thể lực về 3 điểm, sau đó nhận kỹ năng 〖Tư Thục〗 và 〖Kích Giảng〗.",
	sishu: "Tư Thục",
	sishu_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể chọn một nhân vật. Hiệu ứng phán xét 【Lạc Bất Tư Thục】 của nhân vật đó trong ván này sẽ bị đảo ngược.",
	olluanji: "Loạn Kích",
	olluanji_info: "Bạn có thể dùng hai lá bài trên tay cùng chất xem như sử dụng 【Vạn Tiễn Tề Phát】. Sau khi bạn chọn mục tiêu cho 【Vạn Tiễn Tề Phát】, bạn có thể giảm bớt một mục tiêu cho lá bài này.",
	olluanji_remove: "Loạn Kích",
	olxueyi: "Huyết Duệ",
	olxueyi_info: "Chủ công kỹ, Tỏa định kỹ. ① Khi trò chơi bắt đầu, bạn nhận 2X dấu ấn “Duệ” (X là số lượng nhân vật phe Quần trên sân). ② Khi giai đoạn ra bài bắt đầu, bạn có thể xóa một dấu ấn “Duệ”, sau đó rút một lá bài. ③ Giới hạn bài trên tay của bạn +Y (Y là số lượng dấu ấn “Duệ”).",
	olxueyi_draw: "Huyết Duệ",
	olhunzi: "Hồn Tư",
	olhunzi_info: "Giác tỉnh kỹ, Giai đoạn chuẩn bị, nếu thể lực của bạn là 1, bạn giảm 1 điểm giới hạn thể lực và nhận kỹ năng 〖Anh Tư〗 và 〖Anh Hồn〗; giai đoạn kết thúc lượt này, bạn rút hai lá bài hoặc hồi phục 1 điểm thể lực.",
	olzhiba: "Chế Bá",
	olzhiba_info: "Chủ công kỹ, trong giai đoạn ra bài của nhân vật phe Ngô khác giới hạn một lần, họ có thể đấu điểm với bạn (bạn có thể từ chối). Nếu họ không thắng, bạn có thể nhận hai lá bài đấu điểm. Trong giai đoạn ra bài của bạn giới hạn một lần, bạn có thể đấu điểm với một nhân vật phe Ngô, nếu bạn thắng, bạn nhận hai lá bài đấu điểm.",
	olzhiba2: "Chế Bá",
	xinleiji: "Lôi Kích",
	xinleiji_misa: "Lôi Kích",
	xinguidao: "Quỷ Đạo",
	xinleiji_info: "① Khi bạn sử dụng 【Thiểm】 hoặc 【Thiểm Điện】, hoặc đánh ra 【Thiểm】, bạn có thể tiến hành phán xét. ② Sau khi lá bài phán xét có hiệu lực, nếu kết quả là: Bích, bạn có thể gây cho một nhân vật 2 điểm sát thương sấm sét; Nhép: Bạn hồi phục 1 điểm thể lực và có thể gây cho một nhân vật 1 điểm sát thương sấm sét.",
	xinleiji_append: '<span style="font-family:yuanli">Phán xét không thể kích hoạt 〖Lôi Kích〗: 〖Bạo Ngược〗, 〖Trợ Tế〗, <br>〖Hoằng Nghi〗, 〖Cô Ảnh〗.</span>',
	xinleiji_faq: "Phán xét không thể kích hoạt 〖Lôi Kích〗",
	xinleiji_faq_info: "<br>Đổng Trác/Giới Đổng Trác 〖Bạo Ngược〗<br>Hoàng Cân Lôi Sứ 〖Trợ Tế〗<br>Dương Huy Du 〖Hoằng Nghi〗<br>Minh Lại Bạch Vũ 〖Cô Ảnh〗",
	xinguidao_info: "Trước khi lá bài phán xét của một nhân vật có hiệu lực, bạn có thể đánh ra một lá bài màu đen xem như lá bài phán xét và nhận lấy lá bài phán xét cũ. Nếu lá bài bạn đánh ra theo cách này là Bích từ 2-9, bạn rút một lá bài.",
	xinhuangtian: "Hoàng Thiên",
	xinhuangtian2: "Hoàng Thiên",
	xinhuangtian_info: "Chủ công kỹ. Trong giai đoạn ra bài của nhân vật phe Quần khác giới hạn một lần, nhân vật đó có thể đưa cho bạn một lá 【Thiểm】 hoặc bài tay chất Bích.",
	reqiangxi: "Cường Kích",
	reqiangxi_info: "Trong giai đoạn ra bài giới hạn một lần đối với mỗi nhân vật khác, bạn có thể chọn một: 1. Mất 1 điểm thể lực và gây 1 điểm sát thương cho một nhân vật khác trong phạm vi tấn công; 2. Bỏ một lá trang bị Vũ khí và gây 1 điểm sát thương cho một nhân vật khác trong phạm vi tấn công.",
	rehuoji: "Hỏa Kế",
	rehuoji_info: "Bạn có thể dùng một lá bài màu đỏ xem như sử dụng 【Hỏa Công】.",
	rekanpo: "Khán Phá",
	rekanpo_info: "Bạn có thể dùng một lá bài màu đen xem như sử dụng 【Vô Giải Khả Kích】.",
	reshuangxiong: "Song Hùng",
	reshuangxiong1: "Song Hùng",
	reshuangxiong2: "Song Hùng",
	reshuangxiong_info: "Giai đoạn rút bài, bạn có thể từ bỏ rút bài. Nếu làm vậy, bạn lật hai lá bài từ đỉnh chồng bài và chọn lấy một lá. Sau đó, trong lượt này bạn có thể dùng một lá bài trên tay khác màu với lá bài này xem như sử dụng 【Quyết Đấu】. Khi bạn chịu sát thương từ 【Quyết Đấu】, bạn có thể nhận tất cả các lá 【Sát】 đã đánh ra trong cuộc quyết đấu đó.",

	reguanxing: "Quan Tinh",
	reguanxing_info: "Giai đoạn chuẩn bị, bạn có thể xem năm lá bài trên đỉnh chồng bài (khi số nhân vật còn sống ít hơn 4 thì đổi thành ba lá), và đặt chúng lên đỉnh hoặc xuống đáy chồng bài theo thứ tự tùy ý, nếu bạn đặt tất cả bài 〖Quan Tinh〗 xuống đáy chồng bài, bạn có thể phát động 〖Quan Tinh〗 lần nữa vào giai đoạn kết thúc.",
	reluoshen: "Lạc Thần",
	reluoshen_info: "Giai đoạn chuẩn bị, bạn có thể tiến hành phán xét, nếu kết quả màu đen thì nhận lá bài phán xét này, và có thể lặp lại quy trình cho đến khi xuất hiện kết quả màu đỏ. Bài bạn nhận được thông qua 〖Lạc Thần〗 không tính vào giới hạn bài tay của lượt hiện tại.",
	reluoshen_info_guozhan: "Giai đoạn chuẩn bị, bạn có thể tiến hành phán xét, nếu là màu đen thì có thể tiếp tục phán xét cho đến khi xuất hiện màu đỏ. Sau đó bạn nhận tất cả các lá bài phán xét màu đen. Bài bạn nhận được thông qua 〖Lạc Thần〗 không tính vào giới hạn bài tay của lượt hiện tại (các lá bài phán xét kết quả màu đen sẽ không đi vào chồng bài bỏ trong quá trình này).",
	rejieyin: "Kết Nhân",
	rejieyin_info: "Trong giai đoạn ra bài giới hạn một lần, bạn có thể chọn một nhân vật nam và bỏ một lá bài trên tay hoặc đặt một lá trang bị trong khu trang bị vào khu trang bị của nhân vật đó, nhân vật có thể lực cao hơn giữa bạn và họ rút một lá bài, nhân vật có thể lực thấp hơn hồi phục 1 điểm thể lực.",
	rebiyue: "Bế Nguyệt",
	rebiyue_info: "Giai đoạn kết thúc, bạn có thể rút một lá bài, nếu bạn không có bài trên tay, đổi thành rút hai lá bài.",
	rejizhi: "Tập Trí",
	rejizhi_info: "Khi bạn sử dụng một lá Cẩm nang, bạn có thể rút một lá bài. Nếu lá đó là bài Cơ bản, bạn có thể bỏ nó, sau đó khiến giới hạn bài tay lượt này +1.",
	reqicai: "Kỳ Tài",
	reqicai_info: "Tỏa định kỹ, bạn sử dụng lá Cẩm nang không bị giới hạn khoảng cách, các lá Phòng cụ và Bảo vật trong khu trang bị của bạn không thể bị nhân vật khác loại bỏ.",
	rezhiheng: "Chế Hành",
	rezhiheng_info: "Trong giai đoạn ra bài giới hạn một lần, bạn có thể bỏ bất kỳ số lượng bài nào và rút lượng bài tương ứng, nếu bạn bỏ tất cả bài trên tay khi phát động 〖Chế Hành〗, bạn rút thêm một lá bài.",
	rejiuyuan: "Cứu Viện",
	rejiuyuan_info: "Chủ công kỹ, khi nhân vật phe Ngô khác hồi phục thể lực trong lượt của họ, nếu thể lực của họ lớn hơn hoặc bằng bạn, nhân vật đó có thể đổi thành khiến bạn hồi phục 1 điểm thể lực, sau đó họ rút một lá bài.",

	new_yajiao: "Nha Giác",
	new_yajiao_info: "Mỗi khi bạn sử dụng hoặc đánh ra bài ngoài lượt của mình, bạn có thể lật một lá bài từ đỉnh chồng bài và đưa nó cho một nhân vật. Nếu lá bài này khác loại với lá bài bạn vừa sử dụng hoặc đánh ra, bạn bỏ một lá bài.",
	new_liyu: "Lợi Ngự",
	new_liyu_info: "Sau khi bạn sử dụng 【Sát】 gây sát thương cho một nhân vật khác, bạn có thể nhận một lá bài trong khu vực của họ. Nếu lá bài này không phải trang bị, họ rút một lá bài. Nếu lá bài này là trang bị, xem như bạn sử dụng một lá 【Quyết Đấu】 lên một nhân vật khác do họ chọn.",
	new_retuxi: "Đột Kích",
	new_retuxi_info: "Khi rút bài trong giai đoạn rút bài, bạn có thể rút ít đi bất kỳ số lượng lá nào, sau đó nhận một lá bài tay của mỗi nhân vật tương ứng.",
	new_retuxi_info_guozhan: "Khi rút bài trong giai đoạn rút bài, bạn có thể rút ít đi tối đa hai lá bài, sau đó nhận một lá bài tay của mỗi nhân vật tương ứng.",
	reyiji_tag: "Đã phân phối",
	new_reyiji: "Di Kế",
	new_reyiji_info: "Sau khi chịu 1 điểm sát thương, bạn có thể rút hai lá bài, sau đó có thể đưa tối đa hai lá bài tay cho các nhân vật khác.",
	new_rejianxiong: "Gian Hùng",
	new_rejianxiong_info: "Sau khi chịu sát thương, bạn có thể nhận lá bài đã gây sát thương cho bạn và rút một lá bài.",
	new_reluoyi: "Khỏa Y",
	new_reluoyi_info: "Khi giai đoạn rút bài bắt đầu, bạn lật ba lá bài từ đỉnh chồng bài. Sau đó, bạn có thể từ bỏ rút bài. Nếu làm vậy, bạn nhận các lá bài Cơ bản, Vũ khí và 【Quyết Đấu】 trong số đó, và cho đến khi lượt tiếp theo của bạn bắt đầu, khi 【Sát】 hoặc 【Quyết Đấu】 bạn sử dụng gây sát thương, sát thương này +1. Nếu không, bạn đặt những lá bài này vào chồng bài bỏ.",
	new_rewusheng: "Võ Thánh",
	new_rewusheng_info: "Bạn có thể dùng một lá bài màu đỏ xem như sử dụng hoặc đánh ra 【Sát】. Lá 【Sát】 chất Rô bạn sử dụng không bị giới hạn khoảng cách.",
	new_yijue: "Nghĩa Tuyệt",
	new_yijue_info: "Trong giai đoạn ra bài giới hạn một lần, bạn có thể bỏ một lá bài và khiến một nhân vật khác có bài tay cho xem một lá bài trên tay. Nếu lá này màu đen, nhân vật đó không thể sử dụng hoặc đánh ra bài tay, các kỹ năng phi tỏa định mất hiệu lực và sát thương từ 【Sát】 Cơ của bạn gây ra +1 cho đến khi kết thúc lượt. Nếu lá này màu đỏ, bạn có thể nhận lấy lá bài này và có thể khiến họ hồi phục 1 điểm thể lực.",
	new_repaoxiao: "Bào Hiếu",
	new_repaoxiao_info: "Tỏa định kỹ, giai đoạn ra bài, bạn sử dụng 【Sát】 không giới hạn số lượng. Nếu bạn đã sử dụng 【Sát】 trong giai đoạn ra bài này, bạn sử dụng 【Sát】 không giới hạn khoảng cách trong lượt này.",
	new_tishen: "Thế Thân",
	new_tishen_info: "Khi giai đoạn ra bài kết thúc, bạn có thể bỏ tất cả lá Cẩm nang và Ngựa của mình. Nếu làm vậy, cho đến khi lượt tiếp theo của bạn bắt đầu, khi một lá 【Sát】 kết thúc quyết toán, nếu bạn là mục tiêu của lá bài này và không chịu sát thương từ nó, bạn nhận tất cả các lá bài thực thể tương ứng với lá bài đó.",
	new_tishen2: "Thế Thân",
	new_tishen2_info: "",
	new_qingjian: "Thanh Kiệm",
	new_qingjian_info: "Giới hạn một lần mỗi lượt. Khi bạn nhận được bài ngoài giai đoạn rút bài, bạn có thể cho xem bất kỳ số lượng lá bài nào và đưa cho một nhân vật khác. Sau đó, giới hạn bài tay của nhân vật hiện tại trong lượt này +X (X là số loại bài chứa trong các lá bài bạn đã đưa).",
	qingjian_add: "Thanh Kiệm",
	qingjian_add_info: "",
	new_reqingnang: "Thanh Nang",
	new_reqingnang_info: "Giai đoạn ra bài, bạn có thể bỏ một lá bài trên tay, khiến một nhân vật chưa từng là mục tiêu của 〖Thanh Nang〗 trong lượt này hồi phục 1 điểm thể lực. Nếu bạn bỏ lá bài màu đen, bạn không thể phát động tiếp 〖Thanh Nang〗 trong lượt này.",
	new_reyaowu: "Diệu Võ",
	new_reyaowu_info: "Tỏa định kỹ, khi một nhân vật sử dụng 【Sát】 gây sát thương cho bạn, nếu lá 【Sát】 này màu đỏ, nhân vật đó hồi 1 điểm thể lực hoặc rút một lá bài. Nếu không bạn rút một lá bài.",
	reyaowu: "Diệu Võ",
	reyaowu_info: "Tỏa định kỹ, khi bạn chịu sát thương từ một lá bài, nếu lá bài này màu đỏ, nguồn sát thương rút một lá bài; nếu không bạn rút một lá bài.",
	reqingguo: "Khuynh Quốc",
	reqingguo_info: "Bạn có thể dùng một lá bài màu đen xem như sử dụng hoặc đánh ra 【Thiểm】.",

	qinxue: "Cần Học",
	retuxi: "Đột Kích",
	reluoyi: "Khỏa Y",
	reluoyi2: "Khỏa Y",
	reganglie: "Cương Liệt",
	qingjian: "Thanh Kiệm",
	reyingzi: "Anh Tư",
	refanjian: "Phản Gián",
	refanjian_card: "Bỏ bài",
	refanjian_hp: "Mất thể lực",
	reqianxun: "Khiêm Tốn",
	reqianxun2: "Khiêm Tốn",
	relianying: "Liên Doanh",
	retishen: "Thế Thân",
	retishen2: "Thế Thân",
	reyajiao: "Nha Giác",
	rejianxiong: "Gian Hùng",
	rejianxiong_mopai: "Rút bài",
	rejianxiong_napai: "Lấy bài",
	reyiji: "Di Kế",
	reyiji2: "Di Kế",
	yijue: "Nghĩa Tuyệt",
	yijue2: "Nghĩa Tuyệt",
	retieji: "Thiết Kỵ",
	refankui: "Phản Phối",
	reyicong: "Nghĩa Tòng",
	qiaomeng: "Kiêu Mãnh",
	rekurou: "Khổ Nhục",
	zhaxiang: "Trá Hàng",
	zhaxiang2: "Trá Hàng",
	zhuhai: "Tru Hại",
	qianxin: "Tiềm Tâm",
	jianyan: "Tiến Ngôn",
	reguicai: "Quỷ Tài",
	xunxun: "Tuân Tuân",
	wangxi: "Vong Khích",
	reguose: "Quốc Sắc",
	fenwei: "Phấn Uy",
	chulao: "Trừ Lệ",
	liyu: "Lợi Ngự",
	rerende: "Nhân Đức",
	rerende_info: "Trong giai đoạn ra bài, bạn có thể đưa ít nhất một lá bài tay cho nhân vật khác, sau đó bạn không thể đưa bài cho nhân vật đó theo cách này nữa trong giai đoạn này; nếu tổng số bài bạn đưa trong giai đoạn này lần đầu đạt hai lá, bạn có thể xem như sử dụng một lá bài Cơ bản.",
	liyu_info: "Sau khi bạn sử dụng 【Sát】 gây sát thương cho một nhân vật khác, nhân vật đó có thể khiến bạn nhận một lá bài của họ, nếu làm vậy, xem như bạn sử dụng một lá 【Quyết Đấu】 lên một nhân vật khác do họ chọn.",
	xunxun_info: "Giai đoạn rút bài, bạn có thể xem bốn lá bài trên đỉnh chồng bài, sau đó đặt hai lá lên đỉnh chồng bài, và đặt những lá còn lại xuống đáy chồng bài theo thứ tự tùy ý.",
	wangxi_info: "Mỗi khi bạn gây 1 điểm sát thương cho nhân vật khác, hoặc chịu 1 điểm sát thương từ nhân vật khác, bạn có thể cùng nhân vật đó mỗi người rút một lá bài.",
	reguose_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể chọn một: Dùng một lá chất Rô xem như sử dụng 【Lạc Bất Tư Thục】; hoặc bỏ một lá chất Rô và bỏ một lá 【Lạc Bất Tư Thục】 trên sân. Sau khi chọn xong, bạn rút một lá bài.",
	fenwei_info: "Hạn định kỹ, khi một nhân vật sử dụng lá Cẩm nang chỉ định ít nhất hai nhân vật làm mục tiêu, bạn có thể khiến lá bài này vô hiệu đối với bất kỳ số lượng nhân vật nào trong số đó.",
	chulao_info: "Giai đoạn ra bài giới hạn một lần, nếu bạn có bài, bạn có thể chọn bất kỳ số lượng nhân vật khác có phe phái khác nhau, bạn bỏ một lá bài của mình và của mỗi nhân vật đó. Sau đó, những nhân vật đã bị bỏ bài Bích theo cách này mỗi người rút một lá bài.",
	reguicai_info: "Trước khi lá bài phán xét của bất kỳ nhân vật nào có hiệu lực, bạn có thể đánh ra một lá bài để thay thế nó.",
	zhuhai_info: "Khi giai đoạn kết thúc của một nhân vật khác bắt đầu, nếu nhân vật đó đã gây sát thương trong lượt này, bạn có thể sử dụng một lá 【Sát】 lên họ.",
	qianxin_info: "Giác tỉnh kỹ, sau khi bạn gây ra một lần sát thương, nếu bạn đã bị thương, bạn phải giảm 1 điểm giới hạn thể lực và nhận kỹ năng 〖Tiến Ngôn〗.",
	jianyan_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể tuyên bố một loại bài hoặc màu sắc, và lật lá bài đầu tiên trong chồng bài khớp với tuyên bố của bạn, sau đó bạn khiến một nhân vật nam nhận lá bài này.",
	rekurou_info: "Trong giai đoạn ra bài giới hạn một lần, bạn có thể bỏ một lá bài, sau đó mất 1 điểm thể lực.",
	zhaxiang_info: "Tỏa định kỹ. Sau khi bạn mất 1 điểm thể lực, bạn rút ba lá bài. Sau đó nếu lúc này là giai đoạn ra bài của bạn, bạn nhận được các hiệu ứng sau trong lượt này: Giới hạn số lần sử dụng 【Sát】 +1, sử dụng 【Sát】 màu đỏ không bị giới hạn khoảng cách và không thể bị đáp trả bởi 【Thiểm】.",
	qiaomeng_info: "Sau khi bạn sử dụng 【Sát】 màu đen gây sát thương cho một nhân vật, bạn có thể bỏ một lá bài trong khu trang bị của nhân vật đó, nếu lá này là Ngựa, bạn nhận lấy nó sau khi nó được đặt vào chồng bài bỏ.",
	reyicong_info: "Tỏa định kỹ, khoảng cách từ bạn đến các nhân vật khác -1. Nếu thể lực của bạn không lớn hơn 2, khoảng cách từ các nhân vật khác đến bạn +1.",
	refankui_info: "Mỗi khi bạn chịu 1 điểm sát thương, bạn có thể nhận một lá bài của nguồn sát thương.",
	retieji_info: "Sau khi bạn sử dụng 【Sát】 chỉ định một nhân vật làm mục tiêu, bạn có thể tiến hành một lần phán xét và khiến các kỹ năng phi tỏa định của nhân vật đó mất hiệu lực cho đến khi kết thúc lượt, trừ khi nhân vật đó bỏ một lá bài cùng chất với kết quả phán xét, nếu không không thể sử dụng 【Thiểm】 để triệt tiêu lá 【Sát】 này.",
	yijue_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể đấu điểm với một nhân vật khác, nếu bạn thắng, cho đến khi kết thúc lượt, nhân vật đó không thể sử dụng hoặc đánh ra bài tay và kỹ năng phi tỏa định mất hiệu lực, nếu bạn không thắng, bạn có thể khiến nhân vật đó hồi phục 1 điểm thể lực.",
	reyiji_info: "Mỗi khi bạn chịu 1 điểm sát thương, bạn có thể rút hai lá bài. Sau đó bạn có thể úp tối đa hai lá bài tay bên cạnh thẻ võ tướng của tối đa hai nhân vật, khi giai đoạn rút bài tiếp theo của các nhân vật này bắt đầu, họ nhận lấy các lá bài bên cạnh thẻ võ tướng đó.",
	rejianxiong_info: "Mỗi khi bạn chịu sát thương, bạn có thể nhận lá bài đã gây sát thương cho bạn, sau đó rút một lá bài.",
	reyajiao_info: "Mỗi khi bạn sử dụng hoặc đánh ra một lá bài tay ngoài lượt, bạn có thể lật một lá bài từ đỉnh chồng bài, nếu lá này cùng loại với lá bài bạn vừa sử dụng hoặc đánh ra, bạn có thể đưa nó cho bất kỳ nhân vật nào; nếu khác loại bạn có thể đặt nó vào chồng bài bỏ.",
	retishen_info: "Hạn định kỹ, khi giai đoạn chuẩn bị bắt đầu, bạn có thể hồi phục thể lực bằng với thể lực của bạn lúc kết thúc lượt trước, sau đó với mỗi điểm thể lực hồi phục theo cách này, bạn rút một lá bài.",
	reqianxun_info: "Mỗi khi một lá Cẩm nang trì hoãn hoặc một lá Cẩm nang thông thường do nhân vật khác sử dụng có hiệu lực, nếu bạn là mục tiêu duy nhất của lá bài này, bạn có thể đặt tất cả bài trên tay lên thẻ võ tướng của mình, nếu làm vậy, khi lượt này kết thúc, bạn nhận lại tất cả bài trên thẻ võ tướng.",
	relianying_info: "Khi bạn mất lá bài tay cuối cùng, bạn có thể khiến tối đa X nhân vật mỗi người rút một lá bài (X là số lượng bài tay bạn đã mất lần này).",
	reyingzi_info: "Tỏa định kỹ, khi rút bài trong giai đoạn rút bài, bạn rút thêm một lá bài; giới hạn bài trên tay của bạn là giới hạn thể lực của bạn.",
	refanjian_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể cho xem một lá bài tay và đưa lá này cho một nhân vật khác. Sau đó nhân vật đó chọn một: Cho xem bài tay của mình và bỏ tất cả các lá cùng chất với lá bài này, hoặc mất 1 điểm thể lực.",
	qingjian_info: "Mỗi khi bạn nhận được bài ngoài giai đoạn rút bài, bạn có thể đưa bất kỳ lá nào trong số đó cho nhân vật khác theo thứ tự tùy ý, mỗi lượt phát động tối đa bốn lần.",
	qinxue_info: "Giác tỉnh kỹ. Khi giai đoạn chuẩn bị hoặc giai đoạn kết thúc bắt đầu, nếu số bài trên tay trừ đi thể lực của bạn lớn hơn 1, bạn giảm 1 điểm giới hạn thể lực, hồi phục 1 điểm thể lực hoặc rút hai lá bài, nhận kỹ năng 〖Công Tâm〗.",
	retuxi_info: "Khi rút bài trong giai đoạn rút bài, bạn có thể rút ít đi bất kỳ số lượng lá nào, sau đó chọn số lượng nhân vật khác có số bài tay lớn hơn hoặc bằng bạn tương ứng, nhận một lá bài tay của mỗi nhân vật đó.",
	reluoyi_info: "Bạn có thể bỏ qua giai đoạn rút bài, sau đó lật ba lá bài từ đỉnh chồng bài, nhận các lá Cơ bản, Vũ khí và 【Quyết Đấu】 trong số đó, nếu làm vậy, cho đến khi lượt tiếp theo của bạn bắt đầu, sát thương gây ra bởi 【Sát】 hoặc 【Quyết Đấu】 mà bạn là nguồn sát thương +1.",
	reganglie_info: "Sau khi bạn chịu 1 điểm sát thương, bạn có thể tiến hành phán xét, nếu kết quả là: Đỏ, bạn gây cho nguồn sát thương 1 điểm sát thương; Đen, bạn bỏ một lá bài của nguồn sát thương.",
	reganglie_info_guozhan: "Sau khi bạn chịu sát thương, bạn có thể tiến hành phán xét, nếu kết quả là: Đỏ, bạn gây cho nguồn sát thương 1 điểm sát thương; Đen, bạn bỏ một lá bài của nguồn sát thương.",
	botu: "Bác Đồ",
	botu_info: "Khi kết thúc lượt, nếu các lá bài bạn đã sử dụng trong giai đoạn ra bài lượt này bao gồm bốn loại chất, bạn có thể thực hiện một lượt bổ sung.",
	rebotu: "Bác Đồ",
	rebotu_info: "Mỗi vòng giới hạn X lần. Khi kết thúc lượt, nếu trong số các lá bài đi vào chồng bài bỏ trong lượt này bao gồm ít nhất bốn loại chất, bạn có thể nhận được một lượt bổ sung. (X là số nhân vật còn sống và tối đa là 3)",

	xin_yuji: "Giới Vu Cát",
	xin_yuji_prefix: "Giới",
	re_zuoci: "Giới Tả Từ",
	re_zuoci_prefix: "Giới",
	reguhuo: "Cổ Hoặc",
	reguhuo_info: "Mỗi lượt của mỗi nhân vật giới hạn một lần, bạn có thể úp một lá bài tay xem như sử dụng hoặc đánh ra một lá bài Cơ bản hoặc Cẩm nang thông thường. Các nhân vật khác đồng thời chọn có nghi ngờ hay không. Sau đó, bạn cho xem lá bài này. Nếu có nhân vật nghi ngờ: Nếu lá bài này là giả, lá bài này bị hủy bỏ, và tất cả những người nghi ngờ mỗi người rút một lá bài; nếu là thật, tất cả những người nghi ngờ sau khi lá bài này kết thúc quyết toán sẽ lần lượt bỏ một lá bài hoặc mất 1 điểm thể lực, và nhận kỹ năng 〖Triền Oán〗.",
	rechanyuan: "Triền Oán",
	rechanyuan_info: "Tỏa định kỹ, bạn không thể nghi ngờ trong quá trình quyết toán của 〖Cổ Hoặc〗. Khi thể lực của bạn không lớn hơn 1, các kỹ năng khác của bạn mất hiệu lực.",
	reguhuo_ally: "Tin tưởng",
	reguhuo_betray: "Nghi ngờ",
	reguhuo_ally_bg: "Thật",
	reguhuo_betray_bg: "Giả",
	rehuashen: "Hóa Thân",
	rehuashen_info: "Khi trò chơi bắt đầu, bạn nhận ngẫu nhiên ba thẻ võ tướng chưa gia nhập trò chơi, chọn một thẻ đặt trước mặt và tuyên bố một kỹ năng của thẻ đó, bạn sở hữu kỹ năng đó đồng thời thay đổi giới tính và phe phái giống với võ tướng đó cho đến khi hóa thân bị thay thế. Khi giai đoạn bắt đầu hoặc kết thúc lượt, bạn có thể chọn một: ① Bỏ tối đa hai thẻ hóa thân chưa cho xem và nhận lại số lượng thẻ hóa thân tương ứng; ② Thay đổi thẻ hóa thân hoặc kỹ năng đang hiển thị. (Bạn không thể tuyên bố các kỹ năng đặc biệt như Hạn định kỹ, Giác tỉnh kỹ, Ẩn nặc kỹ, Sứ mệnh kỹ, Chủ công kỹ).",
	rexinsheng: "Tân Sinh",
	rexinsheng_info: "Sau khi chịu 1 điểm sát thương, bạn có thể nhận một thẻ hóa thân mới.",
	re_menghuo: "Giới Mạnh Hoạch",
	re_menghuo_prefix: "Giới",
	re_caopi: "Giới Tào Phi",
	re_caopi_prefix: "Giới",
	oljiuchi: "Tửu Trì",
	oljiuchi_info: "Bạn có thể dùng một lá bài tay chất Bích xem như sử dụng 【Tửu】. Bạn sử dụng 【Tửu】 không giới hạn số lần, và khi bạn sử dụng 【Sát】 có hiệu ứng của 【Tửu】 gây sát thương trong lượt của mình, bạn khiến 〖Băng Hoại〗 của mình mất hiệu lực cho đến khi kết thúc lượt.",
	repolu: "Phá Lỗ",
	repolu_info: "Khi bạn giết một nhân vật/tử vong, bạn có thể khiến bất kỳ số lượng nhân vật nào rút X+1 lá bài. (X là số lần bạn đã phát động 〖Phá Lỗ〗 trước đó)",
	rexingshang: "Hạnh Thương",
	rexingshang_info: "Sau khi nhân vật khác tử vong, bạn có thể chọn một: Hồi phục 1 điểm thể lực, hoặc nhận tất cả bài của họ.",
	refangzhu: "Phóng Trục",
	refangzhu_info: "Sau khi chịu sát thương, bạn có thể khiến một nhân vật khác chọn một: Rút X lá bài và lật mặt thẻ võ tướng, hoặc bỏ X lá bài và mất 1 điểm thể lực. (X là số thể lực bạn đã mất)",
	rezaiqi: "Tái Khởi",
	rezaiqi_info: "Giai đoạn kết thúc, bạn có thể khiến tối đa X nhân vật chọn một: 1. Rút một lá bài, 2. Khiến bạn hồi phục 1 điểm thể lực (X là số lá bài màu đỏ đã đi vào chồng bài bỏ trong lượt này).",
	ol_caiwenji: "Giới Thái Diễm",
	ol_caiwenji_prefix: "Giới",
	retuntian: "Truân Điền",
	rebeige: "Bi Ca",
	retuntian_info: "① Khi bạn mất bài ngoài lượt, bạn có thể phán xét. Nếu kết quả phán xét là ♥, bạn nhận lá bài phán xét này. Nếu không bạn đặt lá bài này lên thẻ võ tướng, gọi là “Điền”. ② Khoảng cách từ bạn đến các nhân vật khác -X (X là số lượng “Điền” trên thẻ võ tướng của bạn).",
	rebeige_info: "Khi có nhân vật chịu sát thương từ 【Sát】, bạn có thể bỏ một lá bài, và khiến họ tiến hành một lần phán xét, nếu kết quả phán xét là: ♥ nhân vật đó hồi phục X điểm thể lực (X là điểm sát thương); ♦ nhân vật đó rút ba lá bài; ♣ nguồn sát thương bỏ hai lá bài; ♠ nguồn sát thương lật mặt thẻ võ tướng.",
	rehunzi: "Hồn Tư",
	rehunzi_info: "Giác tỉnh kỹ, giai đoạn chuẩn bị, nếu thể lực của bạn không lớn hơn 2, bạn giảm 1 điểm giới hạn thể lực, và nhận kỹ năng 〖Anh Tư〗 và 〖Anh Hồn〗.",
	rezhijian: "Trực Gián",
	rezhijian_info: "Giai đoạn ra bài, bạn có thể đặt một lá trang bị từ trên tay vào khu trang bị của một nhân vật khác (không được thay thế trang bị cũ), sau đó rút một lá bài. Khi bạn sử dụng lá trang bị, bạn có thể rút một lá bài.",
	refangquan: "Phóng Quyền",
	refangquan_info: "Bạn có thể bỏ qua giai đoạn ra bài, nếu làm vậy, giới hạn bài tay của bạn trong lượt này là giới hạn thể lực, và khi kết thúc lượt, bạn có thể bỏ một lá bài tay và khiến một nhân vật khác thực hiện một lượt bổ sung.",
	xin_gaoshun: "Giới Cao Thuận",
	xin_gaoshun_prefix: "Giới",
	repojun: "Phá Quân",
	repojun2: "Phá Quân",
	repojun3: "Phá Quân",
	repojun_info: "Sau khi bạn sử dụng 【Sát】 chỉ định mục tiêu, bạn có thể đặt tối đa X lá bài của họ lên thẻ võ tướng của họ (X là thể lực của họ), sau đó họ nhận lại các lá bài này khi lượt hiện tại kết thúc. Khi bạn sử dụng 【Sát】 gây sát thương cho một nhân vật, nếu số bài tay và số bài trong khu trang bị của nhân vật đó đều không lớn hơn bạn, sát thương này +1.",
	rexianzhen: "Hãm Trận",
	rexianzhen_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể đấu điểm với một nhân vật khác. Nếu bạn thắng, trong lượt này bạn sử dụng bài lên họ không bị giới hạn số lần và khoảng cách đồng thời phớt lờ phòng cụ của họ. Nếu bạn không thắng, bạn không thể sử dụng 【Sát】 trong lượt này. Nếu lá bài đấu điểm bạn mất theo cách này là 【Sát】, lá 【Sát】 của bạn không tính vào giới hạn bài tay lượt này.",
	rejinjiu: "Cấm Tửu",
	rejinjiu_info: "Tỏa định kỹ, các lá 【Tửu】 của bạn đều xem như 【Sát】. Nhân vật khác không thể sử dụng 【Tửu】 trong lượt của bạn. Khi bạn chịu sát thương từ 【Tửu Sát】, bạn khiến sát thương này -X (X là số lượng 【Tửu】 đã ảnh hưởng đến giá trị sát thương của lá 【Sát】 này).",
	rejinjiu2: "Cấm Tửu",
	rejinjiu3: "Cấm Tửu",
	ol_xiahouyuan: "Giới Hạ Hầu Uyên",
	ol_xiahouyuan_prefix: "Giới",
	shebian: "Thiết Biến",
	shebian_info: "Sau khi thẻ võ tướng của bạn bị lật mặt, bạn có thể di chuyển một lá trang bị trên sân.",
	cangzhuo: "Tàng Chuyết",
	cangzhuo_info: "Khi giai đoạn bỏ bài bắt đầu, nếu bạn chưa sử dụng lá Cẩm nang nào trong lượt này, các lá Cẩm nang của bạn không tính vào giới hạn bài tay.",
	re_zhangyi: "Giới Trương Nghị",
	re_zhangyi_prefix: "Giới",
	rewurong: "Vũ Nhung",
	rewurong_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể khiến một nhân vật khác cùng bạn đồng thời cho xem một lá bài tay: Nếu bạn cho xem là 【Sát】 và nhân vật đó cho xem không phải 【Thiểm】, bạn gây cho họ 1 điểm sát thương; nếu bạn cho xem không phải 【Sát】 và nhân vật đó cho xem là 【Thiểm】, bạn nhận một lá bài của họ.",
	ol_pangtong: "Giới Bàng Thống",
	ol_pangtong_prefix: "Giới",
	olniepan: "Niết Bàn",
	olniepan_info: "Hạn định kỹ, khi bạn đang ở trạng thái hấp hối, bạn có thể bỏ tất cả bài trong các khu vực của mình và phục nguyên thẻ võ tướng, sau đó rút ba lá bài và hồi phục thể lực về 3 điểm. Sau đó bạn chọn nhận một trong các kỹ năng sau: 〖Bát Trận〗/〖Hỏa Kế〗/〖Khán Phá〗.",
	ol_weiyan: "Giới Ngụy Diên",
	ol_weiyan_prefix: "Giới",
	reqimou: "Kỳ Mưu",
	reqimou_info: "Hạn định kỹ, giai đoạn ra bài, bạn có thể mất bất kỳ số điểm thể lực nào và rút lượng bài tương ứng, sau đó cho đến khi kết thúc lượt, khoảng cách từ bạn đến các nhân vật khác -X, và bạn có thể sử dụng thêm X lá 【Sát】 (X là số điểm thể lực bạn đã mất).",
	ol_xiaoqiao: "Giới Tiểu Kiều",
	ol_xiaoqiao_prefix: "Giới",
	rehongyan: "Hồng Nhan",
	rehongyan_info: "Tỏa định kỹ, các lá bài Bích và lá bài phán xét Bích trong khu vực của bạn đều xem như Cơ. Khi bạn mất lá bài Cơ đang ngửa ngoài lượt, nếu số bài trên tay nhỏ hơn thể lực, bạn rút một lá bài.",
	reluoying: "Lạc Anh",
	reluoying_discard: "Lạc Anh",
	reluoying_judge: "Lạc Anh",
	reluoying_info: "Khi các lá bài Nhép của nhân vật khác đi vào chồng bài bỏ do bị bỏ hoặc phán xét, bạn có thể nhận lấy chúng.",
	rejiushi: "Tửu Thi",
	rejiushi_info: "Khi bạn cần sử dụng 【Tửu】, nếu thẻ võ tướng của bạn đang mặt ngửa, bạn có thể lật mặt thẻ, xem như sử dụng một lá 【Tửu】. Sau khi bạn chịu sát thương, nếu thẻ võ tướng của bạn đang mặt úp và bạn chưa phát động 〖Tửu Thi〗 vì lần sát thương này, bạn có thể lật mặt thẻ và nhận ngẫu nhiên một lá Cẩm nang từ chồng bài.",
	rejiushi1: "Tửu Thi",
	rejiushi3: "Tửu Thi",
	rejiushi_mark: "Tửu Thi·Cải",
	rejiushi_mark_info: "Khi bạn cần sử dụng 【Tửu】, nếu thẻ võ tướng của bạn đang mặt ngửa, bạn có thể lật mặt thẻ, xem như sử dụng một lá 【Tửu】. Sau khi bạn chịu sát thương, nếu thẻ võ tướng của bạn đang mặt úp và bạn chưa phát động 〖Tửu Thi〗 vì lần sát thương này, bạn có thể lật mặt thẻ. Khi bạn lật mặt thẻ, bạn nhận ngẫu nhiên một lá Cẩm nang từ chồng bài.",
	chengzhang: "Thành Chương",
	chengzhang_info: "Giác tỉnh kỹ, khi giai đoạn chuẩn bị bắt đầu, nếu tổng sát thương bạn gây ra và chịu vào đạt tích lũy 7 điểm trở lên, bạn hồi phục 1 điểm thể lực và rút một lá bài, sau đó viết lại 〖Tửu Thi〗.",
	re_wuyi: "Giới Ngô Ý",
	re_wuyi_prefix: "Giới",
	re_zhuran: "Giới Chu Nhiên",
	re_zhuran_prefix: "Giới",
	re_quancong: "Giới Toàn Tung",
	re_quancong_prefix: "Giới",
	re_liaohua: "Giới Liêu Hóa",
	re_liaohua_prefix: "Giới",
	re_guohuai: "Giới Quách Hoài",
	re_guohuai_prefix: "Giới",
	re_chengpu: "Giới Trình Phổ",
	re_chengpu_prefix: "Giới",
	rechunlao: "Thuần Lao",
	rechunlao2: "Thuần Lao",
	rechunlao_info: "Khi giai đoạn ra bài kết thúc, nếu bạn không có “Thuần”, bạn có thể đặt ít nhất một lá 【Sát】 lên thẻ võ tướng, gọi là “Thuần”. Khi một nhân vật ở trạng thái hấp hối, bạn có thể xóa một lá “Thuần”, xem như nhân vật đó sử dụng một lá 【Tửu】, sau đó nếu thuộc tính của lá “Thuần” này là: Hỏa, bạn hồi 1 điểm thể lực; Lôi, bạn rút hai lá bài.",
	re_caozhang: "Giới Tào Chương",
	re_caozhang_prefix: "Giới",
	yujin_yujin: "Giới Vu Cấm",
	yujin_yujin_prefix: "Giới",
	rexuanfeng: "Toàn Phong",
	rexuanfeng_info: `Khi bạn mất bài trong khu trang bị, hoặc bỏ từ hai lá bài tay trở lên trong giai đoạn bỏ bài, bạn có thể chọn một: 1. Lần lượt bỏ tổng cộng hai lá bài của một đến hai nhân vật khác; 2. Di chuyển một lá bài trong khu trang bị của một nhân vật khác sang khu trang bị của một nhân vật khác nữa. ${get.poptip("rule_beishui")}: Phế bỏ một ô trang bị của bạn.`,
	reyongjin: "Dũng Tiến",
	reyongjin_info: "Khi giai đoạn bạn từng mất bài kết thúc, bạn có thể xem như sử dụng một lá 【Sát】 không giới hạn khoảng cách lên bất kỳ số lượng nhân vật nào có số bài mất trong giai đoạn này bằng với bạn. Sau khi lá 【Sát】 này gây sát thương, bạn ngẫu nhiên khôi phục một ô trang bị (nếu chưa phế bỏ ô nào thì đổi thành đặt một lá trang bị từ chồng bài bỏ vào ô trang bị trống của bạn).",
	olpaoxiao: "Bào Hiếu",
	olpaoxiao2: "Bào Hiếu",
	olpaoxiao_info: "① Tỏa định kỹ, bạn sử dụng 【Sát】 không giới hạn số lần. ② Tỏa định kỹ, khi 【Sát】 bạn sử dụng bị triệt tiêu bởi 【Thiểm】, bạn nhận một dấu ấn “Bào” (→) Khi bạn gây sát thương bằng 【Sát】, bạn bỏ tất cả “Bào” và khiến sát thương +X (X là số “Bào”). Sau khi kết thúc lượt, bạn bỏ tất cả “Bào”.",
	oltishen: "Thế Thân",
	oltishen_info: "Hạn định kỹ, giai đoạn chuẩn bị, bạn có thể hồi phục thể lực về giới hạn, sau đó rút X lá bài (X là số điểm thể lực bạn đã hồi phục).",
	ollongdan: "Long Đảm",
	ollongdan_info: "Bạn có thể dùng một lá 【Sát】 xem như 【Thiểm】, 【Thiểm】 xem như 【Sát】, 【Tửu】 xem như 【Đào】, 【Đào】 xem như 【Tửu】 để sử dụng hoặc đánh ra.",
	olyajiao: "Nha Giác",
	olyajiao_info: "Khi bạn mất bài tay do sử dụng hoặc đánh ra ngoài lượt, bạn có thể lật một lá bài từ đỉnh chồng bài. Nếu hai lá này cùng loại, bạn có thể đưa lá bài đã lật cho một nhân vật; nếu khác loại, bạn có thể bỏ một lá bài trong khu vực của nhân vật có phạm vi tấn công bao hàm bạn.",
	regongji: "Cung Kỵ",
	regongji_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ một lá bài không phải Cơ bản, sau đó bỏ một lá bài của nhân vật khác. Tỏa định kỹ, khi trong khu trang bị của bạn có Ngựa, phạm vi tấn công của bạn là vô hạn.",
	ol_sunjian: "Giới Tôn Kiên",
	ol_sunjian_prefix: "Giới",
	wulie: "Võ Liệt",
	wulie2: "Võ Liệt",
	wulie_info: "Hạn định kỹ, giai đoạn kết thúc, bạn có thể mất bất kỳ số điểm thể lực nào và chỉ định số lượng nhân vật khác tương ứng. Những nhân vật này mỗi người nhận một dấu ấn 「Liệt」. Khi nhân vật có 「Liệt」 chịu sát thương, họ xóa một dấu ấn 「Liệt」, sau đó ngăn chặn sát thương này.",
	re_sunluban: "Giới Tôn Lỗ Ban",
	re_sunluban_prefix: "Giới",
	re_masu: "Giới Mã Tắc",
	re_masu_prefix: "Giới",
	ol_pangde: "Giới Bàng Đức",
	ol_pangde_prefix: "Giới",
	rejianchu: "Kiện Xuất",
	rejianchu_info: "Sau khi bạn sử dụng 【Sát】 chỉ định một nhân vật làm mục tiêu, bạn có thể bỏ một lá bài của họ, nếu lá bài bị bỏ theo cách này không phải Cơ bản, lá 【Sát】 này không thể bị đáp trả bởi 【Thiểm】 và giới hạn số lần sử dụng 【Sát】 của bạn trong lượt này +1, nếu là Cơ bản, nhân vật đó nhận lấy lá 【Sát】 này.",
	re_taishici: "Giới Thái Sử Từ",
	re_taishici_prefix: "Giới",
	hanzhan: "Hàm Chiến",
	hanzhan_gain: "Hàm Chiến",
	hanzhan_info: "① Khi bạn khởi xướng đấu điểm, hoặc trở thành mục tiêu đấu điểm, bạn có thể khiến đối phương đổi cách chọn bài đấu điểm thành chọn ngẫu nhiên một lá bài tay. ② Sau khi bạn kết thúc đấu điểm, bạn có thể nhận lá 【Sát】 có điểm số lớn nhất trong số các lá bài đấu điểm lần này.",
	re_jianyong: "Giới Giản Ung",
	re_jianyong_prefix: "Giới",
	xin_xusheng: "Giới Từ Thịnh",
	xin_xusheng_prefix: "Giới",
	decadepojun: "Phá Quân",
	decadepojun2: "Phá Quân",
	decadepojun_info: "Sau khi bạn sử dụng 【Sát】 chỉ định mục tiêu, bạn có thể đặt tối đa X lá bài của họ lên thẻ võ tướng của họ (X là thể lực của họ). Trong số những lá bài này nếu: có trang bị, bạn đặt một lá trong số các trang bị đó vào chồng bài bỏ; có Cẩm nang, bạn rút một lá bài. Họ nhận lại các lá trên thẻ võ tướng khi kết thúc lượt.",
	re_wangyi: "Giới Vương Dị",
	re_wangyi_prefix: "Giới",
	guanzhang: "Quan Hưng Trương Bào",
	rezishou: "Tự Thủ",
	rezishou2: "Tự Thủ",
	rezishou_info: "Giai đoạn rút bài, bạn có thể rút thêm X lá bài (X là số phe phái còn sống). Nếu làm vậy, lượt này khi bạn gây sát thương cho nhân vật khác, ngăn chặn sát thương này.",
	rezongshi: "Tông Thất",
	rezongshi_info: "Tỏa định kỹ, giới hạn bài tay của bạn +X (X là số phe phái còn sống). Giai đoạn chuẩn bị, nếu số bài tay của bạn lớn hơn thể lực, bạn sử dụng 【Sát】 không giới hạn số lần trong lượt này.",
	ol_dongzhuo: "Giới Đổng Trác",
	ol_dongzhuo_prefix: "Giới",
	olbaonue: "Bạo Ngược",
	olbaonue_info: "Chủ công kỹ, sau khi nhân vật phe Quần khác gây 1 điểm sát thương, bạn có thể tiến hành phán xét, nếu là ♠, bạn hồi 1 điểm thể lực và nhận lá bài phán xét.",
	re_panzhangmazhong: "Giới Phan Chương Mã Trung",
	re_panzhangmazhong_prefix: "Giới",
	re_hanhaoshihuan: "Giới Hàn Hạo Sử Hoán",
	re_hanhaoshihuan_prefix: "Giới",
	xinyicong: "Nghĩa Tòng",
	xinyicong_info: "Tỏa định kỹ, khoảng cách từ bạn đến các nhân vật khác -X, khoảng cách từ các nhân vật khác đến bạn +Y. (X là thể lực hiện tại -1, Y là thể lực đã mất -1)",
	oltianxiang: "Thiên Hương",
	oltianxiang_info: "Khi bạn chịu sát thương, bạn có thể bỏ một lá bài Cơ, ngăn chặn sát thương này và chọn một nhân vật khác, sau đó bạn chọn một: 1. Khiến họ chịu 1 điểm sát thương từ nguồn sát thương gây ra cho họ, sau đó rút X lá bài (X là thể lực đã mất của họ và tối đa là 5); 2. Khiến họ mất 1 điểm thể lực, sau đó nhận lá bài bạn đã bỏ.",
	olhongyan: "Hồng Nhan",
	olhongyan_info: "Tỏa định kỹ, chất các lá bài Bích của bạn được xem là Cơ. Nếu trong khu trang bị của bạn có bài Cơ, giới hạn bài tay cơ bản của bạn được tính theo giới hạn thể lực.",
	piaoling: "Phiêu Linh",
	piaoling_info: "Giai đoạn kết thúc, bạn có thể tiến hành phán xét. Nếu kết quả phán xét là Cơ, bạn chọn một: 1. Đưa lá bài này cho một nhân vật. Nếu bạn đưa cho chính mình, bạn bỏ một lá bài. 2. Đặt lá bài này lên đỉnh chồng bài.",
	decadelihuo: "Lệ Hỏa",
	decadelihuo2: "Lệ Hỏa",
	decadelihuo3: "Lệ Hỏa",
	decadelihuo_info: "Sau khi bạn tuyên bố sử dụng 【Sát】 thường, bạn có thể đổi lá 【Sát】 này thành 【Hỏa Sát】. Khi bạn sử dụng 【Hỏa Sát】 chọn mục tiêu, có thể chọn thêm một mục tiêu bổ sung. Sau khi lá 【Hỏa Sát】 bạn sử dụng kết thúc quyết toán, nếu số mục tiêu của lá 【Sát】 này lớn hơn 1 và bạn đã gây sát thương từ lá 【Sát】 này, bạn mất 1 điểm thể lực.",
	decadechunlao: "Thuần Lao",
	decadechunlao2: "Thuần Lao",
	decadechunlao_info: "Bạn có thể sử dụng 【Tửu (cách dùng ②)】 lên nhân vật khác. Khi bạn cần sử dụng 【Tửu】, nếu thẻ võ tướng chưa bị xoay ngang, bạn có thể xoay ngang thẻ võ tướng, sau đó xem như sử dụng 【Tửu】. Sau khi bạn chịu hoặc gây sát thương, nếu điểm sát thương lớn hơn 1 và thẻ võ tướng đang bị xoay ngang, bạn có thể phục nguyên thẻ võ tướng.",
	rejuece: "Tuyệt Sách",
	rejuece_info: "Giai đoạn kết thúc, bạn có thể gây 1 điểm sát thương cho một nhân vật đã mất bài trong lượt này.",
	remieji: "Diệt Kế",
	remieji_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể đặt một lá Cẩm nang màu đen lên đỉnh chồng bài, sau đó khiến một nhân vật khác có bài chọn một: Đưa cho bạn một lá Cẩm nang, hoặc lần lượt bỏ hai lá không phải Cẩm nang.",
	re_manchong: "Giới Mãn Sủng",
	re_manchong_prefix: "Giới",
	rejunxing: "Tuấn Hình",
	rejunxing_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ bất kỳ số lượng lá bài tay nào và chọn một nhân vật khác. Nhân vật đó chọn một: 1. Bỏ X lá bài và mất 1 điểm thể lực. 2. Lật mặt thẻ võ tướng và rút X lá bài. (X là số bài bạn đã bỏ)",
	re_gongsunzan: "Giới Công Tôn Toản",
	re_gongsunzan_prefix: "Giới",
	reqiaomeng: "Kiêu Mãnh",
	reqiaomeng_info: "Sau khi bạn sử dụng 【Sát】 gây sát thương cho một nhân vật, bạn có thể bỏ một lá bài trong khu vực của nhân vật đó. Nếu lá này là Ngựa, bạn nhận lấy nó sau khi sự kiện bỏ bài này kết thúc quyết toán.",
	ol_dengai: "Giới Đặng Ngải",
	ol_dengai_prefix: "Giới",
	oltuntian: "Truân Điền",
	olzaoxian: "Tạc Hiểm",
	oltuntian_info: "① Khi bạn mất bài ngoài lượt, hoặc mất 【Sát】 do bị bỏ trong lượt, bạn có thể phán xét. Nếu kết quả không phải ♥, bạn đặt lá bài này lên thẻ võ tướng, gọi là “Điền”. ② Khoảng cách từ bạn đến nhân vật khác -X (X là số “Điền”).",
	olzaoxian_info: "Giác tỉnh kỹ, giai đoạn chuẩn bị, nếu bạn có ít nhất ba lá “Điền”, bạn giảm 1 điểm giới hạn thể lực, và nhận kỹ năng 〖Cấp Kích〗. Bạn thực hiện một lượt bổ sung sau khi lượt hiện tại kết thúc.",
	re_sunxiu: "Giới Tôn Hưu",
	re_sunxiu_prefix: "Giới",
	re_caoxiu: "Giới Tào Hưu",
	re_caoxiu_prefix: "Giới",
	xin_lingtong: "Giới Lăng Thống",
	xin_lingtong_prefix: "Giới",
	decadexuanfeng: "Toàn Phong",
	decadexuanfeng_info: "Khi bạn bỏ ít nhất hai lá bài trong giai đoạn bỏ bài, hoặc khi bạn mất bài trong khu trang bị, nếu trên sân không có nhân vật nào ở trạng thái hấp hối, bạn có thể bỏ tổng cộng hai lá bài của tối đa hai nhân vật khác. Nếu lúc này đang trong lượt của bạn, bạn có thể gây 1 điểm sát thương cho một trong các nhân vật mục tiêu đó.",
	yongjin: "Dũng Tiến",
	yongjin_info: "Hạn định kỹ, giai đoạn ra bài, bạn có thể lần lượt di chuyển tối đa ba lá trang bị khác nhau trên sân.",
	xin_liubiao: "Giới Lưu Biểu",
	xin_liubiao_prefix: "Giới",
	decadezishou: "Tự Thủ",
	decadezishou_zhiheng: "Tự Thủ",
	decadezishou_info: "Giai đoạn rút bài, bạn có thể rút thêm X lá bài (X là số phe phái còn sống); sau đó lượt này khi bạn gây sát thương cho nhân vật khác, ngăn chặn sát thương này. Giai đoạn kết thúc, nếu lượt này bạn không sử dụng bài chỉ định nhân vật khác làm mục tiêu, bạn có thể bỏ bất kỳ số lượng lá bài tay khác chất, sau đó rút lượng bài tương ứng.",
	decadezongshi: "Tông Thất",
	decadezongshi_info: "Tỏa định kỹ, giới hạn bài tay của bạn +X (X là số phe phái còn sống). Ngoài lượt của bạn, nếu số bài trên tay lớn hơn hoặc bằng giới hạn bài tay, khi bạn trở thành mục tiêu của Cẩm nang trì hoãn hoặc bài không màu, bạn khiến lá bài này vô hiệu đối với bạn.",
	re_fazheng: "Giới Pháp Chính",
	re_fazheng_prefix: "Giới",
	reenyuan: "Ân Oán",
	reenyuan1: "Ân Oán",
	reenyuan2: "Ân Oán",
	reenyuan_info: "Sau khi bạn nhận được ít nhất hai lá bài của một nhân vật khác, bạn có thể khiến họ rút một lá bài. Sau khi chịu 1 điểm sát thương, bạn có thể khiến nguồn sát thương chọn một: ① Mất 1 điểm thể lực. ② Đưa cho bạn một lá bài tay. Nếu lá này không phải ♥, bạn rút một lá bài.",
	rexuanhuo: "Huyễn Hoặc",
	rexuanhuo_info: "Khi giai đoạn rút bài kết thúc, bạn có thể đưa cho một nhân vật khác hai lá bài tay, sau đó nhân vật đó chọn một: 1. Xem như sử dụng bất kỳ loại 【Sát】 hoặc 【Quyết Đấu】 nào lên một nhân vật khác do bạn chọn, 2. Đưa cho bạn tất cả bài trên tay.",
	re_fuhuanghou: "Giới Phục Hoàng Hậu",
	re_fuhuanghou_prefix: "Giới",
	reqiuyuan: "Cầu Viện",
	reqiuyuan_info: "Khi bạn trở thành mục tiêu của 【Sát】, bạn có thể chọn một nhân vật khác. Trừ khi nhân vật đó đưa cho bạn một lá bài Cơ bản không phải 【Sát】, nếu không họ cũng trở thành mục tiêu của lá 【Sát】 này và nhân vật đó không thể đáp trả lá 【Sát】 này.",
	rezhuikong: "Trụy Khủng",
	rezhuikong_info: "Khi lượt của nhân vật khác bắt đầu, nếu bạn đã bị thương, bạn có thể đấu điểm với họ: Nếu bạn thắng, lượt này nhân vật đó chỉ có thể sử dụng bài lên chính mình; nếu bạn không thắng, bạn nhận lá bài đấu điểm của họ, sau đó họ xem như sử dụng một lá 【Sát】 lên bạn.",
	re_gongsunyuan: "Giới Công Tôn Uyên",
	re_gongsunyuan_prefix: "Giới",
	rehuaiyi: "Hoài Dị",
	rehuaiyi_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể cho xem tất cả bài trên tay, nếu màu sắc của những lá bài này: Tất cả giống nhau, bạn rút một lá bài, và đổi kỹ năng này thành “giới hạn hai lần” trong giai đoạn này, sau đó chấm dứt quyết toán kỹ năng; không tất cả giống nhau, bạn chọn một màu sắc và bỏ tất cả bài tay màu đó, sau đó bạn có thể nhận tối đa X lá bài của mỗi nhân vật (X là số bài tay bạn đã bỏ theo cách này). Nếu bạn nhận được không ít hơn hai lá bài theo cách này, bạn mất 1 điểm thể lực.",
	re_caozhen: "Giới Tào Chân",
	re_caozhen_prefix: "Giới",
	residi: "Ty Địch",
	residi_push: "Ty Địch",
	residi2: "Ty Địch",
	residi3: "Ty Địch",
	residi_info: "Giai đoạn kết thúc, bạn có thể đặt một lá không phải Cơ bản lên thẻ võ tướng, gọi là “Ty”. Khi giai đoạn ra bài của nhân vật khác bắt đầu, bạn có thể xóa một lá “Ty”. Nếu làm vậy, trong giai đoạn này họ không thể sử dụng hoặc đánh ra bài cùng màu với “Ty”. Khi giai đoạn này kết thúc, nếu họ chưa từng sử dụng: 【Sát】, bạn xem như sử dụng một lá 【Sát】 lên họ. Cẩm nang, bạn rút hai lá bài.",
	gz_re_xushu: "Từ Thứ",
	re_zhangchunhua: "Giới Trương Xuân Hoa",
	re_zhangchunhua_prefix: "Giới",
	xin_handang: "Giới Hàn Đương",
	xin_handang_prefix: "Giới",
	xingongji: "Cung Kỵ",
	xingongji2: "Cung Kỵ",
	xingongji_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ một lá bài, sau đó phạm vi tấn công của bạn được xem là vô hạn và sử dụng 【Sát】 cùng chất với lá bài này không giới hạn số lần cho đến khi kết thúc lượt. Nếu lá bài bạn bỏ theo cách này là trang bị, bạn có thể bỏ một lá bài của nhân vật khác.",
	xinjiefan: "Giải Phiền",
	xinjiefan_info: "Hạn định kỹ, giai đoạn ra bài, bạn có thể chọn một nhân vật, khiến tất cả nhân vật có phạm vi tấn công bao hàm nhân vật đó lần lượt chọn một: 1. Bỏ một lá trang bị Vũ khí; 2. Khiến họ rút một lá bài. Sau đó nếu số vòng trò chơi là 1, bạn khôi phục kỹ năng này khi lượt kết thúc.",
	gzquanji: "Quyền Kế",
	gzquanji_info: "Mỗi lượt mỗi hạng mục giới hạn một lần. Sau khi bạn chịu sát thương hoặc gây sát thương, bạn có thể rút một lá bài, sau đó đặt một lá bài lên thẻ võ tướng, gọi là “Quyền”; giới hạn bài trên tay của bạn +X (X là số lượng “Quyền”).",
	gzpaiyi: "Bài Dị",
	gzpaiyi_backup: "Bài Dị",
	gzpaiyi_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể xóa một lá “Quyền” và chọn một nhân vật. Khiến họ rút X lá bài (X là số “Quyền” của bạn và tối đa là 7). Sau đó nếu số bài tay của họ lớn hơn bạn, bạn gây cho họ 1 điểm sát thương.",
	ol_zhurong: "Giới Chúc Dung",
	ol_zhurong_prefix: "Giới",
	changbiao: "Trường Tiêu",
	changbiao_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể dùng bất kỳ số lượng lá bài tay nào xem như sử dụng 【Sát】 (không giới hạn khoảng cách). Nếu bạn gây sát thương lên nhân vật mục tiêu bằng lá 【Sát】 này, bạn rút X lá bài khi kết thúc giai đoạn ra bài (X là số lượng lá bài thực thể tương ứng với lá 【Sát】 này).",
	re_zhoucang: "Giới Chu Thương",
	re_zhoucang_prefix: "Giới",
	rezhongyong: "Trung Dũng",
	rezhongyong_info: "Sau khi bạn sử dụng 【Sát】, bạn có thể đưa lá 【Sát】 này cùng với lá 【Thiểm】 mà nhân vật mục tiêu đã sử dụng cho một nhân vật khác, nếu trong số bài họ nhận được có màu đỏ, họ có thể sử dụng một lá 【Sát】 lên nhân vật trong phạm vi tấn công của bạn. Nếu bài họ nhận được có màu đen, họ rút một lá bài.",
	ollihuo: "Lệ Hỏa",
	ollihuo2: "Lệ Hỏa",
	ollihuo3: "Lệ Hỏa",
	ollihuo4: "Lệ Hỏa",
	ollihuo_info: "Bạn sử dụng 【Sát】 thường có thể đổi thành 【Hỏa Sát】, nếu lá 【Sát】 này gây sát thương, bạn mất 1 điểm thể lực; bạn sử dụng 【Hỏa Sát】 có thể chọn thêm một mục tiêu. Nếu lá bài đầu tiên bạn sử dụng mỗi lượt là 【Sát】, sau khi lá 【Sát】 này quyết toán xong có thể đặt lên thẻ võ tướng của bạn.",
	xinjiangchi: "Tương Trì",
	xinjiangchi_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể chọn: ① Rút một lá bài. ② Rút hai lá bài, sau đó lượt này không thể sử dụng hoặc đánh ra 【Sát】. ③ Bỏ một lá bài, sau đó lượt này có thể sử dụng thêm một lá 【Sát】, và sử dụng 【Sát】 không giới hạn khoảng cách.",
	redingpin: "Định Phẩm",
	redingpin_info: "Giai đoạn ra bài, bạn có thể bỏ một lá bài thuộc loại chưa từng sử dụng/bỏ trong lượt này và chọn một nhân vật. Người đó tiến hành phán xét, nếu kết quả là: Đen, họ rút X lá bài (X là thể lực của họ và tối đa là 3) và không thể là mục tiêu của 〖Định Phẩm〗 nữa trong lượt này; Cơ, bạn khiến lá bài vừa bỏ lần này không tính vào việc kiểm tra tính hợp lệ của loại bài bỏ 〖Định Phẩm〗; Rô, bạn lật mặt thẻ võ tướng.",
	refaen: "Pháp Ân",
	refaen_info: "Sau khi một nhân vật lật mặt hoặc xoay ngang, bạn có thể khiến họ rút một lá bài.",
	dcfaen: "Pháp Ân",
	dcfaen_info: "Sau khi một nhân vật lật lên mặt trước hoặc xoay ngang, bạn có thể khiến họ rút một lá bài.",
	reshizhi: "Thệ Chí",
	reshizhi_info: "Tỏa định kỹ, nếu thể lực của bạn là 1, các lá 【Thiểm】 của bạn xem như 【Sát】, và khi bạn sử dụng lá 【Sát】 thường không chuyển hóa có lá bài thực thể tương ứng là một lá 【Thiểm】 gây sát thương, bạn hồi phục 1 điểm thể lực.",
	re_guotufengji: "Giới Quách Đồ Phùng Kỷ",
	re_guotufengji_prefix: "Giới",
	rejigong: "Cấp Công",
	rejigong2: "Cấp Công",
	rejigong_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể rút tối đa ba lá bài. Nếu làm vậy, giới hạn bài tay cơ bản của bạn lượt này đổi thành X, và khi giai đoạn bỏ bài kết thúc, nếu X không nhỏ hơn Y, bạn hồi phục 1 điểm thể lực. (X là tổng sát thương bạn gây ra trong lượt này, Y là tổng số bài bạn nhận được do rút bài từ 〖Cấp Công〗 lượt này)",
	ol_jiangwei: "Giới Khương Duy",
	ol_jiangwei_prefix: "Giới",
	oltiaoxin: "Khiêu Hấn",
	oltiaoxin_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể chọn một nhân vật có phạm vi tấn công bao hàm bạn. Sau đó trừ khi nhân vật đó sử dụng một lá 【Sát】 lên bạn và lá 【Sát】 này gây sát thương cho bạn, nếu không bạn bỏ một lá bài của họ, sau đó đổi kỹ năng này thành giới hạn hai lần trong giai đoạn ra bài này.",
	olzhiji: "Chí Kế",
	olzhiji_info: "Giác tỉnh kỹ, giai đoạn chuẩn bị hoặc giai đoạn kết thúc, nếu bạn không có bài trên tay, bạn hồi phục 1 điểm thể lực hoặc rút hai lá bài, sau đó giảm 1 điểm giới hạn thể lực, nhận 〖Quan Tinh〗.",
	decadezhenjun: "Trấn Quân",
	decadezhenjun_info: "Giai đoạn chuẩn bị hoặc giai đoạn kết thúc, bạn có thể bỏ X lá bài của một nhân vật (X là số bài tay của họ trừ đi thể lực và ít nhất là 1), nếu trong đó không có trang bị, bạn chọn một: 1. Bạn bỏ một lá bài; 2. Nhân vật đó rút lượng bài tương ứng.",
	decadejingce: "Tinh Sách",
	decadejingce_info: "Giai đoạn kết thúc, nếu số bài bạn sử dụng lượt này không nhỏ hơn thể lực của mình, bạn có thể thực hiện một giai đoạn rút bài hoặc giai đoạn ra bài; nếu những lá bài này chứa số lượng chất cũng không nhỏ hơn thể lực của mình, bạn đổi “hoặc” thành “và”.",
	re_guanping: "Giới Quan Bình",
	re_guanping_prefix: "Giới",
	relongyin: "Long Ngâm",
	relongyin_info: "Khi một nhân vật sử dụng 【Sát】 trong giai đoạn ra bài của họ, bạn có thể bỏ một lá bài khiến lá 【Sát】 này không tính vào số lần sử dụng trong giai đoạn ra bài. Nếu lá 【Sát】 này màu đỏ, bạn rút một lá bài; nếu lá bài bạn bỏ theo cách này có điểm số bằng với lá 【Sát】 này, bạn phục hồi “Kiệt Trung”.",
	jiezhong: "Kiệt Trung",
	jiezhong_info: "Hạn định kỹ, khi giai đoạn ra bài bắt đầu, bạn có thể bổ sung bài tay cho đến giới hạn thể lực (tối đa rút năm lá).",
	re_caifuren: "Giới Thái Phu Nhân",
	re_caifuren_prefix: "Giới",
	reqieting: "Thiết Thính",
	reqieting_info: "Khi lượt của nhân vật khác kết thúc, nếu họ chưa gây sát thương trong lượt này, bạn có thể đặt một lá trang bị trong khu trang bị của họ vào khu trang bị của mình; nếu họ chưa sử dụng bài lên nhân vật khác trong lượt này, bạn có thể rút một lá bài.",
	rexianzhou: "Hiến Châu",
	rexianzhou_info: "Hạn định kỹ. Giai đoạn ra bài, bạn có thể đưa tất cả bài trong khu trang bị cho một nhân vật khác. Bạn hồi phục X điểm thể lực, sau đó gây 1 điểm sát thương cho mỗi nhân vật trong số tối đa X nhân vật trong phạm vi tấn công của họ (X là số bài bạn đã đưa theo cách này).",
	xin_zhonghui: "Giới Chung Hội",
	xin_zhonghui_prefix: "Giới",
	xinquanji: "Quyền Kế",
	xinquanji_info: "① Sau khi bạn chịu 1 điểm sát thương, hoặc khi nhân vật khác nhận được bài của bạn không phải do bạn tặng hoặc đưa, bạn có thể rút một lá bài, sau đó đặt một lá bài tay lên thẻ võ tướng, gọi là “Quyền”. ② Giới hạn bài trên tay của bạn +X (X là số lượng “Quyền”).",
	xinzili: "Tự Lập",
	xinzili_info: "Giác tỉnh kỹ. Giai đoạn chuẩn bị, nếu số “Quyền” lớn hơn 2, bạn hồi phục 1 điểm thể lực và rút hai lá bài, giảm 1 điểm giới hạn thể lực và nhận 〖Bài Dị〗.",
	xinpaiyi: "Bài Dị",
	xinpaiyi_backup: "Bài Dị",
	xinpaiyi_info: "Giai đoạn ra bài mỗi hạng mục giới hạn một lần, bạn có thể xóa một lá “Quyền” và chọn một hạng mục: ① Khiến một nhân vật rút X lá bài. ② Gây 1 điểm sát thương cho mỗi nhân vật trong tối đa X nhân vật. (X là số “Quyền”)",
	re_guyong: "Giới Cố Ung",
	re_guyong_prefix: "Giới",
	reshenxing: "Thận Hạnh",
	reshenxing_info: "Giai đoạn ra bài, bạn có thể bỏ X lá bài (X là số lần bạn đã phát động 〖Thận Hạnh〗 trong giai đoạn này và ít nhất là 0, tối đa là 2), sau đó rút một lá bài.",
	rebingyi: "Bỉnh Nhất",
	rebingyi_info: "Giai đoạn kết thúc, bạn có thể cho xem tất cả bài trên tay. Nếu những lá bài này: Màu sắc đều giống nhau, bạn có thể khiến tối đa X nhân vật mỗi người rút một lá bài (X là số bài tay của bạn); Màu sắc và điểm số đều giống nhau, bạn rút một lá bài.",
	re_jiaxu: "Giới Giả Hủ",
	re_jiaxu_prefix: "Giới",
	rewansha: "Hoàn Sát",
	rewansha_info: "Tỏa định kỹ. ① Trong lượt của bạn, các nhân vật khác không ở trạng thái hấp hối không thể sử dụng 【Đào】. ② Khi có nhân vật rơi vào trạng thái hấp hối trong lượt của bạn, bạn khiến các kỹ năng phi tỏa định của tất cả các nhân vật khác ngoài người đó mất hiệu lực cho đến khi kết thúc quyết toán trạng thái hấp hối này.",
	reluanwu: "Loạn Võ",
	reluanwu_info: "Hạn định kỹ, giai đoạn ra bài, bạn có thể khiến tất cả nhân vật khác lần lượt chọn một: ① Sử dụng một lá 【Sát】 lên nhân vật có khoảng cách gần nhất (hoặc một trong số đó); ② Mất 1 điểm thể lực. Sau khi quyết toán xong, bạn có thể xem như sử dụng một lá 【Sát】 (không giới hạn khoảng cách).",
	reweimu: " Duy Mạc",
	reweimu_info: "Tỏa định kỹ. ① Bạn không thể là mục tiêu của Cẩm nang màu đen. ② Khi bạn chịu sát thương trong lượt của mình, bạn ngăn chặn sát thương này và rút 2X lá bài (X là điểm sát thương).",
	ol_lusu: "Giới Lỗ Túc",
	ol_lusu_prefix: "Giới",
	olhaoshi: "Hảo Thí",
	olhaoshi_info: "Khi giai đoạn rút bài bắt đầu, bạn có thể rút thêm hai lá bài. Sau đó khi giai đoạn rút bài kết thúc, nếu số bài tay của bạn lớn hơn 5, bạn đưa một nửa số bài tay (lấy phần nguyên xuống) cho một nhân vật khác có ít bài tay nhất và nhận hiệu ứng sau cho đến khi lượt tiếp theo của bạn bắt đầu: Khi bạn trở thành mục tiêu của 【Sát】 hoặc Cẩm nang thông thường, họ có thể đưa cho bạn một lá bài tay.",
	oldimeng: "Đế Minh",
	oldimeng_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể khiến hai nhân vật khác có chênh lệch số bài tay không lớn hơn số bài của bạn trao đổi bài tay cho nhau. Nếu làm vậy, khi giai đoạn này kết thúc, bạn bỏ X lá bài (X là chênh lệch số bài tay của hai nhân vật này).",

	rejijiang: "Kích Giảng",
	rejijiang1: "Kích Giảng",
	rejijiang2: "Kích Giảng",
	rejijiang_info: "Chủ công kỹ. ① Khi bạn cần sử dụng hoặc đánh ra 【Sát】, bạn có thể khiến các nhân vật phe Thục khác lần lượt chọn có đánh ra một lá 【Sát】 hay không. Nếu có nhân vật đáp lại, bạn xem như đã sử dụng hoặc đánh ra lá 【Sát】 này. ② Mỗi lượt giới hạn một lần. Khi có nhân vật phe Thục sử dụng hoặc đánh ra 【Sát】 ngoài lượt, họ có thể khiến bạn rút một lá bài.",
	xin_yufan: "Giới Ngu Phiên",
	xin_yufan_prefix: "Giới",
	xinzongxuan: "Túng Huyền",
	xinzongxuan_info: "Khi bài của bạn đi vào chồng bài bỏ do bị bỏ, bạn có thể đặt bất kỳ lá nào trong số đó lên đỉnh chồng bài. Nếu những lá còn lại có Cẩm nang, bạn có thể khiến một nhân vật khác nhận lấy một lá trong đó.",
	xinzhiyan: "Trực Ngôn",
	xinzhiyan_info: "Khi giai đoạn kết thúc bắt đầu, bạn có thể khiến một nhân vật rút một lá bài (di chuyển mặt ngửa). Nếu lá này là bài Cơ bản, bạn rút một lá bài. Nếu lá này là trang bị, họ hồi phục 1 điểm thể lực và sử dụng lá trang bị này.",
	re_xiahoushi: "Giới Hạ Hầu Thị",
	re_xiahoushi_prefix: "Giới",
	reqiaoshi: "Tiều Thập",
	reqiaoshi_info: "Khi giai đoạn kết thúc của nhân vật khác bắt đầu, nếu số bài tay của bạn bằng với họ, bạn có thể cùng họ mỗi người rút một lá bài. Nếu hai lá này cùng chất, bạn có thể lặp lại bước này.",
	reyanyu: "Yến Ngữ",
	reyanyu2: "Yến Ngữ",
	reyanyu_info: "① Giai đoạn ra bài, bạn có thể trọng chú 【Sát】. ② Khi giai đoạn ra bài kết thúc, bạn có thể khiến một nhân vật nam khác rút X lá bài (X là số lần bạn đã phát động 〖Yến Ngữ①〗 trong giai đoạn này và tối đa là 3).",
	rehujia: "Hộ Giá",
	rehujia_info: "Chủ công kỹ. ① Khi bạn cần sử dụng hoặc đánh ra một lá 【Thiểm】, bạn có thể khiến các nhân vật phe Ngụy khác chọn có đánh ra một lá 【Thiểm】 hay không. Nếu có nhân vật đáp lại, bạn xem như đã sử dụng hoặc đánh ra một lá 【Thiểm】. ② Mỗi lượt giới hạn một lần. Khi có nhân vật phe Ngụy sử dụng hoặc đánh ra 【Thiểm】 ngoài lượt, họ có thể khiến bạn rút một lá bài.",
	ol_xuhuang: "Giới Từ Hoảng",
	ol_xuhuang_prefix: "Giới",
	olduanliang: "Đoạn Lương",
	olduanliang_info: "Bạn có thể dùng một lá màu đen không phải Cẩm nang xem như sử dụng 【Binh Lương Thốn Đoạn】. Nếu bạn chưa gây sát thương trong lượt hiện tại, bạn sử dụng 【Binh Lương Thốn Đoạn】 không bị giới hạn khoảng cách.",
	oljiezi: "Tiết Tiết",
	oljiezi_info: "① Khi có nhân vật bỏ qua giai đoạn rút bài, bạn có thể chọn một nhân vật. Nếu nhân vật đó: Có số bài tay ít nhất toàn cuộc và không có “Tiết”, họ nhận một dấu ấn “Tiết”. Nếu không họ rút một lá bài. ② Khi giai đoạn rút bài của một nhân vật kết thúc, nếu họ có “Tiết”, bạn xóa “Tiết” của họ, sau đó khiến họ thực hiện thêm một giai đoạn rút bài.",
	re_madai: "Giới Mã Đại",
	re_madai_prefix: "Giới",
	reqianxi: "Tiềm Tập",
	reqianxi_info: "Khi giai đoạn chuẩn bị bắt đầu, bạn có thể rút một lá bài, sau đó bỏ một lá bài và chọn một nhân vật khác có khoảng cách là 1. Nhân vật đó trong lượt này: {Không thể sử dụng hoặc đánh ra bài cùng màu với lá bài này, và các lá Phòng cụ cùng màu với lá bài này trong khu trang bị mất hiệu lực, và khi họ hồi phục thể lực, bạn rút hai lá bài.}",
	re_guohuanghou: "Giới Quách Hoàng Hậu",
	re_guohuanghou_prefix: "Giới",
	rejiaozhao: "Kiểu Chiếu",
	rejiaozhao_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể cho xem một lá bài tay, và khiến một nhân vật gần bạn nhất chọn một tên bài Cơ bản hoặc Cẩm nang thông thường. Bạn có thể dùng lá bài này xem như lá bài họ đã tuyên bố cho đến khi giai đoạn này kết thúc (bạn không phải là mục tiêu hợp lệ của lá bài này).",
	rejiaozhao_lv2: "Kiểu Chiếu·Thăng cấp Lv.1",
	rejiaozhao_lv2_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể dùng một lá bài tay xem như sử dụng một lá bài Cơ bản hoặc Cẩm nang thông thường (bạn không phải là mục tiêu hợp lệ của lá bài này).",
	rejiaozhao_lv3: "Kiểu Chiếu·Thăng cấp Lv.2",
	rejiaozhao_lv3_info: "Giai đoạn ra bài mỗi loại giới hạn một lần. Bạn có thể dùng một lá bài tay xem như sử dụng một lá bài Cơ bản hoặc Cẩm nang thông thường.",
	redanxin: "Đàn Tâm",
	redanxin_info: "Sau khi chịu sát thương, bạn có thể rút một lá bài và thăng cấp 〖Kiểu Chiếu〗.",
	xin_wuguotai: "Giới Ngô Quốc Thái",
	xin_wuguotai_prefix: "Giới",
	xinganlu: "Cam Lộ",
	xinganlu_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể khiến hai nhân vật trao đổi bài trong khu trang bị, sau đó nếu giá trị tuyệt đối của chênh lệch số bài trang bị giữa hai người này lớn hơn số thể lực bạn đã mất, bạn bỏ hai lá bài tay.",
	xinbuyi: "Bổ Ích",
	xinbuyi_info: "Khi một nhân vật rơi vào trạng thái hấp hối, bạn có thể cho xem một lá bài tay của họ. Nếu lá này không phải Cơ bản, họ bỏ lá này và hồi phục 1 điểm thể lực. Nếu lá bài họ bỏ theo cách này trước khi di chuyển là lá bài tay duy nhất của họ, họ rút một lá bài.",
	decadexianzhen: "Hãm Trận",
	decadexianzhen2: "Hãm Trận",
	decadexianzhen_info: "Mỗi lượt giới hạn một lần. Giai đoạn ra bài, bạn có thể đấu điểm với một nhân vật khác. Nếu bạn thắng: Lượt này bạn phớt lờ phòng cụ của nhân vật đó, và sử dụng bài lên họ không bị giới hạn số lần và khoảng cách, đồng thời lượt này khi sử dụng bài gây sát thương lên họ, sát thương này +1 (mỗi tên bài mỗi lượt giới hạn một lần); nếu bạn không thắng: Bạn không thể sử dụng 【Sát】 trong lượt này, và 【Sát】 không tính vào giới hạn bài tay.",
	decadejinjiu: "Cấm Tửu",
	decadejinjiu_info: "Tỏa định kỹ. Tên các lá 【Tửu】 của bạn đều xem là 【Sát】 và điểm số xem là K; trong lượt của bạn, các nhân vật khác không thể sử dụng 【Tửu】.",
	dc_xushu: "Tân Sát Từ Thứ",
	dc_xushu_prefix: "Tân Sát",
	rezhuhai: "Tru Hại",
	rezhuhai_info: "Khi giai đoạn kết thúc của nhân vật khác bắt đầu, nếu họ đã gây sát thương trong lượt này, bạn có thể chọn một: ⒈ Dùng một lá bài tay xem như 【Sát】 sử dụng lên họ. ⒉ Xem như sử dụng một lá 【Quá Hà Chiết Kiều】 lên họ.",
	xsqianxin: "Tiềm Tâm",
	xsqianxin_info: "Giác tỉnh kỹ. Sau khi bạn gây sát thương, nếu bạn đã bị thương, bạn giảm 1 điểm giới hạn thể lực và nhận 〖Tiến Ngôn〗.",
	rejianyan: "Tiến Ngôn",
	rejianyan_info: "Giai đoạn ra bài mỗi hạng mục giới hạn một lần. Bạn có thể chọn một màu sắc hoặc một loại bài, sau đó hệ thống truy xuất từ chồng bài ra một lá bài thỏa mãn điều kiện đó và cho xem. Sau đó bạn đưa lá bài này cho một nhân vật nam hoặc nhân vật phe Key.",
	re_zhanghe: "Giới Trương Cáp",
	re_zhanghe_prefix: "Giới",
	reqiaobian: "Xảo Biến",
	reqiaobian_info: "① Khi trò chơi bắt đầu, bạn nhận hai dấu ấn “Biến”. ② Khi giai đoạn phán xét bắt đầu, bạn có thể bỏ một lá bài hoặc một “Biến” và bỏ qua giai đoạn này. ③ Khi giai đoạn rút bài bắt đầu, bạn có thể bỏ một lá bài hoặc một “Biến” và bỏ qua giai đoạn này, sau đó có thể nhận tối đa một lá bài tay của mỗi người trong tối đa hai nhân vật khác. ④ Khi giai đoạn ra bài bắt đầu, bạn có thể bỏ một lá bài hoặc một “Biến” và bỏ qua giai đoạn này, sau đó bạn có thể di chuyển một lá bài trên sân. ⑤ Khi giai đoạn bỏ bài bắt đầu, bạn có thể bỏ một lá bài hoặc một “Biến” và bỏ qua giai đoạn này. ⑥ Giai đoạn kết thúc, nếu trong ghi chép của 〖Xảo Biến⑥〗 không bao gồm số bài tay của bạn, bạn nhận một dấu ấn “Biến” và ghi lại số bài tay của mình.",
	olbeige: "Bi Ca",
	olbeige_info: "Khi một nhân vật chịu sát thương qua kênh 【Sát】, nếu bạn có bài, bạn có thể khiến họ tiến hành phán xét. Sau đó bạn có thể bỏ một lá bài, dựa theo kết quả phán xét thực hiện một trong các tùy chọn sau: ♥, họ hồi 1 điểm thể lực; ♦, họ rút hai lá bài; ♣, nguồn sát thương bỏ hai lá bài; ♠, nguồn sát thương lật mặt thẻ võ tướng. Nếu lá bài bạn bỏ có: Điểm số giống kết quả phán xét, bạn nhận lại lá bài bạn đã bỏ; Chất giống kết quả phán xét, bạn nhận lấy lá bài phán xét.",
	dc_bulianshi: "Giới Bộ Luyện Sư",
	dc_bulianshi_prefix: "Giới",
	dcanxu: "An Tuất",
	dcanxu_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể chọn hai nhân vật khác có số bài tay khác nhau, khiến nhân vật có ít bài tay hơn nhận một lá bài tay của nhân vật có nhiều bài tay hơn và cho xem lá đó. Sau đó nếu lá bài này không phải Bích, bạn rút một lá bài; nếu số bài tay của hai nhân vật này bằng nhau, bạn hồi phục 1 điểm thể lực.",
	dczhuiyi: "Truy Ức",
	dczhuiyi_info: "Khi bạn tử vong, bạn có thể khiến một nhân vật khác không phải người kết liễu rút X lá bài (X là số nhân vật còn sống), sau đó họ hồi phục 1 điểm thể lực.",
	re_jushou: "Giới Thư Thụ",
	re_jushou_prefix: "Giới",
	dcshibei: "Thệ Bắc",
	dcshibei_info: "Tỏa định kỹ, sau khi bạn chịu sát thương lần đầu tiên trong một lượt, bạn hồi phục 1 điểm thể lực; sau khi bạn chịu sát thương lần thứ hai trong một lượt, bạn mất 1 điểm thể lực.",
	dcjianying: "Tiệm Doanh",
	dcjianying_info: "Khi bạn sử dụng lá bài có cùng điểm số hoặc cùng chất với lá bài trước đó bạn đã sử dụng, bạn có thể rút một lá bài.",
	re_duji: "Giới Đỗ Cơ",
	re_duji_prefix: "Giới",
	reandong: "An Đông",
	reandong_info: "Khi bạn chịu sát thương gây ra bởi nhân vật khác, bạn có thể khiến nguồn sát thương chọn một: ⒈ Ngăn chặn sát thương này. Sau đó các lá bài ♥ của họ không tính vào giới hạn bài tay của lượt này; ⒉ Bạn xem bài tay của họ và nhận tất cả các lá ♥ trong đó, nếu họ không có bài tay, lần tiếp theo bạn phát động 〖An Đông〗 đổi thành tự mình chọn.",
	reyingshi: "Ứng Thế",
	reyingshi_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể cho xem một lá bài tay, chọn một nhân vật A và một nhân vật khác B. A có thể sử dụng một lá 【Sát】 lên B, sau đó nhận lá bài bạn đã cho xem. Nếu A gây sát thương từ lá 【Sát】 này, A nhận các lá bài khác trong chồng bài có cùng chất và điểm số với lá bài đã cho xem.",
	dcqiaomeng: "Kiêu Mãnh",
	dcqiaomeng_info: "Khi bạn sử dụng lá bài màu đen chỉ định mục tiêu đầu tiên, bạn có thể bỏ một lá bài của một nhân vật khác trong số các nhân vật mục tiêu. Nếu lá bài bạn bỏ theo cách này là: Trang bị, bạn nhận lấy lá này; Cẩm nang, bạn khiến lá bài này không thể bị đáp trả.",
	dc_gongsunzan: "Tân Sát Công Tôn Toản",
	dc_gongsunzan_prefix: "Tân Sát",
	re_liuchen: "Giới Lưu Thầm",
	re_liuchen_prefix: "Giới",
	rezhanjue: "Chiến Tuyệt",
	rezhanjue_effect: "Chiến Tuyệt",
	rezhanjue_info: "Giai đoạn ra bài, nếu số bài bạn nhận được từ 〖Chiến Tuyệt〗 trong giai đoạn này ít hơn 3, bạn có thể dùng tất cả các lá bài tay không có dấu ấn “Cần Vương” xem như sử dụng 【Quyết Đấu】. Sau khi lá 【Quyết Đấu】 này kết thúc quyết toán, bạn rút một lá bài. Sau đó tất cả các nhân vật đã chịu sát thương từ 【Quyết Đấu】 này cũng mỗi người rút một lá bài.",
	reqinwang: "Cần Vương",
	reqinwang_info: "Chủ công kỹ. Giai đoạn ra bài giới hạn một lần, bạn có thể khiến tất cả các nhân vật phe Thục khác lần lượt chọn có đưa cho bạn một lá 【Sát】 hay không, sau đó bạn có thể khiến những nhân vật chọn “có” rút một lá bài.",
	shizhan: "Thế Trảm",
	shizhan_info: "Giai đoạn ra bài giới hạn hai lần, bạn có thể chọn một nhân vật khác. Nhân vật đó xem như sử dụng một lá 【Quyết Đấu】 lên bạn.",
	ol_xunyu: "Giới Tuân Úc",
	ol_xunyu_prefix: "Giới",
	oljieming: "Tiết Mệnh",
	oljieming_info: "Sau khi bạn chịu 1 điểm sát thương hoặc tử vong, bạn có thể khiến một nhân vật rút X lá bài. Sau đó nếu số bài tay của họ lớn hơn X, họ phải bỏ bài tay xuống còn X lá (X là giới hạn thể lực của họ và tối đa là 5).",
	re_liufeng: "Giới Lưu Phong",
	re_liufeng_prefix: "Giới",
	rexiansi: "Hãm Tự",
	rexiansi2: "Hãm Tự",
	rexiansi_info: "① Khi giai đoạn chuẩn bị bắt đầu, bạn có thể đặt một lá bài của mỗi người trong một đến hai nhân vật lên thẻ võ tướng của bạn, gọi là “Nghịch”. ② Khi một nhân vật cần sử dụng 【Sát】 lên bạn, họ có thể xóa hai lá “Nghịch”, sau đó xem như sử dụng một lá 【Sát】 lên bạn. ③ Nếu số “Nghịch” lớn hơn thể lực, bạn có thể xóa một lá “Nghịch” và xem như sử dụng một lá 【Sát】.",
	re_sp_taishici: "Giới SP Thái Sử Từ",
	re_sp_taishici_prefix: "Giới SP",
	rejixu: "Kích Hư",
	rejixu_info: "Giai đoạn ra bài giới hạn một lần. Nếu bạn có bài tay, bạn có thể chọn tối đa X nhân vật, khiến những nhân vật này đoán xem trong khu vực bài tay của bạn có 【Sát】 hay không. Nếu bạn: Có 【Sát】, giới hạn số lần sử dụng 【Sát】 của bạn trong giai đoạn này +Y, và khi bạn sử dụng 【Sát】 chỉ định mục tiêu trong giai đoạn này, bạn có thể khiến Y nhân vật này cũng trở thành mục tiêu của lá 【Sát】 đó; không có 【Sát】, bạn bỏ một lá bài của mỗi người trong Y nhân vật này. Sau đó bạn rút Y lá bài (X là thể lực của bạn, Y là số người đoán sai trong các nhân vật đó).",
	ol_dianwei: "Giới Điển Vi",
	ol_dianwei_prefix: "Giới",
	olqiangxi: "Cường Kích",
	olqiangxi_info: "Giai đoạn ra bài giới hạn hai lần. Bạn có thể bỏ một lá trang bị Vũ khí hoặc chịu 1 điểm sát thương không nguồn, sau đó gây 1 điểm sát thương cho một nhân vật khác chưa từng là mục tiêu của 〖Cường Kích〗 trong lượt này.",
	olninge: "Nanh Ác",
	olninge_info: "Tỏa định kỹ. Khi một nhân vật A chịu sát thương lần thứ hai trong một lượt, nếu A hoặc nguồn sát thương là bạn, bạn rút một lá bài, sau đó bỏ một lá bài trong khu trang bị hoặc khu phán xét của họ.",
	re_zhuhuan: "Giới Chu Hoán",
	re_zhuhuan_prefix: "Giới",
	refenli: "Phấn Lệ",
	refenli_info: "Nếu số bài tay của bạn nhiều nhất toàn cuộc, bạn có thể bỏ qua giai đoạn phán xét và giai đoạn rút bài; nếu thể lực của bạn nhiều nhất toàn cuộc, bạn có thể bỏ qua giai đoạn ra bài; nếu trong khu trang bị của bạn có bài và số lượng nhiều nhất toàn cuộc, bạn có thể bỏ qua giai đoạn bỏ bài.",
	repingkou: "Bình Khấu",
	repingkou_info: "Khi kết thúc lượt, bạn có thể gây 1 điểm sát thương cho mỗi người trong tối đa X nhân vật khác (X là số giai đoạn bạn đã bỏ qua trong lượt này). Nếu số nhân vật bạn chọn ít hơn X, bạn có thể khiến một trong các nhân vật đó ngẫu nhiên bỏ một lá bài trong khu trang bị.",
	dc_liru: "Giới Lý Nho",
	dc_liru_prefix: "Giới",
	dcmieji: "Diệt Kế",
	dcmieji_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể cho xem một lá trang bị Vũ khí hoặc Cẩm nang màu đen. Bạn đặt lá bài này lên đỉnh chồng bài, sau đó khiến một nhân vật khác có bài tay chọn một: ⒈ Bỏ một lá Cẩm nang; ⒉ Lần lượt bỏ hai lá không phải Cẩm nang.",
	dcfencheng: "Phần Thành",
	dcfencheng_info: "Hạn định kỹ. Giai đoạn ra bài, bạn có thể chỉ định một nhân vật khác, khiến các nhân vật khác bắt đầu từ người đó lần lượt chọn một: ⒈ Bỏ ít nhất X lá bài (X là số bài nhân vật trước đó đã bỏ +1). ⒉ Bạn gây cho họ 2 điểm sát thương lửa.",
	oljiang: "Kích Ngang",
	oljiang_info: "① Khi bạn sử dụng 【Quyết Đấu】 hoặc 【Sát】 màu đỏ chỉ định mục tiêu đầu tiên, hoặc trở thành mục tiêu của 【Quyết Đấu】 hoặc 【Sát】 màu đỏ, bạn có thể rút một lá bài. ② Khi có lá 【Quyết Đấu】 hoặc 【Sát】 màu đỏ lần đầu tiên đi vào chồng bài bỏ do bị bỏ trong mỗi lượt, bạn có thể mất 1 điểm thể lực và nhận lấy những lá bài này.",
	re_xunyou: "Giới Tuân Du",
	re_xunyou_prefix: "Giới",
	reqice: "Kỳ Sách",
	reqice_info: "Giai đoạn ra bài giới hạn X lần (X là số “Kỳ Sách” của bạn +1), bạn có thể dùng tất cả bài trên tay xem như sử dụng bất kỳ một lá Cẩm nang thông thường nào.",
	rezhiyu: "Trí Ngu",
	rezhiyu_info: "Sau khi chịu sát thương, bạn có thể rút một lá bài, sau đó cho xem tất cả bài trên tay, khiến nguồn sát thương bỏ một lá bài tay. Nếu màu sắc các lá bài bạn cho xem đều giống nhau, bạn nhận 1 dấu ấn “Kỳ Sách” cho đến khi kết thúc lượt sau và nhận lấy lá bài mà nguồn sát thương đã bỏ.",
	re_caiyong: "Giới Thái Ung",
	re_caiyong_prefix: "Giới",
	rebizhuan: "Tị Soạn",
	rebizhuan_bg: "Thư",
	rebizhuan_info: "① Khi bạn sử dụng lá bài ♠, hoặc trở thành mục tiêu của lá bài ♠ do nhân vật khác sử dụng, bạn có thể đặt một lá bài từ đỉnh chồng bài lên thẻ võ tướng, gọi là “Thư” (bạn sở hữu tối đa bốn lá “Thư”). ② Giới hạn bài trên tay của bạn +X (X là số “Thư”).",
	retongbo: "Thông Bác",
	retongbo_info: "Khi giai đoạn rút bài kết thúc, bạn có thể dùng bất kỳ bài tay nào trao đổi với lượng “Thư” tương ứng. Sau đó nếu số “Thư” ít nhất là 4, bạn có thể đưa bốn lá “Thư” tùy ý cho nhân vật khác. Nếu các lá bài bạn đưa ra có chất hoàn toàn khác nhau, bạn hồi phục 1 điểm thể lực và giới hạn tối đa của “Thư” +1 (tối đa tăng thêm bằng số nhân vật còn sống).",
	re_chengong: "Giới Trần Cung",
	re_chengong_prefix: "Giới",
	remingce: "Minh Sách",
	remingce_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể đưa một lá 【Sát】 hoặc trang bị cho một nhân vật khác, họ chọn một: 1. Xem như sử dụng một lá 【Sát】 lên một nhân vật khác do bạn chọn, và nếu lá này gây sát thương, thực hiện tùy chọn 2; 2. Bạn và họ mỗi người rút một lá bài.",
	re_sundeng: "Giới Tôn Đăng",
	re_sundeng_prefix: "Giới",
	rekuangbi: "Khuông Bật",
	rekuangbi_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể khiến một nhân vật khác đặt tối đa ba lá bài lên thẻ võ tướng của bạn cho đến khi giai đoạn này kết thúc. Sau đó khi bạn sử dụng bài, nếu bạn: Có lá bài “Khuông Bật” cùng chất với lá bài này, bạn xóa một lá trong số đó và cùng họ mỗi người rút một lá bài; không có lá bài “Khuông Bật” cùng chất với lá bài này, bạn ngẫu nhiên xóa một lá bài “Khuông Bật” và rút một lá bài.",
	dc_chenqun: "Giới Trần Quần",
	dc_chenqun_prefix: "Giới",
	repindi: "Phẩm Đệ",
	repindi_info: "Giai đoạn ra bài mỗi nhân vật giới hạn một lần. Bạn có thể bỏ một lá bài thuộc loại chưa từng bị bỏ theo cách này trong giai đoạn hiện tại và chọn một nhân vật, bạn chọn một: 1. Họ rút X lá bài; 2. Họ bỏ X lá bài (X là số lần bạn phát động 〖Phẩm Đệ〗 trong lượt này). Sau đó nếu họ đã bị thương, bạn xoay ngang hoặc phục nguyên.",
	re_mazhong: "Giới Mã Trung",
	re_mazhong_prefix: "Giới",
	refuman: "Phủ Man",
	refuman_info: "Giai đoạn ra bài mỗi nhân vật giới hạn một lần. Bạn có thể bỏ một lá bài, khiến một nhân vật nhận một lá 【Sát】 từ chồng bài bỏ. Sau đó nếu họ mất lá bài này trước khi kết thúc lượt tiếp theo của họ, họ rút một lá bài; nếu họ mất lá bài này do sử dụng hoặc đánh ra, đổi thành bạn và họ mỗi người rút một lá bài.",
	re_guanzhang: "Giới Quan Hưng Trương Bào",
	re_guanzhang_prefix: "Giới",
	retongxin: "Đồng Tâm",
	retongxin_info: "Tỏa định kỹ. Phạm vi tấn công của bạn +2.",
	re_wenpin: "Giới Văn Sính",
	re_wenpin_prefix: "Giới",
	rezhenwei: "Trấn Vệ",
	rezhenwei_info: "Khi một nhân vật khác trở thành mục tiêu của 【Sát】 hoặc Cẩm nang màu đen, nếu thể lực của nhân vật đó không lớn hơn bạn và số mục tiêu của lá bài này là 1, bạn có thể bỏ một lá bài và chọn một: 1. Rút một lá bài, sau đó chuyển mục tiêu của lá 【Sát】 hoặc Cẩm nang màu đen này sang cho bạn; 2. Khiến lá 【Sát】 hoặc Cẩm nang màu đen này vô hiệu và đặt lá bài đó lên thẻ võ tướng của người sử dụng, sau đó khi lượt hiện tại kết thúc, người sử dụng nhận lại những lá bài này.",
	ol_huangzhong: "Giới Hoàng Trung",
	ol_huangzhong_prefix: "Giới",
	remoshi: "Một Thỉ",
	remoshi_info: "Tỏa định kỹ. ① Sau khi bạn sử dụng 【Sát】 gây sát thương cho nhân vật mục tiêu, nếu trong khu trang bị của họ có phòng cụ hoặc ngựa, bạn đặt lá bài thực thể tương ứng với lá 【Sát】 này lên thẻ võ tướng của họ. ② Khi nhân vật có bài “Một Thỉ” mất phòng cụ hoặc ngựa, bạn nhận lấy bài “Một Thỉ” của họ.",
	dc_caozhi: "Giới Tào Thực",
	dc_caozhi_prefix: "Giới",
	dcjiushi: "Tửu Thi",
	dcjiushi_info: "① Khi bạn cần sử dụng 【Tửu】, nếu thẻ võ tướng đang mặt ngửa, bạn có thể lật mặt thẻ, xem như sử dụng một lá 【Tửu】. ② Sau khi chịu sát thương, nếu thẻ võ tướng đang mặt úp tại thời điểm chịu sát thương, bạn có thể lật mặt thẻ. ③ Sau khi bạn sử dụng 【Tửu】, giới hạn số lần sử dụng 【Sát】 của bạn +1 cho đến khi kết thúc lượt sau của bạn.",
	olhuoji: "Hỏa Kế",
	olhuoji_info: "① Bạn có thể dùng một lá bài màu đỏ xem như 【Hỏa Công】. ② Hiệu ứng tác dụng của 【Hỏa Công】 bạn sử dụng đổi thành “Nhân vật mục tiêu ngẫu nhiên cho xem một lá bài tay A, sau đó bạn có thể bỏ một lá bài tay cùng màu với A, gây cho mục tiêu 1 điểm sát thương thuộc tính hỏa”.",
	olkanpo: "Khán Phá",
	olkanpo_info: "① Bạn có thể dùng một lá bài màu đen xem như 【Vô Giải Khả Kích】. ② Lá 【Vô Giải Khả Kích】 bạn sử dụng không thể bị đáp trả.",
	xinwangxi: "Vong Khích",
	xinwangxi_info: "Sau khi bạn gây 1 điểm sát thương cho nhân vật khác, hoặc chịu 1 điểm sát thương từ nhân vật khác, bạn có thể rút hai lá bài, sau đó đưa cho họ một lá bài.",
	ol_yanwen: "Giới Nhan Lương Văn Xử",
	ol_yanwen_prefix: "Giới",
	olshuangxiong: "Song Hùng",
	olshuangxiong_info: "① Khi giai đoạn rút bài kết thúc, bạn có thể bỏ một lá bài. Nếu làm vậy, trong lượt này bạn có thể dùng một lá bài khác màu với lá bài này xem như sử dụng 【Quyết Đấu】. ② Giai đoạn kết thúc, bạn nhận tất cả các lá bài đã gây sát thương cho bạn trong lượt này từ chồng bài bỏ.",
	re_zhuzhi: "Giới Chu Trị",
	re_zhuzhi_prefix: "Giới",
	reanguo: "An Quốc",
	reanguo_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể chọn một nhân vật khác, nếu người đó: Có số bài tay ít nhất toàn cuộc, họ rút một lá bài; có thể lực thấp nhất toàn cuộc, họ hồi 1 điểm thể lực; có số bài trong khu trang bị ít nhất toàn cuộc, họ ngẫu nhiên sử dụng một lá trang bị. Sau đó nếu nhân vật đó có hiệu ứng chưa thực hiện và bạn thỏa mãn điều kiện, bạn thực hiện nó. Nếu bạn và họ đã thực hiện tất cả các nhánh, bạn có thể trọng chú bất kỳ số lượng bài nào.",
	dcyicong: " Nghĩa Tòng",
	dcyicong_info: "Tỏa định kỹ. ① Khoảng cách từ bạn đến nhân vật khác -1. ② Nếu số điểm thể lực bạn đã mất không nhỏ hơn 2, khoảng cách từ nhân vật khác đến bạn +1.",
	re_zhangsong: "Giới Trương Tùng",
	re_zhangsong_prefix: "Giới",
	rexiantu: "Hiến Đồ",
	rexiantu_info: "Khi giai đoạn ra bài của nhân vật khác bắt đầu, bạn có thể rút hai lá bài, sau đó đưa hai lá bài cho nhân vật đó. Sau đó khi giai đoạn này kết thúc, nếu họ chưa gây sát thương trong giai đoạn này, bạn mất 1 điểm thể lực.",
	re_jsp_huangyueying: "Giới SP Hoàng Nguyệt Anh",
	re_jsp_huangyueying_prefix: "Giới SP",
	rejiqiao: "Cơ Xảo",
	rejiqiao_info: "Khi bắt đầu giai đoạn ra bài, bạn có thể bỏ bất kỳ số lượng bài nào, sau đó lật ra X lá bài trên cùng của chồng bài (X là tổng số bài bạn đã bỏ theo cách này và số thẻ trang bị trong số đó), bạn nhận lấy tất cả các lá bài không phải trang bị trong đó.",
	relinglong: "Linh Lung",
	relinglong_info: "Kỹ năng khóa. Nếu vùng trang bị của bạn: Có ô phòng cụ trống, bạn được coi là sở hữu 〖Bát Quái Trận〗; Có hai ô thú cưỡi trống, giới hạn bài trên tay của bạn +2; Có ô bảo vật trống, bạn được coi là sở hữu 〖Kỳ Tài〗; Nếu tất cả điều kiện trên đều thỏa mãn: Lá 【Sát】 hoặc Cẩm nang thường bạn sử dụng không thể bị phản hồi.",
	ol_zhangzhang: "Giới Trương Chiêu Trương Hoành",
	ol_zhangzhang_prefix: "Giới",
	olzhijian: "Trực Gián",
	olzhijian_info: "Giai đoạn ra bài, bạn có thể đặt một lá trang bị vào vùng trang bị của nhân vật khác (có thể thay thế trang bị cũ), sau đó rút một lá bài.",
	olguzheng: "Cố Chính",
	olguzheng_info: "Mỗi giai đoạn giới hạn một lần. Khi có ít nhất hai lá bài của nhân vật khác do bị bỏ mà rơi vào chồng bài bỏ, bạn có thể khiến nhân vật đó nhận lấy một lá trong số đó, sau đó bạn có thể nhận lấy số bài còn lại.",
	re_caochong: "Giới Tào Xung",
	re_caochong_prefix: "Giới",
	rechengxiang: "Xứng Tượng",
	rechengxiang_info: "Sau khi bạn chịu sát thương, bạn có thể lật ra bốn lá bài trên cùng của chồng bài. Sau đó nhận lấy bất kỳ số lượng bài nào có tổng điểm không lớn hơn 13. Nếu tổng điểm các lá bài bạn nhận được bằng 13, bạn lật lại thẻ võ tướng.",
	re_caorui: "Giới Tào Duệ",
	re_caorui_prefix: "Giới",
	remingjian: "Minh Giám",
	remingjian_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể đưa toàn bộ bài trên tay cho một nhân vật khác, sau đó nhân vật đó tại hiệp kế tiếp của họ nhận được hiệu ứng sau: 1. Giới hạn bài trên tay và giới hạn số lần sử dụng 【Sát】 +1; 2. Khi nhân vật đó gây sát thương lần đầu tiên, bạn phát động một lần 〖Khôi Thác〗.",
	rexingshuai: "Hưng Suy",
	rexingshuai_info: "Kỹ năng chủ công, kỹ năng giới hạn. Khi bạn rơi vào trạng thái hấp hối, bạn có thể khiến các nhân vật phe Ngụy khác lần lượt lựa chọn có giúp bạn hồi 1 điểm thể lực hay không. Sau đó các nhân vật này lần lượt chịu 1 điểm sát thương. Nhân vật có hiệu ứng 〖Minh Giám〗 sau khi giết nhân vật khác trong hiệp của mình, bạn làm mới 〖Hưng Suy〗.",
	xin_zhangliang: "Giới Trương Lương",
	xin_zhangliang_prefix: "Giới",
	rejijun: "Tập Quân",
	rejijun_info: "Khi lá bài bạn sử dụng có mục tiêu bao gồm chính mình kết thúc kết toán, bạn có thể tiến hành phán xét một lần và đặt lá bài phán xét lên thẻ võ tướng, gọi là “Phương”.",
	refangtong: "Phương Thống",
	refangtong_info: "Giai đoạn kết thúc, bạn có thể đặt một lá bài trên tay lên thẻ võ tướng, gọi là “Phương”. Nếu làm vậy, bạn có thể loại bỏ bất kỳ số lượng “Phương” nào và gây 1 điểm sát thương thuộc tính Lôi cho một nhân vật khác (Nếu tổng điểm số của “Phương” bị loại bỏ lớn hơn 36, thì đổi thành gây 3 điểm sát thương thuộc tính Lôi).",
	re_simalang: "Giới Tư Mã Lãng",
	re_simalang_prefix: "Giới",
	requji: "Khứ Tật",
	requji_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ X lá bài (X là số thể lực bạn đã mất) và khiến tối đa X nhân vật hồi 1 điểm thể lực, sau đó mục tiêu vẫn đang trong trạng thái bị thương được rút một lá bài. Nếu bạn bỏ bài màu đen theo cách này, bạn mất 1 điểm thể lực.",
	rejunbing: "Quận Binh",
	rejunbing_info: "Giai đoạn kết thúc của một nhân vật, nếu số bài trên tay của người đó nhỏ hơn số thể lực hiện tại, người đó có thể rút một lá bài rồi đưa toàn bộ bài trên tay cho bạn, sau đó bạn có thể đưa cho người đó số bài tương đương.",
	re_zhugedan: "Giới Gia Cát Đản",
	re_zhugedan_prefix: "Giới",
	regongao: "Công Ngao",
	regongao_info: "Kỹ năng khóa. Khi một nhân vật khác lần đầu tiên rơi vào trạng thái hấp hối, bạn tăng 1 điểm giới hạn thể lực, sau đó hồi 1 điểm thể lực.",
	rejuyi: "Cử Nghĩa",
	rejuyi_info: "Kỹ năng thức tỉnh. Giai đoạn chuẩn bị, nếu bạn đã bị thương, và giới hạn thể lực của bạn lớn hơn số nhân vật còn sống trên sân, bạn rút bài cho đến khi bằng giới hạn thể lực, sau đó nhận được kỹ năng 〖Băng Hoại〗 và 〖Uy Trọng〗.",
	reweizhong: "Uy Trọng",
	reweizhong_info: "Kỹ năng khóa. Khi giới hạn thể lực của bạn tăng lên hoặc giảm đi, bạn rút hai lá bài.",
	re_zhongyao: "Giới Chung Diêu",
	re_zhongyao_prefix: "Giới",
	rehuomo: "Hoạt Mặc",
	rehuomo_info: "Mỗi loại tên bài giới hạn một lần mỗi hiệp. Khi bạn cần sử dụng một lá bài Cơ bản, bạn có thể đặt một lá bài màu đen không phải bài Cơ bản lên đỉnh chồng bài, coi như sử dụng lá bài Cơ bản này.",
	zhoutai: "Giới Chu Thái",
	zhoutai_prefix: "Giới",
	caoren: "Giới Tào Nhân",
	caoren_prefix: "Giới",
	ollianhuan: "Liên Hoàn",
	ollianhuan_info: "Bạn có thể dùng một lá bài ♣ coi như sử dụng hoặc đúc lại 【Thiết Tỏa Liên Hoàn】. Sau khi bạn sử dụng 【Thiết Tỏa Liên Hoàn】 chọn mục tiêu, có thể thêm một mục tiêu cho lá bài này.",
	re_lidian: "Giới Lý Điển",
	gz_re_lidian: "Lý Điển",
	re_lidian_prefix: "Giới",
	re_xushu: "Giới Từ Thứ",
	re_xushu_prefix: "Giới",
	rejianxiong_old: "Gian Hùng",
	rejianxiong_old_info: "Sau khi bạn chịu sát thương, bạn có thể rút một lá bài hoặc nhận lấy lá bài đã gây sát thương cho bạn.",
};

export default translates;
