const translates = {
	re_panfeng: "Phàn Phượng",
	xinkuangfu: "Cuồng Phủ",
	xinkuangfu_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể chọn: 1, bỏ một lá bài trong khu vực Trang Bị, bạn dùng 【Giết】 thường không có bài thực thể tương ứng. Nếu 【Giết】 này gây sát thương, bạn bốc hai lá bài. 2, bỏ một lá bài trong khu vực Trang Bị của một nhân vật khác, bạn dùng 【Giết】 thường không có bài thực thể tương ứng. Nếu 【Giết】 này không gây sát thương, bạn bỏ hai lá bài trên tay. (Đều không giới hạn khoảng cách và số lần)",
	xingdaorong: "Hình Đạo Dung",
	xuxie: "Hư Hiệt",
	xuxie_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể giảm 1 điểm giới hạn thể lực và chọn tất cả nhân vật trong khoảng cách 1, bỏ mỗi người một lá bài hoặc khiến mỗi người bốc một lá bài. Khi kết thúc giai đoạn Xuất Bài, nếu giới hạn thể lực của bạn không phải là lớn nhất bàn, thì bạn tăng 1 điểm giới hạn thể lực, sau đó hồi phục 1 điểm thể lực hoặc bốc hai lá bài.",
	caoxing: "Tào Tính",
	cxliushi: "Lưu Thỉ",
	cxliushi2: "Lưu Thỉ",
	cxliushi_info: "Giai đoạn Xuất Bài, bạn có thể đặt một lá bài Cơ (♥) lên đỉnh bộ bài, xem như sử dụng một 【Giết】 nhắm vào một nhân vật (không giới hạn khoảng cách và không tính vào số lần sử dụng). Khi 【Giết】 này gây sát thương, nhân vật chịu sát thương nhận được một “Lưu”. Nhân vật có “Lưu” có giới hạn bài trên tay -X (X là số “Lưu” của người đó).",
	zhanwan: "Trảm Uyển",
	zhanwan_info: "Kỹ năng khóa, sau khi nhân vật có “Lưu” bỏ bài ở giai đoạn Bỏ Bài, bạn bốc số lượng bài tương ứng, sau đó người đó bỏ tất cả “Lưu”.",
	re_chunyuqiong: "Thuần Vu Quỳnh",
	recangchu: "Thương Trữ",
	recangchu2: "Thương Trữ",
	recangchu3: "Thương Trữ",
	recangchu_info: "Kỹ năng khóa. ① Khi bắt đầu ván chơi, bạn nhận được 3 “Lương”. Giới hạn bài trên tay của bạn +X (X là số “Lương”). ② Mỗi lượt giới hạn một lần, khi bạn nhận được bài ngoài lượt của mình, bạn nhận được một “Lương”. (Số “Lương” của bạn không được vượt quá số nhân vật còn sống)",
	reliangying: "Lương Dinh",
	reliangying_info: "Khi bắt đầu giai đoạn Bỏ Bài, bạn có thể bốc tối đa X lá bài, sau đó đưa cho số lượng nhân vật tương ứng mỗi người một lá bài. (X là số “Lương” của bạn)",
	reshishou: "Thất Thủ",
	reshishou2: "Thất Thủ",
	reshishou_info: "Kỹ năng khóa, khi bạn dùng 【Rượu】 hoặc sau khi chịu 1 điểm sát thương Hỏa, bạn bỏ một “Lương”. Giai đoạn Chuẩn Bị, nếu bạn không có “Lương”, bạn mất 1 điểm thể lực.",
	xiahoujie: "Hạ Hầu Kiệt",
	liedan: "Liệt Đảm",
	liedan_info: "Kỹ năng khóa, khi bắt đầu giai đoạn Chuẩn Bị của nhân vật khác, nếu X lớn hơn 0, thì bạn bốc X lá bài. Nếu X bằng 3, thì bạn tăng 1 điểm giới hạn thể lực (tối đa tăng đến 8). Nếu X bằng 0, thì bạn mất 1 điểm thể lực và nhận được một dấu hiệu “Liệt” (X là số lượng các giá trị (số bài trên tay, giá trị thể lực, số bài trong khu vực Trang Bị của bạn) lớn hơn của người đó). Giai đoạn Chuẩn Bị, nếu số “Liệt” lớn hơn 4, thì bạn chết.",
	zhuangdan: "Tráng Đảm",
	zhuangdan_mark: "Tráng Đảm",
	zhuangdan_info: "Kỹ năng khóa, khi kết thúc lượt của nhân vật khác, nếu số bài trên tay bạn là nhiều nhất duy nhất bàn, thì bạn khiến 【Liệt Đảm】 mất hiệu lực cho đến khi kết thúc lượt tiếp theo của bạn.",
	dc_caiyang: "Thái Dương",
	dcxunji: "Tầm Tật",
	dcxunji_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể chọn một nhân vật khác. Khi bắt đầu giai đoạn Kết Thúc tiếp theo của nhân vật đó, nếu trong lượt này người đó đã sử dụng bài đen, thì bạn xem như sử dụng một 【Quyết Đấu】 nhắm vào người đó, và khi 【Quyết Đấu】 này gây sát thương cho người đó, người đó gây lượng sát thương tương ứng cho bạn.",
	dcjiaofeng: "Giao Phong",
	dcjiaofeng_info: "Kỹ năng khóa. Mỗi lượt giới hạn một lần, khi bạn gây sát thương, nếu trong lượt này bạn chưa gây sát thương nào khác và thể lực đã mất của bạn: lớn hơn 0, thì bạn bốc một lá bài; lớn hơn 1, thì sát thương này +1; lớn hơn 2, thì bạn hồi phục 1 điểm thể lực.",
	zhoushan: "Chu Thiện",
	dcmiyun: "Mật Vận",
	dcmiyun_tag: "An",
	dcmiyun_info: "Kỹ năng khóa. ① Khi bắt đầu mỗi vòng, bạn nhận một lá bài của một nhân vật khác theo chiều mặt ngửa, gọi là “An”. ② Khi kết thúc mỗi vòng, nếu bạn có “An”, bạn đưa một số lá bài trên tay bất kỳ bao gồm “An” cho một nhân vật khác, sau đó bạn bổ sung bài trên tay lên giới hạn thể lực. ③ Khi bạn mất “An” không phải do 【Mật Vận②】, bạn mất 1 điểm thể lực.",
	dcdanying: "Đảm Nghênh",
	dcdanying_info: "Mỗi lượt giới hạn một lần. Bạn có thể tiết lộ “An”, sau đó xem như sử dụng hoặc đánh ra một 【Giết】 hoặc 【Tránh】. Sau đó khi bạn trở thành mục tiêu của bài lần tiếp theo trong lượt này, người sử dụng bỏ một lá bài của bạn.",
	re_sunluyu: "Tôn Lục Dục",
	remeibu: "Mị Bộ",
	remeibu_info: "Khi bắt đầu giai đoạn Xuất Bài của nhân vật khác, nếu bạn nằm trong phạm vi tấn công của người đó, bạn có thể bỏ một lá bài A, nhân vật đó trong giai đoạn này có 【Chỉ Tức】, và khi người đó vì 【Chỉ Tức】 bỏ bài cùng hoa với lá bài A, bạn nhận được nó.",
	rezhixi: "Chỉ Tức",
	rezhixi_info: "Kỹ năng khóa, khi bạn dùng 【Giết】 hoặc bài chú thông thường, bạn bỏ một lá bài trên tay.",
	remumu: "Mục Mục",
	remumu_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể chọn một hạng mục: 1. Bỏ một lá bài trong khu vực Trang Bị của một nhân vật khác, sau đó trong lượt này số lần bạn có thể dùng 【Giết】 +1; 2. Nhận một lá bài trong khu vực Trang Bị của một nhân vật, sau đó trong lượt này số lần bạn có thể dùng 【Giết】 -1.",
	re_dongbai: "Đổng Bạch",
	relianzhu: "Liên Tru",
	relianzhu_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể đưa một lá bài ngửa lên cho một nhân vật khác. Nếu bài này là: đỏ, bạn bốc một lá bài; đen, đối phương bỏ hai lá bài hoặc khiến bạn bốc hai lá bài.",
	rexiahui: "Hiệt Tuệ",
	rexiahui_info: "Kỹ năng khóa, ① Bài đen của bạn không tính vào giới hạn bài trên tay. ② Khi có nhân vật khác nhận được bài đen của bạn, trước lần tiếp theo người đó bị trừ thể lực, không thể dùng, đánh ra, bỏ những bài này. ③ Khi kết thúc lượt của một nhân vật khác, nếu trong lượt này người đó đã mất tất cả bài “Hiệt Tuệ” của mình, thì người đó mất 1 điểm thể lực.",
	heyan: "Hà Yến",
	yachai: "Nhai Sài",
	yachai_info: "Sau khi bạn chịu sát thương, bạn có thể khiến nguồn gây sát thương chọn một: ① Người đó trong lượt này không thể dùng bài trên tay nữa, sau đó bạn bốc hai lá bài; ② Người đó tiết lộ tất cả bài trên tay, sau đó đưa cho bạn tất cả bài có một hoa bất kỳ trong bài trên tay của người đó; ③ Bỏ một nửa số bài trên tay (làm tròn lên).",
	qingtan: "Thanh Đàm",
	qingtan_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể khiến tất cả nhân vật có bài trên tay đồng thời chọn một lá bài trên tay và đồng thời tiết lộ. Bạn có thể nhận được bài có một hoa bất kỳ, sau đó nhân vật đã tiết lộ bài có hoa này mỗi người bốc một lá bài. Nếu làm vậy, bỏ các bài còn lại.",
	zhaoyan: "Triệu Yên",
	jinhui: "Cẩm Hội",
	jinhui_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể ngẫu nhiên lật ra ba lá bài từ bộ bài không có nhãn “sát thương” và có phạm vi mục tiêu sử dụng là “chính mình” hoặc “một nhân vật”, sau đó chọn một nhân vật khác. Nhân vật đó chọn và sử dụng một trong số đó theo quy tắc “Cẩm Hội” dưới đây, sau đó bạn có thể sử dụng bất kỳ lá bài còn lại theo quy tắc “Cẩm Hội” dưới đây: nếu mục tiêu sử dụng của bài này là “chính mình”, thì tự dùng bài đó cho mình, nếu không thì dùng bài đó cho đối phương (không giới hạn khoảng cách và không tính vào giới hạn số lần).",
	qingman: "Khinh Mạn",
	qingman_info: "Kỹ năng khóa. Khi kết thúc lượt của một nhân vật, bạn bốc bài trên tay lên X lá (X là số lượng ô trống trong khu vực Trang Bị của người đó).",
	wangtao: "Vương Đào",
	wangyue: "Vương Duyệt",
	huguan: "Hộ Quan",
	huguan_info: "Khi một nhân vật sử dụng lá bài đầu tiên trong giai đoạn Xuất Bài, nếu lá bài này màu đỏ, thì bạn có thể tuyên bố một hoa. Bài có hoa đó không tính vào giới hạn bài trên tay của người đó trong lượt này.",
	yaopei: "Dao Bội",
	yaopei_info: "Khi kết thúc giai đoạn Bỏ Bài của nhân vật khác, nếu bạn đã phát động 【Hộ Quan】 trong lượt này, thì bạn có thể bỏ một lá bài có hoa khác với tất cả hoa của bài người đó đã bỏ trong giai đoạn này. Sau đó bạn chọn một: ① Người đó bốc hai lá bài, bạn hồi phục 1 điểm thể lực. ② Người đó hồi phục 1 điểm thể lực, bạn bốc hai lá bài.",
	mingluan: "Minh Loan",
	mingluan_info: "Khi bắt đầu giai đoạn Kết Thúc của nhân vật khác, nếu có nhân vật đã hồi phục thể lực trong lượt này, thì bạn có thể bỏ một số lá bài bất kỳ, sau đó bốc X lá bài (X là số bài trên tay của nhân vật hiện tại, và tối đa bốc đến năm lá).",
	zhangxuan: "Trương Huyền",
	tongli: "Đồng Lễ",
	tongli_info: "Khi bạn sử dụng bài cơ bản hoặc bài chú thông thường chỉ định mục tiêu đầu tiên trong giai đoạn Xuất Bài, nếu số hoa trong bài trên tay bạn bằng với số bài bạn đã sử dụng trong giai đoạn này, thì bạn có thể khiến bài này kết toán thêm X lần (X là số hoa trong bài trên tay bạn).",
	shezang: "Xa Táng",
	shezang_info: "Mỗi vòng giới hạn một lần. Khi bạn hoặc nhân vật khác trong lượt của bạn vào trạng thái hấp hối, bạn có thể lấy từ bộ bài mỗi hoa một lá bài.",
	tengyin: "Đằng Dận",
	chenjian: "Trần Kiến",
	chenjian_info: "Giai đoạn Chuẩn Bị, bạn có thể lật ngửa 3+X lá bài trên cùng bộ bài (X là số lượng dấu hiệu “Trần Kiến” của bạn và tối đa là 2), sau đó thực hiện một đến hai hạng mục sau: ⒈ Bỏ một lá bài, sau đó khiến một nhân vật nhận được bài cùng hoa với lá bài bạn bỏ. ⒉ Sử dụng một trong số các lá bài còn lại. Nếu bạn thực hiện tất cả các hạng mục, thì bạn nhận được một dấu hiệu “Trần Kiến” và tái luyện tất cả bài trên tay.",
	xixiu: "Tích Tú",
	xixiu_info: "Kỹ năng khóa. ① Khi bạn trở thành mục tiêu sử dụng bài của nhân vật khác, nếu trong khu vực Trang Bị của bạn có bài cùng hoa với bài này, thì bạn bốc một lá bài. ② Nếu số bài trong khu vực Trang Bị của bạn là 1, thì nhân vật khác không thể bỏ bài trong khu vực Trang Bị của bạn.",
	zhangyao: "Trương Yêu",
	yuanyu: "Oán Ngữ",
	yuanyu_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể bốc hai lá bài, sau đó chọn một lá bài trên tay và một nhân vật khác. Nhân vật đó nhận được hiệu ứng sau cho đến khi bạn phát động 【Tịch Nhan】: {Khi bắt đầu giai đoạn Bỏ Bài của bạn và người đó, hoặc khi người đó gây 1 điểm sát thương, người đó phải đặt một lá bài trên tay lên bài tướng của bạn làm “Oán”}. Sau đó bạn đặt lá bài bạn đã chọn lên bài tướng của bạn làm “Oán”.",
	xiyan: "Tịch Nhan",
	xiyan_info: "Khi có bài di chuyển lên bài tướng của bạn làm “Oán”, nếu số hoa trong “Oán” đạt 4 loại, thì bạn có thể nhận được tất cả “Oán”. Sau đó nếu nhân vật trong lượt hiện tại: là bạn, trong lượt này giới hạn bài trên tay bạn +4 và dùng bài không giới hạn số lần và thiết lập lại số lần phát động 【Oán Ngữ】 của bạn trong giai đoạn này; không phải bạn, bạn có thể khiến nhân vật trong lượt hiện tại trong lượt này giới hạn bài trên tay -4 và không thể dùng bài cơ bản.",
	xiahoulingnv: "Hạ Hầu Lệnh Nữ",
	fuping: "Phù Bình",
	fuping_info: "① Sau khi bài do nhân vật khác dùng nhắm vào bạn kết toán xong, nếu bạn chưa ghi nhớ tên bài này vì kỹ năng này và bạn có ô trang bị chưa bị phế bỏ, thì bạn có thể phế bỏ một ô trang bị, ghi nhớ tên bài này. ② Mỗi lượt mỗi tên bài giới hạn một lần. Bạn có thể dùng một bài không phải cơ bản xem như bài cơ bản hoặc bài chú đã được 【Phù Bình①】 ghi nhớ để dùng hoặc đánh ra. ③ Nếu tất cả các ô trang bị của bạn đã bị phế bỏ, thì bạn dùng bài không giới hạn khoảng cách.",
	weilie: "Vĩ Liệt",
	weilie_info: "Mỗi ván giới hạn X lần. Giai đoạn Xuất Bài, bạn có thể bỏ một lá bài và chọn một nhân vật đã bị thương, khiến nhân vật đó hồi phục 1 điểm thể lực. Sau đó nếu thể lực của người đó nhỏ hơn giới hạn thể lực, thì người đó bốc hai lá bài (X là số lượng ghi nhận trong 【Phù Bình①】 của bạn +2).",
	dc_sunru: "Tôn Như",
	xiecui: "Hiệp Thúy",
	xiecui_info: "Khi có nhân vật lần đầu tiên trong lượt vì thực hiện hiệu ứng của bài mà gây sát thương, bạn có thể khiến sát thương này +1. Nếu thế lực của người đó là Ngô, thì nhân vật đó nhận được bài thực thể tương ứng với bài sát thương này, và trong lượt này giới hạn bài trên tay của người đó +1.",
	youxu: "Ưu Tuất",
	youxu_info: "Khi kết thúc lượt của nhân vật A, nếu số bài trên tay của A lớn hơn giá trị thể lực, thì bạn có thể tiết lộ một lá bài trên tay của A, sau đó đưa bài này cho một nhân vật B khác. Nếu thể lực của B là ít nhất bàn, thì B hồi phục 1 điểm thể lực.",
	huaxin: "Hoa Hân",
	wanggui: "Vọng Quy",
	wanggui_info: "Mỗi lượt giới hạn kích hoạt một lần, sau khi bạn gây ra hoặc chịu sát thương, nếu bạn: chỉ lật ngửa bài tướng này, thì bạn có thể gây 1 điểm sát thương cho một nhân vật khác thế lực với bạn; cả hai bài tướng đều lật ngửa, thì bạn có thể khiến các nhân vật cùng thế lực với bạn mỗi người bốc một lá bài.",
	spwanggui: "Vọng Quy",
	spwanggui_info: "① Khi bạn chịu sát thương, bạn có thể bốc một lá bài, hoặc cùng với một nhân vật khác cùng thế lực mỗi người bốc một lá bài; ② Mỗi lượt giới hạn một lần, khi bạn gây sát thương, bạn có thể gây 1 điểm sát thương cho một nhân vật khác thế lực với bạn.",
	xibing: "Tức Binh",
	xibing_info: "Mỗi lượt giới hạn một lần, khi nhân vật khác trong giai đoạn Xuất Bài của họ dùng 【Giết】 đen hoặc bài chú thông thường đen chỉ định một mục tiêu duy nhất, bạn có thể khiến nhân vật đó bốc bài trên tay lên bằng giá trị thể lực hiện tại (tối đa bốc đến năm lá). Nếu người đó vì vậy mà bốc bài, thì trong lượt này người đó không thể dùng bài nữa.",
	luyusheng: "Lục Uất Sinh",
	zhente: "Trinh Đặc",
	zhente2: "Trinh Đặc",
	zhente_info: "Mỗi lượt giới hạn một lần, khi bạn trở thành mục tiêu sử dụng bài cơ bản hoặc bài chú thông thường của nhân vật khác, bạn có thể khiến người sử dụng chọn một: 1. Trong lượt này không thể dùng bài cùng màu với bài này nữa; 2. Bài này vô hiệu với bạn.",
	zhente_info_guozhan: "Mỗi lượt giới hạn một lần, khi bạn trở thành mục tiêu sử dụng bài cơ bản đen hoặc bài chú thông thường đen của nhân vật khác, bạn có thể khiến người sử dụng chọn một: 1. Trong lượt này không thể dùng bài đen nữa; 2. Bài này vô hiệu với bạn.",
	zhiwei: "Chí Vi",
	zhiwei2: "Chí Vi",
	zhiwei_info: "Khi bắt đầu ván chơi / khi bắt đầu lượt của bạn, nếu trên bàn không có nhân vật đã được chọn bằng cách này còn sống, thì bạn chọn một nhân vật khác. Sau khi nhân vật đó gây sát thương, bạn bốc một lá bài, sau khi nhân vật đó chịu sát thương, bạn ngẫu nhiên bỏ một lá bài trên tay. Bài bạn bỏ ở giai đoạn Bỏ Bài đều được nhân vật đó nhận.",
	zhiwei_info_guozhan: "Khi bạn lật ngửa bài tướng này, chọn một nhân vật khác. Sau khi nhân vật đó gây sát thương, bạn bốc một lá bài, sau khi nhân vật đó chịu sát thương, bạn ngẫu nhiên bỏ một lá bài trên tay. Bài bạn bỏ ở giai đoạn Bỏ Bài đều được nhân vật đó nhận. Khi nhân vật đó chết, nếu cả hai bài tướng của bạn đều lật ngửa, bạn úp bài tướng này xuống.",
	zhanghu: "Trương Hổ",
	cuijian: "Thôi Kiên",
	cuijian_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể chọn một nhân vật khác có bài trên tay. Nếu trong bài trên tay người đó có 【Tránh】, thì người đó đưa cho bạn tất cả 【Tránh】 và bài Giáp, sau đó bạn đưa cho người đó số lượng bài tương ứng.",
	zhtongyuan: "Đồng Viện",
	zhtongyuan_info: "Kỹ năng khóa. ① Sau khi bạn dùng bài chú đỏ, bạn thêm vào sau 【Thôi Kiên】 “nếu trong bài trên tay người đó không có 【Tránh】, thì bạn bốc hai lá bài”; ② Sau khi bạn dùng hoặc đánh ra bài cơ bản đỏ, bạn xóa bỏ “, sau đó bạn đưa cho người đó số lượng bài tương ứng” trong 【Thôi Kiên】. ③ Khi bạn dùng bài chú thông thường / bài cơ bản màu đỏ, nếu bạn đã phát động 【Thôi Kiên①】 và 【Thôi Kiên②】, thì bài này không thể bị đáp trả / có thể thêm một mục tiêu bổ sung.",
	lvlingqi: "Lã Linh Kỵ",
	guowu: "Quắc Vũ",
	guowu_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể tiết lộ tất cả bài trên tay, dựa vào số loại bạn tiết lộ, bạn nhận được hiệu ứng tương ứng: ít nhất một loại, lấy từ bộ bài bỏ một 【Giết】; ít nhất hai loại, trong giai đoạn này dùng bài không giới hạn khoảng cách; ít nhất ba loại, trong giai đoạn này dùng 【Giết】 hoặc bài chú thông thường có thể chỉ định thêm tối đa hai mục tiêu.",
	guowu_info_guozhan: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể tiết lộ tất cả bài trên tay, dựa vào số loại bạn tiết lộ, bạn nhận được hiệu ứng tương ứng: ít nhất một loại, lấy từ bộ bài bỏ một 【Giết】; ít nhất hai loại, trong giai đoạn này dùng bài không giới hạn khoảng cách; ít nhất ba loại, trong giai đoạn này dùng 【Giết】 có thể chỉ định thêm tối đa hai mục tiêu (giới hạn một lần).",
	zhuangrong: "Trang Nhung",
	zhuangrong_info: "Kỹ năng giác tỉnh, khi kết thúc lượt của một nhân vật, nếu thể lực hoặc số bài trên tay bạn là 1, bạn giảm 1 điểm giới hạn thể lực và hồi phục thể lực lên giới hạn, bốc bài trên tay lên giới hạn thể lực, sau đó nhận được 【Thần Oai】 và 【Vô Song】.",
	llqshenwei: "Thần Oai",
	llqshenwei_info: "Kỹ năng khóa, khi bắt đầu giai đoạn Bốc Bài, bạn khiến số bài bốc định mức +2; giới hạn bài trên tay của bạn +2.",
	re_kanze: "Hám Trạch",
	rekuanshi: "Khoan Thích",
	rekuanshi_info: "Giai đoạn Kết Thúc, bạn có thể chọn một nhân vật. Bạn nhận được hiệu ứng sau cho đến khi bắt đầu lượt tiếp theo của bạn: mỗi lượt giới hạn một lần, khi người đó chịu điểm sát thương thứ 2 trong một lượt, người đó hồi phục 1 điểm thể lực.",
	liuyong: "Lưu Vĩnh",
	zhuning: "Truật Nịnh",
	zhuning_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể đưa một số lá bài bất kỳ cho một nhân vật khác (gọi là “Khích”), sau đó có thể xem như sử dụng một bài cơ bản / bài chú có nhãn sát thương (không tính vào giới hạn số lần). Nếu bài bạn dùng bằng cách này không gây sát thương, thì bạn đổi 【Truật Nịnh】 trong lượt này thành “giới hạn hai lần”.",
	fengxiang: "Phong Hương",
	fengxiang_info: "Kỹ năng khóa. ① Sau khi bạn chịu sát thương, nếu trên bàn: tồn tại nhân vật có “Khích” nhiều nhất duy nhất, thì người đó hồi phục 1 điểm thể lực; không tồn tại, thì bạn bốc một lá bài. ② Khi bài trên tay của nhân vật di chuyển, nếu nhân vật có “Khích” nhiều nhất trên bàn thay đổi vì điều này, thì bạn bốc một lá bài.",
	fengxiang_tag: "Khích",
	re_xunchen: "Tuân Thầm",
	refenglve: "Phong Lược",
	refenglve_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể thi điểm với một nhân vật khác. Nếu bạn thắng, bạn nhận được hai lá bài trong khu vực của người đó; nếu hòa, thì bạn nhận được lá bài thi điểm của bạn và khiến giới hạn số lần phát động của kỹ năng này trong giai đoạn này +1; nếu bạn thua, người đó nhận được lá bài thi điểm của bạn.",
	anyong: "Ám Dũng",
	anyong_info: "Sau khi một nhân vật gây sát thương lần đầu tiên trong lượt của mình, nếu giá trị sát thương là 1, thì bạn có thể bỏ một lá bài, và gây cho nhân vật bị thương 1 điểm sát thương.",
	wanniangongzhu: "Vạn Niên Công Chúa",
	zhenge: "Chẩm Qua",
	zhenge_info: "Giai đoạn Chuẩn Bị, bạn có thể chọn một nhân vật. Phạm vi tấn công của nhân vật đó trong ván chơi này +1 (tối đa +5). Sau đó nếu tất cả nhân vật khác đều nằm trong phạm vi tấn công của nhân vật đó, thì bạn có thể khiến người đó xem như sử dụng một 【Giết】 nhắm vào một nhân vật khác.",
	xinghan: "Hưng Hán",
	xinghan_info: "Kỹ năng khóa, sau khi 【Giết】 đầu tiên mỗi lượt gây sát thương, nếu người sử dụng 【Giết】 này đã từng là mục tiêu của 【Chẩm Qua】, thì bạn bốc một lá bài. Nếu số bài trên tay bạn không phải là nhiều nhất duy nhất bàn, thì đổi thành bốc X lá bài (X là phạm vi tấn công của nhân vật đó và tối đa là 5).",
	re_chendeng: "Trần Đăng",
	refuyuan: "Phù Viện",
	refuyuan_info: "Sau khi một nhân vật trở thành mục tiêu của 【Giết】, nếu trong lượt này người đó chưa từng là mục tiêu của bài đỏ nào khác, thì bạn có thể khiến người đó bốc một lá bài.",
	reyingshui: "Dinh Thuyết",
	reyingshui_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể đưa một lá bài cho một nhân vật khác trong phạm vi tấn công, sau đó người đó chọn một: ① Đưa cho bạn ít nhất hai lá bài Trang Bị. ② Chịu 1 điểm sát thương.",
	rewangzu: "Vọng Tộc",
	rewangzu_info: "Mỗi lượt giới hạn một lần. Khi bạn chịu sát thương do nhân vật khác gây ra, bạn có thể ngẫu nhiên bỏ một lá bài trên tay, khiến sát thương này -1. Nếu số nhân vật còn sống trong phe của bạn là nhiều nhất bàn, thì bạn có thể tự chọn lá bài để bỏ.",
	re_miheng: "Di Hành",
	rekuangcai: "Cuồng Tài",
	rekuangcai_info: "Kỹ năng khóa. ① Bạn dùng bài trong lượt không giới hạn khoảng cách và số lần. ② Khi bắt đầu giai đoạn Bỏ Bài, nếu trong lượt này bạn: chưa dùng bài, thì giới hạn bài trên tay của bạn trong ván chơi này +1; đã dùng bài nhưng chưa gây sát thương, thì giới hạn bài trên tay của bạn trong ván chơi này -1. ③ Khi bắt đầu giai đoạn Kết Thúc, bạn bốc X lá bài (X là sát thương bạn đã gây ra trong lượt này và tối đa là 5).",
	reshejian: "Thiệt Kiếm",
	reshejian_info: "Mỗi lượt giới hạn hai lần. Khi bạn trở thành mục tiêu duy nhất sử dụng bài của nhân vật khác, bạn có thể bỏ ít nhất hai lá bài trên tay. Nếu làm vậy, bạn chọn một: ⒈ Bỏ số lượng bài tương ứng của người đó. ⒉ Gây cho người đó 1 điểm sát thương.",
	fengxi: "Phùng Hy",
	yusui: "Ngọc Toái",
	yusui_info: "Mỗi lượt giới hạn một lần, khi bạn trở thành mục tiêu sử dụng bài đen của nhân vật khác, bạn có thể mất 1 điểm thể lực, sau đó chọn một: ⒈ Khiến người đó bỏ bài trên tay xuống bằng với bạn; ⒉ Khiến người đó mất Y điểm thể lực (Y là thể lực của người đó trừ đi thể lực của bạn, không chọn được nếu không dương).",
	boyan: "Bác Ngôn",
	boyan_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể chọn một nhân vật khác. Người đó bốc bài trên tay lên giới hạn thể lực (tối đa bốc đến năm lá), sau đó trong lượt này người đó không thể dùng hoặc đánh ra bài trên tay.",
	re_dengzhi: "Đặng Chi",
	jianliang: "Giản Lượng",
	jianliang_info: "Khi bắt đầu giai đoạn Bốc Bài, nếu số bài trên tay bạn không phải là nhiều nhất bàn, thì bạn có thể khiến tối đa hai nhân vật mỗi người bốc một lá bài.",
	weimeng: "Nguy Minh",
	weimeng_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể nhận tối đa X lá bài trên tay của một nhân vật khác, sau đó đưa cho người đó số lượng bài tương ứng (X là thể lực của bạn). Nếu tổng điểm số bài bạn đưa ra: lớn hơn bài nhận được, thì bạn bốc một lá bài; nhỏ hơn bài nhận được, bỏ một lá bài trong khu vực của nhân vật đó.",
	mamidi: "Mã Nhật Đê",
	bingjie: "Bỉnh Tiết",
	bingjie_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể giảm 1 điểm giới hạn thể lực, sau đó khi bạn dùng 【Giết】 hoặc bài chú thông thường chỉ định nhân vật khác làm mục tiêu trong lượt này, người đó bỏ một lá bài. Nếu lá bài người đó bỏ cùng màu với bài bạn dùng, người đó không thể đáp trả bài này.",
	zhengding: "Chính Đính",
	zhengding_info: "Kỹ năng khóa. Khi bạn dùng hoặc đánh ra bài ngoài lượt để đáp trả bài do nhân vật khác sử dụng, nếu hai lá bài này cùng màu, thì bạn tăng 1 điểm giới hạn thể lực và hồi phục 1 điểm thể lực.",
	dc_jiben: "Cát Bản",
	xunli: "Tuân Lệ",
	xunli_info: "Kỹ năng khóa. ① Khi có bài đen bị bỏ và vào bộ bài bỏ, nếu X lớn hơn 0, thì bạn đặt X lá bài trong số đó lên bài tướng làm “Lệ” (X = min(số lượng các bài này, 9-Y), Y = số “Lệ” của bạn). ② Khi bắt đầu giai đoạn Xuất Bài, bạn có thể đổi một số lượng bài đen trên tay bất kỳ lấy số lượng “Lệ” tương ứng.",
	zhishi: "Chỉ Thệ",
	zhishi_info: "Giai đoạn Kết Thúc, bạn có thể chọn một nhân vật. Khi nhân vật đó trước khi bắt đầu lượt tiếp theo của bạn {trở thành mục tiêu của 【Giết】 hoặc vào trạng thái hấp hối}, bạn có thể bỏ một số lượng “Lệ” bất kỳ, sau đó người đó bốc số lượng bài tương ứng.",
	lieyi: "Liệt Y",
	lieyi_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể tiết lộ tất cả “Lệ” và chọn một nhân vật khác, dùng một lá bài có thể dùng nhắm vào người đó trong số đó (không giới hạn khoảng cách và số lần) và lặp lại quy trình này, và đặt những lá bài còn lại vào bộ bài bỏ. Sau đó nếu người đó còn sống và chưa từng vào trạng thái hấp hối vì chịu sát thương trong quy trình này, thì bạn mất 1 điểm thể lực.",
	guanning: "Quản Ninh",
	dunshi: "Độn Thế",
	dunshi_info: "Mỗi lượt giới hạn một lần. Bạn có thể xem như sử dụng hoặc đánh ra một 【Giết】/【Tránh】/【Đào】/【Rượu】, sau đó khi nhân vật trong lượt hiện tại gây sát thương lần tiếp theo, bạn chọn hai hạng mục: ⒈ Ngăn ngừa sát thương này. Hệ thống chọn ngẫu nhiên ba kỹ năng có chứa chữ “Nhân/Nghĩa/Lễ/Trí/Tín” trong tên kỹ năng mà người đó chưa có, sau đó bạn khiến nhân vật trong lượt hiện tại nhận được một kỹ năng trong số đó. ⒉ Xóa bài bạn vừa dùng hoặc đánh ra khỏi 【Độn Thế】 và nhận được một “Tịch”. ⒊ Giảm 1 điểm giới hạn thể lực và bốc X lá bài (X là số “Tịch” của bạn).",
	dc_gaolan: "Cao Lãm",
	xizhen: "Tập Trận",
	xizhen_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể chọn một nhân vật khác, xem như sử dụng 【Giết】 hoặc 【Quyết Đấu】 nhắm vào người đó. Sau đó khi có nhân vật trong giai đoạn này dùng hoặc đánh ra bài để đáp trả bạn, nhân vật đó hồi phục 1 điểm thể lực, bạn bốc một lá bài (nếu người đó đầy thể lực, đổi thành hai lá).",
	dc_huangchengyan: "Hoàng Thừa Ngạn",
	dcjiezhen: "Giải Trận",
	dcjiezhen_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể chọn một nhân vật khác. Nhân vật đó nhận được 【Bát Trận】, và tất cả các kỹ năng không phải {kỹ năng khóa, kỹ năng giới hạn, kỹ năng giác tỉnh, kỹ năng chủ công, kỹ năng có nhãn Charlotte} của người đó mất hiệu lực. Khi bắt đầu lượt tiếp theo của bạn, hoặc sau khi phán định do 【Bát Quái Trận】 của người đó khởi xướng kết toán xong, bạn khiến người đó khôi phục tất cả kỹ năng đã mất hiệu lực bằng cách này và mất 【Bát Trận】 nhận được bằng cách này, sau đó nhận được một lá bài trong khu vực của người đó.",
	dczecai: "Trạch Tài",
	dczecai_info: "Kỹ năng giới hạn. Khi kết thúc mỗi vòng, bạn có thể khiến một nhân vật khác nhận được 【Tập Trí】 cho đến khi kết thúc vòng tiếp theo; nếu người đó là nhân vật có số lượng bài chú đã sử dụng nhiều nhất duy nhất trong vòng này, thì người đó thực hiện một lượt bổ sung.",
	dcyinshi: "Ẩn Thế",
	dcyinshi_info: "Kỹ năng khóa. ① Mỗi lượt giới hạn một lần, khi bạn chịu sát thương, nếu kênh của sát thương này không phải là bài có màu sắc, thì bạn ngăn ngừa sát thương này. ② Khi lá bài phán định của phán định do 【Bát Quái Trận】 khởi xướng có hiệu lực, bạn nhận được lá bài phán định này.",
	tenggongzhu: "Đằng Công Chúa",
	xingchong: "Hạnh Sủng",
	xingchong_info: "Khi bắt đầu mỗi vòng, bạn có thể tuyên bố hai số tự nhiên X và Y, và (X+Y) ≤ min(5, giới hạn thể lực của bạn). Bạn bốc X lá bài và tiết lộ Y lá bài trên tay. Nếu làm vậy, khi bạn mất một lá bài đã tiết lộ bằng cách này trong vòng này, bạn bốc hai lá bài.",
	liunian: "Lưu Niên",
	liunian_info: "Kỹ năng khóa. Khi kết thúc lượt của một nhân vật, nếu trong lượt này đã diễn ra lần xào bài đầu tiên của ván chơi này, thì bạn tăng 1 điểm giới hạn thể lực; nếu trong lượt này đã diễn ra lần xào bài thứ hai của ván chơi này, thì bạn hồi phục 1 điểm thể lực khi kết thúc lượt này, và giới hạn bài trên tay trong ván chơi này +10.",
	caimaozhangyun: "Thái Mạo Trương Doãn",
	lianzhou: "Liên Chu",
	lianzhou_info: "Kỹ năng khóa. Giai đoạn Chuẩn Bị, bạn liên hoàn bài tướng của bạn. Sau đó bạn có thể liên hoàn một số lượng nhân vật bất kỳ có giá trị thể lực bằng bạn.",
	jinglan: "Kinh Lan",
	jinglan_info: "Kỹ năng khóa. Sau khi bạn gây sát thương, nếu số bài trên tay bạn: lớn hơn thể lực, bạn bỏ bốn lá bài trên tay; bằng thể lực, bạn bỏ một lá bài và hồi phục 1 điểm thể lực; nhỏ hơn thể lực, bạn chịu 1 điểm sát thương Hỏa không rõ nguồn gốc và bốc năm lá bài.",
	dc_yanghu: "Dương Hỗ",
	dcdeshao: "Đức Thiệu",
	dcdeshao_info: "Mỗi lượt giới hạn hai lần. Khi bạn trở thành mục tiêu sử dụng bài đen của nhân vật khác, bạn có thể bốc một lá bài, sau đó nếu số bài trên tay người đó không nhỏ hơn bạn, thì bạn bỏ một lá bài của người đó.",
	dcmingfa: "Minh Phạt",
	dcmingfa_info: "① Giai đoạn Xuất Bài giới hạn một lần. Khi bạn dùng 【Giết】 hoặc bài chú thông thường kết toán xong, nếu trên bài tướng bạn không có bài “Minh Phạt”, thì bạn có thể đặt bài này lên bài tướng làm bài “Minh Phạt” và chọn một nhân vật khác, ghi nhớ nhân vật đó và tên bài này. ② Khi kết thúc lượt của một nhân vật, nếu người đó là nhân vật được 【Minh Phạt①】 ghi nhớ, thì bạn xem như lần lượt dùng X 【Minh Phạt①】 đã ghi nhớ nhắm vào người đó, sau đó bỏ bài “Minh Phạt” (X là số bài trên tay của người đó và ít nhất là 1, tối đa là 5). ③ Khi một nhân vật chết, nếu người đó là nhân vật được 【Minh Phạt①】 ghi nhớ, thì bạn bỏ bài “Minh Phạt”.",
	dc_jiling: "Kỷ Linh",
	dcshuangren: "Song Nhận",
	dcshuangren_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể thi điểm với một nhân vật khác A. Nếu bạn thắng, bạn chọn một nhân vật B, hoặc chọn hai nhân vật A và B bao gồm A (thế lực của B cần phải giống với A), sau đó xem như sử dụng một 【Giết】 nhắm vào (các) nhân vật được chọn (không tính vào giới hạn số lần); nếu bạn không thắng, thì bạn không thể dùng 【Giết】 trong giai đoạn này.",
	zhangxun: "Trương Huân",
	suizheng: "Tùy Chinh",
	suizheng_info: "Giai đoạn Kết Thúc, bạn có thể chọn một nhân vật A, nhận được hiệu ứng sau cho đến khi kết thúc lượt tiếp theo của A: ① A trong giai đoạn Xuất Bài của lượt tiếp theo, giới hạn số lần dùng 【Giết】 +2 và không giới hạn khoảng cách; ② Khi kết thúc giai đoạn Xuất Bài của A ở lượt tiếp theo, bạn có thể chọn một nhân vật B đã chịu sát thương do A gây ra trong giai đoạn này, xem như sử dụng một 【Giết】 nhắm vào B.",
	dc_liuba: "Lưu Ba",
	dczhubi: "Chú Tệ",
	dczhubi_info: "Khi có bài ♦ bị bỏ và vào bộ bài bỏ, bạn có thể khiến hệ thống tìm kiếm một 【Vô Trung Sinh Hữu】 từ bộ bài / bộ bài bỏ, và đặt bài này lên đỉnh bộ bài.",
	dcliuzhuan: "Lưu Chuyển",
	dcliuzhuan_tag: "Chuyển",
	dcliuzhuan_info: "Kỹ năng khóa. ① Bài mà nhân vật khác nhận được không phải ở giai đoạn Bốc Bài trong lượt của họ gọi là “Chuyển”. ② Bạn không thể trở thành mục tiêu của bài mà bài thực thể có chứa “Chuyển”. ③ Khi “Chuyển” trực tiếp vào bộ bài bỏ hoặc qua khu vực Xử Lý vào bộ bài bỏ, bạn nhận được nó.",
	huzhao: "Hồ Chiêu",
	midu: "Di Đốc",
	midu_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể chọn một hạng mục: ⒈ Phế bỏ một số lượng ô trang bị hoặc khu vực Phán Định bất kỳ, và khiến một nhân vật bốc số lượng bài tương ứng. ⒉ Khôi phục một ô trang bị hoặc khu vực Phán Định đã bị phế bỏ, sau đó bạn nhận được 【Hoạt Mặc】 cho đến khi bắt đầu lượt tiếp theo.",
	xianwang: "Hiền Vọng",
	xianwang_info: "Kỹ năng khóa. Nếu bạn có ô trang bị bị phế bỏ, thì khoảng cách từ nhân vật khác đến bạn +1, khoảng cách từ bạn đến nhân vật khác -1; nếu số ô trang bị bị phế bỏ lớn hơn 2, thì đổi thành khoảng cách +2/-2.",
	guanhai: "Quản Hải",
	suoliang: "Sách Lương",
	suoliang_info: "Mỗi lượt giới hạn một lần. Sau khi bạn gây sát thương cho nhân vật khác, bạn có thể chọn và tiết lộ tối đa X lá bài của người đó (X là giới hạn thể lực của người đó và tối đa là 5). Nếu trong những lá bài này có bài ♥ hoặc ♣, thì bạn nhận được những lá bài này; nếu không thì bạn bỏ những lá bài này.",
	qinbao: "Xâm Bạo",
	qinbao_info: "Kỹ năng khóa. Khi bạn dùng 【Giết】 hoặc bài chú thông thường, bạn khiến tất cả nhân vật có số bài trên tay không nhỏ hơn bạn không thể đáp trả bài này.",
	dc_lvkuanglvxiang: "Lã Khoáng Lã Tường",
	dcshuhe: "Số Hợp",
	dcshuhe_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể tiết lộ một lá bài trên tay và nhận được một dấu hiệu “Tước”. Nếu trên bàn có bài cùng điểm số với lá bài này, thì bạn nhận được những bài đó; nếu không thì bạn đưa lá bài này cho một nhân vật khác.",
	dcliehou: "Liệt Hầu",
	dcliehou_info: "Kỹ năng khóa. Khi bắt đầu giai đoạn Bốc Bài, bạn khiến số bài bốc định mức +X; sau đó khi kết thúc giai đoạn Bốc Bài này, bạn chọn một: ⒈ Bỏ X lá bài. ⒉ Mất 1 điểm thể lực (X là số “Tước” của bạn +1 và tối đa là 5).",
	yinfuren: "Doanh Phu Nhân",
	dcyingyu: "Thằng Dữ",
	dcyingyu_info: "Khi bắt đầu giai đoạn Chuẩn Bị, bạn có thể tiết lộ mỗi người một lá bài trên tay của hai nhân vật. Nếu hai lá bài này khác hoa, thì bạn có thể khiến một nhân vật nhận được lá bài đã tiết lộ của nhân vật kia.",
	dcyongbi: "Ủng Bế",
	dcyongbi_info: "Kỹ năng giới hạn. Giai đoạn Xuất Bài, bạn có thể đưa tất cả bài trên tay cho một nhân vật nam khác. Bạn đổi thời điểm phát động của 【Thằng Dữ】 thành “khi bắt đầu giai đoạn Chuẩn Bị và giai đoạn Kết Thúc”. Sau đó nếu số hoa có trong những bài này: lớn hơn 1, thì bạn và người đó trong ván chơi này giới hạn bài trên tay +2; lớn hơn 2, thì khi bạn hoặc người đó chịu sát thương lớn hơn 1 trong ván chơi này, sát thương này -1.",
	dc_huangquan: "Hoàng Quyền",
	dcquanjian: "Khuyến Gián",
	dcquanjian_info: "Giai đoạn Xuất Bài mỗi hạng mục giới hạn một lần. Bạn có thể chọn một quy trình và chọn một nhân vật khác A: ⒈ Khiến A gây 1 điểm sát thương cho một nhân vật B khác trong phạm vi tấn công của A. ⒉ Khiến A điều chỉnh số bài trên tay lên giới hạn bài trên tay (tối đa bốc đến năm lá), và trong lượt này A không thể dùng bài trên tay. Sau đó A chọn một: ⒈ Thực hiện quy trình này. ⒉ Sát thương lần tiếp theo trong lượt này phải chịu +1.",
	dctujue: "Đồ Tuyệt",
	dctujue_info: "Kỹ năng giới hạn. Khi bạn vào trạng thái hấp hối, bạn có thể đưa tất cả bài cho một nhân vật khác. Sau đó bạn hồi phục X điểm thể lực và bốc X lá bài (X là số lượng bài bạn đưa cho người đó bằng cách này, và ít nhất là 5).",
	dctujue_append: '<span style="font-family: yuanli"><li>Lời nhắc nhở:<br>Giá trị thể lực của Hoàng Quyền và 【Đồ Tuyệt】 trong bản hiện tại của Vô Danh Sát đều là bản Hải Ngoại</span>',
	chengui: "Trần Khuê",
	dcyingtu: "Doanh Đồ",
	dcyingtu_info: "Mỗi lượt giới hạn một lần. Khi nhà trên / nhà dưới của bạn nhận được bài ngoài giai đoạn Bốc Bài, bạn có thể nhận một lá bài của người đó, sau đó đưa một lá bài cho nhà dưới / nhà trên của bạn. Nếu lá bài bạn đưa ra là bài Trang Bị, thì người đó sử dụng nó.",
	dccongshi: "Tòng Thế",
	dccongshi_info: "Kỹ năng khóa. Sau khi bài Trang Bị được một nhân vật sử dụng kết toán xong, nếu số bài trong khu vực Trang Bị của người đó là nhiều nhất bàn, thì bạn bốc một lá bài.",
	wanglie: "Vương Liệt",
	dcchongwang: "Sùng Vọng",
	dcchongwang_info: "Khi nhân vật khác sử dụng bài cơ bản hoặc bài chú thông thường, nếu bạn là người sử dụng của lá bài trước đó được sử dụng trong ván chơi này, thì bạn có thể chọn một: ⒈ Khiến người đó sau khi bài này kết toán xong sẽ thu hồi lại tất cả bài thực thể tương ứng của bài này; ⒉ Khiến bài này vô hiệu.",
	dchuagui: "Hóa Quy",
	dchuagui_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể chọn tối đa X nhân vật khác có bài (X là số nhân vật còn sống của phe có số nhân vật còn sống nhiều nhất và các nhân vật bạn chọn không hiển thị với nhân vật khác). Các nhân vật này đồng thời chọn một: ⒈ Đưa cho bạn một lá bài, ⒉ Tiết lộ một lá bài. Nếu tất cả các nhân vật này đều chọn hạng mục hai, thì bạn nhận được tất cả bài đã tiết lộ.",
	gongsundu: "Công Tôn Độ",
	dczhenze: "Chấn Trạch",
	dczhenze_info: "Khi bắt đầu giai đoạn Bỏ Bài, bạn có thể chọn một: 1. Khiến tất cả nhân vật có mối quan hệ giữa số bài trên tay và giá trị thể lực khác với bạn mất 1 điểm thể lực; 2. Khiến tất cả nhân vật có mối quan hệ giữa số bài trên tay và giá trị thể lực giống với bạn hồi phục 1 điểm thể lực.",
	dcanliao: "An Liêu",
	dcanliao_info: "Giai đoạn Xuất Bài giới hạn X lần (X là số nhân vật thế lực Quần). Bạn có thể tái luyện một lá bài của một nhân vật.",
	dc_yuejiu: "Lạc Cứu",
	dccuijin: "Xúc Tiến",
	dccuijin_info: "Khi bạn hoặc nhân vật trong phạm vi tấn công của bạn dùng 【Giết】 hoặc 【Quyết Đấu】, bạn có thể bỏ một lá bài, khiến lượng sát thương cơ bản của bài này +1. Sau đó khi bài này bị nhân vật mục tiêu đáp trả hoặc vô hiệu hoặc ngăn ngừa sát thương, bạn bốc hai lá bài và gây cho người sử dụng 1 điểm sát thương.",
	panghui: "Bàng Hội",
	dcyiyong: "Dị Dũng",
	dcyiyong_info: "Khi bạn gây sát thương cho nhân vật khác, nếu bạn có bài, bạn có thể cùng với người đó đồng thời bỏ ít nhất một lá bài. Nếu tổng điểm số bài bạn bỏ bằng cách này: không lớn hơn người đó, bạn bốc X+1 lá bài; không nhỏ hơn người đó, sát thương này +1 (X là số bài người đó bỏ bằng cách này).",
	dcsuchou: "Túc Thù",
	dcsuchou_info: "Kỹ năng khóa, khi bắt đầu giai đoạn Xuất Bài, bạn chọn một: ① Mất 1 điểm thể lực hoặc giảm 1 điểm giới hạn thể lực, trong giai đoạn này dùng bài không thể bị đáp trả; ② Mất 【Túc Thù】.",
	chenjiao: "Trần Kiểu",
	dcxieshoux: "Hiệp Thủ / Thanh Nghiêm",
	dcxieshou: "Hiệp Thủ",
	dcxieshou_info: "Mỗi lượt giới hạn một lần. Sau khi một nhân vật chịu sát thương, nếu khoảng cách từ bạn đến người đó không lớn hơn 2, bạn có thể khiến giới hạn bài trên tay của bạn -1, sau đó người đó chọn một: 1. Hồi phục 1 điểm thể lực; 2. Khôi phục, bốc hai lá bài.",
	dcqingyan: "Thanh Nghiêm",
	dcqingyan_info: "Mỗi lượt giới hạn hai lần. Khi bạn trở thành mục tiêu sử dụng bài đen của nhân vật khác, nếu số bài trên tay bạn: nhỏ hơn thể lực, bạn có thể bổ sung bài trên tay lên giới hạn thể lực; không nhỏ hơn thể lực, bạn có thể bỏ một lá bài để khiến giới hạn bài trên tay của bạn +1.",
	dcqizi: "Khí Tử",
	dcqizi_info: "Kỹ năng khóa. Bạn không thể dùng 【Đào】 cho nhân vật đang trong quy trình hấp hối có khoảng cách từ bạn đến người đó lớn hơn 2.",
	leibo: "Lôi Bạc",
	dcsilve: "Tư Lược",
	dcsilve_info: "Khi bắt đầu ván chơi, bạn chọn một nhân vật khác (không hiển thị với nhân vật khác), gọi là nhân vật “Tư Lược”. Sau đó bạn nhận được các hiệu ứng sau: ① Khi nhân vật “Tư Lược” gây sát thương, nếu bạn trong lượt này chưa vì hiệu ứng này mà nhận được bài của nhân vật bị thương, bạn có thể nhận một lá bài của nhân vật bị thương; ② Khi nhân vật “Tư Lược” chịu sát thương do nhân vật khác gây ra, nếu nguồn gây sát thương còn sống, bạn phải dùng một 【Giết】 nhắm vào nguồn gây sát thương (không giới hạn khoảng cách), nếu không thì bạn bỏ một lá bài trên tay.",
	dcshuaijie: "Suy Kiếp",
	dcshuaijie_info: "Kỹ năng giới hạn. Giai đoạn Xuất Bài, nếu thể lực và số bài trong khu vực Trang Bị của bạn đều lớn hơn nhân vật “Tư Lược”, hoặc không có nhân vật nào có “Tư Lược”, bạn có thể giảm 1 điểm giới hạn thể lực, sau đó chọn một: 1. Nhận tối đa ba lá bài của nhân vật “Tư Lược”; 2. Ngẫu nhiên lấy từ bộ bài ba lá bài có loại khác nhau. Cuối cùng đổi nhân vật “Tư Lược” của bạn thành bạn.",
	dc_sp_jiaxu: "Tân Sát SP Giả Hủ",
	dc_sp_jiaxu_prefix: "Tân Sát SP",
	dcjianshu: "Gian Thư",
	dcjianshu_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể đưa một lá bài đen trên tay cho một nhân vật khác, và chọn một nhân vật khác nữa, bạn khiến người thứ nhất thi điểm với người thứ hai. Nhân vật thắng ngẫu nhiên bỏ một lá bài, nhân vật thua mất 1 điểm thể lực. Nếu có nhân vật chết vì điều này, bạn khiến giới hạn số lần phát động 【Gian Thư】 của bạn trong giai đoạn này +1.",
	dcyongdi: "Ủng Đích",
	dcyongdi_info: "Kỹ năng giới hạn. Giai đoạn Xuất Bài, bạn có thể chọn một nhân vật nam, nếu người đó: có giới hạn thể lực hoặc giá trị thể lực ít nhất, người đó tăng 1 điểm giới hạn thể lực và hồi phục 1 điểm thể lực; có số bài trên tay ít nhất, người đó bốc X lá bài (X là giới hạn thể lực của người đó và tối đa là 5).",
	liupi: "Tân Sát Lưu Bích",
	liupi_prefix: "Tân Sát",
	dcjuying: "Cứ Doanh",
	dcjuying_info: "Khi kết thúc giai đoạn Xuất Bài, nếu số lần bạn dùng 【Giết】 hoặc 【Rượu】 trong giai đoạn này chưa đạt giới hạn, bạn có thể chọn bất kỳ hạng mục nào: 1. Giới hạn số lần dùng 【Giết】 ở lượt tiếp theo +1; 2. Giới hạn bài trên tay trong lượt này +2; 3. Bốc ba lá bài. Nếu số hạng mục bạn chọn vượt quá thể lực của bạn, bạn bỏ một lá bài.",
	dc_huanghao: "Tân Sát Hoàng Hạo",
	dc_huanghao_prefix: "Tân Sát",
	dcqinqing: "Tẩm Tình",
	dcqinqing_info: "Giai đoạn Kết Thúc, bạn có thể bỏ một lá bài của một nhân vật khác có phạm vi tấn công bao gồm vị trí số một. Sau đó nếu số bài trên tay người đó lớn hơn vị trí số một, bạn bốc một lá bài.",
	dccunwei: "Tồn Úy",
	dccunwei_info: "Kỹ năng khóa. Khi bạn trở thành mục tiêu của bài chú, nếu bạn là mục tiêu duy nhất, bạn bốc một lá bài; nếu không thì bạn bỏ một lá bài.",
	dc_zhaotongzhaoguang: "Triệu Thống Triệu Quảng",
	dcqingren: "Thanh Nhận",
	dcqingren_info: "Giai đoạn Kết Thúc, bạn có thể bốc X lá bài (X là số lần bạn phát động 【Dực Tán】 trong lượt này).",
	dclongyuan: "Long Uyên",
	dclongyuan_info: "Kỹ năng giác tỉnh. Khi kết thúc lượt của một nhân vật, nếu bạn đã phát động ít nhất ba lần 【Dực Tán】 trong ván chơi này, bạn bốc hai lá bài và hồi phục 1 điểm thể lực, sửa đổi 【Dực Tán】.",
	zhenghun: "Trịnh Hồn",
	dcqiangzhi: "Cường Trì",
	dcqiangzhi_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể bỏ tổng cộng ba lá bài của bạn và một nhân vật khác. Sau đó nếu trong số bạn và người đó có nhân vật vì vậy mà mất ba lá bài, nhân vật đó gây 1 điểm sát thương cho nhân vật kia.",
	dcpitian: "Tịch Điền",
	dcpitian_info: "① Khi bài của bạn bị bỏ, hoặc khi bạn chịu sát thương, giới hạn bài trên tay của bạn +1. ② Giai đoạn Kết Thúc, nếu số bài trên tay bạn nhỏ hơn giới hạn bài trên tay, bạn có thể bốc lên đến giới hạn bài trên tay (tối đa bốc năm lá), sau đó thiết lập lại giới hạn bài trên tay đã tăng vì 【Tịch Điền①】.",
	furongfuqian: "Phó Nhung Phó Thiêm",
	dcxuewei: "Huyết Vệ",
	dcxuewei_info: "Giai đoạn Kết Thúc, bạn có thể chọn một nhân vật có thể lực không lớn hơn bạn, sau đó bạn nhận được hiệu ứng sau cho đến khi bắt đầu lượt tiếp theo của bạn: khi người đó chịu sát thương, ngăn ngừa sát thương này, sau đó bạn mất 1 điểm thể lực, bạn và người đó mỗi người bốc một lá bài (nếu nhân vật đó là bạn, thì đổi thành bạn bốc một lá bài).",
	dcyuguan: "Ngự Quan",
	dcyuguan_info: "Khi kết thúc lượt của một nhân vật, nếu thể lực đã mất của bạn là nhiều nhất bàn, bạn có thể giảm 1 điểm giới hạn thể lực, sau đó khiến tối đa X nhân vật bốc bài trên tay lên giới hạn thể lực (X là thể lực đã mất của bạn).",
	qinlang: "Tần Lãng",
	dchaochong: "Hạo Sủng",
	dchaochong_info: "Sau khi bạn dùng bài, bạn có thể bốc hoặc bỏ bài trên tay xuống bằng giới hạn bài trên tay của bạn (tối đa bốc năm lá). Sau đó nếu bạn bằng cách này: nhận được bài, giới hạn bài trên tay của bạn -1; mất bài, giới hạn bài trên tay của bạn +1.",
	dcjinjin: "Căng Cẩn",
	dcjinjin_info: "Mỗi lượt giới hạn hai lần. Sau khi bạn gây ra hoặc chịu sát thương, bạn có thể thiết lập lại giới hạn bài trên tay đã tăng hoặc giảm vì 【Hạo Sủng】, khiến nguồn gây sát thương bỏ tối đa X lá bài, sau đó bạn bốc Y lá bài (X là giới hạn bài trên tay đã thay đổi bằng cách này của bạn và ít nhất là 1, Y là X trừ đi số bài người đó bỏ bằng cách này).",
	xianglang: "Hướng Lãng",
	dckanji: "Khám Tập",
	dckanji_info: "Giai đoạn Xuất Bài giới hạn hai lần. Bạn có thể tiết lộ tất cả bài trên tay, nếu các hoa đều khác nhau, bạn bốc hai lá bài. Sau đó nếu bài trên tay bạn vì vậy bao gồm bốn loại hoa, bạn bỏ qua giai đoạn Bỏ Bài tiếp theo.",
	dcqianzheng: "Khiên Chính",
	dcqianzheng_info: "Mỗi lượt giới hạn hai lần. Khi bạn trở thành mục tiêu sử dụng 【Giết】 hoặc bài chú thông thường của nhân vật khác, bạn có thể tái luyện hai lá bài. Nếu trong số bài bạn tái luyện bằng cách này không có bài cùng loại với bài đã chỉ định bạn làm mục tiêu, thì sau khi bài thực thể tương ứng của bài này vào bộ bài bỏ, bạn nhận được tất cả bài thực thể tương ứng của bài này.",
	qiaorui: "Kiều Thụy",
	dcaishou: "Ái Thủ",
	dcaishou_tag: "Ái",
	dcaishou_info: "① Giai đoạn Kết Thúc, bạn có thể bốc X lá bài, gọi là “Ái” (X là giới hạn thể lực của bạn). ② Giai đoạn Chuẩn Bị, bạn bỏ tất cả “Ái”, nếu số bài bạn bỏ bằng cách này lớn hơn thể lực và giới hạn thể lực của bạn nhỏ hơn 9, bạn tăng 1 điểm giới hạn thể lực. ③ Khi bạn mất “Ái” cuối cùng ngoài lượt của mình, bạn giảm 1 điểm giới hạn thể lực.",
	dcsaowei: "Tảo Vi",
	dcsaowei_info: "Sau khi một nhân vật khác dùng 【Giết】 kết toán xong, nếu nhân vật mục tiêu của bài này không bao gồm bạn và đều nằm trong phạm vi tấn công của bạn, bạn có thể dùng một “Ái” xem như 【Giết】 sử dụng cho tất cả nhân vật mục tiêu. Sau khi 【Giết】 chuyển hóa bằng cách này kết toán xong, nếu 【Giết】 này đã gây sát thương, bạn nhận được bài thực thể tương ứng của 【Giết】 này.",
	yuantanyuanxiyuanshang: "Viên Đàm Viên Thượng Viên Hi",
	dcneifa: "Nội Phạt",
	dcneifa_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể bốc ba lá bài, sau đó bỏ một lá bài. Nếu loại bài bạn bỏ là: bài cơ bản, trong giai đoạn này bạn không thể dùng bài chú, và giới hạn số lần sử dụng 【Giết】 +X và có thể chỉ định thêm một mục tiêu; bài chú, trong giai đoạn này bạn không thể dùng bài cơ bản, và khi dùng bài chú thông thường chọn mục tiêu có thể thêm hoặc bớt một mục tiêu (X là số lượng bài không thể dùng vì 【Nội Phạt】 trong bài trên tay bạn sau khi bỏ bài và tối đa là 5. Các mục tiêu bổ sung bạn chọn bằng cách này đều không giới hạn khoảng cách).",
	dc_sunziliufang: "Tân Sát Tôn Tư Lưu Phóng",
	dc_sunziliufang_prefix: "Tân Sát",
	dcqinshen: "Cần Thận",
	dcqinshen_info: "Khi kết thúc giai đoạn Bỏ Bài, bạn có thể bốc X lá bài (X là số hoa chưa từng vào bộ bài bỏ trong lượt này).",
	dcweidang: "Nguy Đảng",
	dcweidang_info: "Giai đoạn Kết Thúc của nhân vật khác, bạn có thể đặt một lá bài có số chữ là X dưới đáy bộ bài, sau đó nhận được một lá bài có số chữ là X từ trong bộ bài (X là số hoa chưa từng vào bộ bài bỏ trong lượt này). Nếu bạn có thể dùng bài này, bạn dùng nó.",
	mengjie: "Mạnh Tiết",
	dcyinlu: "Dẫn Lộ",
	dcyinlu_info: "① Khi bắt đầu ván chơi, bạn khiến ba nhân vật lần lượt nhận được dấu hiệu “Nhạc Tuyền”, “Hoắc Khê”, “Chướng Khí” (nếu số nhân vật trên bàn là 2 thì đổi thành khiến một nhân vật khác nhận 2 trong số đó, bạn nhận dấu hiệu còn lại), sau đó bạn nhận được dấu hiệu “Vân Hương” và nhận được 1 điểm giá trị “Vân Hương”. ② Giai đoạn Chuẩn Bị / khi nhân vật có dấu hiệu 【Dẫn Lộ】 chết, bạn có thể di chuyển 1 dấu hiệu của một nhân vật / tất cả dấu hiệu 【Dẫn Lộ】 của người đó.",
	dcyinlu_lequan: "Nhạc Tuyền",
	dcyinlu_lequan_info: "Giai đoạn Kết Thúc, bạn có thể bỏ một lá bài ♦, sau đó hồi phục 1 điểm thể lực.",
	dcyinlu_huoxi: "Hoắc Khê",
	dcyinlu_huoxi_info: "Giai đoạn Kết Thúc, bạn có thể bỏ một lá bài ♥, sau đó bốc hai lá bài.",
	dcyinlu_zhangqi: "Chướng Khí",
	dcyinlu_zhangqi_info: "Kỹ năng khóa. Giai đoạn Kết Thúc, bạn phải bỏ một lá bài ♠, nếu không thì mất 1 điểm thể lực.",
	dcyinlu_yunxiang: "Vân Hương",
	dcyinlu_yunxiang_info: "① Giai đoạn Kết Thúc, bạn có thể bỏ một lá bài ♣, nhận được 1 điểm giá trị “Vân Hương”. ② Khi bạn chịu sát thương, bạn có thể khấu trừ tất cả giá trị “Vân Hương”, giảm sát thương tương ứng.",
	dcyouqi: "Uu Thê",
	dcyouqi_info: "Kỹ năng khóa. Khi nhân vật khác vì dấu hiệu 【Dẫn Lộ】 bỏ bài, bạn có một xác suất nhất định nhận được bài này.",
	dcyouqi_faq: "〖Uu Thê〗 Xác suất<br>",
	dcyouqi_faq_info: "Khi thỏa mãn điều kiện của 【Uu Thê】, hệ thống sinh ra một số ngẫu nhiên X∈[0,1). Nếu X nhỏ hơn (1.25-0.25Y), hoặc chế độ Lucky Star đã bật, bạn nhận được bài này (Y là khoảng cách từ bạn đến nhân vật đó).",
	dc_sunhanhua: "Tôn Hàn Hoa",
	dchuiling: "Tụ Linh",
	dchuiling_info: "Kỹ năng khóa. Khi bạn dùng bài, nếu màu bài này là màu có số lượng ít hơn trong bộ bài bỏ, bạn nhận được 1 dấu hiệu “Linh”. Nếu trong bộ bài bỏ: số bài đỏ lớn hơn số bài đen, bạn hồi phục 1 điểm thể lực; số bài đen lớn hơn số bài đỏ, bạn có thể bỏ một lá bài của một nhân vật khác.",
	dcchongxu: "Xung Hư",
	dcchongxu_info: "Kỹ năng giới hạn. Giai đoạn Xuất Bài, nếu số “Linh” không nhỏ hơn 4, bạn có thể mất 【Tụ Linh】, tăng giới hạn thể lực bằng với số “Linh” (tối đa tăng bằng giới hạn thể lực của số người chơi), sau đó nhận được 【Đạp Tịch】 và 【Thanh Hoang】.",
	dctaji: "Đạp Tịch",
	dctaji_info: "Khi bạn mất bài trên tay, dựa vào nguyên nhân bạn mất bài để thực hiện hiệu ứng sau: 1. Sử dụng: bạn bỏ một lá bài của nhân vật khác; 2. Đánh ra: bạn bốc một lá bài; 3. Bỏ bài: bạn hồi phục 1 điểm thể lực; 4. Khác: lần tiếp theo bạn gây sát thương cho nhân vật khác, sát thương này +1.",
	dcqinghuang: "Thanh Hoang",
	dcqinghuang_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể giảm 1 điểm giới hạn thể lực, sau đó khi bạn phát động 【Đạp Tịch】 trong lượt này, sẽ ngẫu nhiên thực hiện thêm một loại hiệu ứng.",
	dc_huojun: "Hoắc Tuấn",
	dcgue: "Cô Ách",
	dcgue_info: "Mỗi lượt giới hạn một lần. Khi bạn cần dùng hoặc đánh ra 【Giết】 hoặc 【Tránh】 ngoài lượt của mình, bạn có thể phát động kỹ năng này: bạn tiết lộ tất cả bài trên tay, nếu tổng số lượng 【Giết】 và 【Tránh】 trong đó không vượt quá 1, bạn xem như đã dùng hoặc đánh ra bài này.",
	dcsigong: "Tứ Công",
	dcsigong_info: "Khi kết thúc lượt của nhân vật khác, nếu trong lượt này người đó có bài sử dụng bị đáp trả, bạn có thể bốc hoặc bỏ bài trên tay xuống 1, xem như sử dụng một 【Giết】 cần dùng X 【Tránh】 để đáp trả nhắm vào người đó, và lượng sát thương cơ bản của 【Giết】 này +1 (X là số bài bạn bỏ bằng cách này và ít nhất là 1). Khi bạn gây sát thương bằng cách này, kỹ năng này mất hiệu lực trong vòng này.",
	peiyuanshao: "Bùi Nguyên Thiệu",
	oldmoyu: "Một Dục",
	oldmoyu_info: "Giai đoạn Xuất Bài mỗi nhân vật giới hạn một lần. Bạn có thể nhận một lá bài trong khu vực của một nhân vật khác, sau đó người đó có thể dùng một 【Giết】 không giới hạn khoảng cách nhắm vào bạn, và lượng sát thương cơ bản của 【Giết】 này là X (X là số lần bạn phát động kỹ năng này trong lượt này). Nếu 【Giết】 này gây sát thương cho bạn, bạn khiến kỹ năng này mất hiệu lực trong lượt này.",
	dcmoyu: "Một Dục",
	dcmoyu_info: "Giai đoạn Xuất Bài mỗi nhân vật giới hạn một lần. Bạn có thể nhận một lá bài trong khu vực của một nhân vật khác, sau đó người đó có thể dùng một 【Giết】 không giới hạn khoảng cách nhắn vào bạn. Nếu 【Giết】 này: chưa gây sát thương cho bạn, bạn đổi số bài nhận được ở lần tiếp theo của kỹ năng này trong giai đoạn này thành hai lá; đã gây sát thương cho bạn, bạn khiến kỹ năng này mất hiệu lực trong lượt này.",
	zhangchu: "Trương Sở",
	dcjizhong: "Tập Chúng",
	dcjizhong_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể khiến một nhân vật khác bốc hai lá bài, sau đó người đó chọn một: 1. Nếu người đó chưa có dấu hiệu “Tín Chúng”, người đó nhận được dấu hiệu “Tín Chúng”; 2. Bạn nhận được ba lá bài của người đó.",
	dcrihui: "Nhật Huệ",
	dcrihui_info: "Mỗi lượt giới hạn một lần. Sau khi bạn dùng bài chú thông thường hoặc bài cơ bản đen kết toán xong, nếu số mục tiêu của bài này là 1 và mục tiêu không phải là bạn, và người đó: không có “Tín Chúng”, thì tất cả nhân vật có “Tín Chúng” lần lượt xem như dùng một bài cùng tên và cùng thuộc tính với bài này nhắm vào người đó; có “Tín Chúng”, thì bạn có thể nhận được một lá bài trong khu vực của người đó.",
	dcguangshi: "Quang Thệ",
	dcguangshi_info: "Kỹ năng khóa. Giai đoạn Chuẩn Bị, nếu tất cả nhân vật khác đều có “Tín Chúng”, bạn bốc X lá bài và mất 1 điểm thể lực (X là số “Tín Chúng” trên bàn).",
	dongwan: "Đổng Uyển",
	dcshengdu: "Sinh Đố",
	dcshengdu_info: "Khi bắt đầu lượt, bạn có thể chọn một nhân vật khác, khiến người đó nhận được 1 dấu hiệu “Sinh Đố”. Sau khi nhân vật có dấu hiệu “Sinh Đố” nhận được bài ở giai đoạn Bốc Bài, bạn bốc X lá bài, sau đó người đó bỏ tất cả dấu hiệu “Sinh Đố” (X là số bài bốc nhân với số dấu hiệu “Sinh Đố” của người đó).",
	dcjieling: "Giới Lăng",
	dcjieling_info: "Giai đoạn Xuất Bài mỗi hoa giới hạn một lần, bạn có thể dùng hai lá bài trên tay khác hoa xem như 【Giết】 không giới hạn khoảng cách và không có bất kỳ giới hạn số lần nào. Sau đó nếu 【Giết】 này: gây sát thương, tất cả nhân vật mục tiêu mất 1 điểm thể lực; không gây sát thương, tất cả nhân vật mục tiêu lần lượt nhận được 1 dấu hiệu “Sinh Đố”.",
	yuanyin: "Viên Dận",
	dcmoshou: "Mặc Thủ",
	dcmoshou_info: "Khi bạn trở thành mục tiêu của bài đen do một nhân vật sử dụng, bạn có thể bốc số lá bài bằng giới hạn thể lực, sau đó nếu số bài bạn bốc bằng cách này: lớn hơn 1, bạn khiến số bài bốc lần sau bằng cách này -1; bằng 1, thiết lập lại số bài bốc của kỹ năng này thành giới hạn thể lực của bạn.",
	dcyunjiu: "Vận Cữu",
	dcyunjiu_info: "Sau khi một nhân vật chết, bạn có thể đưa một lá bài đã bỏ lần này của người đó cho một nhân vật khác. Sau đó bạn tăng 1 điểm giới hạn thể lực và hồi phục 1 điểm thể lực.",
	gaoxiang: "Cao Tường",
	dcchiying: "Trì Ứng",
	dcchiying_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể chọn một nhân vật có thể lực không lớn hơn bạn, khiến người đó có thể bỏ mỗi người một lá bài của một số lượng nhân vật khác bất kỳ trong phạm vi tấn công của người đó. Sau đó nếu nhân vật đó không phải là bạn, người đó nhận được tất cả bài cơ bản trong số bài đã bỏ bằng cách này.",
	zhangkai: "Trương Khải",
	dcxiangshu: "Tương Thử",
	dcxiangshu_info: "Khi bắt đầu giai đoạn Xuất Bài của nhân vật khác, nếu số bài trên tay người đó không nhỏ hơn thể lực của người đó, bạn có thể chọn một số nguyên không âm không lớn hơn 5, sau đó bạn bỏ một lá bài hoặc tuyên bố con số này. Nếu làm vậy, khi kết thúc giai đoạn này, nếu chênh lệch giữa số bài trên tay người đó và con số bạn chọn: không lớn hơn 1, bạn nhận được một lá bài của người đó; bằng nhau, bạn gây cho người đó 1 điểm sát thương.",
	mengyou: "Mạnh Du",
	dcmanzhi: "Manh Trí",
	dcmanzhi_info: "① Giai đoạn Chuẩn Bị, bạn có thể chọn một nhân vật khác và chọn một hạng mục: 1. Khiến người đó đưa cho bạn hai lá bài, sau đó người đó xem như sử dụng một 【Giết】 không giới hạn khoảng cách; 2. Nhận tối đa hai lá bài trong khu vực của người đó, sau đó đưa cho người đó số lượng bài tương ứng và bốc một lá bài. ② Giai đoạn Kết Thúc, nếu thể lực của bạn bằng với thể lực ở giai đoạn Chuẩn Bị của lượt này, bạn có thể thực hiện nhánh của 【Manh Trí①】 mà bạn chưa thực hiện trong lượt này.",
	dc_sunchen: "Tôn Sâm",
	dczigu: "Tự Cố",
	dczigu_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể bỏ một lá bài, sau đó nhận được một lá bài Trang Bị trên bàn. Nếu bạn không vì vậy mà nhận được bài của nhân vật khác, bạn bốc một lá bài.",
	dczuowei: "Tác Oai",
	dczuowei_info: "Khi bạn dùng bài trong lượt, bạn có thể dựa vào số bài trên tay mình để thực hiện hiệu ứng tương ứng: lớn hơn X, khiến bài này không thể bị đáp trả; bằng X, gây 1 điểm sát thương cho một nhân vật khác; nhỏ hơn X, bốc hai lá bài và không thể kích hoạt tùy chọn này trong lượt này nữa (X là số lượng bài trong khu vực Trang Bị của bạn và ít nhất là 1).",
	liuchongluojun: "Lưu Sủng Lạc Tuấn",
	dcminze: "Mẫn Trạch",
	dcminze_info: "① Giai đoạn Xuất Bài mỗi nhân vật giới hạn một lần. Bạn có thể đưa tối đa hai lá bài có tên khác nhau cho một nhân vật có số bài trên tay nhỏ hơn bạn. ② Giai đoạn Kết Thúc, bạn bốc bài trên tay lên X lá (X là số tên bài đã mất vì 【Mẫn Trạch①】 của bạn trong lượt này và tối đa là 5).",
	dcjini: "Kích Nghịch",
	dcjini_info: "Sau khi bạn chịu sát thương, bạn có thể tái luyện tối đa Y lá bài trên tay (Y là giới hạn thể lực của bạn trừ đi số bài bạn đã tái luyện bằng cách này trong lượt này). Nếu bạn nhận được 【Giết】 bằng cách này, bạn có thể dùng một 【Giết】 không nhìn khoảng cách và không thể bị đáp trả nhắn vào nguồn gây sát thương.",
	yuechen: "Nhạc Sâm",
	dcporui: "Phá Nhuệ",
	dcporui_info: "Mỗi vòng giới hạn một lần. Giai đoạn Kết Thúc của nhân vật khác, bạn có thể bỏ một lá bài và chọn một nhân vật khác đã mất bài trong lượt này, bạn xem như lần lượt dùng X+1 【Giết】 nhắn vào người đó, sau đó bạn đưa cho người đó X lá bài trên tay (X là số bài người đó đã mất trong lượt này và tối đa là 5).",
	dcgonghu: "Cộng Hộ",
	dcgonghu_info: "Kỹ năng khóa. ① Khi bạn mất bài cơ bản ngoài lượt, nếu số lượng bài cơ bản bạn mất trong lượt này lớn hơn 1, bạn đổi 【Phá Nhuệ】 thành mỗi vòng giới hạn hai lần. ② Sau khi bạn gây ra hoặc chịu sát thương, nếu tổng sát thương bạn gây ra hoặc chịu trong lượt này lớn hơn 1, bạn xóa bỏ “, sau đó bạn đưa cho người đó X lá bài trên tay” trong 【Phá Nhuệ】. ③ Khi bạn dùng bài cơ bản đỏ / bài chú thông thường đỏ, nếu bạn đã phát động 【Cộng Hộ①】 và 【Cộng Hộ②】, thì bài này không thể bị đáp trả / có thể thêm một mục tiêu bổ sung.",
	yue_caiwenji: "Lạc Thái Diễm",
	yue_caiwenji_prefix: "Lạc",
	dcshuangjia: "Sương Già",
	dcshuangjia_tag: "Hồ Già",
	dcshuangjia_info: "Kỹ năng khóa. ① Bắt đầu ván chơi, bạn đánh dấu bài trên tay ban đầu là “Hồ Già”. ② Bài “Hồ Già” của bạn không tính vào giới hạn bài trên tay. ③ Khoảng cách từ nhân vật khác đến bạn +X (X là số “Hồ Già” của bạn và tối đa là 5).",
	dcbeifen: "Bi Phẫn",
	dcbeifen_info: "Kỹ năng khóa. ① Khi bạn mất bài, nếu trong số bài đó có bài “Hồ Già”, bạn nhận được mỗi hoa một lá bài có hoa khác với tất cả hoa của bài “Hồ Già” trong tay bạn. ② Nếu số bài “Hồ Già” trong tay bạn nhỏ hơn số bài không phải “Hồ Già”, bạn dùng bài không giới hạn khoảng cách và số lần.",
	dc_wuban: "Ngô Ban",
	dcyouzhan: "Dụ Chiến",
	dcyouzhan_info: "Kỹ năng khóa. Khi nhân vật khác mất một lá bài trong lượt của bạn, bạn bốc một lá bài (không tính vào giới hạn bài trên tay của lượt này), và người đó nhận được hiệu ứng sau: 1. Người đó chịu sát thương lần tiếp theo trong lượt này +1; 2. Giai đoạn Kết Thúc, nếu người đó trong lượt này chưa chịu sát thương, người đó bốc X lá bài (X là số lần người đó mất bài trong lượt này và tối đa là 3).",
	yue_zhoufei: "Lạc Chu Phi",
	yue_zhoufei_prefix: "Lạc",
	dclingkong: "Linh Không",
	dclingkong_tag: "Không Hầu",
	dclingkong_info: "Kỹ năng khóa. ① Bắt đầu ván chơi, bạn đánh dấu bài trên tay là “Không Hầu”. ② Bài “Không Hầu” của bạn không tính vào giới hạn bài trên tay. ③ Khi bạn nhận được bài ngoài giai đoạn Bốc Bài lần đầu tiên trong một lượt, bạn đánh dấu những bài này là “Không Hầu”.",
	dcxianshu: "Hiền Thục",
	dcxianshu_info: "Giai đoạn Xuất Bài, bạn có thể đưa một “Không Hầu” ngửa lên cho một nhân vật khác, sau đó bạn bốc X lá bài (X là chênh lệch thể lực giữa bạn và người đó và tối đa là 5). Nếu bài này màu đỏ, và thể lực của nhân vật đó không lớn hơn bạn, thì người đó hồi phục 1 điểm thể lực; nếu bài này màu đen, và thể lực của nhân vật đó không nhỏ hơn bạn, thì người đó mất 1 điểm thể lực.",
	dc_zhangmancheng: "Trương Mạn Thành",
	dclvecheng: "Lược Thành",
	dclvecheng_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể chọn một nhân vật khác, bạn dùng 【Giết】 trong bài trên tay hiện tại nhắn vào người đó trong lượt này không có bất kỳ giới hạn số lần nào. Sau đó khi kết thúc lượt, người đó tiết lộ tất cả bài trên tay, nếu trong đó có 【Giết】, người đó có thể chọn lần lượt dùng tất cả 【Giết】 trong đó nhắn vào bạn.",
	dczhongji: "Chung Tập",
	dczhongji_info: "Khi bạn dùng bài, nếu bài này không có hoa hoặc trong khu vực bài trên tay bạn không có bài cùng hoa với bài này, bạn có thể bốc bài trên tay lên giới hạn thể lực và bỏ X lá bài (X là số lần phát động 【Chung Tập】 trong lượt này).",
	dc_jiachong: "Giả Sung",
	dcbeini: "Bội Nghịch",
	dcbeini_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể điều chỉnh bài trên tay lên giới hạn thể lực, sau đó khiến một nhân vật xem như sử dụng một 【Giết】 nhắn vào một nhân vật khác, và các kỹ năng không khóa của các nhân vật này mất hiệu lực cho đến khi kết thúc lượt.",
	dcshizong: "Thị Túng",
	dcshizong_info: "Khi bạn cần sử dụng một lá bài cơ bản, bạn có thể đưa cho một nhân vật khác X lá bài, sau đó người đó có thể đặt một lá bài dưới đáy bộ bài, xem như bạn sử dụng nó. Nếu người đó không phải là nhân vật trong lượt hiện tại, kỹ năng này mất hiệu lực cho đến khi kết thúc lượt (X là số lần bạn phát động 【Thị Túng】 trong lượt này).",
	pangshanmin: "Bàng Sơn Dân",
	dccaisi: "Tài Tư",
	dccaisi_info: "Sau khi bạn dùng bài cơ bản trong lượt / ngoài lượt kết toán xong, bạn có thể ngẫu nhiên lấy một lá bài không phải cơ bản từ bộ bài / bộ bài bỏ, sau đó nếu số lần bạn phát động kỹ năng này trong lượt này: nhỏ hơn hoặc bằng giới hạn thể lực của bạn, số bài bạn nhận được khi phát động kỹ năng này trong lượt này sẽ tăng gấp đôi; lớn hơn giới hạn thể lực của bạn, kỹ năng này mất hiệu lực trong lượt này.",
	dczhuoli: "Trạch Lại",
	dczhuoli_info: "Kỹ năng khóa. Khi kết thúc lượt của một nhân vật, nếu số bài bạn dùng hoặc nhận được trong lượt này lớn hơn thể lực, bạn tăng 1 điểm giới hạn thể lực (nếu giới hạn thể lực của bạn không nhỏ hơn số người chơi trong ván này, bỏ qua bước này), hồi phục 1 điểm thể lực.",
	yue_caiyong: "Lạc Thái Ung",
	yue_caiyong_prefix: "Lạc",
	dcjiaowei: "Tiêu Vĩ",
	dcjiaowei_tag: "Huyền",
	dcjiaowei_info: "Kỹ năng khóa. ① Bắt đầu ván chơi, bạn đánh dấu bài trên tay là “Huyền”. ② Bài “Huyền” của bạn không tính vào giới hạn bài trên tay. ③ Khi bạn mất “Huyền”, ngăn ngừa sát thương bạn chịu lần tiếp theo trong lượt này.",
	dcfeibai: "Phi Bạch",
	dcfeibai_info: "Sau khi bạn dùng bài kết toán xong, bạn có thể chọn nhận một trong hai lá bài có số chữ là X được chọn ngẫu nhiên (X là tổng số chữ của bài này và bài bạn đã sử dụng trước đó trong lượt này). Nếu trong bộ bài và bộ bài bỏ không có lá bài nào có số chữ là X, thì bạn bốc hai lá bài và đánh dấu là “Huyền”, sau đó 【Phi Bạch】 mất hiệu lực trong lượt này.",
	kuaiqi: "Khoái Kỳ",
	dcliangxiu: "Lương Tú",
	dcliangxiu_info: "Giai đoạn Xuất Bài, bạn có thể bỏ hai lá bài khác loại, sau đó phân phát hai lá bài từ bộ bài / bộ bài bỏ có loại khác với cả loại bài bạn bỏ hoặc bài bạn phân phát bằng cách này trong giai đoạn này cho bất kỳ nhân vật nào.",
	dcxunjie: "Tuẫn Tiết",
	dcxunjie_info: "Mỗi vòng mỗi hạng mục giới hạn một lần. Khi kết thúc lượt của một nhân vật, nếu bạn nhận được bài ngoài giai đoạn Bốc Bài trong lượt này, bạn có thể chọn một: 1. Khiến một nhân vật bốc hoặc bỏ bài trên tay xuống bằng với thể lực của người đó; 2. Khiến một nhân vật hồi phục hoặc mất thể lực bằng với số bài trên tay của người đó.",
	dc_dongzhao: "Đổng Chiêu",
	dcyijia: "Dịch Giá",
	dcyijia_info: "Sau khi một nhân vật chịu sát thương, nếu khoảng cách từ bạn đến người đó không lớn hơn 1, bạn có thể di chuyển một lá bài Trang Bị trên bàn đến ô Trang Bị tương ứng của người đó (thay thế trang bị cũ). Nếu người đó vì vậy thoát khỏi phạm vi tấn công của một nhân vật, bạn bốc một lá bài.",
	dcdingji: "Định Cơ",
	dcdingji_info: "Giai đoạn Chuẩn Bị, bạn có thể khiến một nhân vật bốc hoặc bỏ bài trên tay xuống năm lá, sau đó người đó tiết lộ bài trên tay. Nếu các tên bài đều khác nhau, thì người đó có thể xem như sử dụng một trong số bài cơ bản hoặc bài chú thông thường đó.",
	yue_xiaoqiao: "Lạc Tiểu Kiều",
	yue_xiaoqiao_prefix: "Lạc",
	dcqiqin: "Ỷ Cầm",
	dcqiqin_tag: "Cầm",
	dcqiqin_info: "Kỹ năng khóa. ① Bắt đầu ván chơi, bạn đánh dấu bài trên tay là “Cầm”. ② Bài “Cầm” của bạn không tính vào giới hạn bài trên tay. ③ Giai đoạn Chuẩn Bị, bạn nhận được tất cả “Cầm” nằm trong bộ bài bỏ.",
	dcweiwan: "Uyển Uyển",
	dcweiwan_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể bỏ một “Cầm” và ngẫu nhiên nhận được mỗi hoa một lá bài có hoa khác với hoa này trong khu vực của một nhân vật khác, nếu bạn nhận được: một lá bài, người đó mất 1 điểm thể lực; hai lá bài, trong lượt này bạn dùng bài nhắn vào người đó không giới hạn khoảng cách và số lần; ba lá bài, trong lượt này bạn không thể dùng bài nhắn vào người đó.",
	dc_sp_menghuo: "Tân Sát SP Mạnh Hoạch",
	dc_sp_menghuo_prefix: "Tân Sát SP",
	dcmanwang: "Man Vương",
	dcmanwang_info: "Giai đoạn Xuất Bài, bạn có thể bỏ một số lá bài bất kỳ. Sau đó bạn lần lượt thực hiện X hạng mục đầu tiên trong các hạng mục sau: ⒈ Nhận được 【Bạn Xâm】. ⒉ Bốc một lá bài. ⒊ Hồi phục 1 điểm thể lực. ⒋ Bốc hai lá bài và mất 【Bạn Xâm】.",
	dcpanqin: "Bạn Xâm",
	dcpanqin_info: "Khi kết thúc giai đoạn Xuất Bài hoặc giai đoạn Bỏ Bài, bạn có thể dùng tất cả bài bạn đã bỏ trong giai đoạn này và đang nằm trong bộ bài bỏ xem như 【Nam Man Nhập Xâm】 để sử dụng. Sau đó nếu số bài thực thể tương ứng khi bài này được sử dụng không lớn hơn số mục tiêu của bài này, thì bạn thực hiện và loại bỏ hạng mục cuối cùng trong 【Man Vương】, sau đó tăng 1 điểm giới hạn thể lực và hồi phục 1 điểm thể lực.",
	dc_kongrong: "Khổng Dung",
	dckrmingshi: "Danh Sĩ",
	dckrmingshi_info: "Kỹ năng khóa, khi bạn chịu sát thương do nhân vật khác gây ra, nếu số bài trên tay người đó lớn hơn bạn, thì người đó cần bỏ một lá bài trên tay, nếu không thì sát thương này -1.",
	yue_daqiao: "Lạc Đại Kiều",
	yue_daqiao_prefix: "Lạc",
	dczixi: "Tỷ Hy",
	dczixi_info: "① Khi bắt đầu và kết thúc giai đoạn Xuất Bài, bạn có thể dùng một “Cầm” xem như 【Lạc Bất Tư Thục】, 【Binh Lương Đoạn】 hoặc 【Sấm Sét】 không có hiệu ứng đặt vào khu vực Phán Định của một nhân vật. ② Khi bạn dùng bài cơ bản hoặc bài chú thông thường chỉ định mục tiêu duy nhất, bạn có thể dựa vào số bài trong khu vực Phán Định của người đó để thực hiện hạng mục tương ứng: 1. Khiến bài này kết toán thêm một lần đối với người đó; 2. Bốc hai lá bài; 3. Bỏ tất cả bài trong khu vực Phán Định của người đó, gây cho người đó 3 điểm sát thương.",
	jiangfei: "Tưởng Uyển Phí Y",
	dcshoucheng: "Thủ Thành",
	dcshoucheng_info: "Mỗi lượt giới hạn một lần, khi một nhân vật mất bài trên tay ngoài lượt của mình, nếu người đó không còn bài trên tay, bạn có thể khiến người đó bốc hai lá bài.",
	dc_liuli: "Lưu Lý",
	dcfuli: "Phủ Lê",
	dcfuli_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể tiết lộ bài trên tay và bỏ tất cả bài có một loại, sau đó bốc X lá bài (X là tổng số chữ trong tên của những bài này và X tối đa bằng số bài trên tay của nhân vật có số bài trên tay nhiều nhất bàn). Sau đó bạn có thể chọn một nhân vật, khiến phạm vi tấn công của người đó -Y cho đến khi bắt đầu lượt tiếp theo của bạn (Y là 1, nếu bạn vì vậy bỏ bài sát thương, thì Y đổi thành giảm phạm vi tấn công của người đó).",
	dcdehua: "Đức Hóa",
	dcdehua_info: "Kỹ năng khóa. ① Khi bắt đầu mỗi vòng, nếu có tên bài sát thương không phải trì hoãn mà bạn có thể dùng và chưa chọn bằng cách này, bạn chọn một trong số đó và xem như sử dụng nó, sau đó bạn không thể dùng bài có tên bài này trên tay. Nếu bạn đã chọn tất cả các tên bài sát thương, bạn mất 【Đức Hóa】, trong ván chơi này bài sát thương của bạn không tính vào số bài trên tay. ② Giới hạn bài trên tay của bạn +Y (Y là số tên bài đã chọn trong 【Đức Hóa①】 của bạn).",
	gongsunxiu: "Công Tôn Tu",
	dcgangu: "Cán Cổ",
	dcgangu_info: "Kỹ năng khóa. Mỗi lượt giới hạn một lần. Khi nhân vật khác mất thể lực, bạn bốc ba lá bài, sau đó mất 1 điểm thể lực.",
	dckuizhen: "Hối Trận",
	dckuizhen_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể khiến một nhân vật có số bài trên tay hoặc thể lực không nhỏ hơn bạn xem như sử dụng một 【Quyết Đấu】 nhắn vào bạn. Nếu bạn: chịu sát thương với kênh là bài này, bạn xem bài trên tay của người đó và nhận được tất cả 【Giết】 trong đó (bạn dùng bài nhận được bằng cách này không có bất kỳ giới hạn số lần nào); không chịu sát thương với kênh là bài này, người đó mất 1 điểm thể lực.",
	dcshiju: "Thế Cử",
	dcshiju_info: "Giai đoạn Xuất Bài của một nhân vật giới hạn một lần. Người đó có thể đưa cho bạn một lá bài (nếu người đó là bạn thì đổi thành tiết lộ một lá bài), nếu bài này là bài Trang Bị, bạn có thể sử dụng nó, sau đó phạm vi tấn công của người đó trong lượt này +X (X là số bài trong khu vực Trang Bị của bạn). Nếu bạn thay thế trang bị bằng cách này, bạn và người đó mỗi người bốc hai lá bài.",
	dcyingshi: "Ứng Thời",
	dcyingshi_info: "Khi bạn dùng bài chú thông thường chỉ định mục tiêu xong không phải do 【Ứng Thời】, bạn có thể khiến một trong số các mục tiêu đó chọn một: ⒈ Khiến bạn sau khi bài này kết toán xong xem như sử dụng một bài có cùng tên với bài này nhắn vào người đó; ⒉ Bỏ X lá bài, trong lượt này bạn không thể phát động 【Ứng Thời】 nữa (X là số bài trong khu vực Trang Bị của bạn).",
	dcjichou: "Tập Trù",
	dcjichou_info: "Khi kết thúc giai đoạn Kết Thúc, nếu bạn đã dùng bài trong lượt này và tên của những bài này đều khác nhau, bạn có thể xem những bài này đang nằm trong bộ bài bỏ, chọn một số lá bài bất kỳ và chọn số lượng nhân vật tương ứng, đưa mỗi người một lá bài trong số đó, sau đó bạn bốc X lá bài (X là số bài bạn đưa ra lần đầu tiên phát động 【Tập Trù】 trong ván chơi này).",
	dcmouli: "Mưu Lập",
	dcmouli_info: "Kỹ năng giác tỉnh. Khi kết thúc lượt, nếu tổng số tên bài bạn đưa ra vì 【Tập Trù】 lớn hơn 5, bạn tăng 1 điểm giới hạn thể lực và hồi phục 1 điểm thể lực, sau đó nhận được 【Tự Phược】.",
	dczifu: "Tự Phược",
	dczifu_info: "Kỹ năng khóa. Khi bắt đầu giai đoạn Xuất Bài, bạn bốc bài trên tay lên giới hạn thể lực (tối đa bốc đến năm lá). Nếu bạn nhận được bài bằng cách này, bạn phải chọn mỗi tên bài khác nhau một lá trên tay, sau đó bỏ số bài trên tay còn lại.",
	dcsanshi: "Tán Sĩ",
	dcsanshi_tag: "Tử Sĩ",
	dcsanshi_info: "Kỹ năng khóa. ① Khi bắt đầu ván chơi, bạn khiến hệ thống đánh dấu vĩnh viễn một lá bài ngẫu nhiên mỗi điểm số trong bộ bài là “Tử Sĩ” (“Tử Sĩ” hiển thị với bạn). ② Khi kết thúc lượt của một nhân vật, nếu trong lượt này có “Tử Sĩ” vào bộ bài bỏ không phải do bạn dùng hoặc đánh ra, bạn nhận được những bài này từ bộ bài bỏ. ③ Bạn dùng “Tử Sĩ” không thể bị đáp trả.",
	dczhenrao: "Chấn Nhiễu",
	dczhenrao_info: "Mỗi lượt mỗi nhân vật giới hạn một lần. Khi bạn dùng bài chỉ định mục tiêu đầu tiên, nếu (các) mục tiêu bao gồm nhân vật khác, hoặc khi nhân vật khác dùng bài chỉ định bạn làm mục tiêu, bạn có thể chọn một mục tiêu có số bài trên tay lớn hơn bạn trong số đó hoặc người sử dụng bài, sau đó gây cho người đó 1 điểm sát thương.",
	dcchenlve: "Trầm Lược",
	dcchenlve_info: "Kỹ năng giới hạn. Giai đoạn Xuất Bài, bạn có thể đặt tất cả “Tử Sĩ” trong bộ bài, bộ bài bỏ, trên bàn và khu vực bài trên tay của nhân vật khác vào khu vực Xử Lý, sau đó bạn nhận được những bài này. Nếu làm vậy, bạn nhận được hiệu ứng sau: 1. Khi kết thúc giai đoạn này, bạn đưa những bài này ra khỏi ván chơi; 2. Khi bạn chết, bạn đặt tất cả “Tử Sĩ” đã đưa ra khỏi ván chơi bằng cách này vào bộ bài bỏ.",
	dcjianzhuan: "Tiệm Chuyên",
	dcjianzhuan_info: "Kỹ năng khóa. ① Khi bạn dùng bài trong giai đoạn Xuất Bài, bạn chọn một hạng mục chưa thực hiện trong giai đoạn này để thực hiện: ⒈ Khiến một nhân vật bỏ X lá bài; ⒉ Bốc X lá bài; ⒊ Tái luyện X lá bài; ⒋ Bỏ X lá bài (X là số lần phát động kỹ năng này trong giai đoạn này). ② Khi kết thúc giai đoạn Xuất Bài, nếu bạn đã thực hiện tất cả các hạng mục của 【Tiệm Chuyên①】 trong giai đoạn này, thì bạn ngẫu nhiên loại bỏ một hạng mục của 【Tiệm Chuyên①】.",
	dcjianzhuan_faq: "Tiệm Chuyên Xác suất",
	dcjianzhuan_faq_info: "<br>Khi hệ thống ngẫu nhiên chọn hạng mục để xóa, xác suất của hạng mục “Bỏ X lá bài” cố định là 90%; các hạng mục còn lại chia đều 10% xác suất còn lại.<br>Ví dụ lần xóa đầu tiên, xác suất xóa hạng mục bỏ bài là 90%, xác suất ba hạng mục còn lại bị xóa đều là 3.33%, nếu xóa hạng mục không phải bỏ bài, lần xóa thứ hai, xác suất xóa hạng mục bỏ bài vẫn là 90%, hai hạng mục còn lại bị xóa xác suất đều là 5%.",
	dcfanshi: "Phản Thế",
	dcfanshi_info: "Kỹ năng giác tỉnh, giai đoạn Kết Thúc, nếu số hạng mục còn lại của 【Tiệm Chuyên①】 nhỏ hơn 2, thì bạn thực hiện ba lần hạng mục còn lại với X được xem là 1, sau đó tăng 2 điểm giới hạn thể lực và hồi phục 2 điểm thể lực, mất kỹ năng 【Tiệm Chuyên】 và nhận được kỹ năng 【Phúc Đẩu】.",
	dcfudou: "Phúc Đẩu",
	dcfudou_info: "Khi bạn dùng bài đen / bài đỏ chỉ định mục tiêu duy nhất, nếu nhân vật đó không phải là bạn, và người đó trong ván chơi này đã gây sát thương cho bạn / chưa gây sát thương cho bạn, thì bạn có thể cùng với người đó mỗi người mất 1 điểm thể lực / mỗi người bốc một lá bài.",
	wupu: "Ngô Phổ",
	dcduanti: "Đoạn Thể",
	dcduanti_info: "Kỹ năng khóa. Khi bạn dùng hoặc đánh ra bài kết toán xong, nếu bài này là lá bài thứ 5X trong số các bài bạn đã dùng hoặc đánh ra trong ván chơi này (X∈N⁺), bạn hồi phục 1 điểm thể lực, sau đó nếu giới hạn tăng bằng cách này nhỏ hơn 5, bạn tăng 1 điểm giới hạn thể lực.",
	dcshicao: "Thức Thảo",
	dcshicao_info: "Giai đoạn Xuất Bài, bạn có thể tuyên bố một loại, sau đó chọn bốc một lá bài từ đỉnh hoặc đáy bộ bài. Nếu loại bài này khác với loại bạn tuyên bố, bạn xem hai lá bài ở đầu kia của bộ bài, kỹ năng này mất hiệu lực trong lượt này.",
	dc_lifeng: "Lý Phong",
	dctunchu: "Đồn Trữ",
	dctunchu_info: "Kỹ năng khóa. ① Số bài trên tay ban đầu của bạn bằng bốn lần số người chơi. ② Bài trên tay của bạn không thể bị bỏ. ③ Giai đoạn Chuẩn Bị, nếu số bài trên tay bạn lớn hơn thể lực của bạn, thì bạn dùng tối đa ba lá bài trong lượt này.",
	dcshuliang: "Thâu Lương",
	dcshuliang_info: "Khi kết thúc lượt của một nhân vật, bạn có thể đưa một số lá bài bất kỳ cho một số lượng nhân vật bất kỳ không có bài trên tay mỗi người một lá, sau đó những nhân vật lần này nhận được bài có thể chỉ định chính mình làm mục tiêu có thể lần lượt chọn có sử dụng bài vừa nhận được hay không.",
	yue_miheng: "Lạc Di Hành",
	yue_miheng_prefix: "Lạc",
	dcjigu: "Kích Cổ",
	dcjigu_info: "Kỹ năng khóa. ① Bắt đầu ván chơi, bạn đánh dấu bài trên tay là “Kích Cổ”. ② Bài “Kích Cổ” của bạn không tính vào giới hạn bài trên tay. ③ Khi bạn gây ra hoặc chịu sát thương, nếu số bài “Kích Cổ” của bạn bằng số bài trong khu vực Trang Bị của bạn, bạn bốc X lá bài (X là số ô Trang Bị trống của bạn). Sau đó nếu số lần phát động 【Kích Cổ】 của bạn trong vòng này không nhỏ hơn số nhân vật đã qua lượt, hiệu ứng này mất hiệu lực trong vòng này.",
	dcsirui: "Tư Nhuệ",
	dcsirui_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể dùng một lá bài xem như một bài cơ bản hoặc bài chú thông thường có cùng số chữ, không giới hạn khoảng cách và số lần.",
	yue_zoushi: "Lạc Trâu Thị",
	yue_zoushi_prefix: "Lạc",
	dcyunzheng: "Vận Tranh",
	dcyunzheng_tag: "Tranh",
	dcyunzheng_info: "Kỹ năng khóa. ① Bắt đầu ván chơi, bạn đánh dấu bài trên tay là “Tranh”. ② Bài “Tranh” của bạn không tính vào giới hạn bài trên tay. ③ Các kỹ năng không khóa của nhân vật khác có “Tranh” trong tay mất hiệu lực.",
	dchuoxin: "Hoặc Tâm",
	dchuoxin_info: "Khi bạn dùng bài không phải Trang Bị, bạn có thể tiết lộ một lá bài trên tay của một nhân vật khác. Nếu bài này là bài “Tranh” hoặc cùng hoa với bài bạn dùng, bạn có thể nhận được nó; nếu không thì đánh dấu bài này là “Tranh”.",
	yue_zhugeguo: "Lạc Gia Cát Quả",
	yue_zhugeguo_prefix: "Lạc",
	dcxidi: "Hy Địch",
	dcxidi_tag: "Địch",
	dcxidi_info: "Kỹ năng khóa. ① Bắt đầu ván chơi, bạn đánh dấu bài trên tay là “Địch”. ② Bài “Địch” của bạn không tính vào giới hạn bài trên tay. ③ Giai đoạn Chuẩn Bị hoặc giai đoạn Kết Thúc, bạn xem X lá bài trên cùng bộ bài, sau đó đặt những lá bài này lên đỉnh và đáy bộ bài theo bất kỳ thứ tự nào (X là số “Địch” trong tay bạn và ít nhất là 1).",
	dcchengyan: "Thừa Yên",
	dcchengyan_info: "Khi bạn dùng 【Giết】 hoặc bài chú thông thường chỉ định nhân vật khác làm mục tiêu, bạn có thể bốc một lá bài và tiết lộ nó, nếu lá bài tiết lộ là 【Giết】 hoặc bài chú thông thường có thể chỉ định mục tiêu, bạn đổi cách kết toán của bài bạn dùng đối với người đó thành cách kết toán của tên lá bài đã tiết lộ; nếu không, bạn bốc một lá bài và đánh dấu là “Địch”.",
	dc_sp_zhurong: "Tân Sát SP Chúc Dung",
	dc_sp_zhurong_prefix: "Tân Sát SP",
	dcremanhou: "Man Hậu",
	dcremanhou_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể bốc tối đa bốn lá bài và dựa vào số bài bốc lần lượt thực hiện số lượng hạng mục tương ứng: ① Mất 【Thám Loạn】; ② Bỏ một lá bài trên tay; ③ Bỏ một lá bài trên bàn; ④ Mất 1 điểm thể lực, nhận được 【Thám Loạn】.",
	dcretanluan: "Thám Loạn",
	dcretanluan_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể sử dụng một lá bài trong bộ bài bỏ của lượt này do bị bỏ, nếu bài bạn dùng vì vậy bị 【Vô Tiết Khả Kích】 đáp trả hoặc gây sát thương cho nhân vật khác, thì bạn thiết lập lại 【Man Hậu】.",
	dcmanhou: "Man Hậu",
	dcmanhou_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể bốc tối đa bốn lá bài và dựa vào số bài bốc lần lượt thực hiện số lượng hạng mục tương ứng: ① Mất 【Thám Loạn】; ② Bỏ một lá bài trên tay; ③ Mất 1 điểm thể lực; ④ Bỏ một lá bài và nhận được 【Thám Loạn】.",
	dctanluan: "Thám Loạn",
	dctanluan_info: "Kỹ năng khóa, sau khi bạn dùng bài chỉ định mục tiêu, nếu số nhân vật mục tiêu lớn hơn hoặc bằng số nhân vật không phải mục tiêu, bạn có thể bỏ một lá bài trên bàn của một trong các nhân vật mục tiêu; nếu số nhân vật mục tiêu nhỏ hơn số nhân vật không phải mục tiêu, thì số mục tiêu của lá bài tiếp theo bạn dùng trong lượt này +1.",
	dc_mateng: "Tân Sát Mã Đằng",
	dc_mateng_prefix: "Tân Sát",
	dcxiongyi: "Hùng Dị",
	dcxiongyi_info: "Kỹ năng giới hạn, giai đoạn Xuất Bài, bạn có thể cùng với một nhân vật khác mỗi người bốc ba lá bài, sau đó nếu thể lực của bạn là ít nhất duy nhất bàn, bạn hồi phục 1 điểm thể lực. Khi bạn thoát khỏi trạng thái hấp hối, bạn khôi phục kỹ năng này và xóa bỏ hiệu ứng hồi phục thể lực.",
	dc_huangwudie: "Hoàng Vũ Điệp",
	dcshuangrui: "Song Nhuệ",
	dcshuangrui_info: "Giai đoạn Chuẩn Bị, bạn có thể chọn một nhân vật khác, xem như sử dụng một 【Giết】 nhắn vào người đó; nếu nhân vật đó không nằm trong phạm vi tấn công của bạn, bạn khiến 【Giết】 này không thể bị đáp trả và trong lượt này nhận được 【Thú Tinh】, nếu không thì bạn khiến 【Giết】 này gây sát thương +1 và trong lượt này nhận được 【Sát Tuyết】.",
	dcfuxie: "Phục Giới",
	dcfuxie_info: "Giai đoạn Xuất Bài, bạn có thể bỏ một lá bài Vũ Khí hoặc mất một kỹ năng, khiến một nhân vật khác bỏ hai lá bài.",
	dcshouxing: "Thú Tinh",
	dcshouxing_info: "Bạn có thể dùng X lá bài xem như một 【Giết】 không tính vào giới hạn số lần nhắn vào một nhân vật ngoài phạm vi tấn công (X là khoảng cách bạn tính với người đó).",
	dcshaxue: "Sát Tuyết",
	dcshaxue_info: "Sau khi bạn gây sát thương cho nhân vật khác, có thể bốc hai lá bài và bỏ X lá bài (X là khoảng cách bạn tính với người đó).",
	yue_diaochan: "Lạc Điêu Thuyền",
	yue_diaochan_prefix: "Lạc",
	dctanban: "Đàn Bản",
	dctanban_info: "① Bắt đầu ván chơi, bạn đánh dấu bài trên tay là “Đàn Bản”. ② Bài “Đàn Bản” của bạn không tính vào giới hạn bài trên tay. ③ Khi kết thúc giai đoạn Bốc Bài, bạn có thể đổi dấu hiệu “Đàn Bản” của hai loại bài.",
	dcdiou: "Đê Âu",
	dcdiou_info: "Sau khi bạn dùng bài thực thể có chứa bài “Đàn Bản” kết toán xong, bạn có thể tiết lộ một lá bài không phải “Đàn Bản” trên tay, sau đó xem như sử dụng nó, nếu bài này là lần đầu tiên được tiết lộ trong lượt này hoặc tên bài trùng với tên bài bạn vừa dùng, thì bạn bốc hai lá bài.",
	yue_zhouyu: "Lạc Chu Du",
	yue_zhouyu_prefix: "Lạc",
	dcguyin: "Cố Âm",
	dcguyin_info: "Kỹ năng khóa. ① Số bài trên tay ban đầu của bạn là 0, số bài trên tay ban đầu của nhân vật khác +1. ② Sau khi bài trên tay ban đầu của nhân vật khác vì sử dụng hoặc bỏ vào bộ bài bỏ, bạn bốc một lá bài.",
	dcpinglu: "Bình Lỗ",
	dcpinglu_info: "Giai đoạn Xuất Bài, bạn có thể nhận mỗi người một lá bài ngẫu nhiên trên tay của tất cả nhân vật khác trong phạm vi tấn công. Nếu làm vậy, cho đến khi những bài này rời khỏi khu vực bài trên tay bạn, kỹ năng này mất hiệu lực trong giai đoạn này.",
	panghong: "Bàng Hoằng",
	dcpingzhi: "Bình Trí",
	dcpingzhi_info: "Kỹ năng chuyển hóa. Giai đoạn Xuất Bài giới hạn một lần, bạn có thể xem bài trên tay của một nhân vật và tiết lộ một lá bài trong đó, Dương: bạn bỏ lá bài này, sau đó người đó xem như sử dụng một 【Hỏa Công】 nhắn vào bạn, nếu người đó không vì vậy gây sát thương thì kỹ năng này xem như chưa phát động; Âm: sau đó người đó sử dụng bài này, nếu bài này gây sát thương thì kỹ năng này xem như chưa phát động.",
	dcgangjian: "Cương Giản",
	dcgangjian_info: "Kỹ năng khóa. Khi kết thúc mỗi lượt, nếu bạn chưa chịu sát thương trong lượt này, bạn bốc X lá bài (X là số bài đã được tiết lộ trong lượt này và tối đa là 5).",
	dc_zhangyì: "Tân Sát Trương Dực",
	dc_zhangyì_prefix: "Tân Sát",
	dcmurui: "Mộ Nhuệ",
	dcmurui_info: "Bạn có thể dùng một lá bài vào các thời điểm sau: 1. Khi bắt đầu mỗi vòng; 2. Sau khi kết thúc lượt có nhân vật chết; 3. Khi bắt đầu lượt của bạn. Nếu lá bài này gây sát thương, thì bạn bốc hai lá bài và xóa tùy chọn tương ứng.",
	dcaoren: "Ngao Nhận",
	dcaoren_info: "Mỗi vòng giới hạn X lần (X là số tùy chọn đã bị xóa trong “Mộ Nhuệ”), sau khi bài cơ bản bạn dùng kết toán xong, có thể thu hồi nó về tay.",
	houcheng: "Hầu Thành",
	dcxianniang: "Hiến Nhưỡng",
	dcxianniang_info: "Mỗi vòng mỗi hạng mục giới hạn một lần, khi bài của bạn bị nhân vật khác bỏ hoặc sau khi chịu sát thương, bạn có thể nhận tối đa hai lá bài của một nhân vật có số bài trên tay không nhỏ hơn bạn, và có thể đưa cho một nhân vật khác tối đa số lượng bài tương ứng; bài cơ bản nhận hoặc đưa ra vì vậy chỉ có thể dùng xem như 【Rượu】. Nếu số bài bạn nhận được vì kỹ năng này trong vòng này vượt quá hai lá, thì bạn mất 1 điểm thể lực.",
	dc_xiahouxuan: "Tân Sát Hạ Hầu Huyền",
	dc_xiahouxuan_prefix: "Tân Sát",
	dcboxuan: "Bác Huyền",
	dcboxuan_info: "Sau khi bạn dùng bài trên tay kết toán xong, nếu mục tiêu của bài này bao gồm nhân vật khác, bạn có thể tiết lộ ba lá bài dưới đáy bộ bài, nếu trong đó có bài: 1. cùng số chữ với bài bạn dùng, bạn bốc một lá bài; 2. cùng hoa với bài bạn dùng, bạn có thể bỏ một lá bài của một nhân vật khác; 3. cùng loại với bài bạn dùng, bạn có thể dùng một lá bài đã tiết lộ.",
	dcboxuan_rewrite: "Bác Huyền·Cải",
	dcboxuan_rewrite_info: "Sau khi bạn dùng bài trên tay kết toán xong, nếu bài này có mục tiêu, bạn có thể tiết lộ ba lá bài dưới đáy bộ bài, nếu trong đó có bài: 1. cùng số chữ với bài bạn dùng, bạn bốc một lá bài; 2. cùng hoa với bài bạn dùng, bạn có thể bỏ một lá bài của một nhân vật khác; 3. cùng loại với bài bạn dùng, bạn có thể dùng một lá bài đã tiết lộ.",
	dcyizheng: "Nghị Chính",
	dcyizheng_info: "Khi bắt đầu lượt của bạn, bạn có thể cùng với tối đa (giới hạn thể lực) nhân vật khác mỗi người tiết lộ một lá bài trên tay, nếu loại của các lá bài tiết lộ đều giống nhau, bạn có thể đưa những lá bài này cho một nhân vật, nếu không, bạn bỏ những lá bài này.",
	dcguilin: "Quy Lâm",
	dcguilin_info: "Kỹ năng giới hạn, giai đoạn Xuất Bài hoặc khi bạn vào trạng thái hấp hối, bạn có thể hồi phục tất cả thể lực, sau đó mất 【Nghị Chính】 và sửa đổi 【Bác Huyền】.",
	dc_xiangchong: "Tân Sát Hướng Sủng",
	dc_xiangchong_prefix: "Tân Sát",
	dcguying: "Cố Doanh",
	dcguying_info: "Giai đoạn Kết Thúc, bạn có thể chọn một nhân vật, người đó nhận được hiệu ứng sau cho đến trước khi bắt đầu giai đoạn Kết Thúc tiếp theo của bạn: lần tiếp theo chịu sát thương sau đó, bốc số lá bài bằng giới hạn thể lực (tối đa bốc 5 lá), sau đó đưa cho bạn số bài vượt quá giới hạn thể lực trên tay. Nếu trong khoảng thời gian này không có nhân vật nào kích hoạt hiệu ứng này, thì lần tiếp theo bạn phát động 【Cố Doanh】 có thể chọn thêm một nhân vật.",
	dcmuzhen: "Mục Trận",
	dcmuzhen_info: "Giai đoạn Xuất Bài, bạn có thể đưa X lá bài cùng một loại cho một nhân vật khác (X là số lần phát động kỹ năng này trong giai đoạn này, mỗi loại giới hạn một lần), sau đó chọn một: 1. Khiến người đó bỏ số lượng bài tương ứng loại khác, không đủ thì bỏ hết và tiết lộ bài trên tay; 2. Nhận số lượng bài tương ứng trên bàn của người đó; 3. Khiến người đó tiết lộ số lượng bài tương ứng trên cùng bộ bài, và nhận được bài có loại giống trong số đó.",
	dc_zhugejun: "Tân Sát Gia Cát Quân",
	dc_zhugejun_prefix: "Tân Sát",
	dcgengdu: "Canh Độc",
	dcgengdu_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể lật ngửa bốn lá bài trên cùng bộ bài, và chọn nhận tất cả bài có một màu. Nếu màu bạn chọn là: đen, trong giai đoạn này giới hạn X lần, sau khi bạn dùng bài đen bạn bốc hai lá bài, những bài này trong lượt này không thể dùng hoặc đánh ra và không tính vào giới hạn bài trên tay; đỏ, trong giai đoạn này giới hạn X lần, bạn có thể dùng một lá bài đỏ xem như bài chú thông thường chưa được sử dụng trong lượt này (X là số bài đã lật bạn không nhận lần này).",
	dcgumai: "Cô Mạch",
	dcgumai_info: "Mỗi vòng giới hạn một lần, khi bạn gây ra hoặc chịu sát thương, nếu bạn có bài trên tay, bạn có thể tiết lộ tất cả bài trên tay và khiến sát thương này +1/-1. Nếu các hoa của bài đã tiết lộ đều giống nhau, bạn có thể bỏ một lá bài trên tay để khiến kỹ năng này xem như chưa phát động.",
	jimiaojimu: "Cát Mịch Cát Mục",
	dczouyi: "Tru Nghị",
	dczouyi_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể thực hiện tối đa hai hạng mục: 1. Bạn bốc hai lá bài và có thể bỏ một lá bài của một nhân vật khác; 2. Bạn bỏ một lá bài và có thể khiến một nhân vật khác bốc hai lá bài. Sau khi kết toán, số lần sử dụng 【Yểm Tập】 tăng X, bạn hồi phục X điểm thể lực (X là số nhân vật có số bài trên tay bằng bạn).",
	dcyanxi: "Yểm Tập",
	dcyanxi_info: "Mỗi ván giới hạn không lần, khi kết thúc lượt của nhân vật khác, bạn có thể xem như sử dụng một 【Giết】 nhắn vào người đó (sát thương do 【Giết】 này gây ra đổi thành mất thể lực), sau khi kết toán nếu số lần sử dụng của kỹ năng này không phải là 0, lại phát động cho đến khi kỹ năng này hết số lần sử dụng hoặc người đó chết.",
	mamiao: "Mã Miểu",
	dczhangguan: "Trượng Quan",
	dczhangguan_info: "Khi bắt đầu mỗi lượt, bạn có thể điều chỉnh số bài trên tay bằng thể lực, sau đó nếu số bài trên tay bạn: không đổi, bạn hồi phục 1 điểm thể lực; giảm, bạn nhận được một lá bài của nhân vật trong lượt hiện tại.",
	dccongfeng: "Tòng Phong",
	dccongfeng_info: "Sau khi bạn / nhân vật khác nhận được bài của nhân vật khác / bạn không phải do kỹ năng này, sẽ nhận thêm ngẫu nhiên một lá.",
	dc_zhangshiping: "Tân Sát Trương Thế Bình",
	dc_zhangshiping_prefix: "Tân Sát",
	dcbinji: "Tân Tế",
	dcbinji_info: "Khi bắt đầu mỗi vòng, bạn có thể bốc ba lá bài sau đó đưa cho tối đa ba nhân vật khác mỗi người một lá bài, khi những nhân vật này mất những lá bài này, họ ngẫu nhiên lấy một lá bài Vũ Khí từ bộ bài hoặc bộ bài bỏ, sau đó bạn bốc hai lá bài.",
	dczangmao: "Tảng Mậu",
	dczangmao_info: "Giai đoạn Xuất Bài giới hạn ba lần, bạn có thể: 1. Bỏ một số lượng lá bài ♦ bất kỳ, sau đó ngẫu nhiên lấy số lượng bài Tọa Kỵ tương ứng từ bộ bài hoặc bộ bài bỏ; 2. Đưa cho một nhân vật khác một lá bài ♦, sau đó nhận một lá bài Tọa Kỵ trong khu vực Trang Bị của người đó; 3. Đặt một lá bài Tọa Kỵ vào khu vực Trang Bị của một nhân vật khác, sau đó ngẫu nhiên nhận hai lá bài trên tay của người đó.",
	dc_weifeng: "Tân Sát Ngụy Phúng",
	dc_weifeng_prefix: "Tân Sát",
	dchuozhong: "Hoặc Chúng",
	dchuozhong_info: "Giai đoạn Xuất Bài giới hạn hai lần, bạn có thể tiết lộ một lá bài trên tay và khiến một số lượng nhân vật khác bất kỳ trong phạm vi tấn công nhận hoặc đưa cho một nhân vật khác một lá bài, sau đó nhân vật khác có số bài trên tay nhiều nhất sẽ tiết lộ bài trên tay và đặt tất cả bài cùng loại với lá bài bạn tiết lộ lên đỉnh bộ bài.",
	dczhuguo: "Chú Quốc",
	dczhuguo_info: "Kỹ năng khóa, mỗi lượt giới hạn ba lần, sau khi số lượng bài trong bộ bài tăng lên, bạn bốc hai lá bài từ đáy bộ bài.",
};

export default translates;
