import { lib, game, ui, get, ai, _status } from "noname";

const translates = {
	old_huaxiong: "Hoa Hùng",
	old_huaxiong_prefix: "Tướng",
	yufan: "Ngu Phiên",
	xushu: "Cựu Từ Thứ",
	xushu_prefix: "Cựu",
	caozhi: "Tào Thực",
	zhangchunhua: "Trương Xuân Hoa",
	lingtong: "Lăng Thống",
	xunyou: "Tuân Du",
	liubiao: "Lưu Biểu",
	zhuran: "Chu Nhiên",
	yujin: "Vu Cấm",
	masu: "Cựu Mã Tốc",
	masu_prefix: "Cựu",
	xin_masu: "Mã Tốc",
	xin_fazheng: "Pháp Chính",
	wuguotai: "Ngô Quốc Thái",
	chengong: "Trần Cung",
	xusheng: "Từ Thịnh",
	guohuai: "Quách Hoài",
	caochong: "Tào Xung",
	bulianshi: "Bộ Luyện Sư",
	handang: "Hàn Đương",
	fuhuanghou: "Phục Thọ",
	caifuren: "Cái Phu Nhân",
	zhonghui: "Chung Hội",
	old_zhonghui: "Cựu Chung Hội",
	old_zhonghui_prefix: "Cựu",
	sunluban: "Tôn Lỗ Ban",
	chenqun: "Trần Quần",
	zhangsong: "Trương Tùng",
	guyong: "Cố Ung",
	jianyong: "Giản Ung",
	old_madai: "Mã Đại",
	gz_madai: "Mã Đại",
	xin_xushu: "Từ Thứ",
	manchong: "Mãn Sủng",
	liufeng: "Lưu Phong",
	liru: "Cựu Lý Nho",
	liru_prefix: "Cựu",
	yj_jushou: "Thư Thụ",
	zhuhuan: "Chu Hoán",
	xiahoushi: "Hạ Hầu Thị",
	panzhangmazhong: "Phan Chương Mã Trung",
	caorui: "Tào Duệ",
	caoxiu: "Tào Hưu",
	zhongyao: "Chung Do",
	liuchen: "Lưu Thầm",
	zhangyi: "Trương Ng嶷",
	sunxiu: "Tôn Hưu",
	zhuzhi: "Chu Trị",
	quancong: "Toàn Tùng",
	gongsunyuan: "Công Tôn Uyên",
	guotufengji: "Quách Đồ Phùng Kỷ",
	zhoucang: "Chu Thương",
	guanping: "Quan Bình",
	liaohua: "Liêu Hóa",
	caozhen: "Tào Chân",
	wuyi: "Ngô Ý",
	hanhaoshihuan: "Hàn Hạo Sử Hoán",
	chengpu: "Trình Phổ",
	gaoshun: "Cao Thuận",
	xin_liru: "Lý Nho",
	guohuanghou: "Quách Hoàng Hậu",
	liuyu: "Lưu Ngu",
	sundeng: "Tôn Đăng",
	liyan: "Lý Nghiêm",
	sunziliufang: "Tôn Tư Lưu Phóng",
	huanghao: "Hoàng Hạo",
	zhangrang: "Trương Nhượng",
	cenhun: "Sầm Hôn",
	xinxianying: "Tân Hiến Anh",
	wuxian: "Ngô莧",
	xushi: "Từ Thị",
	caojie: "Tào Tiết",
	xuezong: "Tiết Tổng",
	jikang: "Kê Khang",
	qinmi: "Tần Mật",
	caiyong: "Cái Ung",

	new_qingxian: "Thanh Huyền",
	new_qingxian_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ tối đa X lá bài và chọn số lượng nhân vật khác tương ứng. Trong số các nhân vật này, người có số bài trong khu trang bị ít hơn bạn hồi 1 điểm thể lực, bằng bạn thì rút một lá bài, nhiều hơn bạn thì mất 1 điểm thể lực. Nếu số nhân vật bạn chỉ định bằng X, bạn rút một lá bài. (X là trị số thể lực của bạn)",
	new_juexiang: "Tuyệt Xướng",
	new_juexiang_info: `Kỹ năng khóa, sau khi bạn chết, nhân vật giết bạn bỏ tất cả bài trong khu trang bị và mất 1 điểm thể lực. Sau đó, bạn có thể khiến một nhân vật khác nhận kỹ năng ${get.poptip("new_canyun")}. Nếu trên sân có lá bài chất Chuồn (Tép), người đó có thể bỏ một lá trong số đó, sau đó nhận kỹ năng ${get.poptip("new_juexiang")}.`,
	new_canyun: "Tàn Vận",
	new_canyun_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ tối đa X lá bài và chọn số lượng nhân vật khác tương ứng (không thể chọn nhân vật đã từng trở thành mục tiêu của 〖Tàn Vận〗). Trong số các nhân vật này, người có số bài trong khu trang bị ít hơn bạn hồi 1 điểm thể lực, bằng bạn thì rút một lá bài, nhiều hơn bạn thì mất 1 điểm thể lực. Nếu số nhân vật bạn chỉ định bằng X, bạn rút một lá bài. (X là trị số thể lực của bạn)",
	qingxian_draw: "Thanh Huyền",
	qingxian_draw_info: "",
	zhenjun: "Trấn Quân",
	zhenjun_info: "Giai đoạn chuẩn bị, bạn có thể bỏ X lá bài của một nhân vật có số bài trên tay nhiều hơn trị số thể lực (X là hiệu giữa số bài trên tay và trị số thể lực), sau đó chọn một: 1. Bạn bỏ số lượng bài bằng số bài không phải trang bị trong đó; 2. Người đó rút số lượng bài tương ứng.",
	rezhenjun: "Trấn Quân",
	rezhenjun_info: "Giai đoạn chuẩn bị, bạn có thể bỏ X lá bài của một nhân vật (X là hiệu giữa số bài trên tay và trị số thể lực của người đó và ít nhất là 1), sau đó chọn một: 1. Bạn bỏ X lá bài; 2. Người đó rút X lá bài. (X là số lượng bài không phải trang bị trong số bài người đó đã bỏ)",
	fenli: "Phấn Lệ",
	fenli_info: "Nếu số bài trên tay của bạn là nhiều nhất toàn sân, bạn có thể bỏ qua giai đoạn rút bài; nếu trị số thể lực của bạn là cao nhất toàn sân, bạn có thể bỏ qua giai đoạn ra bài; nếu khu trang bị của bạn có bài và số lượng là nhiều nhất toàn sân, bạn có thể bỏ qua giai đoạn bỏ bài.",
	pingkou: "Bình Khấu",
	pingkou_info: "Khi kết thúc lượt, bạn có thể gây cho tối đa X nhân vật khác mỗi người 1 điểm sát thương (X là số giai đoạn bạn đã bỏ qua trong lượt này).",
	xinanguo: "An Quốc",
	xinanguo_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể chọn một nhân vật khác, nếu số bài trên tay người đó ít nhất toàn sân, người đó rút một lá bài; trị số thể lực thấp nhất toàn sân, hồi 1 điểm thể lực; số bài trong khu trang bị ít nhất toàn sân, ngẫu nhiên sử dụng một lá trang bị. Sau đó nếu nhân vật đó có hiệu ứng chưa thực hiện và bạn thỏa mãn điều kiện, bạn thực hiện nó.",
	pindi: "Phẩm Đệ",
	pindi_info: "Giai đoạn ra bài, bạn có thể bỏ một lá bài và chọn một nhân vật khác (không thể bỏ bài cùng loại và không thể chỉ định cùng một nhân vật), sau đó khiến người đó thực hiện một: rút X lá bài; bỏ X lá bài (X là số lần phát động kỹ năng này trong lượt này). Nếu người đó đã bị thương, bạn bị xích (hoành trí).",
	funan_jiexun: "Giới Huấn",
	bizhuan: "Tích Soạn",
	bizhuan_bg: "Thư",
	bizhuan_info: "Sau khi bạn sử dụng lá bài chất Bích, hoặc bạn trở thành mục tiêu của lá bài chất Bích do nhân vật khác sử dụng, bạn có thể đặt một lá bài từ đỉnh chồng bài lên võ tướng bài, gọi là \"Thư\"; bạn sở hữu tối đa bốn lá \"Thư\", mỗi lá \"Thư\" giúp giới hạn bài trên tay +1.",
	tongbo: "Thông Bác",
	tongbo_info: "Sau khi rút bài ở giai đoạn rút bài, bạn có thể dùng số lượng bài tùy ý để thay thế số lượng tương đương lá \"Thư\", sau đó nếu \"Thư\" của bạn bao gồm đủ bốn loại chất, bạn giao tất cả \"Thư\" cho số lượng nhân vật khác tùy ý.",
	qingxian: "Thanh Huyền",
	qingxian_info: "Sau khi bạn chịu sát thương/hồi phục thể lực, bạn có thể khiến nguồn sát thương/một nhân vật khác thực hiện một: mất 1 điểm thể lực, ngẫu nhiên sử dụng một lá trang bị; hồi 1 điểm thể lực, bỏ một lá trang bị. Nếu lá bài sử dụng hoặc bỏ theo cách này là chất Chuồn, bạn rút một lá bài.",
	juexiang: "Tuyệt Xướng",
	juexiang_info: "Sau khi bạn chết, bạn có thể khiến một nhân vật ngẫu nhiên nhận được một kỹ năng trong \"Thanh Huyền Tàn Phổ\", sau đó cho đến khi bắt đầu lượt tiếp theo của người đó, người đó không thể bị chọn làm mục tiêu của lá bài chất Chuồn do nhân vật khác sử dụng.",
	juexiang_ji: "Kích Huyền",
	juexiang_ji_info: "Sau khi bạn chịu sát thương, bạn có thể khiến nguồn sát thương mất 1 điểm thể lực, ngẫu nhiên sử dụng một lá trang bị.",
	juexiang_lie: "Liệt Huyền",
	juexiang_lie_info: "Sau khi bạn hồi phục thể lực, bạn có thể khiến một nhân vật khác mất 1 điểm thể lực, ngẫu nhiên sử dụng một lá trang bị.",
	juexiang_rou: "Nhu Huyền",
	juexiang_rou_info: "Sau khi bạn chịu sát thương, bạn có thể khiến nguồn sát thương hồi 1 điểm thể lực, bỏ một lá trang bị.",
	juexiang_he: "Hòa Huyền",
	juexiang_he_info: "Sau khi bạn hồi phục thể lực, bạn có thể khiến một nhân vật khác hồi 1 điểm thể lực, bỏ một lá trang bị.",
	juexiang_club: "Tuyệt Xướng",
	juexiang_club_bg: "Hưởng",
	juexiang_club_info: "Cho đến khi bắt đầu lượt tiếp theo, không thể bị chọn làm mục tiêu của lá bài chất Chuồn do nhân vật khác sử dụng.",
	jianzheng: "Gián Chinh",
	jianzheng_info: "Khi một nhân vật khác sử dụng [Sát] chỉ định mục tiêu, nếu bạn nằm trong phạm vi tấn công của người đó và bạn không phải là mục tiêu, bạn có thể đặt một lá bài trên tay lên đỉnh chồng bài, hủy bỏ tất cả mục tiêu, sau đó nếu lá [Sát] này không phải màu đen, bạn trở thành mục tiêu.",
	zhuandui: "Chuyên Đối",
	zhuandui_info: "Sau khi bạn sử dụng [Sát] chỉ định mục tiêu/trở thành mục tiêu của [Sát], bạn có thể cùng nhân vật mục tiêu/người sử dụng [Sát] này so bài, nếu bạn thắng, [Sát] này không thể bị phản hồi bởi [Thiểm]/vô hiệu với bạn.",
	zhuandui_use_info: "Sau khi bạn sử dụng [Sát] chỉ định mục tiêu, bạn có thể cùng nhân vật mục tiêu so bài, nếu bạn thắng, [Sát] này không thể bị phản hồi bởi [Thiểm].",
	zhuandui_respond_info: "Sau khi bạn trở thành mục tiêu của [Sát], bạn có thể cùng người sử dụng [Sát] này so bài, nếu bạn thắng, [Sát] này vô hiệu với bạn.",
	tianbian: "Thiên Biện",
	tianbian_info: "Khi bạn so bài, có thể đổi thành dùng một lá bài trên đỉnh chồng bài để so; sau khi lá bài so bài của bạn lật ra, nếu lá bài này chất Cơ, điểm của nó được xem là K.",
	funan: "Phục Nan",
	funan_info: "Khi nhân vật khác sử dụng hoặc đánh ra bài để phản hồi lá bài bạn sử dụng, bạn có thể khiến người đó nhận lấy lá bài bạn đã sử dụng (người đó trong lượt này không thể sử dụng hoặc đánh ra những lá bài này), sau đó bạn nhận lấy lá bài người đó đã sử dụng hoặc đánh ra.",
	jiexun: "Giới Huấn",
	jiexun_info: "Giai đoạn kết thúc, bạn có thể khiến một nhân vật khác rút số bài bằng số lá bài chất Rô trên sân, sau đó bỏ X lá bài (X là số lần kỹ năng này đã phát động trước đó). Nếu có nhân vật vì cách này mà bỏ tất cả bài, bạn mất 〖Giới Huấn〗, sau đó khi phát động 〖Phục Nan〗, không cần khiến đối phương nhận lấy lá bài bạn sử dụng.",
	xinjiexun: "Giới Huấn",
	xinjiexun_info: "Giai đoạn kết thúc, bạn có thể khiến một nhân vật khác rút số bài bằng số lá bài chất Rô trên sân, sau đó bỏ X lá bài (X là số lần kỹ năng này đã phát động trước đó). Nếu có nhân vật vì cách này mà bỏ tất cả bài, bạn đưa X về 0, sau đó khi phát động 〖Phục Nan〗, không cần khiến đối phương nhận lấy lá bài bạn sử dụng.",
	shouxi: "Thủ Tỷ",
	shouxi_info: "Sau khi bạn trở thành mục tiêu của [Sát], bạn có thể tuyên bố tên một loại bài Cơ bản hoặc Cẩm nang chưa từng tuyên bố theo cách này. Nếu người sử dụng bỏ một lá bài bạn đã tuyên bố, người đó lấy một lá bài của bạn; nếu không, lá [Sát] này vô hiệu với bạn.",
	huimin: "Huệ Dân",
	huimin_info: "Giai đoạn kết thúc, bạn có thể rút X lá bài và trưng ra số bài trên tay tương đương (X là số nhân vật có bài trên tay ít hơn trị số thể lực), sau đó bắt đầu từ một nhân vật bạn chỉ định, các nhân vật này lần lượt chọn và nhận lấy một lá trong số đó.",
	wengua: "Vấn Quái",
	wengua2: "Vấn Quái",
	wengua_info: "Giai đoạn ra bài của nhân vật khác/của bạn giới hạn một lần, người đó có thể giao cho bạn một lá bài (nếu lượt hiện tại là của bạn thì bỏ qua bước này), bạn có thể đặt lá bài này/một lá bài lên đỉnh hoặc xuống đáy chồng bài, sau đó bạn cùng người đó/bạn rút một lá bài từ đầu kia.",
	fuzhu: "Phục Tru",
	fuzhu_info: "Giai đoạn kết thúc của một nhân vật nam, nếu số bài còn lại trong chồng bài không lớn hơn mười lần trị số thể lực của bạn, bạn có thể lần lượt đối với người đó sử dụng tất cả lá [Sát] trong chồng bài (không vượt quá số người chơi), sau đó xáo bài.",
	fumian: "Phúc Miên",
	fumian_info: "Giai đoạn chuẩn bị, bạn có thể chọn một: 1. Giai đoạn rút bài rút thêm một lá bài; 2. Sử dụng bài màu đỏ có thể chọn thêm một mục tiêu (giới hạn một lần). Nếu khác với lựa chọn ở lượt trước của bạn, trị số lựa chọn đó +1 và khôi phục kỹ năng này.",
	daiyan: "Đãi Yến",
	daiyan_info: "Giai đoạn kết thúc, bạn có thể khiến một nhân vật khác nhận một lá bài Cơ bản chất Cơ từ chồng bài, sau đó nếu người đó đã từng là mục tiêu của kỹ năng này ở lượt trước, người đó mất 1 điểm thể lực.",
	xinzhongjian: "Trung Giám",
	xinzhongjian_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể trưng ra một lá bài trên tay của mình, sau đó trưng ra tối đa ba lá bài trên tay của một nhân vật khác. Trong số bài người đó trưng ra: mỗi khi có một lá cùng chất, bạn rút một lá bài; cùng điểm, bạn gây cho người đó 1 điểm sát thương; đều khác nhau, bạn bỏ một lá bài trên tay.",
	zhongjian: "Trung Giám",
	zhongjian_bg: "Giám",
	zhongjian_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể trưng ra một lá bài trên tay, sau đó trưng ra X lá bài trên tay của một nhân vật khác (X là trị số thể lực của người đó). Nếu bài trưng ra theo cách này và bài bạn trưng ra: có màu giống nhau, bạn chọn: ① Rút một lá bài. ② Bỏ một lá bài của một nhân vật khác; có điểm giống nhau, lượt này kỹ năng này đổi thành \"Giai đoạn ra bài giới hạn hai lần\"; đều khác nhau, giới hạn bài trên tay của bạn -1.",
	caishi: "Tài Thức",
	caishix: "Tài Thức/Trung Giám",
	caishi_info: "Khi bắt đầu giai đoạn rút bài, bạn có thể chọn một: 1. Khiến giới hạn bài trên tay +1; 2. Hồi 1 điểm thể lực, trong lượt này không thể tự sử dụng bài cho bản thân.",
	xincaishi: "Tài Thức",
	xincaishi_info: "Giai đoạn rút bài, bạn có thể chọn một: 1. Rút ít đi một lá bài, sau đó khi phát động 〖Trung Giám〗 trong lượt này có thể trưng thêm một lá bài của mình; 2. Lượt này giới hạn bài trên tay -1, sau đó khi phát động 〖Trung Giám〗 trong lượt này có thể trưng thêm một lá bài của đối phương; 3. Rút thêm hai lá bài, lượt này không thể phát động 〖Trung Giám〗.",
	guizao: "Cừ Tảo",
	guizao_info: "Khi kết thúc giai đoạn bỏ bài, nếu số lượng bài bạn bỏ trong giai đoạn này không ít hơn 2 và chất của chúng hoàn toàn khác nhau, bạn có thể hồi 1 điểm thể lực hoặc rút một lá bài.",
	jiyu: "Cơ Du",
	jiyu_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể khiến một nhân vật bỏ một lá bài trên tay. Nếu làm vậy, bạn không thể sử dụng bài cùng chất với lá đó cho đến khi kết thúc lượt. Nếu lá bài người đó bỏ theo cách này là chất Bích, bạn lật mặt và khiến người đó mất 1 điểm thể lực. Nếu bạn có bài trên tay chưa bị 〖Cơ Du〗 hạn chế, bạn có thể tiếp tục phát động kỹ năng này, nhưng không thể chọn mục tiêu đã chọn trong lượt này.",
	qinqing: "Tẩm Tình",
	qinqing_info: "Giai đoạn kết thúc, bạn có thể chọn số lượng nhân vật tùy ý có phạm vi tấn công bao gồm Chủ công, sau đó bỏ của mỗi nhân vật đó một lá bài và khiến họ rút một lá bài (không bài thì không bỏ), nếu làm vậy, bạn rút X lá bài (X là số nhân vật có bài trên tay nhiều hơn Chủ công).",
	qinqing_info_doudizhu: "Giai đoạn kết thúc, bạn có thể chọn số lượng nhân vật tùy ý có phạm vi tấn công bao gồm Địa chủ, sau đó bỏ của mỗi nhân vật đó một lá bài và khiến họ rút một lá bài (không bài thì không bỏ), nếu làm vậy, bạn rút X lá bài (X là số nhân vật có bài trên tay nhiều hơn Địa chủ).",
	huisheng: "Hối Sinh",
	huisheng_info: "Khi bạn chịu sát thương do nhân vật khác gây ra, bạn có thể khiến người đó xem số lượng bài tùy ý của bạn và khiến người đó chọn một: 1. Nhận lấy một lá trong số đó, ngăn chặn sát thương này, sau đó bạn không thể phát động 〖Hối Sinh〗 với người đó nữa; 2. Bỏ số lượng bài tương ứng.",
	jishe: "Cực Xa",
	jishe2: "Cực Xa",
	jishe_info: "① Giai đoạn ra bài giới hạn 20 lần, nếu giới hạn bài trên tay của bạn lớn hơn 0, bạn có thể rút một lá bài, sau đó giới hạn bài trên tay lượt này của bạn -1. ② Khi bắt đầu giai đoạn kết thúc, nếu bạn không có bài trên tay, bạn có thể xích tối đa X nhân vật (X là trị số thể lực của bạn).",
	lianhuo: "Liên Họa",
	lianhuo_info: "Kỹ năng khóa, khi bạn chịu sát thương lửa, nếu võ tướng bài của bạn đang trong trạng thái xích và sát thương này không phải sát thương liên hoàn, sát thương này +1.",
	taoluan: "Thao Loạn",
	taoluan_backup: "Thao Loạn",
	taoluan_info: "Bạn có thể dùng một lá bài làm bất kỳ một lá bài Cơ bản hoặc Cẩm nang thông thường nào để sử dụng (lá bài này không được là lá bạn đã sử dụng theo cách này trong ván đấu này), sau đó bạn khiến một nhân vật khác chọn một: 1. Giao cho bạn một lá bài khác loại với lá bạn đã sử dụng; 2. Bạn mất 1 điểm thể lực và 〖Thao Loạn〗 vô hiệu cho đến khi kết thúc lượt.",
	xintaoluan: "Thao Loạn",
	xintaoluan_backup: "Thao Loạn",
	xintaoluan_info: "Nếu trên sân không có nhân vật hấp hối, bạn có thể dùng một lá bài làm bất kỳ một lá bài Cơ bản hoặc Cẩm nang thông thường nào để sử dụng (lá bài này không được là lá bạn đã sử dụng theo cách này trong lượt này), sau đó bạn khiến một nhân vật khác chọn một: 1. Giao cho bạn X lá bài khác loại với lá bạn đã sử dụng; 2. Bạn mất X điểm thể lực và Thao Loạn vô hiệu cho đến khi kết thúc lượt (X là số lần bạn đã phát động 〖Thao Loạn〗 trong lượt này và tối đa là 3).",
	jiaozhao: "Kiểu Chiếu",
	jiaozhao3: "Kiểu Chiếu",
	jiaozhao3_backup: "Kiểu Chiếu",
	jiaozhao2: "Kiểu Chiếu",
	jiaozhao_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể trưng ra một lá bài trên tay, sau đó chọn một nhân vật khác gần nhất, nhân vật đó tuyên bố tên một lá bài Cơ bản. Trong giai đoạn ra bài này, bạn có thể dùng lá bài trên tay này làm lá bài đã tuyên bố để sử dụng (bạn không thể sử dụng lá bài này cho bản thân).",
	danxin: "Đạn Tâm",
	danxin_info: "Sau khi bạn chịu sát thương, bạn có thể rút một lá bài, hoặc thực hiện một sửa đổi sau đây đối với mô tả của \"Kiểu Chiếu\" theo thứ tự: 1. Đổi \"lá bài Cơ bản\" thành \"lá bài Cơ bản hoặc Cẩm nang thông thường\"; 2. Đổi \"chọn một nhân vật khác gần nhất, nhân vật đó\" thành \"bạn\".",
	xindanxin: "Đạn Tâm",
	xindanxin_info: "Sau khi bạn chịu sát thương, bạn có thể rút một lá bài, và thực hiện một sửa đổi sau đây đối với mô tả của \"Kiểu Chiếu\" theo thứ tự: 1. Đổi \"lá bài Cơ bản\" thành \"lá bài Cơ bản hoặc Cẩm nang thông thường\"; 2. Đổi \"chọn một nhân vật khác gần nhất, nhân vật đó\" thành \"bạn\". 3. Đổi \"Giai đoạn ra bài giới hạn một lần\" thành \"Giai đoạn ra bài giới hạn hai lần\".",
	duliang: "Đốc Lương",
	duliang2: "Đốc Lương",
	duliang_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể lấy một lá bài trên tay của nhân vật khác, sau đó chọn một: 1. Khiến người đó xem hai lá bài trên đỉnh chồng bài, sau đó nhận lấy lá bài Cơ bản trong đó; 2. Khiến người đó rút thêm một lá bài ở giai đoạn rút bài tiếp theo.",
	fulin: "Phúc Lân",
	fulin_info: "Kỹ năng khóa, những lá bài bạn nhận được trong lượt không tính vào giới hạn bài trên tay của bạn trong lượt này.",
	kuangbi: "Khuông Bật",
	kuangbi_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể chọn một nhân vật khác có bài, nhân vật đó đặt từ một đến ba lá bài của họ lên võ tướng bài của bạn. Nếu làm vậy, vào giai đoạn chuẩn bị tiếp theo của bạn, bạn nhận tất cả bài trên võ tướng bài, sau đó người đó rút số lượng bài tương đương.",
	xinzhige: "Chỉ Qua",
	xinzhige_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể khiến một nhân vật khác có phạm vi tấn công bao gồm bạn giao cho bạn một lá [Sát] hoặc bài Trang bị Vũ khí, nếu không người đó xem như đối với một nhân vật khác trong phạm vi tấn công do bạn chỉ định sử dụng một lá [Sát].",
	zhige: "Chỉ Qua",
	zhige_info: "Giai đoạn ra bài giới hạn một lần, nếu số bài trên tay của bạn nhiều hơn trị số thể lực, bạn có thể chọn một nhân vật khác có phạm vi tấn công bao gồm bạn, người đó chọn một: 1. Sử dụng một lá [Sát]; 2. Giao một lá bài trong khu trang bị cho bạn.",
	xinzongzuo: "Tông Tộ",
	xinzongzuo_info: "Kỹ năng khóa, trước khi bắt đầu lượt đầu tiên của trò chơi, bạn tăng X điểm giới hạn thể lực và hồi X điểm thể lực (X là số phe phái toàn sân); khi một nhân vật chết, nếu không còn nhân vật cùng phe phái với người đó, bạn giảm 1 điểm giới hạn thể lực và rút hai lá bài.",
	zongzuo: "Tông Tộ",
	zongzuo_info: "Kỹ năng khóa, trước khi bắt đầu lượt đầu tiên của trò chơi, bạn tăng X điểm giới hạn thể lực và hồi X điểm thể lực (X là số phe phái toàn sân); khi một nhân vật chết, nếu không còn nhân vật cùng phe phái với người đó, bạn giảm 1 điểm giới hạn thể lực.",
	xinjuece: "Tuyệt Sách",
	xinjuece_info: "Giai đoạn kết thúc, bạn có thể gây cho một nhân vật không có bài trên tay 1 điểm sát thương.",
	xinmieji: "Diệt Kế",
	xinmieji_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể trưng ra một lá Cẩm nang màu đen và đặt nó lên đỉnh chồng bài, sau đó khiến một nhân vật khác có bài trên tay chọn một: bỏ một lá Cẩm nang; hoặc lần lượt bỏ hai lá không phải Cẩm nang.",
	xinfencheng: "Phần Thành",
	xinfencheng_info: "Kỹ năng giới hạn. Giai đoạn ra bài, bạn có thể khiến tất cả các nhân vật khác mỗi người chọn một: bỏ ít nhất X lá bài (X là số lượng bài nhân vật cửa trên đã bỏ theo cách này + 1); hoặc chịu 2 điểm sát thương lửa do bạn gây ra.",
	qianju: "Thiên Câu",
	qianju_info: "Kỹ năng khóa, nếu bạn đã bị thương, khoảng cách bạn tính đến các nhân vật khác -X (X là số thể lực đã mất của bạn).",
	qingxi: "Khuynh Tập",
	qingxi_info: "Khi bạn sử dụng [Sát] gây sát thương cho nhân vật mục tiêu, nếu khu trang bị của bạn có bài Vũ khí, bạn có thể khiến người đó chọn một: 1. Bỏ X lá bài trên tay (X là phạm vi tấn công của bài Vũ khí này), nếu làm vậy, người đó bỏ lá Vũ khí này của bạn; 2. Khiến trị số sát thương +1.",
	reqianju: "Thiên Câu",
	reqianju_info: "Kỹ năng khóa, nếu bạn đã bị thương, khoảng cách bạn tính đến các nhân vật khác -X (X là số thể lực đã mất của bạn và ít nhất là 1).",
	reqingxi: "Khuynh Tập",
	reqingxi_info: "Sau khi bạn sử dụng [Sát] hoặc [Quyết Đấu] chỉ định mục tiêu, bạn có thể khiến người đó chọn một: 1. Bỏ X lá bài trên tay (X là số nhân vật trong phạm vi tấn công của bạn, và tối đa là 4/2 khi bạn có/không có bài Vũ khí), nếu làm vậy, người đó bỏ lá Vũ khí này của bạn; 2. Khiến trị số sát thương của lá bài này +1 và bạn tiến hành phán xét, nếu kết quả là màu đỏ, người đó không thể phản hồi lá bài này.",
	jieyue: "Tiết Việt",
	jieyue_info: "① Giai đoạn kết thúc, bạn có thể bỏ một lá bài trên tay, sau đó khiến một nhân vật khác chọn một: 1. Đặt một lá bài lên võ tướng bài của bạn, gọi là \"Tiết\"; 2. Khiến bạn bỏ một lá bài của người đó. ② Nếu bạn có \"Tiết\", bạn có thể dùng bài trên tay màu đỏ/đen làm [Thiểm]/[Vô Giải Khả Kích] để sử dụng hoặc đánh ra. ③ Giai đoạn chuẩn bị, nếu bạn có \"Tiết\", bạn nhận lấy nó.",
	xianzhen: "Hãm Trận",
	xianzhen_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể cùng một nhân vật so bài. Nếu bạn thắng, bạn nhận được hiệu ứng sau cho đến khi kết thúc lượt: bỏ qua khoảng cách với nhân vật đó; bỏ qua phòng cụ của nhân vật đó và sử dụng [Sát] đối với người đó không giới hạn số lần. Nếu bạn không thắng, bạn không thể sử dụng [Sát] cho đến khi kết thúc lượt.",
	xinxianzhen: "Hãm Trận",
	xinxianzhen_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể cùng một nhân vật so bài. Nếu bạn thắng, bạn nhận được hiệu ứng sau cho đến khi kết thúc lượt: bỏ qua phòng cụ của nhân vật đó và sử dụng bài đối với người đó không giới hạn số lần và khoảng cách, và khi bạn sử dụng [Sát] hoặc Cẩm nang thông thường chỉ định mục tiêu duy nhất, có thể khiến nhân vật đó cũng trở thành mục tiêu của lá bài này. Nếu bạn không thắng, bạn không thể sử dụng [Sát] và lá [Sát] của bạn không tính vào giới hạn bài trên tay cho đến khi kết thúc lượt.",
	xinxianzhen2: "Hãm Trận",
	jinjiu: "Cấm Tửu",
	jinjiu_info: "Kỹ năng khóa, lá [Tửu] của bạn đều được xem là [Sát].",
	chunlao: "Thuần Lạo",
	chunlao2: "Thuần Lạo",
	chunlao_info: "Khi bắt đầu giai đoạn kết thúc, nếu bạn không có \"Thuần\", bạn có thể đặt ít nhất một lá [Sát] lên võ tướng bài, gọi là \"Thuần\". Khi một nhân vật trong trạng thái hấp hối, bạn có thể loại bỏ một lá \"Thuần\", xem như nhân vật đó sử dụng một lá [Tửu].",
	lihuo: "Lệ Hỏa",
	lihuo_info: "Sau khi bạn tuyên bố sử dụng [Sát] thông thường, bạn có thể đổi lá [Sát] này thành [Hỏa Sát]. Nếu lá [Sát] sử dụng theo cách này gây sát thương, sau khi kết thúc lá [Sát] này bạn mất 1 điểm thể lực; khi bạn sử dụng [Hỏa Sát] chọn mục tiêu, có thể chỉ định thêm một mục tiêu.",
	shenduan: "Thận Đoán",
	shenduan_info: "Khi lá bài Cơ bản màu đen của bạn đi vào chồng bài bỏ do bị bỏ đi, bạn có thể dùng nó làm lá [Binh Lương Thốn Đoạn] để sử dụng (không giới hạn khoảng cách).",
	yonglve: "Dũng Lược",
	yonglve_info: "Khi bắt đầu giai đoạn phán xét của một nhân vật khác, nếu người đó nằm trong phạm vi tấn công của bạn, bạn có thể bỏ một lá bài trong khu phán xét của người đó, xem như đối với nhân vật đó sử dụng một lá [Sát]. Nếu lá [Sát] này không gây sát thương, bạn rút một lá bài.",
	reshenduan: "Thận Đoán",
	reshenduan_info: "Khi lá bài Cơ bản màu đen hoặc bài Trang bị của bạn đi vào chồng bài bỏ do bị bỏ đi, bạn có thể dùng nó làm lá [Binh Lương Thốn Đoạn] để sử dụng (không giới hạn khoảng cách).",
	reyonglve: "Dũng Lược",
	reyonglve_info: "Khi bắt đầu giai đoạn phán xét của nhân vật khác, bạn có thể bỏ một lá bài trong khu phán xét của người đó. Sau đó nếu nhân vật đó nằm trong phạm vi tấn công của bạn, bạn rút một lá bài. Nếu người đó nằm ngoài phạm vi tấn công của bạn, xem như bạn đối với người đó sử dụng một lá [Sát].",
	benxi: "Bôn Tập",
	benxi_info: "Kỹ năng khóa, trong lượt của bạn, mỗi khi bạn sử dụng một lá bài, khoảng cách tấn công của bạn +1 cho đến khi kết thúc lượt; trong lượt của bạn, nếu khoảng cách của bạn đến tất cả nhân vật đều là 1, bạn bỏ qua phòng cụ của nhân vật khác, và lá [Sát] bạn sử dụng có thể chỉ định thêm một mục tiêu.",
	xinbenxi: "Bôn Tập",
	xinbenxi_info: "Kỹ năng khóa, khi bạn sử dụng bài trong lượt, khoảng cách bạn tính đến các nhân vật khác lượt này -1. Trong lượt của bạn, nếu khoảng cách của bạn đến tất cả các nhân vật khác trên sân đều không lớn hơn 1, khi bạn sử dụng [Sát] hoặc Cẩm nang thông thường chọn mục tiêu duy nhất, bạn chọn tối đa hai hạng mục: 1. Chỉ định thêm một mục tiêu cho lá bài này; 2. Khiến lá bài này bỏ qua phòng cụ; 3. Khiến lá bài này không thể bị triệt tiêu; 4. Rút một lá bài khi lá bài này gây sát thương.",
	sidi: "Ty Địch",
	sidi2: "Ty Địch",
	sidi3: "Ty Địch",
	sidi_info: "① Khi bạn sử dụng hoặc nhân vật khác trong lượt của bạn sử dụng [Thiểm], bạn có thể đặt lá bài trên đỉnh chồng bài lên võ tướng bài, gọi là bài \"Ty Địch\". ② Khi bắt đầu giai đoạn ra bài của nhân vật khác, bạn có thể loại bỏ một lá bài \"Ty Địch\", khiến giới hạn số lần sử dụng [Sát] của người đó trong giai đoạn này -1.",
	xinsidi: "Ty Địch",
	xinsidi2: "Ty Địch",
	xinsidi_info: "Khi bắt đầu giai đoạn ra bài của nhân vật khác, bạn có thể bỏ một lá không phải bài Cơ bản có cùng màu với bài trong khu trang bị của bạn, sau đó nhân vật đó trong giai đoạn này không thể sử dụng và đánh ra bài cùng màu với lá bài này. Khi kết thúc giai đoạn này, nếu người đó không sử dụng [Sát] trong giai đoạn này, xem như bạn đối với người đó sử dụng một lá [Sát].",
	dangxian: "Đương Tiên",
	dangxian_info: "Kỹ năng khóa, khi bắt đầu lượt, bạn thực hiện thêm một giai đoạn ra bài.",
	xindangxian: "Đương Tiên",
	xindangxian_info: "Kỹ năng khóa, khi bắt đầu lượt, bạn thực hiện thêm một giai đoạn ra bài. Khi bắt đầu giai đoạn này, bạn mất 1 điểm thể lực và nhận một lá [Sát] từ chồng bài/chồng bài bỏ (nếu bạn đã phát động 〖Phục Lịch〗, có thể không phát động hiệu ứng này).",
	longyin: "Long Ngâm",
	longyin_info: "Khi một nhân vật sử dụng [Sát] trong giai đoạn ra bài của mình, bạn có thể bỏ một lá bài khiến lá [Sát] này không tính vào số lần sử dụng trong giai đoạn ra bài, nếu lá [Sát] này màu đỏ, bạn rút một lá bài.",
	zhongyong: "Trung Dũng",
	zhongyong_info: "Khi lá [Sát] bạn sử dụng trong giai đoạn ra bài bị [Thiểm] của nhân vật mục tiêu triệt tiêu, bạn có thể giao lá [Thiểm] này cho một nhân vật trừ nhân vật đó. Nếu nhân vật nhận lá [Thiểm] không phải là bạn, bạn có thể đối với cùng mục tiêu sử dụng thêm một lá [Sát].",
	xinzhongyong: "Trung Dũng",
	xinzhongyong_info: "Sau khi lá [Sát] bạn sử dụng kết thúc quyết toán, bạn có thể giao lá [Sát] này hoặc lá [Thiểm] nhân vật mục tiêu đã sử dụng cho một nhân vật khác ngoài nhân vật đó, nhân vật nhận được lá bài màu đỏ theo cách này có thể đối với một nhân vật trong phạm vi tấn công của bạn sử dụng một lá [Sát].",
	jigong: "Cấp Công",
	jigong_info: "Khi bắt đầu giai đoạn ra bài, bạn có thể rút hai lá bài. Nếu làm vậy, giới hạn bài trên tay lượt này của bạn đổi thành X (X là tổng điểm sát thương bạn gây ra trong giai đoạn này).",
	shifei: "Sức Phi",
	shifei_info: "Khi bạn cần sử dụng hoặc đánh ra [Thiểm], bạn có thể khiến nhân vật lượt hiện tại rút một lá bài. Sau đó nếu số bài trên tay của người đó không phải là nhiều nhất duy nhất toàn sân, bạn bỏ một lá bài của nhân vật có số bài trên tay nhiều nhất (hoặc một trong số đó) toàn sân, xem như bạn đã sử dụng hoặc đánh ra một lá [Thiểm].",
	huaiyi: "Hoài Dị",
	huaiyi_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể trưng ra tất cả bài trên tay, nếu màu sắc của những lá bài này không hoàn toàn giống nhau, bạn chọn một màu và bỏ tất cả bài trên tay màu đó, sau đó bạn có thể lấy của tối đa X nhân vật mỗi người một lá bài (X là số bài trên tay bạn đã bỏ theo cách này). Nếu bạn lấy được không ít hơn hai lá bài theo cách này, bạn mất 1 điểm thể lực.",
	yaoming: "Yêu Danh",
	yaoming_info: "Mỗi lượt giới hạn một lần, sau khi bạn gây ra hoặc chịu sát thương, bạn có thể chọn một: 1. Bỏ một lá bài trên tay của một nhân vật có số bài trên tay nhiều hơn bạn; 2. Khiến một nhân vật có số bài trên tay ít hơn bạn rút một lá bài.",
	xinyaoming: "Yêu Danh",
	xinyaoming_info: "Mỗi lượt mỗi lựa chọn giới hạn một lần, sau khi bạn gây ra hoặc chịu sát thương, bạn có thể chọn một: 1. Bỏ một lá bài trên tay của một nhân vật khác; 2. Khiến một nhân vật khác rút một lá bài; 3. Khiến một nhân vật bỏ tối đa hai lá bài, sau đó rút số lượng bài tương đương.",
	anguo: "An Quốc",
	anguo_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể chọn một lá bài trong khu trang bị của một nhân vật khác, khiến người đó nhận lấy lá bài này. Sau đó nếu số nhân vật trong phạm vi tấn công của nhân vật đó vì vậy mà giảm đi, bạn rút một lá bài.",
	yanzhu: "Yến Tru",
	yanzhu_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể khiến một nhân vật khác có bài chọn một: khiến bạn nhận tất cả bài trong khu trang bị của họ, sau đó bạn mất kỹ năng 〖Yến Tru〗; hoặc bỏ một lá bài.",
	xingxue: "Hưng Học",
	xingxue_info: "Khi bắt đầu giai đoạn kết thúc, bạn có thể khiến tối đa X nhân vật lần lượt rút một lá bài và đặt một lá bài lên đỉnh chồng bài (X là trị số thể lực của bạn, nếu bạn đã mất kỹ năng 〖Yến Tru〗, đổi X thành giới hạn thể lực của bạn).",
	zhaofu: "Chiếu Phược",
	zhaofu_info: "Kỹ năng Chủ công, kỹ năng khóa, nhân vật có khoảng cách 1 với bạn được xem là nằm trong phạm vi tấn công của các nhân vật phe Ngô khác.",
	reyanzhu: "Yến Tru",
	reyanzhu2: "Yến Tru",
	reyanzhu_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể khiến một nhân vật khác chọn một: giao tất cả bài trong khu trang bị cho bạn và khiến bạn sửa đổi 〖Yến Tru〗 và 〖Hưng Học〗, hoặc bỏ một lá bài và khiến sát thương phải chịu lần tiếp theo +1 cho đến khi bắt đầu lượt tiếp theo của họ.",
	reyanzhu_rewrite: "Yến Tru · Cải",
	reyanzhu_rewrite_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể chọn một nhân vật khác. Sát thương nhân vật đó phải chịu lần tiếp theo +1 cho đến khi bắt đầu lượt tiếp theo của họ.",
	rexingxue: "Hưng Học",
	rexingxue_info: "Khi bắt đầu giai đoạn kết thúc, bạn có thể khiến tối đa X nhân vật mỗi người rút một lá bài. Sau đó nếu có nhân vật mục tiêu có số bài trên tay nhiều hơn trị số thể lực, các nhân vật đó mỗi người đặt một lá bài lên đỉnh chồng bài. (X là trị số thể lực của bạn).",
	rexingxue_rewrite: "Hưng Học · Cải",
	rexingxue_rewrite_info: "Khi bắt đầu giai đoạn kết thúc, bạn có thể khiến tối đa X nhân vật mỗi người rút một lá bài. Sau đó nếu có nhân vật mục tiêu có số bài trên tay nhiều hơn trị số thể lực, các nhân vật đó mỗi người đặt một lá bài lên đỉnh chồng bài. (X là giới hạn thể lực của bạn).",
	rezhaofu: "Chiếu Phược",
	rezhaofu_info: "Kỹ năng Chủ công, kỹ năng khóa, nhân vật trong phạm vi tấn công của bạn được xem là nằm trong phạm vi tấn công của các nhân vật phe Ngô khác.",
	wurong: "Vũ Nhung",
	wurong_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể khiến một nhân vật khác cùng bạn đồng thời trưng ra một lá bài trên tay: nếu bạn trưng ra là [Sát] và nhân vật đó trưng ra không phải là [Thiểm], bạn bỏ lá [Sát] này và gây cho họ 1 điểm sát thương; nếu bạn trưng ra không phải là [Sát] và nhân vật đó trưng ra là [Thiểm], bạn bỏ lá bài mình đã trưng và lấy một lá bài của họ.",
	shizhi: "Thệ Chí",
	shizhi_info: "Kỹ năng khóa, khi trị số thể lực của bạn là 1, các lá [Thiểm] của bạn đều được xem là [Sát].",
	zhanjue: "Chiến Tuyệt",
	zhanjue_info: "Giai đoạn ra bài, bạn có thể dùng tất cả bài trên tay làm lá [Quyết Đấu] để sử dụng. Sau khi kết thúc [Quyết Đấu] này, bạn và nhân vật chịu sát thương từ cách này mỗi người rút một lá bài. Nếu bạn trong cùng một giai đoạn vì cách này mà rút từ hai lá bài trở lên, kỹ năng này vô hiệu cho đến khi kết thúc lượt.",
	qinwang: "Cần Vương",
	qinwang1: "Cần Vương",
	qinwang2: "Cần Vương",
	qinwang_info: "Kỹ năng Chủ công, khi bạn cần sử dụng hoặc đánh ra một lá [Sát], bạn có thể bỏ một lá bài, sau đó xem như bạn đã phát động 〖Kích Tướng ①〗. Nếu có nhân vật phản hồi, nhân vật đó khi đánh ra [Sát] sẽ rút một lá bài.",
	huomo: "Hoạt Mặc",
	huomo_info: "Khi bạn cần sử dụng một lá bài Cơ bản chưa từng sử dụng trong lượt này, bạn có thể đặt một lá không phải Cơ bản màu đen lên đỉnh chồng bài, xem như sử dụng lá bài Cơ bản này.",
	zuoding: "Tá Định",
	zuoding_info: "Khi nhân vật khác trong lượt của họ sử dụng lá bài ♠ chỉ định mục tiêu, nếu trong lượt này chưa có nhân vật nào chịu sát thương, bạn có thể khiến một nhân vật mục tiêu rút một lá bài.",
	taoxi: "Thảo Tập",
	taoxi2: "Thảo Tập",
	taoxi3: "Thảo Tập",
	taoxi_info: "Giai đoạn ra bài giới hạn một lần. Sau khi bạn sử dụng bài chỉ định một nhân vật khác làm mục tiêu duy nhất, bạn có thể lật ra một lá bài trên tay của họ cho đến khi kết thúc lượt, và bạn trong lượt này có thể sử dụng lá bài này như bài trên tay. Khi kết thúc lượt, nếu lá bài này vẫn nằm trong khu bài trên tay của nhân vật đó, bạn mất 1 điểm thể lực.",
	huituo: "Khôi Thác",
	huituo_info: "Sau khi bạn chịu sát thương, bạn có thể khiến một nhân vật tiến hành một lần phán xét, nếu kết quả màu đỏ, nhân vật đó hồi 1 điểm thể lực; nếu kết quả màu đen, nhân vật đó rút X lá bài (X là điểm sát thương của lần sát thương này).",
	mingjian: "Minh Giám",
	mingjian2: "Minh Giám",
	mingjian_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể giao tất cả bài trên tay cho một nhân vật khác, sau đó nhân vật đó trong lượt tiếp theo của họ có giới hạn bài trên tay +1, và giới hạn số lần sử dụng [Sát] +1.",
	xingshuai: "Hưng Suy",
	xingshuai_info: "Kỹ năng Chủ công, kỹ năng giới hạn, khi bạn rơi vào trạng thái hấp hối, các nhân vật phe Ngụy khác có thể lần lượt khiến bạn hồi 1 điểm thể lực, sau đó những nhân vật này lần lượt chịu 1 điểm sát thương.",
	reduodao: "Đoạt Đao",
	reduodao_info: "Sau khi bạn trở thành mục tiêu của [Sát], bạn có thể bỏ một lá bài. Sau đó bạn nhận lấy lá bài Vũ khí trong khu trang bị của người sử dụng [Sát] này.",
	reanjian: "Ám Tiễn",
	reanjian_info: "Kỹ năng khóa, sau khi bạn sử dụng [Sát] chỉ định mục tiêu, nếu bạn không nằm trong phạm vi tấn công của họ, [Sát] này sát thương +1 và bỏ qua phòng cụ của họ. Nếu người đó vì thực hiện hiệu ứng của [Sát] này mà chịu sát thương và rơi vào trạng thái hấp hối, người đó không thể sử dụng [Đào] cho đến khi sự kiện hấp hối này kết thúc quyết toán.",
	duodao: "Đoạt Đao",
	duodao_info: "Sau khi bạn chịu sát thương do [Sát] gây ra, bạn có thể bỏ một lá bài, sau đó nhận lấy lá bài Vũ khí trong khu trang bị của nguồn sát thương.",
	anjian: "Ám Tiễn",
	anjian_info: "Kỹ năng khóa, khi bạn sử dụng [Sát] gây sát thương cho nhân vật mục tiêu, nếu bạn không nằm trong phạm vi tấn công của người đó, sát thương của lá [Sát] này +1.",
	xinpojun: "Phá Quân",
	xinpojun2: "Phá Quân",
	xinpojun_info: "Khi bạn sử dụng [Sát] chỉ định một mục tiêu trong giai đoạn ra bài, bạn có thể úp tối đa X lá bài của họ bên cạnh võ tướng bài của nhân vật đó (X là trị số thể lực của người đó). Nếu làm vậy, sau khi lượt hiện tại kết thúc, nhân vật đó nhận lại tất cả bài bên cạnh võ tướng bài của mình.",

	qiaoshi: "Tiều Thập",
	qiaoshi_info: "Khi bắt đầu giai đoạn kết thúc của nhân vật khác, nếu số bài trên tay của bạn bằng với họ, bạn có thể cùng họ mỗi người rút một lá bài.",
	yanyu: "Yến Ngữ",
	yanyu2: "Yến Ngữ",
	yanyu_info: "Giai đoạn ra bài, bạn có thể trọng chú [Sát]. Khi kết thúc giai đoạn ra bài, nếu bạn trong giai đoạn này đã trọng chú ít nhất hai lá [Sát] theo cách này, bạn có thể khiến một nhân vật nam rút hai lá bài.",

	zzhenggong: "Tranh Công",
	zzhenggong_info: "Sau khi bạn chịu sát thương, bạn có thể nhận một lá bài trong khu trang bị của nguồn sát thương và đặt vào khu trang bị của mình.",
	zquanji: "Quyền Kế",
	zquanji_info: "Khi bắt đầu lượt của nhân vật khác, bạn có thể cùng nhân vật đó so bài. Nếu bạn thắng, nhân vật đó bỏ qua giai đoạn chuẩn bị và giai đoạn phán xét.",
	zbaijiang: "Bái Tướng",
	zbaijiang_info: `Kỹ năng thức tỉnh. Giai đoạn chuẩn bị, nếu số bài trong khu trang bị của bạn không ít hơn hai lá, bạn tăng 1 điểm giới hạn thể lực, mất 〖Quyền Kế〗 và 〖Tranh Công〗, nhận được ${get.poptip("zyexin")} và ${get.poptip("zzili")}.`,
	zyexin: "Dã Tâm",
	zyexin2: "Dã Tâm",
	zyexin_info: "① Sau khi bạn gây ra hoặc chịu sát thương, bạn có thể đặt một lá bài trên đỉnh chồng bài lên võ tướng bài của mình, gọi là \"Quyền\". ② Giai đoạn ra bài giới hạn một lần. Bạn có thể dùng số lượng bài trên tay tùy ý để trao đổi với số lượng tương đương lá \"Quyền\".",
	zzili: "Tự Lập",
	zzili_info: `Kỹ năng thức tỉnh. Giai đoạn chuẩn bị, nếu số lượng \"Quyền\" không ít hơn 4, bạn giảm 1 điểm giới hạn thể lực và nhận được ${get.poptip("zpaiyi")}.`,
	zpaiyi: "Bài Dị",
	zpaiyi_info: "Giai đoạn kết thúc, bạn có thể chọn một lá \"Quyền\", nếu lá bài này là: bài Trang bị, bạn đặt lá bài này vào khu trang bị của một nhân vật; Cẩm nang duy trì, bạn đặt lá bài này vào khu phán xét của một nhân vật; bài Cơ bản hoặc Cẩm nang thông thường, bạn giao lá bài này cho một nhân vật. Sau đó nếu nhân vật tương ứng với khu vực mục tiêu của lá bài này không phải là bạn, bạn có thể rút một lá bài.",
	shibei: "Thệ Bắc",
	shibei_info: "Kỹ năng khóa, sau khi bạn chịu sát thương: nếu sát thương này là lần đầu tiên bạn chịu sát thương trong lượt này, bạn hồi 1 điểm thể lực; nếu không bạn mất 1 điểm thể lực.",
	jianying: "Tiệm Doanh",
	jianying_info: "Khi bạn sử dụng lá bài có cùng điểm hoặc cùng chất với lá bài trước đó bạn đã sử dụng trong giai đoạn ra bài, bạn có thể rút một lá bài.",
	xinenyuan: "Ân Oán",
	xinenyuan1: "Ân Oán",
	xinenyuan2: "Ân Oán",
	xinenyuan_info: "Sau khi bạn nhận từ một nhân vật khác hai lá bài trở lên, bạn có thể khiến họ rút một lá bài; sau khi bạn chịu 1 điểm sát thương, bạn có thể khiến nguồn sát thương chọn một: 1. Giao một lá bài trên tay cho bạn; 2. Mất 1 điểm thể lực.",
	xinxuanhuo: "Huyễn Hoặc",
	xinxuanhuo_info: "Khi bắt đầu giai đoạn rút bài, bạn có thể đổi thành khiến một nhân vật khác rút hai lá bài, sau đó nhân vật đó cần đối với một nhân vật khác trong phạm vi tấn công do bạn chọn sử dụng một lá [Sát], nếu không bạn lấy của họ hai lá bài.",
	fuhun: "Phụ Hồn",
	fuhun_info: `Bạn có thể dùng hai lá bài trên tay làm lá [Sát] để sử dụng hoặc đánh ra; sau khi lá [Sát] bạn sử dụng theo cách này trong giai đoạn ra bài gây sát thương, bạn nhận được ${get.poptip("new_rewusheng")} và ${get.poptip("olpaoxiao")} cho đến khi kết thúc lượt.`,
	yuce: "Ngự Sách",
	yuce_info: "Sau khi bạn chịu sát thương, bạn có thể trưng ra một lá bài trên tay, và khiến nguồn sát thương chọn một: bỏ một lá bài trên tay khác loại với lá này, hoặc khiến bạn hồi 1 điểm thể lực.",
	xiansi: "Hãm Tự",
	xiansix: "Hãm Tự",
	xiansi_bg: "Nghịch",
	xiansi2: "Hãm Tự",
	xiansi_info: "Khi bắt đầu giai đoạn chuẩn bị, bạn có thể đặt của một đến hai nhân vật mỗi người một lá bài lên võ tướng bài của mình, gọi là \"Nghịch\"; khi một nhân vật cần đối với bạn sử dụng [Sát], họ có thể loại bỏ hai lá \"Nghịch\", sau đó xem như đối với bạn sử dụng một lá [Sát].",
	chanhui: "Sấm Hủy",
	chanhui_info: "Giai đoạn ra bài giới hạn một lần, khi bạn sử dụng [Sát] hoặc Cẩm nang thông thường màu đen chỉ định mục tiêu duy nhất, bạn có thể khiến một nhân vật khác có thể trở thành mục tiêu của lá bài này chọn một: giao cho bạn một lá bài và trở thành người sử dụng lá bài này; hoặc trở thành mục tiêu bổ sung của lá bài này.",
	rechanhui: "Sấm Hủy",
	rechanhui_info: "Khi bạn sử dụng [Sát] hoặc Cẩm nang thông thường chỉ định mục tiêu duy nhất, bạn có thể khiến một nhân vật khác (không giới hạn khoảng cách) có thể trở thành mục tiêu của lá bài này chọn một: giao cho bạn một lá bài và trở thành người sử dụng lá bài này; hoặc trở thành mục tiêu bổ sung của lá bài này và bạn trong lượt này không thể phát động lại 〖Sấm Hủy〗.",
	jiaojin: "Kiêu Căng",
	jiaojin_info: "Khi bạn chịu sát thương do nhân vật nam gây ra, bạn có thể bỏ một lá bài trang bị, khiến sát thương này -1.",
	rejiaojin: "Kiêu Căng",
	rejiaojin_info: "Sau khi bạn trở thành mục tiêu của [Sát] hoặc Cẩm nang thông thường do nhân vật khác sử dụng, bạn có thể bỏ một lá bài trang bị, khiến lá bài này vô hiệu với bạn và nhận tất cả bài thực thể tương ứng của lá bài này. Nếu người sử dụng lá bài này là nhân vật nữ, bạn khiến 〖Kiêu Căng〗 vô hiệu cho đến khi kết thúc lượt.",
	shenxing: "Thận Hạnh",
	shenxing_info: "Giai đoạn ra bài, bạn có thể bỏ hai lá bài, sau đó rút một lá bài.",
	bingyi: "Bỉnh Nhất",
	bingyi_info: "Khi bắt đầu giai đoạn kết thúc, bạn có thể trưng ra tất cả bài trên tay, nếu những lá bài này đều cùng màu, bạn khiến tối đa X nhân vật mỗi người rút một lá bài (X là số bài trên tay của bạn).",
	qiangzhi: "Cường Thức",
	qiangzhi_draw: "Cường Thức",
	qiangzhi_info: "Khi bắt đầu giai đoạn ra bài, bạn có thể trưng ra một lá bài trên tay của một nhân vật khác. Nếu làm vậy, khi bạn sử dụng lá bài cùng loại với lá đó trong giai đoạn này, bạn có thể rút một lá bài.",
	xiantu: "Hiến Đồ",
	xiantu_info: "Khi bắt đầu giai đoạn ra bài của một nhân vật khác, bạn có thể rút hai lá bài, sau đó giao cho người đó hai lá bài. Nếu làm vậy, khi kết thúc giai đoạn này, nếu nhân vật đó chưa giết được nhân vật nào trong giai đoạn này, bạn mất 1 điểm thể lực.",
	dingpin: "Định Phẩm",
	dingpin_info: "Giai đoạn ra bài, bạn có thể bỏ một lá bài trên tay, sau đó khiến một nhân vật đã bị thương phán xét, nếu kết quả màu đen, nhân vật đó rút X lá bài (X là số thể lực đã mất của nhân vật đó), sau đó bạn trong lượt này không thể phát động lại 〖Định Phẩm〗 với người đó; nếu kết quả màu đỏ, bạn lật mặt (bạn không thể bỏ loại bài đã bỏ hoặc đã sử dụng trong lượt này).",
	faen: "Pháp Ân",
	faen_info: "Khi một nhân vật lật về mặt chính hoặc bị xích, bạn có thể khiến họ rút một lá bài.",
	jyzongshi: "Túng Thích",
	jyzongshi_info: "Khi bạn thắng so bài, bạn có thể nhận lấy lá bài so bài của đối phương; khi bạn không thắng so bài, bạn có thể thu hồi lá bài so bài của mình.",
	qiaoshui: "Xảo Thuyết",
	qiaoshui3: "Xảo Thuyết",
	qiaoshui_info: "Khi bắt đầu giai đoạn ra bài, bạn có thể cùng một nhân vật khác so bài. Nếu bạn thắng, khi bạn sử dụng lá bài Cơ bản hoặc Cẩm nang thông thường tiếp theo trong lượt này, có thể thêm hoặc bớt một mục tiêu cho lá bài đó; nếu bạn không thắng, bạn không thể sử dụng bài Cẩm nang cho đến khi kết thúc lượt.",
	reqiaoshui: "Xảo Thuyết",
	reqiaoshui_info: "Giai đoạn ra bài, bạn có thể cùng một nhân vật khác so bài. Nếu bạn thắng, khi bạn sử dụng lá bài Cơ bản hoặc Cẩm nang thông thường tiếp theo trong lượt này, có thể thêm hoặc bớt một mục tiêu cho lá bài đó; nếu bạn không thắng, bạn kết thúc giai đoạn ra bài và bài Cẩm nang trong lượt này không tính vào giới hạn bài trên tay.",
	junxing: "Tuấn Hình",
	junxing_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ ít nhất một lá bài trên tay và chọn một nhân vật khác, nhân vật đó cần bỏ một lá bài trên tay khác loại với tất cả các lá bạn đã bỏ, nếu không người đó phải lật mặt võ tướng bài trước rồi rút X lá bài (X là số lượng bài trên tay bạn đã bỏ theo cách này).",
	xinjunxing: "Tuấn Hình",
	xinjunxing_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ ít nhất một lá bài trên tay và chọn một nhân vật khác, nhân vật đó cần bỏ một lá bài trên tay khác loại với tất cả các lá bạn đã bỏ, nếu không người đó phải lật mặt võ tướng bài trước, sau đó rút bài cho đến khi có bốn lá.",

	xswuyan: "Vô Ngôn",
	xinwuyan: "Vô Ngôn",
	jujian: "Cử Tiến",
	xinjujian: "Cử Tiến",
	luoying: "Lạc Anh",
	luoying_discard: "Lạc Anh",
	luoying_judge: "Lạc Anh",
	luoying_judge_noconf: "Lạc Anh · Phán xét",
	jiushi: "Tửu Thi",
	jiushi1: "Tửu Thi",
	jiushi2: "Tửu Thi",
	jiushi3: "Tửu Thi",
	jueqing: "Tuyệt Tình",
	shangshi: "Thương Thệ",
	xuanfeng: "Toàn Phong",
	zhiyu: "Trí Ngu",
	qice: "Kỳ Sách",
	qice_backup: "Kỳ Sách",
	jiangchi: "Tướng Trì",
	jiangchi_less: "Rút ít đi một lá",
	jiangchi_more: "Rút thêm một lá",
	zishou: "Tự Thủ",
	zongshi: "Tông Thất",
	danshou: "Đạm Thủ",
	olddanshou: "Đạm Thủ",
	xindanshou: "Đạm Thủ",
	yizhong: "Nghị Trọng",
	xinzhan: "Tâm Chiến",
	xinzhan_gain: "Nhận lấy",
	xinzhan_place: "Đỉnh chồng bài",
	huilei: "Huy Lệ",
	enyuan: "Ân Oán",
	enyuan1: "Ân Oán",
	enyuan2: "Ân Oán",
	xuanhuo: "Huyễn Hoặc",
	ganlu: "Cam Lộ",
	buyi: "Bổ Ích",
	mingce: "Minh Sách",
	zhichi: "Trí Trì",
	zhichi2: "Trí Trì",
	pojun: "Phá Quân",
	jingce: "Tinh Sách",
	xinjingce: "Tinh Sách",
	chengxiang: "Xứng Tượng",
	oldchengxiang: "Xứng Tượng",
	renxin: "Nhân Tâm",
	oldrenxin: "Nhân Tâm",
	zhenlie: "Trinh Liệt",
	miji: "Bí Kế",
	miji_tag: "Đã phân phối",
	zhiyan: "Trực Ngôn",
	zongxuan: "Túng Huyền",
	anxu: "An Tuất",
	old_anxu: "An Tuất",
	zhuiyi: "Truy Ức",
	gongji: "Cung Kỵ",
	qiuyuan: "Cầu Viện",
	oldqiuyuan: "Cầu Viện",
	zhuikong: "Trụy Khủng",
	oldzhuikong: "Trụy Khủng",
	qieting: "Thiết Thính",
	xianzhou: "Hiến Châu",
	quanji: "Quyền Kế",
	zili: "Tự Lập",
	paiyi: "Bài Dị",
	paiyi_backup: "Bài Dị",
	sanyao: "Tán Dao",
	olsanyao: "Tán Dao",
	olsanyao_backup: "Tán Dao",
	zhiman: "Chế Man",
	resanyao: "Tán Dao",
	rezhiman: "Chế Man",
	qianxi: "Tiềm Tập",
	qianxi2: "Tiềm Tập",
	qianxi2_bg: "Tập",
	fuli: "Phục Lịch",
	xinfuli: "Phục Lịch",
	jiefan: "Giải Phiền",
	juece: "Tuyệt Sách",
	mieji: "Diệt Kế",
	fencheng: "Phần Thành",
	youdi: "Dụ Địch",
	youdi_info: "Khi bắt đầu giai đoạn kết thúc, bạn có thể khiến một nhân vật khác bỏ một lá bài của bạn, nếu lá bài này không phải là [Sát], bạn lấy một lá bài của nhân vật đó.",
	fencheng_info: "Kỹ năng giới hạn. Giai đoạn ra bài, bạn có thể khiến tất cả các nhân vật khác lần lượt chọn một: bỏ X lá bài; hoặc chịu 1 điểm sát thương lửa. (X là số bài trong khu trang bị của nhân vật đó và ít nhất là 1)",
	mieji_info: "Khi bạn sử dụng bài Cẩm nang thông thường màu đen chọn mục tiêu, nếu số mục tiêu là 1, bạn có thể chỉ định thêm một mục tiêu.",
	juece_info: "Khi nhân vật khác trong lượt của bạn mất lá bài trên tay cuối cùng, bạn có thể gây cho họ 1 điểm sát thương.",
	jiefan_info: "Kỹ năng giới hạn, giai đoạn ra bài, bạn có thể chọn một nhân vật, khiến tất cả nhân vật có phạm vi tấn công bao gồm nhân vật đó lần lượt chọn một: 1. Bỏ một lá bài Vũ khí; 2. Khiến họ rút một lá bài.",
	fuli_info: "Kỹ năng giới hạn, khi bạn trong trạng thái hấp hối, bạn có thể hồi phục thể lực bằng số phe phái trên sân, sau đó lật mặt.",
	xinfuli_info: "Kỹ năng giới hạn, khi bạn trong trạng thái hấp hối, có thể hồi phục thể lực đến X điểm và rút bài cho đến khi có X lá (X là số phe phái trên sân). Nếu X lớn hơn 2, bạn lật mặt.",
	qianxi_info: "Giai đoạn chuẩn bị, bạn có thể rút một lá bài, và bỏ một lá bài, sau đó khiến một nhân vật có khoảng cách bằng 1 không thể sử dụng hoặc đánh ra bài trên tay cùng màu với lá bạn đã bỏ cho đến khi kết thúc lượt.",
	zhiman_info: "Khi bạn gây sát thương cho một nhân vật khác, bạn có thể ngăn chặn sát thương này, sau đó lấy một lá bài trong khu trang bị hoặc khu phán xét của họ.",
	sanyao_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ một lá bài và chỉ định một nhân vật có trị số thể lực nhiều nhất (hoặc một trong số đó), bạn gây cho họ 1 điểm sát thương.",
	olsanyao_info: "Giai đoạn ra bài mỗi hạng mục giới hạn một lần, bạn có thể bỏ một lá bài và chỉ định một nhân vật có trị số thể lực hoặc số bài trên tay nhiều nhất (hoặc một trong số đó), và gây cho họ 1 điểm sát thương.",
	rezhiman_info: "Khi bạn gây sát thương cho một nhân vật khác, bạn có thể ngăn chặn sát thương này, sau đó lấy một lá bài trong khu vực của họ.",
	resanyao_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ số lượng bài tùy ý và chỉ định số lượng tương đương nhân vật khác ngoài bạn có trị số thể lực nhiều nhất (hoặc một trong số đó). Bạn lần lượt gây cho những nhân vật này 1 điểm sát thương.",
	paiyi_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể loại bỏ một lá \"Quyền\" và chọn một nhân vật, khiến họ rút hai lá bài, sau đó nếu số bài trên tay của họ nhiều hơn bạn, bạn gây cho họ 1 điểm sát thương.",
	zili_info: `Kỹ năng thức tỉnh, khi bắt đầu giai đoạn chuẩn bị, nếu số lượng \"Quyền\" không ít hơn 3, bạn giảm 1 điểm giới hạn thể lực, sau đó chọn một: 1. Hồi 1 điểm thể lực; 2. Rút hai lá bài. Sau đó bạn nhận được kỹ năng ${get.poptip("paiyi")}.`,
	quanji_info: "Sau khi bạn chịu 1 điểm sát thương, bạn có thể rút một lá bài, sau đó đặt một lá bài trên tay lên võ tướng bài, gọi là \"Quyền\"; giới hạn bài trên tay của bạn +X (X là số lượng \"Quyền\").",
	xianzhou_info: "Kỹ năng giới hạn. Giai đoạn ra bài, bạn có thể giao tất cả bài trong khu trang bị cho một nhân vật khác, sau đó nhân vật đó chọn một: khiến bạn hồi X điểm thể lực; hoặc đối với X nhân vật trong phạm vi tấn công của họ mỗi người gây 1 điểm sát thương (X là số lượng bài bạn giao cho nhân vật đó theo cách này).",
	qieting_info: "Khi kết thúc lượt của nhân vật khác, nếu người đó trong lượt này chưa từng sử dụng bài chỉ định nhân vật khác làm mục tiêu, bạn có thể chọn một: di chuyển một lá bài trong khu trang bị của họ sang vị trí tương ứng trong khu trang bị của bạn; hoặc rút một lá bài.",
	zhuikong_info: "Giai đoạn chuẩn bị của nhân vật khác, nếu bạn đã bị thương, bạn có thể cùng nhân vật đó so bài. Nếu bạn thắng, các lá bài nhân vật đó sử dụng trong lượt này không thể chỉ định nhân vật khác ngoài chính họ làm mục tiêu. Nếu bạn không thắng, khoảng cách của người đó đến bạn trong lượt này được xem là 1.",
	oldzhuikong_info: "Giai đoạn chuẩn bị của nhân vật khác, nếu bạn đã bị thương, bạn có thể cùng nhân vật đó so bài. Nếu bạn thắng, nhân vật đó bỏ qua giai đoạn ra bài của lượt này. Nếu bạn không thắng, khoảng cách của người đó đến bạn trong lượt này được xem là 1.",
	qiuyuan_info: "Khi bạn trở thành mục tiêu của [Sát], bạn có thể khiến một nhân vật khác chọn một: ① Giao cho bạn một lá [Thiểm]; ② Trở thành mục tiêu bổ sung của lá [Sát] này.",
	oldqiuyuan_info: "Khi bạn trở thành mục tiêu của [Sát], bạn có thể khiến một nhân vật khác có bài trên tay ngửa mặt giao cho bạn một lá bài. Nếu lá bài này không phải là [Thiểm], nhân vật đó cũng trở thành mục tiêu bổ sung của lá [Sát] này.",
	gongji_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ một lá bài, sau đó phạm vi tấn công của bạn được xem là vô hạn cho đến khi kết thúc lượt. Nếu lá bài bạn bỏ theo cách này là bài Trang bị, bạn có thể bỏ một lá bài của một nhân vật khác.",
	zhuiyi_info: "Khi bạn chết, bạn có thể khiến một nhân vật khác (trừ nhân vật giết bạn) rút ba lá bài, sau đó họ hồi 1 điểm thể lực.",
	anxu_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể chọn hai nhân vật khác có số bài trên tay khác nhau, khiến nhân vật có nhiều bài hơn giao một lá bài cho nhân vật có ít bài hơn, sau đó nếu số bài trên tay của hai nhân vật này bằng nhau, bạn rút một lá bài hoặc hồi 1 điểm thể lực.",
	old_anxu_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể chọn hai nhân vật khác có số bài trên tay khác nhau, khiến nhân vật có ít bài hơn lấy một lá bài của nhân vật có nhiều bài hơn và trưng ra. Sau đó nếu lá bài này không phải chất Bích, bạn rút một lá bài.",
	zongxuan_info: "Khi lá bài của bạn đi vào chồng bài bỏ do bị bỏ đi, bạn có thể đặt chúng lên đỉnh chồng bài theo thứ tự tùy ý.",
	zhiyan_info: "Giai đoạn kết thúc, bạn có thể khiến một nhân vật rút một lá bài và trưng ra, nếu là bài Trang bị, người đó sử dụng lá bài này và hồi 1 điểm thể lực.",
	miji_info: "Giai đoạn kết thúc, nếu bạn đã bị thương, có thể rút X lá bài, sau đó có thể giao số lượng bài tương đương cho nhân vật khác (X là số thể lực đã mất của bạn).",
	zhenlie_info: "Sau khi bạn trở thành mục tiêu của [Sát] hoặc Cẩm nang thông thường do nhân vật khác sử dụng, bạn có thể mất 1 điểm thể lực và khiến lá bài này vô hiệu với bạn, sau đó bỏ một lá bài của đối phương.",
	chengxiang_info: "Sau khi bạn chịu sát thương, bạn có thể lật ra bốn lá bài trên đỉnh chồng bài. Sau đó nhận lấy số lượng bài tùy ý trong số đó có tổng điểm không lớn hơn 13.",
	oldchengxiang_info: "Sau khi bạn chịu sát thương, bạn có thể lật ra bốn lá bài trên đỉnh chồng bài. Sau đó nhận lấy số lượng bài tùy ý trong số đó có tổng điểm không lớn hơn 12.",
	renxin_info: "Khi một nhân vật khác có trị số thể lực là 1 chịu sát thương, bạn có thể lật mặt võ tướng bài và bỏ một lá bài trang bị, sau đó ngăn chặn sát thương này.",
	renxin_info_guozhan: "Khi một nhân vật khác có trị số thể lực là 1 chịu sát thương, bạn có thể xếp chồng võ tướng bài và bỏ một lá bài trang bị, sau đó ngăn chặn sát thương này.",
	oldrenxin_info: "Khi nhân vật khác rơi vào trạng thái hấp hối, bạn có thể giao tất cả bài trên tay cho nhân vật đó và lật mặt, sau đó nhân vật đó hồi 1 điểm thể lực.",
	jingce_info: "Khi kết thúc giai đoạn ra bài, nếu số lượng bài bạn đã sử dụng trong lượt này lớn hơn hoặc bằng trị số thể lực hiện tại của bạn, bạn có thể rút hai lá bài.",
	xinjingce_info: "Giai đoạn kết thúc, nếu số lượng bài bạn đã sử dụng trong lượt này lớn hơn hoặc bằng trị số thể lực hiện tại của bạn, bạn có thể rút hai lá bài.",
	xswuyan_info: "Kỹ năng khóa, lá Cẩm nang thông thường bạn sử dụng vô hiệu với nhân vật khác; lá Cẩm nang thông thường nhân vật khác sử dụng vô hiệu với bạn.",
	xinwuyan_info: "Kỹ năng khóa, khi bạn sử dụng bài Cẩm nang gây sát thương, bạn ngăn chặn sát thương này; kỹ năng khóa, khi bạn chịu sát thương do bài Cẩm nang gây ra cho bạn, bạn ngăn chặn sát thương này.",
	jujian_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ tối đa ba lá bài, sau đó khiến một nhân vật khác rút số lượng bài tương đương. Nếu bạn bỏ không ít hơn ba lá theo cách này và đều cùng một loại, bạn hồi 1 điểm thể lực.",
	xinjujian_info: "Khi bắt đầu giai đoạn kết thúc, bạn có thể bỏ một lá không phải Cơ bản và chọn một nhân vật khác, khiến họ chọn một: 1. Rút hai lá bài; 2. Hồi 1 điểm thể lực; 3. Lật mặt võ tướng bài về mặt chính và đặt lại (trọng trí) nó.",
	luoying_info: "Khi lá bài chất Chuồn của nhân vật khác đi vào chồng bài bỏ do bị bỏ đi hoặc phán xét, bạn có thể nhận lấy nó.",
	jiushi_info: "Khi bạn cần sử dụng một lá [Tửu], nếu võ tướng bài của bạn đang mặt chính, bạn có thể lật mặt võ tướng bài và xem như đã sử dụng một lá [Tửu]; sau khi bạn chịu sát thương, nếu võ tướng bài của bạn đang mặt sau khi chịu sát thương, bạn có thể lật lại mặt chính.",
	jueqing_info: "Kỹ năng khóa, sát thương bạn sắp gây ra đều được xem là mất thể lực.",
	shangshi_info: "Khi số bài trên tay của bạn ít hơn X, bạn có thể rút bài cho đến khi có X lá (X là số thể lực đã mất của bạn).",
	xuanfeng_info: "Khi bạn mất bài trong khu trang bị, hoặc sau khi đã bỏ từ hai lá bài trở lên trong giai đoạn bỏ bài, bạn có thể lần lượt bỏ tổng cộng hai lá bài của một đến hai nhân vật khác.",
	zhiyu_info: "Sau khi bạn chịu sát thương, bạn có thể rút một lá bài, sau đó trưng ra tất cả bài trên tay. Nếu màu sắc đều giống nhau, bạn khiến nguồn sát thương bỏ một lá bài trên tay.",
	qice_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể dùng tất cả bài trên tay (ít nhất một lá) làm bất kỳ một lá Cẩm nang thông thường nào để sử dụng.",
	jiangchi_info: "Khi rút bài ở giai đoạn rút bài, bạn có thể chọn một: 1. Rút thêm một lá bài, nếu làm vậy, bạn không thể sử dụng hoặc đánh ra [Sát] cho đến khi kết thúc lượt. 2. Rút ít đi một lá bài, nếu làm vậy, bạn sử dụng [Sát] không giới hạn khoảng cách và có thể sử dụng thêm một lá [Sát] cho đến khi kết thúc lượt.",
	zishou_info: "Giai đoạn rút bài, bạn có thể rút thêm X lá bài (X là số phe phái trên sân). Sau đó những lá bài bạn sử dụng trong giai đoạn ra bài của lượt này không thể chỉ định nhân vật khác làm mục tiêu.",
	zongshi_info: "Kỹ năng khóa, giới hạn bài trên tay của bạn +X (X là số phe phái hiện có trên sân).",
	danshou_info: "Giai đoạn ra bài, bạn có thể chọn một nhân vật khác trong phạm vi tấn công của mình, sau đó bỏ X lá bài (X là số lần bạn đã phát động \"Đạm Thủ\" trước đó trong giai đoạn này + 1). Nếu X: là 1, bạn bỏ một lá bài của nhân vật đó; là 2, khiến nhân vật đó giao cho bạn một lá bài; là 3, bạn gây cho nhân vật đó 1 điểm sát thương; không ít hơn 4, bạn và nhân vật đó mỗi người rút hai lá bài.",
	olddanshou_info: "Sau khi bạn gây sát thương, bạn có thể rút một lá bài. Nếu làm vậy, chấm dứt tất cả quyết toán, lượt hiện tại kết thúc.",
	xindanshou_info: "① Mỗi lượt giới hạn một lần, sau khi bạn trở thành mục tiêu của bài Cơ bản hoặc Cẩm nang, bạn có thể rút X lá bài (X là số lần bạn đã trở thành mục tiêu của bài Cơ bản hoặc Cẩm nang trong lượt này). ② Giai đoạn kết thúc của một nhân vật khác, nếu bạn trong lượt này chưa từng phát động 〖Đạm Thủ ①〗, bạn có thể bỏ X lá bài và gây cho họ 1 điểm sát thương (X là số bài trên tay của họ, không có bài thì không bỏ).",
	yizhong_info: "Kỹ năng khóa, khi ô phòng cụ của bạn trống, lá [Sát] màu đen vô hiệu với bạn.",
	xinzhan_info: "Giai đoạn ra bài giới hạn một lần, nếu số bài trên tay của bạn nhiều hơn giới hạn thể lực của mình, bạn có thể xem ba lá bài trên đỉnh chồng bài, sau đó trưng ra bất kỳ lá bài chất Cơ nào trong đó và nhận lấy.",
	huilei_info: "Kỹ năng khóa, khi bạn chết, nhân vật giết bạn bỏ tất cả các lá bài.",
	enyuan_info: "Kỹ năng khóa. ① Sau khi nhân vật khác khiến bạn hồi 1 điểm thể lực, nhân vật đó rút một lá bài. ② Sau khi nhân vật khác gây sát thương cho bạn, họ phải giao cho bạn một lá bài trên tay chất ♥, nếu không thì mất 1 điểm thể lực.",
	xuanhuo_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể giao một lá bài trên tay chất Cơ cho một nhân vật khác, lấy một lá bài của nhân vật đó, sau đó giao cho một nhân vật khác ngoài người đó.",
	ganlu_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể chọn hai nhân vật có hiệu số lượng trang bị trong khu trang bị không lớn hơn X, khiến họ trao đổi bài trong khu trang bị (X là số thể lực đã mất của bạn).",
	buyi_info: "Khi có nhân vật rơi vào trạng thái hấp hối, bạn có thể trưng ra một lá bài trên tay của nhân vật đó: nếu lá bài này không phải là bài Cơ bản, nhân vật đó bỏ lá bài này và hồi 1 điểm thể lực.",
	mingce_info: "Giai đoạn ra bài, bạn có thể giao cho một nhân vật khác một lá bài Trang bị hoặc [Sát], sau đó khiến nhân vật đó chọn một: 1. Xem như đối với một nhân vật khác do bạn chỉ định nằm trong phạm vi tấn công của họ sử dụng một lá [Sát]. 2. Rút một lá bài. Mỗi lượt giới hạn một lần.",
	zhichi_info: "Kỹ năng khóa, sau khi bạn chịu sát thương ngoài lượt của mình, tất cả [Sát] hoặc Cẩm nang thông thường vô hiệu với bạn cho đến khi kết thúc lượt.",
	pojun_info: "Sau khi bạn sử dụng [Sát] gây sát thương, bạn có thể khiến nhân vật chịu sát thương rút X lá bài, sau đó lật mặt (X là trị số thể lực của nhân vật đó và tối đa là 5).",
	shiyong: "Thị Dũng",
	shiyong_info: "Kỹ năng khóa, sau khi bạn chịu một lần sát thương do [Sát] màu đỏ hoặc [Tửu] [Sát] gây ra, phải giảm 1 điểm giới hạn thể lực.",
	old_guanzhang: "Cựu Quan Hưng Trương Bào",
	old_guanzhang_prefix: "Cựu",
	wangyi: "Vương Dị",
	oldqianxi: "Tiềm Tập",
	oldqianxi_info: "Khi bạn sử dụng [Sát] gây sát thương cho nhân vật mục tiêu có khoảng cách là 1, bạn có thể tiến hành một lần phán xét, nếu kết quả phán xét không phải là chất Cơ, bạn ngăn chặn sát thương này, khiến họ giảm 1 điểm giới hạn thể lực.",
	oldzhenlie: "Trinh Liệt",
	oldzhenlie_info: "Trước khi lá bài phán xét của bạn có hiệu lực, bạn có thể lật ra một lá bài trên đỉnh chồng bài để thay thế nó.",
	oldmiji: "Bí Kế",
	oldmiji_info: "Khi bắt đầu giai đoạn chuẩn bị/kết thúc, nếu bạn đã bị thương, bạn có thể phán xét, nếu kết quả phán xét màu đen, bạn xem X lá bài trên đỉnh chồng bài (X là số thể lực đã mất của bạn), sau đó giao những lá bài này cho một nhân vật.",
	old_fuhun: "Phụ Hồn",
	old_fuhun_info: `Khi bắt đầu giai đoạn rút bài, bạn có thể bỏ qua rút bài, đổi thành từ đỉnh chồng bài lật ra hai lá bài và nhận lấy, nếu màu sắc của các lá bài lật ra khác nhau, bạn nhận được ${get.poptip("wusheng")} và ${get.poptip("paoxiao")} cho đến khi kết thúc lượt.`,
	rejueqing: "Tuyệt Tình",
	rejueqing_info: "Khi bạn sắp gây sát thương không phải lan truyền cho nhân vật khác, bạn có thể mất số lượng thể lực tương đương, khiến sát thương này gấp đôi. Nếu làm vậy, sau khi kết thúc quyết toán sát thương này, bạn sửa đổi 〖Tuyệt Tình〗.",
	rejueqing_1st: "Tuyệt Tình",
	rejueqing_rewrite: "Tuyệt Tình · Cải",
	rejueqing_rewrite_info: "Kỹ năng khóa, sát thương bạn sắp gây ra đều được xem là mất thể lực.",
	reshangshi: "Thương Thệ",
	reshangshi_2nd: "Thương Thệ",
	reshangshi_info: "Khi bạn chịu sát thương, bạn có thể bỏ một lá bài. Khi số bài trên tay của bạn ít hơn X, bạn có thể rút bài cho đến khi có X lá. (X là số thể lực đã mất của bạn)",
	rejingce: "Tinh Sách",
	rejingce2: "Tinh Sách",
	rejingce_add: "Tinh Sách",
	rejingce_info: "Khi bạn lần đầu tiên trong lượt sử dụng bài trên tay của một loại chất nào đó, giới hạn bài trên tay của bạn +1. Khi kết thúc giai đoạn ra bài, bạn có thể rút X lá bài (X là số loại bài bạn đã sử dụng trong giai đoạn này).",
	xinkuangbi: "Khuông Bật",
	xinkuangbi_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể khiến một nhân vật khác giao cho bạn tối đa ba lá bài (không tính vào giới hạn bài trên tay lượt này của bạn). Sau đó họ sẽ rút số lượng bài tương đương khi bắt đầu lượt tiếp theo của họ.",
	xinzhaofu: "Chiếu Phược",
	xinzhaofu_info: "Kỹ năng Chủ công, kỹ năng giới hạn. Giai đoạn ra bài, bạn có thể chọn tối đa hai nhân vật khác. Hai nhân vật này được xem là nằm trong phạm vi tấn công của tất cả các nhân vật phe Ngô khác.",
	olbingyi: "Bỉnh Nhất",
	olbingyi_info: "Mỗi giai đoạn giới hạn một lần. Khi bạn mất bài do bị bỏ đi, bạn có thể trưng ra tất cả bài trên tay. Nếu những lá bài này đều cùng màu, bạn có thể cùng tối đa X nhân vật khác mỗi người rút một lá bài (X là số bài trên tay của bạn).",
	olbenxi: "Bôn Tập",
	olbenxi_info: "Kỹ năng khóa. ① Khi bạn sử dụng bài trong lượt, khoảng cách bạn tính đến các nhân vật khác lượt này -1. ② Khi bạn sử dụng [Sát] hoặc Cẩm nang thông thường chỉ định mục tiêu duy nhất trong lượt, nếu khoảng cách của bạn đến tất cả các nhân vật khác trên sân đều không lớn hơn 1, bạn chọn tối đa hai hạng mục: 1. Chỉ định thêm một mục tiêu cho lá bài này; 2. Khiến lá bài này bỏ qua phòng cụ; 3. Khiến lá bài này không thể bị triệt tiêu; 4. Sau khi lá bài này gây sát thương, bạn rút một lá bài.",
};

export default translates;
