import { lib, game, ui, get, ai, _status } from "noname";

const translates = {
	sb_zhanghe_prefix: "Mưu",
	sb_yujin_prefix: "Mưu",
	sb_huaxiong_prefix: "Mưu",
	liucheng_prefix: "Mưu",
	sp_yangwan_prefix: "Mưu",
	sb_huangzhong_prefix: "Mưu",
	sb_lvmeng_prefix: "Mưu",
	sb_sunshangxiang_prefix: "Mưu",
	sb_sunquan_prefix: "Mưu",
	sb_huanggai_prefix: "Mưu",
	sb_zhouyu_prefix: "Mưu",
	sb_caoren_prefix: "Mưu",
	sb_xiahoushi_prefix: "Mưu",
	sb_zhangjiao_prefix: "Mưu",
	sb_caocao_prefix: "Mưu",
	sb_zhenji_prefix: "Mưu",
	sb_ganning_prefix: "Mưu",
	sb_machao_prefix: "Mưu",
	sb_xuhuang_prefix: "Mưu",
	sb_zhangfei_prefix: "Mưu",
	sb_zhaoyun_prefix: "Mưu",
	sb_liubei_prefix: "Mưu",
	sb_jiangwei_prefix: "Mưu",
	sb_fazheng_prefix: "Mưu",
	sb_chengong_prefix: "Mưu",
	sb_diaochan_prefix: "Mưu",
	sb_yuanshao_prefix: "Mưu",
	sb_pangtong_prefix: "Mưu",
	sb_sunce_prefix: "Mưu",
	sb_daqiao_prefix: "Mưu",
	sb_liubiao_prefix: "Mưu",
	sb_zhurong_prefix: "Mưu",
	sb_menghuo_prefix: "Mưu",
	sb_luxun_prefix: "Mưu",
	sp_yangwan: "Mưu Dương Uyển",
	spmingxuan: "Minh Huyền",
	spmingxuan_info: "Kỹ năng khóa. Khi bắt đầu giai đoạn ra bài, bạn phải chọn tối đa X lá bài tay có hoa sắc khác nhau (X là số lượng nhân vật khác chưa được kỹ năng này ghi nhớ), đem những lá bài này ngẫu nhiên giao cho số lượng nhân vật tương ứng trong đó. Sau đó những nhân vật này lần lượt chọn một mục: 1. Đối với bạn sử dụng một lá 【Sát】, sau đó bạn ghi nhớ người đó; 2. Giao cho bạn một lá bài, sau đó bạn rút một lá bài. Nếu những nhân vật này đều chọn cùng một mục, bạn có thể khiến một nhân vật chưa bị ghi nhớ xem như sử dụng một lá 【Sát】.",
	spxianchou: "Hãm Thù",
	spxianchou_info: "Khi bạn chịu sát thương do nhân vật khác gây ra, bạn có thể chọn một nhân vật khác không phải nguồn gây sát thương. Nhân vật đó có thể bỏ một lá bài, xem như đối với nguồn gây sát thương sử dụng một lá 【Sát】 (không hạn chế khoảng cách). Nếu vì lá 【Sát】 này mà gây ra sát thương, người đó rút một lá bài, bạn hồi 1 điểm thể lực.",
	new_spxianchou: "Hãm Thù",
	new_spxianchou_info: "Khi bạn chịu sát thương do nhân vật khác gây ra, bạn có thể chọn một nhân vật khác không phải nguồn gây sát thương. Nhân vật đó có thể xem như đối với nguồn gây sát thương sử dụng một lá 【Sát】 (không hạn chế khoảng cách). Nếu vì lá 【Sát】 này mà gây ra sát thương, thì bạn hồi 1 điểm thể lực, người đó rút một lá bài.",
	liucheng: "Mưu Lưu Sênh",
	splveying: "Lược Ảnh",
	splveying_info: "Kỹ năng khóa. ①Giai đoạn ra bài giới hạn hai lần, sau khi bạn sử dụng 【Sát】 chỉ định mục tiêu, bạn nhận được một “Trùy”. ②Sau khi lá 【Sát】 bạn sử dụng kết thúc kết toán, nếu số “Trùy” của bạn lớn hơn 1, thì bạn bỏ hai “Trùy” và rút một lá bài, sau đó có thể xem như sử dụng một lá 【Quá Hà Tháp Kiều】.",
	spyingwu: "Oanh Vũ",
	spyingwu_info: "Nếu bạn sở hữu 〖Lược Ảnh〗, thì: ①Giai đoạn ra bài giới hạn hai lần, sau khi bạn sử dụng lá Cẩm nang thường không gây sát thương chỉ định mục tiêu, bạn nhận được một “Trùy”. ②Sau khi lá Cẩm nang thường không gây sát thương bạn sử dụng kết thúc kết toán, nếu số “Trùy” của bạn lớn hơn 1, thì bạn bỏ hai “Trùy” và rút một lá bài, sau đó có thể xem như sử dụng một lá 【Sát】.",
	sb_huangzhong: "Mưu Hoàng Trung",
	sbliegong: "Liệt Cung",
	sbliegong_info: "①Nếu trong vùng trang bị của bạn không có bài vũ khí, thì tất cả 【Sát】 trong vùng bài tay của bạn được coi là vô thuộc tính. ②Khi bạn sử dụng bài, hoặc trở thành mục tiêu sử dụng bài của nhân vật khác, bạn ghi nhớ hoa sắc của lá bài này. ③Khi bạn sử dụng 【Sát】 chỉ định mục tiêu duy nhất, nếu ghi nhớ của 〖Liệt Cung②〗 không trống, thì bạn có thể lật ra X lá bài trên cùng của chồng bài (X là số lượng hoa sắc đã ghi nhớ của 〖Liệt Cung②〗 trừ 1), khiến trị số sát thương cơ bản của lá 【Sát】 này +Y (Y là số lượng bài trong số bài lật ra có hoa sắc đã được 〖Liệt Cung②〗 ghi nhớ), và nhân vật mục tiêu không thể sử dụng bài có hoa sắc đã được 〖Liệt Cung②〗 ghi nhớ để phản hồi lá 【Sát】 này. Sau khi sử dụng 【Sát】 này kết thúc kết toán, bạn xóa ghi nhớ của 〖Liệt Cung②〗.",
	sb_huaxiong: "Mưu Hoa Hùng",
	sbyangwei: "Dương Uy",
	sbyangwei_info: "Giai đoạn ra bài, bạn có thể rút hai lá bài, khiến kỹ năng này mất hiệu lực trước giai đoạn kết thúc kế tiếp của bạn, và bạn nhận được hiệu ứng sau cho đến khi kết thúc lượt: Sử dụng 【Sát】 không hạn chế khoảng cách, giới hạn số lần +1 và bỏ qua phòng cụ.",
	sb_yujin: "Mưu Vu Cấm",
	sbxiayuan: "Hiệp Viện",
	sbxiayuan_info: "Mỗi vòng giới hạn một lần. Sau khi nhân vật khác chịu sát thương, nếu vì sát thương này mà kích hoạt hiệu ứng hộ giáp và người đó không còn hộ giáp, thì bạn có thể bỏ hai lá bài tay, khiến người đó nhận được X điểm hộ giáp (X là số lượng hộ giáp người đó đã mất vì kích hoạt hiệu ứng hộ giáp do sát thương này).",
	sbjieyue: "Tiết Việt",
	sbjieyue_info: "Giai đoạn kết thúc, bạn có thể khiến một nhân vật khác nhận được 1 điểm hộ giáp. Sau đó người đó có thể giao cho bạn một lá bài.",
	sb_lvmeng: "Mưu Lã Mông",
	sbkeji: "Khắc Kỷ",
	sbkeji_info: "①Giai đoạn ra bài mỗi mục giới hạn một lần. Bạn có thể chọn một mục: 1. Bỏ một lá bài tay, sau đó nhận 1 điểm hộ giáp; 2. Mất 1 điểm thể lực, sau đó nhận 2 điểm hộ giáp. ②Giới hạn bài tay của bạn +X (X là số hộ giáp của bạn). ③Nếu bạn không phải là nhân vật đang trong tiến trình kết toán hấp hối, bạn không thể sử dụng 【Đào】.",
	sbdujiang: "Độ Giang",
	sbdujiang_info: `Kỹ năng thức tỉnh. Giai đoạn chuẩn bị, nếu số hộ giáp của bạn không ít hơn 3, bạn nhận được ${get.poptip("sbduojing")}, sửa đổi 〖Khắc Kỷ①〗 thành “Giai đoạn ra bài giới hạn một lần”.`,
	sbduojing: "Đoạt Kinh",
	sbduojing_info: "Khi bạn sử dụng 【Sát】 chỉ định mục tiêu, bạn có thể mất 1 điểm hộ giáp. Sau đó khiến 【Sát】 này bỏ qua phòng cụ, bạn nhận một lá bài tay của nhân vật mục tiêu, lượt này giới hạn số lần sử dụng 【Sát】 +1.",
	sb_sunshangxiang: "Mưu Tôn Thượng Hương",
	sbjieyin: "Kết Nhân",
	sbjieyin_info: "Kỹ năng sứ mệnh, thế lực xuất hiện của bạn là Thục. ①Khi trò chơi bắt đầu, bạn khiến một nhân vật khác nhận được 1 dấu ấn “Trợ”. ②Khi bắt đầu giai đoạn ra bài, nhân vật có “Trợ” chọn một mục: 1. Giao cho bạn X lá bài tay (X=min(2, số bài tay của người đó) và ít nhất là 1), sau đó nhận được 1 điểm hộ giáp; 2. Khiến bạn di chuyển “Trợ” cho một nhân vật khác, hoặc loại bỏ “Trợ” của người đó (nếu trước đó người đó từng nhận được “Trợ”, thì chỉ có thể loại bỏ). ③Thất bại: Sau khi một nhân vật tử vong, nếu lúc tử vong người đó có “Trợ”, hoặc khi bạn vì 〖Kết Nhân②〗 mà loại bỏ “Trợ”, bạn đổi thế lực thành Ngô, hồi 1 điểm thể lực, nhận được tất cả “Trang” và giảm 1 điểm giới hạn thể lực.",
	sbliangzhu: "Lương Trợ",
	sbliangzhu_info: "Kỹ năng thế lực Thục. Giai đoạn ra bài giới hạn một lần, bạn có thể đặt một lá bài trong vùng trang bị của nhân vật khác lên thẻ võ tướng, gọi là “Trang”, sau đó nhân vật có “Trợ” phải chọn hồi 1 điểm thể lực hoặc rút hai lá bài.",
	sbxiaoji: "Kiêu Cơ",
	sbxiaoji_info: "Kỹ năng thế lực Ngô. Sau khi bạn mất một lá bài trong vùng trang bị, bạn rút hai lá bài, sau đó có thể bỏ một lá bài trên sân.",
	sb_sunquan: "Mưu Tôn Quyền",
	sbzhiheng: "Chế Hành",
	sbzhiheng_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể bỏ bất kỳ số lượng bài nào và rút số lượng bài tương đương, mỗi khi bạn bỏ toàn bộ bài của một vùng theo cách này, rút thêm một lá bài.",
	sbtongye: "Thống Nghiệp",
	sbtongye_info: "Kỹ năng khóa, khi kết thúc lượt, nếu mỗi vùng của bạn đều có nhân vật khác có số lượng bài bằng với số lượng bài vùng đó của bạn, bạn từ chồng bài hoặc chồng bài bỏ nhận được một lá bài có tên bài chưa từng nhận được theo cách này.",
	sbjiuyuan: "Cứu Viện",
	sbjiuyuan_info: "Kỹ năng chủ công, kỹ năng khóa. ①Khi nhân vật thế lực Ngô khác sử dụng 【Đào】, bạn rút một lá bài. ②Lượng hồi phục của 【Đào】 do nhân vật thế lực Ngô khác sử dụng cho bạn +1.",
	sb_huanggai: "Mưu Hoàng Cái",
	sbkurou: "Khổ Nhục",
	sbkurou_info: "①Khi bắt đầu giai đoạn ra bài, bạn có thể giao cho nhân vật khác một lá bài, nếu lá bài này trong vùng bài tay của đối phương là 【Đào】 hoặc 【Tửu】, bạn mất 2 điểm thể lực, nếu không bạn mất 1 điểm thể lực. ②Sau khi bạn mất 1 điểm thể lực, bạn nhận được 2 điểm hộ giáp.",
	sbzhaxiang: "Trá Hàng",
	sbzhaxiang_info: "Kỹ năng khóa. ①Giai đoạn rút bài, bạn rút thêm X lá bài. ②X lá bài đầu tiên bạn sử dụng trong lượt không hạn chế khoảng cách và số lần và không thể bị phản hồi (X là số điểm thể lực bạn đã mất).",
	sb_zhouyu: "Mưu Chu Du",
	sbyingzi: "Anh Tư",
	sbyingzi_info: "Kỹ năng khóa. Giai đoạn rút bài, bạn rút thêm X lá bài, và khiến giới hạn bài tay lượt này của bạn +X (X là số lượng mục bạn thỏa mãn trong các điều kiện sau: số bài tay không ít hơn 2, trị số thể lực không ít hơn 2, số bài trong vùng trang bị không ít hơn 1).",
	sbfanjian: "Phản Gián",
	sbfanjian_info: "Giai đoạn ra bài, bạn có thể tuyên bố một hoa sắc và chọn một lá bài cùng một nhân vật khác (mỗi loại hoa sắc mỗi lượt giới hạn một lần). Người đó phải chọn một mục: 1. Dự đoán hoa sắc lá bài này có giống với hoa sắc bạn tuyên bố hay không; 2. Lật mặt. Sau đó người đó ngửa mặt nhận lấy lá bài này. Nếu người đó chọn dự đoán và dự đoán sai, người đó mất 1 điểm thể lực, nếu không người đó khiến 〖Phản Gián〗 mất hiệu lực trong lượt này.",
	sb_caoren: "Mưu Tào Nhân",
	sbjushou: "Cứ thủ",
	sbjushou_info: "①Giai đoạn ra bài giới hạn một lần. Nếu thẻ võ tướng của bạn đang mặt ngửa, bạn có thể bỏ tối đa hai lá bài, sau đó bạn lật mặt và nhận số lượng hộ giáp tương đương. ②Sau khi bạn chịu sát thương, nếu thẻ võ tướng của bạn đang mặt úp, bạn chọn một mục: 1. Lật mặt; 2. Nhận 1 điểm hộ giáp. ③Sau khi bạn lật mặt, nếu thẻ võ tướng của bạn đang mặt ngửa, bạn rút X lá bài (X là số hộ giáp của bạn).",
	sbjiewei: "Giải Vi",
	sbjiewei_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể mất 1 điểm hộ giáp và chọn một nhân vật khác. Bạn xem bài tay của người đó và lấy đi một lá.",
	sb_xiahoushi: "Mưu Hạ Hầu Thị",
	sbqiaoshi: "Tiều Thập",
	sbqiaoshi_info: "Mỗi lượt giới hạn một lần. Khi bạn chịu sát thương do nhân vật khác gây ra, người đó có thể khiến bạn hồi thể lực bằng với trị số sát thương lần này, sau đó người đó rút hai lá bài.",
	sbyanyu: "Yến Ngữ",
	sbyanyu_info: "①Giai đoạn ra bài giới hạn hai lần. Bạn có thể bỏ một lá 【Sát】, sau đó rút một lá bài. ②Khi kết thúc giai đoạn ra bài, bạn có thể khiến một nhân vật khác rút 3X lá bài (X là số lần bạn phát động 〖Yến Ngữ①〗 trong giai đoạn này).",
	sb_zhangjiao: "Mưu Trương Giác",
	sbleiji: "Lôi Kích",
	sbleiji_info: "Giai đoạn ra bài, bạn có thể chọn một nhân vật khác và bỏ 4 dấu ấn “Đạo Binh”, gây cho người đó 1 điểm sát thương sấm sét.",
	sbguidao: "Quỷ Đạo",
	sbguidao_info: "①Khi trò chơi bắt đầu/sau khi một nhân vật chịu sát thương thuộc tính, bạn nhận được 6/2 dấu ấn “Đạo Binh” (giới hạn dấu ấn là 8). ②Khi bạn chịu sát thương, bạn có thể bỏ 2 dấu ấn “Đạo Binh” và ngăn chặn sát thương này. Sau đó nếu nhân vật lượt hiện tại không phải bạn, 〖Quỷ Đạo①〗 vô hiệu cho đến trước khi lượt sau của bạn bắt đầu.",
	sbhuangtian: "Hoàng Thiên",
	sbhuangtian_info: "Kỹ năng chủ công, kỹ năng khóa. ①Khi bắt đầu lượt, nếu lượt này là lượt đầu tiên của bạn và số vòng trò chơi là 1, đồng thời trong trò chơi không có 【Thái Bình Yếu Thuật】, bạn trang bị 【Thái Bình Yếu Thuật】. ②Sau khi nhân vật thế lực Quần khác gây sát thương, nếu bạn sở hữu 〖Quỷ Đạo〗, bạn nhận được 2 dấu ấn “Đạo Binh” (mỗi vòng bạn tối đa nhận được 4 dấu ấn “Đạo Binh” theo cách này).",
	sb_caocao: "Mưu Tào Tháo",
	sbjianxiong: "Gian Hùng",
	sbjianxiong_info: "①Khi trò chơi bắt đầu, bạn có thể nhận tối đa 2 dấu ấn “Trị Thế”. ②Sau khi bạn chịu sát thương, bạn có thể nhận lá bài gây sát thương, rút 3-X lá bài (X là số lượng “Trị Thế”), sau đó bạn có thể bỏ 1 dấu ấn “Trị Thế”.",
	sbqingzheng: "Thanh Chính",
	sbqingzheng_info: "Khi bắt đầu giai đoạn ra bài, bạn có thể bỏ toàn bộ bài tay của 3-X loại hoa sắc (X là số lượng “Trị Thế”), và xem bài tay của một nhân vật khác có bài tay, bạn bỏ toàn bộ bài của một loại hoa sắc trong đó. Nếu số bài bị bỏ của người đó nhỏ hơn số bài bạn bỏ theo cách này, bạn gây cho người đó 1 điểm sát thương. Sau đó nếu X nhỏ hơn 2 và bạn sở hữu kỹ năng 〖Gian Hùng〗, bạn có thể nhận được 1 dấu ấn “Trị Thế”.",
	sbhujia: "Hộ Giá",
	sbhujia_info: "Kỹ năng chủ công, mỗi vòng giới hạn một lần. Khi bạn chịu sát thương, bạn có thể chuyển dịch sát thương này cho một nhân vật thế lực Ngụy khác.",
	sb_zhenji: "Mưu Chân Mật",
	sbluoshen: "Lạc Thần",
	sbluoshen_info: "Giai đoạn chuẩn bị, bạn có thể chọn một nhân vật. Bắt đầu từ người đó theo chiều ngược kim đồng hồ, X nhân vật khác lần lượt thực hiện (X là một nửa số lượng nhân vật, làm tròn lên): Trưng bày một lá bài tay, nếu lá bài này màu đen, bạn nhận lấy nó và lá bài này không tính vào giới hạn bài tay lượt này; nếu lá bài này màu đỏ, người đó bỏ nó đi.",
	sb_ganning: "Mưu Cam Ninh",
	sbqixi: "Kỳ Kích",
	sbqixi_info: "Giai đoạn ra bài giới hạn một lần. Nếu bạn có bài tay, bạn có thể khiến một nhân vật khác dự đoán hoa sắc có nhiều nhất trong bài tay của bạn. Nếu người đó đoán đúng, bạn trưng bày toàn bộ bài tay; nếu người đó đoán sai, bạn có thể khiến người đó từ các hoa sắc chưa chọn dự đoán lại, lặp lại tiến trình này. Sau đó bạn bỏ X lá bài trong vùng của người đó (X là số lần người đó đoán sai trong lần 〖Kỳ Kích〗 này).",
	sbfenwei: "Phấn Uy",
	sbfenwei_info: "Kỹ năng giới hạn. ①Giai đoạn ra bài, bạn có thể đem tối đa ba lá bài lần lượt đặt lên thẻ võ tướng của số lượng nhân vật tương ứng, gọi là “Uy”, sau đó bạn rút số lượng bài tương đương. ②Khi một nhân vật trở thành mục tiêu của lá Cẩm nang, nếu người đó có “Uy”, bạn phải chọn: 1. Khiến người đó nhận lấy “Uy” của mình; 2. Khiến người đó loại bỏ “Uy”, và hủy bỏ mục tiêu này.",
	sb_machao: "Mưu Mã Siêu",
	sbtieji: "Thiết Kỵ",
	sbtieji_info: "Sau khi bạn sử dụng 【Sát】 chỉ định nhân vật khác làm mục tiêu, bạn có thể khiến nhân vật mục tiêu không thể phản hồi lá 【Sát】 này, và tất cả kỹ năng phi khóa của người đó mất hiệu lực cho đến khi kết thúc lượt. Sau đó bạn cùng người đó tiến hành mưu dịch. Nếu bạn thắng, và mục bạn chọn là: “Trực thủ địch doanh”, thì bạn nhận một lá bài của người đó; “Nhiễu trận bì địch”, bạn rút hai lá bài.",
	sb_xuhuang: "Mưu Từ Hoảng",
	sbduanliang: "Đoạn Lương",
	sbduanliang_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể cùng một nhân vật khác tiến hành mưu dịch. Nếu bạn thắng, và mục bạn chọn là: “Vi thành đoạn lương”, nếu vùng phán xét của người đó không có 【Binh Lương Thốn Đoạn】, bạn đem lá trên cùng của chồng bài xem như 【Binh Lương Thốn Đoạn】 sử dụng cho người đó, nếu không bạn nhận một lá bài của người đó; “Lôi cổ tiến quân”, bạn xem như đối với người đó sử dụng một lá 【Quyết Đấu】.",
	sbshipo: "Thế Bách",
	sbshipo_info: "Giai đoạn kết thúc, bạn có thể khiến một nhân vật có thể lực ít hơn bạn hoặc tất cả nhân vật khác có 【Binh Lương Thốn Đoạn】 trong vùng phán xét chọn một mục: 1. Giao cho bạn một lá bài tay; 2. Chịu 1 điểm sát thương. Sau khi tất cả nhân vật mục tiêu chọn xong, bạn có thể giao bất kỳ số lượng bài nào bạn nhận được theo cách này cho một nhân vật khác.",
	sb_zhangfei: "Mưu Trương Phi",
	sbpaoxiao: "Bào Tiêu",
	sbpaoxiao_info: "Kỹ năng khóa. ①Bạn sử dụng 【Sát】 không hạn chế số lần. ②Nếu trong vùng trang bị của bạn có bài vũ khí, thì bạn sử dụng 【Sát】 không hạn chế khoảng cách. ③Khi bạn sử dụng lá 【Sát】 thứ hai trở đi trong giai đoạn ra bài, bạn nhận được hiệu ứng sau: {Lá 【Sát】 này không thể bị phản hồi và trị số sát thương cơ bản +1; Sau khi lá 【Sát】 này chỉ định mục tiêu, kỹ năng phi khóa của nhân vật mục tiêu mất hiệu lực trong lượt này; Sau khi lá 【Sát】 này gây sát thương, nếu nhân vật mục tiêu còn sống, thì bạn mất 1 điểm thể lực và ngẫu nhiên bỏ một lá bài tay.}",
	sbxieji: "Hiệp Kích",
	sbxieji_info: `Khi bắt đầu giai đoạn chuẩn bị, bạn có thể cùng một nhân vật khác tiến hành ${get.poptip("rule_xieli")}. Khi bắt đầu giai đoạn kết thúc kế tiếp của người đó, nếu bạn cùng người đó hiệp lực thành công, thì bạn có thể chọn tối đa ba nhân vật khác. Bạn đối với những nhân vật này xem như sử dụng một lá 【Sát】, và khi lá 【Sát】 này vì thực hiện hiệu ứng mặt bài mà gây ra sát thương, bạn rút X lá bài (X là trị số sát thương).`,
	sb_zhaoyun: "Mưu Triệu Vân",
	sblongdan: "Long Đạm",
	sblongdan_info: "Kỹ năng tích lũy (1/3). ①Bạn có thể tiêu hao 1 điểm tích lũy, đem 【Sát】 xem như 【閃】 hoặc đem 【閃】 xem như 【Sát】 sử dụng hoặc đánh ra, sau đó bạn rút một lá bài. ②Khi kết thúc lượt của một nhân vật, bạn nhận được 1 điểm tích lũy.",
	sbjizhu: "Tích Trứ",
	sbjizhu_info: `Khi bắt đầu giai đoạn chuẩn bị, bạn có thể cùng một nhân vật khác tiến hành ${get.poptip("rule_xieli")}. Khi bắt đầu giai đoạn kết thúc kế tiếp của người đó, nếu bạn cùng người đó hiệp lực thành công, thì bạn sửa đổi 〖Long Đạm〗 cho đến khi bắt đầu giai đoạn kết thúc kế tiếp của bạn.`,
	sblongdan_shabi: "Long Đạm-Cải",
	sblongdan_shabi_info: "Kỹ năng tích lũy (1/3). ①Bạn có thể tiêu hao 1 điểm tích lũy, đem một lá bài Cơ bản xem như bài Cơ bản bất kỳ sử dụng hoặc đánh ra, sau đó rút một lá bài. ②Khi kết thúc lượt của một nhân vật, bạn nhận được 1 điểm tích lũy.",
	sb_liubei: "Mưu Lưu Bị",
	sbrende: "Nhân Đức",
	sbrende_info: "①Giai đoạn ra bài mỗi nhân vật giới hạn một lần. Bạn có thể giao bất kỳ số lượng bài nào cho một nhân vật khác, sau đó bạn nhận được số lượng dấu ấn “Nhân Vọng” tương đương (tối đa là 8). ②Mỗi lượt giới hạn một lần. Bạn có thể loại bỏ 2 dấu ấn “Nhân Vọng”, xem như sử dụng hoặc đánh ra một lá bài Cơ bản. ③Khi bắt đầu giai đoạn ra bài, bạn nhận được 2 dấu ấn “Nhân Vọng”.",
	sbzhangwu: "Chương Võ",
	sbzhangwu_info: "Kỹ năng giới hạn. Giai đoạn ra bài, bạn có thể khiến tất cả nhân vật khác từng trở thành mục tiêu của 〖Nhân Đức①〗 trong ván đấu này lần lượt giao cho bạn X lá bài, sau đó bạn hồi 3 điểm thể lực và mất 〖Nhân Đức〗 (X là số vòng trò chơi -1, và tối đa là 3).",
	sbjijiang: "Kích Tướng",
	sbjijiang_info: "Kỹ năng chủ công. Khi kết thúc giai đoạn ra bài, bạn có thể chọn một nhân vật thế lực Thục khác A có trị số thể lực không nhỏ hơn bạn và một nhân vật B nằm trong phạm vi tấn công của A. A chọn một mục: 1. Xem như đối với B sử dụng một lá 【Sát】; 2. Trước khi bắt đầu giai đoạn ra bài kế tiếp, nhảy qua giai đoạn này.",
	sb_jiangwei: "Mưu Khương Duy",
	sbtiaoxin: "Khiêu Khích",
	sbtiaoxin_info: `Giai đoạn ra bài giới hạn một lần, bạn có thể chọn một mục và khiến một nhân vật khác thực hiện: 1. Đem một lá bài tay xem như 【Quyết Đấu】 sử dụng đối với bạn, nếu không lượt này không thể sử dụng hoặc đánh ra bài; 2. Đối với bạn sử dụng một lá 【Sát】, nếu không bạn bỏ một lá bài của người đó. ${get.poptip("rule_beishui")}: Lượt này bạn và người đó chịu sát thương +1.`,
	sbzhiji: "Chí Kế",
	sbzhiji_info: `Kỹ năng thức tỉnh. Giai đoạn chuẩn bị, nếu số bài tay của bạn không lớn hơn trị số thể lực, bạn giảm 1 điểm giới hạn thể lực, hồi 1 điểm thể lực và rút hai lá bài, nhận được ${get.poptip("sbbeifa")}.`,
	sbbeifa: "Bắc Phạt",
	sbbeifa_info: "Kỹ năng tích lũy (3/9). ①Giai đoạn ra bài giới hạn một lần, bạn có thể tiêu hao bất kỳ điểm tích lũy nào, đem một lá bài tay xem như lá bài có cùng số chữ và chưa được ghi nhớ chỉ có thể sử dụng cho nhân vật khác để sử dụng hoặc đánh ra, sau đó ghi nhớ nó. ②Khi bạn chịu sát thương trong lượt hoặc số lượng tên bài ghi nhớ của 〖Bắc Phạt〗 đạt đến X, xóa toàn bộ ghi nhớ, sau đó nếu X lớn hơn 1, giới hạn tích lũy -1 (X là giới hạn tích lũy do kỹ năng này cung cấp). ③Trong lượt của bạn, khi có bài chuyển hóa được sử dụng hoặc đánh ra hoặc có bài bị bỏ, bạn nhận được điểm tích lũy tương ứng với số lượng lá bài thực thể.",
	sb_fazheng: "Mưu Pháp Chính",
	sbxuanhuo: "Huyễn Hoặc",
	sbxuanhuo_info: "①Giai đoạn ra bài giới hạn một lần. Bạn có thể giao một lá bài cho một nhân vật khác chưa có dấu ấn “Huyễn”, sau đó khiến người đó nhận dấu ấn “Huyễn”. ②Khi nhân vật khác có “Huyễn” nhận được bài ngoài giai đoạn rút bài, nếu trong thời gian người đó nhận “Huyễn” lần này mà số lượng bài bạn nhận được từ người đó nhỏ hơn 5, bạn ngẫu nhiên nhận một lá bài tay của người đó.",
	sbenyuan: "Ân Oán",
	sbenyuan_info: "Kỹ năng khóa. Giai đoạn chuẩn bị, nếu trên sân tồn tại nhân vật có “Huyễn”, bạn loại bỏ “Huyễn” của nhân vật đó, và số lượng bài bạn nhận được từ người đó trong thời gian người đó nhận “Huyễn” lần này: không ít hơn 3, bạn giao cho người đó ba lá bài; nhỏ hơn 3, người đó mất 1 điểm thể lực, bạn hồi 1 điểm thể lực.",
	sb_chengong: "Mưu Trần Cung",
	sbmingce: "Minh Sách",
	sbmingce_info: "①Giai đoạn ra bài giới hạn một lần. Bạn có thể giao một lá bài cho một nhân vật khác, người đó chọn một mục: 1. Mất 1 điểm thể lực, khiến bạn rút hai lá bài và nhận được 1 dấu ấn “Sách”; 2. Rút một lá bài. ②Khi bắt đầu giai đoạn ra bài, bạn có thể loại bỏ toàn bộ “Sách” và gây cho một nhân vật khác sát thương tương ứng.",
	sbzhichi: "Trí Trì",
	sbzhichi_info: "Kỹ năng khóa. Sau khi bạn chịu sát thương, ngăn chặn sát thương bạn phải chịu trong lượt này.",
	sb_yuanshao: "Mưu Viên Thiệu",
	sbluanji: "Loạn Kích",
	sbluanji_info: "①Giai đoạn ra bài giới hạn một lần. Bạn có thể đem hai lá bài tay xem như 【Vạn Tiễn Tề Phát】 sử dụng. ②Mỗi lượt giới hạn ba lần, khi nhân vật khác vì phản hồi 【Vạn Tiễn Tề Phát】 bạn sử dụng mà đánh ra 【閃】, bạn rút một lá bài.",
	sbxueyi: "Huyết Duệ",
	sbxueyi_info: "Kỹ năng chủ công, kỹ năng khóa. ①Giới hạn bài tay của bạn +2X (X là số nhân vật thế lực Quần khác trên sân). ②Mỗi lượt giới hạn hai lần, sau khi bạn sử dụng bài chỉ định nhân vật thế lực Quần khác làm mục tiêu, bạn rút một lá bài.",
	sb_diaochan: "Mưu Điêu Thuyền",
	sblijian: "Ly Gián",
	sblijian_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể chọn ít nhất hai nhân vật khác và bỏ X lá bài (X là số lượng nhân vật bạn chọn trừ 1). Sau đó mỗi nhân vật bạn chọn lần lượt xem như đối với nhân vật khác có vị trí gần nhất theo chiều ngược kim đồng hồ trong số các nhân vật này sử dụng một lá 【Quyết Đấu】.",
	sbbiyue: "Bế Nguyệt",
	sbbiyue_info: "Kỹ năng khóa. Giai đoạn kết thúc, bạn rút Y lá bài (Y là số lượng nhân vật bao gồm cả nhân vật đã tử vong từng chịu sát thương trong lượt này +1 và tối đa là 4).",
	sb_pangtong: "Mưu Bàng Thống",
	sblianhuan: "Liên Hoàn",
	sblianhuan_info: "①Giai đoạn ra bài, bạn có thể đúc lại một lá bài tay ♣. ②Giai đoạn ra bài giới hạn một lần. Bạn có thể đem một lá bài tay ♣ xem như 【Thiết Tỏa Liên Hoàn】 sử dụng. ③Khi bạn sử dụng 【Thiết Tỏa Liên Hoàn】, bạn có thể mất 1 điểm thể lực, sau đó khi lá bài này chỉ định mục tiêu đầu tiên, bạn ngẫu nhiên bỏ một lá bài tay của mỗi nhân vật mục tiêu không trong trạng thái liên hoàn.",
	sblianhuan_lv2: "Liên Hoàn-Cải",
	sblianhuan_lv2_info: "①Giai đoạn ra bài, bạn có thể đúc lại một lá bài tay ♣. ②Giai đoạn ra bài giới hạn một lần. Bạn có thể đem một lá bài tay ♣ xem như 【Thiết Tỏa Liên Hoàn】 sử dụng. ③Khi bạn sử dụng 【Thiết Tỏa Liên Hoàn】, bạn có thể chỉ định thêm bất kỳ số lượng nhân vật nào làm mục tiêu. ④Sau khi bạn sử dụng 【Thiết Tỏa Liên Hoàn】 chỉ định mục tiêu đầu tiên, bạn ngẫu nhiên bỏ một lá bài tay của mỗi nhân vật mục tiêu không trong trạng thái liên hoàn.",
	sbniepan: "Niết Bàn",
	sbniepan_info: "Kỹ năng giới hạn. Khi bạn trong trạng thái hấp hối, bạn có thể bỏ toàn bộ bài trong các vùng, rút hai lá bài, hồi phục thể lực đến 2 điểm, lật ngửa lại thẻ võ tướng, sau đó sửa đổi 〖Liên Hoàn〗.",
	sb_sunce: "Mưu Tôn Sách",
	sbjiang: "Kích Ngang",
	sbjiang_info: "①Khi bạn sử dụng 【Quyết Đấu】 hoặc 【Sát】 đỏ chỉ định mục tiêu, hoặc khi bạn trở thành mục tiêu của 【Quyết Đấu】 hoặc 【Sát】 đỏ, bạn rút một lá bài. ②Khi bạn sử dụng 【Quyết Đấu】, bạn có thể chỉ định thêm một mục tiêu, sau đó bạn mất 1 điểm thể lực. ③Giai đoạn ra bài giới hạn một lần. Bạn có thể đem toàn bộ bài tay xem như 【Quyết Đấu】 sử dụng.",
	sbhunzi: "Hồn Tư",
	sbhunzi_info: `Kỹ năng thức tỉnh. Sau khi bạn thoát khỏi trạng thái hấp hối, bạn giảm 1 điểm giới hạn thể lực, nhận 1 điểm hộ giáp, rút ba lá bài. Sau đó bạn nhận được ${get.poptip("sbyingzi")} và ${get.poptip("gzyinghun")}.`,
	sbzhiba: "Chế Bá",
	sbzhiba_info: "Kỹ năng chủ công, kỹ năng giới hạn. Khi bạn vào trạng thái hấp hối, bạn có thể hồi X-1 điểm thể lực và sửa đổi 〖Kích Ngang③〗 thành “Giai đoạn ra bài giới hạn X lần” (X là số nhân vật thế lực Ngô khác trên sân +1). Sau đó những nhân vật thế lực Ngô khác lần lượt chịu 1 điểm sát thương không nguồn, và khi có nhân vật vì thế mà tử vong, bạn rút ba lá bài.",
	sb_daqiao: "Mưu Đại Kiều",
	sbguose: "Quốc Sắc",
	sbguose_info: "Giai đoạn ra bài giới hạn bốn lần, bạn có thể đem một lá bài ♦ xem như 【Lạc Bất Tư Thục】 sử dụng hoặc bỏ một lá 【Lạc Bất Tư Thục】 trên sân, sau đó bạn rút một lá bài.",
	sbliuli: "Lưu Ly",
	sbliuli_info: "Khi bạn trở thành mục tiêu của 【Sát】, bạn có thể bỏ một lá bài và chọn một nhân vật trong phạm vi tấn công của bạn không phải người sử dụng 【Sát】 này, chuyển dịch lá 【Sát】 này cho nhân vật đó. Nếu bạn bỏ bài ♥ theo cách này, thì bạn có thể khiến một nhân vật khác không phải người sử dụng 【Sát】 này nhận dấu ấn “Lưu Ly”, và loại bỏ toàn bộ các dấu ấn “Lưu Ly” khác trên sân (mỗi lượt giới hạn một lần). Khi bắt đầu lượt của nhân vật có “Lưu Ly”, người đó loại bỏ “Lưu Ly” của mình và thực hiện thêm một giai đoạn ra bài.",
	sb_liubiao: "Mưu Lưu Biểu",
	sbzishou: "Tự Thủ",
	sbzishou_info: "Kỹ năng khóa. Giai đoạn kết thúc của nhân vật khác, nếu người đó và bạn trong ván đấu này đều chưa từng gây sát thương cho đối phương, người đó phải giao cho bạn một lá bài.",
	sbzongshi: "Tông Thất",
	sbzongshi_info: "Kỹ năng khóa. Mỗi nhân vật giới hạn một lần. Sau khi bạn chịu sát thương, bạn khiến nguồn gây sát thương bỏ toàn bộ bài tay.",
	sb_zhurong: "Mưu Chúc Dung",
	sblieren: "Liệt Nhẫn",
	sblieren_info: "Sau khi bạn sử dụng 【Sát】 chỉ định mục tiêu duy nhất, sau đó cùng người đó đấu điểm. Nếu bạn thắng, sau khi lá 【Sát】 này kết thúc kết toán, bạn có thể gây cho một nhân vật khác 1 điểm sát thương.",
	sbjuxiang: "Cự Tượng",
	sbjuxiang_info: "Kỹ năng khóa. ①【Nam Man Nhập Xâm】 vô hiệu đối với bạn. ②Sau khi nhân vật khác sử dụng 【Nam Man Nhập Xâm】 kết thúc kết toán, bạn nhận được toàn bộ bài thực thể tương ứng của lá bài này. ③Giai đoạn kết thúc, nếu bạn chưa từng sử dụng 【Nam Man Nhập Xâm】 trong lượt này, bạn đem một lá 【Nam Man Nhập Xâm】 ngẫu nhiên ngoài trò chơi (tổng cộng hai lá) giao cho một nhân vật.",
	sb_menghuo: "Mưu Mạnh Hoạch",
	sbhuoshou: "Họa Thủ",
	sbhuoshou_info: "Kỹ năng khóa. ①【Nam Man Nhập Xâm】 vô hiệu đối với bạn. ②Sau khi nhân vật khác sử dụng 【Nam Man Nhập Xâm】 chỉ định mục tiêu đầu tiên, bạn thay thế người đó trở thành nguồn gây sát thương của lá bài này. ③Khi bắt đầu giai đoạn ra bài, bạn ngẫu nhiên nhận được một lá 【Nam Man Nhập Xâm】 trong chồng bài bỏ. ④Giai đoạn ra bài, nếu bạn đã sử dụng 【Nam Man Nhập Xâm】 trong giai đoạn này, bạn không thể sử dụng 【Nam Man Nhập Xâm】.",
	sbzaiqi: "Tái Khởi",
	sbzaiqi_info: "Kỹ năng tích lũy (0/7). ①Khi kết thúc giai đoạn bỏ bài, bạn có thể tiêu hao bất kỳ điểm tích lũy nào và chọn số lượng nhân vật tương ứng, sau đó khiến những nhân vật này chọn một mục: 1. Khiến bạn rút một lá bài; 2. Bỏ một lá bài, sau đó bạn hồi 1 điểm thể lực. ②Mỗi lượt giới hạn một lần. Sau khi bạn gây sát thương, bạn nhận được 1 điểm tích lũy.",
	sb_zhanghe: "Mưu Trương Cáp",
	sbqiaobian: "Xảo Biến",
	sbqiaobian_info: "Giai đoạn chuẩn bị, bạn có thể bỏ bất kỳ số lượng bài nào trong các vùng khác nhau, sau đó nhảy qua số lượng giai đoạn tương ứng, và sau khi nhảy qua giai đoạn tương ứng có thể thực hiện hiệu ứng tương quan. Nếu bạn nhảy qua theo cách này: 1. Giai đoạn rút bài, bạn có thể nhận tối đa hai nhân vật khác mỗi người một lá bài tay; 2. Giai đoạn ra bài, bạn có thể di chuyển một lá bài trên sân, sau đó nếu số bài trong vùng trang bị của bạn không tăng thêm, thì bạn có thể khiến nhân vật có số bài trên sân tăng thêm vì thế rút hai lá bài; 3. Giai đoạn bỏ bài, bạn rút một lá bài, giai đoạn kết thúc, nếu số bài tay của bạn không nhỏ hơn số nhân vật trên sân, bạn thực hiện thêm một giai đoạn ra bài.",
	sbliaoshi: "Liệu Thế",
	sbliaoshi_info: `Mỗi lượt giới hạn một lần, bạn có thể đem bài nhận được nhờ 〖Xảo Biến〗 xem như 【Sát】 hoặc 【閃】 sử dụng hoặc đánh ra.`,
	old_sbqiaobian: "Xảo Biến",
	old_sbqiaobian_info: "Mỗi lượt giới hạn một lần. ①Bạn có thể mất 1 điểm thể lực và nhảy qua giai đoạn phán xét, di chuyển toàn bộ bài trong vùng phán xét cho một nhân vật khác (lá bài không thể đặt vào vùng phán xét của người đó thì đổi thành bỏ đi). ②Bạn có thể nhảy qua giai đoạn rút bài, tại giai đoạn chuẩn bị kế tiếp rút năm lá bài và hồi 1 điểm thể lực. ③Bạn có thể bỏ bài tay cho đến khi còn sáu lá (nếu số bài tay ít hơn sáu lá thì nhảy qua) và nhảy qua giai đoạn ra bài cùng giai đoạn bỏ bài, sau đó di chuyển một lá bài trên sân.",
	sb_yl_luzhi: "Mưu Lư Thực",
	sb_yl_luzhi_prefix: "Mưu",
	sbmingren: "Minh Nhiệm",
	sbmingren_info: "①Khi trò chơi bắt đầu, bạn rút ba lá bài, sau đó đặt một lá bài tay lên thẻ võ tướng của bạn, gọi là “Nhiệm”. ②Giai đoạn kết thúc, bạn có thể dùng một lá bài tay thay thế “Nhiệm”.",
	sbzhenliang: "Trinh Lương",
	sbzhenliang_info: "Kỹ năng chuyển đổi. Dương: Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ X lá bài có cùng màu sắc với “Nhiệm” và gây cho một nhân vật trong phạm vi tấn công 1 điểm sát thương (X là hiệu số trị số thể lực giữa bạn và người đó và X ít nhất là 1). Âm: Ngoài lượt của bạn, sau khi một nhân vật sử dụng hoặc đánh ra bài kết thúc kết toán, nếu lá bài này cùng loại biệt với “Nhiệm”, thì bạn có thể khiến tối đa hai nhân vật mỗi người rút hai lá bài.",
	sb_xiaoqiao: "Mưu Tiểu Kiều",
	sb_xiaoqiao_prefix: "Mưu",
	sbtianxiang: "Thiên Hương",
	sbtianxiang_info: "①Giai đoạn ra bài giới hạn ba lần, bạn có thể giao cho một nhân vật khác chưa có dấu ấn “Thiên Hương” một lá bài tay màu đỏ, sau đó khiến người đó nhận dấu ấn “Thiên Hương” của hoa sắc lá bài này. ②Khi bạn chịu sát thương, bạn có thể loại bỏ dấu ấn “Thiên Hương” của một nhân vật, nếu dấu ấn “Thiên Hương” này là: Cơ (♥), bạn ngăn chặn sát thương này, người đó chịu 1 điểm sát thương do nguồn gây sát thương gây ra cho họ (nếu không có nguồn gây sát thương thì đổi thành sát thương không nguồn); Rô (♦), người đó giao cho bạn hai lá bài. ③Giai đoạn chuẩn bị, bạn loại bỏ toàn bộ dấu ấn “Thiên Hương” trên sân, sau đó rút số lượng bài tương đương.",
	sbtianxiang_info_versus_two: "①Giai đoạn ra bài giới hạn ba lần, bạn có thể giao cho một nhân vật khác chưa có dấu ấn “Thiên Hương” một lá bài tay màu đỏ, sau đó khiến người đó nhận dấu ấn “Thiên Hương” của hoa sắc lá bài này. ②Khi bạn chịu sát thương, bạn có thể loại bỏ dấu ấn “Thiên Hương” của một nhân vật, nếu dấu ấn “Thiên Hương” này là: Cơ (♥), bạn ngăn chặn sát thương này, người đó chịu 1 điểm sát thương do nguồn gây sát thương gây ra cho họ (nếu không có nguồn gây sát thương thì đổi thành sát thương không nguồn); Rô (♦), người đó giao cho bạn hai lá bài. ③Giai đoạn chuẩn bị, bạn loại bỏ toàn bộ dấu ấn “Thiên Hương” trên sân, sau đó rút X lá bài (X là số lượng dấu ấn “Thiên Hương” bị loại bỏ + 2).",
	sb_sp_zhugeliang: "Mưu Gia Cát Lượng",
	sb_sp_zhugeliang_prefix: "Mưu",
	sbhuoji: "Hỏa Kế",
	sbhuoji_info: `Kỹ năng sứ mệnh. ①Sứ mệnh: Giai đoạn ra bài giới hạn một lần. Bạn có thể gây cho một nhân vật khác 1 điểm sát thương lửa, sau đó bạn đối với tất cả các nhân vật khác có cùng thế lực với người đó và không phải người đó gây mỗi người 1 điểm sát thương lửa. ②Thành công: Giai đoạn chuẩn bị, nếu ván đấu này bạn đã gây sát thương lửa cho nhân vật khác không ít hơn tổng số nhân vật ván đấu này, thì bạn mất 〖Hỏa Kế〗 và 〖Khán Phá〗, sau đó nhận được ${get.poptip("sbguanxing")} và ${get.poptip("sbkongcheng")}. ③Thất bại: Trước khi sứ mệnh thành công bị vào trạng thái hấp hối.`,
	sbkanpo: "Khán Phá",
	sbkanpo_info: "①Khi bắt đầu mỗi vòng, bạn xóa tên bài đã ghi nhớ của 〖Khán Phá①〗, sau đó bạn có thể lần lượt ghi nhớ bất kỳ tên bài phi trang bị nào chưa từng được ghi nhớ ở lần phát động 〖Khán Phá①〗 trước đó (nhân vật khác không nhìn thấy, mỗi ván đấu tối đa ghi nhớ 2 tên bài). ②Khi nhân vật khác sử dụng lá bài có tên bài bạn đã ghi nhớ ở 〖Khán Phá①〗, bạn có thể loại bỏ một ghi nhớ của tên bài này trong 〖Khán Phá①〗 khiến lá bài này vô hiệu, sau đó bạn rút một lá bài.",
	sbkanpo_info_identity: "①Khi bắt đầu mỗi vòng, bạn xóa tên bài đã ghi nhớ của 〖Khán Phá①〗, sau đó bạn có thể lần lượt ghi nhớ bất kỳ tên bài phi trang bị nào chưa từng được ghi nhớ ở lần phát động 〖Khán Phá①〗 trước đó (nhân vật khác không nhìn thấy, mỗi ván đấu tối đa ghi nhớ 4 tên bài). ②Khi nhân vật khác sử dụng lá bài có tên bài bạn đã ghi nhớ ở 〖Khán Phá①〗, bạn có thể loại bỏ một ghi nhớ của tên bài này trong 〖Khán Phá①〗 khiến lá bài này vô hiệu, sau đó bạn rút một lá bài.",
	sbguanxing: "Quan Tinh",
	sbguanxing_info: "①Giai đoạn chuẩn bị, bạn đem toàn bộ “Tinh” đặt vào chồng bài bỏ, đem X lá trên cùng của chồng bài đặt lên thẻ võ tướng của bạn, gọi là “Tinh” (X là 7 trừ đi ba lần số lần đã phát động 〖Quan Tinh①〗 trước đó, và X ít nhất là 0). Sau đó bạn có thể đặt bất kỳ số lượng “Tinh” nào lên trên cùng chồng bài. ②Giai đoạn kết thúc, nếu bạn chưa từng đặt “Tinh” lên trên cùng chồng bài tại giai đoạn chuẩn bị của lượt này, bạn có thể đặt bất kỳ số lượng “Tinh” nào lên trên cùng chồng bài. ③Bạn có thể sử dụng hoặc đánh ra “Tinh” như bài tay.",
	sbkongcheng: "Không Thành",
	sbkongcheng_info: "Kỹ năng khóa. Khi bạn chịu sát thương, nếu bạn sở hữu kỹ năng 〖Quan Tinh〗, và nếu bạn: có “Tinh”, bạn phán xét, nếu kết quả điểm số không lớn hơn số lượng “Tinh” của bạn, sát thương này -1; không có “Tinh”, sát thương này +1.",
	sb_huangyueying: "Mưu Hoàng Nguyệt Anh",
	sb_huangyueying_prefix: "Mưu",
	sbqicai: "Kỳ Tài",
	sbqicai_backup: "Kỳ Tài",
	sbqicai_info: "①Giai đoạn ra bài giới hạn một lần. Bạn có thể đem một lá bài trang bị trong bài tay hoặc trong chồng bài bỏ đặt vào ô trang bị tương ứng của một nhân vật khác, sau đó người đó nhận được hiệu ứng sau: Sau khi người đó nhận được lá Cẩm nang thường, người đó giao lá bài này cho bạn (giới hạn ba lá). ②Bạn sử dụng lá bài Cẩm nang không hạn chế khoảng cách.",
	sbjizhi: "Tập Trí",
	sbjizhi_info: "Kỹ năng khóa, khi bạn sử dụng một lá Cẩm nang thường, bạn rút một lá bài, và lá bài này lượt này không tính vào giới hạn bài tay của bạn.",
	sb_guanyu: "Mưu Quan Vũ",
	sb_guanyu_prefix: "Mưu",
	sbwusheng: "Võ Thánh",
	sbwusheng_wusheng_backup: "Võ Thánh",
	sbwusheng_info: "Bạn có thể đem một lá bài tay xem như 【Sát】 bất kỳ sử dụng hoặc đánh ra. Khi bắt đầu giai đoạn ra bài, bạn có thể chọn một nhân vật khác không phải chủ công, giai đoạn này đối với người đó sử dụng 【Sát】 không hạn chế khoảng cách và số lần, sau khi sử dụng 【Sát】 chỉ định người đó làm mục tiêu thì rút một lá bài, sau khi sử dụng ba lá 【Sát】 đối với người đó thì không thể sử dụng 【Sát】 đối với người đó nữa.",
	sbwusheng_info_identity: "Bạn có thể đem một lá bài tay xem như 【Sát】 bất kỳ sử dụng hoặc đánh ra. Khi bắt đầu giai đoạn ra bài, bạn có thể chọn một nhân vật khác không phải chủ công, giai đoạn này đối với người đó sử dụng 【Sát】 không hạn chế khoảng cách và số lần, sau khi sử dụng 【Sát】 chỉ định người đó làm mục tiêu thì rút hai lá bài, sau khi sử dụng ba lá 【Sát】 đối với người đó thì không thể sử dụng 【Sát】 đối với người đó nữa.",
	sbyijue: "Nghĩa Tuyệt",
	sbyijue_info: "Kỹ năng khóa, mỗi nhân vật mỗi ván đấu giới hạn một lần, khi một nhân vật khác chịu sát thương do bạn gây ra lớn hơn hoặc bằng trị số thể lực của họ, bạn ngăn chặn sát thương này, và lượt này khi bạn sử dụng bài chỉ định người đó làm mục tiêu, lá bài này vô hiệu đối với người đó.",
	sb_caopi: "Mưu Tào Phi",
	sb_caopi_prefix: "Mưu",
	sbxingshang: "Hành Sảng",
	sbxingshang_info: "①Khi một nhân vật chịu sát thương (mỗi lượt giới hạn một lần) hoặc tử vong, bạn nhận được 2 dấu ấn “Tụng” (bạn sở hữu tối đa 9 dấu ấn “Tụng”). ②Giai đoạn ra bài giới hạn hai lần, bạn có thể: " + ["Loại bỏ 2 dấu ấn “Tụng”, khiến một nhân vật lật ngửa lại thẻ võ tướng", "Loại bỏ 2 dấu ấn “Tụng”, khiến một nhân vật rút ba lá bài", "Loại bỏ 3 dấu ấn “Tụng”, khiến một nhân vật có giới hạn thể lực nhỏ hơn 10 hồi 1 điểm thể lực, tăng 1 điểm giới hạn thể lực, ngẫu nhiên khôi phục một ô trang bị đã bị phế bỏ", "Loại bỏ 4 dấu ấn “Tụng”, nhận được tất cả kỹ năng trên thẻ võ tướng của một nhân vật đã trận vong, sau đó bạn mất 〖Hành Sảng〗〖Phóng Trục〗〖Tụng Uy〗"].map((str, index) => `${index + 1}.${str}`).join("；") + "。",
	sbfangzhu: "Phóng Trục",
	sbfangzhu_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể: " + ["Loại bỏ 2 dấu ấn “Tụng”, khiến một nhân vật khác chỉ có thể sử dụng bài Cơ bản từ bài tay cho đến khi kết thúc lượt của người đó", "Loại bỏ 6 dấu ấn “Tụng”, khiến một nhân vật khác chỉ có thể sử dụng bài Cẩm nang từ bài tay cho đến khi kết thúc lượt của người đó", "Loại bỏ 8 dấu ấn “Tụng”, khiến một nhân vật khác chỉ có thể sử dụng bài Trang bị từ bài tay cho đến khi kết thúc lượt của người đó", "Loại bỏ 6 dấu ấn “Tụng”, khiến kỹ năng phi Charlotte của một nhân vật khác mất hiệu lực cho đến khi kết thúc lượt của người đó", "Loại bỏ 4 dấu ấn “Tụng”, khiến một nhân vật khác không thể phản hồi lá bài do một nhân vật khác sử dụng cho đến khi kết thúc lượt của người đó", "Loại bỏ 8 dấu ấn “Tụng”, khiến một nhân vật khác lật mặt thẻ võ tướng"].map((str, index) => `${index + 1}.${str}`).join("；") + "。",
	sbfangzhu_info_doudizhu: "Giai đoạn ra bài giới hạn một lần, bạn có thể: " + ["Loại bỏ 2 dấu ấn “Tụng”, khiến một nhân vật khác chỉ có thể sử dụng bài Cơ bản từ bài tay cho đến khi kết thúc lượt của người đó", "Loại bỏ 6 dấu ấn “Tụng”, khiến một nhân vật khác chỉ có thể sử dụng bài Cẩm nang từ bài tay cho đến khi kết thúc lượt của người đó", "Loại bỏ 4 dấu ấn “Tụng”, khiến một nhân vật khác không thể phản hồi lá bài do một nhân vật khác sử dụng cho đến khi kết thúc lượt của người đó"].map((str, index) => `${index + 1}.${str}`).join("；") + "。",
	sbsongwei: "Tụng Uy",
	sbsongwei_info: "Kỹ năng chủ công, khi bắt đầu giai đoạn ra bài, bạn nhận được Y dấu ấn “Tụng” (Y là hai lần số nhân vật thế lực Ngụy khác trên sân).",
	sb_xunyu: "Mưu Tuân Úc",
	sb_xunyu_prefix: "Mưu",
	sbquhu: "Khu Hổ",
	sbquhu_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể chọn hai nhân vật khác có bài, bạn cùng những nhân vật này đồng thời úp bất kỳ số lượng bài nào lên thẻ võ tướng. Nếu số bài bạn úp theo cách này là duy nhất ít nhất, thì nhân vật khác úp bài nhiều nhất nhận được số bài bạn úp, và những nhân vật này nhận lại số bài úp của chính mình; nếu không, trong hai nhân vật này nhân vật úp bài nhiều hơn gây cho nhân vật úp bài ít hơn 1 điểm sát thương, nhận được số bài bạn úp, sau đó những nhân vật này đem số bài úp của chính mình đặt vào chồng bài bỏ (nếu hai nhân vật này úp số bài bằng nhau, xem như nhân vật có vị trí gần nhất theo chiều ngược kim đồng hồ với bạn úp bài nhiều hơn).",
	sbjieming: "Tiết Mệnh",
	sbjieming_info: "Sau khi bạn chịu sát thương, bạn có thể khiến một nhân vật rút bốn lá bài, sau đó người đó có thể bỏ bất kỳ số lượng bài nào. Nếu số bài người đó bỏ nhỏ hơn X, bạn mất 1 điểm thể lực (X là số điểm thể lực bạn đã mất, ít nhất là 1).",
	sb_xiahoudun: "Mưu Hạ Hầu Đôn",
	sb_xiahoudun_prefix: "Mưu",
	sbganglie: "Cương Liệt",
	sbganglie_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể chọn bất kỳ nhân vật nào từng gây sát thương cho bạn trong ván đấu này và bạn chưa từng chọn theo cách này, bạn gây cho người đó 2 điểm sát thương.",
	sbqingjian: "Thanh Kiệm",
	sbqingjian_info: "①Khi có một lá bài không vì sử dụng mà rơi vào chồng bài bỏ, nếu số lượng “Thanh Kiệm” của bạn nhỏ hơn X, bạn đem lá bài này đặt lên thẻ võ tướng của mình, gọi là “Thanh Kiệm” (X là trị số thể lực của bạn +1, và ít nhất là 1). ②Khi kết thúc giai đoạn ra bài, bạn đem toàn bộ “Thanh Kiệm” phân phối cho nhân vật bất kỳ.",
	sb_gaoshun: "Mưu Cao Thuận",
	sb_gaoshun_prefix: "Mưu",
	sbxianzhen: "Hãm Trận",
	sbxianzhen_info_identity: "Giai đoạn ra bài giới hạn một lần. Bạn có thể chọn một nhân vật có trị số thể lực nhỏ hơn bạn, bạn tại giai đoạn này nhận được hiệu ứng sau: ⒈ Bạn đối với người đó sử dụng bài không hạn chế khoảng cách; ⒉ Khi bạn sử dụng 【Sát】 chỉ định người đó làm mục tiêu, bạn có thể cùng người đó đấu điểm: nếu bạn thắng, lá 【Sát】 này bỏ qua phòng cụ và không tính vào số lần, và nếu lượt này bạn gây sát thương cho người đó theo cách này nhỏ hơn 2, bạn gây cho người đó 1 điểm sát thương; nếu lá bài đấu điểm của người đó là 【Sát】, thì bạn nhận lấy nó; nếu lá bài đấu điểm của người đó là lá bài tay cuối cùng của người đó, thì khi lá 【Sát】 này gây sát thương cho người đó, sát thương này +1.",
	sbxianzhen_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể chọn một nhân vật khác, bạn tại giai đoạn này nhận được hiệu ứng sau: ⒈ Bạn đối với người đó sử dụng bài không hạn chế khoảng cách; ⒉ Khi bạn sử dụng 【Sát】 chỉ định người đó làm mục tiêu, bạn có thể cùng người đó đấu điểm: nếu bạn thắng, lá 【Sát】 này bỏ qua phòng cụ và không tính vào số lần, và nếu lượt này bạn gây sát thương cho người đó theo cách này nhỏ hơn 2, bạn gây cho người đó 1 điểm sát thương; nếu lá bài đấu điểm của người đó là 【Sát】, thì bạn nhận lấy nó; nếu lá bài đấu điểm của người đó là lá bài tay cuối cùng của người đó, thì khi lá 【Sát】 này gây sát thương cho người đó, sát thương này +1.",
	sbjinjiu: "Cấm Tửu",
	sbjinjiu_info: "Kỹ năng khóa. ①【Tửu】 của bạn đều được coi là 【Sát】. ②Khi bạn chịu sát thương của lá 【Sát】 có nạp 【Tửu】, bạn khiến sát thương này giảm còn 1. ③Nhân vật khác không thể sử dụng 【Tửu】 trong lượt của bạn. ④Sau khi lá bài đấu điểm của nhân vật khác trưng bày, nếu bạn là người phát động hoặc người tham gia và lá bài này là 【Tửu】, thì điểm số của lá bài này được coi là A.",
	sb_handang: "Mưu Hàn Đương",
	sb_handang_prefix: "Mưu",
	sbgongqi: "Cung Kỵ",
	sbgongqi_info: "①Khi bắt đầu giai đoạn ra bài, bạn có thể bỏ một lá bài, sau đó giai đoạn này bạn nhận được hiệu ứng sau: Khi bạn sử dụng bài, bạn khiến tất cả các nhân vật khác không thể sử dụng hoặc đánh ra bài tay có màu sắc khác với lá bài bạn đã bỏ để phản hồi lá bài này. ②Phạm vi tấn công của bạn +4.",
	sbjiefan: "Giải Phiền",
	sbjiefan_info: `Giai đoạn ra bài giới hạn một lần, bạn có thể khiến một nhân vật chọn một mục: ⒈ Khiến tất cả các nhân vật có phạm vi tấn công bao hàm người đó lần lượt bỏ một lá bài; ⒉ Người đó rút số lượng bài bằng với số lượng nhân vật có phạm vi tấn công bao hàm người đó; ⒊ ${get.poptip("rule_beishui")}: Kỹ năng này vô hiệu cho đến khi bạn giết một nhân vật.`,
	sb_gongsunzan: "Mưu Công Tôn Toản",
	sb_gongsunzan_prefix: "Mưu",
	sbyicong: "Nghĩa Tòng",
	sbyicong_info: "Kỹ năng tích lũy (2/4). ①Mỗi vòng bắt đầu, bạn có thể tiêu hao bất kỳ điểm tích lũy nào và chọn một mục: ⒈ Khoảng cách của bạn đến nhân vật khác trong vòng này -1, khiến hệ thống chọn X lá 【Sát】 trong chồng bài; ⒉ Khoảng cách từ nhân vật khác đến bạn trong vòng này +1, khiến hệ thống chọn X lá 【閃】 trong chồng bài (X là điểm tích lũy bạn tiêu hao). Sau đó nếu số lượng “Hộ” của bạn nhỏ hơn 4, bạn đem lá bài hệ thống chọn đặt lên thẻ võ tướng, gọi là “Hộ”. ②Bạn có thể sử dụng hoặc đánh ra “Hộ” như bài tay.",
	sbqiaomeng: "Kiêu Mãnh",
	sbqiaomeng_info: "Khi bạn sử dụng 【Sát】 gây sát thương, nếu bạn có 〖Nghĩa Tòng〗, bạn có thể chọn một mục: ⒈ Bỏ một lá bài trong vùng của nhân vật bị thương và rút một lá bài; ⒉ Nhận được 3 điểm tích lũy.",
	sb_luxun: "Mưu Lục Tốn",
	sbqianxun: "Khiêm Tốn",
	sbqianxun_info: "Khi một lá bài Cẩm nang có hiệu lực đối với bạn, nếu tên bài này chưa được ghi nhớ và bạn không phải là người sử dụng, thì bạn ghi nhớ nó, sau đó có thể đặt tối đa X lá bài lên thẻ võ tướng của bạn, nhận lại khi kết thúc lượt này (X là số lượng tên bài ghi nhớ của “Khiêm Tốn” và tối đa là 5). Khi bắt đầu giai đoạn ra bài, bạn có thể loại bỏ một tên bài đã ghi nhớ, nếu là Cẩm nang thường thì có thể xem như sử dụng lá bài này.",
	sblianying: "Liên Doanh",
	sblianying_info: "Khi kết thúc lượt của nhân vật khác, bạn có thể xem X lá trên cùng của chồng bài, sau đó đem những lá bài này giao cho nhân vật bất kỳ (X là số lượng bài bạn đã mất trong lượt này + 1, tối đa là 5).",
	sb_jiaxu: "Mưu Giả Hủ",
	sb_jiaxu_prefix: "Mưu",
	sbwansha: "Hoàn Sát",
	sbwansha_info: "①Trong lượt của bạn, nhân vật khác không trong trạng thái hấp hối không thể sử dụng 【Đào】. ②Mỗi vòng giới hạn hai lần, khi một nhân vật vào trạng thái hấp hối, bạn có thể xem bài tay của người đó và chọn từ không đến ba lá bài trong đó (người khác không nhìn thấy), sau đó người đó chọn một mục: 1. Bạn đem những lá bài này phân phối cho bất kỳ nhân vật nào không phải người đó; 2. Người đó bỏ đi những lá bài khác ngoài những lá bài này.",
	sbwansha_rewrite: "Hoàn Sát-Cải",
	sbwansha_rewrite_info: "①Trong lượt của bạn, nhân vật khác không trong trạng thái hấp hối không thể sử dụng 【Đào】. ②Mỗi vòng giới hạn hai lần, khi một nhân vật vào trạng thái hấp hối, bạn có thể xem bài tay của người đó và chọn trong vùng của người đó từ không đến ba lá bài (người khác không nhìn thấy), sau đó người đó chọn một mục: 1. Bạn đem những lá bài này phân phối cho bất kỳ nhân vật nào không phải người đó; 2. Người đó bỏ đi những lá bài khác ngoài những lá bài này.",
	sbluanwu: "Loạn Võ",
	sbluanwu_info: "Kỹ năng giới hạn, giai đoạn ra bài, bạn có thể khiến tất cả các nhân vật khác lần lượt chọn một mục: ① Đối với một nhân vật khác có khoảng cách gần nhất (hoặc một trong số đó) sử dụng một lá 【Sát】; ② Mất 1 điểm thể lực. Sau khi một nhân vật vì thế mà mất thể lực, bạn có thể sửa đổi 〖Hoàn Sát〗 hoặc 〖Duy Mạc〗.",
	sbweimu: "Duy Mạc",
	sbweimu_info: "Kỹ năng khóa. Khi bạn trở thành mục tiêu của lá Cẩm nang màu đen, hủy bỏ nó.",
	sbweimu_rewrite: "Duy Mạc-Cải",
	sbweimu_rewrite_info: "Kỹ năng khóa. ①Khi bạn trở thành mục tiêu của lá Cẩm nang màu đen, hủy bỏ nó. ②Khi bắt đầu mỗi vòng, bạn từ chồng bài bỏ ngẫu nhiên nhận được một lá Cẩm nang màu đen hoặc bài trang bị phòng cụ.",
	sb_zhugejin: "Mưu Chư Cát Cẩn",
	sb_zhugejin_prefix: "Mưu",
	sbhuanshi: "Hoãn Thích",
	sbhuanshi_info: "Trước khi lá bài phán xét của một nhân vật có hiệu lực, bạn có thể xem một lá trên cùng của chồng bài, sau đó có thể dùng lá bài này thay thế nó hoặc dùng một lá bài tay thay thế nó.",
	sbhuanshi_tag: "Đỉnh chồng bài",
	sbhongyuan: "Hoằng Viện",
	sbhongyuan_info: "Kỹ năng tích lũy (1/3). Khi bạn nhận được một lúc ít nhất hai lá bài, có thể tiêu hao 1 điểm tích lũy và khiến tối đa hai nhân vật mỗi người rút một lá bài; khi một nhân vật khác mất đi một lúc ít nhất hai lá bài, bạn có thể tiêu hao 1 điểm tích lũy khiến người đó rút hai lá bài.",
	sbmingzhe: "Minh Triết",
	sbmingzhe_info: "Kỹ năng khóa, mỗi vòng giới hạn hai lần, khi bạn mất bài ngoài lượt, bạn chọn một nhân vật: nếu người đó có kỹ năng tích lũy, người đó nhận được 1 điểm tích lũy; nếu trong số bài bạn mất có lá bài phi cơ bản, người đó rút hai lá bài.",
	sb_guojia: "Mưu Quách Gia",
	sb_guojia_prefix: "Mưu",
	sbtiandu: "Thiên Đố",
	sbtiandu_info: "Kỹ năng chuyển đổi, khi bắt đầu giai đoạn ra bài, Dương: Bạn có thể bỏ hai lá bài tay, sau đó xem như sử dụng một lá Cẩm nang thường; Âm: Bạn tiến hành phán xét và nhận lá bài phán xét, sau đó nếu kết quả phán xét cùng hoa sắc với lá bài bạn đã bỏ nhờ 〖Thiên Đố〗 trong ván đấu này, bạn chịu 1 điểm sát thương không nguồn.",
	sbyiji: "Di Kế",
	sbyiji_info: "Khi bạn chịu sát thương, bạn có thể rút hai lá bài, sau đó bạn có thể giao tối đa số lượng bài tay tương đương cho bất kỳ nhân vật nào khác. Khi bạn lần đầu vào trạng thái hấp hối mỗi vòng, bạn có thể rút hai lá bài, sau đó bạn có thể giao tối đa số lượng bài tương đương cho bất kỳ nhân vật nào khác.",
	sbyiji_info_identity: "Khi bạn chịu sát thương, bạn có thể rút hai lá bài, sau đó bạn có thể giao những lá bài này cho bất kỳ nhân vật nào khác. Khi bạn lần đầu vào trạng thái hấp hối mỗi vòng, bạn có thể rút một lá bài, sau đó bạn có thể giao những lá bài này cho bất kỳ nhân vật nào khác.",
	sbyiji_info_doudizhu: "Khi bạn chịu sát thương, bạn có thể rút hai lá bài, sau đó bạn có thể giao tối đa số lượng bài tay tương đương cho bất kỳ nhân vật nào khác. Khi bạn lần đầu vào trạng thái hấp hối mỗi vòng, bạn có thể rút một lá bài, sau đó bạn có thể giao những lá bài này cho bất kỳ nhân vật nào khác.",
	sb_zhangliao: "Mưu Trương Liêu",
	sb_zhangliao_prefix: "Mưu",
	sbtuxi: "Đột Kích",
	sbtuxi_info: "Trong lượt của bạn giới hạn hai lần, khi bạn không phải vì kỹ năng này mà nhận được bài, bạn có thể đem bất kỳ số lượng bài nào trong đó đặt vào chồng bài bỏ, sau đó nhận tối đa X nhân vật khác mỗi người một lá bài tay (X là số bài bạn đã đặt vào chồng bài bỏ theo cách này).",
	sbdengfeng: "Đăng Phong",
	sbdengfeng_info: `Giai đoạn chuẩn bị, bạn có thể chọn một nhân vật khác và chọn một mục: ① Khiến người đó nhận tối đa hai lá bài trong vùng trang bị của mình. ② Bạn nhận một lá 【Sát】 trong chồng bài. ③ ${get.poptip("rule_beishui")}: Bạn mất 1 điểm thể lực.`,
	sb_guohuai: "Mưu Quách Hoài",
	sb_guohuai_prefix: "Mưu",
	sbjingce: "Tinh Sách",
	sbjingce_info: "Kỹ năng khóa, khi bắt đầu lượt, nếu trên thẻ võ tướng của bạn không có bài “Tinh Sách”, thì bạn xóa ghi nhớ dự đoán chưa được xác thực, sau đó đem ba lá trên cùng của chồng bài đặt lên thẻ võ tướng của bạn, gọi là bài “Tinh Sách”. Khi kết thúc lượt, bạn dự đoán nhân vật sẽ nhận được những lá bài “Tinh Sách” này (hoặc dự đoán những lá bài “Tinh Sách” này không bị bất kỳ nhân vật nào nhận được), sau đó dựa theo thứ tự dự đoán đem những lá bài này lần lượt đặt thành lá thứ ba/sáu/chín trên cùng của chồng bài (nếu số bài còn lại trong chồng bài không đủ, thì đem những lá bài không thể đạt tới đặt vào đáy chồng bài theo thứ tự dự đoán). Nếu bạn dự đoán đúng, thì bạn lần lượt rút 1/2/3 lá bài.",
	sb_xiahouyuan: "Mưu Hạ Hầu Uyên",
	sb_xiahouyuan_prefix: "Mưu",
	sbshensu: "Thần Tốc",
	sbshensu_info: "Khi bắt đầu lượt, bạn có thể chọn và thực hiện bất kỳ mục nào sau đây: ① Nhảy qua giai đoạn phán xét và giai đoạn rút bài; ② Nhảy qua giai đoạn rút bài và giai đoạn ra bài; ③ Nhảy qua giai đoạn ra bài và giai đoạn bỏ bài. Mỗi khi bạn chọn một mục, xem như sử dụng một lá 【Sát】 không hạn chế khoảng cách (những lá 【Sát】 sử dụng liên tiếp không thể chỉ định cùng một mục tiêu; nếu mục tương ứng bao hàm giai đoạn ra bài, thì lá 【Sát】 này không thể bị phản hồi). Nếu các mục bạn chọn bao hàm giai đoạn lặp lại, thì bạn lật mặt thẻ võ tướng.",
	sbzhengzi: "Chỉnh Ty",
	sbzhengzi_info: "Khi kết thúc lượt, nếu sát thương bạn gây ra trong lượt này không ít hơn trị số thể lực của bạn, thì bạn có thể hồi 1 điểm thể lực và lật ngửa lại thẻ võ tướng.",
	sb_lvbu: "Mưu Lã Bố",
	sb_lvbu_prefix: "Mưu",
	sbwushuang: "Vô Song",
	sbwushuang_info: "Kỹ năng khóa. ①【Sát】 bạn sử dụng cần hai lá 【閃】 mới có thể triệt tiêu; nhân vật đấu điểm 【Quyết Đấu】 với bạn mỗi lần cần đánh ra hai lá 【Sát】. ②Mỗi lượt giới hạn hai lần, khi bạn sử dụng 【Sát】 hoặc 【Quyết Đấu】 gây sát thương, nếu nhân vật bị thương chưa từng sử dụng hoặc đánh ra 【Sát】 hoặc 【閃】 để phản hồi lá bài này, thì sát thương này +1.",
	sbliyu: "Lợi Ngự",
	sbliyu_info: `Sau khi bạn sử dụng 【Sát】 gây sát thương cho một nhân vật khác, bạn có thể nhận tối đa số lượng bài trong vùng của người đó tương đương với trị số sát thương, sau đó người đó rút số lượng bài tương đương. Nếu bạn cùng người đó vì thế mà đã nhận được toàn bộ các loại bài, người đó chọn một mục: ① Bạn xem như đối với một nhân vật khác do người đó chỉ định sử dụng một lá 【Quyết Đấu】; ② Người đó nhận được 〖Vô Song〗 cho đến khi kết thúc lượt của người đó.`,
	sb_zhuran: "Mưu Chu Nhiên",
	sb_zhuran_prefix: "Mưu",
	sbzhenwei: "Trấn Vi",
	sbzhenwei_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể chọn một nhân vật khác, cùng người đó đồng thời chọn có bỏ bất kỳ số lượng bài nào hay không. Sau đó bạn có thể chọn thực hiện tối đa X mục (X là số lượng điều kiện mà số bài bạn bỏ so với số bài người đó bỏ không nhỏ hơn: 1. Số bài; 2. Số hoa sắc): 1. Gây cho người đó 1 điểm sát thương; 2. Rút ba lá bài.",
	sbheyuan: "Hợp Viện",
	sbheyuan_info: `Giai đoạn kết thúc, bạn có thể chọn một nhân vật bị thương mà kỹ năng này chưa từng chọn và bỏ X lá bài (X là số bài bạn đã bỏ khi phát động 〖Trấn Vi〗 lần trước), khiến người đó thực hiện mục cuối cùng của 〖Trấn Vi〗 đã thực hiện, và sau đó khi bạn đối với nhân vật khác ngoài người đó phát động 〖Trấn Vi〗, nhân vật đó có thể đồng thời bỏ bài (những lá bài này khi so sánh điều kiện “Trấn Vi” được tính là bài do bạn bỏ).`,
};

export default translates;
