import { lib, game, ui, get, ai, _status } from "noname";

const translates = {
	```plaintext
	clan_wuxian_prefix: "Tộc",
	clan_wuban_prefix: "Tộc",
	clan_xunshu_prefix: "Tộc",
	clan_xunchen_prefix: "Tộc",
	clan_xuncai_prefix: "Tộc",
	clan_xuncan_prefix: "Tộc",
	clan_hanshao_prefix: "Tộc",
	clan_hanrong_prefix: "Tộc",
	clan_wukuang_prefix: "Tộc",
	clan_wangling_prefix: "Tộc",
	clan_zhongyan_prefix: "Tộc",
	clan_wangyun_prefix: "Tộc",
	clan_wanghun_prefix: "Tộc",
	clan_zhonghui_prefix: "Tộc",
	clan_zhongyu_prefix: "Tộc",
	clan_wanglun_prefix: "Tộc",
	clan_xunyou_prefix: "Tộc",
	clan_wuqiao_prefix: "Tộc",
	clan_wangshen_prefix: "Tộc",

	clan_wangshen: "Tộc Vương Thẩm",
	clananran: "Ngạn Nhiên",
	clananran_info: "Khi bắt đầu giai đoạn Xuất Bài hoặc sau khi bạn chịu sát thương, bạn có thể chọn một hạng mục: ① Bốc X lá bài; ② Khiến tối đa X nhân vật mỗi người bốc một lá bài. Nhân vật nhận được bài theo cách này, lá bài tiếp theo sử dụng trong lượt này không thể là những lá bài này. (X là số lần kỹ năng này phát động và tối đa là 4)",
	clangaobian: "Cáo Biến",
	clangaobian_info: "Kỹ năng khóa, khi kết thúc lượt của nhân vật khác, nếu trong lượt này chỉ có một nhân vật bị thương, thì khiến người đó chọn một: ① Sử dụng một 【Giết】 đã vào bộ bài bỏ trong lượt này; ② Mất 1 điểm thể lực.",
	clan_wuxian: "Tộc Ngô Hiến",
	clanyirong: "Di Vinh",
	clanyirong_info: "Giai đoạn Xuất Bài giới hạn hai lần. Nếu số bài trên tay bạn: nhỏ hơn X, thì bạn có thể bốc bài lên X lá, sau đó X-1; lớn hơn X, thì bạn có thể bỏ bài xuống X lá, sau đó X+1. (X là giới hạn bài trên tay của bạn)",
	clanguixiang: "Quý Tướng",
	clanguixiang_info: "Kỹ năng khóa. Trước khi bắt đầu giai đoạn thứ X trong lượt của bạn (X là giới hạn bài trên tay của bạn), nếu giai đoạn này không phải là giai đoạn Xuất Bài, thì bạn kết thúc giai đoạn này, thay vào đó thực hiện một giai đoạn Xuất Bài.",
	clanmuyin: "Mục Âm",
	clanmuyin_info: "Kỹ năng tộc. Khi bắt đầu lượt, bạn có thể chọn một nhân vật Trần Lưu Ngô Thị có giới hạn bài trên tay không phải là nhiều nhất bàn. Giới hạn bài trên tay của nhân vật đó +1.",
	chenliuwushi: "Trần Lưu · Ngô Thị",
	clan_wuban: "Tộc Ngô Ban",
	clanzhanding: "Trảm Đinh",
	clanzhanding_info: "Bạn có thể dùng một số lá bài bất kỳ xem như 【Giết】 và khiến giới hạn bài trên tay của bạn -1. Sau khi 【Giết】 bạn dùng theo cách này kết toán xong, nếu bạn đã gây sát thương vì 【Giết】 này, thì bạn bốc bài lên đến giới hạn bài trên tay, nếu không thì bạn khiến 【Giết】 này không tính vào giới hạn số lần.",
	clan_xunshu: "Tộc Tuân Thục",
	clanshenjun: "Thần Quân",
	clanshenjun_info: "Khi một nhân vật sử dụng 【Giết】 hoặc bài chú thông thường, nếu trong tay bạn có bài có tên bài đó, bạn tiết lộ chúng, và những lá bài này gọi là “Thần Quân”. Sau đó khi giai đoạn này kết thúc, bạn có thể dùng số lá bài bằng với số “Thần Quân” của bạn xem như một lá bài “Thần Quân” để sử dụng.",
	clanbalong: "Bát Long",
	clanbalong_info: "Kỹ năng khóa. Khi trong một lượt, lần đầu tiên bạn {hồi phục thể lực hoặc chịu sát thương hoặc mất thể lực}, nếu loại bài có số lượng nhiều nhất duy nhất trên tay bạn là bài chú, bạn tiết lộ tất cả bài trên tay và bốc lên số lượng bằng số nhân vật.",
	clandaojie: "Đạo Tiết",
	clandaojie_info: "Kỹ năng tộc, kỹ năng khóa. Sau khi bạn sử dụng bài chú thông thường không phải loại sát thương lần đầu tiên mỗi lượt, bạn phải mất một kỹ năng khóa hoặc mất 1 điểm thể lực, khiến một nhân vật Dĩnh Xuyên Tuân Thị nhận được tất cả bài thực thể tương ứng với bài này.",
	clan_xuncai: "Tộc Tuân Thái",
	clanlieshi: "Liệt Thệ",
	clanlieshi_info: "Giai đoạn Xuất Bài, bạn có thể chọn một hạng mục: 1. Phế bỏ khu vực Phán Định và chịu 1 điểm sát thương Hỏa do bạn gây ra; 2. Bỏ tất cả 【Tránh】; 3. Bỏ tất cả 【Giết】. Sau đó khiến một nhân vật khác chọn một hạng mục từ những hạng mục bạn chưa chọn.",
	clandianzhan: "Điểm Chiến",
	clandianzhan_info: "Kỹ năng khóa. Sau khi bạn sử dụng một lá bài có một hoa lần đầu tiên mỗi vòng: nếu số mục tiêu của bài này là 1 và mục tiêu chưa bị liên hoàn, bạn liên hoàn mục tiêu của bài này; nếu bạn có bài trên tay có hoa này, bạn tái luyện những lá bài này. Sau khi thực hiện cả hai, bạn bốc một lá bài.",
	clanhuanyin: "Hoàn Âm",
	clanhuanyin_info: "Kỹ năng khóa. Khi bạn vào trạng thái hấp hối, bổ sung bài trên tay lên bốn lá.",
	clan_xunchen: "Tộc Tuân Thầm",
	clansankuang: "Tam Khoảng",
	clansankuang_info: "Kỹ năng khóa. Sau khi bạn sử dụng một loại bài lần đầu tiên mỗi vòng, bạn khiến một nhân vật khác đưa cho bạn ít nhất X lá bài, sau đó nhận được từ khu vực Trang Bị hoặc khu vực Xử Lý tất cả bài thực thể tương ứng với bài bạn đã sử dụng (X là số điều kiện sau mà người đó đáp ứng: trên bàn có bài, đã bị thương, thể lực nhỏ hơn số bài trên tay).",
	clanbeishi: "Ty Thế",
	clanbeishi_info: "Kỹ năng khóa. Khi một nhân vật mất lá bài cuối cùng trên tay, nếu người đó là nhân vật mục tiêu đầu tiên bạn phát động 【Tam Khoảng】, bạn hồi phục 1 điểm thể lực.",
	clan_xuncan: "Tộc Tuân Thái",
	clanyunshen: "Úy Thân",
	clanyunshen_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể khiến một nhân vật khác hồi phục 1 điểm thể lực, sau đó chọn một hạng mục: 1. Bạn xem như sử dụng một đòn 【Giết】 băng nhắm vào người đó; 2. Người đó xem như sử dụng một đòn 【Giết】 băng nhắm vào bạn.",
	clanshangshen: "Thương Thần",
	clanshangshen_info: "Sau khi một nhân vật chịu sát thương thuộc tính, nếu trong lượt này trước đó chưa có nhân vật nào hoặc đã chết chịu sát thương thuộc tính, bạn có thể thực hiện hiệu ứng 【Sấm Sét】 với nhân vật mục tiêu là bạn, sau đó người đó bốc bài lên bốn lá.",
	clanfenchai: "Phân Sai",
	clanfenchai_info: "Kỹ năng khóa. Nếu trong nhân vật mục tiêu khác giới mà bạn phát động kỹ năng lần đầu tiên: có nhân vật còn sống, lá bài phán định của bạn được xem là ♥; không có nhân vật còn sống, lá bài phán định của bạn được xem là ♠.",
	clan_hanshao: "Tộc Hàn Thiều",
	clanfangzhen: "Phóng Chẩn",
	clanfangzhen_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể liên hoàn một nhân vật và chọn một hạng mục: 1. Bốc hai lá bài, sau đó đưa cho người đó hai lá bài; 2. Khiến người đó hồi phục 1 điểm thể lực. Sau đó khi bắt đầu vòng thứ X của ván chơi, bạn mất 【Phóng Chẩn】 (X là số ghế của người đó).",
	clanliuju: "Lưu Câu",
	clanliuju_info: "Khi kết thúc giai đoạn Xuất Bài, bạn có thể thi điểm với một nhân vật A. Nhân vật thua có thể sử dụng một số lá bài bất kỳ không phải bài cơ bản trong số các lá bài dùng để thi điểm. Sau đó nếu khoảng cách từ bạn đến A hoặc từ A đến bạn thay đổi, bạn thiết lập lại 【Tuất Dân】.",
	clanxumin: "Tuất Dân",
	clanxumin_info: "Kỹ năng tộc, kỹ năng giới hạn. Bạn có thể dùng một lá bài xem như 【Ngũ Cốc Phong Đăng】 sử dụng cho một số lượng nhân vật khác bất kỳ.",
	clan_hanrong: "Tộc Hàn Dung",
	clanlianhe: "Liên Hòa",
	clanlianhe_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể liên hoàn hai nhân vật. Khi kết thúc giai đoạn Xuất Bài tiếp theo của chính các nhân vật này, nếu trong giai đoạn này người đó không bốc bài, người đó khiến bạn bốc X+1 lá bài hoặc đưa cho bạn X-1 lá bài (X là số bài người đó nhận được trong giai đoạn này và tối đa là 3).",
	clanhuanjia: "Hoãn Giáp",
	clanhuanjia_info: "Khi kết thúc giai đoạn Xuất Bài, bạn có thể thi điểm với một nhân vật. Nhân vật thắng có thể sử dụng một lá bài dùng để thi điểm. Sau đó nếu bài này: chưa gây sát thương, bạn nhận được lá bài thi điểm còn lại; đã gây sát thương, bạn mất một kỹ năng.",
	clan_wukuang: "Tộc Ngô Khuông",
	clanlianzhu: "Liên Tru",
	clanlianzhu_info: "Kỹ năng chuyển hóa. Mỗi lượt của mỗi nhân vật A, giai đoạn Xuất Bài giới hạn một lần. Dương: A có thể tái luyện một lá bài, sau đó bạn có thể tái luyện một lá bài. Nếu hai lá bài này cùng màu, thì giới hạn bài trên tay của bạn +1; Âm: A có thể khiến bạn chọn một nhân vật khác B nằm trong tầm tấn công của bạn hoặc A, sau đó A và bạn có thể lần lượt chọn có dùng một 【Giết】 nhắm vào B hay không. Nếu hai 【Giết】 này khác màu, thì giới hạn bài trên tay của bạn -1.",
	clan_wangling: "Tộc Vương Lăng",
	clanbolong: "Bác Long",
	clanbolong_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể khiến một nhân vật khác chọn một hạng mục: 1. Bạn đưa cho người đó một lá bài, sau đó xem như sử dụng một đòn 【Giết】 Lôi nhắm vào người đó; 2. Đưa cho bạn số lá bài bằng với số bài trên tay bạn, sau đó xem như sử dụng một 【Rượu】 nhắm vào bạn.",
	clanzhongliu: "Trung Lưu",
	clanzhongliu_info: "Kỹ năng tộc, kỹ năng khóa. Khi bạn sử dụng bài, nếu tất cả bài thực thể tương ứng với bài này không phải là bài trên tay của nhân vật Thái Nguyên Vương Thị, bạn thiết lập lại kỹ năng trên bài tướng.",
	clan_zhongyan: "Tộc Chung Diễm",
	clanguangu: "Quan Cốt",
	clanguangu_info: "Kỹ năng chuyển hóa, giai đoạn Xuất Bài giới hạn một lần. Dương: Bạn có thể xem tối đa bốn lá bài trên cùng bộ bài; Âm: Bạn có thể xem tối đa bốn lá bài trên tay của một nhân vật. Sau đó bạn có thể sử dụng một trong những lá bài đó.",
	clanxiaoyong: "Khiếu Vịnh",
	clanxiaoyong_info: "Kỹ năng khóa. Khi bạn sử dụng bài có số chữ là X lần đầu tiên trong lượt, bạn thiết lập lại 【Quan Cốt】 (X là số lá bài bạn đã xem lần phát động 【Quan Cốt】 trước đó).",
	clanbaozu: "Bảo Tộc",
	clanbaozu_info: "Kỹ năng tộc, kỹ năng giới hạn. Khi một nhân vật Dĩnh Xuyên Chung Thị vào trạng thái hấp hối, bạn có thể khiến người đó bị liên hoàn và hồi phục 1 điểm thể lực.",
	clan_wangyun: "Tộc Vương Doãn",
	clanjiexuan: "Giải Huyền",
	clanjiexuan_info: "Kỹ năng giới hạn, kỹ năng chuyển hóa. Dương: Bạn có thể dùng một lá bài màu đỏ xem như 【Thuận Thủ Khiên Dương】; Âm: Bạn có thể dùng một lá bài màu đen xem như 【Quá Hà Sách Kiều】.",
	clanmingjie: "Minh Giới",
	clanmingjie_info: "Kỹ năng giới hạn. Giai đoạn Xuất Bài, bạn có thể chọn một nhân vật, sau đó bạn nhận được hiệu ứng dưới đây: ① Khi bạn dùng bài, bạn có thể chỉ định người đó làm mục tiêu bổ sung cho đến khi kết thúc lượt tiếp theo của người đó. ② Khi kết thúc lượt tiếp theo của người đó, bạn có thể sử dụng các lá bài màu đen bích và các lá bài đã bị vô hiệu hóa đã sử dụng trong lượt này.",
	clan_wanghun: "Tộc Vương Hồn",
	clanfuxun: "Phủ Tuần",
	clanfuxun_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể nhận hoặc đưa cho một nhân vật khác một lá bài trên tay, sau đó nếu số bài trên tay người đó bằng với bạn và trong giai đoạn này chỉ nhận hoặc mất bài bằng cách này, bạn có thể dùng một lá bài xem như bài cơ bản bất kỳ.",
	clanchenya: "Trầm Nhã",
	clanchenya_info: "Khi một nhân vật phát động kỹ năng có cụm từ “giai đoạn Xuất Bài giới hạn một lần”, bạn có thể khiến người đó tái luyện một số lá bài bất kỳ có số chữ trong tên bài là X (X là số bài trên tay của người đó).",
	clan_zhonghui: "Tộc Chung Hội",
	clanyuzhi: "Vu Chí",
	clanyuzhi_info: "Kỹ năng khóa. ① Khi bắt đầu mỗi vòng, bạn tiết lộ một lá bài trên tay, sau đó bốc X lá bài (X là số chữ trong tên của lá bài này). ② Khi kết thúc mỗi vòng, bạn bỏ lá bài đã tiết lộ vì 【Vu Chí】 trong vòng này, sau đó nếu số bài bạn dùng trong vòng này hoặc số bài bạn bốc vì 【Vu Chí】 ở vòng trước nhỏ hơn số bài bạn bốc vì 【Vu Chí】 trong vòng này, bạn chịu 1 điểm sát thương Lôi hoặc mất 【Bảo Tộc】.",
	clanxieshu: "Hiệp Thuật",
	clanxieshu_info: "Sau khi bạn gây ra hoặc chịu sát thương do bài, bạn có thể liên hoàn bài tướng và bỏ Y lá bài, sau đó bốc số lá bài bằng thể lực đã mất của bạn (Y là số chữ trong tên của bài này). Nếu trong lượt này có nhân vật đã vào trạng thái hấp hối, thì 【Hiệp Thuật】 mất hiệu lực trong lượt này.",
	clan_zhongyu: "Tộc Chung Dục",
	clanjiejian: "Tiệp Gián",
	clanjiejian_info: "Khi bạn sử dụng lá bài thứ X trong một lượt và chỉ định mục tiêu đầu tiên xong, nếu bài này không phải là bài Trang Bị, thì bạn có thể khiến một nhân vật mục tiêu bốc X lá bài. (X là số chữ trong tên của bài này)",
	clanhuanghan: "Hoàng Hãn",
	clanhuanghan_info: "Sau khi bạn chịu sát thương do bài gây ra, bạn có thể bốc X lá bài và bỏ Y lá bài (X là số chữ trong tên của bài này, Y là thể lực đã mất của bạn), sau đó nếu lần phát động kỹ năng này không phải là lần đầu tiên bạn phát động kỹ năng này trong lượt này, bạn thiết lập lại kỹ năng 【Bảo Tộc】.",
	clan_wanglun: "Tộc Vương Luân",
	clanqiuxin: "Cầu Tâm",
	clanqiuxin_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể khiến một nhân vật khác chọn một hạng mục: Sau khi 【Giết】 (1.) hoặc bài chú thông thường (2.) tiếp theo bạn sử dụng nhắm vào người đó kết toán xong, bạn xem như sử dụng một bài chú thông thường (1.) hoặc 【Giết】 (2.) nhắm vào người đó.",
	clanjianyuan: "Giản Viễn",
	clanjianyuan_info: "Khi một nhân vật phát động kỹ năng có cụm từ “giai đoạn Xuất Bài giới hạn một lần”, bạn có thể khiến người đó tái luyện một số lá bài bất kỳ có số chữ trong tên bài là X (X là số bài đã sử dụng của người đó trong giai đoạn này).",
	clan_xunyou: "Tộc Tuân Du",
	clanbaichu: "Bách Xuất",
	clanbaichu_new: "Tổ Hợp Mới",
	clanbaichu_trick: "Đã ghi nhận",
	clanbaichu_info: `Kỹ năng khóa, sau khi bạn sử dụng một lá bài kết toán xong, nếu bạn: chưa ghi nhận tổ hợp hoa và loại của bài này, thì bạn ghi nhận tổ hợp này và ghi nhận một tên bài chú thông thường, nếu không thì bạn nhận được kỹ năng ${get.poptip("qice")} trong vòng này; đã ghi nhận tên bài này, bạn hồi phục 1 điểm thể lực hoặc bốc một lá bài.`,
	clan_wuqiao: "Tộc Ngô Kiều",
	clanqiajue: "Khảo Quật",
	clanqiajue_info: "Khi bắt đầu giai đoạn Bốc Bài, bạn có thể bỏ một lá bài màu đen. Nếu làm vậy, khi kết thúc giai đoạn này, bạn tiết lộ bài trên tay, nếu tổng số điểm của những lá bài này lớn hơn 30, giới hạn bài trên tay của bạn -2, nếu không thì bạn thực hiện một giai đoạn Bốc Bài bổ sung.",
	clan_wangguang: "Tộc Vương Quảng",
	clan_wangguang_prefix: "Tộc",
	clanlilun: "Ly Luận",
	clanlilun_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể tái luyện hai lá bài có cùng tên bài (không thể là bài có tên bạn đã tái luyện bằng cách này trong lượt này), sau đó sử dụng một trong hai lá bài đó.",
	clanjianji: "Kiến Cơ",
	clanjianji_info: "Kỹ năng giới hạn, khi kết thúc lượt của một nhân vật, nếu người ngồi trên và người ngồi dưới của người đó đều không trong lượt này: sử dụng bài, thì bạn có thể cùng người đó mỗi người bốc một lá bài; từng là mục tiêu của bài, thì bạn có thể xem như sử dụng một 【Giết】.",
	clan_wangmingshan: "Tộc Vương Minh Sơn",
	clan_wangmingshan_prefix: "Tộc",
	clantanque: "Đàn Tước",
	clantanque_info: "Mỗi lượt giới hạn một lần. Khi bạn sử dụng bài kết toán xong, bạn có thể gây 1 điểm sát thương cho một nhân vật có thể lực hoặc số bài trên tay là X và không phải là 0 (X là chênh lệch điểm số giữa bài này và bài bạn đã sử dụng trước đó).",
	clanshengmo: "Thặng Mặc",
	clanshengmo_info: "Mỗi vòng giới hạn một lần, khi bạn cần sử dụng bài cơ bản, bạn có thể nhận được một lá bài đã vào bộ bài bỏ trong lượt này (mỗi điểm số giới hạn một lần), sau đó nếu điểm số của lá bài này không phải là lớn nhất và không phải là nhỏ nhất trong số những lá bài đó, bạn xem như sử dụng bài cơ bản chưa dùng bằng cách này.",
	clan_zhongyao: "Tộc Chung Do",
	clan_zhongyao_prefix: "Tộc",
	clanchengqi: "Thừa Khải",
	clanchengqi_info: "Bạn có thể dùng ít nhất hai lá bài trên tay xem như bài cơ bản hoặc bài chú thông thường chưa được sử dụng trong lượt này, và số chữ trong tên bài bạn chuyển hóa theo cách này không được lớn hơn tổng số chữ trong tên của tất cả bài thực thể được chuyển hóa theo cách này, nếu số chữ trong tên bài bạn chuyển hóa theo cách này bằng tổng số chữ trong tên của tất cả bài thực thể được chuyển hóa theo cách này, thì khi bạn sử dụng bài này có thể khiến một nhân vật bốc một lá bài.",
	clanjieli: "Giới Lệ",
	clanjieli_info: "Giai đoạn Kết Thúc, bạn có thể chọn một nhân vật, bạn xem những lá bài có số chữ trong tên nhiều nhất trên tay người đó và X lá bài trên cùng bộ bài, sau đó bạn có thể đổi chỗ bất kỳ lá bài nào trong số đó (X là giá trị lớn nhất trong số chữ trong tên của các lá bài bạn đã sử dụng trong lượt này).",
	clan_wangchang: "Tộc Vương Xưởng",
	clan_wangchang_prefix: "Tộc",
	clankaiji: "Khai Tế",
	clankaiji_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể khiến một nhân vật chưa được chọn bằng cách này trong vòng này bỏ một lá bài trên tay bạn, sau đó bạn có thể sử dụng lá bài này đang ở trong bộ bài bỏ, nếu làm vậy, bạn bốc một lá bài.",
	clan_wuyi: "Tộc Ngô Ý",
	clan_wuyi_prefix: "Tộc",
	clangaojin: "Cao Kính",
	clangaojin_info: "Khi bạn sử dụng lá bài thứ X trong một lượt (X là giới hạn bài trên tay của bạn), bạn có thể khiến lá bài tiếp theo bạn sử dụng trong lượt này không bị giới hạn khoảng cách và số lần, sau đó bạn có thể chọn tối đa hai hạng mục: 1. Giới hạn bài trên tay -1; 2. Bốc số lá bài bằng giá trị thể lực; 3. Giới hạn bài trên tay +1; nếu các hạng mục liền kề, bạn bỏ × lá bài.",
	old_clangaojin: "Cao Kính",
	old_clangaojin_info: "Kỹ năng khóa, khi bắt đầu ván chơi, khoảng cách bạn tính với các nhân vật khác -X, sau khi khoảng cách bạn tính với các nhân vật khác thay đổi, bạn bốc một lá bài (X là giới hạn bài trên tay của bạn).",
	old_clangaojin_append: `<span style="font-family: yuanli"><li><span style="text-decoration: line-through;">Bản vá lỗi×</span> Lưu ý:<br>Thời điểm sau khi khoảng cách thay đổi theo đúng nghĩa không thể thực hiện được trong khung chương trình Vô Danh Sát, xin đừng phản hồi về việc kỹ năng này không phát động trong một số trường hợp khoảng cách thay đổi.</span>`,
	clanpoxi: "Phá Tập",
	clanpoxi_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể bỏ một lá bài của một nhân vật có khoảng cách không lớn hơn 1, nếu lá bài bỏ là bài Trang Bị / bài Cơ Bản, thì bạn có thể dùng lá bài này xem như 【Giết】, và có thể khiến nhân vật mục tiêu không thể đáp trả 【Giết】 này, nếu gây sát thương bằng cách này thì khoảng cách bạn tính với các nhân vật khác +1.",
	clan_yangci: "Tộc Dương Tứ",
	clan_yangci_prefix: "Tộc",
	clanqieyi: "Thiết Nghị",
	clanqieyi_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể xem hai lá bài trên cùng bộ bài. Nếu làm vậy, trong lượt này, sau khi mỗi lá bài đầu tiên có mỗi hoa bạn sử dụng kết toán xong, tiết lộ một lá bài trên cùng bộ bài, nếu hai lá bài này cùng màu hoặc cùng loại: giống nhau, bạn nhận được lá bài đã tiết lộ; đều khác nhau, bạn đặt một lá bài lên đỉnh bộ bài.",
	clanjianzhi: "Gián Trực",
	clanjianzhi_info: "Kỹ năng khóa, giai đoạn Kết Thúc, bạn tiến hành phán định tối đa X lần (X là số lần phát động 【Thiết Nghị】 của bạn trong lượt này). Bạn phân phối các lá bài phán định có cùng hoa với hoa bạn đã sử dụng trong lượt này cho bất kỳ nhân vật nào; nếu trong lá bài phán định có hoa bạn chưa sử dụng trong lượt này, bạn chịu 1 điểm sát thương Lôi không rõ nguồn gốc.",
	clanquhuo: "Khứ Hoặc",
	clanquhuo_info: "Kỹ năng tộc, sau lần đầu tiên trong mỗi lượt bạn mất 【Rượu】 hoặc bài Trang Bị trên tay không phải do sử dụng, đánh ra hay bỏ bài, bạn có thể khiến một nhân vật Hoằng Nông Dương Thị hồi phục 1 điểm thể lực.",
	clan_yangxiu: "Tộc Dương Tu",
	clan_yangxiu_prefix: "Tộc",
	clanjiewu: "Tiệp Ngộ",
	clanjiewu_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể khiến bài trên tay của một nhân vật luôn hiển thị với bạn trong giai đoạn này. Sau đó, sau khi bạn dùng bài chỉ định nhân vật khác làm mục tiêu trong giai đoạn này, bạn có thể tiết lộ một lá bài trên tay của nhân vật 「Tiệp Ngộ」, nếu: hai lá bài cùng hoa, bạn bốc một lá bài, nếu số lần lá bài này đã được tiết lộ bằng cách này trong lượt này lớn hơn 1, bạn đặt một lá bài của người có số bài nhiều hơn giữa bạn và người đó lên đỉnh bộ bài.",
	clangaoshi: "Cao Thị",
	clangaoshi_info: "Giai đoạn Kết Thúc, bạn có thể lần lượt lật ngửa các lá bài trên cùng bộ bài, cho đến khi bạn lật được tên bài bạn đã sử dụng trong lượt này, hoặc lật được ít nhất X lá bài (X là số lần bạn phát động 【Tiệp Ngộ】 trong lượt này), sau đó bạn có thể sử dụng các lá bài đã lật, nếu bạn đã sử dụng tất cả các lá bài đã lật vì điều này, bạn bốc hai lá bài.",
	clan_xunshuang: "Tộc Tuân Sảng",
	clan_xunshuang_prefix: "Tộc",
	clanyangji: "Dương Tật",
	clanyangji_info: "Giai đoạn Chuẩn Bị, hoặc khi kết thúc giai đoạn mà giá trị thể lực của bạn đã thay đổi, bạn có thể sử dụng một lá bài. Nếu lá bài này không gây sát thương, bạn có thể dùng một lá bài màu đen bích xem như 【Lạc Bất Tư Thục】 sử dụng cho nhân vật của lượt hiện tại.",
	clandandao: "Đam Đạo",
	clandandao_info: "Kỹ năng khóa, sau lần phán định đầu tiên của bạn mỗi lượt, giới hạn bài trên tay của nhân vật trong lượt hiện tại +1.",
	clanqingli: "Thanh Lệ",
	clanqingli_info: "Kỹ năng khóa, khi kết thúc mỗi lượt, bạn bốc bài lên đến giới hạn bài trên tay (tối đa bốc đến 5).",
	clan_yangzhong: "Tộc Dương Chúng",
	clan_yangzhong_prefix: "Tộc",
	clanjuetu: "Tuyệt Đồ",
	clanjuetu_info: "Kỹ năng khóa, trước khi bắt đầu giai đoạn Bỏ Bài, bạn sửa đổi hiệu ứng được thực hiện trong giai đoạn này thành: giữ lại mỗi hoa một lá bài trên tay, đặt số bài trên tay còn lại vào bộ bài bỏ, sau đó bạn khiến một nhân vật bỏ một lá bài trên tay, nếu trong tay bạn không có lá bài có hoa này, bạn gây cho người đó 1 điểm sát thương.",
	clankudu: "Khổ Độ",
	clankudu_info: "Kỹ năng giới hạn, giai đoạn Kết Thúc, bạn có thể tái luyện hai lá bài, khiến một nhân vật khi kết thúc X lượt tiếp theo bốc một lá bài, sau lượt thứ X, người đó thực hiện một lượt bổ sung (X là chênh lệch điểm số của hai lá bài bạn tái luyện và tối đa là 5).",
	clan_yangbiao: "Tộc Dương Bưu",
	clan_yangbiao_prefix: "Tộc",
	clanjiannan: "Gian Nan",
	clanjiannan_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể bốc hai lá bài. Nếu làm vậy, sau khi một nhân vật trong giai đoạn này mất tất cả bài “Gian Nan” hoặc lá bài cuối cùng trên tay, nếu không có nhân vật nào trong trạng thái hấp hối, bạn khiến một nhân vật thực hiện một hạng mục: 1. Bỏ hai lá bài; 2. Bốc hai lá bài; 3. Tái luyện tất cả bài Trang Bị; 4. Đặt một lá bài chú lên đỉnh bộ bài hoặc mất 1 điểm thể lực (mỗi lượt mỗi hạng mục giới hạn một lần).",
	clanyichi: "Nghĩa Xích",
	clanyichi_info: "Giai đoạn Kết Thúc, bạn có thể thi điểm. Nếu bạn thắng, (những) nhân vật thua lần lượt thực hiện X hạng mục đầu tiên của 【Gian Nan】 (X là số lần bạn phát động 【Gian Nan】 trong lượt này).",
	clan_luji: "Tộc Lục Tích",
	clan_luji_prefix: "Tộc",
	clangailan: "Cai Lãm",
	clangailan_info: `Kỹ năng khóa, khi bắt đầu ván chơi, bạn xào bốn ${get.poptip("huntianyi")} vào bộ bài. Khi bắt đầu lượt, bạn đặt một ${get.poptip("huntianyi")} từ bộ bài hoặc bộ bài bỏ vào khu vực Trang Bị.`,
	huntianyi: "Hỗn Thiên Nghi",
	huntianyi_info: "Kỹ năng khóa, khi bạn mất bài này khỏi khu vực Trang Bị, ngẫu nhiên lấy từ bộ bài hai lá bài chú có cùng điểm số với bài này. Khi bạn chịu sát thương, hủy bỏ bài này và ngăn ngừa sát thương đó.",
	huntianyi_skill: "Hỗn Thiên Nghi",
	huntianyi_skill_info: "Kỹ năng khóa, khi bạn mất bài này khỏi khu vực Trang Bị, ngẫu nhiên lấy từ bộ bài hai lá bài chú có cùng điểm số với bài này. Khi bạn chịu sát thương, hủy bỏ bài này và ngăn ngừa sát thương đó.",
	clanfennu: "Phấn Nỗ",
	clanfennu_info: "① Khi bắt đầu giai đoạn Xuất Bài, bạn có thể khiến tối đa (bằng giá trị thể lực) nhân vật mỗi người bỏ một lá bài, đặt những lá bài này lên bài tướng của bạn, gọi là “Dật”. ② Nếu trên bài tướng của bạn có “Dật”, khi bạn dùng bài chỉ định mục tiêu thì ghi nhận điểm số của bài này. ③ Giai đoạn Chuẩn Bị, nếu điểm số đã ghi nhận lớn hơn tổng điểm số của “Dật”, bạn xóa bỏ ghi nhận và nhận được tất cả “Dật’.",
	clanzelie: "Trạch Liệt",
	clanzelie_info: "Kỹ năng tộc, sau khi nhân vật Ngô Quận Lục Thị mất tất cả bài trên khu vực của họ, bạn có thể khiến một nhân vật lần tới trong lượt này sau khi bốc bài / bỏ bài, người đó bốc một lá bài / bỏ một lá bài.",
	clan_lujing: "Tộc Lục Cảnh",
	clan_lujing_prefix: "Tộc",
	clantanfeng: "Thám Phong",
	clantanfeng_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể xem như sử dụng một đòn 【Giết】 không nhìn Giáp, không tính số lần nhắm vào một nhân vật. Nếu 【Giết】 này gây sát thương, bạn bốc X lá bài (X là chênh lệch số bài trong khu vực Trang Bị giữa bạn và người đó); nếu không thì người đó có thể xem như sử dụng một đòn 【Giết】 nhắm vào bạn.",
	clanjuewei: "Tuyệt Vi",
	clanjuewei_info: "Mỗi lượt giới hạn một lần, sau khi bạn dùng bài sát thương chỉ định mục tiêu, hoặc sau khi bạn trở thành mục tiêu của bài sát thương, bạn có thể chọn một hạng mục: 1. Tái luyện một lá bài Trang Bị, sau khi bài này kết toán xong xem như sử dụng bài này nhắm vào một nhân vật mục tiêu không phải là bạn; 2. Bỏ một lá bài Trang Bị, khiến bài này vô hiệu.",
	clan_hanfu: "Tộc Hàn Phúc",
	clan_hanfu_prefix: "Tộc",
	clanheta: "Hòa Tha",
	clanheta_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể vào trạng thái liên hoàn. Sau đó trong lượt này khi bạn dùng bài, có thể giải trừ trạng thái liên hoàn và thêm hoặc bớt một số lượng mục tiêu bất kỳ cho bài này (không giới hạn khoảng cách, chỉ có thể chọn những nhân vật bạn đã dùng bài nhắm vào trước đó trong lượt này).",
	clanyingxiang: "Nghênh Hương",
	clanyingxiang_info: `Khi kết thúc giai đoạn Xuất Bài, bạn có thể tuyên bố tên một bài cơ bản hoặc bài chú đơn mục tiêu và thi điểm, nhân vật thắng xem như sử dụng bài bạn đã tuyên bố. Nếu tên bài đã tuyên bố trùng với tên của bất kỳ lá bài dùng để thi điểm: giống tên, bạn xem như chưa phát động ${get.poptip("clanxumin")}; đều khác tên, bạn nhận được tất cả các lá bài dùng để thi điểm và mất một kỹ năng.`,
	clan_xunyu: "Tộc Tuân Úc",
	clan_xunyu_prefix: "Tộc",
	clandingan: "Định An",
	clandingan_info: "Kỹ năng khóa, sau khi bài có một tên bài được sử dụng lần thứ hai trong mỗi lượt, nếu trong lượt này chưa có nhân vật nào vào trạng thái hấp hối, bạn và một nhân vật không phải mục tiêu mỗi người bốc một lá bài (mỗi lượt mỗi nhân vật giới hạn một lần), sau đó bạn gây 1 điểm sát thương cho một nhân vật khác có số bài trên tay nhiều nhất, hoặc khiến người đó ngẫu nhiên bỏ bài có tên giống nhau nhiều nhất trên tay.",
	clanfuning: "Phủ Ninh",
	clanfuning_info: "Mỗi vòng, sau lần đầu tiên giá trị thể lực của bạn thay đổi, bạn có thể đưa ít nhất X lá bài cho một nhân vật khác (X là thể lực đã mất của bạn), nếu số bài bạn đưa ra: đều cùng màu, bạn hồi phục 1 điểm thể lực; số lượng lớn hơn số nhân vật đã chịu sát thương trong lượt này, bạn điều chỉnh bài trên tay lên bằng giới hạn thể lực.",
	clan_chenqun: "Tộc Trần Quần",
	clan_chenqun_prefix: "Tộc",
	clangezhi: "Cách Chế",
	clangezhi_info: "Mỗi lượt giới hạn một lần, sau khi bạn hoặc nhân vật trong phạm vi tấn công của bạn chịu sát thương, nếu nguồn gây sát thương không phải là bạn, bạn có thể bỏ một lá bài của bạn và một lá bài của nguồn gây sát thương, và có thể phân phối những lá bài này. Nếu loại của các lá bài bỏ vì điều này khác nhau, bạn và nguồn gây sát thương trong lượt này chỉ có thể sử dụng những loại bài này.",
	clanmingdian: "Minh Điển",
	clanmingdian_info: "Giai đoạn Xuất Bài hoặc sau khi bạn chịu sát thương, bạn có thể tái luyện một số lượng bài Cơ Bản bất kỳ (mỗi vòng mỗi tên bài giới hạn một lần). Nếu bạn tái luyện tên bài bạn đã sử dụng trong lượt này, bạn nhận được một lá bài Cơ Bản có tên chưa có trên tay.",
	clanshize: "Sĩ Tắc",
	clanshize_info: "Kỹ năng tộc, kỹ năng khóa, sau lần đầu tiên bài bạn dùng trong lượt bị đáp trả, bạn khiến một nhân vật Dĩnh Xuyên Trần Thị phạm vi tấn công +1, cho đến khi người đó chịu sát thương lần tiếp theo.",
	clan_chentai: "Tộc Trần Thái",
	clan_chentai_prefix: "Tộc",
	clanfenjian: "Phấn Kiếm",
	clanfenjian_info: "Mỗi hạng mục trong giai đoạn Xuất Bài giới hạn một lần, bạn có thể chọn một nhân vật có phạm vi tấn công: 1. Nhỏ hơn bạn; 2. Bằng bạn; 3. Lớn hơn bạn. Người đó phải bỏ một lá bài, nếu lá bài bỏ là 【Tránh】, bạn bốc một lá bài, nếu không thì phạm vi tấn công của bạn trong lượt này -1 (tối đa giảm xuống 0).",
	clandongxu: "Động Hư",
	clandongxu_info: "Kỹ năng chuyển hóa, Dương: Bạn có thể đặt một lá bài trong khu vực Trang Bị của bạn vào khu vực Trang Bị của nhân vật khác (thay thế trang bị cũ), xem như sử dụng một 【Giết】 nhắm vào người đó; Âm: Bạn có thể bốc bài lên X (X là phạm vi tấn công của bạn và tối đa là 5), xem như sử dụng một 【Tránh】.",
	clan_xunshi: "Tộc Tuân Thì",
	clan_xunshi_prefix: "Tộc",
	clanqingjue: "Thanh Tuyệt",
	clanqingjue_info: "Kỹ năng khóa, mỗi hoa trên tay bạn chỉ có một lá bài duy nhất không tính vào giới hạn bài trên tay. Sau lần đầu tiên giá trị thể lực của bạn thay đổi mỗi lượt, bạn bỏ những lá bài trên tay có số lượng hoa khác một một cách bất kỳ, và thực hiện một số lượng hạng mục tương ứng: 1. Đưa những lá bài này cho một nhân vật khác; 2. Nhận được mỗi lá bài một hoa chưa có trên tay.",
	clanxsyingxiang: "Oanh Hương",
	clanxsyingxiang_info: `Kỹ năng khóa, khi nhân vật khác nhận được bài của bạn, gọi bài này là bài “Oanh Hương”. Sau khi bài “Oanh Hương” được sử dụng, bạn và (các) nhân vật có bài “Oanh Hương” trên tay mỗi người bốc một lá bài. Nếu bài “Oanh Hương” bị mất không phải do sử dụng, bạn phát động một lần ${get.poptip("clanqingjue")} (mỗi vòng giới hạn một lần).`,
};

export default translates;
