const translates = {
	caocao: "Tào Tháo",
	hujia: "Hộ Giá",
	hujia_info: "Chủ Công Kỹ. Khi bạn cần sử dụng hoặc đánh ra một lá 【Né】, bạn có thể yêu cầu các tướng thế lực Ngụy khác chọn có muốn đánh ra một lá 【Né】 hay không. Nếu có tướng hưởng ứng, bạn được coi là đã sử dụng hoặc đánh ra một lá 【Né】.",
	jianxiong: "Gian Hùng",
	jianxiong_info: "Sau khi bạn nhận sát thương, bạn có thể lấy lá bài đã gây sát thương cho bạn.",

	simayi: "Tư Mã Ý",
	fankui: "Phản Hồi",
	fankui_info: "Sau khi bạn nhận sát thương, bạn có thể lấy một lá bài từ nguồn gây sát thương.",
	guicai: "Quỷ Tài",
	guicai_info: "Trước khi lá bài phán định của một tướng có hiệu lực, bạn có thể đánh ra một lá bài tay để thay thế.",
	guicai_info_guozhan: "Trước khi lá bài phán định của một tướng có hiệu lực, bạn có thể đánh ra một lá bài để thay thế.",

	xiahoudun: "Hạ Hầu Đôn",
	zhangliao: "Trương Liêu",
	xuzhu: "Hứa Chử",
	guojia: "Quách Gia",
	zhenji: "Chân Mật",
	liubei: "Lưu Bị",
	guanyu: "Quan Vũ",
	zhangfei: "Trương Phi",
	zhugeliang: "Gia Cát Lượng",
	zhaoyun: "Triệu Vân",
	machao: "Mã Siêu",
	huangyueying: "Hoàng Nguyệt Anh",
	sunquan: "Tôn Quyền",
	ganning: "Cam Ninh",
	lvmeng: "Lữ Mông",
	huanggai: "Hoàng Cái",
	zhouyu: "Chu Du",
	daqiao: "Đại Kiều",
	luxun: "Lục Tốn",
	sunshangxiang: "Tôn Thượng Hương",
	huatuo: "Hoa Đà",
	lvbu: "Lữ Bố",
	diaochan: "Điêu Thuyền",
	huaxiong: "Hoa Hùng",
	xf_yiji: "Y Tịch",
	re_yuanshu: "Viên Thuật",
	caozhang: "Tào Chương",

	ganglie: "Cương Liệt",
	tuxi: "Đột Tập",
	luoyi: "Lõa Y",
	luoyi2: "Lõa Y",
	tiandu: "Thiên Đố",
	yiji: "Di Kế",
	luoshen: "Lạc Thần",
	qingguo: "Khuynh Quốc",
	rende: "Nhân Đức",
	jijiang: "Kích Tướng",
	jijiang1: "Kích Tướng",
	jijiang2: "Kích Tướng",
	wusheng: "Vũ Thánh",
	paoxiao: "Bào Hiêu",
	guanxing: "Quan Tinh",
	kongcheng: "Không Thành",
	kongcheng1: "Không Thành",
	longdan: "Long Đảm",
	longdan1: "Long Đảm",
	longdan2: "Long Đảm",
	mashu: "Mã Thuật",
	feiying: "Phi Ảnh",
	tieji: "Thiết Kỵ",
	jizhi: "Tập Trí",
	qicai: "Kỳ Tài",
	zhiheng: "Chế Hoành",
	jiuyuan: "Cứu Viện",
	qixi: "Kỳ Tập",
	keji: "Khắc Kỷ",
	kurou: "Khổ Nhục",
	yingzi: "Anh Tư",
	fanjian: "Phản Gián",
	guose: "Quốc Sắc",
	liuli: "Lưu Ly",
	qianxun: "Khiêm Tốn",
	lianying: "Liên Doanh",
	xiaoji: "Hiêu Cơ",
	jieyin: "Kết Nhân",
	qingnang: "Thanh Nang",
	jijiu: "Cấp Cứu",
	wushuang: "Vô Song",
	wushuang1: "Vô Song",
	wushuang2: "Vô Song",
	lijian: "Ly Gián",
	biyue: "Bế Nguyệt",
	pileTop: "Đầu bài",
	pileBottom: "Đáy bài",
	ganglie_info: "Sau khi bạn nhận sát thương, bạn có thể phán định. Nếu kết quả không phải ♥, nguồn gây sát thương phải bỏ hai lá bài tay; nếu không, nhận 1 điểm sát thương từ bạn.",
	tuxi_info: "Trong giai đoạn rút bài, bạn có thể thay vào đó lấy mỗi người một lá bài tay từ tối đa hai tướng khác.",
	luoyi_info: "Trong giai đoạn rút bài, bạn có thể rút ít hơn một lá. Nếu làm vậy, khi bạn dùng 【Sát】 hoặc 【Quyết Đấu】 gây sát thương trong lượt này, sát thương +1.",
	tiandu_info: "Sau khi lá bài phán định của bạn có hiệu lực, bạn có thể lấy lá bài đó.",
	yiji_info: "Sau khi bạn nhận 1 điểm sát thương, bạn có thể xem hai lá bài trên đầu bài, rồi phân phát chúng cho bất kỳ tướng nào.",
	luoshen_info: "Trong giai đoạn chuẩn bị, bạn có thể phán định. Nếu kết quả là đen, bạn lấy lá phán định đó. Bạn có thể lặp lại quy trình này cho đến khi xuất hiện kết quả phán định đỏ.",
	luoshen_info_guozhan: "Trong giai đoạn chuẩn bị, bạn có thể phán định. Nếu kết quả là đen, có thể tiếp tục phán định cho đến khi xuất hiện lá phán định đỏ. Sau đó bạn lấy tất cả lá phán định đen. (Các lá có kết quả phán định đen không vào bỏ bài trong quá trình này.)",
	qingguo_info: "Bạn có thể dùng một lá bài tay đen như 【Né】.",
	rende_info: "Trong giai đoạn xuất bài, bạn có thể đưa bất kỳ số lá bài tay nào cho tướng khác. Khi bạn trao lá bài thứ hai trong một lượt theo cách này, bạn hồi 1 điểm máu.",
	jijiang_info: "Chủ Công Kỹ. Khi bạn cần sử dụng hoặc đánh ra 【Sát】, bạn có thể yêu cầu các tướng thế lực Thục khác lần lượt chọn có muốn đánh ra một lá 【Sát】 hay không. Nếu có tướng hưởng ứng, bạn được coi là đã sử dụng hoặc đánh ra 【Sát】 đó.",
	wusheng_info: "Bạn có thể dùng một lá bài đỏ như 【Sát】.",
	paoxiao_info: "Khóa Kỹ. Trong giai đoạn xuất bài, bạn không có giới hạn số lần dùng 【Sát】.",
	guanxing_info: "Trong giai đoạn chuẩn bị, bạn có thể xem X lá bài trên đầu bài, rồi đặt chúng theo thứ tự bất kỳ lên đầu hoặc xuống đáy bài. (X bằng số tướng còn sống, tối đa 5.)",
	kongcheng_info: "Khóa Kỹ. Khi bạn không có bài tay, bạn không thể là mục tiêu của 【Sát】 hay 【Quyết Đấu】.",
	longdan_info: "Bạn có thể dùng 【Sát】 như 【Né】, hoặc dùng 【Né】 như 【Sát】.",
	mashu_info: "Khóa Kỹ. Khi tính khoảng cách từ bạn đến tướng khác, -1.",
	feiying_info: "Khóa Kỹ. Khi tướng khác tính khoảng cách đến bạn, +1.",
	tieji_info: "Sau khi bạn dùng 【Sát】 chỉ định mục tiêu, bạn có thể phán định. Nếu kết quả là đỏ, 【Sát】 này không thể né tránh.",
	jizhi_info: "Khi bạn sử dụng lá bài Cẩm Nang thông thường, bạn có thể rút một lá bài.",
	qicai_info: "Khóa Kỹ. Khi bạn dùng bài Cẩm Nang, không có giới hạn khoảng cách.",
	zhiheng_info: "Giới hạn một lần trong giai đoạn xuất bài. Bạn có thể bỏ bất kỳ số lá bài nào, rồi rút số lượng bài tương đương.",
	jiuyuan_info: "Chủ Công Kỹ. Khóa Kỹ. Lá 【Đào】 mà tướng thế lực Ngô khác dùng cho bạn có hiệu quả hồi máu +1.",
	qixi_info: "Bạn có thể dùng một lá bài đen như 【Qua Sông Phá Cầu】.",
	keji_info: "Khi bắt đầu giai đoạn bỏ bài, nếu bạn không sử dụng hoặc đánh ra 【Sát】 nào trong giai đoạn xuất bài lượt này, bạn có thể bỏ qua giai đoạn này.",
	kurou_info: "Trong giai đoạn xuất bài, bạn có thể mất 1 điểm máu, rồi rút hai lá bài.",
	yingzi_info: "Trong giai đoạn rút bài, bạn có thể rút thêm một lá bài.",
	fanjian_info: "Giới hạn một lần trong giai đoạn xuất bài. Bạn có thể khiến một tướng chọn một chất bài, rồi tướng đó lấy một lá bài tay của bạn. Nếu chất bài tướng đó chọn khác với chất của lá nhận được, bạn gây 1 điểm sát thương cho tướng đó.",
	guose_info: "Bạn có thể dùng một lá rô (♦) như 【Lạc Bất Tư Thục】.",
	liuli_info: "Khi bạn là mục tiêu của 【Sát】, bạn có thể bỏ một lá bài và chuyển 【Sát】 này sang một tướng khác trong tầm tấn công (không thể là người dùng 【Sát】 đó).",
	qianxun_info: "Khóa Kỹ. Bạn không thể là mục tiêu của 【Thuận Thủ Khiên Dương】 và 【Lạc Bất Tư Thục】.",
	lianying_info: "Khi bạn mất lá bài tay cuối cùng, bạn có thể rút một lá bài.",
	xiaoji_info: "Sau khi bạn mất một lá trong vùng trang bị, bạn có thể rút hai lá bài.",
	jieyin_info: "Giới hạn một lần trong giai đoạn xuất bài. Bạn có thể bỏ hai lá bài tay và chọn một tướng nam đã bị thương. Bạn và tướng đó mỗi người hồi 1 điểm máu.",
	qingnang_info: "Giới hạn một lần trong giai đoạn xuất bài. Bạn có thể bỏ một lá bài tay và khiến một tướng hồi 1 điểm máu.",
	jijiu_info: "Ngoài lượt của bạn, bạn có thể dùng một lá bài đỏ như 【Đào】.",
	wushuang_info: "Khóa Kỹ. ① Khi bạn dùng 【Sát】 chỉ định một tướng, tướng đó cần dùng hai lá 【Né】 mới hóa giải; ② Khi bạn dùng 【Quyết Đấu】 chỉ định tướng khác, hoặc trở thành mục tiêu 【Quyết Đấu】 của tướng khác, mỗi lần hưởng ứng cần đánh ra hai lá 【Sát】.",
	lijian_info: "Giới hạn một lần trong giai đoạn xuất bài. Bạn có thể bỏ một lá bài, coi như một tướng nam dùng một lá 【Quyết Đấu】 nhắm vào một tướng nam khác (không thể bị 【Vô Hà Khả Kích】 hưởng ứng).",
	biyue_info: "Trong giai đoạn kết thúc, bạn có thể rút một lá bài.",
	yaowu: "Diệu Vũ",
	yaowu_info: "Khóa Kỹ. Khi một tướng dùng 【Sát】 đỏ gây sát thương cho bạn, tướng đó hồi 1 điểm máu hoặc rút một lá bài.",
	new_jiangchi: "Tướng Trì",
	new_jiangchi_info: "Khi kết thúc giai đoạn rút bài, bạn có thể chọn một: 1. Rút một lá bài — nếu làm vậy, lượt này bạn không thể sử dụng hoặc đánh ra 【Sát】 và 【Sát】 không tính vào giới hạn bài tay. 2. Bỏ một lá bài — nếu làm vậy, trong giai đoạn xuất bài bạn dùng 【Sát】 không giới hạn khoảng cách và có thể dùng thêm một lá 【Sát】, cho đến hết lượt.",
	xinfu_jijie: "Cơ Tiệp",
	xinfu_jijie_info: "Giới hạn một lần trong giai đoạn xuất bài. Bạn có thể xem một lá bài dưới đáy bài, rồi trao cho một tướng.",
	xinfu_jiyuan: "Cấp Viện",
	xinfu_jiyuan_info: "Khi một tướng vào trạng thái cận tử, hoặc sau khi bạn trao bài cho một tướng khác, bạn có thể khiến tướng đó rút một lá bài.",
	ganglie_three: "Cương Liệt",
	ganglie_three_info: "Sau khi bạn nhận sát thương, bạn có thể khiến một tướng địch phán định. Nếu kết quả không phải ♥, tướng đó bỏ hai lá bài hoặc nhận 1 điểm sát thương từ bạn.",
	zhongyi: "Trung Nghĩa",
	zhongyi2: "Trung Nghĩa",
	zhongyi_info: "Hạn Định Kỹ. Trong giai đoạn xuất bài, bạn có thể đặt một lá bài lên thẻ tướng. Khi thẻ tướng của bạn có lá bài 〖Trung Nghĩa〗, sát thương từ 【Sát】 của tướng cùng phe +1. Khi ván tiếp theo bắt đầu, bạn đặt lá bài 〖Trung Nghĩa〗 vào bỏ bài.",
	zhanshen: "Chiến Thần",
	zhanshen_info: "Giác Tỉnh Kỹ. Trong giai đoạn chuẩn bị, nếu có tướng cùng phe khác đã chết và bạn đã bị thương, bạn bỏ vũ khí trong vùng trang bị, giảm 1 điểm máu tối đa, và nhận kỹ năng 〖Mã Thuật〗 và 〖Thần Kích〗.",
	shenji: "Thần Kích",
	shenji_info: "Khóa Kỹ. Số mục tiêu tối đa bạn chỉ định khi dùng 【Sát】 +2, số lần dùng tối đa +1.",
	rewangzun: "Vọng Tôn",
	rewangzun2: "Vọng Tôn",
	rewangzun_info: "Khóa Kỹ. Khi bắt đầu giai đoạn chuẩn bị của một tướng khác, nếu máu của tướng đó lớn hơn bạn, bạn rút một lá bài. Nếu tướng đó có danh phận chủ công/chủ soái/quân chủ/địa chủ và được lật ngửa, bạn rút thêm một lá bài và giới hạn bài tay của tướng đó lượt này -1.",
	retongji: "Đồng Tật",
	retongji_info: "Khi một tướng trong tầm tấn công bao gồm bạn trở thành mục tiêu 【Sát】, nếu bạn không phải người dùng hay mục tiêu 【Sát】 đó, tướng đó có thể bỏ một lá bài rồi chuyển 【Sát】 sang bạn.",
	std_panfeng: "Tiêu Chuẩn Phan Phượng",
	std_panfeng_prefix: "Tiêu Chuẩn",
	stdkuangfu: "Cuồng Phủ",
	stdkuangfu_info: "Khóa Kỹ. Giới hạn một lần trong giai đoạn xuất bài. Sau khi bạn dùng 【Sát】 gây sát thương cho tướng khác, nếu máu của tướng đó: nhỏ hơn bạn — bạn rút hai lá bài; không nhỏ hơn bạn — bạn mất 1 điểm máu.",
	ganfuren: "Tiêu Chuẩn Cam Phu Nhân",
	ganfuren_prefix: "Tiêu Chuẩn",
	stdshushen: "Thục Thận",
	stdshushen_info: "Khi bạn hồi 1 điểm máu, bạn có thể khiến một tướng khác rút một lá bài (nếu tướng đó không có bài tay, rút hai lá thay thế).",
	old_re_lidian: "Lý Điển",
	std_yuejin: "Tiêu Chuẩn Nhạc Tiến",
	std_yuejin_prefix: "Tiêu Chuẩn",
	stdxiaoguo: "Kiêu Quả",
	stdxiaoguo_info: "Khi bắt đầu giai đoạn kết thúc của tướng khác, bạn có thể bỏ một lá bài cơ bản, khiến tướng đó chọn một: 1. Bỏ một lá trang bị; 2. Nhận 1 điểm sát thương từ bạn.",
	stdqingjiao: "Khinh Giảo",
	stdqingjiao_info: "Chủ Công Kỹ. Khóa Kỹ. Trong giai đoạn kết thúc, nếu lượt này bạn đã gây sát thương cho tướng thế lực Quần Hùng khác, bạn rút một lá bài.",
};
};

export default translates;
