export default {
"#ganfuren:die": "Làm ơn hãy chăm sóc tốt cho A Đẩu giúp tôi……",
"#jianxiong1": "Thà ta phụ người thiên hạ, chứ không để người thiên hạ phụ ta!",
"#jianxiong2": "Ta thường hay giết người trong mộng!",
"#hujia1": "Tướng Ngụy ở đâu?",
"#hujia2": "Người đâu! Hộ giá!",
"#caocao:die": "Bá nghiệp chưa thành, chưa thành mà!",
"#fankui1": "Đã ra đời bôn ba, sớm muộn gì cũng phải trả thôi.",
"#fankui2": "Lần sau chú ý một chút.",
"#guicai1": "Thiên mệnh? Ha ha ha ha……",
"#guicai2": "Ta chính là con của thiên mệnh!",
"#simayi:die": "Chẳng lẽ đúng là ý trời khó cưỡng?",
"#ganglie1": "Lũ chuột nhắt, dám làm ta bị thương!",
"#ganglie2": "Gậy ông đập lưng ông!",
"#xiahoudun:die": "Cả, cả hai bên đều không nhìn thấy gì nữa rồi……",
"#tuxi1": "Hừ, không ngờ tới đúng không!",
"#tuxi2": "Đưa đây!",
"#zhangliao:die": "Thực sự không ngờ tới……",
"#luoyi1": "Cởi!",
"#luoyi2": "Ai đến quyết chiến với ta ba trăm hiệp?",
"#xuzhu:die": "Lạnh, lạnh quá……",
"#tiandu1": "Thôi vậy.",
"#tiandu2": "Cũng tốt.",
"#yiji1": "Cứ như vậy đi.",
"#yiji2": "Ồ?",
"#guojia:die": "Khụ, khụ……",
"#luoshen1": "Thấp thoáng tựa mây nhẹ che trăng.",
"#luoshen2": "Bồng bềnh như tuyết lượn trước gió.",
"#qingguo1": "Lướt sóng nhẹ nhàng, bít tất vương bụi.",
"#qingguo2": "Thân nhanh như chim le, phiêu hốt tựa thần linh.",
"#zhenji:die": "Thương thay cuộc hội ngộ tốt đẹp nay đã dứt, buồn thay một kiếp người nơi đất khách quê người……",
"#rende1": "Lấy đức phục người.",
"#rende2": "Chỉ có hiền và đức, mới có thể phục được người.",
"#jijiang11": "Tướng Thục ở đâu?",
"#jijiang12": "Các ngươi có dám ứng chiến không?",
"#liubei:die": "Đây chính là Đào Viên sao?",
"#wusheng1": "Quan Vũ ở đây, các ngươi chịu chết đi!",
"#wusheng2": "Xem ngươi chỉ là kẻ cắm rơm bán mình!",
"#guanyu:die": "Cái gì? Nơi này tên là Mạch Thành?",
"#paoxiao1": "Người nước Yên Trương Phi ở đây!",
"#paoxiao2": "A~~~!",
"#zhangfei:die": "Thực sự là, giết không nổi nữa rồi……",
"#guanxing1": "Xem thiên tượng đêm nay, biết việc lớn trong thiên hạ.",
"#guanxing2": "Biết trời thì dễ, nghịch trời mới khó.",
"#kongcheng11": "（Tiếng gảy đàn）",
"#kongcheng12": "（Tiếng gảy đàn）",
"#zhugeliang:die": "Tướng tinh rụng lạc, thiên mệnh khó cưỡng……",
"#longdan_sha1": "Có thể tiến có thể lui, mới là pháp khí thực sự!",
"#longdan_sha2": "Ta chính là Thường Sơn Triệu Tử Long!",
"#longdan_sha_sp_zhaoyun1": "Đại tướng quân, há có thể hữu dũng vô mưu?",
"#longdan_sha_sp_zhaoyun2": "Một kỹ năng xông pha thiên hạ, có gì phải sợ!",
"#zhaoyun:die": "Đây, chính là mùi vị của thất bại sao?",
"#tieji1": "Toàn quân đột kích!",
"#tieji2": "（Tiếng vó ngựa, tiếng ngựa hí）",
"#machao:die": "（Tiếng vó ngựa xa dần……）",
"#jizhi1": "Hừ hừ~",
"#jizhi2": "Hừ~",
"#huangyueying:die": "Lượng……",
"#zhiheng1": "Để ta suy nghĩ kỹ đã.",
"#zhiheng2": "Khoan đã.",
"#jiuyuan1": "Có ngươi phò tá, rất tốt!",
"#jiuyuan2": "Thật thoải mái a.",
"#sunquan:die": "Cha, đại ca, Trọng Mưu hổ thẹn rồi……",
"#qixi1": "Đỡ chiêu đi!",
"#qixi2": "Bài của ngươi nhiều quá rồi đó!",
"#ganning:die": "Hai mươi năm sau, lại là một hảo hán……",
"#keji1": "Không phải không báo, là giờ chưa tới!",
"#keji2": "Còn giữ được rừng xanh, lo gì không có củi đốt!",
"#lvmeng:die": "Bị nhìn thấu rồi sao……",
"#kurou1": "Hãy đánh roi ta đi, Công Cẩn!",
"#kurou2": "Vào sinh ra tử, không từ nan.",
"#huanggai:die": "Mất máu…… nhiều quá rồi……",
"#yingzi1": "Ha ha ha ha!",
"#yingzi2": "Các ngươi nhìn cho kỹ đây!",
"#fanjian1": "Hãy đau đớn đi, trong địa ngục của thù và hận!",
"#fanjian2": "Hãy giãy giụa đi, trong vực thẳm của máu và tối tăm!",
"#zhouyu:die": "Đã sinh Du, sao còn sinh……",
"#guose1": "Hãy nghỉ ngơi đi.",
"#guose2": "Ngươi mệt rồi.",
"#liuli1": "Giao cho ngươi đó~",
"#liuli2": "Ngươi tới đi mà~",
"#daqiao:die": "Bá Phù, thiếp đi đây……",
"#qianxun1": "Nho sinh thoát tục, không làm những việc tham dâm hưởng lạc.",
"#qianxun2": "Bậc quân tử khiêm nhường, không uống nước suối trộm.",
"#lianying1": "Bài không phải là vạn năng, nhưng không có bài thì vạn vạn lần không thể.",
"#lianying2": "Cái cũ không đi, cái mới không đến.",
"#luxun:die": "Ta vẫn còn quá trẻ……",
"#xiaoji1": "Hừ!",
"#xiaoji2": "Xem sự lợi hại của ta đây!",
"#jieyin1": "Phu quân, thân thể là quan trọng nhất.",
"#jieyin2": "Chàng khỏe, thiếp cũng khỏe.",
"#sunshangxiang:die": "Không! Vẫn chưa thể chết được!",
"#qingnang1": "Ngủ sớm dậy sớm, mới có thể dưỡng sinh.",
"#qingnang2": "Càng già thì càng phải bồi bổ a.",
"#jijiu1": "Đừng căng thẳng, có lão phu ở đây.",
"#jijiu2": "Cứu một mạng người, hơn xây bảy tháp phù đồ.",
"#huatuo:die": "Thầy thuốc…… không thể tự chữa cho mình sao……",
"#wushuang1": "Ai có thể cản ta!",
"#wushuang2": "Thần cản sát Thần, Phật cản sát Phật!",
"#lvbu:die": "Không thể nào!",
"#lijian1": "Ưm hơ hơ~~ hơ hơ~~",
"#lijian2": "Phu quân, chàng phải làm chủ cho thiếp……",
"#biyue1": "Thất lễ rồi~",
"#biyue2": "Ngưỡng mộ chưa~",
"#diaochan:die": "Phụ thân đại nhân, con xin lỗi……",
"#yaowu1": "Đại nhân đại lượng, không thèm chấp nhặt với ngươi!",
"#yaowu2": "Hừ, trước tiên cho ngươi nếm chút ngọt đầu!",
"#huaxiong:die": "Điều này, sao có thể……",
"#yicong1": "Xông lên!",
"#yicong2": "Các tướng nghe lệnh, dàn trận thế, ngự địch!",
"#gongsunzan:die": "Quân ta sắp bại, ta không còn mặt mũi nào sống lay lắt trên đời……",
"#xinfu_jijie1": "Một vái một đứng, chưa đủ làm nhọc.",
"#xinfu_jijie2": "Biết lời xem hành, mới có thể ung dung đàm luận.",
"#xinfu_jiyuan1": "Nếu ngài từ biệt, tất sẽ bị Thái Mạo hãm hại.",
"#xinfu_jiyuan2": "Tình thế nguy cấp, xin hãy mau lên đường.",
"#xf_yiji:die": "Chưa thể, cứu được Lưu công thoát hiểm……",
"#wangzun1": "Chân mệnh thiên tử, tám phương bái phục.",
"#wangzun2": "Quy thuận ta, phong tước thưởng đất!",
"#tongji1": "Tội giết vua, đáng chu di cửu tộc!",
"#tongji2": "Ngươi, ngươi đây là làm phản rồi!",
"#re_yuanshu:die": "Hãy trả lại Ngọc Tỷ cho ta……"
};
