const translates = {
	old_zhangxingcai: "Cựu Trương Tinh Thái",
	old_zhangxingcai_prefix: "Cựu",
	old_xusheng: "Cựu Từ Thịnh",
	old_xusheng_prefix: "Cựu",
	old_lingtong: "Cựu Lăng Thống",
	old_lingtong_prefix: "Cựu",
	old_zhuran: "Cựu Chu Nhiên",
	old_zhuran_prefix: "Cựu",
	old_caoxiu: "Cựu Tào Hưu",
	old_caoxiu_prefix: "Cựu",
	old_caozhen: "Cựu Tào Chân",
	old_caozhen_prefix: "Cựu",
	old_maliang: "Cựu Mã Lương",
	old_maliang_prefix: "Cựu",
	old_chenqun: "Cựu Trần Quần",
	old_chenqun_prefix: "Cựu",
	old_zhuhuan: "Cựu Chu Hoàn",
	old_zhuhuan_prefix: "Cựu",
	old_zhuzhi: "Cựu Chu Trị",
	old_zhuzhi_prefix: "Cựu",
	old_zhugezhan: "Cựu Gia Cát Chiêm",
	old_zhugezhan_prefix: "Cựu",
	yuji: "Cựu Vu Cát",
	yuji_prefix: "Cựu",
	old_zhangfei: "Tân Sát Trương Phi",
	old_zhangfei_prefix: "Tân Sát",
	old_huatuo: "OL Hoa Đà",
	old_huatuo_prefix: "OL",
	old_guanyu: "Cựu Quan Vũ",
	old_guanyu_prefix: "Cựu",
	ol_zhuran: "OL Chu Nhiên",
	ol_zhuran_prefix: "OL",
	old_fuhuanghou: "Cựu Phục Thọ",
	old_fuhuanghou_prefix: "Cựu",
	old_caochong: "Cựu Tào Xung",
	old_caochong_prefix: "Cựu",
	old_guanqiujian: "Cựu Quán Khâu Kiệm",
	old_guanqiujian_prefix: "Cựu",
	old_wangyun: "Cựu Vương Doãn",
	old_wangyun_prefix: "Cựu",
	old_zhaoyun: "Tân Sát Triệu Vân",
	old_zhaoyun_prefix: "Tân Sát",
	ol_huaxiong: "Cựu Hoa Hùng",
	ol_huaxiong_prefix: "Cựu",
	old_xiaoqiao: "Cựu Tiểu Kiều",
	old_xiaoqiao_prefix: "Cựu",
	old_wanglang: "Cựu Vương Lãng",
	old_wanglang_prefix: "Cựu",
	old_wangyi: "Cựu Vương Dị",
	old_wangyi_prefix: "Cựu",
	xin_yujin: "Tiết Việt Vu Cấm",
	xin_yujin_prefix: "Tiết Việt",
	re_yujin: "Nghị Trọng Vu Cấm",
	re_yujin_prefix: "Nghị Trọng",

	old_guhuo: "Cổ Hoặc",
	old_guhuo_info: "Bạn có thể úp một lá trên tay dùng hoặc đánh ra như một lá Cơ bản hoặc Cẩm nang thường. Những người chơi khác có thể lực khác 0 lần lượt chọn có nghi ngờ hay không. Sau đó, nếu có người nghi ngờ, bạn ngửa lá bài đó ra: Nếu là giả, lá bài bị hủy, những người đó được rút 1 lá; Nếu là thật, những người đó mất 1 điểm thể lực, và nếu lá bài không phải chất Cơ (♥), lá bài đó bị hủy.",
	old_guhuo_guess: "Cổ Hoặc",
	old_jijun: "Tập Quân",
	old_jijun_info: "Giai đoạn ra bài, bạn có thể đặt bất kỳ số lượng bài trên tay lên thẻ võ tướng, gọi là 'Phương'.",
	old_fangtong: "Phương Thống",
	old_fangtong_info: "Kỹ năng khóa. Giai đoạn kết thúc, nếu số lượng 'Phương' của bạn không ít hơn 36, phe của bạn sẽ giành chiến thắng và kết thúc ván đấu.",
	old_zuilun: "Tội Luận",
	old_zuilun_info: "Giai đoạn ra bài, bạn có thể lấy của một người chơi khác một lá bài (trên tay và khu trang bị mỗi loại một lần), sau đó người đó rút 1 lá.",
	old_fuyin: "Phụ Ấm",
	old_fuyin_info: "Kỹ năng khóa. Nếu khu trang bị của bạn không có Giáp, bạn không thể trở thành mục tiêu của [Sát], [Quyết đấu] hoặc [Hỏa công] từ những người chơi có số bài trên tay không ít hơn bạn.",
	oldanxu: "An Tuất",
	oldanxu_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể chọn hai người chơi khác có số bài trên tay không bằng nhau, người có ít bài hơn sẽ lấy một lá bài trên tay của người có nhiều bài hơn và ngửa nó ra, sau đó nếu lá bài đó không phải chất Bích (♠), bạn rút 1 lá.",
	oldfaen: "Pháp Ân",
	oldfaen_info: "Khi một người chơi bị lật mặt hoặc bị xích, bạn có thể khiến người đó rút 1 lá bài.",
	oldxuanfeng: "Toàn Phong",
	oldxuanfeng_info: "Khi bạn mất bài trong khu trang bị, bạn có thể chọn một trong hai: 1. Xem như sử dụng một lá [Sát] lên một người chơi khác; 2. Gây 1 điểm sát thương cho một người chơi trong khoảng cách 1.",
	ol_yuanshu: "Cựu Viên Thuật",
	ol_yuanshu_prefix: "Cựu",
	fazheng: "Cựu Pháp Chính",
	fazheng_prefix: "Cựu",
	junk_simayi: "Cựu Tấn Tư Mã Ý",
	junk_simayi_prefix: "Cựu Tấn",
	madai: "Cựu Mã Đại",
	madai_prefix: "Cựu",
	old_yangzhi: "Cựu Dương Chỉ",
	old_yangzhi_prefix: "Cựu",
	old_yangyan: "Cựu Dương Diễm",
	old_yangyan_prefix: "Cựu",
	old_caorui: "Cựu Tào Duệ",
	old_caorui_prefix: "Cựu",
	oldmingjian: "Minh Giám",
	oldmingjian_info: "Trước khi bắt đầu giai đoạn ra bài, bạn có thể bỏ qua giai đoạn này và đưa toàn bộ bài trên tay cho một người chơi khác. Nếu làm vậy, bạn kết thúc lượt hiện tại, sau đó người đó nhận được một lượt phụ (chỉ bao gồm giai đoạn ra bài).",
	old_handang: "Cựu Hàn Đương",
	old_handang_prefix: "Cựu",
	oldgongji: "Cung Kị",
	oldgongji_info: "Bạn có thể dùng một lá bài trang bị như một lá [Sát] không bị giới hạn khoảng cách.",
	oldjiefan: "Giải Phiền",
	oldjiefan_info: "Khi một người chơi A rơi vào trạng thái hấp hối ngoài lượt của bạn, bạn có thể sử dụng một lá [Sát] lên người chơi có lượt hiện tại. Khi lá [Sát] này gây sát thương, bạn ngăn chặn sát thương đó, xem như sử dụng một lá [Đào] cho A.",
	old_gaoshun: "Cựu Cao Thuận",
	old_gaoshun_prefix: "Cựu",
	old_liubiao: "Cựu Lưu Biểu",
	old_liubiao_prefix: "Cựu",
	oldre_liubiao: "RE Lưu Biểu",
	oldre_liubiao_prefix: "RE",
	oldzishou: "Tự Thủ",
	oldzishou_info: "Giai đoạn rút bài, nếu bạn đã bị thương, bạn có thể khiến số bài rút định mức +X (X là số thể lực đã mất của bạn), sau đó bỏ qua giai đoạn ra bài tiếp theo.",
	old_huanghao: "Cựu Hoàng Hạo",
	old_huanghao_prefix: "Cựu",
	oldqinqing: "Tẩm Tình",
	oldqinqing_info: "Giai đoạn kết thúc, bạn có thể chọn một người chơi khác có tầm tấn công bao gồm cả Chủ công, sau đó bạn hủy một lá bài của người đó (không có bài thì không hủy), và khiến họ rút 1 lá. Nếu số bài trên tay của người đó nhiều hơn Chủ công, bạn rút 1 lá.",
	oldhuisheng: "Hối Sinh",
	oldhuisheng_info: "Mỗi người chơi giới hạn một lần. Khi bạn chịu sát thương từ người chơi khác, bạn có thể để người đó xem bất kỳ số lượng bài nào của bạn và để người đó chọn một: 1. Lấy một trong số những lá bài đó và ngăn chặn sát thương; 2. Hủy bỏ số lượng bài tương đương.",
	old_dingfeng: "Cựu Đinh Phụng",
	old_dingfeng_prefix: "Cựu",
	new_caoren: "Cựu Tào Nhân",
	new_caoren_prefix: "Cựu",
	old_liyan: "Cựu Lý Nghiêm",
	old_liyan_prefix: "Cựu",
	old_chendao: "Cựu Trần Đáo",
	old_chendao_prefix: "Cựu",
	old_caocao: "Cựu Thần Tào Tháo",
	old_caocao_prefix: "Cựu Thần",
	junkguixin: "Quy Tâm",
	junkguixin_info: "Khi kết thúc lượt, bạn có thể chọn một: ① Nhận một trong các kỹ năng Chủ công từ chồng bài võ tướng còn lại; ② Thay đổi phe của một người chơi khác.",
	old_caochun: "Cựu Tào Thuần",
	old_caochun_prefix: "Cựu",
	old_guanyinping: "Cựu Quan Ngân Bình",
	old_guanyinping_prefix: "Cựu",
	panfeng: "Cựu Phan Phụng",
	panfeng_prefix: "Cựu",
	old_shixie: "Cựu Sĩ Nhiếp",
	old_shixie_prefix: "Cựu",
	old_wuyi: "Cựu Ngô Ý",
	old_wuyi_prefix: "Cựu",
	one_dc_sp_machao: "Lao SP Mã Siêu",
	one_dc_sp_machao_prefix: "Lao|SP",
	two_dc_sp_machao: "Lao SP Mã Siêu",
	two_dc_sp_machao_prefix: "Lao|SP",
	cx_majun: "Truyền Giới Mã Quân",
	cx_majun_ab: "Lao Mã Quân",
	cx_majun_prefix: "Lao",
	qq_majun: "Kỳ Xảo Mã Quân",
	qq_majun_ab: "Lao Mã Quân",
	qq_majun_prefix: "Lao",
	xj_peixiu: "Lao Bùi Tú",
	xj_peixiu_prefix: "Lao",
	hr_wufu: "Lao Ngũ Phụ",
	hr_wufu_prefix: "Lao",
	new_simayi: "Lao Thần Tư Mã Ý",
	new_simayi_prefix: "Lao|Thần",
	junk_sunquan: "Lao Thần Tôn Quyền",
	junk_sunquan_prefix: "Lao|Thần",
	ol_baosanniang: "Lao Bào Tam Nương",
	ol_baosanniang_prefix: "Lao",
	x_yao_yuanshu: "Lao Hào Viên Thuật",
	x_yao_yuanshu_prefix: "Lao|Hào",
	yao_yaoyi: "Hào Nghi",
	yao_yaoyi_tag: "invisible",
	yao_yaoyi_info: "Kỹ năng khóa. ① Các lá bài tay ban đầu của bạn được đặt úp. ② Mỗi lượt mỗi tên lá bài giới hạn một lần, bạn có thể dùng một lá bài đang úp như một lá bài Cơ bản hoặc Cẩm nang thường bất kỳ.",
	yao_chenwei: "Sấm Vĩ",
	yao_chenwei_info: "Kỹ năng chuyển đổi. Khi bạn sử dụng lá bài đang úp, bạn có thể, Dương: Khiến một người chơi lật mặt một lá bài trên tay của bạn; Âm: Lấy một lá bài của người chơi khác và đặt úp lá bài đó.",
	sy_baosanniang: "Thủ Sát Lao Bào Tam Nương",
	sy_baosanniang_prefix: "Thủ Sát|Lao",
	fx_baosanniang: "Phương Hứa Bào Tam Nương",
	fx_baosanniang_ab: "Thủ Sát Lao Bào Tam Nương",
	fx_baosanniang_prefix: "Thủ Sát|Lao",
	x_dc_zhangqiying: "Tân Sát Lao Trương Kì Anh",
	x_dc_zhangqiying_prefix: "Tân Sát|Lao",
	two_yj_puyuan: "Lao SP Bồ Nguyên",
	two_yj_puyuan_prefix: "Lao|SP",
	two_yj_tengjia: "Lao Đằng Giáp Nam Hài",
	two_yj_tengjia_prefix: "Lao",
	two_yj_hanbing: "Lao Hàn Băng Kiếm Thiếu Nữ",
	two_yj_hanbing_prefix: "Lao",
	chegu: "Triệt Cốt",
	chegu_info: "Khi bạn sử dụng lá bài không phải trang bị nhắm vào mục tiêu trong lượt, bạn có thể hủy bỏ toàn bộ mục tiêu của lá bài đó và chọn một: 1. Hủy tối đa [2] lá bài của một người chơi; 2. Hủy mỗi người một lá bài của tối đa [2] người chơi. Sau đó nếu các lá bài bị hủy theo cách này có màu hoặc loại giống nhau, giá trị trong dấu [] của kỹ năng này trong lượt này đều +1.",
	jianrou: "Kiếm Nhu",
	jianrou_info: "Mỗi vòng giới hạn một lần, khi bạn chịu sát thương, bạn có thể hủy hai lá bài để ngăn chặn sát thương đó. Nếu các lá bài bạn hủy theo cách này có màu hoặc loại giống nhau, bạn rút 1 lá và xem như kỹ năng này chưa từng phát động.",
};

export default translates;
