import { lib, game, ui, get, ai, _status } from "noname";

const translates = {
	sxrm: "Thực Tâm Nhập Ma",
	//Thực Tâm Nhập Ma Nghi
	sxrm_caocao: "Ma Tào Tháo",
	sxrm_caocao_prefix: "Ma",
	sxrmkuxin: "Khô Tâm",
	sxrmkuxin_info: "Sau khi chịu sát thương, bạn có thể khiến tất cả các nhân vật khác lần lượt chọn trưng ra số quân bài trên tay tùy ý, sau đó bạn nhận lấy tất cả các quân bài đã trưng ra hoặc toàn bộ bài trên tay chưa trưng ra của một nhân vật và trưng chúng ra, nếu bạn không nhận được lá ♥ theo cách này, bạn bỏ các quân bài đó và lật mặt.",
	sxrmsigu: "Tự Cố",
	sxrmsigu_info: `Giai đoạn ra bài giới hạn một lần, bạn có thể khiến một nhân vật khác tiến hành phán xét, khiến người đó nhận được kỹ năng thứ X trong số ${["zhichi", "reganglie", "refankui", "new_reyiji", "oljieming", "fangzhu", "shibei", "rechengxiang", "zhiyu", "jilei", "benyu", "chouce", "new_wuhun"].map(skill => get.poptip(skill)).join("")} (X là điểm phán xét). Nếu làm vậy, bạn gây cho người đó hai lần 1 điểm sát thương, sau đó người đó mất kỹ năng đã nhận theo cách này.`,
	sxrm_liubei: "Nghi Lưu Bị",
	sxrm_liubei_prefix: "Nghi",
	sxrmchengbian: "Thừa Biến",
	sxrmchengbian_info: `Giai đoạn chuẩn bị và giai đoạn kết thúc, bạn có thể cùng một nhân vật tiến hành ${get.poptip("sxrm_compare")}, sau đó xem như đối với người đó sử dụng một lá [Quyết Đấu], bạn và người đó có thể đem ít nhất một nửa số bài trên tay làm [Sát] đánh ra cho đến khi [Quyết Đấu] này kết thúc. Sau khi kết thúc [Quyết Đấu], công bố kết quả so bài, nhân vật thắng sẽ rút bài đến khi bằng giới hạn thể lực.`,
	sxrm_jianggan: "Nghi Tưởng Cán",
	sxrm_jianggan_prefix: "Nghi",
	sxrmzongheng: "Tung Hoành",
	sxrmzongheng_info: "Giai đoạn chuẩn bị, bạn có thể xem bài trên tay của hai nhân vật khác, trưng ra và nhận lấy một lá trong đó, sau đó bạn bỏ của nhân vật còn lại các lá bài trên tay có cùng chất, cùng điểm, cùng loại với lá bài đã trưng ra mỗi loại một lá.",
	sxrmduibian: "Đối Biện",
	sxrmduibian_info: `Mỗi lượt khi lần đầu chịu sát thương, bạn có thể cùng nguồn sát thương ${get.poptip("sxrm_compare")} và ngăn chặn sát thương này, sau đó người đó có thể khiến bạn bỏ một lá bài của người đó và công bố kết quả so bài, nếu người đó thắng thì bạn mất 1 điểm thể lực.`,
	sxrm_huatuo: "Nghi Hoa Đà",
	sxrm_huatuo_prefix: "Nghi",
	sxrmmiehai: "Diệt Hại",
	sxrmmiehai_info: "Bạn có thể dùng hai lá bài làm một lá [Sát] đâm (Thứ Sát) không giới hạn khoảng cách và số lần. Sau khi kết thúc lần [Sát] này, trong quá trình đó các nhân vật đã bị thương và mất lá ♠ ở mặt trước được rút hai lá bài và hồi 1 điểm thể lực.",
	sxrm_lvboshe: "Nghi Lã Bá Sa",
	sxrm_lvboshe_prefix: "Nghi",
	sxrmqingjun: "Thỉnh Quân",
	sxrmqingjun_info: `Mỗi khi kết thúc vòng, bạn có thể chọn một nhân vật khác, khiến bạn và các nhân vật khác có phạm vi tấn công bao gồm người đó mỗi người rút hai lá bài và phát động ${get.poptip("sxrmshefu")}; nếu làm vậy, người đó thực hiện một lượt bổ sung, khi kết thúc lượt này, các nhân vật đã phát động [Thiết Phục] theo cách này sẽ loại bỏ "Phục Binh", sau đó các nhân vật trong số đó không bị thương trong lượt này mỗi người xem như đối với người đó sử dụng một lá [Sát].`,
	sxrmshefu: "Thiết Phục",
	sxrmshefu_info: "Giai đoạn kết thúc, bạn có thể úp một lá bài làm \"Phục Binh\"; khi nhân vật khác sử dụng bài trên tay ngoài lượt của bạn, bạn có thể loại bỏ một lá \"Phục Binh\" có cùng màu sắc và chủng loại với lá bài đó, khiến lá bài đó vô hiệu.",
	sxrm_fuhuanghou: "Nghi Phục Thọ",
	sxrm_fuhuanghou_prefix: "Nghi",
	sxrmmitu: "Mật Đồ",
	sxrmmitu_info: "Giai đoạn chuẩn bị, bạn có thể khiến tối đa ba nhân vật đã bị thương mỗi người rút một lá bài và trưng ra, sau đó khiến các nhân vật này lần lượt chọn có so bài với một nhân vật khác do bạn chỉ định hay không, nhân vật thắng so bài xem như đối với nhân vật không thắng sử dụng một lá [Sát]. Cứ mỗi nhân vật không dùng lá bài đã trưng ra để so bài, bạn giảm 1 điểm giới hạn thể lực.",
	sxrmqianliu: "Tiềm Lưu",
	sxrmqianliu_info: "Sau khi nhân vật trong khoảng cách 1 trở thành mục tiêu của [Sát], bạn có thể xem bốn lá bài dưới đáy chồng bài và đặt lại lên trên đầu hoặc xuống dưới đáy chồng bài theo thứ tự tùy ý; nếu các lá bài này có chất hoàn toàn khác nhau, bạn có thể trưng ra và nhận lấy chúng.",
	sxrm_xunyu: "Nghi Tuân Úc",
	sxrm_xunyu_prefix: "Nghi",
	sxrmhuice: "Hồi Sách",
	sxrmhuice_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể lần lượt so bài với hai nhân vật, nhân vật thắng trong một lần so bài sẽ gây cho nhân vật không thắng trong lần so bài còn lại 1 điểm sát thương.",
	sxrmyihe: "Dị Hợp",
	sxrmyihe_info: "Kỹ năng khóa, trong lượt của bạn mỗi lượt giới hạn một lần, khi một nhân vật chịu sát thương, nếu quan hệ lớn nhỏ giữa số bài trên tay và trị số thể lực của người đó và nguồn sát thương là: giống nhau, người đó và nguồn sát thương mỗi người rút hai lá bài; khác nhau, sát thương này +1.",
	sxrmjizhi: "Tê Chí",
	sxrmjizhi_info: "Kỹ năng khóa, nhân vật khác không thể đối với bạn sử dụng [Đào]; mỗi khi bạn lần đầu rơi vào trạng thái hấp hối trong mỗi lượt, hồi 1 điểm thể lực.",
	sxrm_caopi: "Nghi Tào Phi",
	sxrm_caopi_prefix: "Nghi",
	sxrmzhengsi: "Tranh Tự",
	sxrmzhengsi_info: "Giai đoạn ra bài, bạn có thể chọn ba nhân vật có bài trên tay bao gồm cả bạn, khiến một trong số đó trưng ra một lá bài trước, sau đó các nhân vật còn lại đồng thời trưng ra một lá bài. Nhân vật trưng ra lá bài có điểm lớn nhất sẽ bỏ hai lá bài trên tay, nhân vật trưng ra lá bài có điểm nhỏ nhất sẽ mất 1 điểm thể lực.",
	sxrmchengming: "Thừa Mệnh",
	sxrmchengming_info: "Khi kết thúc giai đoạn ra bài, nếu bạn đã phát động [Tranh Tự] trong giai đoạn này, và trong số các nhân vật đã từng trở thành mục tiêu của [Tranh Tự] trong giai đoạn này: bạn có số bài trên tay lớn nhất, bạn có thể hồi 2 điểm thể lực; bạn có trị số thể lực lớn nhất, bạn có thể lấy của mỗi nhân vật đó một lá bài.",
	sxrm_wanghou: "Nghi Vương Hậu",
	sxrm_wanghou_prefix: "Nghi",
	sxrmjugu: "Tụ Cốc",
	sxrmjugu_info: "Giai đoạn chuẩn bị, bạn có thể lần lượt chọn bất kỳ nhân vật nào tối đa tổng cộng năm lá bài, đặt các lá bài này ngửa mặt lên trên đầu chồng bài; khi kết thúc lượt này, các nhân vật đó nhận lại các lá bài tương ứng đã đặt theo cách này từ đầu chồng bài (nếu không có thì bỏ qua), sau đó mỗi người rút một lá bài.",
	//Thực Tâm Nhập Ma · Mạn
	sxrm_guanyu: "Ma Quan Vũ",
	sxrm_guanyu_prefix: "Ma",
	sxrmhanguo: "Hám Quốc",
	sxrmhanguo_info: `Mỗi khi bắt đầu vòng, bạn có thể chọn một nhân vật khác chưa từng được chọn theo cách này ở vòng trước, úp tất cả bài của người đó cho đến khi kết thúc vòng này, và trong vòng này: sau khi bạn sử dụng [Sát] gây sát thương cho người đó, người đó tử vong; người đó có thể phát động ${get.poptip("hujia")} không giới hạn phe phái và nhân vật phản hồi kỹ năng đó sẽ nhận một lá bài của bạn.`,
	sxrmweiwo: "Duy Ngã",
	sxrmweiwo_info: `Kỹ năng giới hạn, giai đoạn kết thúc, bạn có thể khiến tối đa ba nhân vật khác mỗi người nhận một kỹ năng khác nhau trong số ${get.poptip("rende")}${get.poptip("qingnang")}${get.poptip("longyin")} (chỉ có thể phát động đối với bạn), sau đó bạn nhận được ${get.poptip("old_wushen")}.`,
	old_wushen: "Võ Thần",
	old_wushen_info: "Kỹ năng khóa, các lá bài trên tay chất ♥ của bạn được xem là [Sát] không giới hạn khoảng cách.",
	sxrm_guanyinping: "Mạn Quan Ngân Bình",
	sxrm_guanyinping_prefix: "Mạn",
	sxrmyinmou: "In Mưu",
	sxrmyinmou_info: `Giai đoạn kết thúc của một nhân vật nam, người đó có thể liên kết một lá bài trên tay của bạn và của người đó mà chưa bị ${get.poptip("sxrm_connect")}. Sau mỗi lần bạn đầu tiên mất lá bài ${get.poptip("sxrm_connect")} trong mỗi lượt, các nhân vật đồng thời mất lá bài ${get.poptip("sxrm_connect")} lần này sẽ lần lượt rút X lá bài (X là số nhân vật đó và tối đa là 5).`,
	sxrmquchi: "Khu Xích",
	sxrmquchi_info: `Giai đoạn ra bài giới hạn một lần, bạn có thể gây cho một nhân vật 1 điểm sát thương lửa, nếu người đó có lá bài ${get.poptip("sxrm_connect")}, đặt lại các lá bài này và khiến sát thương này +1.`,
	sxrm_yujin: "Mạn Vu Cấm",
	sxrm_yujin_prefix: "Mạn",
	sxrmsuwu: "Túc Ngũ",
	sxrmsuwu_info: `Giai đoạn chuẩn bị, bạn có thể ${get.poptip("sxrm_connect")} tối đa bốn nhân vật mỗi người một lá bài trên tay; nếu bạn có lá bài ${get.poptip("sxrm_connect")}, nhân vật có lá bài ${get.poptip("sxrm_connect")} mỗi lượt sử dụng lá bài gây sát thương đầu tiên sẽ không thể bị phản hồi và sau khi kết thúc người đó rút hai lá bài.`,
	sxrmrenwang: "Nhân Vương",
	sxrmrenwang_info: `Mỗi lượt giới hạn một lần, bạn có thể dùng một lá bài ${get.poptip("sxrm_connect")} làm lá [Đào].`,
	sxrm_mifang: "Mạn Mi Phương",
	sxrm_mifang_prefix: "Mạn",
	sxrmhuoe: "Hỏa Ách",
	sxrmhuoe_info: "Giai đoạn kết thúc, bạn có thể xem như đối với tối đa bốn nhân vật khác sử dụng một lá [Hỏa Công], nếu bạn có bài có thể bỏ, phải bỏ nó và hủy các mục tiêu còn lại, nếu không người đó xem bài trên tay của bạn. Sau khi kết thúc, bạn phân phối các lá bài đã trưng ra do việc này, nếu tổng điểm nhỏ hơn 13, bạn mất 1 điểm thể lực.",
	sxrmtanduo: "Tham Đọa",
	sxrmtanduo_info: "Kỹ năng khóa, giai đoạn bỏ bài mà bạn cần bỏ bài được đổi thành giai đoạn rút bài.",
	sxrm_liufeng: "Mạn Khấu Phong",
	sxrm_liufeng_prefix: "Mạn",
	sxrmhuaibing: "Hoài Binh",
	sxrmhuaibing_info: "Giai đoạn chuẩn bị, bạn có thể chọn hai nhân vật có bài, nhận lấy của mỗi nhân vật đó một lá bài trên tay (nếu là bạn thì bỏ qua), sau đó bạn trưng ra bài trên tay, khiến nhân vật có trị số thể lực ít hơn trong đó vào giai đoạn rút bài tiếp theo số bài rút, giai đoạn ra bài số lần ra [Sát], giai đoạn bỏ bài giới hạn bài trên tay đổi thành số lượng lá bài màu đỏ trong đó.",
	sxrm_luxun: "Mạn Lục Tốn",
	sxrm_luxun_prefix: "Mạn",
	sxrmchanyu: "Siểm Du",
	sxrmchanyu_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể khiến một nhân vật khác rút số bài bằng trị số thể lực của người đó và cùng người đó dùng lá bài có điểm nhỏ nhất của mỗi bên để so bài, sau đó hai bên trưng bài trên tay: nhân vật thắng có thể trao đổi tất cả bài trên tay của một loại màu sắc hoặc chủng loại của hai bên.",
	sxrmchanyu_tag: "invisible",
	sxrmcongfeng: "Tòng Phong",
	sxrmcongfeng_info: "Kỹ năng chuyển đổi, sau khi bạn sử dụng bài hoặc trở thành mục tiêu của bài, bạn có thể Dương: cùng người sử dụng mỗi người rút một lá bài; Âm: bỏ hai lá bài của người sử dụng.",
	sxrm_lvmeng: "Mạn Lã Mông",
	sxrm_lvmeng_prefix: "Mạn",
	sxrmkongzhi: "Không Chí",
	sxrmkongzhi_info: "Kỹ năng khóa, sau khi bạn sử dụng [Sát] chỉ định mục tiêu duy nhất, nhận lấy tối đa ba lá bài của người đó; nếu bạn đã bị thương, bài Cẩm Nang thông thường vô hiệu đối với bạn và các lá bài Cơ Bản của bạn đều được xem là [Thiểm].",
	sxrmbizha: "Bỉ Trá",
	sxrmbizha_info: "Giai đoạn kết thúc, bạn có thể rút một lá bài và so bài: nếu người đó không thắng, người đó mất 2 điểm thể lực và khiến bạn xem bài trên tay của người đó, bạn có thể sử dụng tối đa hai lá bài có điểm nhỏ hơn lá bài so bài của người đó; nếu bạn không thắng, bạn giảm 1 điểm giới hạn thể lực.",
	sxrm_pangde: "Mạn Bàng Đức",
	sxrm_pangde_prefix: "Mạn",
	sxrmnuozhan: "Nhuế Chiến",
	sxrmnuozhan_info: "Giai đoạn chuẩn bị, bạn có thể rút một lá bài và khiến một nhân vật khác tuyên bố tên một lá bài loại gây sát thương, sau đó bạn khiến bạn hoặc người đó xem như đối với đối phương sử dụng lá bài này và sát thương +1; nếu lá bài này không gây sát thương cho mục tiêu, người sử dụng mất 1 điểm thể lực và bạn có thể lặp lại quy trình này đối với cùng một nhân vật.",
	sxrm_yanwen: "Mạn Nhan Lương Văn Xử",
	sxrm_yanwen_prefix: "Mạn",
	sxrmhaibian: "Hãi Biến",
	sxrmhaibian_info: "Khi bắt đầu lượt của một nhân vật, nếu lượt trước bạn từng sử dụng bài trên tay, thì người sử dụng lá bài màu đen và màu đỏ cuối cùng của lượt trước có thể lần lượt xem như sử dụng một lá [Quyết Đấu].",
	sxrmqiewang: "Khiếp Vong",
	sxrmqiewang_info: "Kỹ năng khóa, sau khi nhân vật trong khoảng cách 1 của bạn chịu sát thương, bạn rút một lá bài, khiến bài trên tay của bạn trong lượt này đều được xem là [Vô Giải Khả Kích].",
};

export default translates;
