import { lib, game, ui, get, ai, _status } from "noname";

const translates = {
	zhuji: "Chu Tích",
	potjiezhu: "Kiệt Trục",
	potjiezhu_info: "Mỗi lượt giới hạn một lần, bạn có thể bỏ bài trên tay xuống giá trị duy nhất gần nhất, xem như sử dụng một đòn 【Giết】 thông thường không giới hạn khoảng cách, chỉ định tối đa X mục tiêu (X là số bài đã bỏ). Sau khi đòn 【Giết】 này kết toán, nếu số mục tiêu của 【Giết】 này là X và gây sát thương cho tất cả mục tiêu, bạn sẽ bốc bài lên giá trị duy nhất gần nhất.",
	pothuanshi: "Hoàn Thi",
	pothuanshi_info: `Kỹ năng sứ mệnh, 【Giết】 đầu tiên bạn sử dụng mỗi lượt gây sát thương +1; Bạn không thể sử dụng nhưng có thể tái luyện 【Rượu】 khi không trong trạng thái hấp hối. Thành công: Sau khi bạn gây ra hoặc chịu sát thương, nếu giá trị sát thương lần này bằng thể lực của bạn, bạn nhận được ${get.poptip("potjianlv")}.`,
	potjianlv: "Kiêm Lự",
	potjianlv_info: "Khi bạn bỏ ít nhất X lá bài cùng một lúc (X là số lần kỹ năng này đã kích hoạt +1), bạn có thể gây 1 điểm sát thương cho một nhân vật khác. Nếu mục tiêu đó chết vì sát thương này, bạn chọn một: 1. Đặt lại X của kỹ năng này; 2. Gây 1 điểm sát thương cho một nhân vật khác.",
	sp_zhonghui: "Thế Chung Hội",
	sp_zhonghui_prefix: "Thế",
	mbsizi: "Tứ Tư",
	mbsizi_info: `Kỹ năng Tích Lực (4/4). Giai đoạn Xuất Bài mỗi lượt giới hạn một lần, bạn có thể tiêu hao một lượng điểm Tích Lực bất kỳ, khiến cho một số lượt bằng với lượng đó, bắt đầu từ lượt này, thực hiện hiệu ứng sau cho đến khi bắt đầu lượt tiếp theo của bạn: 1. Tất cả nhân vật dùng 【Giết】 gây sát thương +1; 2. Khi mỗi lượt kết thúc, bạn bốc 2 lá và nhân vật đã dùng 【Giết】 trong lượt đó mất 1 điểm thể lực. Nếu lượng Tích Lực bạn tiêu hao lớn hơn thể lực của bạn, thực hiện thêm một hiệu ứng: Khi mỗi lượt kết thúc, nếu không có nhân vật nào dùng 【Giết】 trong lượt đó, nhân vật của lượt hiện tại mất 1 điểm thể lực.`,
	mbxiezhi: "Hiệp Chí",
	mbxiezhi_info: "Kỹ năng khóa, khi giá trị thể lực của bạn thay đổi, bạn nhận được X điểm Tích Lực (X là giá trị thay đổi lần này). Nếu bạn có điểm Tích Lực không thể nhận vì lý do gì, giới hạn bài trên tay và số lần dùng 【Giết】 của bạn tăng vĩnh viễn +1.",
	mbyunan: "Vu Nan",
	mbyunan_info: `Kỹ năng Giác Tỉnh, thế lực xuất hiện của bạn là Ngụy. Khi bạn khiến một nhân vật khác vào trạng thái hấp hối, nếu lượt này đã có nhân vật chết, bạn đổi thế lực thành Quần, sau đó nhận được ${get.poptip("mbkechang")}, nếu đã có thì nâng cấp ${get.poptip({
		id: "yunan_kechang",
		name: "〖Khắc Xương〗",
		type: "character",
		info: "Kỹ năng Chủ Công, kỹ năng khóa, nhân vật thế lực Quần dùng 【Giết】 không giới hạn khoảng cách; 【Giết】 bạn dùng không thể bị đáp trả.",
	})}.`,
	mbkechang: "Khắc Xương",
	mbkechang_info: "Kỹ năng Chủ Công, kỹ năng khóa, nhân vật thế lực Quần dùng 【Giết】 không giới hạn khoảng cách.",
	mbkechang_rewrite: "Khắc Xương·Cấp Hai",
	get mbkechang_rewrite_info() {
		return lib.poptip.getInfo("yunan_kechang");
	},
	pot_taishici: "Thế Thái Sử Từ",
	pot_taishici_prefix: "Thế",
	pothanzhan: "Hàm Chiến",
	pothanzhan_info: "Giai đoạn Xuất Bài mỗi lượt giới hạn một lần, bạn có thể chọn một nhân vật khác, bạn và người đó bốc bài lên X lá (X lần lượt là giới hạn thể lực của mỗi người và tối đa là 3), sau đó bạn xem như sử dụng một đòn 【Quyết Đấu】 nhắm vào người đó.",
	potzhanlie: "Chiến Liệt",
	potzhanlie_info: "① Khi bắt đầu lượt của một nhân vật, bạn ghi nhận X (X là phạm vi tấn công của bạn), X lá 【Giết】 đầu tiên trong lượt này vào bộ bài bỏ sau khi bỏ, bạn nhận được số lượng dấu hiệu “Liệt” tương ứng (bạn có tối đa 6 dấu hiệu “Liệt”). ② Khi giai đoạn Xuất Bài kết thúc, bạn có thể bỏ tất cả dấu hiệu “Liệt” (không có dấu hiệu vẫn có thể phát động), xem như sử dụng một đòn 【Giết】 không giới hạn số lần và chọn tối đa Y hạng mục trong số các hạng mục sau (Y là số dấu hiệu bạn bỏ lần này / 2, làm tròn xuống): 1. 【Giết】 này có thể chỉ định thêm một mục tiêu; 2. Sát thương cơ bản của 【Giết】 này +1; 3. 【Giết】 này cần bỏ thêm một lá bài mới có thể đáp trả; 4. Sau khi 【Giết】 này kết toán xong, bạn bốc 3 lá bài.",
	potzhenfeng: "Chấn Phong",
	potzhenfeng_info: "Kỹ năng giới hạn, giai đoạn Xuất Bài, bạn có thể chọn một: ① Hồi phục 2 điểm thể lực; ② Sửa đổi chữ “X” trong mô tả của 【Hàm Chiến】 và 【Chiến Liệt】 thành một trong các giá trị: thể lực hiện tại, thể lực đã mất, số nhân vật còn sống (chỉ có thể chọn nếu có kỹ năng tương ứng).",
	pot_dongzhao: "Thế Đống Chiêu",
	pot_dongzhao_prefix: "Thế",
	spmiaolve: "Diệu Lược",
	spmiaolve_info: `Khi bắt đầu ván chơi, bạn nhận được hai lá ${get.poptip("dz_mantianguohai")}; Khi bạn chịu sát thương, bạn có thể chọn một: 1: Bốc 2 lá bài; 2: Lấy một lá Trí Nang từ bộ bài hoặc bộ bài bỏ.`,
	spyingjia: "Nghênh Giá",
	spyingjia_info: "Kỹ năng giới hạn, sau khi lượt của một nhân vật kết thúc, nếu bạn đã sử dụng lớn hơn hoặc bằng hai lá bài chú cùng tên trong lượt này, bạn có thể bỏ một lá bài trên tay, khiến một nhân vật thực hiện một lượt bổ sung, khi bắt đầu lượt bổ sung này, người đó bốc 2 lá bài.",
	pot_lougui: "Thế Lâu Khuê",
	pot_lougui_prefix: "Thế",
	potguansha: "Quán Sa",
	potguansha_info: "Kỹ năng giới hạn, khi kết thúc giai đoạn Xuất Bài, bạn có thể thay thế tất cả bài của mình bằng một số lượng bài cơ bản tương ứng, sau đó giới hạn bài trên tay của bạn trong lượt này +X (X là số lượng bài cơ bản bạn nhận được).",
	potjiyu: "Cấp Ngự",
	potjiyu_info: "① Giai đoạn Xuất Bài mỗi lượt giới hạn một lần, bạn có thể bỏ một lá bài trên tay, ngẫu nhiên lấy từ bộ bài mỗi lá bài có loại khác với lá bài này. ② Mỗi giai đoạn giới hạn hai lần, khi bạn mất tất cả bài đã nhận được từ 【Cấp Ngự①】 trong giai đoạn này, bạn được thiết lập lại 【Cấp Ngự①】.",
	pot_yuji: "Thế Vu Cát",
	pot_yuji_prefix: "Thế",
	potdaozhuan: "Đạo Chuyển",
	potdaozhuan_info: "Mỗi lượt giới hạn một lần, bạn có thể đặt một lá bài của bạn hoặc của nhân vật trong lượt hiện tại vào bộ bài bỏ, xem như sử dụng một lá bài cơ bản (mỗi vòng giới hạn một lần với mỗi tên bài). Nếu nhân vật trong lượt hiện tại mất bài vì điều này, kỹ năng này sẽ mất hiệu lực trong vòng này.",
	potfuji: "Phù Tế",
	potfuji_info: "Giai đoạn Xuất Bài mỗi lượt giới hạn một lần, bạn có thể tiết lộ tối đa X lá bài và đưa cho số lượng nhân vật khác tương ứng, gọi là “Phù Tế” (X là số nhân vật khác trên bàn). Khi nhân vật khác dùng bài “Phù Tế” sẽ nhận được một lá bài cùng hoa với bài “Phù Tế”; sau đó nếu bài này là: 【Giết】, sát thương gây ra bởi bài này +1; 【Tránh】, sau khi kết toán người đó bốc một lá bài. Sau đó nếu số bài trên tay bạn là thấp nhất bàn, bạn bốc 2 lá, và 【Giết】 và 【Tránh】 tiếp theo bạn sử dụng được xem là có hiệu ứng tương ứng cho đến khi bắt đầu lượt tiếp theo của bạn.",
	pot_chendao: "Thế Trần Đáo",
	pot_chendao_prefix: "Thế",
	potwanglie: "Vãng Liệt",
	potwanglie_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể chọn một lá bài trên tay, bạn dùng lá bài này trong giai đoạn này không bị giới hạn khoảng cách và không thể bị đáp trả, và sau khi sử dụng lá bài này kết toán xong, bạn không thể dùng bài nhắm vào nhân vật khác trong giai đoạn này.",
	pothongyi: "Hoằng Nghị",
	pothongyi_info: "Kỹ năng khóa. ① Khi bắt đầu ván chơi, bạn nhận 4 dấu hiệu “Nghị”; Khi bạn gây ra hoặc chịu sát thương, bạn nhận 1 dấu hiệu “Nghị”; Bạn có tối đa 5 dấu hiệu “Nghị”. ② Giai đoạn Chuẩn Bị, bạn chọn một hạng mục, và khi kết thúc giai đoạn thực hiện hạng mục còn lại: 1. Bốc X lá bài (X là số dấu hiệu “Nghị” bạn hiện có); 2. Bỏ tất cả dấu hiệu “Nghị”.",
	pothongyi_append: `<span style="font-family: yuanli"><li>Kỹ năng này là bản Hải Ngoại</span>`,
	pangxi: "Thế Bàng Hi",
	pangxi_prefix: "Thế",
	mbxuye: "Súc Nghiệp",
	mbxuye_info: "Mỗi lượt giới hạn một lần, khi nhân vật có số bài trên tay ít nhất bàn chịu sát thương, bạn có thể khiến người đó bốc 2 lá, sau đó nếu số bài trên tay người đó trở thành nhiều nhất bàn, bạn đặt một lá bài trong khu vực của người đó lên đỉnh bộ bài.",
	mbkuangxiang: "Khuông Tương",
	mbkuangxiang_info: "Giai đoạn Xuất Bài mỗi lượt giới hạn một lần, bạn có thể đổi bài trên tay với một nhân vật khác có số bài trên tay không lớn hơn bạn, và cho đến trước khi bắt đầu giai đoạn Xuất Bài tiếp theo của bạn, sau khi bạn hoặc người đó mất tất cả bài nhận được từ việc đổi này, bạn có thể thực hiện một lần hiệu ứng của 【Súc Nghiệp】 (không bị ảnh hưởng bởi giới hạn số lần phát động).",
	sunsháo: "Thế Tôn Thiều",
	sunsháo_prefix: "Thế",
	mbganjue: "Cảm Quyết",
	mbganjue_info: "Giai đoạn Xuất Bài mỗi lượt giới hạn một lần, bạn có thể dùng một lá bài trong khu vực Trang Bị xem như một đòn 【Giết】 thông thường không tính số lần, không giới hạn khoảng cách và số lần, nếu nhân vật mục tiêu không có bài trên tay cùng màu với 【Giết】 này, người đó không thể đáp trả 【Giết】 này.",
	mbzhuji: "Trúc Kỹ",
	mbzhuji_info: "Khi kết thúc giai đoạn Xuất Bài, bạn có thể bỏ tất cả bài trên tay có cùng một hoa (tối thiểu một lá), lấy và sử dụng một lá bài Trang Bị cùng hoa đó từ bộ bài. Nếu số bài bạn bỏ lớn hơn hoặc bằng số bài trong khu vực Trang Bị của bạn khi bỏ bài, bạn chọn một: 1. Bốc 2 lá bài; 2. Hồi phục 1 điểm thể lực; 3. Nhận 1 điểm giáp.",
	mb_xiahoushang: "Thế Hạ Hầu Thượng",
	mb_xiahoushang_prefix: "Thế",
	mbtanfeng: "Thám Phong",
	mbtanfeng_info: "Giai đoạn Chuẩn Bị, bạn có thể chọn bất kỳ hạng mục nào: 1. Bỏ tối đa hai lá bài của một nhân vật, sau đó nếu số bài trên tay người đó nhỏ hơn hoặc bằng bạn, bạn bỏ qua giai đoạn Bốc Bài; 2. Gây 1 điểm sát thương Hỏa cho một nhân vật, sau đó nếu thể lực người đó nhỏ hơn hoặc bằng bạn, bạn bỏ qua giai đoạn Xuất Bài.",
	mb_yanghong: "Thế Dương Hoằng",
	mb_yanghong_prefix: "Thế",
	mbjianji: "Gian Kế",
	mbjianji_info: "Giai đoạn Xuất Bài mỗi lượt giới hạn một lần, bạn có thể bí mật chọn một lá bài trên tay, và khiến hai nhân vật thi điểm, nhân vật thắng xem như dùng một đòn 【Giết】 không giới hạn khoảng cách nhắm vào nhân vật thua, và trong lần thi điểm này, các nhân vật này có thể bí mật chọn cách dùng lá bài này để thi điểm. Sau đó nếu lá bài này là 【Giết】, bạn gây 1 điểm sát thương cho mỗi nhân vật đã chọn dùng lá bài này để thi điểm.",
	mbjianji_card: "Gian Kế",
	mbjianji_card_info: "Lá bài được chọn bí mật, có thể dùng để thi điểm",
	mbyuanmo: "Viễn Mô",
	mbyuanmo_info: "Mỗi lượt giới hạn hai lần, khi giai đoạn Chuẩn Bị hoặc khi bạn chịu sát thương, bạn có thể di chuyển một lá bài trên bàn, sau đó bạn có thể khiến nhân vật mất bài vì điều này bốc X lá (X là số nhân vật trong phạm vi tấn công của người đó bị giảm đi vì việc này và tối đa là 5).",
	mb_luyusheng: "Thế Lục Uất Sinh",
	mb_luyusheng_prefix: "Thế",
	mbrunwei: "Nhuận Vi",
	mbrunwei_info: "Giai đoạn Xuất Bài mỗi lượt giới hạn một lần, bạn có thể tiết lộ tối đa năm lá bài trên cùng bộ bài, khiến một nhân vật nhận được tất cả bài có cùng một màu trong số đó. Nếu làm vậy: 1. Mỗi giai đoạn giới hạn một lần, sau khi bạn mất thêm X lá bài nữa (X là số bài người đó nhận được vì điều này), kỹ năng này xem như chưa phát động nhưng không thể nhắm vào nhân vật đã nhận bài trong lượt này làm mục tiêu; 2. Khi giai đoạn này kết thúc, bạn bỏ số bài trên tay đã nhận được bằng cách này.",
	mbshuanghuai: "Sương Hoài",
	mbshuanghuai_info: "Mỗi lượt giới hạn một lần, khi nhân vật trong khoảng cách 1 với bạn chịu sát thương, bạn có thể chọn một: 1. Ngăn ngừa sát thương này; 2. Khiến người đó nhận một lá 【Đào】 từ bộ bài bỏ. Nếu nhân vật đó so với lần bạn phát động trước: giống nhau, bạn và người đó mỗi người bốc một lá; khác nhau, bạn mất 1 điểm thể lực.",
	mb_tianfeng: "Thế Điền Phong",
	mb_tianfeng_prefix: "Thế",
	mbganggeng: "Cương Ngạnh",
	mbganggeng_info: "Giai đoạn Xuất Bài mỗi lượt giới hạn một lần, bạn có thể đưa ít nhất hai lá bài trên tay cho một nhân vật khác. Khi kết thúc lượt, nếu số bài trên tay người đó: là nhiều nhất bàn, bạn bốc một lá; không phải nhiều nhất bàn, bạn bỏ một lá bài trong khu vực của người đó.",
	mbsijian: "Tử Gián",
	mbsijian_info: `Mỗi lượt giới hạn hai lần, khi bạn mất lá bài cuối cùng trên tay, hoặc khi bạn vào trạng thái hấp hối, bạn có thể chọn một: 1. Chọn một nhân vật khác, sau khi người đó dùng lá bài tiếp theo cần bỏ một lá bài. 2. Khiến nhân vật của lượt hiện tại bốc 2 lá bài. Nếu lúc này không có nhân vật nào trong trạng thái hấp hối, bạn có thể ${get.poptip("rule_beishui")}: Mất X điểm thể lực (X là số lần bạn đã phát động Bối Thủy trước đó).`,
	mb_huangzu: "Thế Hoàng Tổ",
	mb_huangzu_prefix: "Thế",
	mbchizhang: "Sy Trương",
	mbchizhang_info: "Bạn dùng bài sát thương không giới hạn khoảng cách. Khi bạn dùng một bài sát thương (trừ 【Sấm Sét】) trên tay chỉ định mục tiêu xong, bạn có thể bỏ một số lượng bài trên tay bất kỳ, các nhân vật khác không thể dùng hoặc đánh ra bài cùng màu với bài bạn đã bỏ theo cách này để đáp trả bài này.",
	mbduanyang: "Đoạn Ương",
	mbduanyang_info: "Mỗi lượt giới hạn một lần, khi bạn mất bài trên tay không phải do sử dụng, bạn có thể lấy ngẫu nhiên một lá 【Giết】 trong số đó đặt lên bài tướng, và khi giai đoạn này kết thúc sẽ sử dụng nó; 【Giết】 bạn dùng theo cách này sau khi gây sát thương, bạn có thể tái luyện tối đa hai lá bài trong khu vực của nhân vật bị thương, sau đó bốc 4 lá bài.",
	guoyuan: "Thế Quốc Uyên",
	guoyuan_prefix: "Thế",
	mbqingdao: "Thanh Đạo",
	mbqingdao_info: "Khi bài sát thương do nhân vật khác dùng nhắm vào bạn kết toán xong, nếu bạn: chịu sát thương vì bài này, thì bạn có thể lấy một lá 【Tránh】 từ bộ bài hoặc bộ bài bỏ, hoặc bỏ một lá bài trong khu vực của một nhân vật; không chịu sát thương vì bài này, thì bạn có thể lấy một lá 【Giết】 từ bộ bài hoặc bộ bài bỏ, hoặc dùng một lá bài trên tay (không giới hạn khoảng cách).",
	mbxiugeng: "Tu Canh",
	mbxiugeng_info: "Khi bắt đầu lượt, bạn có thể ghi nhớ số bài trên tay của tối đa hai nhân vật. Nếu làm vậy, khi bắt đầu giai đoạn Bốc Bài tiếp theo của các nhân vật này, nếu số bài trên tay người đó: nhỏ hơn hoặc bằng giá trị ghi nhớ, người đó bốc 2 lá; lớn hơn hoặc bằng giá trị ghi nhớ, giới hạn bài trên tay của người đó +1.",
	mbchenshe: "Trần Xá",
	mbchenshe_info: "Khi một nhân vật khác vào trạng thái hấp hối, bạn có thể lần lượt bỏ một lá bài của bạn, của nhân vật đó, của nguồn gây sát thương, nếu các nhân vật này đã bỏ tổng cộng ba lá bài theo cách này, và các lá bài này đều cùng hoa, thì người đó hồi phục thể lực lên tối đa, sau đó bạn mất kỹ năng này.",
	mb_zhangyan: "Thế Trương Yến",
	mb_zhangyan_prefix: "Thế",
	mbfeijing: "Phi Kính",
	mbfeijing_info: "Bạn có thể dùng một lá bài chú loại sát thương xem như 【Giết】 để dùng hoặc đánh ra. Mỗi lượt giới hạn hai lần, khi bạn dùng 【Giết】 chỉ định một mục tiêu duy nhất, bạn có thể khiến tất cả nhân vật theo chiều ngược chiều kim đồng hồ hoặc thuận chiều kim đồng hồ giữa bạn và mục tiêu đó đồng thời tiết lộ và lần lượt bỏ một lá bài trên tay, sau đó bạn có thể chọn một màu, khiến nhân vật đã bỏ bài màu đó trở thành mục tiêu bổ sung của 【Giết】 này.",
	mbxiaoge: "Kiêu Qua",
	mbxiaoge_info: "Kỹ năng khóa, 【Giết】 bạn dùng: đối với nhân vật trở thành mục tiêu của 【Giết】 này vì 【Phi Kính】, khi gây sát thương sẽ ngăn ngừa, sau đó bạn hồi phục 1 điểm thể lực và nhận được bài đã bỏ vì 【Phi Kính】 của người đó; nếu chỉ chỉ định một nhân vật làm mục tiêu, sau khi 【Giết】 này kết toán bạn xem như dùng một đòn 【Quyết Đấu】 nhắm vào người đó.",
	pot_weiyan: "Thế Ngụy Diên",
	pot_weiyan_prefix: "Thế",
	potzhongao: "Trung Ngạo",
	potzhongao_info: `Kỹ năng sứ mệnh, ① Khi bắt đầu ván chơi, bạn nhận được ${get.poptip("potkuanggu")}. ② Thành công: Sau khi bạn giết một nhân vật, nâng cấp 【Cuồng Cốt】, sau đó nếu số bài bạn dùng trong giai đoạn này: nhỏ hơn số bài đã bỏ vì 【Tráng Thệ】, bốc một lá; nhỏ hơn thể lực đã mất vì 【Tráng Thệ】, hồi phục 1 điểm thể lực (nếu thể lực đã đầy thì đổi thành bốc một lá). ③ Thất bại: Bạn vào trạng thái hấp hối, hoặc bạn không thực hiện 【Tráng Thệ】 khi bắt đầu giai đoạn Xuất Bài, mất 【Tráng Thệ】 và nhận được ${get.poptip("kunfen")}.`,
	potzhuangshi: "Tráng Thệ",
	potzhuangshi_info: "Khi bắt đầu giai đoạn Xuất Bài, bạn có thể thực hiện bất kỳ hạng mục nào: 1. Bỏ một số lượng bài trên tay bất kỳ, khiến một số lượng bài tương ứng bạn dùng đầu tiên trong giai đoạn này không giới hạn khoảng cách và không thể bị đáp trả; 2. Mất một số điểm thể lực bất kỳ, khiến một số lượng bài tương ứng bạn dùng đầu tiên trong giai đoạn này không tính vào giới hạn số lần.",
	potzhuangshi_tag: "Đã chọn bỏ",
	potyinzhan: "Ẩm Chiến",
	potyinzhan_info: `Kỹ năng khóa, khi bạn dùng 【Giết】 gây sát thương cho một nhân vật, nếu: 1. Thể lực của bạn nhỏ hơn hoặc bằng người đó, sát thương này +1; 2. Số bài của bạn nhỏ hơn hoặc bằng người đó, sau khi 【Giết】 này kết toán bạn bỏ một lá bài của người đó; ${get.poptip("rule_chengshi")}: bạn hồi phục 1 điểm thể lực, nhận được lá bài đã bỏ của người đó.`,
	potkuanggu: "Cuồng Cốt",
	potkuanggu_info: "Sau khi bạn gây sát thương cho một nhân vật trong khoảng cách 1 trở lại, bạn có thể chọn một: 1. Hồi phục 1 điểm thể lực; 2. Bốc một lá bài.",
	potkuanggu_pot_weiyan_achieve: "Cuồng Cốt·Cấp Hai",
	potkuanggu_pot_weiyan_achieve_info: `Sau khi bạn gây sát thương cho một nhân vật trong khoảng cách 1 trở lại, bạn có thể chọn một: 1. Hồi phục 1 điểm thể lực; 2. Bốc một lá bài; 3. ${get.poptip("rule_beishui")}: Bỏ một lá bài và khiến số lần bạn dùng 【Giết】 trong giai đoạn này +1.`,
	pot_lusu: "Thế Lỗ Túc",
	pot_lusu_prefix: "Thế",
	pothaoshi: "Hảo Thi",
	pothaoshi_info: "Giai đoạn Kết Thúc, bạn có thể chọn một nhân vật khác: cho đến khi bắt đầu lượt tiếp theo của bạn, người đó có thể dùng hoặc đánh ra bài trên tay của bạn như bài trên tay của mình, và hai lần đầu người đó khiến bạn mất lá bài cuối cùng vì điều này, bạn sẽ bốc bài lên 3 lá.",
	potdimeng: "Đế Minh",
	potdimeng_info: "Giai đoạn Xuất Bài mỗi lượt giới hạn một lần, bạn có thể chọn hai nhân vật có chênh lệch số bài trên tay nhỏ hơn hoặc bằng 3, khiến họ đổi bài trên tay cho nhau. Sau đó bạn chọn một: 1. Bỏ X lá bài (không đủ thì bỏ hết); 2. Nhân vật có ít bài hơn sau khi đổi bốc X lá bài (X là thể lực bạn đã mất).",
	mb_sunjun: "Thế Tôn Tuấn",
	mb_sunjun_prefix: "Thế",
	mbxiongtu: "Hung Đồ",
	mbxiongtu_info: "Giai đoạn Xuất Bài mỗi lượt giới hạn một lần, bạn có thể tiết lộ một lá bài trên tay của một nhân vật khác và chọn một: 1. Bỏ lá bài này; 2. Bỏ X lá bài và gây 1 điểm sát thương cho người đó (X là số hoa chưa từng vào bộ bài bỏ trong lượt này).",
	mbxianshuai: "Tiên Suất",
	mbxianshuai_info: "Kỹ năng khóa, lá bài đầu tiên của mỗi hoa trên tay bạn dùng trong lượt không tính vào giới hạn số lần và không giới hạn số lần.",
	mb_chenzhi: "Thế Trần Chi",
	mb_chenzhi_prefix: "Thế",
	mbquanchong: "Quyền Sủng",
	mbquanchong_info: "Kỹ năng khóa, mỗi vòng giới hạn một lần, khi kết thúc giai đoạn, bạn bỏ tất cả bài, thực hiện một lượt bổ sung, nếu thể lực của bạn không phải là lớn nhất duy nhất toàn bàn, thì khi bắt đầu lượt thực hiện theo cách này bạn mất 1 điểm thể lực.",
	mbrenxing: "Nhậm Hành",
	mbrenxing_info: "Mỗi vòng giới hạn hai lần, lần đầu tiên trong mỗi lượt có bài bị bỏ không phải ở giai đoạn Bỏ Bài, bạn có thể chọn một: 1. Cùng với nhân vật của lượt hiện tại mỗi người bốc một lá bài; 2. Bỏ một lá bài của nhân vật chưa dùng hoặc đánh ra 【Giết】 trong lượt này.",
	pot_xinxianying: "Thế Tân Hiến Anh",
	pot_xinxianying_prefix: "Thế",
	potjiejie: "Giới Tiết",
	potjiejie_info: `Giai đoạn Xuất Bài của mỗi nhân vật giới hạn một lần, nhân vật của lượt hiện tại có thể khiến bạn xem bài trên tay của họ, sau đó bạn có thể chọn một hoa, nếu bài trên tay họ: 1. Có chứa hoa này, họ dùng bài có hoa này trong lượt này không giới hạn số lần, sau đó bỏ bài có hoa còn lại trên tay; 2. Không chứa hoa này, họ nhận được một lá bài có hoa này. Mỗi vòng giới hạn hai lần, nếu số hoa mà họ đã tiết lộ bài cho bạn theo cách này trong vòng này là nhiều nhất duy nhất, bạn phát động một lần ${get.poptip("potqingshi")} nhắm vào họ.`,
	potqingshi: "Thanh Thức",
	potqingshi_info: "Khi bạn chịu sát thương, bạn có thể chọn một nhân vật, sau đó nếu bạn và người đó cùng trận doanh: giống nhau: bạn và người đó mỗi người bốc một lá; khác nhau: bạn bỏ một lá bài của bạn và một lá của người đó.",
	pot_huanjie: "Thế Hoàn Giai",
	pot_huanjie_prefix: "Thế",
	potgongmou: "Cộng Mưu",
	potgongmou_info: `Giai đoạn Chuẩn Bị, bạn có thể đổi bài trên tay với một nhân vật khác, nếu làm vậy, bạn nhận được kỹ năng ${get.poptip("qice")} và người đó nhận được kỹ năng ${get.poptip("kanpo")} cho đến khi kết thúc lượt này.`,
	potzhengshuo: "Chính Sóc",
	potzhengshuo_info: "Kỹ năng giới hạn, giai đoạn Xuất Bài, bạn có thể khiến tất cả nhân vật bỏ tất cả bài trên tay, sau đó xào bài. Nếu làm vậy, tất cả nhân vật mỗi người bốc 4 lá bài.",
	pot_dengai: "Thế Đặng Ngải",
	pot_dengai_prefix: "Thế",
	pottuntian: "Đồn Điền",
	pottuntian_info: "Kỹ năng Tích Lực (0/0), khi bạn mất bài không phải bài sát thương, bạn nhận được 1 điểm Tích Lực; giai đoạn Xuất Bài mỗi lượt giới hạn một lần, bạn có thể tiêu hao một lượng điểm Tích Lực bất kỳ, khiến tối đa một số lượng nhân vật tương ứng mỗi người lấy một lá bài Hồng Đào từ bộ bài hoặc bộ bài bỏ; khi bắt đầu lượt của một nhân vật, nếu Tích Lực của bạn đã đầy, bạn bốc một lá và giới hạn Tích Lực tối đa +1.",
	potjixi: "Cấp Tập",
	potjixi_info: "Khi kết thúc lượt của một nhân vật, nếu trên bàn tồn tại nhân vật khác mà bạn đã dùng bài chỉ định làm mục tiêu trong lượt này, bạn có thể bỏ một lá bài của nhân vật đang trong lượt, sau đó xem như sử dụng một đòn 【Thuận Thủ Khiên Dương】 không nhìn khoảng cách chỉ định bất kỳ số lượng nhân vật nào trong số đó làm mục tiêu.",
	potzaoxian: "Tạc Hiểm",
	potzaoxian_info: "Kỹ năng khóa, khi số lượng điểm Tích Lực bạn tiêu hao cùng một lúc: không nhỏ hơn 2, bạn lấy một lá 【Vô Trung Sinh Hữu】 từ bộ bài bỏ; không nhỏ hơn 5, bạn lấy một lá 【Vô Tiết Khả Kích】 từ bộ bài bỏ; không nhỏ hơn 7, bạn lấy một lá 【Ngũ Cốc Phong Đăng】 từ bộ bài bỏ.",
	old_pottuntian: "Đồn Điền",
	old_pottuntian_info: "Kỹ năng Tích Lực (1/3), giai đoạn Xuất Bài mỗi lượt giới hạn một lần, bạn có thể giảm 1 điểm Tích Lực, khiến một nhân vật đặt một lá bài lên bài tướng của bạn, gọi là “Điền”. Khi kết thúc lượt, bạn bốc X lá (X là số lượng điểm Tích Lực bạn đã mất trong lượt này). Khi bạn mất bài hoặc “Điền” ngoài lượt của mình, bạn nhận được 1 điểm Tích Lực.",
	old_potjixi: "Cấp Tập",
	old_potjixi_info: `Nếu bạn có kỹ năng ${get.poptip("old_pottuntian")}, bạn có thể bỏ 1 dấu hiệu “Tranh Vinh”, sau đó dùng hoặc đánh ra một lá “Điền” theo cách không tính số lần và không giới hạn khoảng cách.`,
	old_potzaoxian: "Tạc Hiểm",
	old_potzaoxian_info: `Kỹ năng khóa, khi kết thúc lượt của một nhân vật, nếu bạn có kỹ năng ${get.poptip("old_pottuntian")}, và bạn có 0 hoặc 3 điểm Tích Lực, bạn nhận được 1 dấu hiệu “Tranh Vinh”.`,
	pot_chenjiao: "Thế Trần Kiểu",
	pot_chenjiao_prefix: "Thế",
	potqingyan: "Thanh Nghiêm",
	potqingyan_info: "Khi bạn cần sử dụng 【Tránh】 hoặc 【Vô Tiết Khả Kích】, bạn có thể tiết lộ X lá bài trên tay (X là số lần phát động kỹ năng này trong vòng này và tối đa là 5) và xem như đã sử dụng nó, sau đó kỹ năng này mất hiệu lực cho đến khi trên tay bạn không còn lá bài nào đã tiết lộ theo cách này.",
	potceduan: "Sách Đoạn",
	potceduan_info: "Giai đoạn Xuất Bài mỗi lượt giới hạn một lần, bạn có thể chọn một nhân vật có phạm vi tấn công bao gồm bạn, tất cả nhân vật trong phạm vi tấn công của người đó đồng thời tiết lộ một lá bài trên tay, sau đó bạn dùng tất cả bài có màu sắc (đen/đỏ) có số lượng bài tiết lộ nhiều nhất trên tay bạn xem như một đòn 【Giết】 không tính vào giới hạn số lần sử dụng nhắm vào người đó, nếu gây sát thương, bạn bốc một lá bài.",
	pot_zanghong: "Thế Tạng Hồng",
	pot_zanghong_prefix: "Thế",
	pot_liezhi: "Liệt Chí",
	pot_liezhi_info: "Mỗi lượt giới hạn một lần, bạn có thể giảm 1 điểm giới hạn thể lực, xem như sử dụng một 【Đào】/【Rượu】 không giới hạn số lần.",
	pot_jugu: "Cứ Cô",
	pot_jugu_info: "Khi bạn trở thành mục tiêu của một lá bài, nếu bạn chưa bị thương, bạn có thể bốc 2 lá bài, sau đó bỏ X lá bài (X là số lần bạn đã phát động kỹ năng này trong lượt này).",
};

export default translates;
