import { lib, game, ui, get, ai, _status } from "noname";

const translates = {
	re_yuanshao: "Viên Thiệu",
	re_lusu: "Lỗ Túc",
	re_yuji: "Vu Cát",
	wangji: "Vương Cơ",
	kuailiangkuaiyue: "Khoái Lương Khoái Việt",
	sunliang: "Tôn Lượng",
	yl_luzhi: "Lư Thực",
	xuyou: "Hứa Du",
	luji: "Lục Tích",
	wangping: "Vương Bình",
	yanyan: "Nghiêm Nhan",

	zhugezhan: "Gia Cát Chiêm",
	lukang: "Lục Kháng",
	haozhao: "Hách Chiêu",
	yl_yuanshu: "Tân Sát Viên Thuật",
	yl_yuanshu_prefix: "Tân Sát",
	zhangxiu: "Trương Tú",
	chendao: "Trần Đáo",
	guanqiujian: "Vô Khâu Kiệm",
	zhoufei: "Chu Phi",

	nzry_jianxiang: "Tiến Giáng",
	nzry_jianxiang_info: "Khi bạn trở thành mục tiêu của lá bài do nhân vật khác sử dụng, bạn có thể khiến một nhân vật có số lượng bài trên tay ít nhất rút một lá bài.",
	nzry_shenshi: "Thẩm Thời",
	nzry_shenshi_info: "Kỹ năng chuyển đổi, Dương: Trong giai đoạn ra bài giới hạn một lần, bạn có thể đưa một lá bài cho một nhân vật khác có số bài trên tay nhiều nhất, sau đó gây cho nhân vật đó 1 điểm sát thương, nếu nhân vật đó vì vậy mà tử vong, bạn có thể khiến một nhân vật rút bài đến khi đủ bốn lá. Âm: Sau khi nhân vật khác gây sát thương cho bạn, bạn có thể xem bài trên tay của nhân vật đó, sau đó đưa cho nhân vật đó một lá bài, khi kết thúc lượt của nhân vật hiện tại, nếu lá bài này vẫn nằm trong khu vực bài trên tay hoặc khu vực trang bị của nhân vật đó, bạn rút bài đến khi đủ bốn lá.",
	nzry_mingren: "Minh Nhiệm",
	nzry_mingren_info: "① Khi trò chơi bắt đầu, bạn rút hai lá bài, sau đó đặt một lá bài trên tay lên trên thẻ võ tướng của bạn, gọi là “Nhiệm”. ② Giai đoạn kết thúc, bạn có thể dùng một lá bài trên tay để thay thế “Nhiệm”.",
	nzry_zhenliang: "Trinh Lương",
	nzry_zhenliang_info: "Kỹ năng chuyển đổi, Dương: Trong giai đoạn ra bài giới hạn một lần, bạn có thể bỏ một lá bài có cùng màu sắc với “Nhiệm” và gây cho một nhân vật trong phạm vi tấn công 1 điểm sát thương. Âm: Khi lá bài bạn sử dụng hoặc đánh ra ngoài lượt kết thúc giải quyết, nếu lá bài này có cùng màu sắc với “Nhiệm”, bạn có thể khiến một nhân vật rút một lá bài.",
	nzry_chenglve: "Thành Lược",
	nzry_chenglve_info: "Kỹ năng chuyển đổi, trong giai đoạn ra bài giới hạn một lần, Dương: Bạn có thể rút một lá bài, sau đó bỏ hai lá bài trên tay. Âm: Bạn có thể rút hai lá bài, sau đó bỏ một lá bài trên tay. Nếu làm như vậy, cho đến khi kết thúc lượt này, bạn sử dụng các lá bài có cùng hoa sắc với lá bài đã bỏ sẽ không bị giới hạn khoảng cách và số lần.",
	nzry_cunmu: "Thốn Mục",
	nzry_cunmu_info: "Kỹ năng khóa, khi bạn rút bài, đổi thành rút bài từ dưới đáy chồng bài.",
	nzry_kuizhu: "Quỵ Tru",
	nzry_kuizhu_info: "Sau khi giai đoạn bỏ bài kết thúc, bạn có thể chọn một mục: ① Khiến tối đa X nhân vật mỗi người rút một lá bài. ② Gây cho bất kỳ số lượng nhân vật nào có tổng sinh lực bằng X mỗi người 1 điểm sát thương. (X là số lá bài bạn đã bỏ trong giai đoạn này)",
	nzry_zhizheng: "Xế Chính",
	rechezheng: "Xế Chính",
	nzry_zhizheng_info: "Kỹ năng khóa, trong giai đoạn ra bài của bạn, khi bạn gây sát thương cho nhân vật khác trong phạm vi tấn công không bao gồm bạn, ngăn chặn sát thương này. Khi giai đoạn ra bài kết thúc, nếu số lá bài bạn đã sử dụng trong giai đoạn này ít hơn số lượng các nhân vật này, bạn bỏ một lá bài của một trong số các nhân vật đó.",
	nzry_lijun1: "Lập Quân",
	nzry_lijun: "Lập Quân",
	nzry_lijun_info: "Kỹ năng chủ công, trong giai đoạn ra bài của nhân vật thuộc thế lực Ngô khác giới hạn một lần, sau khi người đó sử dụng 【Sát】 kết thúc giải quyết, có thể đưa lá bài vật thể tương ứng với 【Sát】 này cho bạn, sau đó bạn có thể khiến người đó rút một lá bài và tăng giới hạn số lần sử dụng 【Sát】 trong giai đoạn này thêm 1.",
	nzry_huaiju: "Hoài Quất",
	nzry_huaiju_info: "Kỹ năng khóa, khi trò chơi bắt đầu, bạn nhận được 3 dấu ấn “Quýt”. (Khi nhân vật có “Quýt” chịu sát thương, ngăn chặn sát thương này, sau đó xóa đi một dấu ấn “Quýt”; nhân vật có “Quýt” trong giai đoạn rút bài sẽ rút thêm một lá bài)",
	tachibana_effect: "Hoài Quất",
	nzry_yili: "Di Lễ",
	nzry_yili_info: "Khi giai đoạn ra bài bắt đầu, bạn có thể mất 1 điểm sinh lực hoặc xóa đi một dấu ấn “Quýt”, sau đó khiến một nhân vật khác nhận được một dấu ấn “Quýt”.",
	nzry_zhenglun: "Chỉnh Luận",
	nzry_zhenglun_info: "Nếu bạn không có “Quýt”, bạn có thể bỏ qua giai đoạn rút bài sau đó nhận được một dấu ấn “Quýt”.",
	nzry_feijun: "Phi Quân",
	nzry_feijun_info: "Trong giai đoạn ra bài giới hạn một lần. Bạn có thể bỏ một lá bài, sau đó chọn một mục: ⒈ Khiến một nhân vật có số bài trên tay nhiều hơn bạn đưa cho bạn một lá bài; ⒉ Khiến một nhân vật có số bài trong khu vực trang bị nhiều hơn bạn bỏ một lá bài trang bị.",
	nzry_binglve: "Binh Lược",
	nzry_binglve_info: "Kỹ năng khóa, khi bạn phát động “Phi Quân”, nếu mục tiêu không giống với các mục tiêu bạn đã chỉ định trước đó, bạn rút hai lá bài.",
	nzry_juzhan: "Cự Chiến",
	nzry_juzhan_info: "Kỹ năng chuyển đổi, Dương: Sau khi bạn trở thành mục tiêu của 【Sát】 của nhân vật khác, bạn có thể cùng người đó mỗi người rút một lá bài, sau đó người đó trong lượt này không thể sử dụng bài lên bạn nữa. Âm: Sau khi bạn sử dụng 【Sát】 chỉ định một nhân vật làm mục tiêu, bạn có thể nhận một lá bài của người đó, sau đó bạn trong lượt này không thể sử dụng bài lên người đó nữa.",

	liangyin: "Lương Nhân",
	liangyin_info: "Khi có lá bài di chuyển ra ngoài trò chơi, bạn có thể khiến một nhân vật có số bài trên tay nhiều hơn bạn rút một lá bài; khi có lá bài từ ngoài trò chơi gia nhập vào bài trên tay của bất kỳ nhân vật nào, bạn có thể khiến một nhân vật có số bài trên tay ít hơn bạn bỏ một lá bài.",
	kongsheng: "Không Thanh",
	kongsheng_info: "Giai đoạn chuẩn bị, bạn có thể đặt bất kỳ số lượng lá bài nào lên trên thẻ võ tướng của bạn; giai đoạn kết thúc, bạn sử dụng các lá bài trang bị trên thẻ võ tướng, và nhận các lá bài khác trên thẻ võ tướng.",
	kongsheng2: "Không Thanh",
	kongsheng2_info: "",
	xinfu_zuilun: "Tội Luận",
	xinfu_zuilun_info: "Giai đoạn kết thúc, bạn có thể xem ba lá bài trên cùng của chồng bài, mỗi khi bạn thỏa mãn một mục dưới đây thì giữ lại một lá, sau đó đặt số bài còn lại về theo thứ tự bất kỳ: 1. Bạn đã gây sát thương trong lượt này; 2. Bạn chưa bỏ bài trong lượt này; 3. Số bài trên tay là ít nhất toàn trường. Nếu đều không thỏa mãn, bạn và một nhân vật khác mất 1 điểm sinh lực.",
	xinfu_fuyin: "Phụ Ấm",
	xinfu_fuyin_info: "Kỹ năng khóa, sau khi bạn lần đầu tiên trong mỗi lượt trở thành mục tiêu của 【Sát】 hoặc 【Quyết Đấu】, nếu số bài trên tay của bạn ít hơn hoặc bằng nhân vật đó, lá bài này vô hiệu với bạn.",
	drlt_wanglie: "Vãng Liệt",
	drlt_wanglie_info: "① Giai đoạn ra bài, lá bài đầu tiên bạn sử dụng không bị giới hạn khoảng cách. ② Khi bạn sử dụng bài trong giai đoạn ra bài, bạn có thể khiến lá bài này không thể bị hưởng ứng, sau đó bạn trong giai đoạn này không thể sử dụng bài nữa.",
	drlt_xiongluan: "Hùng Loạn",
	drlt_xiongluan_info: "Kỹ năng hạn định, giai đoạn ra bài, bạn có thể phế bỏ khu vực phán xét và khu vực trang bị của mình, sau đó chỉ định một nhân vật khác. Cho đến khi kết thúc lượt, bạn sử dụng bài lên nhân vật đó không bị giới hạn khoảng cách và số lần, nhân vật đó không thể sử dụng và đánh ra bài trên tay.",
	drlt_congjian: "Tòng Gián",
	drlt_congjian_info: "Khi bạn trở thành mục tiêu của lá bài Cẩm Nang, nếu số mục tiêu của lá bài này nhiều hơn 1, bạn có thể đưa cho một trong số các nhân vật mục tiêu khác một lá bài, sau đó rút một lá bài, nếu bạn đưa ra lá bài trang bị, đổi thành rút hai lá bài.",
	drlt_yongsi: "Dung Tứ",
	drlt_yongsi_info: "Kỹ năng khóa, giai đoạn rút bài, bạn đổi thành rút X lá bài (X là số thế lực còn sống); giai đoạn kết thúc ra bài, nếu trong lượt này bạn: 1. Không gây sát thương, rút bài đến khi bằng sinh lực hiện tại; 2. Gây sát thương vượt quá 1 điểm, giới hạn bài trên tay lượt này đổi thành số sinh lực đã mất.",
	drlt_weidi: "Ngụy Đế",
	weidi_tag: "Ngụy Đế",
	drlt_weidi_info: "Kỹ năng chủ công, khi giai đoạn bỏ bài bắt đầu, nếu số bài trên tay của bạn nhiều hơn giới hạn bài trên tay, bạn có thể đưa tối đa X lá bài trên tay lần lượt cho các nhân vật thuộc thế lực Quần hùng khác với số lượng tương đương (X là hiệu số giữa số bài trên tay và giới hạn bài trên tay của bạn).",
	drlt_qianjie: "Khiêm Tiết",
	drlt_qianjie_info: "Kỹ năng khóa, khi bạn bị đặt ngang, hủy bỏ nó. Bạn không thể trở thành mục tiêu của Cẩm Nang trì hoãn. Bạn không thể trở thành mục tiêu của tỷ bài của nhân vật khác.",
	drlt_jueyan: "Quyết Yển",
	drlt_jueyan_info: `Giai đoạn ra bài giới hạn một lần, bạn có thể phế bỏ một loại ô trang bị, sau đó thực hiện mục tương ứng: Ô vũ khí, bạn trong lượt này tăng giới hạn số lần sử dụng 【Sát】 thêm 3 và cả ván đấu này tăng giới hạn số lần sử dụng 【Sát】 thêm 1; Ô giáp trụ, bạn rút ba lá bài, và cả ván đấu này tăng giới hạn bài trên tay thêm 3; Ô tọa kỵ, bạn trong cả ván đấu này sử dụng bài không giới hạn khoảng cách; Ô bảo vật, bạn nhận được ${get.poptip("rejizhi")}. Sau đó sửa đổi 〖Quyết Yển〗.`,
	drlt_jueyan_rewrite: "Quyết Yển · Cải",
	drlt_jueyan_rewrite_info: `Giai đoạn ra bài giới hạn một lần, bạn có thể phế bỏ một loại ô trang bị, sau đó thực hiện mục tương ứng: Ô vũ khí, bạn trong lượt này tăng giới hạn số lần sử dụng 【Sát】 thêm 3; Ô giáp trụ, bạn rút ba lá bài, và trong lượt này tăng giới hạn bài trên tay thêm 3; Ô tọa kỵ, bạn trong lượt này sử dụng bài không giới hạn khoảng cách; Ô bảo vật, bạn nhận được ${get.poptip("rejizhi")} cho đến khi kết thúc lượt.`,
	drlt_poshi: "Phá Thế",
	drlt_poshi_info: `Kỹ năng thức tỉnh, khi giai đoạn chuẩn bị bắt đầu, nếu các ô trang bị của bạn đều đã bị phế bỏ hoặc sinh lực bằng 1, bạn giảm 1 điểm giới hạn sinh lực, rút bài đến khi bằng giới hạn sinh lực, mất 〖Quyết Yển〗 và nhận được ${get.poptip("drlt_huairou")}.`,
	drlt_huairou: "Hoài Nhu",
	drlt_huairou_info: "Trong giai đoạn ra bài, bạn có thể đúc lại lá bài trang bị.",
	drlt_zhengu: "Trấn Cốt",
	drlt_zhengu2: "Trấn Cốt",
	drlt_zhengu_info: "Giai đoạn kết thúc, bạn có thể chọn một nhân vật khác, sau khi lượt của bạn kết thúc và khi lượt tiếp theo của nhân vật đó kết thúc, người đó rút bài đến hoặc bỏ bài còn X lá. (X là số bài trên tay của bạn và tối đa là 5)",
	drlt_zhenrong: "Chinh Vinh",
	drlt_zhenrong_info: "Sau khi bạn gây sát thương cho nhân vật khác, nếu bài trên tay của người đó nhiều hơn bạn, bạn có thể đặt một lá bài của người đó lên trên thẻ võ tướng của bạn, gọi là “Vinh”.",
	drlt_hongju: "Hồng Cử",
	drlt_hongju_info: `Kỹ năng thức tỉnh, giai đoạn chuẩn bị, nếu số lượng “Vinh” lớn hơn hoặc bằng 3 và trên sân có nhân vật tử vong, bạn có thể dùng bất kỳ số lượng lá bài trên tay nào để thay thế số lượng “Vinh” tương đương, sau đó giảm 1 điểm giới hạn sinh lực và nhận được ${get.poptip("drlt_qingce")}.`,
	drlt_qingce: "Thanh Trắc",
	drlt_qingce_info: "Trong giai đoạn ra bài, bạn có thể xóa đi một lá “Vinh”, sau đó bỏ một lá bài trong khu vực trang bị hoặc khu vực phán xét của một nhân vật.",

	zhengrong: "Chinh Vinh",
	hongju: "Hồng Cử",
	qingce: "Thanh Trắc",
	qingce_backup: "Thanh Trắc",
	zhengrong_info: "Sau khi bạn sử dụng lá bài Cơ bản hoặc Cẩm Nang có nhãn 「Sát thương」 chỉ định mục tiêu, bạn có thể đặt một lá bài của một nhân vật mục tiêu có số bài trên tay không nhỏ hơn bạn lên trên thẻ võ tướng của bạn, gọi là 「Vinh」.",
	hongju_info: `Kỹ năng thức tỉnh, giai đoạn chuẩn bị, nếu số lượng 「Vinh」 trên thẻ võ tướng của bạn không nhỏ hơn 3, bạn kích hoạt kỹ năng này. Bạn có thể dùng bất kỳ số lượng bài trên tay nào để trao đổi số lượng 「Vinh」 tương đương. Bạn giảm 1 điểm giới hạn sinh lực và nhận được kỹ năng ${get.poptip("qingce")}.`,
	qingce_info: "Trong giai đoạn ra bài, bạn có thể nhận một lá 「Vinh」 và bỏ một lá bài trên tay, sau đó bỏ một lá bài trên sân.",

	jianchu: "Kiện Xuất",
	jianchu_info: "Sau khi bạn sử dụng 【Sát】 chỉ định một nhân vật làm mục tiêu, bạn có thể bỏ một lá bài của người đó, nếu lá bài bị bỏ theo cách này là bài trang bị, 【Sát】 này không thể bị hưởng ứng bởi 【Thiểm】, nếu không phải bài trang bị, nhân vật đó nhận được 【Sát】 này.",
	redimeng: "Đế Minh",
	redimeng_info: "Trong giai đoạn ra bài giới hạn một lần, bạn có thể bỏ X lá bài chọn hai nhân vật khác (X là hiệu số bài trên tay của hai nhân vật này), bạn trộn lẫn bài trên tay của họ, sau đó khiến một trong hai nhân vật nhận được một lá trong đó, và khiến nhân vật còn lại nhận được một lá trong đó, sau đó lặp lại quy trình này cho đến khi các lá bài này đều được nhận hết.",
	reluanji: "Loạn Kích",
	reluanji_info: "Bạn có thể dùng hai lá bài trên tay có hoa sắc không giống với hoa sắc bạn đã chuyển hóa theo cách này trong lượt này để sử dụng như 【Vạn Tiễn Tề Phát】, sau đó khi một nhân vật vì hưởng ứng lá bài này mà đánh ra 【Thiểm】, nhân vật đó rút một lá bài. Nếu 【Vạn Tiễn Tề Phát】 bạn sử dụng theo cách này không gây sát thương, bạn có thể sau khi lá bài này kết thúc giải quyết rút X lá bài. (X là số mục tiêu của lá bài này)",
	xintianxiang: "Thiên Hương",
	xintianxiang2: "Thiên Hương",
	xintianxiang3: "Thiên Hương",
	xintianxiang4: "Thiên Hương",
	xintianxiang_bg: "Hương",
	xintianxiang_info: "Khi bạn chịu sát thương, bạn có thể bỏ một lá bài Cơ, chuyển sát thương này cho một nhân vật khác, sau đó bạn chọn một mục: Khiến nhân vật đó rút X lá bài (X là số sinh lực đã mất của người đó); hoặc ngăn chặn tất cả sát thương người đó gây ra và phải chịu, và kỹ năng này vô hiệu cho đến khi bắt đầu lượt tiếp theo của bạn.",
	xinshensu: "Thần Tốc",
	xinshensu_info: "Bạn có thể chọn từ một đến ba mục: 1. Bỏ qua giai đoạn phán xét và giai đoạn rút bài; 2. Bỏ qua giai đoạn ra bài và bỏ một lá bài trang bị; 3. Bỏ qua giai đoạn bỏ bài và lật mặt thẻ võ tướng của bạn. Mỗi khi bạn chọn một mục, coi như bạn sử dụng một lá 【Sát】 không giới hạn khoảng cách lên một nhân vật khác.",
	yinghun: "Anh Hồn",
	yinghun_info: "Khi giai đoạn chuẩn bị bắt đầu, bạn có thể khiến một nhân vật khác thực hiện một mục: Rút X lá bài, sau đó bỏ một lá bài; hoặc rút một lá bài, sau đó bỏ X lá bài (X là số sinh lực đã mất của bạn).",
	gzyinghun: "Anh Hồn",
	gzyinghun_info: "Khi giai đoạn chuẩn bị bắt đầu, nếu bạn đã bị thương, bạn có thể khiến một nhân vật khác thực hiện một mục: Rút X lá bài, sau đó bỏ một lá bài; hoặc rút một lá bài, sau đó bỏ X lá bài (X là số sinh lực đã mất của bạn).",

	tiaoxin: "Khiêu Hấn",
	zhiji: "Chí Kế",
	zhiji_draw: "Rút bài",
	zhiji_recover: "Hồi máu",
	xiangle: "Hưởng Lạc",
	fangquan: "Phóng Quyền",
	ruoyu: "Nhược Ngu",
	qiaobian: "Xảo Biến",
	tuntian: "Đồn Điền",
	tuntian_bg: "Điền",
	zaoxian: "Tạc Hiểm",
	jixi: "Cấp Tập",
	jiang: "Kích Ngang",
	hunzi: "Hồn Tư",
	zhiba: "Chế Bá",
	zhiba2: "Chế Bá",
	zhijian: "Trực Gián",
	guzheng: "Cố Chính",
	beige: "Bi Ca",
	duanchang: "Đoạn Tràng",
	// fushen:'Phụ Thân',
	huashen: "Hóa Thân",
	xinsheng: "Tân Sinh",
	qimou: "Kỳ Mưu",
	xinqiangxi: "Cường Kích",
	xinjushou: "Cứ Thủ",
	xinjiewei: "Giải Vây",
	retianxiang: "Thiên Hương",
	retianxiang_info: "Khi bạn chịu sát thương, bạn có thể bỏ một lá bài Cơ trên tay, ngăn chặn sát thương này và chọn một nhân vật khác, sau đó bạn chọn một mục: 1. Khiến người đó chịu 1 điểm sát thương do nguồn sát thương gây ra cho người đó, sau đó rút X lá bài (X là số sinh lực đã mất của người đó và tối đa là 5); 2. Khiến người đó mất 1 điểm sinh lực, sau đó nhận lá bài bạn đã bỏ.",
	xinjiewei_info: "Bạn có thể dùng bài trong khu vực trang bị như 【Vô Giải Khả Kích】; khi thẻ võ tướng của bạn từ mặt sau lật về mặt trước, bạn có thể bỏ một lá bài, sau đó di chuyển một lá bài trên sân.",
	xinjushou_info: "Giai đoạn kết thúc, bạn có thể lật mặt và rút bốn lá bài, sau đó bỏ một lá bài trên tay, nếu lá bài bỏ theo cách này là bài trang bị, bạn đổi thành sử dụng nó.",
	jixi_info: "Trong giai đoạn ra bài, bạn có thể dùng bất kỳ lá bài “Điền” nào như 【Thuận Thủ Khiên Dương】.",
	xinqiangxi_info: "Trong giai đoạn ra bài mỗi mục giới hạn một lần, bạn có thể chọn một mục: 1. Mất 1 điểm sinh lực và gây cho một nhân vật khác trong phạm vi tấn công của bạn 1 điểm sát thương; 2. Bỏ một lá bài trang bị và gây cho một nhân vật khác trong phạm vi tấn công của bạn 1 điểm sát thương.",
	qimou_info: "Kỹ năng hạn định, giai đoạn ra bài, bạn có thể mất bất kỳ điểm sinh lực nào, sau đó cho đến khi kết thúc lượt, bạn tính khoảng cách đến các nhân vật khác giảm X, và bạn có thể sử dụng thêm X lá 【Sát】 (X là số sinh lực bạn đã mất).",
	tiaoxin_info: "Trong giai đoạn ra bài giới hạn một lần, bạn có thể chỉ định một nhân vật có phạm vi tấn công bao gồm bạn, nhân vật đó cần sử dụng một lá 【Sát】 lên bạn, nếu không bạn bỏ một lá bài của người đó.",
	zhiji_info: `Kỹ năng thức tỉnh, giai đoạn chuẩn bị, nếu bạn không có bài trên tay, bạn phải hồi 1 điểm sinh lực hoặc rút hai lá bài, sau đó giảm 1 điểm giới hạn sinh lực, và nhận kỹ năng ${get.poptip("reguanxing")}.`,
	xiangle_info: "Kỹ năng khóa, khi bạn trở thành mục tiêu của 【Sát】 do một nhân vật sử dụng, nhân vật đó cần bỏ một lá bài Cơ bản, nếu không 【Sát】 này vô hiệu với bạn.",
	fangquan_info: "Bạn có thể bỏ qua giai đoạn ra bài của mình, nếu làm như vậy, khi kết thúc lượt, bạn có thể bỏ một lá bài trên tay và khiến một nhân vật khác thực hiện thêm một lượt.",
	ruoyu_info: `Kỹ năng chủ công, kỹ năng thức tỉnh, giai đoạn chuẩn bị, nếu sinh lực của bạn là ít nhất toàn trường (hoặc một trong số đó), bạn phải tăng 1 điểm giới hạn sinh lực và hồi 1 điểm sinh lực, sau đó nhận kỹ năng ${get.poptip("rejijiang")}.`,
	qiaobian_info: "Bạn có thể bỏ một lá bài trên tay và bỏ qua một giai đoạn của mình (ngoại trừ giai đoạn chuẩn bị và giai đoạn kết thúc). Nếu bạn bỏ qua giai đoạn rút bài theo cách này, bạn có thể nhận tối đa mỗi người một lá bài trên tay của hai nhân vật khác; nếu bạn bỏ qua giai đoạn ra bài theo cách này, bạn có thể di chuyển một lá bài trên sân.",
	tuntian_info: "① Khi bạn mất bài ngoài lượt của mình, bạn có thể phán xét. Nếu kết quả phán xét không phải là Cơ, bạn đặt lá bài này lên trên thẻ võ tướng của mình, gọi là “Điền”. ② Bạn tính khoảng cách đến các nhân vật khác giảm X (X là số lượng “Điền” trên thẻ võ tướng của bạn).",
	zaoxian_info: `Kỹ năng thức tỉnh, giai đoạn chuẩn bị, nếu trên thẻ võ tướng của bạn có ít nhất ba lá “Điền”, bạn giảm 1 điểm giới hạn sinh lực, và nhận kỹ năng ${get.poptip("jixi")}.`,
	jiang_info: "Mỗi khi bạn sử dụng (sau khi chỉ định mục tiêu) hoặc bị sử dụng (sau khi trở thành mục tiêu) một lá 【Quyết Đấu】 hoặc 【Sát】 màu đỏ, bạn có thể rút một lá bài.",
	hunzi_info: `Kỹ năng thức tỉnh, giai đoạn chuẩn bị, nếu sinh lực của bạn bằng 1, bạn giảm 1 điểm giới hạn sinh lực, và nhận kỹ năng ${get.poptip("reyingzi")} và ${get.poptip("gzyinghun")}.`,
	zhiba_info: "Kỹ năng chủ công, trong giai đoạn ra bài của nhân vật thuộc thế lực Ngô khác giới hạn một lần, người đó có thể cùng bạn tiến hành tỷ bài một lần. Nếu nhân vật đó không thắng, bạn có thể nhận các lá bài tỷ bài của cả hai bên. Nếu bạn đã phát động 〖Hồn Tư〗, bạn có thể từ chối tỷ bài này.",
	zhijian_info: "Trong giai đoạn ra bài, bạn có thể đặt một lá bài trang bị trong tay vào khu vực trang bị của một nhân vật khác (không được thay thế trang bị cũ), sau đó rút một lá bài.",
	guzheng_info: "Khi giai đoạn bỏ bài của nhân vật khác kết thúc, bạn có thể khiến người đó nhận một lá bài trong số các lá bài đã vào chồng bài bỏ trong giai đoạn này, sau đó bạn nhận các lá bài còn lại.",
	beige_info: "Khi có nhân vật chịu sát thương do 【Sát】 gây ra, bạn có thể bỏ một lá bài, và khiến người đó tiến hành phán xét một lần, nếu kết quả phán xét là: Cơ - nhân vật đó hồi 1 điểm sinh lực; Rô - nhân vật đó rút hai lá bài; Nhép - nguồn sát thương bỏ hai lá bài; Bích - nguồn sát thương lật mặt thẻ võ tướng.",
	duanchang_info: "Kỹ năng khóa, nhân vật giết chết bạn sẽ mất tất cả các kỹ năng hiện có.",
	// fushen_info:'Trước khi lượt bắt đầu, bạn có thể chọn trao đổi quyền điều khiển với bất kỳ một nhân vật nào, nhân vật đó có thể chọn đổi lại với bạn trước khi lượt tiếp theo bắt đầu.',
	huashen_info: "① Khi trò chơi bắt đầu, bạn ngẫu nhiên lấy hai lá bài từ chồng thẻ võ tướng đặt úp lên thẻ võ tướng (đều gọi là “Lá bài hóa thân”), chọn và lật ra một “Lá bài hóa thân” và tuyên bố một kỹ năng trên thẻ võ tướng đó, bạn sở hữu kỹ năng đó đồng thời giới tính và thuộc tính thế lực biến thành giống với võ tướng đó cho đến khi hóa thân đó bị thay thế (bạn không thể tuyên bố các kỹ năng đặc biệt như kỹ năng hạn định, kỹ năng thức tỉnh, kỹ năng ẩn nặc, kỹ năng sứ mệnh, kỹ năng chủ công, v.v.). ② Khi lượt bắt đầu hoặc kết thúc, bạn có thể chọn lại một “Lá bài hóa thân” và tuyên bố một kỹ năng trên thẻ võ tướng đó.",
	xinsheng_info: "Khi bạn chịu 1 điểm sát thương, bạn có thể nhận một lá “Lá bài hóa thân”.",
	jiangwei: "Khương Duy",
	liushan: "Lưu Thiện",
	zhanghe: "Trương Cáp",
	dengai: "Đặng Ngải",
	sunce: "Tôn Sách",
	zhangzhang: "Trương Chiêu Trương Hoành",
	caiwenji: "Thái Diễm",
	zuoci: "Tả Từ",

	zhurong: "Chúc Dung",
	menghuo: "Mạnh Hoạch",
	caopi: "Tào Phi",
	re_xuhuang: "Từ Hoảng",
	lusu: "Cựu Lỗ Túc",
	lusu_prefix: "Cựu",
	sunjian: "Tôn Kiên",
	dongzhuo: "Đổng Trác",
	jiaxu: "Giả Hủ",
	huoshou: "Họa Thủ",
	huoshou1: "Họa Thủ",
	huoshou2: "Họa Thủ",
	zaiqi: "Tái Khởi",
	zaiqixx: "Tái Khởi",
	juxiang: "Cự Tượng",
	juxiang1: "Cự Tượng",
	juxiang2: "Cự Tượng",
	lieren: "Liệt Nhận",
	xingshang: "Hành Sương",
	fangzhu: "Phóng Trục",
	songwei: "Tụng Uy",
	songwei2: "Tụng Uy",
	duanliang: "Đoạn Lương",
	duanliang1: "Đoạn Lương",
	haoshi: "Hảo Thí",
	dimeng: "Đế Minh",
	jiuchi: "Tửu Trì",
	roulin: "Nhục Lâm",
	benghuai: "Băng Hoại",
	baonue: "Bạo Ngược",
	baonue2: "Bạo Ngược",
	baonue_hp: "Sinh lực",
	baonue_maxHp: "Giới hạn sinh lực",
	luanwu: "Loạn Vũ",
	wansha: "Hoàn Sát",
	weimu: "Duy Mạc",
	jiezi: "Tiết Ti",
	jiezi_info: "Kỹ năng khóa, sau khi nhân vật khác bỏ qua giai đoạn rút bài, bạn rút một lá bài.",
	huoshou_info: "Kỹ năng khóa, 【Nam Man Nhập Xâm】 vô hiệu với bạn; bạn được coi là nguồn sát thương của tất cả 【Nam Man Nhập Xâm】.",
	zaiqi_info: "Giai đoạn rút bài, nếu bạn đã bị thương, bạn có thể đổi thành lật ra X lá bài trên cùng của chồng bài (X là số sinh lực bạn đã mất), và hồi X điểm sinh lực (X là số lá bài Cơ trong đó). Sau đó bạn đặt những lá bài Cơ này vào chồng bài bỏ, và nhận các lá bài còn lại.",
	zaiqixx_info: "Giai đoạn rút bài, nếu bạn đã bị thương, bạn có thể đổi thành lật ra X lá bài trên cùng của chồng bài (X là số sinh lực bạn đã mất + 1), và hồi X điểm sinh lực (X là số lá bài Cơ trong đó). Sau đó bạn đặt những lá bài Cơ này vào chồng bài bỏ, và nhận các lá bài còn lại.",
	juxiang_info: "Kỹ năng khóa. ① 【Nam Man Nhập Xâm】 vô hiệu với bạn. ② Sau khi 【Nam Man Nhập Xâm】 do nhân vật khác sử dụng kết thúc giải quyết, bạn nhận tất cả các lá bài vật thể tương ứng với lá bài này.",
	lieren_info: "Khi bạn sử dụng 【Sát】 gây sát thương, có thể cùng nhân vật chịu sát thương đó tiến hành tỷ bài; nếu bạn thắng, bạn nhận một lá bài của đối phương.",
	xingshang_info: "Khi có nhân vật tử vong, bạn có thể nhận tất cả các lá bài của nhân vật đó.",
	fangzhu_info: "Sau khi bạn chịu sát thương, bạn có thể khiến một nhân vật khác rút X lá bài (X là số sinh lực bạn đã mất), sau đó nhân vật đó lật mặt thẻ võ tướng.",
	songwei_info: "Kỹ năng chủ công, sau khi kết quả lá bài phán xét của nhân vật thuộc thế lực Ngụy khác là màu đen và có hiệu lực, người đó có thể khiến bạn rút một lá bài.",
	duanliang_info: "Bạn có thể dùng một lá bài Cơ bản hoặc bài trang bị màu đen như 【Binh Lương Thốn Đoạn】; nếu số bài trên tay của một nhân vật nhiều hơn hoặc bằng số bài trên tay của bạn, bạn sử dụng 【Binh Lương Thốn Đoạn】 lên người đó không bị giới hạn khoảng cách.",
	haoshi_info: "Giai đoạn rút bài, bạn có thể rút thêm hai lá bài. Nếu lúc này số bài trên tay của bạn nhiều hơn năm lá, bạn phải đưa một nửa (làm tròn xuống) số bài trên tay cho một nhân vật có số bài trên tay ít nhất toàn trường ngoại trừ bạn.",
	dimeng_info: "Trong giai đoạn ra bài giới hạn một lần, bạn có thể chọn hai nhân vật khác, bạn bỏ số bài tương đương với hiệu số bài trên tay của hai nhân vật này, sau đó tráo đổi bài trên tay của họ.",
	yinghun_old_info: "Giai đoạn chuẩn bị, nếu bạn đã bị thương, bạn có thể khiến một nhân vật khác thực hiện một trong hai mục sau: 1. Rút X lá bài, sau đó bỏ một lá bài. 2. Rút một lá bài, sau đó bỏ X lá bài. (X là số sinh lực bạn đã mất)",
	jiuchi_info: "Bạn có thể dùng một lá bài Bích trên tay như 【Tửu】.",
	roulin_info: "Kỹ năng khóa. Khi bạn sử dụng 【Sát】 lên nhân vật nữ, hoặc nhân vật nữ sử dụng 【Sát】 lên bạn, đều cần sử dụng liên tiếp hai lá 【Thiểm】 mới có thể triệt tiêu.",
	benghuai_info: "Kỹ năng khóa. Giai đoạn kết thúc, nếu sinh lực của bạn không phải là ít nhất toàn trường, bạn mất 1 điểm sinh lực hoặc giảm 1 điểm giới hạn sinh lực.",
	baonue_info: "Kỹ năng chủ công, sau khi nhân vật thuộc thế lực Quần hùng khác gây sát thương, có thể tiến hành phán xét một lần, nếu là Bích, bạn hồi 1 điểm sinh lực.",
	luanwu_info: "Kỹ năng hạn định, giai đoạn ra bài, bạn có thể khiến tất cả các nhân vật ngoại trừ bạn lần lượt sử dụng một lá 【Sát】 lên một nhân vật khác có khoảng cách gần nhất với họ, nếu không sẽ mất 1 điểm sinh lực.",
	wansha_info: "Kỹ năng khóa, trong lượt của bạn, ngoại trừ bạn ra, những nhân vật không ở trạng thái hấp hối không thể sử dụng 【Đào】.",
	weimu_info: "Kỹ năng khóa, bạn không thể trở thành mục tiêu của lá bài Cẩm Nang màu đen.",

	sp_zhugeliang: "Ngọa Long",
	pangtong: "Bàng Thống",
	xunyu: "Tuân Úc",
	dianwei: "Điển Vi",
	taishici: "Thái Sử Từ",
	yanwen: "Nhan Lương Văn Sửa",
	yuanshao: "Cựu Viên Thiệu",
	yuanshao_prefix: "Cựu",
	re_pangde: "Bàng Đức",
	huoji: "Hỏa Kế",
	bazhen: "Bát Trận",
	kanpo: "Khán Phá",
	niepan: "Niết Bàn",
	oldniepan: "Niết Bàn",
	quhu: "Khu Hổ",
	jieming: "Tiết Mệnh",
	qiangxix: "Cường Kích",
	qiangxi: "Cường Kích",
	tianyi: "Thiên Nghĩa",
	shuangxiong: "Song Hùng",
	shuangxiong1: "Song Hùng",
	shuangxiong2: "Song Hùng",
	luanji: "Loạn Kích",
	xueyi: "Huyết Duệ",
	mengjin: "Mãnh Tiến",
	huoji_info: "Bạn có thể dùng một lá bài màu đỏ trên tay như 【Hỏa Công】.",
	bazhen_info: "Kỹ năng khóa, nếu trong ô giáp trụ của bạn không có bài và không bị phế bỏ, bạn được coi là đang trang bị 【Bát Quái Trận】.",
	kanpo_info: "Bạn có thể dùng bất kỳ lá bài màu đen nào trên tay như 【Vô Giải Khả Kích】.",
	niepan_info: "Kỹ năng hạn định, trong giai đoạn ra bài hoặc khi bạn ở trạng thái hấp hối, bạn có thể bỏ tất cả các lá bài trong khu vực của mình và phục nguyên thẻ võ tướng, sau đó rút ba lá bài và hồi sinh lực về 3 điểm.",
	oldniepan_info: "Kỹ năng hạn định, khi bạn ở trạng thái hấp hối, bạn có thể bỏ tất cả các lá bài trong khu vực của mình và phục nguyên thẻ võ tướng, sau đó rút ba lá bài và hồi sinh lực về 3 điểm.",
	quhu_info: "Trong giai đoạn ra bài giới hạn một lần, bạn có thể tỷ bài với một nhân vật có sinh lực lớn hơn bạn, nếu bạn thắng, nhân vật đó gây 1 điểm sát thương cho một nhân vật khác do bạn chỉ định trong phạm vi tấn công của người đó. Nếu bạn không thắng, nhân vật đó gây cho bạn 1 điểm sát thương.",
	jieming_info: "Sau khi bạn chịu 1 điểm sát thương, bạn có thể khiến một nhân vật rút bài đến X lá (X là giới hạn sinh lực của người đó và tối đa là 5).",
	qiangxi_info: "Trong giai đoạn ra bài giới hạn một lần, bạn có thể mất 1 điểm sinh lực hoặc bỏ một lá bài vũ khí, sau đó gây cho một nhân vật khác trong phạm vi tấn công của bạn 1 điểm sát thương.",
	qiangxix_info: "Trong giai đoạn ra bài giới hạn hai lần, bạn có thể mất 1 điểm sinh lực hoặc bỏ một lá bài vũ khí, sau đó gây cho một nhân vật khác chưa từng là mục tiêu của 〖Cường Kích〗 trong giai đoạn này 1 điểm sát thương.",
	tianyi_info: "Trong giai đoạn ra bài giới hạn một lần, bạn có thể tỷ bài với một nhân vật khác. Nếu bạn thắng, bạn nhận được các hiệu ứng kỹ năng sau cho đến khi kết thúc lượt: bạn sử dụng 【Sát】 không giới hạn khoảng cách; có thể sử dụng thêm một lá 【Sát】; khi sử dụng 【Sát】 có thể chỉ định thêm một mục tiêu. Nếu bạn không thắng, bạn không thể sử dụng 【Sát】 cho đến khi kết thúc lượt.",
	shuangxiong_info: "Giai đoạn rút bài, bạn có thể đổi thành tiến hành phán xét một lần: bạn nhận lá bài phán xét này, và bạn có thể trong lượt này dùng bất kỳ lá bài trên tay nào có màu sắc khác với lá bài phán xét này như 【Quyết Đấu】.",
	luanji_info: "Trong giai đoạn ra bài, bạn có thể dùng bất kỳ hai lá bài trên tay có cùng hoa sắc như 【Vạn Tiễn Tề Phát】.",
	xueyi_info: "Kỹ năng chủ công, kỹ năng khóa, mỗi khi có một nhân vật thuộc thế lực Quần hùng khác còn sống trên sân, giới hạn bài trên tay của bạn sẽ +2.",
	mengjin_info: "Khi 【Sát】 bạn sử dụng bị 【Thiểm】 triệt tiêu, bạn có thể bỏ một lá bài của nhân vật mục tiêu.",

	re_xiahouyuan: "Hạ Hầu Uyên",
	re_huangzhong: "Hoàng Trung",
	re_weiyan: "Ngụy Diên",

	old_zhoutai: "Chu Thái",
	old_caoren: "Tào Nhân",
	xuhuang: "Cựu Từ Hoảng",
	xuhuang_prefix: "Cựu",
	pangde: "Cựu Bàng Đức",
	pangde_prefix: "Cựu",
	xiahouyuan: "Cựu Hạ Hầu Uyên",
	xiahouyuan_prefix: "Cựu",
	huangzhong: "Cựu Hoàng Trung",
	huangzhong_prefix: "Cựu",
	sp_zhangjiao: "Trương Giác",
	weiyan: "Cựu Ngụy Diên",
	weiyan_prefix: "Cựu",
	xiaoqiao: "Tiểu Kiều",
	zhangjiao: "Cựu Trương Giác",
	zhangjiao_prefix: "Cựu",
	//yuji:'Vu Cát',
	shensu: "Thần Tốc",
	shensu1: "Thần Tốc",
	shensu2: "Thần Tốc",
	shensu4: "Thần Tốc",
	jushou: "Cứ Thủ",
	moon_jushou: "Cứ Thủ",
	liegong: "Liệt Cung",
	kuanggu: "Cuồng Cốt",
	tianxiang: "Thiên Hương",
	hongyan: "Hồng Nhan",
	buqu: "Bất Khuất",
	buqu_bg: "Sáng",
	leiji: "Lôi Kích",
	guidao: "Quỷ Đạo",
	huangtian: "Hoàng Thiên",
	huangtian2: "Hoàng Thiên",
	guhuo: "Cổ Hoặc",
	fenji: "Phấn Kích",
	releiji: "Lôi Kích",
	jiewei: "Giải Vây",
	tiangong: "Thiên Công",
	tiangong2: "Thiên Công",
	xinliegong: "Liệt Cung",
	xinkuanggu: "Cuồng Cốt",
	gzbuqu: "Bất Khuất",
	gzbuqu_info: "① Khi bạn bị trừ 1 điểm sinh lực, nếu sinh lực của bạn ít hơn 1, bạn có thể đặt một lá bài trên cùng của chồng bài lên trên thẻ võ tướng của bạn, gọi là “Sáng”. ② Khi bạn hồi 1 điểm sinh lực, bạn xóa đi một lá “Sáng”. ③ Nếu bạn có “Sáng” và các điểm số đều không giống nhau, bạn sẽ không giải quyết quy trình hấp hối.",
	xinkuanggu_info: "Sau khi bạn gây 1 điểm sát thương, nếu nhân vật bị thương khi chịu sát thương này có khoảng cách đến bạn không lớn hơn 1, bạn có thể hồi 1 điểm sinh lực hoặc rút một lá bài.",
	xinliegong_info: "① Bạn sử dụng 【Sát】 có thể chọn nhân vật có khoảng cách đến bạn không lớn hơn điểm số của 【Sát】 này làm mục tiêu. ② Sau khi bạn sử dụng 【Sát】 chỉ định một mục tiêu, bạn có thể căn cứ theo các điều kiện sau để thực hiện hiệu ứng tương ứng: 1. Số bài trên tay của người đó ít hơn hoặc bằng số bài trên tay của bạn, 【Sát】 này không thể bị hưởng ứng, 2. Sinh lực của người đó lớn hơn hoặc bằng sinh lực của bạn, sát thương của 【Sát】 này +1.",
	jiewei_info: "Sau khi thẻ võ tướng của bạn lật mặt, bạn có thể rút một lá bài. Sau đó bạn có thể sử dụng một lá bài Cẩm Nang hoặc bài trang bị, và có thể sau khi lá bài này kết thúc giải quyết bỏ một lá bài cùng loại trên sân.",
	releiji_info: "Khi bạn sử dụng hoặc đánh ra một lá 【Thiểm】, bạn có thể khiến một nhân vật khác tiến hành phán xét một lần: nếu kết quả là Nhép, bạn hồi 1 điểm sinh lực, và gây cho người đó 1 điểm sát thương hệ lôi; nếu kết quả là Bích, bạn gây cho người đó 2 điểm sát thương hệ lôi.",
	tiangong_info: "Kỹ năng khóa, bạn ngăn chặn sát thương hệ lôi sắp phải chịu. Mỗi khi bạn gây sát thương hệ lôi, bạn rút một lá bài.",
	shensu_info: "Bạn có thể bỏ qua giai đoạn phán xét và giai đoạn rút bài, hoặc bỏ qua giai đoạn ra bài và bỏ một lá bài trang bị. Nếu làm như vậy, bạn có thể coi như sử dụng một lá 【Sát】 không giới hạn khoảng cách lên bất kỳ một nhân vật nào.",
	jushou_info: "Giai đoạn kết thúc, bạn có thể rút ba lá bài và lật mặt.",
	moon_jushou_info: "Giai đoạn kết thúc, bạn có thể rút một lá bài và lật mặt.",
	liegong_info: "Khi bạn sử dụng 【Sát】, nếu số bài trên tay của mục tiêu lớn hơn hoặc bằng sinh lực của bạn, hoặc nhỏ hơn hoặc bằng phạm vi tấn công của bạn, bạn có thể khiến 【Sát】 này không thể bị hưởng ứng.",
	kuanggu_info: "Kỹ năng khóa, sau khi bạn gây sát thương, nếu nhân vật bị thương khi chịu sát thương này có khoảng cách đến bạn không lớn hơn 1, bạn hồi X điểm sinh lực (X là trị số sát thương).",
	tianxiang_info: "Khi bạn sắp chịu sát thương, bạn có thể bỏ một lá bài Cơ trên tay, chuyển sát thương cho một nhân vật khác, sau đó nhân vật đó rút X lá bài (X là số sinh lực đã mất của người đó).",
	hongyan_info: "Kỹ năng khóa, các lá bài Bích và lá bài phán xét Bích trong khu vực của bạn đều được coi là Cơ.",
	buqu_info: "Kỹ năng khóa, khi bạn ở trạng thái hấp hối, bạn lật ra một lá bài trên cùng của chồng bài và đặt lên trên thẻ võ tướng của mình, gọi là “Sáng”. Nếu điểm số của lá bài này khác với tất cả các điểm số của “Sáng” đã có trên thẻ võ tướng, bạn hồi về 1 sinh lực. Nếu điểm số giống nhau, đặt lá bài này vào chồng bài bỏ. Chỉ cần trên thẻ võ tướng của bạn có “Sáng”, giới hạn bài trên tay của bạn sẽ bằng với số lượng “Sáng”.",
	buqu_info_guozhan: "Kỹ năng khóa, khi bạn ở trạng thái hấp hối, bạn lật ra một lá bài trên cùng của chồng bài và đặt lên trên thẻ võ tướng của mình, gọi là “Sáng”. Nếu điểm số của lá bài này khác với tất cả các điểm số của “Sáng” đã có trên thẻ võ tướng, bạn hồi về 1 sinh lực. Nếu điểm số giống nhau, đặt lá bài này vào chồng bài bỏ.",
	leiji_info: "Khi bạn sử dụng hoặc đánh ra một lá 【Thiểm】, bạn có thể khiến bất kỳ một nhân vật nào tiến hành phán xét một lần. Nếu kết quả là Bích, người đó chịu 2 điểm sát thương hệ lôi.",
	guidao_info: "Trước khi lá bài phán xét của một nhân vật có hiệu lực, bạn có thể đánh ra một lá bài màu đen để thay thế nó.",
	huangtian_info: "Kỹ năng chủ công, trong giai đoạn ra bài của nhân vật thuộc thế lực Quần khác giới hạn một lần, người đó có thể đưa cho bạn một lá 【Thiểm】 hoặc 【Thiểm Điện】.",
	guhuo_info: "Mỗi lượt của mỗi nhân vật giới hạn một lần, bạn có thể đặt úp một lá bài trên tay để sử dụng hoặc đánh ra như một lá bài Cơ bản hoặc lá Cẩm Nang thông thường. Các nhân vật khác lần lượt chọn có nghi ngờ hay không. Một khi có nhân vật khác nghi ngờ thì lật lá bài này lên: nếu là giả thì lá bài này bị hủy bỏ, nếu là thật, nhân vật nghi ngờ nhận được kỹ năng “Triền Oán” (Kỹ năng khóa, bạn không thể nghi ngờ Vu Cát, chỉ cần sinh lực của bạn bằng 1, bạn mất các kỹ năng võ tướng của mình).",
	fenji_info: "Khi lá bài trên tay của một nhân vật không phải do được tặng hoặc đưa mà bị một nhân vật khác lấy được, hoặc lá bài trên tay của một nhân vật bị nhân vật khác bỏ đi, bạn có thể mất 1 điểm sinh lực, khiến người đó rút hai lá bài.",

	new_fenji: "Phấn Kích",
	new_fenji_info: "Khi giai đoạn kết thúc của một nhân vật bắt đầu, nếu người đó không có bài trên tay, bạn có thể khiến người đó rút hai lá bài, sau đó bạn mất 1 điểm sinh lực.",
	gzduanliang: "Đoạn Lương",
	gzduanliang_info: "Bạn có thể dùng một lá bài Cơ bản màu đen hoặc bài trang bị màu đen như 【Binh Lương Thốn Đoạn】; bạn có thể sử dụng 【Binh Lương Thốn Đoạn】 lên nhân vật có khoảng cách là 2.",
	xinfu_guhuo: "Cổ Hoặc",
	xinfu_guhuo_info: `Mỗi lượt giới hạn một lần. Bạn có thể đặt úp một lá bài trên tay để sử dụng hoặc đánh ra như một lá bài Cơ bản hoặc lá Cẩm Nang thông thường, các nhân vật khác lần lượt chọn có nghi ngờ hay không. Khi có nhân vật nghi ngờ, bạn chấm dứt quy trình nghi ngờ và trưng ra lá bài này: nếu là giả, lá bài này bị hủy bỏ; nếu là thật, nhân vật đó nhận được ${get.poptip("chanyuan")}.`,
	guhuo_guess: "Cổ Hoặc",
	guhuo_guess_info: "",
	chanyuan: "Triền Oán",
	chanyuan_info: "Kỹ năng khóa. Bạn không thể tiến hành nghi ngờ trong quy trình giải quyết của 〖Cổ Hoặc〗. Khi sinh lực của bạn bằng 1, các kỹ năng khác của bạn vô hiệu.",
	guhuo_respond: "Cổ Hoặc",
	guhuo_respond_info: "",
	guhuo_wuxie: "Cổ Hoặc",
	guhuo_wuxie_info: "",
	guhuo_phase: "Cổ Hoặc",
	guhuo_phase_info: "",
	xinhongyan: "Hồng Nhan",
	xinhongyan_info: "Kỹ năng khóa, hoa sắc của các lá bài Bích và lá bài phán xét Bích của bạn được coi là Cơ. Trước khi kết quả phán xét của một nhân vật có hiệu lực, nếu kết quả phán xét là Cơ, bạn đổi nó thành một loại hoa sắc.",
	olliangyin: "Lương Nhân",
	olliangyin_info: "Khi có lá bài di chuyển, nếu sự kiện di chuyển này là sự kiện di chuyển bài ra khỏi trò chơi/vào trong trò chơi đầu tiên trong giai đoạn bạn sở hữu 〖Lương Nhân〗 của lượt này, bạn có thể chọn một nhân vật khác. Bạn và người đó mỗi người rút một lá bài/bỏ một lá bài, sau đó bạn có thể chọn bạn hoặc một trong số các nhân vật có số bài trên tay là X, nhân vật đó hồi 1 điểm sinh lực (X là số lượng “Không” của bạn).",
	olkongsheng: "Không Thanh",
	olkongsheng_info: "① Khi giai đoạn chuẩn bị bắt đầu, bạn có thể đặt bất kỳ số lượng lá bài nào lên trên thẻ võ tướng của bạn, gọi là “Không”. ② Khi giai đoạn kết thúc bắt đầu, nếu bạn có “Không” không phải là bài trang bị, bạn nhận các lá bài không phải trang bị trong “Không”, sau đó khiến một nhân vật lần lượt sử dụng các lá bài trang bị trong “Không” và mất 1 điểm sinh lực.",
	dcwanglie: "Vãng Liệt",
	dcwanglie_info: "① Giai đoạn ra bài, hai lá bài đầu tiên bạn sử dụng lên nhân vật khác không bị giới hạn khoảng cách. ② Khi bạn sử dụng bài trong giai đoạn ra bài, bạn có thể khiến lá bài này không thể bị hưởng ứng, sau đó bạn trong giai đoạn này không thể sử dụng bài chỉ định nhân vật khác làm mục tiêu.",
	nzry_shicai: "Thị Tài",
	nzry_shicai_info: "Sau khi bạn sử dụng lá bài không phải trang bị kết thúc giải quyết, hoặc sau khi trở thành mục tiêu của lá bài trang bị do chính mình sử dụng, nếu lá bài này là lá bài đầu tiên thuộc loại đó bạn sử dụng trong lượt này, bạn có thể đặt lá bài này lên trên cùng của chồng bài, sau đó rút một lá bài.",
	lianhuan: "Liên Hoàn",
	lianhuan_info: "Bạn có thể dùng lá bài Nhép trên tay như 【Thiết Tỏa Liên Hoàn】 để sử dụng hoặc đúc lại.",
};

export default translates;
