import { lib, game, ui, get, ai, _status } from "noname";

const translates = {
	yj_zhanghe: "☆ Trương Hợp",
	yj_zhanghe_prefix: "☆",
	yj_zhangliao: "☆ Trương Liêu",
	yj_zhangliao_prefix: "☆",
	yj_xuhuang: "☆ Từ Hoảng",
	yj_xuhuang_prefix: "☆",
	yj_ganning: "☆ Cam Ninh",
	yj_ganning_prefix: "☆",
	xhzhiyan: "Trị Nghiêm",
	xhzhiyan_info: "Giai đoạn Xuất Bài, nếu số bài trên tay bạn không bằng giới hạn thể lực, thì bạn có thể bốc/bỏ bài trên tay lên/xuống giới hạn bài trên tay, sau đó trong lượt này không thể dùng bài nhắn vào nhân vật khác / có thể đưa một lá bài đã bỏ cho một nhân vật khác.",
	zhilve: "Trí Lược",
	zhilve_info: "Kỹ năng khóa, giai đoạn Chuẩn Bị, bạn chọn một: 1. Di chuyển một lá bài trong khu vực Trang Bị trên bàn và mất 1 điểm thể lực. 2. Di chuyển một lá bài trong khu vực Phán Định trên bàn và khiến giới hạn bài trên tay trong lượt này -1. 3. Trong lượt này, giai đoạn Bốc Bài bốc thêm một lá bài và 【Giết】 đầu tiên sử dụng không giới hạn khoảng cách và không tính vào giới hạn số lần.",
	xinzhilve: "Trí Lược",
	xinzhilve_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể mất 1 điểm thể lực và chọn một: 1. Di chuyển một lá bài trên bàn; 2. Xem như sử dụng một 【Giết】 không giới hạn khoảng cách và không tính vào giới hạn số lần, và bốc một lá bài. Sau đó giới hạn bài trên tay của bạn trong lượt này +1.",
	xinxhzhiyan: "Trị Nghiêm",
	xinxhzhiyan_false: "Trị Nghiêm",
	xinxhzhiyan_info: "Giai đoạn Xuất Bài mỗi hạng mục giới hạn một lần, nếu số bài trên tay bạn: lớn hơn thể lực, thì bạn có thể đưa X lá bài trên tay cho một nhân vật khác (X là chênh lệch giữa số bài trên tay bạn và thể lực); nhỏ hơn giới hạn thể lực, thì bạn có thể bốc X lá bài và trong giai đoạn này không thể dùng bài nhắn vào nhân vật khác nữa (X là chênh lệch giữa số bài trên tay bạn và giới hạn thể lực).",
	weifeng: "Oai Phong",
	weifeng2: "Oai Phong",
	weifeng3: "Oai Phong",
	weifeng_info: "Kỹ năng khóa, sau khi bạn sử dụng bài cơ bản sát thương hoặc bài chú thông thường đầu tiên trong giai đoạn Xuất Bài, bạn khiến một nhân vật mục tiêu khác không có “Cụ” nhận được một dấu hiệu có tên là tên bài này, gọi là “Cụ”. Khi nhân vật có “Cụ” chịu sát thương, người đó bỏ “Cụ”, sau đó nếu tên bài gây sát thương và “Cụ”: giống nhau, sát thương này +1; khác nhau, bạn nhận được một lá bài của nhân vật đó. Khi bắt đầu giai đoạn Chuẩn Bị hoặc khi bạn chết, bạn bỏ tất cả “Cụ” trên bàn.",
	gnjinfan: "Cẩm Phàm",
	gnjinfan_gain: "Cẩm Phàm",
	gnjinfan_info: "Khi bắt đầu giai đoạn Bỏ Bài, bạn có thể đặt một số lá bài trên tay bất kỳ lên bài tướng, gọi là “Linh” (mỗi hoa giới hạn một “Linh”). Bạn có thể dùng hoặc đánh ra “Linh” như bài trên tay. Khi có “Linh” di chuyển đến khu vực Xử Lý, bạn nhận từ bộ bài một lá bài cùng hoa với “Linh”.",
	gnsheque: "Xạ Khước",
	gnsheque_info: "Khi bắt đầu giai đoạn Chuẩn Bị của một nhân vật khác, nếu trong khu vực Trang Bị của người đó có bài, thì bạn có thể dùng một 【Giết】 nhắn vào người đó (không giới hạn khoảng cách và không nhìn Giáp).",
	yj_huangzhong: "☆ Hoàng Trung",
	yj_huangzhong_prefix: "☆",
	spshidi: "Thế Địch",
	spshidi_info: "Kỹ năng chuyển hóa, kỹ năng khóa. ① Khi bắt đầu giai đoạn Chuẩn Bị / Kết Thúc, nếu tổng số lần bạn phát động nhánh này là lẻ / chẵn, thì bạn nhận được một “☯”. ② Nếu số “☯” của bạn là chẵn, thì khoảng cách từ bạn đến nhân vật khác -1, và 【Giết】 đen bạn dùng không thể bị đáp trả. ③ Nếu số “☯” của bạn là lẻ, thì khoảng cách từ nhân vật khác đến bạn +1, và bạn không thể đáp trả 【Giết】 đỏ.",
	spyishi: "Nghĩa Thích",
	spyishi_info: "Khi bạn gây sát thương cho nhân vật khác có bài trong khu vực Trang Bị, bạn có thể khiến sát thương này -1, sau đó nhận một lá bài trong khu vực Trang Bị của người đó.",
	spqishe: "Kỵ Xạ",
	spqishe_info: "Bạn có thể dùng một lá bài Trang Bị xem như 【Rượu】. Giới hạn bài trên tay của bạn +X (X là số bài trong khu vực Trang Bị của bạn).",
	yj_weiyan: "☆ Ngụy Diên",
	yj_weiyan_prefix: "☆",
	mbguli: "Cô Lệ",
	mbguli_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể dùng tất cả bài trên tay xem như một 【Giết】 không nhìn Giáp và không giới hạn số lần. Sau khi 【Giết】 này kết toán xong, bạn có thể bốc bài trên tay lên X lá (X là giới hạn thể lực của bạn), sau đó nếu 【Giết】 này chưa gây sát thương, bạn mất 1 điểm thể lực.",
	mbaosi: "Ngạo Tứ",
	mbaosi_info: "Kỹ năng khóa. Khi bạn gây sát thương cho một nhân vật trong phạm vi tấn công trong giai đoạn Xuất Bài, bạn dùng bài nhắn vào người đó trong giai đoạn này không giới hạn số lần. Lá bài thứ X bạn dùng trong giai đoạn Xuất Bài không thể bị đáp trả (X là số vòng chơi).",
	yj_zhoubuyi: "☆ Chu Bất Nghi",
	yj_zhoubuyi_prefix: "☆",
	mbhuiyao: "Huệ Yểu",
	mbhuiyao_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể chịu 1 điểm sát thương không rõ nguồn gốc, sau đó bạn chọn một nhân vật khác, khiến người đó xem như đã gây 1 điểm sát thương cho một nhân vật khác.",
	mbquesong: "Tước Tụng",
	mbquesong_info: "Giai đoạn Kết Thúc của một nhân vật, nếu bạn đã chịu sát thương trong lượt này, bạn có thể khiến tối đa ba nhân vật chọn một: 1. Bốc 4-X lá bài và khôi phục bài tướng; 2. Bỏ X-1 lá bài sau đó hồi phục 1 điểm thể lực (X là số nhân vật được chọn lần này). Nếu số lần bạn chịu sát thương trong lượt này lớn hơn X, các nhân vật được chọn có thể lần lượt thực hiện cả hai hạng mục, sau đó các kỹ năng không khóa của họ mất hiệu lực cho đến khi bắt đầu lượt tiếp theo của họ.",
	old_mbquesong: "Tước Tụng",
	old_mbquesong_info: "Giai đoạn Kết Thúc của một nhân vật, nếu bạn đã chịu sát thương trong lượt này, bạn có thể khiến một nhân vật chọn một: 1. Bốc X lá bài và khôi phục bài tướng (X là 3, nếu số bài không phải Bảo Vật trong khu vực Trang Bị của người đó không nhỏ hơn ba thì X là 2); 2. Hồi phục 1 điểm thể lực.",
	lukai: "Lục Khải",
	lukai_spade: "♠",
	lukai_spade_bg: "♠️",
	lukai_heart: "♥",
	lukai_heart_bg: "♥️",
	lukai_club: "♣",
	lukai_club_bg: "♣",
	lukai_diamond: "♦",
	lukai_diamond_bg: "♦️️",
	lkbushi: "Bốc Thệ",
	lkbushi_info: "① Bạn dùng bài ♠ không giới hạn số lần. ② Khi bạn dùng hoặc đánh ra bài ♥, bạn bốc một lá bài. ③ Khi bạn trở thành mục tiêu của bài ♣, bạn có thể bỏ một lá bài, khiến bài này vô hiệu với bạn. ④ Khi bắt đầu giai đoạn Kết Thúc, bạn nhận một lá bài ♦ từ bộ bài hoặc bộ bài bỏ. ⑤ Khi bắt đầu giai đoạn Chuẩn Bị, bạn có thể điều chỉnh thứ tự tương ứng của bốn loại hoa trong kỹ năng này.",
	lkzhongzhuang: "Trung Tráng",
	lkzhongzhuang_info: "Kỹ năng khóa. ① Khi bạn gây sát thương do thực hiện hiệu ứng của 【Giết】, nếu phạm vi tấn công của bạn lớn hơn 3, thì sát thương này +1. ② Khi một nhân vật chịu sát thương do bạn gây ra do thực hiện hiệu ứng của 【Giết】, nếu phạm vi tấn công của bạn nhỏ hơn 3, thì sát thương này đổi thành 1.",
	kebineng: "Kha Tỷ Năng",
	kousheng: "Khấu Tinh",
	kousheng_info: "① Khi bắt đầu giai đoạn Xuất Bài, bạn có thể chọn một số lá bài trên tay bất kỳ, những lá bài này gọi là “Khấu Tinh” cho đến khi kết thúc lượt. ② “Khấu Tinh” của bạn đều được xem là 【Giết】 và không giới hạn số lần. ③ Khi bạn gây sát thương do thực hiện hiệu ứng của 【Giết】 có bài thực thể tương ứng chứa “Khấu Tinh”, bạn tiết lộ tất cả bài “Khấu Tinh”, sau đó nhân vật mục tiêu có thể đổi tất cả bài trên tay lấy những bài này.",
	zhugeshang: "Gia Cát Thượng",
	sangu: "Tam Cố",
	sangu_info: "Giai đoạn Kết Thúc, bạn có thể chọn tối đa ba tên bài trong {【Giết】 hoặc bài chú thông thường không phải notarget hoặc singleCard}, sau đó khiến một nhân vật khác ghi nhớ những tên bài này. Khi bắt đầu giai đoạn Xuất Bài tiếp theo của nhân vật đó, bài trên tay của người đó khi cần dùng bài đều được xem là lá bài đầu tiên trong ghi nhớ của họ cho đến khi kết thúc giai đoạn này, và khi người đó dùng hoặc đánh ra bài có bài thực thể tương ứng, sẽ loại bỏ lá bài đầu tiên trong những bài này. Nếu tất cả tên bài bạn chọn bằng cách này đều là tên bài bạn đã dùng trong lượt này, thì bạn ngăn ngừa sát thương do người đó dùng bài bằng cách này gây ra.",
	yizu: "Dật Tổ",
	yizu_info: "Kỹ năng khóa. Mỗi lượt giới hạn một lần, khi bạn trở thành mục tiêu của 【Giết】 hoặc 【Quyết Đấu】, nếu thể lực của bạn không lớn hơn thể lực của người sử dụng, thì bạn hồi phục 1 điểm thể lực.",
	liwan: "Lý Uyển",
	liandui: "Liên Đối",
	liandui_info: "① Khi bạn dùng bài, nếu người sử dụng của lá bài trước đó được sử dụng trong ván chơi này không phải là bạn, bạn có thể khiến người đó bốc hai lá bài. ② Khi nhân vật khác dùng bài, nếu người sử dụng của lá bài trước đó được sử dụng trong ván chơi này là bạn, người đó có thể khiến bạn bốc hai lá bài.",
	biejun: "Biệt Quân",
	biejun_info: "① Giai đoạn Xuất Bài của nhân vật khác giới hạn một lần. Người đó có thể đưa một lá bài trên tay cho bạn. ② Mỗi lượt giới hạn một lần. Khi bạn chịu sát thương, nếu trong tay bạn không có bài nhận được trong lượt này do 【Biệt Quân①】, bạn có thể lật úp và ngăn ngừa sát thương này.",
	yj_sufei: "Tô Phi",
	shuojian: "Số Gián",
	shuojian_info: "Giai đoạn Xuất Bài giới hạn ba lần. Bạn có thể đưa cho một nhân vật khác một lá bài, người đó chọn một: 1. Khiến bạn bốc X lá bài và bỏ X-1 lá bài; 2. Xem như sử dụng X 【Quá Hà Sách Kiều】, sau đó kỹ năng này mất hiệu lực trong lượt này (X là số lần kỹ năng này còn có thể phát động trong giai đoạn này +1).",
	yj_qiaozhou: "Tiếu Chu",
	shiming: "Thức Mệnh",
	shiming_info: "Mỗi vòng giới hạn một lần. Giai đoạn Bốc Bài của một nhân vật, bạn có thể xem ba lá bài trên cùng bộ bài, và có thể đặt một trong số đó xuống đáy bộ bài. Sau đó nhân vật đó có thể đổi thành gây cho chính mình 1 điểm sát thương, sau đó bốc ba lá bài từ đáy bộ bài.",
	jiangxi: "Tương Tức",
	jiangxi_info: "Khi kết thúc lượt của một nhân vật, nếu vị trí số một trong lượt này đã vào trạng thái hấp hối hoặc chưa chịu sát thương, bạn có thể thiết lập lại 【Thức Mệnh】 và bốc một lá bài; nếu tất cả nhân vật đều chưa chịu sát thương, bạn có thể cùng với nhân vật trong lượt hiện tại mỗi người bốc một lá bài.",
	hanlong: "Hàn Long",
	duwang: "Độc Vãng",
	duwang_info: "Kỹ năng khóa. ① Khi bắt đầu ván chơi, bạn đặt năm lá bài không phải 【Giết】 từ đỉnh bộ bài lên bài tướng, gọi là “Thích”. ② Nếu bạn có “Thích” có tên bài không phải 【Giết】, khoảng cách từ bạn đến nhân vật khác hoặc từ nhân vật khác đến bạn +1.",
	cibei: "Thích Bắc",
	cibei_info: "① Khi một nhân vật dùng 【Giết】 không chuyển hóa gây sát thương và bài thực thể tương ứng của 【Giết】 này vào bộ bài bỏ, bạn có thể đặt một “Thích” không phải 【Giết】 vào bộ bài bỏ, và đặt những bài này vào “Thích”, sau đó bỏ một lá bài trong khu vực của một nhân vật. ② Khi kết thúc lượt của một nhân vật, nếu “Thích” của bạn đều là 【Giết】, bạn nhận được tất cả “Thích”, và những bài này không thể bị bỏ, không tính vào giới hạn bài trên tay, và khi bạn dùng bài có bài thực thể tương ứng chứa những bài này thì không giới hạn số lần và khoảng cách.",
	wuanguo: "Vũ An Quốc",
	diezhang: "Điệp Chướng",
	diezhang_info: "Kỹ năng chuyển hóa. ① Giai đoạn Xuất Bài, giới hạn số lần bạn dùng 【Giết】 +1. ② Dương: Khi bài bạn dùng bị nhân vật khác đáp trả, bạn có thể bỏ một lá bài, xem như sử dụng X 【Giết】 nhắn vào người đó; Âm: Khi bài do nhân vật khác dùng bị bạn đáp trả, bạn có thể bốc X lá bài, xem như sử dụng một 【Giết】 nhắn vào người đó (X là 1).",
	duanwan: "Đoạn Uyển",
	duanwan_info: "Kỹ năng giới hạn. Khi bạn đang trong trạng thái hấp hối, bạn có thể hồi phục thể lực về 2 điểm, sau đó xóa bỏ 【Điệp Chướng①】 và nhánh 【Điệp Chướng②】 của trạng thái chuyển hóa hiện tại, và sửa đổi 【Điệp Chướng】 thành “mỗi lượt giới hạn một lần” và sửa đổi X thành 2.",
	dcduliang: "Đốc Lương",
	dcduliang2: "Đốc Lương",
	dcduliang_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể nhận một lá bài của một nhân vật khác, sau đó chọn một: 1. Bạn xem hai lá bài trên cùng bộ bài, sau đó khiến người đó nhận một hoặc hai lá bài cơ bản trong số đó; 2. Khiến người đó ở giai đoạn Bốc Bài của lượt tiếp theo bốc thêm một lá bài.",
	sunli: "Tôn Lễ",
	kangli: "Kháng Lệ",
	kangli_info: "Khi bạn gây ra hoặc chịu sát thương, bạn bốc hai lá bài. Sau đó lần tiếp theo bạn gây sát thương sẽ bỏ những lá bài này.",
	xiahoumao: "Hạ Hầu Mậu",
	tongwei: "Thống Vi",
	tongwei_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể tái luyện hai lá bài và chỉ định một nhân vật khác, sau khi lá bài tiếp theo người đó dùng kết toán xong, nếu điểm số của lá bài này nằm giữa điểm số của hai lá bài bạn tái luyện lần trước, bạn xem như sử dụng một 【Giết】 hoặc 【Quá Hà Sách Kiều】 nhắn vào người đó.",
	cuguo: "Xúc Quốc",
	cuguo_info: "Kỹ năng khóa. Khi bài bạn dùng bị đáp trả lần đầu tiên trong một lượt, bạn bỏ một lá bài, xem như sử dụng lại lá bài đã bị đáp trả đó nhắn vào nhân vật mục tiêu của bài này. Sau khi bài này kết toán xong, nếu bài này bị đáp trả, bạn mất 1 điểm thể lực.",
	chenshi: "Trần Thức",
	qingbei: "Kình Bắc",
	qingbei_info: "① Khi bắt đầu mỗi vòng, bạn có thể chọn một số loại hoa bất kỳ, bạn không thể dùng các loại hoa này trong vòng này. ② Sau khi bạn dùng bài kết toán xong, bạn bốc X lá bài (X là số loại hoa bạn đã chọn trong 【Kình Bắc①】 của vòng này).",
	feiyao: "Phí Diệu",
	zhenfeng: "Trấn Phong",
	zhenfeng_info: "Mỗi lượt giới hạn một lần. Khi nhân vật khác dùng bài trong lượt của họ, nếu số bài trên tay người đó không lớn hơn thể lực của người đó, bạn có thể đoán số lượng bài trên tay người đó cùng loại với bài này. Nếu bạn đoán đúng, bạn bốc X lá bài và xem như sử dụng một 【Giết】 nhắn vào người đó (X là số lần bạn đoán đúng liên tiếp và tối đa là 5); nếu bạn đoán sai và chênh lệch lớn hơn 1, người đó xem như sử dụng một 【Giết】 nhắn vào bạn.",
	linghuyu: "Lệnh Hồ Ngu",
	yj_simafu: "Tư Mã Phu",
	yj_xuangongzhu: "Tuyên Công Chúa",
	xukun: "Từ Khôn",
	xvzhi: "Súc Chí",
	xvzhi_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể khiến hai nhân vật mỗi người chọn một số lá bài trên tay bất kỳ và đổi những lá bài này cho nhau, sau đó nhân vật có số bài nhận được ít hơn được xem như sử dụng 【Giết】 không nhìn khoảng cách; nếu số bài nhận được bằng nhau, bạn bốc hai lá bài và có thể phát động lại một lần 【Súc Chí】 nhắn vào nhân vật chưa được chọn bằng cách này trong giai đoạn này.",
	beiyu: "Bị Dự",
	beiyu_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể bốc bài trên tay lên giới hạn thể lực, sau đó bạn đặt tất cả bài có một hoa xuống đáy bộ bài.",
	duchi: "Đốc Trì",
	duchi_info: "Mỗi lượt giới hạn một lần, khi bạn trở thành mục tiêu sử dụng bài của nhân vật khác, bạn có thể bốc một lá bài từ đáy bộ bài và tiết lộ tất cả bài trên tay, nếu màu sắc đều giống nhau, thì bài này vô hiệu với bạn.",
	yjqimei: "Tề Mi",
	yjqimei_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể chọn một nhân vật khác, bạn và người đó mỗi người bốc hai lá bài và tiết lộ hai lá bài trên tay, sau đó bạn dựa vào tổng số hoa của bài đã tiết lộ của bạn và người đó để thực hiện hiệu ứng sau: 1. Bạn lần lượt sử dụng những bài có thể sử dụng trong số các bài đã tiết lộ này; 2. Bạn và người đó khôi phục bài tướng; 3. Bạn và người đó tái luyện bài đã tiết lộ; 4. Bạn và người đó mỗi người bốc một lá bài.",
	yjzhuiji: "Truy Cơ",
	yjzhuiji_info: "Khi bạn chết, bạn có thể khiến một nhân vật ngẫu nhiên sử dụng một số lượng bài Trang Bị bất kỳ từ bộ bài và bộ bài bỏ cho đến khi người đó không còn ô Trang Bị trống. Nếu làm vậy, khi người đó mất bài Trang Bị đã sử dụng bằng cách này, người đó phế bỏ ô Trang Bị tương ứng.",
	fazhu: "Phiệt Trúc",
	fazhu_info: "Giai đoạn Chuẩn Bị, bạn có thể tái luyện một số lá bài không phải sát thương bất kỳ trong khu vực của bạn, sau đó đưa cho tối đa số lượng nhân vật tương ứng mỗi người một lá bài trong số bài nhận được bằng cách này, những nhân vật này có thể lần lượt sử dụng một 【Giết】 không giới hạn khoảng cách.",
	xunyuxunyou: "Tuân Úc Tuân Du",
	zhinang: "Trí Nang",
	zhinang_info: "① Khi bạn dùng bài chú, bạn có thể nhận được một kỹ năng có câu thoại kỹ năng chứa “mưu” cho đến khi phát động lại hạng mục này; ② Khi bạn dùng bài Trang Bị, bạn có thể nhận được một kỹ năng có tên kỹ năng chứa “mưu” cho đến khi phát động lại hạng mục này.",
	gouzhu: "Câu Chử",
	gouzhu_info: "Sau khi bạn mất kỹ năng, nếu kỹ năng này là: kỹ năng khóa, hồi phục 1 điểm thể lực; kỹ năng giác tỉnh, nhận một bài cơ bản; kỹ năng giới hạn, gây 1 điểm sát thương cho một nhân vật khác ngẫu nhiên; kỹ năng chuyển hóa, giới hạn bài trên tay +1; kỹ năng Chủ Công, tăng 1 điểm giới hạn thể lực.",
	yj_sb_guojia: "Tân Sát Mưu Quách Gia",
	yj_sb_guojia_prefix: "Tân Sát Mưu",
	xianmou: "Tiên Mưu",
	xianmou_info: "Kỹ năng chuyển hóa. ① Khi bắt đầu ván chơi, bạn có thể chuyển đổi trạng thái của kỹ năng này; ② Khi kết thúc lượt bạn đã mất bài, bạn có thể: Dương, xem năm lá bài trên cùng bộ bài và nhận tối đa X lá bài, nếu không nhận đủ X lá bài thì nhận được 【Di Kế】 cho đến khi phát động lại hạng mục này; Âm, xem bài trên tay của một nhân vật và bỏ tối đa X lá bài trong đó, nếu bỏ đủ X lá bài thì bạn thực hiện một lần phán định 【Sấm Sét】 (X là số bài bạn đã mất trong lượt này).",
	lunshi: "Luận Thế",
	lunshi_info: "Trong quá trình kết toán một nhân vật sử dụng bài chú thông thường nhắn vào nhân vật khác, nếu số lượng bài hai màu trên tay bạn bằng nhau, bạn có thể dùng một lá bài trên tay xem như 【Vô Tiết Khả Kích】 không thể bị đáp trả.",
	mp_liuling: "Lưu Linh",
	mpjiusong: "Tửu Tụng",
	mpjiusong_info: "① Bạn có thể dùng một bài chú xem như 【Rượu】. ② Khi một nhân vật dùng 【Rượu】, bạn nhận được 1 dấu hiệu “Túy” (số “Túy” tối đa là 3).",
	mpmaotao: "Mao Đào",
	mpmaotao_info: "Khi nhân vật khác dùng bài cơ bản hoặc bài chú thông thường chỉ định mục tiêu duy nhất, bạn có thể bỏ 1 “Túy”, khiến mục tiêu của bài này đổi thành một nhân vật hợp lệ ngẫu nhiên (không giới hạn khoảng cách). Nếu nhân vật mục tiêu giống với mục tiêu ban đầu và bạn chưa nhận được bài bằng cách này trong lượt này, bạn ngẫu nhiên nhận một bài chú từ bộ bài.",
	mpbishi: "Tịch Thế",
	mpbishi_info: "Kỹ năng khóa. Bạn không thể trở thành mục tiêu của bài chú sát thương.",
	mp_wangrong: "Vương Nhung",
	mpjianlin: "Kiệm Lận",
	mpjianlin_info: "Sau khi kết thúc mỗi lượt, nếu trong lượt này có bài cơ bản của bạn vì sử dụng, đánh ra hoặc bỏ bài mà vào bộ bài bỏ, thì bạn có thể chọn một lá bài trong số đó để nhận.",
	mpsixiao: "Tử Hiếu",
	mpsixiao_info: "Kỹ năng khóa, khi bắt đầu ván chơi, bạn chọn một nhân vật khác. Mỗi lượt giới hạn một lần, khi nhân vật đó cần dùng hoặc đánh ra bài, người đó có thể xem bài trên tay của bạn và dùng hoặc đánh ra một lá bài trong đó, sau đó bạn bốc một lá bài.",
	yj_majun: "Mã Quân",
	gongqiao: "Công Xảo",
	gongqiao_info: "① Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể đặt một lá bài trên tay vào bất kỳ ô Trang Bị nào của bạn (có thể thay thế bài Trang Bị cũ). ② Nếu bài thực thể trong khu vực Trang Bị của bạn có: ⒈ bài cơ bản, khi bạn dùng bài cơ bản, bạn khiến giá trị trên mặt bài này +1; ⒉ bài chú, khi bạn lần đầu tiên dùng một loại bài trong một lượt, bạn bốc một lá bài; ⒊ bài Trang Bị, giới hạn bài trên tay của bạn +3.",
	gongqiao_equip: "Công Xảo",
	gongqiao_equip_info: "Vốn dĩ là một lá bài Trang Bị.",
	gongqiao_trick: "Công Xảo",
	gongqiao_trick_info: "Vốn dĩ là một lá bài chú.",
	gongqiao_basic: "Công Xảo",
	gongqiao_basic_info: "Vốn dĩ là một lá bài cơ bản.",
	jingyi: "Tinh Ích",
	jingyi_info: "Kỹ năng khóa. Mỗi lượt mỗi phân loại phụ giới hạn một lần, khi có bài thực thể vào khu vực Trang Bị của bạn, bạn bốc X lá bài, sau đó bỏ hai lá bài (X là số lượng bài thực thể trong khu vực Trang Bị của bạn).",
	chuanxie: "Truyền Giới",
	chuanxie_info: "Kỹ năng khóa. ① Khi bắt đầu ván chơi, bạn chọn một hoa. ② Khi một nhân vật dùng hoa 【Truyền Giới①】, bạn đổi hoa được ghi nhận bởi 【Truyền Giới①】 thành hoa tiếp theo, sau đó nhận từ bộ bài một lá bài có hoa tiếp theo nữa (thứ tự: ♠/♥/♣/♦).",
	yjqiaosi: "Xảo Tư",
	yjqiaosi_info: "Mỗi lượt giới hạn một lần, khi bạn gây ra hoặc chịu sát thương, bạn có thể đổi hoa được ghi nhận bởi 【Truyền Giới①】 thành hoa trước đó hoặc tiếp theo.",
	yuliao: "Dư Liệu",
	yuliao_info: "① Mỗi giai đoạn giới hạn một lần, có bài vào bộ bài bỏ, bạn có thể đặt một lá bài trong số đó lên bài tướng, gọi là “Tài” (tối đa tám lá). ② Khi bạn vào trạng thái hấp hối, bạn có thể đặt tất cả “Tài” vào bộ bài bỏ, sau đó bốc số lượng bài tương ứng.",
	qiqiao: "Kỳ Xảo",
	qiqiao_info: "Giai đoạn Xuất Bài, bạn có thể đặt hai “Tài” vào bộ bài bỏ và chọn một lá bài trong khu vực Trang Bị của một nhân vật, người đó dựa vào “Tài” bạn đã bỏ để nhận được hiệu ứng sau cho đến khi lá bài này rời khỏi khu vực Trang Bị của người đó: bài cơ bản: giới hạn số lần người đó dùng 【Giết】 +1; bài chú, người đó dùng bài chú không thể bị đáp trả; bài Trang Bị, khi lá bài này rời khỏi khu vực Trang Bị của người đó, người đó bốc hai lá bài.",
	yanxie: "Nghiên Giới",
	yanxie_info: "Giai đoạn Xuất Bài. ① Bạn có thể đặt hai “Tài” cùng loại vào bộ bài bỏ và bốc số lượng bài tương ứng, sau đó ngẫu nhiên nhận một lá bài Trang Bị từ bộ bài. ② Bạn có thể đặt một lá bài Trang Bị vào khu vực Trang Bị của một nhân vật khác.",
	mp_xiangxiu: "Hướng Tú",
	mpmiaoxi: "Diệu Tích",
	mpmiaoxi_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể đồng thời tiết lộ một lá bài trên tay của bạn và một nhân vật khác, nếu hai lá bài này: cùng màu, nhận được lá bài đã tiết lộ của đối phương; cùng hoa, khiến người đó mất 1 điểm thể lực; cùng điểm số, số lần phát động 【Diệu Tích】 trong lượt này +1, sau đó hạng mục này mất hiệu lực trong lượt này.",
	mpsijiu: "Tư Cựu",
	mpsijiu_info: "Khi kết thúc lượt, nếu bạn đã nhận được bài của nhân vật khác trong lượt này, bạn có thể bốc một lá bài và xem bài trên tay của một nhân vật.",
	new_yj_dongzhuo: "☆ Đổng Trác",
	new_yj_dongzhuo_prefix: "☆",
	xiongjin: "Hùng Tiến",
	xiongjin_info: "Mỗi vòng mỗi hạng mục giới hạn một lần. ① Khi bắt đầu giai đoạn Xuất Bài, bạn có thể bốc X lá bài, sau đó khi bắt đầu giai đoạn Bỏ Bài của lượt này, bạn bỏ tất cả bài không phải cơ bản. ② Khi bắt đầu giai đoạn Xuất Bài của nhân vật khác, bạn có thể khiến người đó bốc X lá bài, sau đó khi bắt đầu giai đoạn Bỏ Bài của lượt này, người đó bỏ tất cả bài cơ bản. (X là thể lực đã mất của bạn, ít nhất là 1, tối đa là 4)",
	zhenbian: "Trấn Biên",
	zhenbian_info: "Kỹ năng khóa. ① Giới hạn bài trên tay của bạn bằng giới hạn thể lực. ② Có bài không phải do sử dụng vào bộ bài bỏ, bạn ghi nhận hoa của những bài này, sau đó nếu bạn đã ghi nhận ít nhất bốn loại hoa và giới hạn thể lực của bạn nhỏ hơn 8, thì bạn xóa ghi nhận và tăng 1 điểm giới hạn thể lực.",
	baoxi: "Bạo Tập",
	baoxi_sha: "Bạo Tập-Giết",
	baoxi_juedou: "Bạo Tập-Quyết Đấu",
	baoxi_info: "Mỗi vòng mỗi hạng mục giới hạn một lần, khi có ít nhất hai lá bài cơ bản / không cơ bản cùng lúc vào bộ bài bỏ, bạn có thể giảm 1 điểm giới hạn thể lực, dùng một lá bài trên tay xem như 【Quyết Đấu】/【Giết】 không giới hạn khoảng cách và số lần.",
	fj_peixiu: "Bùi Tú",
	fjzhitu: "Chế Đồ",
	fjzhitu_info: "Khi bạn dùng bài cơ bản hoặc bài chú đơn mục tiêu chỉ định mục tiêu duy nhất, bạn có thể khiến một số lượng nhân vật bất kỳ có khoảng cách từ bạn đến họ bằng khoảng cách từ bạn đến nhân vật mục tiêu cũng trở thành mục tiêu của bài này.",
	dcfujue: "Phục Tước",
	dcfujue_info: "Giai đoạn Xuất Bài giới hạn một lần. Bạn có thể di chuyển một lá bài trên bàn, sau đó bạn điều chỉnh bài lên năm lá. Nếu bạn nhận được và mất bài trong quy trình này, trong lượt này khoảng cách bạn tính với nhân vật khác -1.",
	xjzhitu: "Chế Đồ",
	xjzhitu_info: "① Khi bạn dùng bài hoặc trở thành mục tiêu của bài, nếu bạn chưa ghi nhận điểm số của bài này, bạn ghi nhận nó và bốc một lá bài. ② Bạn dùng bài có điểm số đã ghi nhận không giới hạn khoảng cách. ③ Nếu bạn đã ghi nhận tất cả các điểm số, bài bạn dùng không thể bị đáp trả.",
	dcxiujue: "Tu Tước",
	dcxiujue_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể thi điểm với một nhân vật khác. Nhân vật thắng có thể lần lượt sử dụng bài thi điểm của cả hai bên (nhân vật khác ngoài người thi điểm không phải là mục tiêu hợp lệ của bài này). Nếu hòa, bạn và người đó mỗi người bốc một lá bài.",
	dchuairen: "Hoài Nhận",
	dchuairen_info: "Bạn có thể dùng bài trong khu vực Trang Bị xem như bài cơ bản không giới hạn số lần. Nếu bài này: thông tin trên mặt bài có chứa bài cơ bản này, bạn bốc hai lá bài; là bài cuối cùng trong khu vực Trang Bị, giá trị sát thương gây ra hoặc lượng hồi phục +1.",
	dcchizei: "Xích Tặc",
	dcchizei_info: "Khi bạn chịu sát thương, bạn có thể dùng bài trên cùng bộ bài để thi điểm với nguồn gây sát thương, nếu bạn: thắng, bạn có thể lặp lại quy trình này; không thắng, bạn bỏ X lá bài (X là số lần bạn thắng lần này).",
	wufu: "Ngũ Phu",
	dczhonge: "Trung Ngạc",
	dczhonge_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể điều chỉnh bài trên tay lên giới hạn thể lực, cùng với một nhân vật khác đồng thời chọn một: 1. Bạn và người đó lần lượt bốc một lá bài; 2. Bạn và người đó lần lượt xem như sử dụng một 【Giết】 nhắn vào đối phương. Nếu hạng mục người đó chọn khác với bạn, bạn thực hiện thêm một lần mỗi thao tác khi thực hiện mỗi hạng mục.",
	dcjuekai: "Tuyệt Khái",
	dcjuekai_info: `Kỹ năng giới hạn, giai đoạn Xuất Bài, bạn có thể thiết lập lại ${get.poptip("dczhonge")}, sau đó cho đến khi kết thúc giai đoạn Xuất Bài, nhân vật đã nhận được bài trong giai đoạn này không thể dùng bài trên tay nữa.`,
	yj_zhanghuan: "Tân Sát Trương Hoán",
	yj_zhanghuan_prefix: "Tân Sát",
	dcyiju: "Nghĩa Cự",
	dcyiju_info: "Kỹ năng khóa, sau khi nhân vật khác dùng bài chỉ định bạn là mục tiêu duy nhất, bạn bỏ một lá bài.",
	dcshuguo: "Thú Quốc",
	dcshuguo_info: "Khi kết thúc mỗi lượt, bạn có thể lần lượt sử dụng các bài đã vào bộ bài bỏ trong lượt này vì bị bỏ cho đến khi bạn sử dụng bài bị bỏ của nhân vật khác. Nếu số bài trên tay bạn không phải là nhiều nhất duy nhất bàn, mỗi một lá bài bị bỏ trong lượt này không được sử dụng, bạn bốc một lá bài (tối đa bốc 5).",
	yj_zhangyan: "Tân Sát Trương Yến",
	yj_zhangyan_prefix: "Tân Sát",
	dcqiaolve: "Kiều Lược",
	dcqiaolve_info: "Sau khi bạn dùng bài chỉ định mục tiêu đầu tiên, nếu bao gồm nhân vật khác làm mục tiêu và trong ván chơi này đây là lần đầu tiên nhân vật đó trở thành mục tiêu của tên bài này, bạn có thể nhận một lá bài của người đó.",
	dchanjie: "Hạn Tiệp",
	dchanjie_info: "Khi bắt đầu lượt của nhân vật khác, nếu thể lực của người đó không nhỏ hơn bạn, bạn có thể dùng một lá bài đen trên tay xem như một bài sát thương sử dụng nhắn vào người đó.",
	yao_yuanshu: "Hào Viên Thuật",
	yao_yuanshu_prefix: "Hào",
	dcwangyao: "Vọng Hào",
	dcwangyao_info: "Khi bắt đầu ván chơi, bạn nhận được mỗi loại một hào “Dương”, “Âm”. Sau khi bạn trở thành mục tiêu sử dụng 【Giết】 hoặc bài chú thông thường của nhân vật khác, có thể lật một hào, sau đó nếu hai hào cùng âm hoặc cùng dương, bạn bốc một lá bài.",
	dczengua: "Tấn Quái",
	dczengua_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể bỏ một lá bài trên tay và chọn một nhân vật khác, đoán xem loại bài nào đó trong tay người đó có phải là nhiều nhất bàn hay không. Nếu đoán đúng, bạn nhận một lá bài thuộc loại đó của người đó; nếu không, người đó bốc một lá bài, bạn lật một hào.",
	dckanghui: "Kháng Hối",
	dckanghui_info: "Kỹ năng khóa, nếu hào của bạn đều là: Dương, giới hạn bài trên tay của bạn +2; Âm: sát thương do nhân vật khác gây ra cho bạn +1.",
	yj_puyuan_prefix: "SP",
	yj_puyuan: "SP Bồ Nguyên",
	biancai: "Biện Tài",
	biancai_info: "Khi bắt đầu lượt của mỗi nhân vật, bạn có thể thực hiện phán định, đỏ, bạn nhận một lá bài Trang Bị từ bộ bài; đen, bạn nhận một lá bài Trang Bị từ bộ bài bỏ.",
	cuiren: "Thối Nhận",
	cuiren_info: "Giai đoạn Xuất Bài giới hạn một lần, bạn có thể bỏ một lá bài Trang Bị, và dựa vào loại bài bỏ để nhận được hiệu ứng sau cho đến khi kết thúc lượt: vũ khí: bạn dùng bài không giới hạn khoảng cách và số lần; giáp: bài bạn dùng không thể bị đáp trả; tọa kỵ: khi bạn dùng bài chỉ định mục tiêu, có thể chỉ định thêm một số lượng mục tiêu bất kỳ.",
	shenfeng: "Thần Phong",
	shenfeng_info: "Khi bạn dùng 【Giết】 chỉ định mục tiêu, bạn có thể bỏ một lá bài Trang Bị, sau đó chọn một: 1. Khiến 【Giết】 này gây sát thương +1; 2. Khiến sát thương do 【Giết】 này gây ra được xem là mất thể lực; 3. Khiến nhân vật mục tiêu bỏ hai lá bài.",
	pyhuanling: "Hoán Linh",
	pyhuanling_info: "Khi bắt đầu giai đoạn Xuất Bài hoặc khi bạn chịu sát thương, bạn có thể tái luyện một lá bài, sau đó nhận một lá bài Trang Bị cùng hoa từ trên bàn, bộ bài bỏ hoặc bộ bài, và chọn một trong ba kỹ năng chủ binh xuất hiện ngẫu nhiên từ trang bị đó để khiến một nhân vật nhận được. Nếu nhân vật đó không phải là bạn, bạn bốc X lá bài (X là số kỹ năng của người đó).",
	pyshenduan: "Thần Đoán",
	pyshenduan_info: "Kỹ năng khóa, mỗi lượt mỗi phân loại phụ giới hạn một lần, sau khi bạn sử dụng một lá bài Trang Bị, dựa vào phân loại phụ thực hiện hiệu ứng tương ứng: vũ khí: xem như sử dụng một 【Giết】; giáp: tăng 1 điểm giới hạn thể lực và hồi phục 1 điểm thể lực; mã tấn công: bỏ mỗi nhân vật khác một lá bài; mã phòng thủ: bốc một lá bài và giới hạn bài trên tay trong ván này +1.",
	yj_hanbing: "Thiếu Nữ Hàn Băng Kiếm",
	bingling: "Băng Linh",
	bingling_info: "Khi bạn dùng 【Giết】 chỉ định mục tiêu, bạn có thể bỏ hai lá bài của nhân vật mục tiêu. Nếu hai lá bài này cùng loại / cùng hoa / cùng số chữ trong tên / cùng điểm số, thì bạn nhận được hai lá bài này / hồi phục 1 điểm thể lực / bốc X lá bài / khiến người đó mất tất cả thể lực (X là số chữ trong tên của một trong hai lá bài); nếu đều khác nhau, thì bạn chịu 1 điểm sát thương Hỏa không rõ nguồn gốc.",
	yj_tengjia: "Cậu Bé Đằng Giáp",
	tenggu: "Đằng Cố",
	tenggu_info: `Kỹ năng khóa, bạn không thể trang bị bài Giáp, bạn được xem như đang trang bị ${get.poptip("tengjia")}; khi bạn vào trạng thái hấp hối vì sát thương không phải Hỏa, giảm 1 điểm giới hạn thể lực và hồi phục tất cả thể lực.`,
	dunyong: "Độn Dũng",
	dunyong_info: "Khi bạn gây sát thương cho nhân vật khác, nếu giới hạn thể lực của bạn không phải là thấp nhất duy nhất bàn, bạn chịu lượng sát thương tương đương; khi có nhân vật vào trạng thái hấp hối, bạn bốc X lá bài, khiến bạn trong lượt này dùng bài không giới hạn khoảng cách và số lần (X là giới hạn thể lực của nhân vật hấp hối).",
	renjia: "Nhận Giáp",
	renjia_info: "Kỹ năng khóa, bạn không có khu vực Giáp; hai lần đầu mỗi vòng bạn chịu sát thương không phải thuộc tính -1, sát thương Hỏa bạn chịu +1, và bạn bốc một lá bài sau khi gây ra hoặc chịu sát thương thuộc tính.",
	yj_yanyu: "Diễm Ngục",
	yj_yanyu_info: "Kỹ năng giới hạn. Giai đoạn Xuất Bài, bạn có thể tiết lộ hai lá bài trên tay sau đó chọn một nhân vật khác A, đặt một 【Đằng Giáp】 từ bộ bài vào khu vực Giáp của người đó (thay thế trang bị cũ), nếu làm vậy, bài cơ bản cùng hoa với hai lá bài này trên tay của bạn và tất cả nhân vật khác không phải A được xem là 【Giết】 Hỏa, bài chú được xem là 【Hỏa Công】, bài Trang Bị được xem là 【Thiết Tác Liên Hoàn】, và sau khi những bài này được sử dụng, bạn bốc một lá bài.",
	yj_fazheng: "☆ Pháp Chính",
	yj_fazheng_prefix: "☆",
	youtan: "Ưu Thán",
	youtan_info: "Kỹ năng khóa, ① Khi bạn nhận được bài ngoài giai đoạn Xuất Bài, ghi nhận hoa của bài này; trong giai đoạn Xuất Bài bạn không thể dùng bài có hoa chưa được kỹ năng này ghi nhận. ② Khi bạn trở thành mục tiêu sử dụng bài của nhân vật khác, nếu hoa của bài này bạn chưa ghi nhận, người đó phải bỏ một lá bài, nếu không thì bài này vô hiệu với bạn.",
	ciren: "Từ Nhiệm",
	ciren_info: "Giai đoạn Chuẩn Bị của nhân vật khác, người đó có thể đưa cho bạn một lá bài, sau đó bạn phải chọn một: 1. Đưa cho người đó một lá bài khác cùng hoa; 2. Khiến người đó bốc một lá bài.",
	zhancai: "Triển Tài",
	zhancai_info: `Giai đoạn Xuất Bài giới hạn một lần, bạn có thể bốc số lá bài bằng số hoa ${get.poptip("youtan")} đã ghi nhận, sau đó xóa một hoa đã ghi nhận.`,
	yj_x_xunxu: "Địch Âm Tuân Huân",
	yj_x_xunxu_prefix: "Địch Âm",
	diyin: "Địch Âm",
	diyin_info: "Kỹ năng khóa, mỗi khi bạn mất bảy lá bài, bạn nhận được lá bài tiếp theo vào bộ bài bỏ; khi bạn chịu sát thương, tất cả nhân vật có thể lực giống bạn mỗi người bốc một lá bài.",
	boqia: "Bác Hiệp",
	boqia_info: "Mỗi lượt giới hạn một lần, bạn có thể dùng ba lá bài xem như một bài cơ bản hoặc bài chú thông thường không phải sát thương, nếu hoa hoặc loại của ba lá bài này đều khác nhau, sau khi bài này kết toán, bạn khiến một nhân vật điều chỉnh bài trên tay lên giới hạn thể lực của người đó, sau đó bạn xem như kỹ năng này chưa được phát động.",
	yj_y_xunxu: "Khám Luật Tuân Huân",
	yj_y_xunxu_prefix: "Khám Luật",
	kanlv: "Khám Luật",
	kanlv_info: "Khi bạn chịu sát thương, bạn có thể lật ngửa bốn lá bài trên cùng bộ bài và bài trên tay của bạn, sau đó bạn lần lượt thực hiện hai hạng mục sau: 1. Đưa mỗi loại hoa một lá trong số đó cho một nhân vật khác; 2. Bạn nhận những lá bài còn lại.",
	kanlv_append: `<span style="font-family: yuanli">Khám Luật hiện tại là phiên bản đúng ý đồ nhà thiết kế, không đủ bốn màu thì lấy bài luôn</span>`,
	yjshenwei: "Thận Vi",
	yjshenwei_info: "Sau khi bạn dùng bài, trong lượt này không thể dùng bài có hoa đó nữa, nếu bài này chỉ định nhân vật khác làm mục tiêu, bạn chịu 1 điểm sát thương; khi bạn cần dùng 【Đào】, nếu lúc này bạn không có bài nào có thể dùng, bạn có thể bỏ một loại hoa bài trên tay xem như đã dùng nó, nếu có nhân tử vì vậy thoát khỏi trạng thái hấp hối, kỹ năng này mất hiệu lực trong vòng này.",
};

export default translates;
