import { lib, game, ui, get, ai, _status } from "noname";

const translates = {
	sp_dongzhao_prefix: "Thủ Sát",
	liuba_prefix: "Thủ Sát",
	sp_zhujun_prefix: "Thủ Sát",
	sp_huangfusong_prefix: "Thủ Sát",
	sp_zhangchangpu_prefix: "Thủ Sát",
	sp_cuiyan_prefix: "Thủ Sát",
	sp_huaman_prefix: "Thủ Sát",
	sp_gaolan_prefix: "Thủ Sát",
	sunyi_prefix: "Thủ Sát",
	sp_wangshuang_prefix: "Thủ Sát",
	sp_zongyu_prefix: "Thủ Sát",
	db_wenyang_prefix: "Thủ Sát",
	sp_yanghu_prefix: "Thủ Sát",
	sp_zhangwen_prefix: "Thủ Sát",
	sp_xujing_prefix: "Thủ Sát",
	sp_huaxin_prefix: "Thủ Sát",
	zhouchu_prefix: "Thủ Sát",
	sp_mifuren_prefix: "Thủ Sát",
	sp_xinpi_prefix: "Thủ Sát",
	sp_bianfuren_prefix: "Thủ Sát",
	sp_duyu_prefix: "Thủ Sát",
	luotong_prefix: "Thủ Sát",
	sp_wangcan_prefix: "Thủ Sát",
	sp_sunshao_prefix: "Thủ Sát",
	sp_xunchen_prefix: "Thủ Sát",
	sp_kongrong_prefix: "Thủ Sát",

	sp_wangcan: "Thủ Sát Vương Sạn",
	spqiai: "Thất Ai",
	spqiai_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể đưa một lá bài không phải cơ bản cho một nhân vật khác. Sau đó người đó chọn một: ① Bạn hồi 1 điểm thể lực. ② Bạn rút hai lá bài.",
	spshanxi: "Thiện Hịch",
	spshanxi_suoming: "Thiện Hịch",
	spshanxi_info: "Khi bắt đầu giai đoạn ra bài, bạn có thể khiến một nhân vật khác nhận dấu ấn “Hịch” và xóa các dấu ấn “Hịch” khác đã có trên sân (nếu có). Nhân vật có dấu ấn “Hịch” khi hồi phục thể lực, nếu trị số thể lực lớn hơn 0, thì cần chọn một: ① Đưa cho bạn hai lá bài. ② Mất 1 điểm thể lực.",
	sp_chenzhen: "Trần Chấn",
	shameng: "Sáp Minh",
	shameng_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ hai lá bài trên tay cùng màu và chọn một nhân vật khác. Người đó rút hai lá bài, sau đó bạn rút ba lá bài.",
	sp_sunshao: "Thủ Sát Tôn Thiệu",
	fubi: "Phụ Bật",
	fubi2: "Phụ Bật",
	fubi_info: "Khi trò chơi bắt đầu, bạn có thể chọn một nhân vật khác. Giới hạn bài trên tay của nhân vật đó trước khi bạn chết được +3.",
	zuici: "Tội Từ",
	zuici_info: "Khi bạn rơi vào trạng thái hấp hối, bạn có thể phế bỏ một ô trang bị không trống của mình, sau đó hồi phục trị số thể lực về 1 điểm.",
	sp_xunchen: "Thủ Sát Tuân Thâm",
	jianzhan: "Gián Chiến",
	jianzhan_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể chọn một nhân vật A khác và một nhân vật B khác nằm trong phạm vi tấn công của A có số bài trên tay nhỏ hơn A. A chọn một: ① Xem như sử dụng một lá 【Sát】 đối với B. ② Khiến bạn rút một lá bài.",
	duoji: "Đoạt Ký",
	duoji_info: "Kỹ năng giới hạn, giai đoạn ra bài, bạn có thể bỏ hai lá bài trên tay và chọn một nhân vật khác có bài trong khu trang bị. Bạn nhận tất cả bài trong khu trang bị của người đó.",
	binglinchengxiax: "Binh Lâm Thành Hạ",
	binglinchengxiax_info: "Giai đoạn ra bài, sử dụng lên một nhân vật khác. Bạn lật ra bốn lá bài trên cùng của chồng bài, lần lượt sử dụng tất cả các lá 【Sát】 trong đó đối với người đó, sau đó đặt những lá bài còn lại lên trên cùng của chồng bài.",
	mjweipo: "Nguy Bách",
	mjweipo_effect: "Nguy Bách",
	mjweipo_remove: "Nguy Bách",
	mjweipo_info: "Mỗi lượt giới hạn một lần, giai đoạn ra bài, bạn có thể chọn một Trí Nang hoặc 【Binh Lâm Thành Hạ】, khiến một nhân vật chưa có hiệu ứng 〖Nguy Bách〗 nhận hiệu ứng dùng một lần như sau cho đến khi bắt đầu lượt tiếp theo của bạn: Người đó có thể bỏ một lá 【Sát】 trong giai đoạn ra bài, và nhận một lá bài do bạn chọn.",
	mjchenshi: "Trần Thế",
	mjchenshi_player: "Trần Thế",
	mjchenshi_target: "Trần Thế",
	mjchenshi_info: "Một nhân vật khác sau khi sử dụng 【Binh Lâm Thành Hạ】 chỉ định mục tiêu đầu tiên, có thể đưa cho bạn một lá bài, và đặt tất cả các lá bài không phải 【Sát】 trong ba lá trên cùng của chồng bài vào đống bài bỏ; một nhân vật khác sau khi trở thành mục tiêu của 【Binh Lâm Thành Hạ】, có thể đưa cho bạn một lá bài, sau đó đặt tất cả các lá 【Sát】 trong ba lá trên cùng của chồng bài vào đống bài bỏ.",
	mjmouzhi: "Mưu Thức",
	mjmouzhi_info: "Kỹ năng tỏa định, khi bạn chịu sát thương, nếu lá bài tương ứng với nguồn sát thương có cùng hoa sắc với sát thương bạn chịu lần trước, thì bạn ngăn chặn sát thương này.",
	luotong: "Thủ Sát Lạc Thống",
	qinzheng: "Cần Chính",
	qinzheng_info: "Kỹ năng tỏa định, khi bạn sử dụng hoặc đánh ra bài, nếu tổng số bài bạn đã sử dụng hoặc đánh ra trong ván game này: là bội số của 3, bạn nhận một lá 【Sát】 hoặc 【Thiểm】 từ chồng bài; là bội số của 5, bạn nhận một lá 【Đào】 hoặc 【Tửu】 từ chồng bài; là bội số của 8, bạn nhận một lá 【Quyết Đấu】 hoặc 【Vô Trung Sinh Hữu】 từ chồng bài (có thể nhận lá bài phái sinh thay thế tương ứng).",
	sp_duyu: "Thủ Sát Đỗ Dự",
	spwuku: "Vũ Kho",
	spwuku_info: "Kỹ năng tỏa định, khi có nhân vật sử dụng bài trang bị, nếu số lượng “Vũ Kho” của bạn nhỏ hơn 3, thì bạn nhận một “Vũ Kho”.",
	spwuku_info_guozhan: "Kỹ năng tỏa định, khi có nhân vật thuộc thế lực khác sử dụng bài trang bị, nếu số lượng “Vũ Kho” của bạn nhỏ hơn 2, thì bạn nhận một “Vũ Kho”.",
	spsanchen: "Tam Trần",
	spsanchen_info: `Kỹ năng thức tỉnh, giai đoạn kết thúc, nếu số lượng “Vũ Kho” của bạn lớn hơn 2, thì bạn tăng 1 điểm giới hạn thể lực và hồi 1 điểm thể lực, sau đó nhận ${get.poptip("spmiewu")}.`,
	spmiewu: "Diệt Ngô",
	spmiewu_info: "Mỗi lượt giới hạn một lần. Bạn có thể bỏ một thẻ “Vũ Kho” và dùng một lá bài như một lá bài cơ bản hoặc cẩm nang bất kỳ, sau đó rút một lá bài.",
	sp_bianfuren: "Thủ Sát Biện Phu Nhân",
	spwanwei: "Vãn Nguy",
	spwanwei_info: "Mỗi vòng tích lũy giới hạn một lần. ① Giai đoạn ra bài, bạn có thể chọn một nhân vật khác. ② Khi có nhân vật khác đang ở trạng thái hấp hối. Bạn có thể khiến nhân vật đó hồi phục X+1 điểm thể lực (ít nhất hồi về 1), sau đó bạn mất X điểm thể lực. (X là trị số thể lực của bạn)",
	spyuejian: "Ước Kiệm",
	spyuejian_info: "Kỹ năng tỏa định, cơ số giới hạn bài trên tay của bạn bằng giới hạn thể lực của bạn. Khi bạn ở trạng thái hấp hối, bạn có thể bỏ hai lá bài, sau đó hồi phục 1 điểm thể lực.",
	feiyi: "Thủ Sát Phí Y",
	feiyi_prefix: "Thủ Sát",
	reshengxi: "Sinh Tức",
	reshengxi_info: "Giai đoạn kết thúc, nếu bạn chưa gây sát thương trong lượt này, thì bạn có thể rút hai lá bài.",
	fyjianyu: "Gián Dụ",
	fyjianyu_info: "Mỗi vòng giới hạn một lần. Giai đoạn ra bài, bạn có thể chọn hai nhân vật, khiến những nhân vật này nhận “Dụ” cho đến khi bắt đầu lượt tiếp theo của bạn. Khi một nhân vật A có “Dụ” sử dụng bài chỉ định một nhân vật B khác có “Dụ” làm mục tiêu trong giai đoạn ra bài của mình, bạn khiến B rút một lá bài.",
	mjshengxi: "Sinh Tức",
	mjshengxi_info: "Giai đoạn chuẩn bị, bạn có thể nhận một lá 【Điều Tế Diêm Mai】; giai đoạn kết thúc, nếu lượt này bạn đã sử dụng bài và không gây sát thương, thì bạn có thể nhận một lá Trí Nang hoặc rút một lá bài.",
	mjkuanji: "Khoan Tế",
	mjkuanji_info: "Mỗi lượt giới hạn một lần. Khi bạn mất bài do bị bỏ bài, bạn có thể khiến một nhân vật khác nhận một trong số đó, sau đó bạn rút một lá bài.",
	tiaojiyanmei: "Điều Tế Diêm Mai",
	tiaojiyanmei_info: "Giai đoạn ra bài, sử dụng lên hai nhân vật khác có số bài trên tay không bằng nhau. Nếu nhân vật mục tiêu có số bài trên tay tại thời điểm kết thúc chuẩn bị sử dụng lá bài này lớn hơn số bài trung bình của tất cả mục tiêu lúc đó, người đó bỏ một lá bài. Nếu nhỏ hơn thì người đó rút một lá bài. Sau khi lá bài này sử dụng kết thúc, nếu số bài trên tay của tất cả nhân vật mục tiêu đều bằng nhau, thì bạn có thể khiến một nhân vật nhận tất cả các lá bài bị bỏ do thực hiện hiệu ứng của lá bài này.",
	refubi: "Phụ Bật",
	refubi_info: "Khi trò chơi bắt đầu, bạn có thể khiến một nhân vật khác nhận dấu ấn “Phụ Bật”. Khi bắt đầu giai đoạn chuẩn bị của nhân vật có dấu ấn “Phụ Bật”, bạn có thể chọn một: ① Khiến giới hạn số lần sử dụng 【Sát】 trong lượt này của người đó +1. ② Khiến giới hạn bài trên tay trong lượt này của người đó +3.",
	rezuici: "Tội Từ",
	rezuici_backup: "Tội Từ",
	rezuici_info: "Giai đoạn ra bài, hoặc khi bạn đang ở trạng thái hấp hối, bạn có thể phế bỏ một ô trang bị có bài và hồi phục 2 điểm thể lực, sau đó có thể di chuyển dấu ấn “Phụ Bật”.",
	mjdingyi: "Định Nghi",
	mjdingyi_info: "Khi trò chơi bắt đầu, bạn chọn một hiệu ứng (hiệu ứng giống nhau không thể cộng dồn) và khiến toàn bộ nhân vật trên sân nhận được: ① Số bài rút định mức trong giai đoạn rút bài +1. ② Giới hạn bài trên tay +2. ③ Phạm vi tấn công +1. ④ Hồi phục 1 điểm thể lực khi thoát khỏi trạng thái hấp hối.",
	mjzuici: "Tội Từ",
	mjzuici_info: "Sau khi bạn chịu sát thương, bạn có thể khiến nguồn sát thương mất hiệu ứng 〖Định Nghi〗, sau đó khiến người đó nhận một lá Trí Nang do bạn chọn từ chồng bài.",
	mjfubi: "Phụ Bật",
	mjfubi_info: "Mỗi vòng giới hạn một lần. Giai đoạn ra bài, bạn có thể chọn một: ① Thay đổi hiệu ứng 〖Định Nghi〗 của một nhân vật. ② Bỏ một lá bài và khiến hiệu ứng 〖Định Nghi〗 của một nhân vật tăng gấp đôi cho đến khi bắt đầu lượt tiếp theo của bạn.",
	wujing: "Ngô Cảnh",
	heji: "Hợp Kích",
	heji_info: "Khi có lá 【Quyết Đấu】 hoặc 【Sát】 đỏ do nhân vật sử dụng kết thúc kết toán, nếu số mục tiêu tương ứng của lá bài này là 1, thì bạn có thể sử dụng một lá 【Sát】 hoặc 【Quyết Đấu】 đối với cùng mục tiêu đó (không giới hạn khoảng cách và số lần). Nếu lá bài bạn sử dụng theo cách này không phải là bài chuyển hóa, thì bạn nhận ngẫu nhiên một lá bài đỏ từ chồng bài.",
	liubing: "Lưu Binh",
	liubing_info: "Kỹ năng tỏa định. ① Lá 【Sát】 không hư cấu đầu tiên bạn sử dụng trong giai đoạn ra bài được coi là hoa Rô ♦. ② Sau khi lá 【Sát】 đen không chuyển hóa do nhân vật khác sử dụng trong giai đoạn ra bài của họ kết thúc kết toán, nếu lá 【Sát】 này không gây sát thương, thì bạn nhận lấy nó.",
	sp_mifuren: "Thủ Sát Mi Phu Nhân",
	spcunsi: "Tồn Tự",
	spcunsi2: "Tồn Tự",
	spcunsi_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể lật mặt thẻ võ tướng ra sau và chọn một nhân vật khác. Người đó nhận một lá 【Sát】 từ chồng bài hoặc đống bài bỏ, và sát thương cơ bản của lá 【Sát】 tiếp theo được +1.",
	spguixiu: "Khuê Tú",
	spguixiu_info: "Kỹ năng tỏa định, sau khi bạn chịu sát thương, nếu mặt thẻ võ tướng của bạn đang lật sau, thì bạn lật mặt thẻ võ tướng lên trước. Khi thẻ võ tướng của bạn từ mặt sau lật lên mặt trước, bạn rút một lá bài.",
	qingyu: "Thanh Ngọc",
	qingyu_info: `Kỹ năng sứ mệnh. ① Khi bạn chịu sát thương, bạn bỏ hai lá bài, sau đó ngăn chặn sát thương này. ② Sứ mệnh: Giai đoạn chuẩn bị, nếu trị số thể lực của bạn bằng giới hạn thể lực và số bài trên tay của bạn nhỏ hơn số vòng chơi, thì bạn nhận ${get.poptip("xuancun")}. ③ Thất bại: Khi bạn rơi vào trạng thái hấp hối, bạn giảm 1 điểm giới hạn thể lực, khiến một nhân vật khác nhận ${get.poptip("mbyongjue")}.`,
	xuancun: "Huyền Tồn",
	xuancun_info: "Khi lượt của nhân vật khác kết thúc, nếu số bài trên tay của bạn nhỏ hơn trị số thể lực, thì bạn có thể khiến người đó rút X lá bài (X là hiệu số giữa trị số thể lực và số bài trên tay của bạn, tối đa là 2).",
	mbyongjue: "Dũng Quyết",
	mbyongjue_info: "Kỹ năng tỏa định, nếu lá bài đầu tiên một nhân vật sử dụng trong lượt của mình là 【Sát】, bạn nhận lấy nó sau khi lá 【Sát】 này kết thúc kết toán.",
	xinlirang: "Lễ Nhượng",
	xinlirang_info: "① Khi bắt đầu giai đoạn rút bài của nhân vật khác, nếu bạn không có dấu ấn “Khiêm”, thì bạn có thể nhận một dấu ấn “Khiêm”. Nếu làm vậy, số bài rút định mức của người đó +2, và khi bắt đầu giai đoạn bỏ bài của lượt này, bạn có thể nhận tối đa hai lá bài mà người đó bỏ đi. ② Giai đoạn chuẩn bị, nếu bạn có dấu ấn “Khiêm”, thì bạn bỏ qua giai đoạn rút bài tiếp theo và xóa dấu ấn “Khiêm”.",
	xinmingshi: "Danh Sĩ",
	xinmingshi_info: "Kỹ năng tỏa định, sau khi bạn chịu sát thương, nếu bạn có dấu ấn “Khiêm”, thì nguồn sát thương bỏ một lá bài trong khu vực của mình. Nếu lá bài này là: Màu đen: Bạn nhận lấy nó. Màu đỏ: Bạn hồi 1 điểm thể lực.",
	sp_xinpi: "Thủ Sát Tân Tì",
	spyinju: "Dẫn Cứ",
	spyinju2: "Dẫn Cứ",
	spyinju_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể khiến một nhân vật khác chọn một: ① Sử dụng một lá 【Sát】 đối với bạn (không giới hạn khoảng cách). ② Khi bắt đầu giai đoạn chuẩn bị của lượt tiếp theo của người đó, bỏ qua giai đoạn ra bài và giai đoạn bỏ bài.",
	spchijie: "Trì Tiết",
	spchijie_info: "Mỗi lượt giới hạn một lần. Khi bạn trở thành mục tiêu duy nhất của lá bài do nhân vật khác sử dụng, bạn có thể phán xét. Nếu kết quả lớn hơn 6, thì bạn hủy bỏ tất cả mục tiêu của lá bài này.",
	reduoji: "Đoạt Ký",
	reduoji_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể đặt một lá bài lên thẻ võ tướng của nhân vật khác, gọi là “Ký”. Khi có bài trang bị đi vào khu trang bị của một nhân vật do được sử dụng, nếu nhân vật đó có “Ký” và là người sử dụng, thì bạn nhận lá bài trang bị này, người đó dời đi một “Ký” và rút một lá bài. Sau khi lượt của một nhân vật khác kết thúc, nếu người đó có “Ký”, thì bạn nhận tất cả “Ký” của người đó.",
	wangling: "Vương Lăng",
	mouli: "Mưu Lập",
	mouli_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể đưa một lá bài trên tay cho một nhân vật khác, người đó nhận hiệu ứng sau cho đến khi bắt đầu lượt tiếp theo của bạn: Người đó có thể dùng bài đen như 【Sát】, bài đỏ như 【Thiểm】. Thời điểm người đó lần đầu kích hoạt “Sau khi sử dụng 【Sát】/【Thiểm】 kết thúc kết toán”, bạn rút ba lá bài.",
	zifu: "Tự Phược",
	zifu_info: "Kỹ năng tỏa định, khi có nhân vật chết, nếu hiệu ứng “Mưu Lập” người đó nhận từ bạn chưa hết hạn, thì bạn giảm 2 điểm giới hạn thể lực.",
	xingqi: "Tinh Khải",
	xingqi_info: "① Khi bạn sử dụng bài, nếu lá bài này không phải cẩm nang duy trì và bạn chưa có “Bị” cùng tên, thì bạn nhận một thẻ “Bị” có tên giống với lá bài này. ② Giai đoạn kết thúc, bạn có thể dời đi một thẻ “Bị”, sau đó nhận một lá bài có cùng tên với “Bị” này từ chồng bài.",
	xinzifu: "Tự Phược",
	xinzifu_info: "Kỹ năng tỏa định. Khi giai đoạn ra bài kết thúc, nếu bạn không sử dụng bài trong giai đoạn này, thì bạn dời đi tất cả “Bị” và giới hạn bài trên tay của lượt này -1.",
	mibei: "Mật Bị",
	mibei_info: `Kỹ năng sứ mệnh. ① Sứ mệnh: Sau khi lá bài bạn sử dụng kết thúc kết toán, nếu trong “Bị” của bạn bao gồm bài cơ bản, bài cẩm nang, bài trang bị với số lượng mỗi loại đều lớn hơn 1, thì bạn nhận từ chồng bài mỗi loại một lá và nhận kỹ năng ${get.poptip("xinmouli")}. ② Thất bại: Khi bắt đầu giai đoạn kết thúc, nếu bạn không có “Bị”, và bạn cũng không có “Bị” khi bắt đầu giai đoạn chuẩn bị của lượt này, thì bạn giảm 1 điểm giới hạn thể lực.`,
	xinmouli: "Mưu Lập",
	xinmouli_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể chỉ định một nhân vật khác. Người đó dời đi một “Bị” của bạn, sau đó nhận một lá bài cùng tên với “Bị” này từ chồng bài.",
	wangfuzhaolei: "Vương Phủ Triệu Lũy",
	xunyi: "Tuẫn Nghĩa",
	xunyi2: "Tuẫn Nghĩa",
	xunyi3: "Tuẫn Nghĩa",
	xunyi_info: "① Khi trò chơi bắt đầu, bạn khiến một nhân vật khác nhận “Nghĩa”; sau khi nhân vật có hiệu ứng “Nghĩa” chết, bạn có thể khiến một nhân vật khác nhận “Nghĩa”. ② Khi bạn hoặc nhân vật “Nghĩa” gây ra/chịu 1 điểm sát thương, nếu nhân vật chịu thương/nguồn sát thương không phải là bên còn lại, khiến bên còn lại rút một lá bài/bỏ một lá bài.",
	zhouchu: "Thủ Sát Chu Xử",
	xianghai: "Hương Hại",
	xianghai_info: "Kỹ năng tỏa định, giới hạn bài trên tay của nhân vật khác -1. Các lá bài trang bị trong khu bài trên tay của bạn đều được coi là 【Tửu】.",
	chuhai: "Trừ Hại",
	chuhai_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể rút một lá bài, sau đó đấu điểm với một nhân vật khác. Nếu bạn thắng, thì bạn xem bài trên tay của người đó, và nhận từ chồng bài/đống bài bỏ mỗi loại bài có trong bài trên tay của người đó một lá, và khi bạn gây sát thương cho người đó trong giai đoạn này, bạn đặt một lá bài trang bị từ chồng bài/đống bài bỏ vào một ô trang bị trống của mình.",
	rechuhai: "Trừ Hại",
	rechuhai_info: `Kỹ năng sứ mệnh. ① Giai đoạn ra bài giới hạn một lần, bạn có thể rút một lá bài, sau đó đấu điểm với một nhân vật khác. Nếu bạn thắng, thì bạn xem bài trên tay của người đó, và nhận từ chồng bài/đống bài bỏ mỗi loại bài có trong bài trên tay của người đó một lá, và khi bạn gây sát thương cho người đó trong giai đoạn này, bạn đặt một lá bài trang bị từ chồng bài/đống bài bỏ vào một ô trang bị trống của mình. ② Khi bạn tung bài đấu điểm do phát động 〖Trừ Hại ①〗, bạn khiến điểm số của lá bài này +X (X=(4 - số bài trong khu trang bị của bạn)). ③ Sứ mệnh: Khi có bài trang bị đi vào khu trang bị của bạn, nếu trong khu trang bị của bạn có ít nhất ba lá bài, thì bạn hồi phục trị số thể lực về giới hạn, mất 〖Hương Hại〗 và nhận ${get.poptip("zhangming")}. ④ Thất bại: Khi bạn đấu điểm do phát động 〖Trừ Hại ①〗 mà không thắng, nếu điểm số cuối cùng của bạn không lớn hơn 6, thì bạn kích hoạt nhánh sứ mệnh thất bại.`,
	zhangming: "Chương Danh",
	zhangming_info: "Kỹ năng tỏa định. ① Lá bài ♣ bạn sử dụng không thể bị nhân vật khác đáp trả. ② Mỗi lượt giới hạn một lần, sau khi bạn gây sát thương cho nhân vật khác, bạn bỏ ngẫu nhiên một lá bài trên tay của người đó, sau đó bạn nhận từ chồng bài hoặc đống bài bỏ mỗi loại bài khác với loại bài đã bỏ một lá (nếu người đó không có bài trên tay, thì bạn thay bằng việc nhận từ chồng bài hoặc đống bài bỏ mỗi loại bài một lá), và lá bài nhận được theo cách này không tính vào giới hạn bài trên tay của lượt này.",
	sp_kongrong: "Thủ Sát Khổng Dung",
	spmingshi: "Danh Sĩ",
	spmingshi_info: "Kỹ năng tỏa định, sau khi bạn chịu 1 điểm sát thương, nguồn sát thương bỏ một lá bài.",
	splirang: "Lễ Nhượng",
	splirang_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ tất cả bài trên tay, sau đó đưa tối đa X lá bài trong số đó cho một nhân vật khác (X là trị số thể lực của bạn), sau đó rút một lá bài.",
	caizhenji: "Thái Trinh Cơ",
	sheyi: "Xá Duệ",
	sheyi_info: "Mỗi vòng giới hạn một lần. Khi có nhân vật khác có trị số thể lực nhỏ hơn bạn chịu sát thương, bạn có thể đưa cho người đó ít nhất X lá bài và ngăn chặn sát thương này (X là trị số thể lực của bạn).",
	tianyin: "Thiên Âm",
	tianyin_info: "Kỹ năng tỏa định, khi bắt đầu giai đoạn kết thúc, bạn nhận từ chồng bài mỗi loại bài chưa được sử dụng trong lượt này một lá.",
	xiangchong: "Hướng Sủng",
	guying: "Cố Doanh",
	guying_info: "Kỹ năng tỏa định. Mỗi lượt giới hạn một lần, khi bạn mất bài ngoài lượt của mình, nếu số bài là 1, thì bạn nhận 1 thẻ “Cố” và khiến nhân vật của lượt hiện tại chọn một: ① Giao ngẫu nhiên cho bạn một lá bài. ② Khiến bạn nhận lại lá bài vừa mất, nếu là bài trang bị, thì bạn sử dụng nó. Khi bắt đầu giai đoạn chuẩn bị, bạn dời đi tất cả “Cố” và bỏ số bài tương ứng.",
	muzhen: "Mục Trận",
	muzhen_backup: "Mục Trận",
	muzhen_info: "Giai đoạn ra bài mỗi loại giới hạn một lần. ① Bạn có thể đưa tối đa hai lá bài cho một nhân vật khác có bài trong khu trang bị, sau đó nhận một lá bài trong khu trang bị của người đó. ② Bạn có thể đặt một lá bài trang bị vào khu trang bị của nhân vật khác, sau đó nhận một lá bài trên tay của người đó. ③ Bạn có thể chọn bất kỳ số lượng nhân vật khác, mỗi khi những nhân vật này có số bài trên tay hoặc số bài trang bị giống bạn ở một hạng mục, người đó rút một lá bài, nếu những nhân vật này đều rút hai lá bài, bạn rút số bài bằng số nhân vật đã chọn.",
	sp_huaxin: "Thủ Sát Hoa Hâm",
	hxrenshi: "Nhân Sĩ",
	hxrenshi_info: "Giai đoạn ra bài mỗi nhân vật giới hạn một lần. Bạn có thể đưa một lá bài trên tay cho một nhân vật khác.",
	debao: "Đức Bảo",
	debao_info: "Kỹ năng tỏa định, khi nhân vật khác nhận được bài của bạn, nếu số lượng “Nhân” của bạn nhỏ hơn giới hạn thể lực, thì bạn đặt một lá bài từ trên cùng chồng bài lên thẻ võ tướng, gọi là “Nhân”. Giai đoạn chuẩn bị, bạn nhận lấy tất cả “Nhân”.",
	buqi: "Bất Khí",
	buqi_info: "Kỹ năng tỏa định, khi có nhân vật rơi vào trạng thái hấp hối, nếu số lượng “Nhân” của bạn lớn hơn 1, thì bạn dời đi hai lá “Nhân” và khiến người đó hồi 1 điểm thể lực. Sau khi một nhân vật chết, bạn đặt tất cả “Nhân” vào đống bài bỏ.",
	yuanqing: "Uyên Thanh",
	yuanqing_info: "Kỹ năng tỏa định, khi giai đoạn ra bài kết thúc, bạn ngẫu nhiên đặt mỗi loại bài bạn đã sử dụng trong lượt này từ đống bài bỏ vào kho Nhân.",
	shuchen: "Sơ Trần",
	shuchen_info: "Kỹ năng tỏa định, khi có nhân vật rơi vào trạng thái hấp hối, nếu số bài trong kho Nhân lớn hơn ba, thì bạn nhận tất cả bài trong kho Nhân, sau đó người đó hồi 1 điểm thể lực.",
	sp_xujing: "Thủ Sát Hứa Tĩnh",
	boming: "Bác Danh",
	boming_info: "Giai đoạn ra bài giới hạn hai lần, bạn có thể đưa một lá bài cho một nhân vật khác. Giai đoạn kết thúc, nếu lượt này bạn đã mất hơn hai lá bài theo cách này, thì bạn rút một lá bài.",
	ejian: "Ác Tiến",
	ejian_info: "Kỹ năng tỏa định, mỗi nhân vật giới hạn một lần. Khi có nhân vật khác nhận được bài của bạn do 〖Bác Danh〗, nếu người đó sở hữu bài khác cùng loại với lá bài này, thì bạn khiến người đó chọn một: ① Chịu 1 điểm sát thương. ② Hiển thị tất cả bài trên tay, và bỏ tất cả bài cùng loại với lá bài này.",
	zhangzhongjing: "Trương Cơ",
	jishi: "Tế Thế",
	jishi_info: "Kỹ năng tỏa định. ① Sau khi lá bài bạn sử dụng kết thúc kết toán, nếu bạn không gây sát thương từ lá bài này, thì bạn đặt tất cả các lá bài thực thể tương ứng vào kho Nhân. ② Khi có bài không phải do tràn bộ nhớ mà rời khỏi kho Nhân, bạn rút một lá bài.",
	liaoyi: "Liệu Dịch",
	liaoyi_info: "Khi bắt đầu lượt của nhân vật khác, nếu người đó: ① Số bài trên tay nhỏ hơn trị số thể lực và số bài trong kho Nhân lớn hơn hoặc bằng X, thì bạn có thể khiến người đó nhận X lá bài từ kho Nhân; ② Số bài trên tay lớn hơn trị số thể lực, thì bạn có thể khiến người đó đặt X lá bài vào kho Nhân (X là hiệu số giữa số bài trên tay và trị số thể lực của người đó, tối đa là 4).",
	xinliaoyi: "Liệu Dịch",
	xinliaoyi_info: "Khi bắt đầu lượt của nhân vật khác, bạn có thể chọn một: ① Khiến người đó nhận một lá bài từ kho Nhân. ② Nếu số bài trên tay của người đó lớn hơn trị số thể lực, thì khiến người đó đặt X lá bài trên tay vào kho Nhân (X là hiệu số giữa số bài trên tay và trị số thể lực của người đó).",
	binglun: "Bệnh Luận",
	binglun_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể đặt một lá bài trong kho Nhân vào đống bài bỏ và chọn một nhân vật. Nhân vật đó chọn một: ① Rút một lá bài. ② Hồi phục 1 điểm thể lực khi kết thúc lượt tiếp theo của mình.",
	sp_zhangwen: "Thủ Sát Trương Ôn",
	gebo: "Qua Bạc",
	gebo_info: "Kỹ năng tỏa định, khi có nhân vật hồi phục thể lực, bạn đặt một lá bài từ trên cùng chồng bài vào kho Nhân.",
	spsongshu: "Tụng Thục",
	spsongshu_info: "Khi bắt đầu giai đoạn rút bài của nhân vật khác, nếu trị số thể lực của người đó lớn hơn bạn và trong kho Nhân có bài, thì bạn có thể khiến người đó từ bỏ rút bài. Người đó thay bằng việc nhận X lá bài Nhân (X là trị số thể lực của bạn, tối đa là 5), và trong lượt này không thể sử dụng bài chỉ định nhân vật khác làm mục tiêu.",
	liuzhang: "Lưu Chương",
	xiusheng: "Hưu Sinh",
	xiusheng_info: "Kỹ năng tỏa định. Giai đoạn chuẩn bị, bạn đặt tất cả “Sinh” vào đống bài bỏ, sau đó rút X lá bài, và đặt số bài tương đương lên thẻ võ tướng, gọi là “Sinh” (X là số nhân vật còn sống của thế lực bạn chọn do 〖Dẫn Lang〗).",
	yinlang: "Dẫn Lang",
	yinlang_info: "① Mỗi vòng giới hạn một lần. Khi bắt đầu lượt, bạn chọn một thế lực trên sân. ② Khi bắt đầu giai đoạn ra bài của một nhân vật, nếu thế lực của người đó giống với thế lực bạn đã chọn, thì người đó chọn một: 1. Nhận một lá “Sinh” của bạn, sau đó khi người đó sử dụng bài trong lượt này không thể chỉ định mục tiêu là nhân vật khác ngoài bạn. 2. Bạn nhận một lá “Sinh”.",
	huaibi: "Hoài Bích",
	huaibi_info: "Kỹ năng chủ công, kỹ năng tỏa định. Giới hạn bài trên tay của bạn +X (X là số nhân vật còn sống của thế lực bạn chọn do 〖Dẫn Lang〗).",
	jutu: "Cứ Thổ",
	jutu_info: "Kỹ năng tỏa định, giai đoạn chuẩn bị, bạn nhận lấy tất cả “Sinh” trên thẻ võ tướng của mình, sau đó rút X+1 lá bài, rồi đặt X lá bài lên thẻ võ tướng của mình, gọi là “Sinh” (X là số lượng nhân vật của thế lực bạn chọn do 〖Yêu Hổ〗).",
	yaohu: "Yêu Hổ",
	yaohu_info: "Mỗi vòng giới hạn một lần, khi bắt đầu lượt của bạn, bạn phải chọn một thế lực trên sân. Khi bắt đầu giai đoạn ra bài của các nhân vật khác thuộc thế lực đó, người đó nhận một lá “Sinh” của bạn, sau đó người đó phải chọn một: ① Sử dụng một lá 【Sát】 đối với một nhân vật khác do bạn chỉ định (không giới hạn khoảng cách và số lần); ② Đưa cho bạn hai lá bài.",
	rehuaibi: "Hoài Bích",
	rehuaibi_info: "Kỹ năng chủ công, kỹ năng tỏa định, giới hạn bài trên tay của bạn +X (X là số lượng nhân vật của thế lực bạn chọn do 〖Yêu Hổ〗).",
	qiaogong: "Kiều Công",
	yizhu: "Di Châu",
	yizhu_info: "① Giai đoạn kết thúc, bạn rút hai lá bài, sau đó ngẫu nhiên chèn hai lá bài vào vị trí trong 2X lá bài đầu tiên của chồng bài (X là số nhân vật, tên lá bài được chọn hiển thị công khai cho các nhân vật khác). ② Khi nhân vật khác sử dụng lá bài “Di Châu” chỉ định mục tiêu duy nhất, bạn có thể hủy bỏ mục tiêu này, sau đó bạn xóa dấu ấn “Di Châu” tương ứng.",
	luanchou: "Loan Trù",
	luanchou_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể khiến hai nhân vật nhận dấu ấn “Nhân” và xóa dấu ấn cũ. Nhân vật có dấu ấn “Nhân” được coi là sở hữu kỹ năng 〖Cộng Hoạn〗.",
	gonghuan: "Cộng Hoạn",
	gonghuan_info: "Kỹ năng tỏa định. Mỗi lượt giới hạn một lần, khi một nhân vật khác chịu sát thương, nếu người đó có dấu ấn “Nhân” và trị số thể lực nhỏ hơn bạn, thì bạn chuyển sát thương đó cho chính mình. Sau khi kết toán sát thương này kết thúc, bạn và người đó dời đi dấu ấn “Nhân”.",
	sp_yanghu: "Thủ Sát Dương Hựu",
	mingfa: "Minh Phạt",
	mingfa_info: "① Giai đoạn kết thúc, bạn có thể hiển thị một lá bài và ghi nhớ là “Minh Phạt”. ② Khi bắt đầu giai đoạn ra bài, nếu lá bài “Minh Phạt” đang ở trong khu bài trên tay hoặc khu trang bị của bạn, thì bạn có thể sử dụng lá bài “Minh Phạt” để đấu điểm với một nhân vật khác. Nếu bạn thắng: Bạn nhận một lá bài của đối phương và nhận một lá bài có điểm số bằng điểm số của lá bài “Minh Phạt” - 1 từ chồng bài. Nếu bạn không thắng: Bạn không thể sử dụng bài chỉ định nhân vật khác làm mục tiêu trong lượt này. ③ Sau khi lá bài đấu điểm của bạn lật ra, bạn khiến điểm số của lá bài này +2.",
	rongbei: "Nhung Bị",
	rongbei_info: "Kỹ năng giới hạn. Giai đoạn ra bài, bạn có thể chọn một nhân vật có ô trang bị trống. Hệ thống chọn một lá bài trang bị cho mỗi ô trang bị trống của nhân vật đó, sau đó nhân vật đó sử dụng chúng.",
	db_wenyang: "Thủ Sát Văn Ương",
	dbquedi: "Khước Địch",
	dbquedi_info: `Mỗi lượt giới hạn một lần. Khi bạn sử dụng 【Sát】 hoặc 【Quyết Đấu】 chỉ định mục tiêu duy nhất, bạn có thể chọn: ① Nhận một lá bài trên tay của nhân vật mục tiêu. ② Bỏ một lá bài cơ bản, và khiến sát thương cơ bản của lá bài này +1. ③ ${get.poptip("rule_beishui")}: Giảm 1 điểm giới hạn thể lực.`,
	dbzhuifeng: "Truy Phong",
	dbzhuifeng_info: "Kỹ năng thế lực Ngụy. Mỗi lượt giới hạn hai lần, bạn có thể mất 1 điểm thể lực và coi như sử dụng một lá 【Quyết Đấu】 (vẫn kết toán sau khi bạn chết). Khi bạn chịu sát thương do lá 【Quyết Đấu】 này, bạn ngăn chặn sát thương này và khiến kỹ năng này mất hiệu lực cho đến khi giai đoạn ra bài kết thúc.",
	dbchongjian: "Xung Kiên",
	dbchongjian_backup: "Xung Kiên",
	dbchongjian_info: "Kỹ năng thế lực Ngô. Bạn có thể dùng một lá bài trang bị như một loại 【Sát】 (không giới hạn khoảng cách và bỏ qua phòng cụ) hoặc 【Tửu】. Khi bạn sử dụng 【Sát】 theo cách này gây sát thương, bạn nhận X lá bài trong khu trang bị của nhân vật mục tiêu (X là trị số sát thương).",
	dbchoujue: "Cừu Quyết",
	dbchoujue_info: "Kỹ năng tỏa định. Sau khi bạn giết nhân vật khác, bạn tăng 1 điểm giới hạn thể lực và rút hai lá bài, sau đó giới hạn số lần phát động 〖Khước Địch〗 trong lượt này của bạn +1.",
	sp_chendong: "Thủ Sát Trần Vũ Đổng Tập",
	sp_chendong_prefix: "Thủ Sát",
	spyilie: "Nghị Liệt",
	spyilie_info: `Khi bắt đầu giai đoạn ra bài, bạn có thể chọn: ① Giới hạn số lần sử dụng 【Sát】 trong giai đoạn này +1. ② Trong lượt này khi sử dụng 【Sát】 bị 【Thiểm】 triệt tiêu, rút một lá bài. ③ ${get.poptip("rule_beishui")}: Mất 1 điểm thể lực.`,
	spfenming: "Phấn Mệnh",
	spfenming_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể chọn một nhân vật có trị số thể lực không lớn hơn bạn. Nếu người đó: Chưa bị xích, người đó bị xích; Đã bị xích, bạn nhận một lá bài của người đó.",
	yuanhuan: "Viên Hoán",
	qingjue: "Thỉnh Quyết",
	qingjue_info: "Mỗi vòng giới hạn một lần. Khi có nhân vật A khác sử dụng bài chỉ định một nhân vật B khác có trị số thể lực nhỏ hơn A và không ở trạng thái hấp hối làm mục tiêu duy nhất, bạn có thể rút một lá bài, sau đó đấu điểm với A. Nếu bạn thắng, bạn hủy bỏ mục tiêu này. Nếu bạn không thắng, bạn đổi mục tiêu của lá bài này thành chính mình.",
	fengjie: "Phụng Tiết",
	fengjie2: "Phụng Tiết",
	fengjie_info: "Kỹ năng tỏa định, khi bắt đầu giai đoạn chuẩn bị, bạn chọn một nhân vật khác và nhận hiệu ứng sau cho đến khi bắt đầu lượt tiếp theo của bạn: Khi bắt đầu giai đoạn kết thúc của một nhân vật, bạn rút bài cho đến khi (tối đa rút đến bốn lá) hoặc bỏ bài cho đến khi bằng với trị số thể lực của người đó.",
	sp_zongyu: "Thủ Sát Tông Dự",
	zhibian: "Trực Biện",
	zhibian_info: `Giai đoạn chuẩn bị, bạn có thể đấu điểm với một nhân vật khác. Nếu bạn thắng, bạn có thể chọn: ① Di chuyển một lá bài trong khu trang bị/khu phán xét của người đó sang khu vực tương ứng của bạn. ② Hồi phục 1 điểm thể lực. ③ ${get.poptip("rule_beishui")}: Bỏ qua giai đoạn rút bài tiếp theo; nếu bạn không thắng, bạn mất 1 điểm thể lực.`,
	yuyan: "Ngự Nghiêm",
	yuyan_info: "Kỹ năng tỏa định. Khi bạn trở thành mục tiêu của lá 【Sát】 không chuyển hóa, nếu trị số thể lực của người sử dụng lớn hơn bạn và lá 【Sát】 này có điểm số, thì bạn khiến người sử dụng chọn một: ① Đưa cho bạn một lá bài có điểm số lớn hơn lá 【Sát】 này. ② Hủy bỏ mục tiêu này.",
	sp_wangshuang: "Thủ Sát Vương Song",
	yiyong: "Dị Dũng",
	yiyong_info: "Khi bạn chịu sát thương từ nguồn là 【Sát】 do nhân vật khác gây ra, nếu trong khu trang bị của bạn có bài vũ khí, thì bạn có thể nhận tất cả các lá bài thực thể tương ứng với lá 【Sát】 này, sau đó dùng những lá bài này như 【Sát】 sử dụng đối với nguồn sát thương (không giới hạn khoảng cách). Nếu trong khu trang bị của người đó không có bài vũ khí, thì sát thương này +1.",
	shanxie: "Thiện Giới",
	shanxie_info: "① Giai đoạn ra bài giới hạn một lần, bạn có thể nhận một lá bài vũ khí từ chồng bài. Nếu trong chồng bài không có bài vũ khí, thì bạn đổi thành việc nhận ngẫu nhiên một lá bài vũ khí trong khu trang bị của một nhân vật. ② Khi nhân vật khác sử dụng 【Thiểm】 để đáp trả lá 【Sát】 do bạn sử dụng, nếu lá 【Thiểm】 này không có điểm số hoặc điểm số không lớn hơn hai lần phạm vi tấn công của bạn, thì bạn khiến lá 【Thiểm】 này vô hiệu.",
	shanxie_info_old: "① Giai đoạn ra bài giới hạn một lần, bạn có thể chọn một: ⒈ Nhận một lá bài vũ khí từ chồng bài. ⒉ Nhận một lá bài vũ khí trong khu trang bị của nhân vật khác và sử dụng, sau đó người đó dùng một lá bài trên tay như 【Sát】 sử dụng đối với bạn. ② Khi nhân vật khác sử dụng 【Thiểm】 để đáp trả lá 【Sát】 do bạn sử dụng, nếu lá 【Thiểm】 này không có điểm số hoặc điểm số không lớn hơn hai lần phạm vi tấn công của bạn, thì bạn khiến lá 【Thiểm】 này vô hiệu.",
	sunyi: "Thủ Sát Tôn Dực",
	zaoli: "Táo Lệ",
	zaoli_info: "Kỹ năng tỏa định. ① Bạn không thể sử dụng hoặc đánh ra lá bài trên tay không phải là lá bài nhận được trong lượt này. ② Khi bạn sử dụng hoặc đánh ra bài trên tay, bạn nhận một “Lệ” (tối đa 4 cái). ③ Khi bắt đầu lượt, nếu bạn có “Lệ”, thì bạn dời đi tất cả “Lệ” và bỏ bất kỳ số lá bài nào, sau đó rút X+Y lá bài. Nếu X lớn hơn 2, bạn mất 1 điểm thể lực (X là số dấu ấn bạn dời đi, Y là số lá bài bạn bỏ).",
	sp_gaolan: "Thủ Sát Cao Lãm",
	spjungong: "Tuấn Công",
	spjungong_info: "Giai đoạn ra bài, bạn có thể mất X+1 điểm thể lực hoặc bỏ X+1 lá bài trên tay, coi như sử dụng một lá 【Sát】 đối với một nhân vật khác (không tính vào giới hạn số lần và khoảng cách, X là số lần bạn đã phát động 〖Tuấn Công〗 trong lượt này). Nếu bạn gây sát thương từ lá 【Sát】 này, thì bạn khiến kỹ năng này mất hiệu lực cho đến khi kết thúc lượt.",
	spdengli: "Đẳng Lực",
	spdengli_info: "Khi bạn sử dụng 【Sát】 chỉ định mục tiêu, hoặc trở thành mục tiêu của 【Sát】, nếu trị số thể lực của người sử dụng và mục tiêu bằng nhau, thì bạn rút một lá bài.",
	sp_huaman: "Thủ Sát Hoa Man",
	spxiangzhen: "Tượng Trận",
	spxiangzhen_info: "Kỹ năng tỏa định. ① 【Nam Man Nhập Xâm】 vô hiệu đối với bạn. ② Khi lá 【Nam Man Nhập Xâm】 do nhân vật sử dụng kết thúc kết toán, nếu có nhân vật chịu sát thương từ lá bài này, thì bạn và nguồn sát thương mỗi người rút một lá bài.",
	spfangzong: "Phương Tung",
	spfangzong_info: "Kỹ năng tỏa định. ① Bạn không thể sử dụng lá bài có nhãn sát thương chỉ định nhân vật trong phạm vi tấn công làm mục tiêu trong lượt của mình. ② Nhân vật có phạm vi tấn công bao gồm bạn không thể sử dụng lá bài có nhãn sát thương chỉ định bạn làm mục tiêu. ③ Giai đoạn kết thúc, bạn rút bài trên tay đến X lá (X là số người còn sống trên sân, tối đa là 8).",
	spxizhan: "Hi Chiến",
	spxizhan_info: "Khi bắt đầu lượt của nhân vật khác, bạn phải chọn một: ① Mất 1 điểm thể lực. ② Bỏ một lá bài và khiến 〖Phương Tung〗 mất hiệu lực trong lượt này, sau đó nếu hoa sắc của lá bài này là: ♠, người đó coi như sử dụng một lá 【Tửu】; ♥, bạn coi như sử dụng một lá 【Vô Trung Sinh Hữu】; ♣, bạn coi như sử dụng 【Thiết Tỏa Liên Hoàn】 đối với người đó; ♦: bạn coi như sử dụng Hỏa 【Sát】 đối với người đó (không giới hạn khoảng cách).",
	sp_cuiyan: "Thủ Sát Thôi Diễm",
	spyajun: "Nhã Tuấn",
	spyajun_info: "① Giai đoạn rút bài, bạn khiến số bài rút định mức +1. ② Khi bắt đầu giai đoạn ra bài, bạn có thể dùng một lá bài nhận được trong lượt này để đấu điểm với nhân vật khác. Nếu bạn thắng, thì bạn có thể đặt một trong số các lá bài đấu điểm lên trên cùng chồng bài. Nếu bạn không thắng, giới hạn bài trên tay của lượt này của bạn -1.",
	spzundi: "Tôn Đích",
	spzundi_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể bỏ một lá bài trên tay và chọn một nhân vật, sau đó bạn tiến hành phán xét. Nếu kết quả là: Màu đen, người đó rút ba lá bài; Màu đỏ, người đó có thể di chuyển một lá bài trên sân.",
	sp_zhangchangpu: "Thủ Sát Trương Xương Bồ",
	spdifei: "Đê Phỉ",
	spdifei_info: "Kỹ năng tỏa định. Mỗi lượt giới hạn một lần, sau khi bạn chịu sát thương, bạn rút một lá bài hoặc bỏ một lá bài trên tay, sau đó hiển thị tất cả bài trên tay. Nếu nguồn của sát thương này là lá bài không có hoa sắc hoặc trong bài trên tay của bạn không có lá bài nào cùng hoa sắc với lá bài này, thì bạn hồi 1 điểm thể lực.",
	spyanjiao: "Nghiêm Giáo",
	spyanjiao_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể đưa tất cả bài của một loại hoa sắc trong bài trên tay cho một nhân vật khác, gây cho người đó 1 điểm sát thương. Sau đó bạn rút số bài tương đương khi bắt đầu lượt tiếp theo của mình.",
	sp_jiangwan: "Thủ Sát Tưởng Uyển",
	sp_jiangwan_prefix: "Thủ Sát",
	spzhenting: "Trấn Đình",
	spzhenting_info: `Mỗi lượt giới hạn một lần. Khi bạn hoặc nhân vật trong phạm vi tấn công của bạn trở thành mục tiêu của 【Sát】 hoặc cẩm nang duy trì, nếu bạn không phải người sử dụng lá bài này, bạn có thể chọn một: ① Bỏ một lá bài trên tay của người sử dụng; ② Rút một lá bài; ③ ${get.poptip("rule_beishui")}: Thay thế người đó trở thành mục tiêu của lá bài này.`,
	spjincui: "Tận Tụy",
	spjincui_info: "Kỹ năng giới hạn. Giai đoạn ra bài, bạn có thể hoán đổi vị trí với một nhân vật khác, sau đó mất X điểm thể lực (X là trị số thể lực của bạn - số lần bạn đã phát động 〖Trấn Đình〗); nếu bạn không mất thể lực theo cách này, bạn tăng 1 điểm giới hạn thể lực và mất lựa chọn bối thủy của 〖Trấn Đình〗.",
	sp_jiangqing: "Tưởng Khâm",
	spjianyi: "Kiệm Y",
	spjianyi_info: "Kỹ năng tỏa định. Khi lượt của nhân vật khác kết thúc, nếu trong đống bài bỏ có bài phòng cụ đi vào đống bài bỏ do bị bỏ đi trong lượt này, thì bạn nhận lấy một lá trong đó.",
	spshangyi: "Thượng Nghĩa",
	spshangyi_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể bỏ một lá bài và chọn một nhân vật khác. Người đó xem bài trên tay của bạn, sau đó bạn xem bài trên tay của người đó và nhận lấy một lá trong đó.",
	sp_lvfan: "Thủ Sát Lã Phạm",
	sp_lvfan_prefix: "Thủ Sát",
	spdiaodu: "Điều Độ",
	spdiaodu_info: "Giai đoạn chuẩn bị, bạn có thể khiến một nhân vật rút một lá bài, sau đó di chuyển một lá bài trong khu trang bị của người đó.",
	spdiancai: "Điển Tài",
	spdiancai_info: "Khi bắt đầu giai đoạn kết thúc của nhân vật khác, bạn có thể khiến tối đa X nhân vật mỗi người rút một lá bài (X là số bài trên tay bạn đã mất trong lượt này).",
	mbdiaodu: "Điều Độ",
	mbdiaodu_info: "Giai đoạn chuẩn bị, bạn có thể di chuyển một lá bài trong khu trang bị của một nhân vật (không thể di chuyển cho chính mình), sau đó người đó rút một lá bài.",
	mbdiancai: "Điển Tài",
	mbdiancai_info: "Sau khi giai đoạn ra bài của nhân vật khác kết thúc, nếu số bài bạn mất trong giai đoạn này không nhỏ hơn trị số thể lực của bạn, thì bạn có thể bổ sung số bài trên tay đến giới hạn thể lực.",
	spyanji: "Nghiêm Kỷ",
	spyanji_info: `Khi bắt đầu giai đoạn ra bài, bạn có thể tiến hành “${get.poptip("rule_zhengsu")}”.`,
	sp_huangfusong: "Thủ Sát Hoàng Phủ Tung",
	spzhengjun: "Chỉnh Quân",
	spzhengjun_info: `Khi bắt đầu giai đoạn ra bài, bạn có thể tiến hành “${get.poptip("rule_zhengsu")}”. Sau khi bạn nhận được phần thưởng chỉnh túc vì vậy, bạn có thể khiến một nhân vật khác nhận phần thưởng chỉnh túc.`,
	spshiji: "Thế Kích",
	spshiji_info: "Khi bạn gây sát thương thuộc tính cho nhân vật khác, nếu số bài trên tay của bạn không phải là nhiều nhất duy nhất trên sân, thì bạn có thể xem bài trên tay của người đó. Bạn khiến người đó bỏ tất cả bài đỏ trong đó, sau đó rút số bài tương đương.",
	sptaoluan: "Thảo Loạn",
	sptaoluan_info: "Mỗi lượt giới hạn một lần. Khi kết quả phán xét của một nhân vật được xác định, nếu hoa sắc của kết quả là ♠, thì bạn có thể chấm dứt sự kiện cấp trên dẫn đến phán xét này. Sau đó chọn một: ① Nhận lá bài thực thể tương ứng với lá bài phán xét. ② Coi như sử dụng một lá Hỏa 【Sát】 đối với nhân vật phán xét (không giới hạn khoảng cách và số lần).",
	sp_zhujun: "Thủ Sát Chu Tuấn",
	yangjie: "Dương Giải",
	yangjie_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể rút một lá bài và đấu điểm với một nhân vật A khác. Khi bạn hiển thị lá bài đấu điểm của mình theo cách này, bạn khiến điểm số của lá bài này -X (X là trị số thể lực bạn đã mất). Nếu bạn không thắng, thì bạn có thể khiến một nhân vật B khác nhận được hai lá bài đấu điểm, sau đó người đó coi như sử dụng một lá Hỏa 【Sát】 đối với A.",
	zjjuxiang: "Cự Giáng",
	zjjuxiang_info: "Kỹ năng giới hạn. Khi một nhân vật khác thoát khỏi trạng thái hấp hối, bạn có thể gây cho người đó 1 điểm sát thương, sau đó rút X lá bài (X là giới hạn thể lực của người đó và tối đa là 5).",
	xinyangjie: "Dương Giải",
	xinyangjie_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể đấu điểm với một nhân vật A khác. Nếu bạn không thắng, thì bạn có thể khiến một nhân vật B khác coi như sử dụng một lá Hỏa 【Sát】 đối với A.",
	xinjuxiang: "Cự Giáng",
	xinjuxiang_info: "Kỹ năng giới hạn, khi một nhân vật khác thoát khỏi trạng thái hấp hối, bạn có thể gây cho người đó 1 điểm sát thương.",
	houfeng: "Hậu Phổng",
	houfeng_info: `Mỗi vòng giới hạn một lần. Khi bắt đầu giai đoạn ra bài của một nhân vật khác, nếu người đó nằm trong phạm vi tấn công của bạn, thì bạn có thể khiến người đó tiến hành “${get.poptip("rule_zhengsu")}”. Sau khi người đó nhận được phần thưởng chỉnh túc vì vậy, bạn nhận được phần thưởng chỉnh túc tương tự.`,
	liuba: "Thủ Sát Lưu Ba",
	duanbi: "Đoán Tệ",
	duanbi_info: "Kỹ năng giới hạn. Giai đoạn ra bài, nếu tổng số bài trên tay của tất cả nhân vật trên sân lớn hơn hai lần tổng số nhân vật, thì bạn có thể khiến tất cả nhân vật khác mỗi người bỏ X lá bài trên tay (X là một nửa số bài trên tay của nhân vật đó và làm tròn xuống và tối đa là 3). Sau đó bạn có thể chọn một nhân vật, khiến người đó ngẫu nhiên nhận được ba lá bài bị bỏ theo cách này.",
	tongduo: "Thống Độ",
	tongduo_info: "Mỗi lượt giới hạn một lần. Sau khi bạn trở thành mục tiêu duy nhất của lá bài do nhân vật khác sử dụng, bạn có thể khiến một nhân vật trọng chú một lá bài.",
	shen_huatuo: "Thủ Sát Thần Hoa Đà",
	shen_huatuo_prefix: "Thủ Sát Thần",
	wuling: "Ngũ Linh",
	wuling_info: `① Giai đoạn ra bài giới hạn hai lần. Bạn có thể chọn một nhân vật chưa có “${get.poptip({
		id: "wl_wuqinxi",
		name: "Ngũ Cầm Hí",
		type: "character",
		info: `“Ngũ Cầm Hí” chia thành năm hiệu ứng khác nhau: “Hổ, Lộc, Hùng, Viên, Hạc”:<span style='font-family: yuanli'>
				<br><li>Hổ: Khi bạn sử dụng lá bài chỉ định mục tiêu duy nhất gây sát thương cho nhân vật mục tiêu, sát thương này +1.
				<br><li>Lộc: ① Khi bạn nhận được hiệu ứng này, bạn hồi 1 điểm thể lực và bỏ tất cả bài trong khu phán xét. ② Bạn không thể trở thành mục tiêu của cẩm nang duy trì.
				<br><li>Hùng: Mỗi lượt giới hạn một lần, khi bạn chịu sát thương, sát thương này -1.
				<br><li>Viên: Khi bạn nhận được hiệu ứng này, bạn chọn một nhân vật khác, nhận một lá bài trong khu trang bị của người đó.
				<br><li>Hạc: Khi bạn nhận được hiệu ứng này, bạn rút ba lá bài.
			</span>`,
	})}”, truyền dạy “${get.poptip("wl_wuqinxi")}” cho người đó theo thứ tự bạn chọn, và người đó nhận hiệu ứng sau: Người đó nhận được hiệu ứng “${get.poptip("wl_wuqinxi")}” đầu tiên bạn chọn, và tại mỗi giai đoạn chuẩn bị của người đó sẽ dời đi hiệu ứng “${get.poptip("wl_wuqinxi")}” hiện tại và chuyển sang loại tiếp theo. ② Khi bạn chết, bạn khiến các nhân vật trên sân mất đi “${get.poptip("wl_wuqinxi")}” mà bạn đã truyền dạy.`,
	wuling_wuqinxi: "Ngũ Cầm Hí",
	get wuling_wuqinxi_info() {
		return lib.poptip.getInfo("wl_wuqinxi");
	},
	youyi: "Du Y",
	youyi_info: "① Khi kết thúc giai đoạn bỏ bài, bạn có thể đặt tất cả các lá bài bị bỏ trong giai đoạn này vào khu Nhân. ② Giai đoạn ra bài giới hạn một lần. Bạn có thể đặt tất cả các lá bài trong khu Nhân vào đống bài bỏ, khiến tất cả nhân vật mỗi người hồi 1 điểm thể lực.",
	wuqinxi_hu: "Hổ",
	wuqinxi_hu_bg: "Hổ",
	wuqinxi_hu_info: "Khi bạn sử dụng lá bài chỉ định mục tiêu duy nhất gây sát thương cho nhân vật mục tiêu, sát thương này +1.",
	wuqinxi_lu: "Lộc",
	wuqinxi_lu_bg: "Lộc",
	wuqinxi_lu_info: "① Khi bạn nhận được hiệu ứng này, bạn hồi 1 điểm thể lực và bỏ tất cả bài trong khu phán xét. ② Bạn không thể trở thành mục tiêu của cẩm nang duy trì.",
	wuqinxi_xiong: "Hùng",
	wuqinxi_xiong_bg: "Hùng",
	wuqinxi_xiong_info: "Mỗi lượt giới hạn một lần, khi bạn chịu sát thương, sát thương này -1.",
	wuqinxi_yuan: "Viên",
	wuqinxi_yuan_bg: "Viên",
	wuqinxi_yuan_info: "Khi bạn nhận được hiệu ứng này, bạn chọn một nhân vật khác, nhận một lá bài trong khu trang bị của người đó.",
	wuqinxi_he: "Hạc",
	wuqinxi_he_bg: "Hạc",
	wuqinxi_he_info: "Khi bạn nhận được hiệu ứng này, bạn rút ba lá bài.",
	shen_lusu: "Thần Lỗ Túc",
	shen_lusu_prefix: "Thần",
	dingzhou: "Định Châu",
	dingzhou_info: "Giai đoạn ra bài giới hạn một lần. Bạn có thể đưa X lá bài cho một nhân vật có bài trên sân, sau đó bạn nhận tất cả các lá bài trên sân của người đó (X là số bài trên sân của người đó).",
	tamo: "Táp Mô",
	tamo_info: "Khi trò chơi bắt đầu, bạn có thể phân bổ lại vị trí chỗ ngồi của tất cả nhân vật ngoại trừ chủ công.",
	tamo_info_doudizhu: "Khi trò chơi bắt đầu, bạn có thể phân bổ lại vị trí chỗ ngồi của tất cả nhân vật.",
	tamo_faq: "FAQ",
	tamo_faq_info: "<br><li>Q: Trong trường hợp vị trí số 1 không phải chủ công, 〖Táp Mô〗 kết toán thế nào?</li><li>A: Nhân vật đó có thể tiến hành trao đổi vị trí bình thường. Nếu do ảnh hưởng của kỹ năng này dẫn đến nhân vật vị trí số 1 thay đổi, thì lấy nhân vật vị trí số 1 sau khi sắp xếp làm nhân vật khởi đầu để bắt đầu ván game này.</li>",
	zhimeng: "Trí Minh",
	zhimeng_info: "Sau khi lượt kết thúc, bạn có thể chọn một nhân vật khác. Nếu làm vậy, bạn và người đó sẽ đặt tất cả bài trên tay của mỗi người vào khu xử lý, sau đó bạn ngẫu nhiên nhận lấy một nửa trong số bài đó (làm tròn lên), người đó nhận số bài còn lại.",
	mb_shen_jiangwei: "Thủ Sát Thần Khương Duy",
	mb_shen_jiangwei_prefix: "Thủ Sát|Thần",
	mbtiantao: "Thiên Đào",
	mbtiantao_info: "Kỹ năng tỏa định, giai đoạn kết thúc, bạn chọn một khu vực và bỏ tất cả bài trong đó, sau đó lần lượt bỏ một lá bài ở cùng khu vực đó của bất kỳ số nhân vật khác, nhân vật vì vậy bị bỏ bài mà không bị bỏ lá 【Sát】 sẽ mất 1 điểm thể lực.",
	mbxinghun: "Tinh Hồn",
	mbxinghun_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể xem năm lá bài trên cùng của chồng bài, dùng bất kỳ số lượng bài trên tay để trao đổi với số bài tương đương trong đó và sắp xếp tùy ý, sau đó bạn khiến một nhân vật khác hiển thị bài trên tay của bạn và năm lá bài trên cùng của chồng bài, bạn lần lượt sử dụng các lá 【Sát】 trong đó đối với người đó.",
	mbshenpei: "Thần Bái",
	mbshenpei_info: `Kỹ năng giới hạn, khi bạn rơi vào trạng thái hấp hối, bạn có thể hồi phục X điểm thể lực (X là số lần bạn đã rơi vào trạng thái hấp hối trong ván game này), sau đó gây cho một nhân vật trị số sát thương lôi điện tương đương và nhận ${get.poptip("mbhuitian")}.`,
	mbhuitian: "Hồi Thiên",
	mbhuitian_info: "Khi lượt của một nhân vật kết thúc, nếu trị số thể lực của người đó lớn hơn bạn, bạn có thể rút một lá bài và thực hiện một lượt bổ sung. Khi mỗi vòng bắt đầu, nếu bạn đã phát động kỹ năng này, bạn chết.",
	shen_guojia: "Thần Quách Gia",
	shen_guojia_prefix: "Thần",
	shuishi: "Tuệ Thức",
	shuishi_info: "Giai đoạn ra bài giới hạn một lần, nếu giới hạn thể lực của bạn nhỏ hơn 10, thì bạn có thể chọn một nhân vật. Bạn khiến người đó rút một lá bài, nếu lá bài người đó nhận được theo cách này: Có hoa sắc không giống với bất kỳ lá bài nào khác trên tay của nhân vật đó, thì bạn tăng 1 điểm giới hạn thể lực, nếu giới hạn thể lực của bạn nhỏ hơn 10, thì bạn có thể lặp lại quy trình này; nếu không bạn giảm 1 điểm giới hạn thể lực, và người đó hiển thị tất cả bài trên tay.",
	stianyi: "Thiên Dực",
	stianyi_info: `Kỹ năng thức tỉnh, giai đoạn chuẩn bị, nếu tất cả nhân vật còn sống trên sân đều đã từng chịu sát thương trong ván game này, thì bạn tăng 2 điểm giới hạn thể lực và hồi 1 điểm thể lực, sau đó khiến một nhân vật nhận kỹ năng ${get.poptip("zuoxing")}.`,
	zuoxing: "Tá Hạnh",
	zuoxing2: "Tá Hạnh",
	zuoxing_info: "Giai đoạn ra bài giới hạn một lần, nếu nhân vật khiến bạn nhận được 〖Tá Hạnh〗 còn sống và giới hạn thể lực lớn hơn 1, thì bạn có thể khiến người đó giảm 1 điểm giới hạn thể lực, và coi như sử dụng một lá bài cẩm nang thông thường.",
	sghuishi: "Huy Phệ",
	sghuishi_info: "Kỹ năng giới hạn, giai đoạn ra bài, bạn có thể chọn một nhân vật khác: Nếu người đó có kỹ năng thức tỉnh chưa phát động, thì bạn khiến người đó khi phát động những kỹ năng thức tỉnh này bỏ qua điều kiện ban đầu; nếu không người đó rút bốn lá bài. Sau đó bạn giảm 2 điểm giới hạn thể lực.",
	shen_taishici: "Thần Thái Sử Từ",
	shen_taishici_prefix: "Thần",
	dulie: "Đốc Liệt",
	dulie_info: "Kỹ năng tỏa định. Khi bạn trở thành mục tiêu của 【Sát】, nếu trị số thể lực của người sử dụng lớn hơn bạn, thì bạn tiến hành phán xét. Nếu kết quả là Hồng đào, thì hủy bỏ mục tiêu này.",
	tspowei: "Phá Vi",
	tspowei_info: `Kỹ năng sứ mệnh. ① Khi trò chơi bắt đầu, bạn khiến tất cả các nhân vật khác nhận một “Vi”. ② Sau khi một nhân vật chịu sát thương, nếu người đó có “Vi”, thì người đó dời đi “Vi”. ③ Khi bắt đầu lượt, bạn chọn tất cả nhân vật có “Vi”. Những nhân vật này mất “Vi”, sau đó nhân vật đầu tiên không phải bạn nằm dưới nhà của những nhân vật này nhận số lượng “Vi” tương đương. ④ Khi bắt đầu lượt của một nhân vật khác, nếu người đó có “Vi”, thì bạn có thể chọn một: ⒈ Bỏ một lá bài trên tay và gây cho người đó 1 điểm sát thương. ⒉ Nếu trị số thể lực của người đó không lớn hơn bạn, thì bạn nhận một lá bài trên tay của người đó. Sau khi chọn xong, bạn được coi là nằm trong phạm vi tấn công của người đó cho đến khi kết thúc lượt. ⑤ Sứ mệnh: Khi bắt đầu lượt, nếu trên sân không có “Vi”, thì bạn nhận kỹ năng ${get.poptip("shenzhu")}. ⑥ Thất bại: Khi bạn rơi vào trạng thái hấp hối, bạn hồi phục trị số thể lực về 1 điểm, sau đó bỏ tất cả bài trong khu trang bị.`,
	shenzhu: "Thần Trước",
	shenzhu_info: "Kỹ năng tỏa định, sau khi bạn sử dụng lá 【Sát】 không chuyển hóa có lá bài thực thể tương ứng kết thúc kết toán, bạn chọn một: ① Rút một lá bài, và giới hạn số lần sử dụng 【Sát】 trong lượt này +1. ② Rút ba lá bài, và lượt này không thể sử dụng thêm 【Sát】.",
	dangmo: "Đãng Ma",
	dangmo_info: "Sau khi bạn sử dụng lá 【Sát】 đầu tiên trong giai đoạn ra bài chọn mục tiêu, bạn có thể thêm tối đa Y-1 mục tiêu cho lá bài này (Y là trị số thể lực của bạn).",
	reshuishi: "Tuệ Thức",
	reshuishi_info: "Giai đoạn ra bài giới hạn một lần. Nếu giới hạn thể lực của bạn nhỏ hơn 10, bạn có thể tiến hành phán xét mà lá bài phán xét không đặt vào đống bài bỏ. Nếu kết quả phán xét có hoa sắc không giống với bất kỳ kết quả phán xét nào khác của lần phát động kỹ năng này và giới hạn thể lực của bạn nhỏ hơn 10, thì bạn tăng 1 điểm giới hạn thể lực, và có thể lặp lại quy trình này. Sau đó bạn đưa tất cả các lá bài phán xét nằm trong khu xử lý cho một nhân vật. Nếu số bài trên tay của người đó là nhiều nhất trên sân, thì bạn giảm 1 điểm giới hạn thể lực.",
	resghuishi: "Huy Phệ",
	resghuishi_info: "Kỹ năng giới hạn, giai đoạn ra bài, bạn có thể chọn một nhân vật. Nếu giới hạn thể lực của bạn không nhỏ hơn số người còn sống và người đó có kỹ năng thức tỉnh chưa phát động, thì bạn khiến một trong các kỹ năng đó bỏ qua điều kiện phát động; nếu không người đó rút bốn lá bài. Sau đó bạn giảm 2 điểm giới hạn thể lực.",
	qizhengxiangsheng: "Kỳ Chính Tương Sinh",
	qizhengxiangsheng_info: "Giai đoạn ra bài, sử dụng lên một nhân vật khác. Bạn đánh dấu nhân vật mục tiêu là “Kỳ binh” hoặc “Chính binh” (nhân vật khác không thể thấy). Sau đó nhân vật mục tiêu có thể đánh ra một lá 【Sát】 hoặc 【Thiểm】. Nếu là “Kỳ binh” và không đánh ra 【Sát】, thì bạn gây cho người đó 1 điểm sát thương; nếu là “Chính binh” và không đánh ra 【Thiểm】, thì bạn nhận một lá bài của người đó.",
	shen_xunyu: "Thần Tuân Úc",
	shen_xunyu_prefix: "Thần",
	tianzuo: "Thiên Tá",
	tianzuo_info: `Kỹ năng tỏa định. ① Khi trò chơi bắt đầu, bạn thêm tám lá ${get.poptip("qizhengxiangsheng")} vào chồng bài. ② ${get.poptip("qizhengxiangsheng")} vô hiệu đối với bạn.`,
	lingce: "Linh Sách",
	lingce_info: `Kỹ năng tỏa định. Khi có ${get.poptip("qizhengxiangsheng")} hoặc Trí Nang hoặc lá bài cẩm nang đã được ghi nhớ bởi 〖Định Hán ①〗 được sử dụng, nếu lá bài này không phải bài chuyển hóa và số lượng bài thực thể tương ứng là 1, thì bạn rút một lá bài.`,
	dinghan: "Định Hán",
	dinghan_info: "① Khi bạn trở thành mục tiêu của lá bài cẩm nang thông thường chưa được ghi nhớ, hoặc có lá bài cẩm nang duy trì chưa được ghi nhớ đi vào khu phán xét của bạn, bạn ghi nhớ tên lá bài này và hủy bỏ nó. ② Giai đoạn chuẩn bị, bạn có thể thêm hoặc bớt một tên lá bài cẩm nang trong ghi nhớ của 〖Định Hán ①〗.",
	shen_sunce: "Thần Tôn Sách",
	shen_sunce_prefix: "Thần",
	yingba: "Anh Bá",
	yingba_info: "① Giai đoạn ra bài giới hạn một lần, bạn có thể khiến một nhân vật khác có giới hạn thể lực lớn hơn 1 giảm 1 điểm giới hạn thể lực và nhận dấu ấn “Bình định”, sau đó bạn giảm 1 điểm giới hạn thể lực. ② Bạn sử dụng bài đối với nhân vật có dấu ấn “Bình định” không bị giới hạn khoảng cách.",
	scfuhai: "Phúc Hải",
	scfuhai_info: "Kỹ năng tỏa định. ① Khi bạn sử dụng bài chỉ định mục tiêu, nếu nhân vật mục tiêu có dấu ấn “Bình định”, thì người đó không thể đáp trả lá bài này. Nếu số bài bạn nhận được theo cách này trong lượt này nhỏ hơn 2, thì bạn rút một lá bài. ② Khi nhân vật có dấu ấn “Bình định” chết, bạn tăng X điểm giới hạn thể lực và rút X lá bài. (X là số lượng dấu ấn “Bình định” mà người đó sở hữu).",
	pinghe: "Phùng Hà",
	pinghe_info: "Kỹ năng tỏa định. ① Cơ số giới hạn bài trên tay của bạn bằng trị số thể lực bạn đã mất. ② Khi bạn chịu sát thương từ nhân vật khác gây ra, nếu bạn có bài và giới hạn thể lực của bạn lớn hơn 1, thì bạn ngăn chặn sát thương này, giảm 1 điểm giới hạn thể lực và đưa một lá bài trên tay cho một nhân vật khác. Sau đó nếu bạn sở hữu 〖Anh Bá〗, thì nguồn sát thương nhận một dấu ấn “Bình định”.",
};

export default translates;
