import { lib, game, ui, get, ai, _status } from "noname";

const translates = {
	ol_xiahoushi: "OL Giới Hạ Hầu Thị",
	ol_xiahoushi_prefix: "OL Giới",
	olqiaoshi: "Tiều Thập",
	olqiaoshi_info: "Mỗi giai đoạn kết thúc, bạn có thể cùng nhân vật có lượt hiện tại mỗi người rút 1 lá bài. Sau đó nếu số bài trên tay của người đó và bạn không bằng nhau, kỹ năng này vô hiệu trong vòng này.",
	olyanyu: "Yến Ngữ",
	olyanyu_info: "Giai đoạn ra bài, bạn có thể trọng chú [Sát]. Khi kết thúc giai đoạn ra bài, nếu bạn đã mất ít nhất 2 lá [Sát] trong giai đoạn này, bạn có thể khiến một nhân vật nam rút 2 lá bài.",
	ol_zhangliao: "OL Thần Trương Liêu",
	ol_zhangliao_prefix: "OL Thần",
	olduorui: "Đoạt Nhuệ",
	olduorui_info: "Sau khi bạn gây sát thương cho một nhân vật trong giai đoạn ra bài, bạn có thể chọn một kỹ năng trên thẻ võ tướng của nhân vật đó. Nếu làm vậy, bạn kết thúc giai đoạn ra bài, và khiến kỹ năng này vô hiệu cho đến khi kết thúc lượt tiếp theo của nhân vật đó.",
	olzhiti: "Chỉ Đề",
	olzhiti_info: "Kỹ năng khóa, giới hạn bài trên tay của những nhân vật đã bị thương trong tầm tấn công của bạn -1. Nếu số nhân vật đã bị thương trên sân: không ít hơn 1, giới hạn bài trên tay của bạn +1; không ít hơn 3, khi bắt đầu giai đoạn rút bài, số bài rút định mức +1; không ít hơn 5, khi kết thúc lượt, bạn phế bỏ một ô trang bị ngẫu nhiên của một nhân vật.",
	shen_caopi: "Thần Tào Phi",
	shen_caopi_prefix: "Thần",
	chuyuan: "Trữ Nguyên",
	chuyuan_info: "Sau khi một nhân vật chịu sát thương, nếu số lượng 'Trữ' trên thẻ võ tướng của bạn nhỏ hơn giới hạn thể lực, bạn có thể khiến nhân vật đó rút 1 lá bài. Sau đó nhân vật đó đặt một lá bài trên tay lên thẻ võ tướng của bạn, gọi là 'Trữ'.",
	dengji: "Đăng Cực",
	dengji_info: `Kỹ năng thức tỉnh, giai đoạn chuẩn bị, nếu số lượng 'Trữ' trên thẻ võ tướng không ít hơn 3, bạn giảm 1 giới hạn thể lực và nhận tất cả 'Trữ', sau đó nhận kỹ năng ${get.poptip("tianxing")} và ${get.poptip("new_rejianxiong")}.`,
	tianxing: "Thiên Hành",
	tianxing_info: `Kỹ năng thức tỉnh, giai đoạn chuẩn bị, nếu số lượng 'Trữ' trên thẻ võ tướng không ít hơn 3, bạn giảm 1 giới hạn thể lực và nhận tất cả 'Trữ', sau đó mất kỹ năng 〖Trữ Nguyên〗, chọn nhận một trong các kỹ năng sau: ${get.poptip("rerende")}/${get.poptip("rezhiheng")}/${get.poptip("olluanji")}/${get.poptip("caopi_xingdong")}.`,
	shen_zhenji: "Thần Chân Mật",
	shen_zhenji_prefix: "Thần",
	shenfu: "Thần Phú",
	shenfu_info: "Kết thúc lượt, nếu số bài trên tay là: Số lẻ, bạn có thể gây cho một nhân vật khác 1 điểm sát thương hệ Lôi. Nếu người đó vì vậy rơi vào trạng thái hấp hối, bạn có thể lặp lại quy trình này (không thể chọn nhân vật đã chọn trong lần này). Số chẵn, bạn có thể chọn một nhân vật, khiến người đó rút 1 lá hoặc bỏ 1 lá trên tay. Nếu số bài trên tay của người đó bằng số thể lực, bạn có thể lặp lại quy trình này (không thể chọn nhân vật đã chọn trong lần này).",
	qixian: "Thất Huyền",
	qixian_info: "Kỹ năng khóa, giới hạn bài trên tay của bạn được xem là 7.",
	caopi_xingdong: "Hành Động",
	caopi_xingdong_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể đưa một lá [Sát] hoặc Cẩm nang thường cho một nhân vật khác, sau đó nhân vật đó chọn một: Sử dụng lá bài này lên mục tiêu khác ngoài bạn, sau khi kết thúc kết toán lá bài này, bạn và người đó mỗi người rút 1 lá; Hoặc bỏ qua giai đoạn phán xét và giai đoạn rút bài của lượt sau.",
	shen_dianwei: "Thần Điển Vi",
	shen_dianwei_prefix: "Thần",
	juanjia: "Quyên Giáp",
	juanjia_info: "Kỹ năng khóa. Khi bắt đầu trò chơi, bạn phế bỏ một ô giáp, sau đó nhận thêm một ô vũ khí.",
	qiexie: "Khiết Hiệp",
	qiexie_info: `Kỹ năng khóa. Giai đoạn chuẩn bị, bạn xem ngẫu nhiên 5 lá bài trong chồng bài võ tướng còn lại, chọn số lượng lá bất kỳ, chuyển hóa chúng thành ${get.poptip({
		id: "qiexie_equip1",
		name: "Vũ khí",
		type: "character",
		info: "1. Lá bài này không có hoa sắc và điểm số, tầm tấn công bằng giới hạn thể lực của võ tướng này.<br>2. Kỹ năng của vũ khí này là tất cả các kỹ năng trên thẻ võ tướng có mô tả chứa '[Sát]' và không có nhãn khác ngoài Kỹ năng khóa.<br>3. Khi vũ khí này rời khỏi khu trang bị, nó được đưa trở lại chồng bài võ tướng.",
	})} và đặt vào ô vũ khí của bạn.`,
	cuijue: "Tồi Quyết",
	cuijue_info: "Mỗi lượt mỗi nhân vật giới hạn một lần. Giai đoạn ra bài, bạn có thể bỏ 1 lá bài, sau đó gây 1 điểm sát thương cho nhân vật khác có khoảng cách xa nhất trong tầm tấn công (nếu không có thì không chọn).",
	shen_sunquan: "Thần Tôn Quyền",
	shen_sunquan_prefix: "Thần",
	junk_zhangjiao: "OL Thần Trương Giác",
	junk_zhangjiao_prefix: "OL Thần",
	ol_zhangsong: "OL Giới Trương Tùng",
	ol_zhangsong_prefix: "OL Giới",
	olqiangzhi: "Cường Thức",
	olqiangzhi_info: "Bắt đầu giai đoạn ra bài, bạn có thể xem và ngửa 1 lá trên tay của nhân vật khác, sau đó trong giai đoạn này, sau khi bạn sử dụng lá bài cùng loại đó, bạn có thể rút 1 lá.",
	olxiantu: "Hiến Đồ",
	olxiantu_info: "Khi bắt đầu giai đoạn ra bài của nhân vật khác, bạn có thể rút tối đa 2 lá rồi đưa cho người đó số bài tương đương. Khi giai đoạn này kết thúc, nếu sát thương người đó gây ra nhỏ hơn số bài bạn đã đưa, bạn mất 1 điểm thể lực.",
	ol_jsrg_zhanghe: "Thiểm Trương Cáp",
	ol_jsrg_zhanghe_prefix: "Thiểm",
	olqiongtu: "Cùng Đồ",
	olqiongtu_info: "Kỹ năng phe Quần, mỗi lượt giới hạn một lần, bạn có thể xem như sử dụng một lá [Vô giải khả kích] và rút 1 lá bài, sau đó bạn phải đặt một lá bài phi cơ bản lên thẻ võ tướng. Nếu bạn không đặt bài theo cách này, bạn lấy tất cả bài trên thẻ võ tướng và đổi phe sang Ngụy.",
	olxianzhu: "Tiên Trước",
	olxianzhu_info: "Kỹ năng phe Ngụy, giai đoạn ra bài mỗi loại giới hạn một lần, bạn có thể bỏ 1 lá Cẩm nang hoặc Trang bị, xem như sử dụng một lá [Sát] không giới hạn số lần. Nếu lá [Sát] này gây sát thương, bạn có thể sử dụng lá bài đã bỏ lần này.",
	ol_caojie: "OL Giới Tào Tiết",
	ol_caojie_prefix: "OL Giới",
	olshouxi: "Thủ Tỉ",
	olshouxi_info: "Mỗi lượt giới hạn một lần, khi bạn trở thành mục tiêu của [Sát], bạn có thể bỏ ít nhất một lá [Sát], gây cho người sử dụng 1 điểm sát thương. Sau đó nếu lá [Sát] này không gây sát thương cho bạn, bạn rút bài cho đến giới hạn (tối đa rút đến 5).",
	olhuimin: "Huệ Dân",
	olhuimin_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể khiến bất kỳ nhân vật nào có số bài trên tay nhỏ hơn hoặc bằng số thể lực được rút 1 lá bài, sau đó giới hạn bài tay của bạn +X cho đến khi bắt đầu lượt tiếp theo của bạn (X là số nhân vật có bài trên tay nhiều hơn thể lực trong số đó).",
	ol_re_xinxianying: "OL Giới Tân Hiến Anh",
	ol_re_xinxianying_prefix: "OL Giới",
	olcaishi: "Tài Thức",
	olcaishi_info: "Kỹ năng khóa, sau khi bạn sử dụng loại bài đầu tiên trong mỗi vòng, nếu giới hạn bài tay của bạn không phải lớn nhất toàn sân, bạn tăng 1 điểm giới hạn bài tay, nếu không bạn hồi 1 điểm thể lực và khiến kỹ năng này vô hiệu trong vòng này.",
	olzhongjian: "Trung Giám",
	olzhongjian_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể xem X lá trên tay của một nhân vật khác (X là số thể lực của người đó), sau đó bạn ngửa một lá trên tay của mình. Nếu bài của người đó chứa lá bài: cùng màu với lá bạn ngửa, bạn rút 1 lá; cùng tên với lá bạn ngửa, giai đoạn này kỹ năng đổi thành giới hạn hai lần.",
	ol_sb_chengyu: "OL Mưu Trình Dục",
	ol_sb_chengyu_prefix: "OL Mưu",
	olsbliduan: "Lệ Đoán",
	olsbliduan_info: "Sau khi bạn dùng [Sát], lá Cẩm nang tiếp theo bạn dùng có thể chỉ định thêm một mục tiêu; Sau khi bạn dùng Cẩm nang, lá [Sát] tiếp theo bạn dùng có thể chỉ định thêm một mục tiêu.",
	olsbdanchi: "Đảm Trì",
	olsbdanchi_info: "Mỗi lượt giới hạn một lần, sau khi bạn gây ra hoặc chịu sát thương, bạn có thể khiến nhân vật chịu sát thương chọn một loại bài. Sau đó nguồn sát thương sử dụng lá bài tiếp theo trong lượt này, bạn xem như sử dụng một lá [Vô trung sinh hữu], nếu khác loại với loại đã chọn ở 'Đảm Trì', bạn xem như sử dụng thêm một lá [Sát].",
	old_olsbdanchi: "Đảm Trì",
	old_olsbdanchi_info: "Sau lần đầu tiên bạn gây hoặc chịu sát thương do bài trong mỗi lượt, bạn có thể khiến mục tiêu của lá bài đó đồng thời dự đoán, lá bài tiếp theo nguồn sát thương dùng trong lượt này là [Sát] hay Cẩm nang. Khi kết thúc lượt, nếu có nhân vật đoán đúng, bạn rút 2 lá; nếu có nhân vật đoán sai, bạn xem như sử dụng một lá [Sát].",
	ol_sb_dongzhao: "OL Mưu Đổng Chiêu",
	ol_sb_dongzhao_prefix: "OL Mưu",
	olsbshunji: "Thuận Cơ",
	olsbshunji_info: "Mỗi vòng mỗi nhân vật giới hạn một lần, khi một nhân vật chịu sát thương, bạn có thể rút tối đa 2 lá, sau đó đưa cho người đó số bài tương đương. Nếu bạn vì vậy mất sạch một tên bài nào đó (mỗi tên bài giới hạn một lần), bạn gây cho người đó 1 điểm sát thương.",
	olsbyishi: "Di Thế",
	olsbyishi_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể giữ lại mỗi hoa sắc 1 lá bài trên tay và ngửa ra, bỏ các lá còn lại vào chồng bài bỏ, sau đó di chuyển một lá bài trên sân. Nếu bạn không mất bài tay vì việc này, cho đến khi bắt đầu lượt tiếp theo, bạn không mất bài cùng hoa sắc với lá bài đã di chuyển khi sử dụng, sau đó rút 1 lá.",
	ol_sb_xizhicai: "OL Mưu Hí Chí Tài",
	ol_sb_xizhicai_prefix: "OL Mưu",
	olsbxinchuan: "Tân Truyền",
	olsbxinchuan_info: "Sau khi lá Cẩm nang bạn dùng vào chồng bài bỏ, bạn có thể khiến một nhân vật thực hiện X lần rút 1 lá và X lần bỏ 1 lá (X là số loại hoa sắc còn thiếu trong chồng bài bỏ lượt này), sau đó nếu số bài tay của người đó bằng số thể lực, khiến nhân vật kế tiếp thực hiện quy trình còn lại.",
	olsbjinjin: "Kim Tẫn",
	olsbjinjin_info: "Khi bạn cần dùng Cẩm nang thường, có thể đem bất kỳ số lượng lá bài có hoa sắc khác nhau đã vào chồng bài bỏ lượt này ra khỏi trò chơi và mất 〖Kim Tẫn〗, xem như sử dụng nó; sau đó khi kết thúc lượt tiếp theo mà bạn có chịu sát thương, khiến một nhân vật nhận các lá bài đã ra khỏi trò chơi và 〖Kim Tẫn〗.",
	ol_jsrg_zhujun: "Thiểm Chu Tuấn",
	ol_jsrg_zhujun_prefix: "Thiểm",
	olfendi: "Phân Địch",
	olfendi_info: "Sau khi bạn dùng [Sát] chỉ định mục tiêu duy nhất, có thể ngửa tối đa X lá bài tay của người đó (X là giới hạn thể lực của bạn). Nếu làm vậy, cho đến khi kết thúc kết toán [Sát] này, người đó chỉ có thể dùng hoặc đánh ra các lá bài thực thể hoàn toàn nằm trong số đó, và sau khi [Sát] gây sát thương, bạn lấy các lá bài đó từ tay hoặc chồng bài bỏ của họ.",
	oljuxiang: "Cự Giáng",
	oljuxiang_info: "Mỗi lượt giới hạn một lần, sau khi bạn nhận bài ngoài giai đoạn rút bài, có thể bỏ các lá đó, khiến số lần dùng [Sát] của nhân vật có lượt hiện tại trong lượt này +X (X là số bài bạn đã bỏ theo cách này).",
	ol_jsrg_sunjian: "Thiểm Tôn Kiên",
	ol_jsrg_sunjian_prefix: "Thiểm",
	olpingtao: "Bình Thảo",
	olpingtao_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể khiến nhân vật khác chọn một: 1. Đưa cho bạn 1 lá bài, lá [Sát] tiếp theo bạn dùng trong lượt này có thể chỉ định thêm một mục tiêu; 2. Bạn xem như sử dụng một lá [Sát] có giới hạn số lần lên người đó.",
	oljuelie: "Tuyệt Liệt",
	oljuelie_info: "Sau khi bạn dùng [Sát] chỉ định mục tiêu đầu tiên, có thể bỏ tối đa X lá bài (X là số thể lực của bạn), sau đó khiến mục tiêu bỏ tổng cộng số bài tương đương; sau đó nếu bài tay hoặc thể lực của bạn là nhỏ nhất toàn sân, sát thương cơ bản của lá [Sát] này +1. Sau khi bạn dùng lá [Sát] này giết chết một nhân vật, rút bài đến giới hạn thể lực.",
	dm_sunquan: "Ma Tôn Quyền",
	dm_sunquan_prefix: "Ma",
	olquanyu: "Quyền Ngự",
	olquanyu_info: `Kỹ năng khóa, khi bắt đầu mỗi vòng, bạn khiến tất cả nhân vật đồng thời chọn một hiệu ứng "Quyền Ngự" mà họ chưa từng chọn trong ván này: ${get.poptip({
		id: "quanyu_effect",
		name: "Quyền Ngự",
		type: "character",
		info: "<li>Bạch Hồng: Sát thương +1<br><li>Thanh Minh: Chỉ định thêm một mục tiêu<br><li>Tích Tà: Bỏ qua giáp<br><li>Tử Điện: Không thể đáp trả<br><li>Bách Lý: Kết toán thêm một lần<br><li>Lưu Tinh: Không giới hạn số lần",
	})}, sau đó bạn rút X lá bài (X là số nhân vật chọn hiệu ứng giống bạn). Các lá [Sát] chỉ định mục tiêu duy nhất bạn dùng sẽ kèm theo hiệu ứng "Quyền Ngự" bạn đã chọn vòng này.`,
	oltianen: "Thiên Ân",
	oltianen_info: `Kỹ năng khóa, mỗi lượt mỗi loại giới hạn một lần, sau khi bạn dùng bài chỉ định mục tiêu duy nhất: Nếu vòng này hiệu ứng "Quyền Ngự" của bạn và người đó chọn khác nhau, bạn bỏ ngẫu nhiên 1 lá của họ, phát động một lần ${get.poptip("olquanyu")} lên họ; Nếu giống nhau, bạn nhận từ chồng bài 1 lá [Sát] không tính vào giới hạn bài tay.`,
	olqiangang: "Càn Cương",
	olqiangang_info: `Giai đoạn ra bài, bạn có thể ${get.poptip("rule_rumo")}, mất 〖Thiên Ân〗, sau đó trong ván này các lá [Sát] chỉ định mục tiêu duy nhất bạn dùng đều thực hiện tất cả các hiệu ứng "Quyền Ngự" mà mục tiêu đã từng chọn.`,
	ol_sb_guojia: "OL Mưu Quách Gia",
	ol_sb_guojia_prefix: "OL Mưu",
	olsbdinglun: "Định Luận",
	olsbdinglun_info: `Giai đoạn ra bài giới hạn một lần, bạn có thể chọn tối đa một nửa số nhân vật (làm tròn lên), nếu tổng số bài tay của họ lớn hơn tổng số bài tay của những người còn lại, những người này nhận 〖Xuất Tập〗 cho đến giai đoạn chuẩn bị tiếp theo của bạn và rút 1 lá bài.`,
	olsbquxi: "Xuất Tập",
	olsbquxi_info: "Giai đoạn ra bài mỗi loại giới hạn một lần, lá [Thiểm]/[Đào] của bạn có thể dùng như [Quá hà chiết kiều]/[Thuận thủ khiên dương].",
	olsbjieli: "Giải Ly",
	olsbjieli_info: "Mỗi vòng giới hạn một lần, khi bạn trở thành mục tiêu duy nhất của một lá bài, bạn có thể chọn một: 1. Bạn chọn lại mục tiêu cho lá bài này; 2. Xem tất cả bài tay của nhân vật khác, lấy các lá có cùng hoa sắc với lá bài này.",
	ol_re_yujin: "OL Giới Vu Cấm",
	ol_re_yujin_prefix: "OL|Giới",
	ol_zhenjun: "Trấn Quân",
	ol_zhenjun_info: "Giai đoạn chuẩn bị, bạn có thể bỏ X lá của một nhân vật (X là số bài tay trừ đi số thể lực của họ và ít nhất là 1), sau đó chọn một: 1. Bạn bỏ số bài tương đương với số lá không phải trang bị trong đó: 2. Giai đoạn kết thúc, người đó rút số bài tương đương với số lá không phải trang bị trong đó.",
	ol_yizhong: "Nghị Trọng",
	ol_yizhong_info: "Kỹ năng khóa, các lá [Sát] đen do nhân vật có số thể lực lớn hơn hoặc bằng bạn sử dụng lên bạn sẽ vô hiệu, nhân vật có số bài tay ít hơn hoặc bằng bạn không thể đáp trả [Sát] đen bạn sử dụng.",
	ol_sb_xuyou: "OL Mưu Hứa Duệ",
	ol_sb_xuyou_prefix: "OL Mưu",
	olsbqianfu: "Thiên Phụ",
	olsbqianfu_info: "Kỹ năng chuyển đổi, giai đoạn ra bài, Dương: Bạn có thể dùng 1 lá bài đen như [Quá hà chiết kiều]: Âm: Bạn có thể dùng 1 lá bài đỏ như [Hỏa công]. Sau kết toán, bạn có thể đặt lá bài đã bỏ vì việc này lên đầu chồng bài.",
	olsbyushi: "Ngự Thế",
	olsbyushi_info: `Sau khi bạn gây hoặc chịu sát thương, bạn có thể khiến một nhân vật: Có kỹ năng chuyển đổi thì chuyển trạng thái của một kỹ năng chuyển đổi: Không có kỹ năng chuyển đổi thì nhận được 〖Thiên Phụ〗 giới hạn mỗi loại một lần trong giai đoạn ra bài cho đến khi mất lá bài tay cuối cùng. X lần đầu mỗi vòng, sau khi trạng thái kỹ năng chuyển đổi được chuyển, bạn rút 1 lá (X là giới hạn thể lực của bạn).`,
	olsbfenchao: "Phần Sào",
	olsbfenchao_info: "Kỹ năng giới hạn, giai đoạn kết thúc, bạn có thể khiến một nhân vật nhận các lá bài gây sát thương từ chồng bài bỏ (không quá số người còn sống) và khiến các lá bài này khi gây sát thương đổi thành sát thương lửa.",
	ol_sb_lusu: "OL Mưu Lỗ Túc",
	ol_sb_lusu_prefix: "OL Mưu",
	lusu_phaseZhunbei: "Giai đoạn chuẩn bị",
	lusu_phaseJudge: "Giai đoạn phán xét",
	lusu_phaseDraw: "Giai đoạn rút bài",
	lusu_phaseUse: "Giai đoạn ra bài",
	lusu_phaseDiscard: "Giai đoạn bỏ bài",
	lusu_phaseJieshu: "Giai đoạn kết thúc",
	olsbduduan: "Độc Đoán",
	olsbduduan_info: "Bắt đầu lượt, bạn có thể rút 1 lá, bỏ qua một trong các giai đoạn phán xét, rút bài, ra bài và bỏ bài (mỗi giai đoạn giới hạn một lần), và tráo đổi hai giai đoạn còn lại.",
	olsbyinglve: "Anh Lược",
	olsbyinglve_info: "Giai đoạn ra bài mỗi loại giới hạn một lần, bạn có thể khiến một nhân vật: 1. Mất 1 điểm thể lực, giai đoạn rút bài sau rút thêm 2 lá; 2. Rút 2 lá bài, giai đoạn bỏ bài sau giới hạn bài tay -2.",
	olsbmengshi: "Minh Thế",
	olsbmengshi_info: "Kỹ năng giới hạn, giai đoạn kết thúc, bạn có thể mất X điểm thể lực, sau đó tráo đổi giá trị thể lực của hai nhân vật khác (X là chênh lệch thể lực của cả hai và không thể bằng 0). Cuối mỗi lượt, bạn rút 1 lá và hồi 1 điểm thể lực, cho đến khi một bên trong 'Minh Thế' tử vong.",
	ol_sb_zhugeliang: "OL Mưu Gia Cát Lượng",
	ol_sb_zhugeliang_prefix: "OL Mưu",
	olsbzhitian: "Tri Thiên",
	olsbzhitian_info: "Giai đoạn ra bài, 7 lá trên cùng của chồng bài hiển thị với bạn. Trong kết toán [Hỏa công] của bạn, bạn có thể xem và chọn một trong 7 lá đầu chồng bài để thay thế lá bài bỏ của [Hỏa công].",
	olsbwujing: "Vũ Tĩnh",
	olsbwujing_info: "Kỹ năng khóa, trong lượt của bạn, sau khi có bài không do sử dụng mà vào chồng bài bỏ, lá bài tiếp theo bạn dùng không bị giới hạn số lần; Mỗi lượt lần đầu có bài không phải bài tay vào chồng bài bỏ, bạn rút 1 lá.",
	olsbzhijue: "Trí Tuyệt",
	olsbzhijue_info: "Kỹ năng chuyển đổi, Dương: Giai đoạn ra bài, bạn có thể dùng 1 lá đầu chồng bài như [Hỏa công]; Âm: Đặt một loại màu bài tay vào chồng bài bỏ (mỗi màu mỗi lượt giới hạn một lần), sau đó xem như sử dụng một lá bài Cơ bản hoặc Cẩm nang thường trong đó. Nếu bạn không gây sát thương theo cách này, bạn khiến số bài hiển thị và xem của 〖Tri Thiên〗 -1 (tối thiểu giảm đến 1), sau đó bạn rút 2 lá.",
	ol_madai: "OL Giới Mã Đại",
	ol_madai_prefix: "OL Giới",
	olqianxi: "Tiềm Tập",
	olqianxi_info: "Bắt đầu giai đoạn ra bài, bạn có thể ngửa 1 lá bài, vòng này các nhân vật khác có khoảng cách bằng 1 không thể dùng hoặc đánh ra bài tay cùng màu với lá bài này, và sát thương bạn gây ra bằng lá bài này trong lượt này +1.",
	ol_sb_yl_luzhi: "OL Mưu Lô Thực",
	ol_sb_yl_luzhi_prefix: "OL Mưu",
	olsibing: "Ty Binh",
	olsibing_info: "Mỗi lượt giới hạn một lần. ① Khi bạn dùng bài gây sát thương chỉ định mục tiêu duy nhất, có thể bỏ bất kỳ số lượng bài đỏ để khiến mục tiêu bỏ số bài tay đỏ tương đương, nếu không sẽ không thể đáp trả lá bài đó; ② Sau khi kết toán bài gây sát thương nhắm vào bạn, nếu không gây sát thương cho bạn, bạn có thể bỏ 1 lá đen và xem như sử dụng một lá [Sát].",
	olliance: "Liễm Sách",
	olliance_info: "Mỗi vòng giới hạn một lần, sau khi số bài tay của bạn thay đổi, nếu là ít nhất toàn sân, bạn có thể rút bài đến giới hạn thể lực, sau đó lần tiếp theo có nhân vật gây sát thương trong lượt này, sát thương đó +1.",
	ol_guanzhang: "OL Giới Quan Hưng Trương Bào",
	ol_guanzhang_prefix: "OL Giới",
	olfuhun: "Phụ Hồn",
	olfuhun_info: `Bạn có thể dùng hai lá bài như lá [Sát]. Mục tiêu của lá [Sát] chuyển hóa này chỉ có thể dùng bài tay cùng màu để đáp trả; Sau khi bạn dùng [Sát] gây sát thương trong giai đoạn ra bài, lượt này bạn nhận được ${get.poptip("new_rewusheng")} và ${get.poptip("olpaoxiao")}.`,
	ol_sunxiu: "OL Giới Tôn Hưu",
	ol_sunxiu_prefix: "OL Giới",
	ol_sb_zhangxiu: "OL Mưu Trương Tú",
	ol_sb_zhangxiu_prefix: "OL Mưu",
	olsbchoulie: "Thù Liệp",
	olsbchoulie_info: "Kỹ năng giới hạn, bắt đầu lượt, bạn có thể chọn một nhân vật khác. Vòng này khi bắt đầu mỗi giai đoạn của bạn, bạn có thể bỏ 1 lá bài xem như sử dụng một lá [Sát] lên người đó. Họ có thể bỏ 1 lá Cơ bản hoặc Vũ khí để khiến lá [Sát] này vô hiệu.",
	olsbzhuijiao: "Truy Giảo",
	olsbzhuijiao_info: "Kỹ năng khóa. Khi bạn dùng [Sát], nếu lá bài trước đó bạn dùng không gây sát thương, bạn rút 1 lá và khiến sát thương của [Sát] này +1. Sau kết toán [Sát] này, nếu vẫn không gây sát thương, bạn bỏ 1 lá.",
	ol_sb_zhaoyun: "OL Mưu Triệu Vân",
	ol_sb_zhaoyun_prefix: "OL Mưu",
	olsbnilan: "Nghịch Lạn",
	olsbnilan_info: "Khi bạn không gây sát thương do kỹ năng này, có thể chọn một: 1. Bỏ toàn bộ bài tay, nếu trong đó có [Sát], bạn có thể gây cho nhân vật khác 1 điểm sát thương; 2. Rút 2 lá bài. Nếu làm vậy, lần tới sau khi chịu sát thương bạn có thể thực hiện lựa chọn còn lại.",
	olsbjueya: "Tuyệt Nhai",
	olsbjueya_info: "Khi bạn cần dùng một lá bài Cơ bản mà bạn chưa từng dùng theo cách này, nếu bạn không có bài tay, bạn có thể xem như sử dụng nó.",
	ol_sb_zhangfei: "OL Mưu Trương Phi",
	ol_sb_zhangfei_prefix: "OL Mưu",
	olsbjingxian: "Kính Hiền",
	olsbjingxian_info: "Giai đoạn ra bài mỗi nhân vật giới hạn một lần, bạn có thể đưa cho họ tối đa 2 lá phi cơ bản, sau đó họ chọn số lượng hiệu ứng tương đương: 1. Họ và bạn mỗi người rút 1 lá; 2. Khiến bạn nhận 1 lá [Sát] từ chồng bài.",
	olsbxieyong: "Hiệp Dũng",
	olsbxieyong_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể chọn một nhân vật khác, cho đến khi kết thúc lượt tiếp theo của họ, bạn ở trạng thái [Tửu]. Trong thời gian này sau khi họ dùng một lá bài (mục tiêu không phải bản thân), bạn có thể dùng một lá [Sát] bỏ qua giáp lên họ.",
	ol_liaohua: "OL Giới Liêu Hóa",
	ol_liaohua_prefix: "OL Giới",
	oldangxian: "Đương Tiên",
	oldangxian_info: "Bắt đầu lượt, bạn thực hiện thêm một giai đoạn ra bài. Khi bắt đầu giai đoạn này, bạn có thể nhận một lá [Sát] không giới hạn khoảng cách từ chồng bài hoặc chồng bài bỏ, nếu làm vậy, khi kết thúc giai đoạn này, nếu bạn chưa gây sát thương, bạn tự gây cho mình 1 điểm sát thương.",
	olfuli: "Phục Lịch",
	olfuli_info: "Kỹ năng giới hạn, khi bạn rơi vào trạng thái hấp hối, có thể hồi thể lực đến X, rút bài đến X lá. Nếu số sát thương bạn gây ra trong ván này nhỏ hơn X, bạn lật mặt võ tướng (X là số phe còn sống).",
	ol_sb_huangyueying: "OL Mưu Hoàng Nguyệt Anh",
	ol_sb_huangyueying_prefix: "OL Mưu",
	olsblixian: "Lý Hiền",
	olsblixian_info: "Sau khi bạn chịu sát thương, bạn có thể dùng một lá bài như [Vô trung sinh hữu]. Sau khi bạn đã dùng 3 tên bài Cẩm nang khác nhau theo cách này, kỹ năng này cũng có thể phát động ở giai đoạn kết thúc của bạn.",
	olsbingcai: "Tịnh Cải",
	olsbingcai_info: "Khi lá bài Cơ bản đầu tiên mỗi lượt được sử dụng, bạn có thể trọng chú 1 lá bài. Nếu hai lá đều là loại gây sát thương hoặc đều phi sát thương, lá bài này kết toán thêm một lần. Sau đó nếu lá trọng chú là Cẩm nang, bạn thêm một tên bài cho 〖Lý Hiền〗: [Thuận thủ khiên dương]; [Quá hà chiết kiều]; [Thiết tỏa liên hoàn]. Sau khi thêm đủ các tên bài trên, 〖Lý Hiền〗 cũng có thể phát động ở giai đoạn chuẩn bị của bạn.",
	ol_sb_jushou: "OL Mưu Thư Thụ",
	ol_sb_jushou_prefix: "OL Mưu",
	olsbguliang: "Cố Lương",
	olsbguliang_info: "Mỗi lượt giới hạn một lần, khi nhân vật khác dùng bài lên bạn, bạn có thể khiến lá bài đó vô hiệu với bạn, nếu làm vậy, bạn không thể đáp trả bài họ dùng lên bạn cho đến khi kết thúc lượt.",
	olsbxutu: "Từ Đồ",
	olsbxutu_info: "Kỹ năng khóa, khi bắt đầu trò chơi, bạn đặt 3 lá từ đầu chồng bài lên thẻ võ tướng, gọi là 'Tư'. Mỗi giai đoạn kết thúc, bạn tráo đổi một lá bài trong chồng bài bỏ lượt này với một lá 'Tư', khiến một nhân vật nhận 3 lá 'Tư' có cùng hoa sắc hoặc điểm số, sau đó bổ sung 'Tư' cho đủ 3.",
	ol_lingtong: "OL Giới Lăng Thống",
	ol_lingtong_prefix: "OL Giới",
	olxuanfeng: "Toàn Phong",
	olxuanfeng_info: "Khi bạn mất ít nhất 2 lá bài cùng lúc, hoặc mất bài trong khu trang bị, bạn có thể lần lượt bỏ tổng cộng 2 lá bài của 1 đến 2 nhân vật khác.",
	ol_jianyong: "OL Giới Giản Ung",
	ol_jianyong_prefix: "OL Giới",
	olqiaoshui: "Xảo Thuyết",
	olqiaoshui_info: "Giai đoạn ra bài, bạn có thể đấu điểm với một nhân vật khác. Nếu thắng, lá Cơ bản hoặc Cẩm nang thường tiếp theo bạn dùng trong lượt này có thể tăng hoặc giảm một mục tiêu; Nếu không thắng, kỹ năng này vô hiệu trong lượt này và bạn không thể dùng Cẩm nang trong lượt này.",
	ol_caozhang: "OL Giới Tào Chương",
	ol_caozhang_prefix: "OL Giới",
	oljiangchi: "Tương Trì",
	oljiangchi_info: "Khi kết thúc giai đoạn rút bài, bạn có thể chọn một: ① Rút 1 lá bài, giới hạn số lần dùng [Sát] vòng này -1, và [Sát] không tính vào giới hạn bài tay. ② Trọng chú 1 lá bài, vòng này dùng [Sát] không giới hạn khoảng cách, và giới hạn số lần dùng [Sát] +1.",
	ol_sb_jiangwei: "OL Mưu Khương Duy",
	ol_sb_jiangwei_prefix: "OL Mưu",
	olsbzhuri: "Trục Nhật",
	olsbzhuri_info: "Khi giai đoạn của bạn kết thúc, nếu bạn đã mất bài tay hoặc nhận thêm bài trong giai đoạn này, bạn có thể đấu điểm với một nhân vật. Nếu thắng, bạn có thể sử dụng một trong các lá bài đấu điểm; Nếu không thắng, bạn mất 1 điểm thể lực hoặc khiến kỹ năng này vô hiệu trong lượt này.",
	olsbranji: "Nhiên Kỷ",
	olsbranji_info: `Kỹ năng giới hạn, giai đoạn kết thúc. Nếu số giai đoạn bạn đã dùng bài trong lượt này lớn hơn hoặc bằng / nhỏ hơn hoặc bằng số thể lực, bạn có thể nhận kỹ năng ${get.poptip("kunfenx")}/${get.poptip("zhaxiang")} (nếu thỏa mãn cả hai thì nhận cả hai, 〖Khốn Phấn〗 nhận theo cách này đổi thành kỹ năng thường). Nếu làm vậy, bạn điều chỉnh số bài tay đến giới hạn hoặc hồi thể lực đến giới hạn, sau đó bạn không thể hồi thể lực cho đến khi giết chết nhân vật khác.`,
	kunfenx: "Khốn Phấn",
	kunfenx_info: "Khi bắt đầu giai đoạn kết thúc, bạn có thể mất 1 điểm thể lực, sau đó rút 2 lá bài.",
	ol_sb_guanyu: "OL Mưu Quan Vũ",
	ol_sb_guanyu_prefix: "OL Mưu",
	olsbfumeng: "Phó Mộng",
	olsbfumeng_info: "Bắt đầu mỗi vòng, bạn có thể khiến số lượng bài tay bất kỳ có tên bài được xem là [Sát].",
	olsbguidao: "Quy Đao",
	olsbguidao_info: "Giai đoạn ra bài, bạn có thể trọng chú 2 lá bài và xem như sử dụng một lá [Quyết đấu] (số lá [Sát] trọng chú phải nhiều hơn số lá [Sát] trọng chú của lần phát động 〖Quy Đao〗 trước đó trong lượt này). Khi mục tiêu chịu sát thương từ lá bài này, họ phải đoán số lượng lá bài có tên là [Sát] trên tay bạn nhiều hơn hay số lá không phải [Sát] nhiều hơn, nếu đoán sai, sát thương [Quyết đấu] gây ra +1.",
	ol_sb_taishici: "OL Mưu Thái Sử Từ",
	ol_sb_taishici_prefix: "OL Mưu",
	olsbdulie: "Đốc Liệt",
	olsbdulie_info: "Mỗi lượt giới hạn một lần, khi bạn trở thành mục tiêu duy nhất của một lá Cơ bản hoặc Cẩm nang thường từ nhân vật khác, bạn có thể khiến lá bài này kết toán thêm một lần. Nếu làm vậy, sau khi kết thúc kết toán, bạn rút X lá bài (X là tầm tấn công của bạn và tối đa là 5).",
	olsbdouchan: "Đấu Triền",
	olsbdouchan_info: "Kỹ năng khóa, giai đoạn chuẩn bị, bạn nhận 1 lá [Quyết đấu] từ chồng bài, nếu không có [Quyết đấu], tầm tấn công và giới hạn dùng [Sát] trong giai đoạn ra bài của bạn +1 (số lần tăng không quá số người chơi trong ván).",
	olsbweilin: "Uy Lâm",
	olsbweilin_info: "Mỗi lượt giới hạn một lần, bạn có thể dùng một lá bài như lá [Sát] hoặc [Tửu] bất kỳ, và các lá bài tay cùng màu với lá bài này của mục tiêu trong lượt này đều được xem là [Sát].",
	olsbduoshou: "Đoạt Thủ",
	olsbduoshou_info: "Kỹ năng khóa. ① Lá bài đỏ đầu tiên bạn dùng mỗi lượt không giới hạn khoảng cách. ② Lá bài Cơ bản đầu tiên bạn dùng mỗi lượt không tính vào số lần sử dụng. ③ Sau lần đầu gây sát thương mỗi lượt, bạn rút 1 lá.",
	ol_gaoshun: "OL Giới Cao Thuận",
	ol_gaoshun_prefix: "OL Giới",
	olxianzhen: "Hãm Trận",
	olxianzhen_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể đấu điểm với một nhân vật. Nếu thắng, vòng này bạn bỏ qua giáp của người đó và không giới hạn số lần hay khoảng cách khi dùng bài lên họ, đồng thời khi bạn dùng [Sát] hoặc Cẩm nang thường chỉ định mục tiêu, có thể khiến người đó cũng trở thành mục tiêu; Nếu không thắng, vòng này bạn không thể dùng [Sát] lên họ và lá [Sát] của bạn không tính vào giới hạn bài tay.",
	ol_sb_yuanshao: "OL Mưu Viên Thiệu",
	ol_sb_yuanshao_prefix: "OL Mưu",
	olsbhetao: "Hợp Thảo",
	olsbhetao_info: "Sau khi nhân vật khác dùng bài chỉ định mục tiêu đầu tiên, nếu số mục tiêu lớn hơn 1, bạn có thể bỏ 1 lá cùng màu với lá bài đó và khiến lá bài đó kết toán hai lần lên một trong các mục tiêu.",
	olsbshenli: "Thần Ly",
	olsbshenli_info: "Giai đoạn ra bài giới hạn một lần, sau khi bạn dùng [Sát] chỉ định mục tiêu, có thể khiến tất cả nhân vật có thể trở thành mục tiêu của lá bài này đều trở thành mục tiêu, sau khi kết toán xong, nếu sát thương X bạn gây ra bởi lá bài này: lớn hơn số bài tay, bạn rút X lá (tối đa 5); lớn hơn số thể lực, bạn một lần nữa dùng lá bài này lên tất cả các mục tiêu hợp lệ.",
	olsbyufeng: "Ngọc Phong",
	olsbyufeng_block: "Tư Chiêu Kiếm",
	olsbyufeng_info: `Bắt đầu trò chơi, bạn đặt ${get.poptip("sizhaojian")} vào khu trang bị.`,
	sizhaojian: "Tư Chiêu Kiếm",
	sizhaojian_info: "Khi bạn dùng một lá [Sát] có điểm số chỉ định mục tiêu, bạn khiến mục tiêu chỉ có thể dùng lá [Thiểm] không có điểm hoặc có điểm lớn hơn hoặc bằng lá [Sát] này để đáp trả.",
	ol_yufan: "OL Giới Ương Phiên",
	ol_yufan_prefix: "OL Giới",
	olzongxuan: "Túng Huyền",
	olzongxuan_info: "Khi bạn mất bài do bỏ bài, hoặc nhân vật cửa trên của bạn lần đầu mất bài do bỏ bài mỗi lượt, bạn có thể đặt bất kỳ lá bài nào trong số đó từ chồng bài bỏ lên đầu chồng bài theo thứ tự bất kỳ.",
	olzhiyan: "Trực Ngôn",
	olzhiyan_info: "Giai đoạn kết thúc của bạn hoặc nhân vật cửa trên, bạn có thể khiến một nhân vật ngửa mặt rút 1 lá bài, sau đó nếu lá bài đó: là bài Trang bị, họ sử dụng nó và hồi 1 điểm thể lực; không phải Trang bị và số thể lực không bằng bạn, họ mất 1 điểm thể lực.",
	ol_chengpu: "OL Giới Trình Phổ",
	ol_chengpu_prefix: "OL Giới",
	dclihuo: "Lệ Hỏa",
	dclihuo_info: "① Các lá [Sát] không phải hệ Hỏa bạn dùng có thể đổi thành Hỏa [Sát], nếu làm vậy, sau kết toán nếu gây sát thương, bạn bỏ 1 lá hoặc mất 1 thể lực. ② Bạn dùng Hỏa [Sát] có thể chỉ định thêm một mục tiêu.",
	olchunlao: "Thuần Lạo",
	olchunlao_info: "① Khi lá [Sát] của bạn hoặc nhân vật cửa trên/dưới vào chồng bài bỏ do bị bỏ, bạn đem các lá đó gọi là 'Thuần' đặt lên thẻ võ tướng (tối đa 9). ② Khi một nhân vật hấp hối, bạn có thể đặt X lá 'Thuần' vào chồng bài bỏ, khiến họ xem như dùng một lá [Tửu] (X là số lần bạn đã dùng [Tửu] theo cách này trong vòng này).",
	ol_wangyi: "OL Giới Vương Dị",
	ol_wangyi_prefix: "OL Giới",
	olzhenlie: "Trinh Liệt",
	olzhenlie_info: `Khi bạn trở thành mục tiêu của [Sát] hoặc Cẩm nang thường từ nhân vật khác, bạn có thể mất 1 điểm thể lực khiến lá bài đó vô hiệu với mình, sau đó chọn một: ① Lấy một lá bài của người sử dụng; ② Phát động một lần ${get.poptip("olmiji")} ở giai đoạn kết thúc lượt này.`,
	olmiji: "Bí Kế",
	olmiji_info: "Giai đoạn kết thúc, nếu bạn đã bị thương, có thể rút X lá bài, sau đó có thể chia tối đa X lá bài cho các nhân vật khác (X là số thể lực đã mất).",
	ol_sb_pangtong: "OL Mưu Bàng Thống",
	ol_sb_pangtong_prefix: "OL Mưu",
	olsbhongtu: "Hồng Đồ",
	olsbhongtu_info: `Khi kết thúc giai đoạn của một nhân vật, nếu bạn đã nhận ít nhất 2 lá bài trong giai đoạn này, bạn có thể rút 3 lá, ngửa 3 lá trên tay, khiến một nhân vật khác chọn có sử dụng một lá trong đó hay không và khiến bạn bỏ ngẫu nhiên một lá khác trong đó. Nếu điểm số lá bài được dùng thỏa mãn điều kiện, họ nhận kỹ năng/hiệu ứng sau cho đến hết lượt sau: Lớn nhất duy nhất, nhận ${get.poptip("nzry_feijun")}; Không lớn nhất cũng không nhỏ nhất, nhận ${get.poptip("qianxi")}; Nhỏ nhất duy nhất, giới hạn bài tay +2. Nếu họ không dùng bài theo cách này, bạn và người đó mỗi người chịu 1 điểm sát thương lửa.`,
	olsbqiwu: "Tê Ngô",
	olsbqiwu_info: "Lần đầu chịu sát thương mỗi lượt, nếu nguồn sát thương là bạn hoặc nằm trong tầm tấn công của bạn, bạn có thể bỏ 1 lá đỏ để ngăn chặn sát thương.",
	ol_fazheng: "OL Giới Pháp Chính",
	ol_fazheng_prefix: "OL Giới",
	olxuanhuo: "Huyễn Hoặc",
	olxuanhuo_info: "Khi kết thúc giai đoạn rút bài, bạn có thể đưa cho nhân vật khác 2 lá bài, sau đó họ chọn một: 1. Dùng một lá [Sát] lên một nhân vật khác do bạn chọn, 2. Để bạn xem và lấy 2 lá bài của họ.",
	olenyuan: "Ân Oán",
	olenyuan_info: "① Khi bạn nhận cùng lúc hơn 1 lá bài từ nhân vật khác, có thể khiến họ rút 1 lá. ② Khi bạn chịu 1 điểm sát thương, có thể khiến nguồn sát thương chọn một: 1. Đưa cho bạn 1 lá bài tay đỏ; 2. Mất 1 điểm thể lực.",
	ol_caifuren: "OL Giới Thái Phu Nhân",
	ol_caifuren_prefix: "OL Giới",
	olqieting: "Thiết Thính",
	olqieting_info: "Sau khi lượt của nhân vật khác kết thúc, nếu họ không gây sát thương/dùng bài trong lượt này, bạn có thể chọn một/tối đa hai: 1. Đưa một lá trong khu trang bị của họ vào khu trang bị của bạn; 2. Rút 1 lá bài.",
	ol_liru: "OL Giới Lý Nho",
	ol_liru_prefix: "OL Giới",
	oljuece: "Tuyệt Sách",
	oljuece_info: "Giai đoạn kết thúc, bạn có thể gây 1 điểm sát thương cho một nhân vật có số bài tay không lớn hơn bạn.",
	olmieji: "Diệt Kế",
	olmieji_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể đặt một lá Cẩm nang lên đầu chồng bài, sau đó khiến một nhân vật khác có bài tay phải bỏ 1 lá Cẩm nang hoặc lần lượt bỏ 2 lá bài.",
	ol_liubiao: "OL Giới Lưu Biểu",
	ol_liubiao_prefix: "OL Giới",
	olzishou: "Tự Thủ",
	olzishou_info: "Giai đoạn rút bài, bạn có thể rút thêm X lá, khi kết thúc lượt mà bạn rút bài theo cách này, nếu bạn đã dùng bài gây sát thương, bạn bỏ X lá bài (X là số phe trên sân).",
	olzongshi: "Tông Thất",
	olzongshi_info: "Kỹ năng khóa. ① Giới hạn bài tay của bạn +X (X là số phe trên sân). ② Mỗi phe giới hạn một lần, khi nhân vật khác gây sát thương cho bạn, bạn ngăn chặn sát thương và khiến người đó lấy 1 lá trong khu vực của bạn.",
	ol_wuguotai: "OL Giới Ngô Quốc Thái",
	ol_wuguotai_prefix: "OL Giới",
	olganlu: "Cam Lộ",
	olganlu_info: "Giai đoạn ra bài giới hạn một lần, bạn có thể tráo đổi trang bị của hai nhân vật, sau đó nếu số thể lực đã mất của bạn nhỏ hơn X, bạn bỏ X lá bài (X là chênh lệch số lượng trang bị trước khi tráo).",
	olbuyi: "Bổ Ích",
	olbuyi_info: "Khi một nhân vật hấp hối, bạn có thể ngửa 1 lá bài của họ. Nếu không phải bài Cơ bản, họ bỏ lá đó và hồi 1 điểm thể lực.",
	ol_sb_kongrong: "OL Mưu Khổng Dung",
	ol_sb_kongrong_prefix: "OL Mưu",
	olsbliwen: "Lập Văn",
	olsbliwen_info: "① Khi bắt đầu trò chơi, bạn nhận 3 dấu ấn 'Hiền' (giới hạn dấu ấn 'Hiền' của một nhân vật là 5). ② Sau khi bạn dùng hoặc đánh ra bài, nếu cùng hoa sắc hoặc loại với lá trước đó, bạn nhận 1 dấu ấn 'Hiền'. ③ Kết thúc lượt, bạn lần lượt thực hiện: 1. Có thể chia dấu ấn 'Hiền' cho nhân vật khác; 2. Các nhân vật có dấu ấn theo thứ tự số lượng từ lớn đến nhỏ lần lượt chọn dùng 1 lá bài tay, nếu không dùng sẽ mất toàn bộ dấu ấn và bạn rút số bài tương đương.",
	olsbzhengyi: "Tranh Nghĩa",
	olsbzhengyi_info: "Khi một nhân vật có dấu ấn 'Hiền' chịu sát thương, tất cả những người khác có dấu ấn đồng thời chọn có hủy bỏ sát thương hay không, nếu có người chọn 'Có', sát thương bị hủy, sau đó người có thể lực lớn nhất trong số người chọn 'Có' lần lượt mất X thể lực (X là điểm sát thương).",
	ol_zhangchunhua: "OL Giới Trương Xuân Hoa",
	ol_zhangchunhua_prefix: "OL Giới",
	oljianmie: "Tiễn Diệt",
	oljianmie_info: "Giai đoạn ra bài giới hạn một lần, bạn chọn một nhân vật khác, cả hai đồng thời chọn một màu sắc rồi bỏ bài tay màu đó, nếu bạn/họ bỏ nhiều bài hơn, bạn/họ xem như dùng một lá [Quyết đấu] lên đối phương.",
	ol_caochong: "OL Giới Tào Xung",
	ol_caochong_prefix: "OL Giới",
	olchengxiang: "Xưng Tượng",
	olchengxiang_info: "Sau khi bạn chịu 1 điểm sát thương, có thể lật 4 lá đầu chồng bài, sau đó lấy bất kỳ số lá có tổng điểm không quá 13; nếu tổng đúng bằng 13, lần sau phát động lật thêm 1 lá.",
	olrenxin: "Nhân Tâm",
	olrenxin_info: "Khi một nhân vật khác hấp hối, bạn có thể lật mặt võ tướng và bỏ 1 lá trang bị để hồi cho họ 1 thể lực.",
	ol_sb_sunjian: "OL Mưu Tôn Kiên",
	ol_sb_sunjian_prefix: "OL Mưu",
	olsbhulie: "Hổ Liệt",
	olsbhulie_info: "Mỗi lượt mỗi loại giới hạn một lần, sau khi bạn dùng [Sát] hoặc [Quyết đấu] chỉ định mục tiêu duy nhất, có thể khiến sát thương cơ bản +1. Nếu không gây sát thương, mục tiêu xem như dùng một lá [Sát] lên bạn.",
	olsbyipo: "Nghị Phách",
	olsbyipo_info: "Sau khi thể lực thay đổi, nếu thể lực lớn hơn 0 và là lần đầu đạt đến mức đó, bạn chọn một nhân vật và chọn một: 1. Khiến họ rút X lá rồi bỏ 1 lá; 2. Khiến họ rút 1 lá rồi bỏ X lá (X là thể lực đã mất và ít nhất là 1).",
	ol_sb_yuanshu: "OL Mưu Viên Thuật",
	ol_sb_yuanshu_prefix: "OL Mưu",
	olsbjinming: "Căng Danh",
	olsbjinming_info: "Bắt đầu lượt, có thể chọn một: 1. Hồi 1 thể lực; 2. Bỏ 2 lá bài; 3. Dùng 3 loại bài; 4. Gây 4 điểm sát thương. Kết thúc lượt bạn rút X lá, nếu không thỏa mãn điều kiện đã chọn, xóa tùy chọn đó (X là số thứ tự tùy chọn cuối cùng đã chọn).",
	olsbxiaoshi: "Kiêu Phệ",
	olsbxiaoshi_info: "Giai đoạn ra bài giới hạn một lần, bạn dùng bài có thể chỉ định thêm một mục tiêu (không giới hạn khoảng cách). Sau kết toán, nếu không gây sát thương, bạn mất 1 thể lực hoặc khiến một mục tiêu rút X lá (X là số thứ tự tùy chọn cuối cùng của 〖Căng Danh〗).",
	ol_caozhi: "OL Giới Tào Thực",
	ol_caozhi_prefix: "OL Giới",
	oljiushi: "Tửu Thi",
	oljiushi_info: "① Khi cần dùng [Tửu], nếu võ tướng đang ngửa, có thể lật mặt xem như dùng 1 lá [Tửu]. ② Sau khi chịu sát thương nếu võ tướng đang úp, hoặc sau khi nhận đủ X lá bài từ 〖Lạc Anh〗 (X là giới hạn thể lực) khi võ tướng đang úp, bạn có thể lật mặt lại. ③ Nếu võ tướng đang úp, bài nhận từ 〖Lạc Anh〗 không giới hạn khoảng cách và không thể đáp trả.",
	ol_sb_huaxiong: "OL Mưu Hoa Hùng",
	ol_sb_huaxiong_prefix: "OL Mưu",
	olsbbojue: "Bác Quyết",
	olsbbojue_info: "Giai đoạn ra bài giới hạn hai lần, chọn nhân vật khác, cả hai cùng chọn rút 1 lá hoặc bỏ 1 lá, sau đó nếu chênh lệch tổng bài tay là: 0, hai bên lần lượt bỏ 1 lá của đối phương; 2, hai bên lần lượt xem như dùng [Sát] lên đối phương.",
	olsbyangwei: "Dương Uy",
	olsbyangwei_info: "Kỹ năng khóa. Khi bạn rút/bỏ lá bài thứ hai trong lượt này ngoài giai đoạn rút/bỏ bài, lần tới gây/chịu sát thương sẽ +1.",
	ol_sb_dongzhuo: "OL Mưu Đổng Trác",
	ol_sb_dongzhuo_prefix: "OL Mưu",
	olguanbian: "Quan Biến",
	olguanbian_info: "Kỹ năng khóa. ① Bắt đầu trò chơi, giới hạn bài tay, khoảng cách người khác tính đến bạn và bạn tính đến người khác đều +X (X là số người chơi). ② Kết thúc vòng đầu hoặc sau khi phát động 〖Hung Nghịch〗 hoặc 〖Phong Thưởng〗, bạn mất 〖Quan Biến〗.",
	olxiongni: "Hung Nghịch",
	olxiongni_info: "Bắt đầu giai đoạn ra bài, bạn có thể bỏ 1 lá, sau đó tất cả những người khác chọn: 1. Bỏ 1 lá cùng hoa sắc; 2. Chịu 1 điểm sát thương từ bạn.",
	olfengshang: "Phong Thưởng",
	olfengshang_info: "Giai đoạn ra bài giới hạn một lần hoặc khi có nhân vật hấp hối (mỗi lượt một lần), bạn có thể chia 2 lá cùng hoa sắc trong chồng bài bỏ lượt này cho số người tương đương. Nếu không nhận bài theo cách này, xem như dùng 1 lá [Tửu] không tính vào số lần.",
	olzhibin: "Chấp Bính",
	olzhibin_info: `Kỹ năng Chủ công, Kỹ năng khóa. Giai đoạn chuẩn bị, nếu các nhân vật phe Quần khác đã dùng tổng cộng bài đen đạt: 3 lá, bạn +1 giới hạn thể lực và hồi 1 thể lực; 6 lá, bạn nhận 〖Phần Thành〗; 9 lá, bạn nhận 〖Băng Hoại〗.`,
	ol_sb_dengai: "OL Mưu Đặng Ngải",
	ol_sb_dengai_prefix: "OL Mưu",
	olsbjigu: "Tích Cốc",
	olsbjigu_info: "Kỹ năng khóa. Sau khi bài nhân vật khác dùng ngoài lượt của họ vào chồng bài bỏ, nếu số 'Cốc' nhỏ hơn thể lực giới hạn, bạn đặt các lá không phải Cơ (♥) lên thẻ võ tướng, gọi là 'Cốc'. Khi bắt đầu lượt của nhân vật có giới hạn thể lực bằng bạn, có thể dùng bài tay tráo đổi số 'Cốc' tương đương.",
	olsbjiewan: "Giải Oản",
	olsbjiewan_info: "① Mỗi giai đoạn chuẩn bị, có thể giảm 1 giới hạn thể lực hoặc bỏ 2 'Cốc' để dùng 1 lá bài tay như [Thuận thủ khiên dương] với khoảng cách X (X là số 'Cốc' và ít nhất là 1). ② Mỗi giai đoạn kết thúc, nếu số bài tay bằng số 'Cốc' và giới hạn thể lực của bạn không phải cao nhất duy nhất, bạn +1 giới hạn thể lực.",
	ol_sb_gongsunzan: "OL Mưu Công Tôn Toản",
	ol_sb_gongsunzan_prefix: "OL Mưu",
	olsbjiaodi: "Tiễu Địch",
	olsbjiaodi_info: "Kỹ năng khóa. ① Tầm tấn công được xem là số thể lực của bạn. ② Khi dùng [Sát] chỉ định mục tiêu duy nhất, nếu tầm tấn công của họ: nhỏ hơn hoặc bằng bạn, sát thương +1 và lấy 1 lá bài tay của họ; lớn hơn hoặc bằng bạn, bỏ 1 lá trong khu vực của họ và chọn thêm 1 mục tiêu bổ sung cho lá [Sát] này.",
	olsbbaojing: "Bảo Kinh",
	olsbbaojing_info: "Giai đoạn ra bài giới hạn một lần, có thể khiến tầm tấn công của nhân vật khác +1 hoặc -1 (tối thiểu là 1) cho đến khi bắt đầu giai đoạn ra bài tiếp theo của bạn.",
	ol_guohuai: "OL Giới Quách Hoài",
	ol_guohuai_prefix: "OL Giới",
	oljingce: "Tinh Sách",
	oljingce_info: "Lần đầu dùng bài tay một hoa sắc trong lượt, giới hạn bài tay +1. Khi kết thúc giai đoạn ra bài của một nhân vật, bạn có thể rút X lá bài (X là số loại bài bạn đã dùng trong giai đoạn này).",
	ol_fuhuanghou: "OL Giới Phục Thọ",
	ol_fuhuanghou_prefix: "OL Giới",
	olqiuyuan: "Cầu Viện",
	olqiuyuan_info: "Khi trở thành mục tiêu của [Sát] hoặc Cẩm nang gây sát thương, có thể khiến nhân vật khác chọn: 1. Đưa cho bạn 1 lá cùng loại nhưng khác tên; 2. Trở thành mục tiêu bổ sung của lá bài đó.",
	ol_sb_zhangrang: "OL Mưu Trương Nhượng",
	ol_sb_zhangrang_prefix: "OL Mưu",
	olsblucun: "Lộ Tồn",
	olsblucun_info: "① Mỗi vòng mỗi loại giới hạn một lần, bạn xem như dùng một lá bài Cơ bản hoặc Cẩm nang thường có mục tiêu chưa từng dùng theo cách này, sau đó một nhân vật ngẫu nhiên có nhiều bài tay nhất trong các mục tiêu đặt 1 lá bài tay lên thẻ võ tướng của bạn, gọi là 'Lộ'. ② Mỗi giai đoạn kết thúc, bỏ ngẫu nhiên 1 'Lộ' rồi rút 1 lá.",
	olsbtuisheng: "Thuế Sinh",
	olsbtuisheng_info: `Kỹ năng giới hạn, giai đoạn chuẩn bị hoặc khi hấp hối, có thể đặt lại các tên bài đã dùng bởi 〖Lộ Tồn〗, sau đó chọn một và hồi 1 thể lực: ① Đặt toàn bộ bài tay lên thẻ võ tướng làm 'Lộ'; ② Nhận ngẫu nhiên từ chồng bài bỏ số lá bài bằng số vòng đấu có tên nằm trong danh sách đã dùng của 'Lộ Tồn'.`,
	ol_sb_wenchou: "OL Mưu Văn Xú",
	ol_sb_wenchou_prefix: "OL Mưu",
	olsblunzhan: "Luân Chiến",
	olsblunzhan_info: "Giai đoạn ra bài, dùng số lượng bài bất kỳ (tối đa 5 và không trùng số lượng đã dùng trước đó trong lượt) như lá [Quyết đấu]. Nếu gây sát thương cho mục tiêu duy nhất, rút X lá và không thể phát động lên người đó nữa trong lượt này (X là số lần bạn đã dùng bài nhắm vào người đó lượt này).",
	olsbjuejue: "Quyết Tuyệt",
	olsbjuejue_info: "Kỹ năng khóa, khi lần đầu trong lượt chỉ dùng toàn bộ bài tay nhắm vào duy nhất một người, bạn khiến họ bỏ X lá bài (X là số lần bạn đã dùng bài nhắm vào họ lượt này).",
	ol_sb_jiaxu: "OL Mưu Giả Hủ",
	ol_sb_jiaxu_prefix: "OL Mưu",
	olsbwance: "Hoàn Sách",
	olsbwance_info: "Giai đoạn ra bài giới hạn một lần, chọn nhân vật có bài tay và một tên Cẩm nang thường đơn mục tiêu, người đó lần lượt dùng X lá bài tay như lá Cẩm nang đó (X là số vòng đấu, tối đa 3). Khi họ dùng bài theo cách này, bạn có thể bỏ 1 lá bài để sửa đổi mục tiêu của lá bài đó.",
	olsbchenzhi: "Trầm Trí",
	olsbchenzhi_info: "① Khi chịu sát thương, nếu vòng này đã chịu X lần sát thương, thì ngăn chặn nó (X là số vòng đấu, tối đa 3). ② Mỗi ván giới hạn một lần, kết thúc mỗi vòng, nếu chưa phát động hiệu ứng ①, có thể khôi phục một kỹ năng giới hạn của một nhân vật.",
	olsbluanchao: "Loạn Triều",
	olsbluanchao_info: "Kỹ năng giới hạn, bắt đầu mỗi vòng, có thể khiến tất cả nhân vật lần lượt chọn nhận 1 lá [Sát] hoặc [Thiểm] từ chồng bài. Người chọn [Sát] sẽ được +1 sát thương cho lần gây sát thương đầu tiên trong vòng này.",
	ol_jsrg_zhaoyun: "Thiểm Triệu Vân",
	ol_jsrg_zhaoyun_prefix: "Thiểm",
	ollonglin: "Long Lâm",
	ollonglin_info: "Sau khi nhân vật khác lần đầu dùng [Sát] trong giai đoạn ra bài của họ, bạn có thể bỏ 1 lá khiến [Sát] vô hiệu, sau đó họ có thể xem như dùng 1 [Quyết đấu] lên bạn, nếu bạn gây sát thương theo cách này, lá bài tiếp theo họ dùng không thể nhắm vào người khác.",
	olzhendan: "Trấn Đảm",
	olzhendan_info: "① Dùng 1 lá phi cơ bản trên tay như lá bài Cơ bản bất kỳ chưa dùng trong vòng này. ② Sau khi chịu sát thương hoặc kết thúc mỗi vòng, rút X lá bài và kỹ năng vô hiệu trong vòng này (X là số lượt các nhân vật đã thực hiện trong vòng này, tối đa 5).",
	ol_jsrg_liuhong: "Thiểm Lưu Hoành",
	ol_jsrg_liuhong_prefix: "Thiểm",
	olchaozheng: "Triều Tranh",
	olchaozheng_info: "① Giai đoạn chuẩn bị, có thể nghị sự với tất cả người khác. Nếu kết quả là: Đỏ, những người chọn Đỏ hồi 1 thể lực; Đen, những người khác chọn Đỏ mất 1 thể lực. Sau đó bạn rút X lá (X là số người cùng ý kiến với bạn, tối đa 2). ② Khi nghị sự, trọng số ý kiến của bạn +1.",
	olshenchong: "Thậm Sủng",
	olshenchong_info: `Kỹ năng giới hạn. Giai đoạn chuẩn bị, có thể khiến nhân vật khác nhận 〖Phi Dương〗 và 〖Bạt Hổ〗. Nếu làm vậy, khi bạn chết, kẻ giết bạn bỏ toàn bộ bài tay và mất sạch kỹ năng.`,
	oljulian: "Tụ Liễm",
	oljulian_info: "Kỹ năng Chủ công. ① Phe Quần khác mỗi lượt giới hạn một lần, khi nhận bài không phải trong giai đoạn rút bài và không do 〖Tụ Liễm〗, có thể rút thêm 1 lá. ② Giai đoạn kết thúc, bạn có thể lấy mỗi người phe Quần khác 1 lá bài.",
	dm_simayi: "Ma Tư Mã Ý",
	dm_simayi_prefix: "Ma",
	olguifu: "Quỷ Phục",
	olguifu_info: "① Mỗi vòng bắt đầu hoặc sau khi chịu sát thương/mất thể lực/hồi thể lực, nhận ngẫu nhiên 1 lá [Thiểm] không tính vào giới hạn bài tay. ② Ghi lại tên bài/kỹ năng trực tiếp gây sát thương trong ván. ③ Mỗi lượt mỗi tên bài giới hạn một lần, dùng [Thiểm] từ kỹ năng này như các tên bài đã ghi lại.",
	olmoubian: "Mưu Biến",
	olmoubian_info: `Giai đoạn chuẩn bị, nếu tổng tên bài và kỹ năng đã ghi lại ≥ 3, có thể ${get.poptip("rule_rumo")}, nhận toàn bộ kỹ năng đã ghi và nhận 〖Sậu Kích〗.`,
	olzhouxi: "Sậu Kích",
	olzhouxi_info: "① Giai đoạn chuẩn bị, chọn 1 trong 3 kỹ năng gây sát thương để nhận cho đến lượt sau. ② Nhân vật chịu sát thương từ bạn vòng này khi kết thúc vòng xem như dùng 1 [Sát] lên bạn.",
	olrumo: "Nhập Ma",
	olrumo_info: "Mỗi ván giới hạn một lần, khi đủ điều kiện có thể Nhập Ma. Sau đó cuối mỗi vòng nếu chưa gây sát thương, bạn mất 1 thể lực.",
	ol_sb_xiaoqiao: "OL Mưu Tiểu Kiều",
	ol_sb_xiaoqiao_prefix: "OL Mưu",
	olmiluo: "Mê Lạc",
	olmiluo_info: "Giai đoạn ra bài giới hạn một lần, ngửa và đưa cho tối đa 2 người mỗi người 1 lá, gọi là bài 'Mê Lạc'. Cuối mỗi vòng, khiến 1 người không có/có bài 'Mê Lạc' mất/hồi 1 thể lực.",
	oljueyan: "Tuyệt Nhan",
	oljueyan_info: "Mỗi vòng mỗi loại giới hạn một lần, khi cần dùng Cẩm nang thường hoặc Cơ bản đỏ từ tay, có thể ngửa mặt xem như sử dụng; lần đầu ngửa một hoa sắc mỗi vòng được rút 1 lá.",
	ol_guohuanghou: "OL Giới Quách Hoàng Hậu",
	ol_guohuanghou_prefix: "OL Giới",
	oljiaozhao: "Kiểu Chiếu",
	oljiaozhao_info: "Giai đoạn ra bài giới hạn một lần, dùng 1 lá bài như lá Cơ bản hoặc Cẩm nang thường chưa ai dùng trong vòng này.",
	oldanxin: "Đạn Tâm",
	oldanxin_info: `Sau khi chịu sát thương, rút X lá và nâng cấp 〖Kiểu Chiếu〗 (X là số lần nâng cấp).`,
	ol_sunluban: "OL Giới Tôn Lỗ Ban",
	ol_sunluban_prefix: "OL Giới",
	olzenhui: "Sàm Hủy",
	olzenhui_info: "Giai đoạn ra bài giới hạn một lần, khi dùng [Sát] hoặc Cẩm nang thường (trừ loại chỉ định mục tiêu như [Tá đao sát nhân]), có thể khiến 1 mục tiêu hợp lệ chọn: 1. Đưa bạn 1 lá và thay bạn làm người sử dụng; 2. Trở thành mục tiêu bổ sung.",
	oljiaojin: "Kiêu Căng",
	oljiaojin_info: "Khi chịu sát thương, bỏ 1 lá Cẩm nang phi sát thương hoặc Trang bị để ngăn chặn và lấy lá bài gây sát thương đó.",
	dm_diaochan: "Ma Điêu Thuyền",
	dm_diaochan_prefix: "Ma",
	olhuanhuo: "Huyễn Hoặc",
	olhuanhuo_info: "Đầu mỗi vòng rút 2 lá, bỏ tối đa 2 lá và chọn số người tương đương. Lượt sau của họ bắt buộc chọn 1 lá tay hợp lệ để dùng (không thể dùng kỹ năng chủ động), sau mỗi lá dùng phải bỏ ngẫu nhiên 1 lá cho đến khi dùng đủ 2 lá.",
	olqingshi: "Khuynh Thế",
	olqingshi_info: `Giai đoạn chuẩn bị, có thể ${get.poptip("rule_rumo")}, khiến mọi người nhận 1 lá Cẩm nang sát thương đơn mục tiêu. Khi họ dùng nhắm vào người khác, bạn có thể bỏ 1 lá để đổi mục tiêu. Các lá này gây sát thương giúp bạn rút 1 lá, nếu không dùng mà vào chồng bỏ thì bạn lấy chúng.`,
	dm_lvbu: "Ma Lã Bố",
	dm_lvbu_prefix: "Ma",
	olduoqi: "Đoạt Khí",
	olduoqi_info: "Kỹ năng khóa. ① Bài tay khởi đầu của mọi người gọi là 'Khí'. ② Trước lượt đầu của vị trí số 1, bạn thực hiện một giai đoạn ra bài không thể dùng Cẩm nang trì hoãn. ③ Mỗi lượt lần đầu gây sát thương cho ai, bạn lấy 1 lá 'Khí' của họ từ mọi khu vực.",
	olkuangmo: "Cuồng Ma",
	olkuangmo_info: `Giai đoạn ra bài, có thể ${get.poptip("rule_rumo")}, chọn 1 người cùng trở thành nhân vật 'Cuồng', sát thương lần đầu gây cho nhau mỗi lượt +1; giết đối phương lấy hết 'Khí'. Nếu đối phương chết, bạn chọn lại.`,
	olgangquan: "Cương Quyền",
	olgangquan_info: "Nếu lá bài trước đó dùng là 'Khí', có thể dùng Trang bị như Hỏa [Sát] nhắm vào người lân cận; nếu không, dùng Cẩm nang như [Quyết đấu].",
	ol_jsrg_zhangliao: "Thiểm Trương Liêu",
	ol_jsrg_zhangliao_prefix: "Thiểm",
	olzhengbing: "Chỉnh Binh",
	olzhengbing_info: "Kỹ năng phe Quần. Giai đoạn ra bài giới hạn 3 lần. Trọng chú 1 lá bài: [Sát] thì giới hạn bài tay +1; [Thiểm] thì rút 1 lá; [Đào]/[Tửu] thì cuối lượt thực hiện thêm 1 giai đoạn ra bài. Nếu kích hoạt đủ các mục, đổi phe sang Ngụy.",
	dm_caocao: "OL Ma Tào Tháo",
	dm_caocao_prefix: "OL|Ma",
	olbachao: "Bá Triều",
	olbachao_info: `Bắt đầu giai đoạn ra bài, khiến mọi người chọn có đưa bạn 1 lá không, sau đó gây 1 sát thương cho người không đưa bài phi cơ bản; nếu người đó là bạn, vòng này dùng bài tay không giới hạn khoảng cách/số lần và ${get.poptip("rule_rumo")}.`,
	olfuzai: "Phúc Tải",
	olfuzai_info: "Kỹ năng khóa, ① Trang bị của bạn chỉ có thể dùng như [Tá đao sát nhân] hoặc [Vô trung sinh hữu]. ② Nếu khu trang bị trống, xem như đang trang bị Vũ khí và Giáp ngẫu nhiên (ưu tiên loại có tầm đánh/tên bài trùng số thể lực).",
};

export default translates;
